pub const ClusterIssueCode = enum {
    access_denied,
    cluster_unreachable,
    configuration_conflict,
    internal_failure,
    resource_limit_exceeded,
    resource_not_found,
    iam_role_not_found,
    vpc_not_found,
    insufficient_free_addresses,
    ec2_service_not_subscribed,
    ec2_subnet_not_found,
    ec2_security_group_not_found,
    kms_grant_revoked,
    kms_key_not_found,
    kms_key_marked_for_deletion,
    kms_key_disabled,
    sts_regional_endpoint_disabled,
    unsupported_version,
    other,

    pub const json_field_names = .{
        .access_denied = "ACCESS_DENIED",
        .cluster_unreachable = "CLUSTER_UNREACHABLE",
        .configuration_conflict = "CONFIGURATION_CONFLICT",
        .internal_failure = "INTERNAL_FAILURE",
        .resource_limit_exceeded = "RESOURCE_LIMIT_EXCEEDED",
        .resource_not_found = "RESOURCE_NOT_FOUND",
        .iam_role_not_found = "IAM_ROLE_NOT_FOUND",
        .vpc_not_found = "VPC_NOT_FOUND",
        .insufficient_free_addresses = "INSUFFICIENT_FREE_ADDRESSES",
        .ec2_service_not_subscribed = "EC2_SERVICE_NOT_SUBSCRIBED",
        .ec2_subnet_not_found = "EC2_SUBNET_NOT_FOUND",
        .ec2_security_group_not_found = "EC2_SECURITY_GROUP_NOT_FOUND",
        .kms_grant_revoked = "KMS_GRANT_REVOKED",
        .kms_key_not_found = "KMS_KEY_NOT_FOUND",
        .kms_key_marked_for_deletion = "KMS_KEY_MARKED_FOR_DELETION",
        .kms_key_disabled = "KMS_KEY_DISABLED",
        .sts_regional_endpoint_disabled = "STS_REGIONAL_ENDPOINT_DISABLED",
        .unsupported_version = "UNSUPPORTED_VERSION",
        .other = "OTHER",
    };
};
