pub const ErrorCode = enum {
    subnet_not_found,
    security_group_not_found,
    eni_limit_reached,
    ip_not_available,
    access_denied,
    operation_not_permitted,
    vpc_id_not_found,
    unknown,
    node_creation_failure,
    pod_eviction_failure,
    insufficient_free_addresses,
    cluster_unreachable,
    insufficient_number_of_replicas,
    configuration_conflict,
    admission_request_denied,
    unsupported_addon_modification,
    k8_s_resource_not_found,

    pub const json_field_names = .{
        .subnet_not_found = "SUBNET_NOT_FOUND",
        .security_group_not_found = "SECURITY_GROUP_NOT_FOUND",
        .eni_limit_reached = "ENI_LIMIT_REACHED",
        .ip_not_available = "IP_NOT_AVAILABLE",
        .access_denied = "ACCESS_DENIED",
        .operation_not_permitted = "OPERATION_NOT_PERMITTED",
        .vpc_id_not_found = "VPC_ID_NOT_FOUND",
        .unknown = "UNKNOWN",
        .node_creation_failure = "NODE_CREATION_FAILURE",
        .pod_eviction_failure = "POD_EVICTION_FAILURE",
        .insufficient_free_addresses = "INSUFFICIENT_FREE_ADDRESSES",
        .cluster_unreachable = "CLUSTER_UNREACHABLE",
        .insufficient_number_of_replicas = "INSUFFICIENT_NUMBER_OF_REPLICAS",
        .configuration_conflict = "CONFIGURATION_CONFLICT",
        .admission_request_denied = "ADMISSION_REQUEST_DENIED",
        .unsupported_addon_modification = "UNSUPPORTED_ADDON_MODIFICATION",
        .k8_s_resource_not_found = "K8S_RESOURCE_NOT_FOUND",
    };
};
