const std = @import("std");

pub const NodegroupIssueCode = enum {
    auto_scaling_group_not_found,
    auto_scaling_group_invalid_configuration,
    ec2_security_group_not_found,
    ec2_security_group_deletion_failure,
    ec2_launch_template_not_found,
    ec2_launch_template_version_mismatch,
    ec2_subnet_not_found,
    ec2_subnet_invalid_configuration,
    iam_instance_profile_not_found,
    ec2_subnet_missing_ipv6_assignment,
    iam_limit_exceeded,
    iam_node_role_not_found,
    node_creation_failure,
    asg_instance_launch_failures,
    instance_limit_exceeded,
    insufficient_free_addresses,
    access_denied,
    internal_failure,
    cluster_unreachable,
    ami_id_not_found,
    auto_scaling_group_opt_in_required,
    auto_scaling_group_rate_limit_exceeded,
    ec2_launch_template_deletion_failure,
    ec2_launch_template_invalid_configuration,
    ec2_launch_template_max_limit_exceeded,
    ec2_subnet_list_too_long,
    iam_throttling,
    node_termination_failure,
    pod_eviction_failure,
    source_ec2_launch_template_not_found,
    limit_exceeded,
    unknown,
    auto_scaling_group_instance_refresh_active,
    kubernetes_label_invalid,
    ec2_launch_template_version_max_limit_exceeded,
    ec2_instance_type_does_not_exist,

    pub const json_field_names = .{
        .auto_scaling_group_not_found = "AutoScalingGroupNotFound",
        .auto_scaling_group_invalid_configuration = "AutoScalingGroupInvalidConfiguration",
        .ec2_security_group_not_found = "Ec2SecurityGroupNotFound",
        .ec2_security_group_deletion_failure = "Ec2SecurityGroupDeletionFailure",
        .ec2_launch_template_not_found = "Ec2LaunchTemplateNotFound",
        .ec2_launch_template_version_mismatch = "Ec2LaunchTemplateVersionMismatch",
        .ec2_subnet_not_found = "Ec2SubnetNotFound",
        .ec2_subnet_invalid_configuration = "Ec2SubnetInvalidConfiguration",
        .iam_instance_profile_not_found = "IamInstanceProfileNotFound",
        .ec2_subnet_missing_ipv6_assignment = "Ec2SubnetMissingIpv6Assignment",
        .iam_limit_exceeded = "IamLimitExceeded",
        .iam_node_role_not_found = "IamNodeRoleNotFound",
        .node_creation_failure = "NodeCreationFailure",
        .asg_instance_launch_failures = "AsgInstanceLaunchFailures",
        .instance_limit_exceeded = "InstanceLimitExceeded",
        .insufficient_free_addresses = "InsufficientFreeAddresses",
        .access_denied = "AccessDenied",
        .internal_failure = "InternalFailure",
        .cluster_unreachable = "ClusterUnreachable",
        .ami_id_not_found = "AmiIdNotFound",
        .auto_scaling_group_opt_in_required = "AutoScalingGroupOptInRequired",
        .auto_scaling_group_rate_limit_exceeded = "AutoScalingGroupRateLimitExceeded",
        .ec2_launch_template_deletion_failure = "Ec2LaunchTemplateDeletionFailure",
        .ec2_launch_template_invalid_configuration = "Ec2LaunchTemplateInvalidConfiguration",
        .ec2_launch_template_max_limit_exceeded = "Ec2LaunchTemplateMaxLimitExceeded",
        .ec2_subnet_list_too_long = "Ec2SubnetListTooLong",
        .iam_throttling = "IamThrottling",
        .node_termination_failure = "NodeTerminationFailure",
        .pod_eviction_failure = "PodEvictionFailure",
        .source_ec2_launch_template_not_found = "SourceEc2LaunchTemplateNotFound",
        .limit_exceeded = "LimitExceeded",
        .unknown = "Unknown",
        .auto_scaling_group_instance_refresh_active = "AutoScalingGroupInstanceRefreshActive",
        .kubernetes_label_invalid = "KubernetesLabelInvalid",
        .ec2_launch_template_version_max_limit_exceeded = "Ec2LaunchTemplateVersionMaxLimitExceeded",
        .ec2_instance_type_does_not_exist = "Ec2InstanceTypeDoesNotExist",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .auto_scaling_group_not_found => "AutoScalingGroupNotFound",
            .auto_scaling_group_invalid_configuration => "AutoScalingGroupInvalidConfiguration",
            .ec2_security_group_not_found => "Ec2SecurityGroupNotFound",
            .ec2_security_group_deletion_failure => "Ec2SecurityGroupDeletionFailure",
            .ec2_launch_template_not_found => "Ec2LaunchTemplateNotFound",
            .ec2_launch_template_version_mismatch => "Ec2LaunchTemplateVersionMismatch",
            .ec2_subnet_not_found => "Ec2SubnetNotFound",
            .ec2_subnet_invalid_configuration => "Ec2SubnetInvalidConfiguration",
            .iam_instance_profile_not_found => "IamInstanceProfileNotFound",
            .ec2_subnet_missing_ipv6_assignment => "Ec2SubnetMissingIpv6Assignment",
            .iam_limit_exceeded => "IamLimitExceeded",
            .iam_node_role_not_found => "IamNodeRoleNotFound",
            .node_creation_failure => "NodeCreationFailure",
            .asg_instance_launch_failures => "AsgInstanceLaunchFailures",
            .instance_limit_exceeded => "InstanceLimitExceeded",
            .insufficient_free_addresses => "InsufficientFreeAddresses",
            .access_denied => "AccessDenied",
            .internal_failure => "InternalFailure",
            .cluster_unreachable => "ClusterUnreachable",
            .ami_id_not_found => "AmiIdNotFound",
            .auto_scaling_group_opt_in_required => "AutoScalingGroupOptInRequired",
            .auto_scaling_group_rate_limit_exceeded => "AutoScalingGroupRateLimitExceeded",
            .ec2_launch_template_deletion_failure => "Ec2LaunchTemplateDeletionFailure",
            .ec2_launch_template_invalid_configuration => "Ec2LaunchTemplateInvalidConfiguration",
            .ec2_launch_template_max_limit_exceeded => "Ec2LaunchTemplateMaxLimitExceeded",
            .ec2_subnet_list_too_long => "Ec2SubnetListTooLong",
            .iam_throttling => "IamThrottling",
            .node_termination_failure => "NodeTerminationFailure",
            .pod_eviction_failure => "PodEvictionFailure",
            .source_ec2_launch_template_not_found => "SourceEc2LaunchTemplateNotFound",
            .limit_exceeded => "LimitExceeded",
            .unknown => "Unknown",
            .auto_scaling_group_instance_refresh_active => "AutoScalingGroupInstanceRefreshActive",
            .kubernetes_label_invalid => "KubernetesLabelInvalid",
            .ec2_launch_template_version_max_limit_exceeded => "Ec2LaunchTemplateVersionMaxLimitExceeded",
            .ec2_instance_type_does_not_exist => "Ec2InstanceTypeDoesNotExist",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
