pub const NodegroupIssueCode = enum {
    auto_scaling_group_not_found,
    auto_scaling_group_invalid_configuration,
    ec2_security_group_not_found,
    ec2_security_group_deletion_failure,
    ec2_launch_template_not_found,
    ec2_launch_template_version_mismatch,
    ec2_subnet_not_found,
    ec2_subnet_invalid_configuration,
    iam_instance_profile_not_found,
    ec2_subnet_missing_ipv6_assignment,
    iam_limit_exceeded,
    iam_node_role_not_found,
    node_creation_failure,
    asg_instance_launch_failures,
    instance_limit_exceeded,
    insufficient_free_addresses,
    access_denied,
    internal_failure,
    cluster_unreachable,
    ami_id_not_found,
    auto_scaling_group_opt_in_required,
    auto_scaling_group_rate_limit_exceeded,
    ec2_launch_template_deletion_failure,
    ec2_launch_template_invalid_configuration,
    ec2_launch_template_max_limit_exceeded,
    ec2_subnet_list_too_long,
    iam_throttling,
    node_termination_failure,
    pod_eviction_failure,
    source_ec2_launch_template_not_found,
    limit_exceeded,
    unknown,
    auto_scaling_group_instance_refresh_active,
    kubernetes_label_invalid,
    ec2_launch_template_version_max_limit_exceeded,
    ec2_instance_type_does_not_exist,

    pub const json_field_names = .{
        .auto_scaling_group_not_found = "AUTO_SCALING_GROUP_NOT_FOUND",
        .auto_scaling_group_invalid_configuration = "AUTO_SCALING_GROUP_INVALID_CONFIGURATION",
        .ec2_security_group_not_found = "EC2_SECURITY_GROUP_NOT_FOUND",
        .ec2_security_group_deletion_failure = "EC2_SECURITY_GROUP_DELETION_FAILURE",
        .ec2_launch_template_not_found = "EC2_LAUNCH_TEMPLATE_NOT_FOUND",
        .ec2_launch_template_version_mismatch = "EC2_LAUNCH_TEMPLATE_VERSION_MISMATCH",
        .ec2_subnet_not_found = "EC2_SUBNET_NOT_FOUND",
        .ec2_subnet_invalid_configuration = "EC2_SUBNET_INVALID_CONFIGURATION",
        .iam_instance_profile_not_found = "IAM_INSTANCE_PROFILE_NOT_FOUND",
        .ec2_subnet_missing_ipv6_assignment = "EC2_SUBNET_MISSING_IPV6_ASSIGNMENT",
        .iam_limit_exceeded = "IAM_LIMIT_EXCEEDED",
        .iam_node_role_not_found = "IAM_NODE_ROLE_NOT_FOUND",
        .node_creation_failure = "NODE_CREATION_FAILURE",
        .asg_instance_launch_failures = "ASG_INSTANCE_LAUNCH_FAILURES",
        .instance_limit_exceeded = "INSTANCE_LIMIT_EXCEEDED",
        .insufficient_free_addresses = "INSUFFICIENT_FREE_ADDRESSES",
        .access_denied = "ACCESS_DENIED",
        .internal_failure = "INTERNAL_FAILURE",
        .cluster_unreachable = "CLUSTER_UNREACHABLE",
        .ami_id_not_found = "AMI_ID_NOT_FOUND",
        .auto_scaling_group_opt_in_required = "AUTO_SCALING_GROUP_OPT_IN_REQUIRED",
        .auto_scaling_group_rate_limit_exceeded = "AUTO_SCALING_GROUP_RATE_LIMIT_EXCEEDED",
        .ec2_launch_template_deletion_failure = "EC2_LAUNCH_TEMPLATE_DELETION_FAILURE",
        .ec2_launch_template_invalid_configuration = "EC2_LAUNCH_TEMPLATE_INVALID_CONFIGURATION",
        .ec2_launch_template_max_limit_exceeded = "EC2_LAUNCH_TEMPLATE_MAX_LIMIT_EXCEEDED",
        .ec2_subnet_list_too_long = "EC2_SUBNET_LIST_TOO_LONG",
        .iam_throttling = "IAM_THROTTLING",
        .node_termination_failure = "NODE_TERMINATION_FAILURE",
        .pod_eviction_failure = "POD_EVICTION_FAILURE",
        .source_ec2_launch_template_not_found = "SOURCE_EC2_LAUNCH_TEMPLATE_NOT_FOUND",
        .limit_exceeded = "LIMIT_EXCEEDED",
        .unknown = "UNKNOWN",
        .auto_scaling_group_instance_refresh_active = "AUTO_SCALING_GROUP_INSTANCE_REFRESH_ACTIVE",
        .kubernetes_label_invalid = "KUBERNETES_LABEL_INVALID",
        .ec2_launch_template_version_max_limit_exceeded = "EC2_LAUNCH_TEMPLATE_VERSION_MAX_LIMIT_EXCEEDED",
        .ec2_instance_type_does_not_exist = "EC2_INSTANCE_TYPE_DOES_NOT_EXIST",
    };
};
