pub const UpdateParamType = enum {
    version,
    platform_version,
    endpoint_private_access,
    endpoint_public_access,
    cluster_logging,
    desired_size,
    labels_to_add,
    labels_to_remove,
    taints_to_add,
    taints_to_remove,
    max_size,
    min_size,
    release_version,
    public_access_cidrs,
    launch_template_name,
    launch_template_version,
    identity_provider_config,
    encryption_config,
    addon_version,
    service_account_role_arn,
    resolve_conflicts,
    max_unavailable,
    max_unavailable_percentage,
    node_repair_enabled,
    update_strategy,
    configuration_values,
    security_groups,
    subnets,
    authentication_mode,
    pod_identity_associations,
    upgrade_policy,
    zonal_shift_config,
    compute_config,
    storage_config,
    kubernetes_network_config,
    remote_network_config,
    deletion_protection,
    node_repair_config,
    updated_tier,
    previous_tier,

    pub const json_field_names = .{
        .version = "VERSION",
        .platform_version = "PLATFORM_VERSION",
        .endpoint_private_access = "ENDPOINT_PRIVATE_ACCESS",
        .endpoint_public_access = "ENDPOINT_PUBLIC_ACCESS",
        .cluster_logging = "CLUSTER_LOGGING",
        .desired_size = "DESIRED_SIZE",
        .labels_to_add = "LABELS_TO_ADD",
        .labels_to_remove = "LABELS_TO_REMOVE",
        .taints_to_add = "TAINTS_TO_ADD",
        .taints_to_remove = "TAINTS_TO_REMOVE",
        .max_size = "MAX_SIZE",
        .min_size = "MIN_SIZE",
        .release_version = "RELEASE_VERSION",
        .public_access_cidrs = "PUBLIC_ACCESS_CIDRS",
        .launch_template_name = "LAUNCH_TEMPLATE_NAME",
        .launch_template_version = "LAUNCH_TEMPLATE_VERSION",
        .identity_provider_config = "IDENTITY_PROVIDER_CONFIG",
        .encryption_config = "ENCRYPTION_CONFIG",
        .addon_version = "ADDON_VERSION",
        .service_account_role_arn = "SERVICE_ACCOUNT_ROLE_ARN",
        .resolve_conflicts = "RESOLVE_CONFLICTS",
        .max_unavailable = "MAX_UNAVAILABLE",
        .max_unavailable_percentage = "MAX_UNAVAILABLE_PERCENTAGE",
        .node_repair_enabled = "NODE_REPAIR_ENABLED",
        .update_strategy = "UPDATE_STRATEGY",
        .configuration_values = "CONFIGURATION_VALUES",
        .security_groups = "SECURITY_GROUPS",
        .subnets = "SUBNETS",
        .authentication_mode = "AUTHENTICATION_MODE",
        .pod_identity_associations = "POD_IDENTITY_ASSOCIATIONS",
        .upgrade_policy = "UPGRADE_POLICY",
        .zonal_shift_config = "ZONAL_SHIFT_CONFIG",
        .compute_config = "COMPUTE_CONFIG",
        .storage_config = "STORAGE_CONFIG",
        .kubernetes_network_config = "KUBERNETES_NETWORK_CONFIG",
        .remote_network_config = "REMOTE_NETWORK_CONFIG",
        .deletion_protection = "DELETION_PROTECTION",
        .node_repair_config = "NODE_REPAIR_CONFIG",
        .updated_tier = "UPDATED_TIER",
        .previous_tier = "PREVIOUS_TIER",
    };
};
