const std = @import("std");

pub const UpdateParamType = enum {
    version,
    platform_version,
    endpoint_private_access,
    endpoint_public_access,
    cluster_logging,
    desired_size,
    labels_to_add,
    labels_to_remove,
    taints_to_add,
    taints_to_remove,
    max_size,
    min_size,
    release_version,
    public_access_cidrs,
    launch_template_name,
    launch_template_version,
    identity_provider_config,
    encryption_config,
    addon_version,
    service_account_role_arn,
    resolve_conflicts,
    max_unavailable,
    max_unavailable_percentage,
    node_repair_enabled,
    update_strategy,
    configuration_values,
    security_groups,
    subnets,
    authentication_mode,
    pod_identity_associations,
    upgrade_policy,
    zonal_shift_config,
    compute_config,
    storage_config,
    kubernetes_network_config,
    remote_network_config,
    deletion_protection,
    node_repair_config,
    updated_tier,
    previous_tier,

    pub const json_field_names = .{
        .version = "Version",
        .platform_version = "PlatformVersion",
        .endpoint_private_access = "EndpointPrivateAccess",
        .endpoint_public_access = "EndpointPublicAccess",
        .cluster_logging = "ClusterLogging",
        .desired_size = "DesiredSize",
        .labels_to_add = "LabelsToAdd",
        .labels_to_remove = "LabelsToRemove",
        .taints_to_add = "TaintsToAdd",
        .taints_to_remove = "TaintsToRemove",
        .max_size = "MaxSize",
        .min_size = "MinSize",
        .release_version = "ReleaseVersion",
        .public_access_cidrs = "PublicAccessCidrs",
        .launch_template_name = "LaunchTemplateName",
        .launch_template_version = "LaunchTemplateVersion",
        .identity_provider_config = "IdentityProviderConfig",
        .encryption_config = "EncryptionConfig",
        .addon_version = "AddonVersion",
        .service_account_role_arn = "ServiceAccountRoleArn",
        .resolve_conflicts = "ResolveConflicts",
        .max_unavailable = "MaxUnavailable",
        .max_unavailable_percentage = "MaxUnavailablePercentage",
        .node_repair_enabled = "NodeRepairEnabled",
        .update_strategy = "UpdateStrategy",
        .configuration_values = "ConfigurationValues",
        .security_groups = "SecurityGroups",
        .subnets = "Subnets",
        .authentication_mode = "AuthenticationMode",
        .pod_identity_associations = "PodIdentityAssociations",
        .upgrade_policy = "UpgradePolicy",
        .zonal_shift_config = "ZonalShiftConfig",
        .compute_config = "ComputeConfig",
        .storage_config = "StorageConfig",
        .kubernetes_network_config = "KubernetesNetworkConfig",
        .remote_network_config = "RemoteNetworkConfig",
        .deletion_protection = "DeletionProtection",
        .node_repair_config = "NodeRepairConfig",
        .updated_tier = "UpdatedTier",
        .previous_tier = "PreviousTier",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .version => "Version",
            .platform_version => "PlatformVersion",
            .endpoint_private_access => "EndpointPrivateAccess",
            .endpoint_public_access => "EndpointPublicAccess",
            .cluster_logging => "ClusterLogging",
            .desired_size => "DesiredSize",
            .labels_to_add => "LabelsToAdd",
            .labels_to_remove => "LabelsToRemove",
            .taints_to_add => "TaintsToAdd",
            .taints_to_remove => "TaintsToRemove",
            .max_size => "MaxSize",
            .min_size => "MinSize",
            .release_version => "ReleaseVersion",
            .public_access_cidrs => "PublicAccessCidrs",
            .launch_template_name => "LaunchTemplateName",
            .launch_template_version => "LaunchTemplateVersion",
            .identity_provider_config => "IdentityProviderConfig",
            .encryption_config => "EncryptionConfig",
            .addon_version => "AddonVersion",
            .service_account_role_arn => "ServiceAccountRoleArn",
            .resolve_conflicts => "ResolveConflicts",
            .max_unavailable => "MaxUnavailable",
            .max_unavailable_percentage => "MaxUnavailablePercentage",
            .node_repair_enabled => "NodeRepairEnabled",
            .update_strategy => "UpdateStrategy",
            .configuration_values => "ConfigurationValues",
            .security_groups => "SecurityGroups",
            .subnets => "Subnets",
            .authentication_mode => "AuthenticationMode",
            .pod_identity_associations => "PodIdentityAssociations",
            .upgrade_policy => "UpgradePolicy",
            .zonal_shift_config => "ZonalShiftConfig",
            .compute_config => "ComputeConfig",
            .storage_config => "StorageConfig",
            .kubernetes_network_config => "KubernetesNetworkConfig",
            .remote_network_config => "RemoteNetworkConfig",
            .deletion_protection => "DeletionProtection",
            .node_repair_config => "NodeRepairConfig",
            .updated_tier => "UpdatedTier",
            .previous_tier => "PreviousTier",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
