pub const UpdateType = enum {
    version_update,
    endpoint_access_update,
    logging_update,
    config_update,
    associate_identity_provider_config,
    disassociate_identity_provider_config,
    associate_encryption_config,
    addon_update,
    vpc_config_update,
    access_config_update,
    upgrade_policy_update,
    zonal_shift_config_update,
    auto_mode_update,
    remote_network_config_update,
    deletion_protection_update,
    control_plane_scaling_config_update,

    pub const json_field_names = .{
        .version_update = "VERSION_UPDATE",
        .endpoint_access_update = "ENDPOINT_ACCESS_UPDATE",
        .logging_update = "LOGGING_UPDATE",
        .config_update = "CONFIG_UPDATE",
        .associate_identity_provider_config = "ASSOCIATE_IDENTITY_PROVIDER_CONFIG",
        .disassociate_identity_provider_config = "DISASSOCIATE_IDENTITY_PROVIDER_CONFIG",
        .associate_encryption_config = "ASSOCIATE_ENCRYPTION_CONFIG",
        .addon_update = "ADDON_UPDATE",
        .vpc_config_update = "VPC_CONFIG_UPDATE",
        .access_config_update = "ACCESS_CONFIG_UPDATE",
        .upgrade_policy_update = "UPGRADE_POLICY_UPDATE",
        .zonal_shift_config_update = "ZONAL_SHIFT_CONFIG_UPDATE",
        .auto_mode_update = "AUTO_MODE_UPDATE",
        .remote_network_config_update = "REMOTE_NETWORK_CONFIG_UPDATE",
        .deletion_protection_update = "DELETION_PROTECTION_UPDATE",
        .control_plane_scaling_config_update = "CONTROL_PLANE_SCALING_CONFIG_UPDATE",
    };
};
