const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const IndicatorType = @import("indicator_type.zig").IndicatorType;
const Indicator = @import("indicator.zig").Indicator;

pub const ListIndicatorsInput = struct {
    /// The Amazon Resource Name (ARN) of the behavior graph.
    graph_arn: []const u8,

    /// For the list of indicators of compromise that are generated by Detective
    /// investigations, see [Detective
    /// investigations](https://docs.aws.amazon.com/detective/latest/userguide/detective-investigation-about.html).
    indicator_type: ?IndicatorType = null,

    /// The investigation ID of the investigation report.
    investigation_id: []const u8,

    /// Lists the maximum number of indicators in a page.
    max_results: ?i32 = null,

    /// Lists if there are more results available. The value of nextToken is a
    /// unique pagination token for each page. Repeat the call using the returned
    /// token to retrieve the next page. Keep all other arguments unchanged.
    ///
    /// Each pagination token expires after 24 hours. Using an expired pagination
    /// token will return a Validation Exception error.
    next_token: ?[]const u8 = null,

    pub const json_field_names = .{
        .graph_arn = "GraphArn",
        .indicator_type = "IndicatorType",
        .investigation_id = "InvestigationId",
        .max_results = "MaxResults",
        .next_token = "NextToken",
    };
};

pub const ListIndicatorsOutput = struct {
    /// The Amazon Resource Name (ARN) of the behavior graph.
    graph_arn: ?[]const u8 = null,

    /// Lists the indicators of compromise.
    indicators: ?[]const Indicator = null,

    /// The investigation ID of the investigation report.
    investigation_id: ?[]const u8 = null,

    /// Lists if there are more results available. The value of nextToken is a
    /// unique pagination token for each page. Repeat the call using the returned
    /// token to retrieve the next page. Keep all other arguments unchanged.
    ///
    /// Each pagination token expires after 24 hours. Using an expired pagination
    /// token will return a Validation Exception error.
    next_token: ?[]const u8 = null,

    pub const json_field_names = .{
        .graph_arn = "GraphArn",
        .indicators = "Indicators",
        .investigation_id = "InvestigationId",
        .next_token = "NextToken",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: ListIndicatorsInput, options: CallOptions) !ListIndicatorsOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "detective", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: ListIndicatorsInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("api.detective", "Detective", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/investigations/listIndicators";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"GraphArn\":");
    try aws.json.writeValue(@TypeOf(input.graph_arn), input.graph_arn, allocator, &body_buf);
    has_prev = true;
    if (input.indicator_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"IndicatorType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"InvestigationId\":");
    try aws.json.writeValue(@TypeOf(input.investigation_id), input.investigation_id, allocator, &body_buf);
    has_prev = true;
    if (input.max_results) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"MaxResults\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.next_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"NextToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !ListIndicatorsOutput {
    const result: ListIndicatorsOutput = try aws.json.parseJsonObject(
        ListIndicatorsOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
