const aws = @import("aws");

/// A structure used as a protocol between query engines and Lake Formation or
/// Glue. Contains both a Lake Formation generated authorization identifier and
/// information from the request's authorization context.
pub const QuerySessionContext = struct {
    /// An opaque string-string map passed by the query engine.
    additional_context: ?[]const aws.map.StringMapEntry,

    /// An identifier string for the consumer cluster.
    cluster_id: ?[]const u8,

    /// A cryptographically generated query identifier generated by Glue or Lake
    /// Formation.
    query_authorization_id: ?[]const u8,

    /// A unique identifier generated by the query engine for the query.
    query_id: ?[]const u8,

    /// A timestamp provided by the query engine for when the query started.
    query_start_time: ?i64,

    pub const json_field_names = .{
        .additional_context = "AdditionalContext",
        .cluster_id = "ClusterId",
        .query_authorization_id = "QueryAuthorizationId",
        .query_id = "QueryId",
        .query_start_time = "QueryStartTime",
    };
};
