const std = @import("std");

pub const LanguageCode = enum {
    arb,
    cmn_cn,
    cy_gb,
    da_dk,
    de_de,
    en_au,
    en_gb,
    en_gb_wls,
    en_in,
    en_us,
    es_es,
    es_mx,
    es_us,
    fr_ca,
    fr_fr,
    is_is,
    it_it,
    ja_jp,
    hi_in,
    ko_kr,
    nb_no,
    nl_nl,
    pl_pl,
    pt_br,
    pt_pt,
    ro_ro,
    ru_ru,
    sv_se,
    tr_tr,
    en_nz,
    en_za,
    ca_es,
    de_at,
    yue_cn,
    ar_ae,
    fi_fi,
    en_ie,
    nl_be,
    fr_be,
    cs_cz,
    de_ch,
    en_sg,

    pub const json_field_names = .{
        .arb = "arb",
        .cmn_cn = "cmn-CN",
        .cy_gb = "cy-GB",
        .da_dk = "da-DK",
        .de_de = "de-DE",
        .en_au = "en-AU",
        .en_gb = "en-GB",
        .en_gb_wls = "en-GB-WLS",
        .en_in = "en-IN",
        .en_us = "en-US",
        .es_es = "es-ES",
        .es_mx = "es-MX",
        .es_us = "es-US",
        .fr_ca = "fr-CA",
        .fr_fr = "fr-FR",
        .is_is = "is-IS",
        .it_it = "it-IT",
        .ja_jp = "ja-JP",
        .hi_in = "hi-IN",
        .ko_kr = "ko-KR",
        .nb_no = "nb-NO",
        .nl_nl = "nl-NL",
        .pl_pl = "pl-PL",
        .pt_br = "pt-BR",
        .pt_pt = "pt-PT",
        .ro_ro = "ro-RO",
        .ru_ru = "ru-RU",
        .sv_se = "sv-SE",
        .tr_tr = "tr-TR",
        .en_nz = "en-NZ",
        .en_za = "en-ZA",
        .ca_es = "ca-ES",
        .de_at = "de-AT",
        .yue_cn = "yue-CN",
        .ar_ae = "ar-AE",
        .fi_fi = "fi-FI",
        .en_ie = "en-IE",
        .nl_be = "nl-BE",
        .fr_be = "fr-BE",
        .cs_cz = "cs-CZ",
        .de_ch = "de-CH",
        .en_sg = "en-SG",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .arb => "arb",
            .cmn_cn => "cmn-CN",
            .cy_gb => "cy-GB",
            .da_dk => "da-DK",
            .de_de => "de-DE",
            .en_au => "en-AU",
            .en_gb => "en-GB",
            .en_gb_wls => "en-GB-WLS",
            .en_in => "en-IN",
            .en_us => "en-US",
            .es_es => "es-ES",
            .es_mx => "es-MX",
            .es_us => "es-US",
            .fr_ca => "fr-CA",
            .fr_fr => "fr-FR",
            .is_is => "is-IS",
            .it_it => "it-IT",
            .ja_jp => "ja-JP",
            .hi_in => "hi-IN",
            .ko_kr => "ko-KR",
            .nb_no => "nb-NO",
            .nl_nl => "nl-NL",
            .pl_pl => "pl-PL",
            .pt_br => "pt-BR",
            .pt_pt => "pt-PT",
            .ro_ro => "ro-RO",
            .ru_ru => "ru-RU",
            .sv_se => "sv-SE",
            .tr_tr => "tr-TR",
            .en_nz => "en-NZ",
            .en_za => "en-ZA",
            .ca_es => "ca-ES",
            .de_at => "de-AT",
            .yue_cn => "yue-CN",
            .ar_ae => "ar-AE",
            .fi_fi => "fi-FI",
            .en_ie => "en-IE",
            .nl_be => "nl-BE",
            .fr_be => "fr-BE",
            .cs_cz => "cs-CZ",
            .de_ch => "de-CH",
            .en_sg => "en-SG",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
