pub const LanguageCode = enum {
    arb,
    cmn_cn,
    cy_gb,
    da_dk,
    de_de,
    en_au,
    en_gb,
    en_gb_wls,
    en_in,
    en_us,
    es_es,
    es_mx,
    es_us,
    fr_ca,
    fr_fr,
    is_is,
    it_it,
    ja_jp,
    hi_in,
    ko_kr,
    nb_no,
    nl_nl,
    pl_pl,
    pt_br,
    pt_pt,
    ro_ro,
    ru_ru,
    sv_se,
    tr_tr,
    en_nz,
    en_za,
    ca_es,
    de_at,
    yue_cn,
    ar_ae,
    fi_fi,
    en_ie,
    nl_be,
    fr_be,
    cs_cz,
    de_ch,
    en_sg,

    pub const json_field_names = .{
        .arb = "arb",
        .cmn_cn = "cmn_CN",
        .cy_gb = "cy_GB",
        .da_dk = "da_DK",
        .de_de = "de_DE",
        .en_au = "en_AU",
        .en_gb = "en_GB",
        .en_gb_wls = "en_GB_WLS",
        .en_in = "en_IN",
        .en_us = "en_US",
        .es_es = "es_ES",
        .es_mx = "es_MX",
        .es_us = "es_US",
        .fr_ca = "fr_CA",
        .fr_fr = "fr_FR",
        .is_is = "is_IS",
        .it_it = "it_IT",
        .ja_jp = "ja_JP",
        .hi_in = "hi_IN",
        .ko_kr = "ko_KR",
        .nb_no = "nb_NO",
        .nl_nl = "nl_NL",
        .pl_pl = "pl_PL",
        .pt_br = "pt_BR",
        .pt_pt = "pt_PT",
        .ro_ro = "ro_RO",
        .ru_ru = "ru_RU",
        .sv_se = "sv_SE",
        .tr_tr = "tr_TR",
        .en_nz = "en_NZ",
        .en_za = "en_ZA",
        .ca_es = "ca_ES",
        .de_at = "de_AT",
        .yue_cn = "yue_CN",
        .ar_ae = "ar_AE",
        .fi_fi = "fi_FI",
        .en_ie = "en_IE",
        .nl_be = "nl_BE",
        .fr_be = "fr_BE",
        .cs_cz = "cs_CZ",
        .de_ch = "de_CH",
        .en_sg = "en_SG",
    };
};
