const std = @import("std");

pub const VoiceId = enum {
    aditi,
    amy,
    astrid,
    bianca,
    brian,
    camila,
    carla,
    carmen,
    celine,
    chantal,
    conchita,
    cristiano,
    dora,
    emma,
    enrique,
    ewa,
    filiz,
    gabrielle,
    geraint,
    giorgio,
    gwyneth,
    hans,
    ines,
    ivy,
    jacek,
    jan,
    joanna,
    joey,
    justin,
    karl,
    kendra,
    kevin,
    kimberly,
    lea,
    liv,
    lotte,
    lucia,
    lupe,
    mads,
    maja,
    marlene,
    mathieu,
    matthew,
    maxim,
    mia,
    miguel,
    mizuki,
    naja,
    nicole,
    olivia,
    penelope,
    raveena,
    ricardo,
    ruben,
    russell,
    salli,
    seoyeon,
    takumi,
    tatyana,
    vicki,
    vitoria,
    zeina,
    zhiyu,
    aria,
    ayanda,
    arlet,
    hannah,
    arthur,
    daniel,
    liam,
    pedro,
    kajal,
    hiujin,
    laura,
    elin,
    ida,
    suvi,
    ola,
    hala,
    andres,
    sergio,
    remi,
    adriano,
    thiago,
    ruth,
    stephen,
    kazuha,
    tomoko,
    niamh,
    sofie,
    lisa,
    isabelle,
    zayd,
    danielle,
    gregory,
    burcu,
    jitka,
    sabrina,
    jasmine,
    jihye,

    pub const json_field_names = .{
        .aditi = "Aditi",
        .amy = "Amy",
        .astrid = "Astrid",
        .bianca = "Bianca",
        .brian = "Brian",
        .camila = "Camila",
        .carla = "Carla",
        .carmen = "Carmen",
        .celine = "Celine",
        .chantal = "Chantal",
        .conchita = "Conchita",
        .cristiano = "Cristiano",
        .dora = "Dora",
        .emma = "Emma",
        .enrique = "Enrique",
        .ewa = "Ewa",
        .filiz = "Filiz",
        .gabrielle = "Gabrielle",
        .geraint = "Geraint",
        .giorgio = "Giorgio",
        .gwyneth = "Gwyneth",
        .hans = "Hans",
        .ines = "Ines",
        .ivy = "Ivy",
        .jacek = "Jacek",
        .jan = "Jan",
        .joanna = "Joanna",
        .joey = "Joey",
        .justin = "Justin",
        .karl = "Karl",
        .kendra = "Kendra",
        .kevin = "Kevin",
        .kimberly = "Kimberly",
        .lea = "Lea",
        .liv = "Liv",
        .lotte = "Lotte",
        .lucia = "Lucia",
        .lupe = "Lupe",
        .mads = "Mads",
        .maja = "Maja",
        .marlene = "Marlene",
        .mathieu = "Mathieu",
        .matthew = "Matthew",
        .maxim = "Maxim",
        .mia = "Mia",
        .miguel = "Miguel",
        .mizuki = "Mizuki",
        .naja = "Naja",
        .nicole = "Nicole",
        .olivia = "Olivia",
        .penelope = "Penelope",
        .raveena = "Raveena",
        .ricardo = "Ricardo",
        .ruben = "Ruben",
        .russell = "Russell",
        .salli = "Salli",
        .seoyeon = "Seoyeon",
        .takumi = "Takumi",
        .tatyana = "Tatyana",
        .vicki = "Vicki",
        .vitoria = "Vitoria",
        .zeina = "Zeina",
        .zhiyu = "Zhiyu",
        .aria = "Aria",
        .ayanda = "Ayanda",
        .arlet = "Arlet",
        .hannah = "Hannah",
        .arthur = "Arthur",
        .daniel = "Daniel",
        .liam = "Liam",
        .pedro = "Pedro",
        .kajal = "Kajal",
        .hiujin = "Hiujin",
        .laura = "Laura",
        .elin = "Elin",
        .ida = "Ida",
        .suvi = "Suvi",
        .ola = "Ola",
        .hala = "Hala",
        .andres = "Andres",
        .sergio = "Sergio",
        .remi = "Remi",
        .adriano = "Adriano",
        .thiago = "Thiago",
        .ruth = "Ruth",
        .stephen = "Stephen",
        .kazuha = "Kazuha",
        .tomoko = "Tomoko",
        .niamh = "Niamh",
        .sofie = "Sofie",
        .lisa = "Lisa",
        .isabelle = "Isabelle",
        .zayd = "Zayd",
        .danielle = "Danielle",
        .gregory = "Gregory",
        .burcu = "Burcu",
        .jitka = "Jitka",
        .sabrina = "Sabrina",
        .jasmine = "Jasmine",
        .jihye = "Jihye",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .aditi => "Aditi",
            .amy => "Amy",
            .astrid => "Astrid",
            .bianca => "Bianca",
            .brian => "Brian",
            .camila => "Camila",
            .carla => "Carla",
            .carmen => "Carmen",
            .celine => "Celine",
            .chantal => "Chantal",
            .conchita => "Conchita",
            .cristiano => "Cristiano",
            .dora => "Dora",
            .emma => "Emma",
            .enrique => "Enrique",
            .ewa => "Ewa",
            .filiz => "Filiz",
            .gabrielle => "Gabrielle",
            .geraint => "Geraint",
            .giorgio => "Giorgio",
            .gwyneth => "Gwyneth",
            .hans => "Hans",
            .ines => "Ines",
            .ivy => "Ivy",
            .jacek => "Jacek",
            .jan => "Jan",
            .joanna => "Joanna",
            .joey => "Joey",
            .justin => "Justin",
            .karl => "Karl",
            .kendra => "Kendra",
            .kevin => "Kevin",
            .kimberly => "Kimberly",
            .lea => "Lea",
            .liv => "Liv",
            .lotte => "Lotte",
            .lucia => "Lucia",
            .lupe => "Lupe",
            .mads => "Mads",
            .maja => "Maja",
            .marlene => "Marlene",
            .mathieu => "Mathieu",
            .matthew => "Matthew",
            .maxim => "Maxim",
            .mia => "Mia",
            .miguel => "Miguel",
            .mizuki => "Mizuki",
            .naja => "Naja",
            .nicole => "Nicole",
            .olivia => "Olivia",
            .penelope => "Penelope",
            .raveena => "Raveena",
            .ricardo => "Ricardo",
            .ruben => "Ruben",
            .russell => "Russell",
            .salli => "Salli",
            .seoyeon => "Seoyeon",
            .takumi => "Takumi",
            .tatyana => "Tatyana",
            .vicki => "Vicki",
            .vitoria => "Vitoria",
            .zeina => "Zeina",
            .zhiyu => "Zhiyu",
            .aria => "Aria",
            .ayanda => "Ayanda",
            .arlet => "Arlet",
            .hannah => "Hannah",
            .arthur => "Arthur",
            .daniel => "Daniel",
            .liam => "Liam",
            .pedro => "Pedro",
            .kajal => "Kajal",
            .hiujin => "Hiujin",
            .laura => "Laura",
            .elin => "Elin",
            .ida => "Ida",
            .suvi => "Suvi",
            .ola => "Ola",
            .hala => "Hala",
            .andres => "Andres",
            .sergio => "Sergio",
            .remi => "Remi",
            .adriano => "Adriano",
            .thiago => "Thiago",
            .ruth => "Ruth",
            .stephen => "Stephen",
            .kazuha => "Kazuha",
            .tomoko => "Tomoko",
            .niamh => "Niamh",
            .sofie => "Sofie",
            .lisa => "Lisa",
            .isabelle => "Isabelle",
            .zayd => "Zayd",
            .danielle => "Danielle",
            .gregory => "Gregory",
            .burcu => "Burcu",
            .jitka => "Jitka",
            .sabrina => "Sabrina",
            .jasmine => "Jasmine",
            .jihye => "Jihye",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
