pub const JobLogEvent = enum {
    job_start,
    server_skipped,
    cleanup_start,
    cleanup_end,
    cleanup_fail,
    snapshot_start,
    snapshot_end,
    snapshot_fail,
    using_previous_snapshot,
    using_previous_snapshot_failed,
    conversion_start,
    conversion_end,
    conversion_fail,
    launch_start,
    launch_failed,
    job_cancel,
    job_end,
    deploy_network_configuration_start,
    deploy_network_configuration_end,
    deploy_network_configuration_failed,
    update_network_configuration_start,
    update_network_configuration_end,
    update_network_configuration_failed,
    update_launch_template_start,
    update_launch_template_end,
    update_launch_template_failed,
    network_recovery_fail,

    pub const json_field_names = .{
        .job_start = "JOB_START",
        .server_skipped = "SERVER_SKIPPED",
        .cleanup_start = "CLEANUP_START",
        .cleanup_end = "CLEANUP_END",
        .cleanup_fail = "CLEANUP_FAIL",
        .snapshot_start = "SNAPSHOT_START",
        .snapshot_end = "SNAPSHOT_END",
        .snapshot_fail = "SNAPSHOT_FAIL",
        .using_previous_snapshot = "USING_PREVIOUS_SNAPSHOT",
        .using_previous_snapshot_failed = "USING_PREVIOUS_SNAPSHOT_FAILED",
        .conversion_start = "CONVERSION_START",
        .conversion_end = "CONVERSION_END",
        .conversion_fail = "CONVERSION_FAIL",
        .launch_start = "LAUNCH_START",
        .launch_failed = "LAUNCH_FAILED",
        .job_cancel = "JOB_CANCEL",
        .job_end = "JOB_END",
        .deploy_network_configuration_start = "DEPLOY_NETWORK_CONFIGURATION_START",
        .deploy_network_configuration_end = "DEPLOY_NETWORK_CONFIGURATION_END",
        .deploy_network_configuration_failed = "DEPLOY_NETWORK_CONFIGURATION_FAILED",
        .update_network_configuration_start = "UPDATE_NETWORK_CONFIGURATION_START",
        .update_network_configuration_end = "UPDATE_NETWORK_CONFIGURATION_END",
        .update_network_configuration_failed = "UPDATE_NETWORK_CONFIGURATION_FAILED",
        .update_launch_template_start = "UPDATE_LAUNCH_TEMPLATE_START",
        .update_launch_template_end = "UPDATE_LAUNCH_TEMPLATE_END",
        .update_launch_template_failed = "UPDATE_LAUNCH_TEMPLATE_FAILED",
        .network_recovery_fail = "NETWORK_RECOVERY_FAIL",
    };
};
