/// Card data parameters that are required to generate a cardholder verification
/// value for the payment card.
pub const CardHolderVerificationValue = struct {
    /// The transaction counter value that comes from a point of sale terminal.
    application_transaction_counter: []const u8,

    /// A number that identifies and differentiates payment cards with the same
    /// Primary Account Number (PAN).
    pan_sequence_number: []const u8,

    /// A random number generated by the issuer.
    unpredictable_number: []const u8,

    pub const json_field_names = .{
        .application_transaction_counter = "ApplicationTransactionCounter",
        .pan_sequence_number = "PanSequenceNumber",
        .unpredictable_number = "UnpredictableNumber",
    };
};
