/// Parameters that are required to generate or verify Dynamic Card Verification
/// Value (dCVV).
pub const DynamicCardVerificationCode = struct {
    /// The transaction counter value that comes from the terminal.
    application_transaction_counter: []const u8,

    /// A number that identifies and differentiates payment cards with the same
    /// Primary Account Number (PAN).
    pan_sequence_number: []const u8,

    /// The data on the two tracks of magnetic cards used for financial
    /// transactions. This includes the cardholder name, PAN, expiration date, bank
    /// ID (BIN) and several other numbers the issuing bank uses to validate the
    /// data received.
    track_data: []const u8,

    /// A random number generated by the issuer.
    unpredictable_number: []const u8,

    pub const json_field_names = .{
        .application_transaction_counter = "ApplicationTransactionCounter",
        .pan_sequence_number = "PanSequenceNumber",
        .track_data = "TrackData",
        .unpredictable_number = "UnpredictableNumber",
    };
};
