pub const MetricName = enum {
    device_rssi,
    device_snr,
    device_roaming_rssi,
    device_roaming_snr,
    device_uplink_count,
    device_downlink_count,
    device_uplink_lost_count,
    device_uplink_lost_rate,
    device_join_request_count,
    device_join_accept_count,
    device_roaming_uplink_count,
    device_roaming_downlink_count,
    gateway_up_time,
    gateway_down_time,
    gateway_rssi,
    gateway_snr,
    gateway_uplink_count,
    gateway_downlink_count,
    gateway_join_request_count,
    gateway_join_accept_count,
    aws_account_uplink_count,
    aws_account_downlink_count,
    aws_account_uplink_lost_count,
    aws_account_uplink_lost_rate,
    aws_account_join_request_count,
    aws_account_join_accept_count,
    aws_account_roaming_uplink_count,
    aws_account_roaming_downlink_count,
    aws_account_device_count,
    aws_account_gateway_count,
    aws_account_active_device_count,
    aws_account_active_gateway_count,

    pub const json_field_names = .{
        .device_rssi = "DeviceRSSI",
        .device_snr = "DeviceSNR",
        .device_roaming_rssi = "DeviceRoamingRSSI",
        .device_roaming_snr = "DeviceRoamingSNR",
        .device_uplink_count = "DeviceUplinkCount",
        .device_downlink_count = "DeviceDownlinkCount",
        .device_uplink_lost_count = "DeviceUplinkLostCount",
        .device_uplink_lost_rate = "DeviceUplinkLostRate",
        .device_join_request_count = "DeviceJoinRequestCount",
        .device_join_accept_count = "DeviceJoinAcceptCount",
        .device_roaming_uplink_count = "DeviceRoamingUplinkCount",
        .device_roaming_downlink_count = "DeviceRoamingDownlinkCount",
        .gateway_up_time = "GatewayUpTime",
        .gateway_down_time = "GatewayDownTime",
        .gateway_rssi = "GatewayRSSI",
        .gateway_snr = "GatewaySNR",
        .gateway_uplink_count = "GatewayUplinkCount",
        .gateway_downlink_count = "GatewayDownlinkCount",
        .gateway_join_request_count = "GatewayJoinRequestCount",
        .gateway_join_accept_count = "GatewayJoinAcceptCount",
        .aws_account_uplink_count = "AwsAccountUplinkCount",
        .aws_account_downlink_count = "AwsAccountDownlinkCount",
        .aws_account_uplink_lost_count = "AwsAccountUplinkLostCount",
        .aws_account_uplink_lost_rate = "AwsAccountUplinkLostRate",
        .aws_account_join_request_count = "AwsAccountJoinRequestCount",
        .aws_account_join_accept_count = "AwsAccountJoinAcceptCount",
        .aws_account_roaming_uplink_count = "AwsAccountRoamingUplinkCount",
        .aws_account_roaming_downlink_count = "AwsAccountRoamingDownlinkCount",
        .aws_account_device_count = "AwsAccountDeviceCount",
        .aws_account_gateway_count = "AwsAccountGatewayCount",
        .aws_account_active_device_count = "AwsAccountActiveDeviceCount",
        .aws_account_active_gateway_count = "AwsAccountActiveGatewayCount",
    };
};
