pub const PartOfSpeechTagType = enum {
    adj,
    adp,
    adv,
    aux,
    conj,
    cconj,
    det,
    intj,
    noun,
    num,
    o,
    part,
    pron,
    propn,
    punct,
    sconj,
    sym,
    verb,

    pub const json_field_names = .{
        .adj = "ADJ",
        .adp = "ADP",
        .adv = "ADV",
        .aux = "AUX",
        .conj = "CONJ",
        .cconj = "CCONJ",
        .det = "DET",
        .intj = "INTJ",
        .noun = "NOUN",
        .num = "NUM",
        .o = "O",
        .part = "PART",
        .pron = "PRON",
        .propn = "PROPN",
        .punct = "PUNCT",
        .sconj = "SCONJ",
        .sym = "SYM",
        .verb = "VERB",
    };
};
