pub const PiiEntityType = enum {
    bank_account_number,
    bank_routing,
    credit_debit_number,
    credit_debit_cvv,
    credit_debit_expiry,
    pin,
    email,
    address,
    name,
    phone,
    ssn,
    date_time,
    passport_number,
    driver_id,
    url,
    age,
    username,
    password,
    aws_access_key,
    aws_secret_key,
    ip_address,
    mac_address,
    all,
    license_plate,
    vehicle_identification_number,
    uk_national_insurance_number,
    ca_social_insurance_number,
    us_individual_tax_identification_number,
    uk_unique_taxpayer_reference_number,
    in_permanent_account_number,
    in_nrega,
    international_bank_account_number,
    swift_code,
    uk_national_health_service_number,
    ca_health_number,
    in_aadhaar,
    in_voter_number,

    pub const json_field_names = .{
        .bank_account_number = "BANK_ACCOUNT_NUMBER",
        .bank_routing = "BANK_ROUTING",
        .credit_debit_number = "CREDIT_DEBIT_NUMBER",
        .credit_debit_cvv = "CREDIT_DEBIT_CVV",
        .credit_debit_expiry = "CREDIT_DEBIT_EXPIRY",
        .pin = "PIN",
        .email = "EMAIL",
        .address = "ADDRESS",
        .name = "NAME",
        .phone = "PHONE",
        .ssn = "SSN",
        .date_time = "DATE_TIME",
        .passport_number = "PASSPORT_NUMBER",
        .driver_id = "DRIVER_ID",
        .url = "URL",
        .age = "AGE",
        .username = "USERNAME",
        .password = "PASSWORD",
        .aws_access_key = "AWS_ACCESS_KEY",
        .aws_secret_key = "AWS_SECRET_KEY",
        .ip_address = "IP_ADDRESS",
        .mac_address = "MAC_ADDRESS",
        .all = "ALL",
        .license_plate = "LICENSE_PLATE",
        .vehicle_identification_number = "VEHICLE_IDENTIFICATION_NUMBER",
        .uk_national_insurance_number = "UK_NATIONAL_INSURANCE_NUMBER",
        .ca_social_insurance_number = "CA_SOCIAL_INSURANCE_NUMBER",
        .us_individual_tax_identification_number = "US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER",
        .uk_unique_taxpayer_reference_number = "UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER",
        .in_permanent_account_number = "IN_PERMANENT_ACCOUNT_NUMBER",
        .in_nrega = "IN_NREGA",
        .international_bank_account_number = "INTERNATIONAL_BANK_ACCOUNT_NUMBER",
        .swift_code = "SWIFT_CODE",
        .uk_national_health_service_number = "UK_NATIONAL_HEALTH_SERVICE_NUMBER",
        .ca_health_number = "CA_HEALTH_NUMBER",
        .in_aadhaar = "IN_AADHAAR",
        .in_voter_number = "IN_VOTER_NUMBER",
    };
};
