pub const TargetedSentimentEntityType = enum {
    person,
    location,
    organization,
    facility,
    brand,
    commercial_item,
    movie,
    music,
    book,
    software,
    game,
    personal_title,
    event,
    date,
    quantity,
    attribute,
    other,

    pub const json_field_names = .{
        .person = "PERSON",
        .location = "LOCATION",
        .organization = "ORGANIZATION",
        .facility = "FACILITY",
        .brand = "BRAND",
        .commercial_item = "COMMERCIAL_ITEM",
        .movie = "MOVIE",
        .music = "MUSIC",
        .book = "BOOK",
        .software = "SOFTWARE",
        .game = "GAME",
        .personal_title = "PERSONAL_TITLE",
        .event = "EVENT",
        .date = "DATE",
        .quantity = "QUANTITY",
        .attribute = "ATTRIBUTE",
        .other = "OTHER",
    };
};
