pub const ScalableDimension = enum {
    ecs_service_desired_count,
    ec2_spot_fleet_request_target_capacity,
    emr_instance_group_instance_count,
    appstream_fleet_desired_capacity,
    dynamo_db_table_read_capacity_units,
    dynamo_db_table_write_capacity_units,
    dynamo_db_index_read_capacity_units,
    dynamo_db_index_write_capacity_units,
    rds_cluster_read_replica_count,
    sage_maker_variant_desired_instance_count,
    custom_resource_scalable_dimension,
    comprehend_doc_classifier_endpoint_inference_units,
    comprehend_entity_recognizer_endpoint_inference_units,
    lambda_function_provisioned_concurrency,
    cassandra_table_read_capacity_units,
    cassandra_table_write_capacity_units,
    kafka_broker_storage_volume_size,
    elasti_cache_cache_cluster_nodes,
    elasti_cache_replication_group_node_groups,
    elasti_cache_replication_group_replicas,
    neptune_cluster_read_replica_count,
    sage_maker_variant_desired_provisioned_concurrency,
    sage_maker_inference_component_desired_copy_count,
    work_spaces_work_spaces_pool_desired_user_sessions,

    pub const json_field_names = .{
        .ecs_service_desired_count = "ECSServiceDesiredCount",
        .ec2_spot_fleet_request_target_capacity = "EC2SpotFleetRequestTargetCapacity",
        .emr_instance_group_instance_count = "EMRInstanceGroupInstanceCount",
        .appstream_fleet_desired_capacity = "AppstreamFleetDesiredCapacity",
        .dynamo_db_table_read_capacity_units = "DynamoDBTableReadCapacityUnits",
        .dynamo_db_table_write_capacity_units = "DynamoDBTableWriteCapacityUnits",
        .dynamo_db_index_read_capacity_units = "DynamoDBIndexReadCapacityUnits",
        .dynamo_db_index_write_capacity_units = "DynamoDBIndexWriteCapacityUnits",
        .rds_cluster_read_replica_count = "RDSClusterReadReplicaCount",
        .sage_maker_variant_desired_instance_count = "SageMakerVariantDesiredInstanceCount",
        .custom_resource_scalable_dimension = "CustomResourceScalableDimension",
        .comprehend_doc_classifier_endpoint_inference_units = "ComprehendDocClassifierEndpointInferenceUnits",
        .comprehend_entity_recognizer_endpoint_inference_units = "ComprehendEntityRecognizerEndpointInferenceUnits",
        .lambda_function_provisioned_concurrency = "LambdaFunctionProvisionedConcurrency",
        .cassandra_table_read_capacity_units = "CassandraTableReadCapacityUnits",
        .cassandra_table_write_capacity_units = "CassandraTableWriteCapacityUnits",
        .kafka_broker_storage_volume_size = "KafkaBrokerStorageVolumeSize",
        .elasti_cache_cache_cluster_nodes = "ElastiCacheCacheClusterNodes",
        .elasti_cache_replication_group_node_groups = "ElastiCacheReplicationGroupNodeGroups",
        .elasti_cache_replication_group_replicas = "ElastiCacheReplicationGroupReplicas",
        .neptune_cluster_read_replica_count = "NeptuneClusterReadReplicaCount",
        .sage_maker_variant_desired_provisioned_concurrency = "SageMakerVariantDesiredProvisionedConcurrency",
        .sage_maker_inference_component_desired_copy_count = "SageMakerInferenceComponentDesiredCopyCount",
        .work_spaces_work_spaces_pool_desired_user_sessions = "WorkSpacesWorkSpacesPoolDesiredUserSessions",
    };
};
