pub const ServiceNamespace = enum {
    ecs,
    emr,
    ec2,
    appstream,
    dynamodb,
    rds,
    sagemaker,
    custom_resource,
    comprehend,
    lambda,
    cassandra,
    kafka,
    elasticache,
    neptune,
    workspaces,

    pub const json_field_names = .{
        .ecs = "ECS",
        .emr = "EMR",
        .ec2 = "EC2",
        .appstream = "APPSTREAM",
        .dynamodb = "DYNAMODB",
        .rds = "RDS",
        .sagemaker = "SAGEMAKER",
        .custom_resource = "CUSTOM_RESOURCE",
        .comprehend = "COMPREHEND",
        .lambda = "LAMBDA",
        .cassandra = "CASSANDRA",
        .kafka = "KAFKA",
        .elasticache = "ELASTICACHE",
        .neptune = "NEPTUNE",
        .workspaces = "WORKSPACES",
    };
};
