const AutomatedReasoningPolicyGeneratedTestCase = @import("automated_reasoning_policy_generated_test_case.zig").AutomatedReasoningPolicyGeneratedTestCase;

/// Contains a comprehensive test suite generated by the build workflow,
/// providing validation capabilities for automated reasoning policies.
pub const AutomatedReasoningPolicyGeneratedTestCases = struct {
    /// Represents a collection of generated test cases.
    generated_test_cases: []const AutomatedReasoningPolicyGeneratedTestCase,

    pub const json_field_names = .{
        .generated_test_cases = "generatedTestCases",
    };
};
