pub const LanguageCodeType = enum {
    ar,
    bg,
    bn,
    da,
    de,
    cs,
    el,
    en,
    es,
    fa,
    fi,
    fr,
    hi,
    hu,
    id,
    it,
    ja,
    ko,
    lt,
    lv,
    nl,
    no,
    pt,
    ro,
    ru,
    sv,
    sw,
    th,
    tr,
    zh,
    default,

    pub const json_field_names = .{
        .ar = "AR",
        .bg = "BG",
        .bn = "BN",
        .da = "DA",
        .de = "DE",
        .cs = "CS",
        .el = "EL",
        .en = "EN",
        .es = "ES",
        .fa = "FA",
        .fi = "FI",
        .fr = "FR",
        .hi = "HI",
        .hu = "HU",
        .id = "ID",
        .it = "IT",
        .ja = "JA",
        .ko = "KO",
        .lt = "LT",
        .lv = "LV",
        .nl = "NL",
        .no = "NO",
        .pt = "PT",
        .ro = "RO",
        .ru = "RU",
        .sv = "SV",
        .sw = "SW",
        .th = "TH",
        .tr = "TR",
        .zh = "ZH",
        .default = "DEFAULT",
    };
};
