const RecordMarkerFailedCause = @import("record_marker_failed_cause.zig").RecordMarkerFailedCause;

/// Provides the details of the `RecordMarkerFailed` event.
pub const RecordMarkerFailedEventAttributes = struct {
    /// The cause of the failure. This information is generated by the system and
    /// can be useful for diagnostic purposes.
    ///
    /// If `cause` is set to `OPERATION_NOT_PERMITTED`, the decision failed
    /// because it lacked sufficient permissions. For details and example IAM
    /// policies, see [Using IAM to Manage Access to Amazon SWF
    /// Workflows](https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html)
    /// in the *Amazon SWF Developer Guide*.
    cause: RecordMarkerFailedCause,

    /// The ID of the `DecisionTaskCompleted` event corresponding to the decision
    /// task that resulted in the
    /// `RecordMarkerFailed` decision for this cancellation request. This
    /// information can be useful for diagnosing problems by tracing back the chain
    /// of
    /// events leading up to this event.
    decision_task_completed_event_id: i64 = 0,

    /// The marker's name.
    marker_name: []const u8,

    pub const json_field_names = .{
        .cause = "cause",
        .decision_task_completed_event_id = "decisionTaskCompletedEventId",
        .marker_name = "markerName",
    };
};
