const RequestCancelExternalWorkflowExecutionFailedCause = @import("request_cancel_external_workflow_execution_failed_cause.zig").RequestCancelExternalWorkflowExecutionFailedCause;

/// Provides the details of the `RequestCancelExternalWorkflowExecutionFailed`
/// event.
pub const RequestCancelExternalWorkflowExecutionFailedEventAttributes = struct {
    /// The cause of the failure. This information is generated by the system and
    /// can be useful for diagnostic purposes.
    ///
    /// If `cause` is set to `OPERATION_NOT_PERMITTED`, the decision failed
    /// because it lacked sufficient permissions. For details and example IAM
    /// policies, see [Using IAM to Manage Access to Amazon SWF
    /// Workflows](https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html)
    /// in the *Amazon SWF Developer Guide*.
    cause: RequestCancelExternalWorkflowExecutionFailedCause,

    /// The data attached to the event that the decider can use in subsequent
    /// workflow tasks.
    /// This data isn't sent to the workflow execution.
    control: ?[]const u8 = null,

    /// The ID of the `DecisionTaskCompleted` event corresponding to the decision
    /// task that resulted in the
    /// `RequestCancelExternalWorkflowExecution` decision for this cancellation
    /// request. This information can be useful for diagnosing problems by tracing
    /// back the chain of
    /// events leading up to this event.
    decision_task_completed_event_id: i64 = 0,

    /// The ID of the `RequestCancelExternalWorkflowExecutionInitiated` event
    /// corresponding to the
    /// `RequestCancelExternalWorkflowExecution` decision to cancel this external
    /// workflow execution. This
    /// information can be useful for diagnosing problems by tracing back the chain
    /// of events leading up to this
    /// event.
    initiated_event_id: i64 = 0,

    /// The `runId` of the external workflow execution.
    run_id: ?[]const u8 = null,

    /// The `workflowId` of the external workflow to which the cancel request was to
    /// be delivered.
    workflow_id: []const u8,

    pub const json_field_names = .{
        .cause = "cause",
        .control = "control",
        .decision_task_completed_event_id = "decisionTaskCompletedEventId",
        .initiated_event_id = "initiatedEventId",
        .run_id = "runId",
        .workflow_id = "workflowId",
    };
};
