const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;

pub const RespondActivityTaskCanceledInput = struct {
    /// Information about the cancellation.
    details: ?[]const u8 = null,

    /// The `taskToken` of the ActivityTask.
    ///
    /// `taskToken` is generated by the service and should be treated as an opaque
    /// value.
    /// If the task is passed to another process, its `taskToken` must also be
    /// passed.
    /// This enables it to provide its progress and respond with results.
    task_token: []const u8,

    pub const json_field_names = .{
        .details = "details",
        .task_token = "taskToken",
    };
};

pub const RespondActivityTaskCanceledOutput = struct {};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: RespondActivityTaskCanceledInput, options: CallOptions) !RespondActivityTaskCanceledOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "swf", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: RespondActivityTaskCanceledInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("swf", "SWF", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.0");
    try request.headers.put(allocator, "X-Amz-Target", "SimpleWorkflowService.RespondActivityTaskCanceled");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !RespondActivityTaskCanceledOutput {
    _ = status;
    _ = headers;
    _ = body;
    _ = allocator;
    return .{};
}
