const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Decision = @import("decision.zig").Decision;
const TaskList = @import("task_list.zig").TaskList;

pub const RespondDecisionTaskCompletedInput = struct {
    /// The list of decisions (possibly empty) made by the decider while processing
    /// this
    /// decision task. See the docs for the Decision structure for
    /// details.
    decisions: ?[]const Decision = null,

    /// User defined context to add to workflow execution.
    execution_context: ?[]const u8 = null,

    /// The task list to use for the future decision tasks of this workflow
    /// execution. This list overrides the original task list you specified while
    /// starting the workflow execution.
    task_list: ?TaskList = null,

    /// Specifies a timeout (in seconds) for the task list override. When this
    /// parameter is missing, the task list override is permanent. This parameter
    /// makes it possible to temporarily override the task list. If a decision task
    /// scheduled on the override task list is not started within the timeout, the
    /// decision task will time out. Amazon SWF will revert the override and
    /// schedule a new decision task to the original task list.
    ///
    /// If a decision task scheduled on the override task list is started within the
    /// timeout, but not completed within the start-to-close timeout, Amazon SWF
    /// will also revert the override and schedule a new decision task to the
    /// original task list.
    task_list_schedule_to_start_timeout: ?[]const u8 = null,

    /// The `taskToken` from the DecisionTask.
    ///
    /// `taskToken` is generated by the service and should be treated as an opaque
    /// value.
    /// If the task is passed to another process, its `taskToken` must also be
    /// passed.
    /// This enables it to provide its progress and respond with results.
    task_token: []const u8,

    pub const json_field_names = .{
        .decisions = "decisions",
        .execution_context = "executionContext",
        .task_list = "taskList",
        .task_list_schedule_to_start_timeout = "taskListScheduleToStartTimeout",
        .task_token = "taskToken",
    };
};

pub const RespondDecisionTaskCompletedOutput = struct {};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: RespondDecisionTaskCompletedInput, options: CallOptions) !RespondDecisionTaskCompletedOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "swf", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: RespondDecisionTaskCompletedInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("swf", "SWF", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.0");
    try request.headers.put(allocator, "X-Amz-Target", "SimpleWorkflowService.RespondDecisionTaskCompleted");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !RespondDecisionTaskCompletedOutput {
    _ = status;
    _ = headers;
    _ = body;
    _ = allocator;
    return .{};
}
