const ActivityType = @import("activity_type.zig").ActivityType;
const ScheduleActivityTaskFailedCause = @import("schedule_activity_task_failed_cause.zig").ScheduleActivityTaskFailedCause;

/// Provides the details of the `ScheduleActivityTaskFailed` event.
pub const ScheduleActivityTaskFailedEventAttributes = struct {
    /// The activityId provided in the `ScheduleActivityTask` decision that failed.
    activity_id: []const u8,

    /// The activity type provided in the `ScheduleActivityTask` decision that
    /// failed.
    activity_type: ActivityType,

    /// The cause of the failure. This information is generated by the system and
    /// can be useful for diagnostic purposes.
    ///
    /// If `cause` is set to `OPERATION_NOT_PERMITTED`, the decision failed
    /// because it lacked sufficient permissions. For details and example IAM
    /// policies, see [Using IAM to Manage Access to Amazon SWF
    /// Workflows](https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html)
    /// in the *Amazon SWF Developer Guide*.
    cause: ScheduleActivityTaskFailedCause,

    /// The ID of the `DecisionTaskCompleted` event corresponding to the decision
    /// that resulted in the
    /// scheduling of this activity task. This information can be useful for
    /// diagnosing problems by tracing back the chain of
    /// events leading up to this event.
    decision_task_completed_event_id: i64 = 0,

    pub const json_field_names = .{
        .activity_id = "activityId",
        .activity_type = "activityType",
        .cause = "cause",
        .decision_task_completed_event_id = "decisionTaskCompletedEventId",
    };
};
