const Achievability = @import("achievability.zig").Achievability;
const AssessmentCost = @import("assessment_cost.zig").AssessmentCost;
const AssessmentStatus = @import("assessment_status.zig").AssessmentStatus;
const AssessmentStep = @import("assessment_step.zig").AssessmentStep;
const AssessmentErrorCode = @import("assessment_error_code.zig").AssessmentErrorCode;

/// Contains summary information about a failure mode assessment.
pub const AssessmentSummary = struct {
    /// The achievability results from the assessment.
    achievability: ?Achievability = null,

    /// The cost of the assessment.
    assessment_cost: ?AssessmentCost = null,

    /// The unique identifier of the assessment.
    assessment_id: []const u8,

    /// The current status of the assessment.
    assessment_status: ?AssessmentStatus = null,

    /// The current step of the assessment process.
    assessment_step: ?AssessmentStep = null,

    /// The number of billable assessment units consumed by the assessment.
    billable_assessment_unit_count: ?i32 = null,

    /// The timestamp when the assessment ended.
    ended_at: ?i64 = null,

    /// The error code if the assessment failed.
    error_code: ?AssessmentErrorCode = null,

    /// A message describing the error if the assessment failed.
    error_message: ?[]const u8 = null,

    service_arn: []const u8,

    /// The timestamp when the assessment started.
    started_at: ?i64 = null,

    /// The total number of findings generated by the assessment.
    total_findings: ?i32 = null,

    pub const json_field_names = .{
        .achievability = "achievability",
        .assessment_cost = "assessmentCost",
        .assessment_id = "assessmentId",
        .assessment_status = "assessmentStatus",
        .assessment_step = "assessmentStep",
        .billable_assessment_unit_count = "billableAssessmentUnitCount",
        .ended_at = "endedAt",
        .error_code = "errorCode",
        .error_message = "errorMessage",
        .service_arn = "serviceArn",
        .started_at = "startedAt",
        .total_findings = "totalFindings",
    };
};
