const std = @import("std");

pub const ExportableInstanceField = enum {
    account_id,
    instance_arn,
    instance_name,
    finding,
    finding_reason_codes,
    lookback_period_in_days,
    current_instance_type,
    utilization_metrics_cpu_maximum,
    utilization_metrics_memory_maximum,
    utilization_metrics_ebs_read_ops_per_second_maximum,
    utilization_metrics_ebs_write_ops_per_second_maximum,
    utilization_metrics_ebs_read_bytes_per_second_maximum,
    utilization_metrics_ebs_write_bytes_per_second_maximum,
    utilization_metrics_disk_read_ops_per_second_maximum,
    utilization_metrics_disk_write_ops_per_second_maximum,
    utilization_metrics_disk_read_bytes_per_second_maximum,
    utilization_metrics_disk_write_bytes_per_second_maximum,
    utilization_metrics_network_in_bytes_per_second_maximum,
    utilization_metrics_network_out_bytes_per_second_maximum,
    utilization_metrics_network_packets_in_per_second_maximum,
    utilization_metrics_network_packets_out_per_second_maximum,
    current_on_demand_price,
    current_standard_one_year_no_upfront_reserved_price,
    current_standard_three_year_no_upfront_reserved_price,
    current_vcpus,
    current_memory,
    current_storage,
    current_network,
    recommendation_options_instance_type,
    recommendation_options_projected_utilization_metrics_cpu_maximum,
    recommendation_options_projected_utilization_metrics_memory_maximum,
    recommendation_options_platform_differences,
    recommendation_options_performance_risk,
    recommendation_options_vcpus,
    recommendation_options_memory,
    recommendation_options_storage,
    recommendation_options_network,
    recommendation_options_on_demand_price,
    recommendation_options_standard_one_year_no_upfront_reserved_price,
    recommendation_options_standard_three_year_no_upfront_reserved_price,
    recommendations_sources_recommendation_source_arn,
    recommendations_sources_recommendation_source_type,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    effective_recommendation_preferences_cpu_vendor_architectures,
    effective_recommendation_preferences_enhanced_infrastructure_metrics,
    effective_recommendation_preferences_inferred_workload_types,
    inferred_workload_types,
    recommendation_options_migration_effort,
    effective_recommendation_preferences_external_metrics_source,
    tags,
    instance_state,
    external_metric_status_code,
    external_metric_status_reason,
    current_instance_gpu_info,
    recommendation_options_instance_gpu_info,
    utilization_metrics_gpu_percentage_maximum,
    utilization_metrics_gpu_memory_percentage_maximum,
    recommendation_options_projected_utilization_metrics_gpu_percentage_maximum,
    recommendation_options_projected_utilization_metrics_gpu_memory_percentage_maximum,
    idle,
    effective_recommendation_preferences_preferred_resources,
    effective_recommendation_preferences_lookback_period,
    effective_recommendation_preferences_utilization_preferences,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .instance_arn = "InstanceArn",
        .instance_name = "InstanceName",
        .finding = "Finding",
        .finding_reason_codes = "FindingReasonCodes",
        .lookback_period_in_days = "LookbackPeriodInDays",
        .current_instance_type = "CurrentInstanceType",
        .utilization_metrics_cpu_maximum = "UtilizationMetricsCpuMaximum",
        .utilization_metrics_memory_maximum = "UtilizationMetricsMemoryMaximum",
        .utilization_metrics_ebs_read_ops_per_second_maximum = "UtilizationMetricsEbsReadOpsPerSecondMaximum",
        .utilization_metrics_ebs_write_ops_per_second_maximum = "UtilizationMetricsEbsWriteOpsPerSecondMaximum",
        .utilization_metrics_ebs_read_bytes_per_second_maximum = "UtilizationMetricsEbsReadBytesPerSecondMaximum",
        .utilization_metrics_ebs_write_bytes_per_second_maximum = "UtilizationMetricsEbsWriteBytesPerSecondMaximum",
        .utilization_metrics_disk_read_ops_per_second_maximum = "UtilizationMetricsDiskReadOpsPerSecondMaximum",
        .utilization_metrics_disk_write_ops_per_second_maximum = "UtilizationMetricsDiskWriteOpsPerSecondMaximum",
        .utilization_metrics_disk_read_bytes_per_second_maximum = "UtilizationMetricsDiskReadBytesPerSecondMaximum",
        .utilization_metrics_disk_write_bytes_per_second_maximum = "UtilizationMetricsDiskWriteBytesPerSecondMaximum",
        .utilization_metrics_network_in_bytes_per_second_maximum = "UtilizationMetricsNetworkInBytesPerSecondMaximum",
        .utilization_metrics_network_out_bytes_per_second_maximum = "UtilizationMetricsNetworkOutBytesPerSecondMaximum",
        .utilization_metrics_network_packets_in_per_second_maximum = "UtilizationMetricsNetworkPacketsInPerSecondMaximum",
        .utilization_metrics_network_packets_out_per_second_maximum = "UtilizationMetricsNetworkPacketsOutPerSecondMaximum",
        .current_on_demand_price = "CurrentOnDemandPrice",
        .current_standard_one_year_no_upfront_reserved_price = "CurrentStandardOneYearNoUpfrontReservedPrice",
        .current_standard_three_year_no_upfront_reserved_price = "CurrentStandardThreeYearNoUpfrontReservedPrice",
        .current_vcpus = "CurrentVCpus",
        .current_memory = "CurrentMemory",
        .current_storage = "CurrentStorage",
        .current_network = "CurrentNetwork",
        .recommendation_options_instance_type = "RecommendationOptionsInstanceType",
        .recommendation_options_projected_utilization_metrics_cpu_maximum = "RecommendationOptionsProjectedUtilizationMetricsCpuMaximum",
        .recommendation_options_projected_utilization_metrics_memory_maximum = "RecommendationOptionsProjectedUtilizationMetricsMemoryMaximum",
        .recommendation_options_platform_differences = "RecommendationOptionsPlatformDifferences",
        .recommendation_options_performance_risk = "RecommendationOptionsPerformanceRisk",
        .recommendation_options_vcpus = "RecommendationOptionsVcpus",
        .recommendation_options_memory = "RecommendationOptionsMemory",
        .recommendation_options_storage = "RecommendationOptionsStorage",
        .recommendation_options_network = "RecommendationOptionsNetwork",
        .recommendation_options_on_demand_price = "RecommendationOptionsOnDemandPrice",
        .recommendation_options_standard_one_year_no_upfront_reserved_price = "RecommendationOptionsStandardOneYearNoUpfrontReservedPrice",
        .recommendation_options_standard_three_year_no_upfront_reserved_price = "RecommendationOptionsStandardThreeYearNoUpfrontReservedPrice",
        .recommendations_sources_recommendation_source_arn = "RecommendationsSourcesRecommendationSourceArn",
        .recommendations_sources_recommendation_source_type = "RecommendationsSourcesRecommendationSourceType",
        .last_refresh_timestamp = "LastRefreshTimestamp",
        .current_performance_risk = "CurrentPerformanceRisk",
        .recommendation_options_savings_opportunity_percentage = "RecommendationOptionsSavingsOpportunityPercentage",
        .recommendation_options_estimated_monthly_savings_currency = "RecommendationOptionsEstimatedMonthlySavingsCurrency",
        .recommendation_options_estimated_monthly_savings_value = "RecommendationOptionsEstimatedMonthlySavingsValue",
        .effective_recommendation_preferences_cpu_vendor_architectures = "EffectiveRecommendationPreferencesCpuVendorArchitectures",
        .effective_recommendation_preferences_enhanced_infrastructure_metrics = "EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics",
        .effective_recommendation_preferences_inferred_workload_types = "EffectiveRecommendationPreferencesInferredWorkloadTypes",
        .inferred_workload_types = "InferredWorkloadTypes",
        .recommendation_options_migration_effort = "RecommendationOptionsMigrationEffort",
        .effective_recommendation_preferences_external_metrics_source = "EffectiveRecommendationPreferencesExternalMetricsSource",
        .tags = "Tags",
        .instance_state = "InstanceState",
        .external_metric_status_code = "ExternalMetricStatusCode",
        .external_metric_status_reason = "ExternalMetricStatusReason",
        .current_instance_gpu_info = "CurrentInstanceGpuInfo",
        .recommendation_options_instance_gpu_info = "RecommendationOptionsInstanceGpuInfo",
        .utilization_metrics_gpu_percentage_maximum = "UtilizationMetricsGpuPercentageMaximum",
        .utilization_metrics_gpu_memory_percentage_maximum = "UtilizationMetricsGpuMemoryPercentageMaximum",
        .recommendation_options_projected_utilization_metrics_gpu_percentage_maximum = "RecommendationOptionsProjectedUtilizationMetricsGpuPercentageMaximum",
        .recommendation_options_projected_utilization_metrics_gpu_memory_percentage_maximum = "RecommendationOptionsProjectedUtilizationMetricsGpuMemoryPercentageMaximum",
        .idle = "Idle",
        .effective_recommendation_preferences_preferred_resources = "EffectiveRecommendationPreferencesPreferredResources",
        .effective_recommendation_preferences_lookback_period = "EffectiveRecommendationPreferencesLookBackPeriod",
        .effective_recommendation_preferences_utilization_preferences = "EffectiveRecommendationPreferencesUtilizationPreferences",
        .effective_recommendation_preferences_savings_estimation_mode = "EffectiveRecommendationPreferencesSavingsEstimationMode",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .account_id => "AccountId",
            .instance_arn => "InstanceArn",
            .instance_name => "InstanceName",
            .finding => "Finding",
            .finding_reason_codes => "FindingReasonCodes",
            .lookback_period_in_days => "LookbackPeriodInDays",
            .current_instance_type => "CurrentInstanceType",
            .utilization_metrics_cpu_maximum => "UtilizationMetricsCpuMaximum",
            .utilization_metrics_memory_maximum => "UtilizationMetricsMemoryMaximum",
            .utilization_metrics_ebs_read_ops_per_second_maximum => "UtilizationMetricsEbsReadOpsPerSecondMaximum",
            .utilization_metrics_ebs_write_ops_per_second_maximum => "UtilizationMetricsEbsWriteOpsPerSecondMaximum",
            .utilization_metrics_ebs_read_bytes_per_second_maximum => "UtilizationMetricsEbsReadBytesPerSecondMaximum",
            .utilization_metrics_ebs_write_bytes_per_second_maximum => "UtilizationMetricsEbsWriteBytesPerSecondMaximum",
            .utilization_metrics_disk_read_ops_per_second_maximum => "UtilizationMetricsDiskReadOpsPerSecondMaximum",
            .utilization_metrics_disk_write_ops_per_second_maximum => "UtilizationMetricsDiskWriteOpsPerSecondMaximum",
            .utilization_metrics_disk_read_bytes_per_second_maximum => "UtilizationMetricsDiskReadBytesPerSecondMaximum",
            .utilization_metrics_disk_write_bytes_per_second_maximum => "UtilizationMetricsDiskWriteBytesPerSecondMaximum",
            .utilization_metrics_network_in_bytes_per_second_maximum => "UtilizationMetricsNetworkInBytesPerSecondMaximum",
            .utilization_metrics_network_out_bytes_per_second_maximum => "UtilizationMetricsNetworkOutBytesPerSecondMaximum",
            .utilization_metrics_network_packets_in_per_second_maximum => "UtilizationMetricsNetworkPacketsInPerSecondMaximum",
            .utilization_metrics_network_packets_out_per_second_maximum => "UtilizationMetricsNetworkPacketsOutPerSecondMaximum",
            .current_on_demand_price => "CurrentOnDemandPrice",
            .current_standard_one_year_no_upfront_reserved_price => "CurrentStandardOneYearNoUpfrontReservedPrice",
            .current_standard_three_year_no_upfront_reserved_price => "CurrentStandardThreeYearNoUpfrontReservedPrice",
            .current_vcpus => "CurrentVCpus",
            .current_memory => "CurrentMemory",
            .current_storage => "CurrentStorage",
            .current_network => "CurrentNetwork",
            .recommendation_options_instance_type => "RecommendationOptionsInstanceType",
            .recommendation_options_projected_utilization_metrics_cpu_maximum => "RecommendationOptionsProjectedUtilizationMetricsCpuMaximum",
            .recommendation_options_projected_utilization_metrics_memory_maximum => "RecommendationOptionsProjectedUtilizationMetricsMemoryMaximum",
            .recommendation_options_platform_differences => "RecommendationOptionsPlatformDifferences",
            .recommendation_options_performance_risk => "RecommendationOptionsPerformanceRisk",
            .recommendation_options_vcpus => "RecommendationOptionsVcpus",
            .recommendation_options_memory => "RecommendationOptionsMemory",
            .recommendation_options_storage => "RecommendationOptionsStorage",
            .recommendation_options_network => "RecommendationOptionsNetwork",
            .recommendation_options_on_demand_price => "RecommendationOptionsOnDemandPrice",
            .recommendation_options_standard_one_year_no_upfront_reserved_price => "RecommendationOptionsStandardOneYearNoUpfrontReservedPrice",
            .recommendation_options_standard_three_year_no_upfront_reserved_price => "RecommendationOptionsStandardThreeYearNoUpfrontReservedPrice",
            .recommendations_sources_recommendation_source_arn => "RecommendationsSourcesRecommendationSourceArn",
            .recommendations_sources_recommendation_source_type => "RecommendationsSourcesRecommendationSourceType",
            .last_refresh_timestamp => "LastRefreshTimestamp",
            .current_performance_risk => "CurrentPerformanceRisk",
            .recommendation_options_savings_opportunity_percentage => "RecommendationOptionsSavingsOpportunityPercentage",
            .recommendation_options_estimated_monthly_savings_currency => "RecommendationOptionsEstimatedMonthlySavingsCurrency",
            .recommendation_options_estimated_monthly_savings_value => "RecommendationOptionsEstimatedMonthlySavingsValue",
            .effective_recommendation_preferences_cpu_vendor_architectures => "EffectiveRecommendationPreferencesCpuVendorArchitectures",
            .effective_recommendation_preferences_enhanced_infrastructure_metrics => "EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics",
            .effective_recommendation_preferences_inferred_workload_types => "EffectiveRecommendationPreferencesInferredWorkloadTypes",
            .inferred_workload_types => "InferredWorkloadTypes",
            .recommendation_options_migration_effort => "RecommendationOptionsMigrationEffort",
            .effective_recommendation_preferences_external_metrics_source => "EffectiveRecommendationPreferencesExternalMetricsSource",
            .tags => "Tags",
            .instance_state => "InstanceState",
            .external_metric_status_code => "ExternalMetricStatusCode",
            .external_metric_status_reason => "ExternalMetricStatusReason",
            .current_instance_gpu_info => "CurrentInstanceGpuInfo",
            .recommendation_options_instance_gpu_info => "RecommendationOptionsInstanceGpuInfo",
            .utilization_metrics_gpu_percentage_maximum => "UtilizationMetricsGpuPercentageMaximum",
            .utilization_metrics_gpu_memory_percentage_maximum => "UtilizationMetricsGpuMemoryPercentageMaximum",
            .recommendation_options_projected_utilization_metrics_gpu_percentage_maximum => "RecommendationOptionsProjectedUtilizationMetricsGpuPercentageMaximum",
            .recommendation_options_projected_utilization_metrics_gpu_memory_percentage_maximum => "RecommendationOptionsProjectedUtilizationMetricsGpuMemoryPercentageMaximum",
            .idle => "Idle",
            .effective_recommendation_preferences_preferred_resources => "EffectiveRecommendationPreferencesPreferredResources",
            .effective_recommendation_preferences_lookback_period => "EffectiveRecommendationPreferencesLookBackPeriod",
            .effective_recommendation_preferences_utilization_preferences => "EffectiveRecommendationPreferencesUtilizationPreferences",
            .effective_recommendation_preferences_savings_estimation_mode => "EffectiveRecommendationPreferencesSavingsEstimationMode",
            .recommendation_options_savings_opportunity_after_discounts_percentage => "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
            .recommendation_options_estimated_monthly_savings_currency_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
            .recommendation_options_estimated_monthly_savings_value_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
