const std = @import("std");

pub const ExportableLambdaFunctionField = enum {
    account_id,
    function_arn,
    function_version,
    finding,
    finding_reason_codes,
    number_of_invocations,
    utilization_metrics_duration_maximum,
    utilization_metrics_duration_average,
    utilization_metrics_memory_maximum,
    utilization_metrics_memory_average,
    lookback_period_in_days,
    current_configuration_memory_size,
    current_configuration_timeout,
    current_cost_total,
    current_cost_average,
    recommendation_options_configuration_memory_size,
    recommendation_options_cost_low,
    recommendation_options_cost_high,
    recommendation_options_projected_utilization_metrics_duration_lower_bound,
    recommendation_options_projected_utilization_metrics_duration_upper_bound,
    recommendation_options_projected_utilization_metrics_duration_expected,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    tags,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .function_arn = "FunctionArn",
        .function_version = "FunctionVersion",
        .finding = "Finding",
        .finding_reason_codes = "FindingReasonCodes",
        .number_of_invocations = "NumberOfInvocations",
        .utilization_metrics_duration_maximum = "UtilizationMetricsDurationMaximum",
        .utilization_metrics_duration_average = "UtilizationMetricsDurationAverage",
        .utilization_metrics_memory_maximum = "UtilizationMetricsMemoryMaximum",
        .utilization_metrics_memory_average = "UtilizationMetricsMemoryAverage",
        .lookback_period_in_days = "LookbackPeriodInDays",
        .current_configuration_memory_size = "CurrentConfigurationMemorySize",
        .current_configuration_timeout = "CurrentConfigurationTimeout",
        .current_cost_total = "CurrentCostTotal",
        .current_cost_average = "CurrentCostAverage",
        .recommendation_options_configuration_memory_size = "RecommendationOptionsConfigurationMemorySize",
        .recommendation_options_cost_low = "RecommendationOptionsCostLow",
        .recommendation_options_cost_high = "RecommendationOptionsCostHigh",
        .recommendation_options_projected_utilization_metrics_duration_lower_bound = "RecommendationOptionsProjectedUtilizationMetricsDurationLowerBound",
        .recommendation_options_projected_utilization_metrics_duration_upper_bound = "RecommendationOptionsProjectedUtilizationMetricsDurationUpperBound",
        .recommendation_options_projected_utilization_metrics_duration_expected = "RecommendationOptionsProjectedUtilizationMetricsDurationExpected",
        .last_refresh_timestamp = "LastRefreshTimestamp",
        .current_performance_risk = "CurrentPerformanceRisk",
        .recommendation_options_savings_opportunity_percentage = "RecommendationOptionsSavingsOpportunityPercentage",
        .recommendation_options_estimated_monthly_savings_currency = "RecommendationOptionsEstimatedMonthlySavingsCurrency",
        .recommendation_options_estimated_monthly_savings_value = "RecommendationOptionsEstimatedMonthlySavingsValue",
        .tags = "Tags",
        .effective_recommendation_preferences_savings_estimation_mode = "EffectiveRecommendationPreferencesSavingsEstimationMode",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .account_id => "AccountId",
            .function_arn => "FunctionArn",
            .function_version => "FunctionVersion",
            .finding => "Finding",
            .finding_reason_codes => "FindingReasonCodes",
            .number_of_invocations => "NumberOfInvocations",
            .utilization_metrics_duration_maximum => "UtilizationMetricsDurationMaximum",
            .utilization_metrics_duration_average => "UtilizationMetricsDurationAverage",
            .utilization_metrics_memory_maximum => "UtilizationMetricsMemoryMaximum",
            .utilization_metrics_memory_average => "UtilizationMetricsMemoryAverage",
            .lookback_period_in_days => "LookbackPeriodInDays",
            .current_configuration_memory_size => "CurrentConfigurationMemorySize",
            .current_configuration_timeout => "CurrentConfigurationTimeout",
            .current_cost_total => "CurrentCostTotal",
            .current_cost_average => "CurrentCostAverage",
            .recommendation_options_configuration_memory_size => "RecommendationOptionsConfigurationMemorySize",
            .recommendation_options_cost_low => "RecommendationOptionsCostLow",
            .recommendation_options_cost_high => "RecommendationOptionsCostHigh",
            .recommendation_options_projected_utilization_metrics_duration_lower_bound => "RecommendationOptionsProjectedUtilizationMetricsDurationLowerBound",
            .recommendation_options_projected_utilization_metrics_duration_upper_bound => "RecommendationOptionsProjectedUtilizationMetricsDurationUpperBound",
            .recommendation_options_projected_utilization_metrics_duration_expected => "RecommendationOptionsProjectedUtilizationMetricsDurationExpected",
            .last_refresh_timestamp => "LastRefreshTimestamp",
            .current_performance_risk => "CurrentPerformanceRisk",
            .recommendation_options_savings_opportunity_percentage => "RecommendationOptionsSavingsOpportunityPercentage",
            .recommendation_options_estimated_monthly_savings_currency => "RecommendationOptionsEstimatedMonthlySavingsCurrency",
            .recommendation_options_estimated_monthly_savings_value => "RecommendationOptionsEstimatedMonthlySavingsValue",
            .tags => "Tags",
            .effective_recommendation_preferences_savings_estimation_mode => "EffectiveRecommendationPreferencesSavingsEstimationMode",
            .recommendation_options_savings_opportunity_after_discounts_percentage => "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
            .recommendation_options_estimated_monthly_savings_currency_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
            .recommendation_options_estimated_monthly_savings_value_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
