pub const ExportableLicenseField = enum {
    account_id,
    resource_arn,
    lookback_period_in_days,
    last_refresh_timestamp,
    license_finding,
    license_finding_reason_codes,
    current_license_configuration_number_of_cores,
    current_license_configuration_instance_type,
    current_license_configuration_operating_system,
    current_license_configuration_license_name,
    current_license_configuration_license_edition,
    current_license_configuration_license_model,
    current_license_configuration_license_version,
    current_license_configuration_metrics_source,
    recommendation_options_operating_system,
    recommendation_options_license_edition,
    recommendation_options_license_model,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    tags,

    pub const json_field_names = .{
        .account_id = "ACCOUNT_ID",
        .resource_arn = "RESOURCE_ARN",
        .lookback_period_in_days = "LOOKBACK_PERIOD_IN_DAYS",
        .last_refresh_timestamp = "LAST_REFRESH_TIMESTAMP",
        .license_finding = "LICENSE_FINDING",
        .license_finding_reason_codes = "LICENSE_FINDING_REASON_CODES",
        .current_license_configuration_number_of_cores = "CURRENT_LICENSE_CONFIGURATION_NUMBER_OF_CORES",
        .current_license_configuration_instance_type = "CURRENT_LICENSE_CONFIGURATION_INSTANCE_TYPE",
        .current_license_configuration_operating_system = "CURRENT_LICENSE_CONFIGURATION_OPERATING_SYSTEM",
        .current_license_configuration_license_name = "CURRENT_LICENSE_CONFIGURATION_LICENSE_NAME",
        .current_license_configuration_license_edition = "CURRENT_LICENSE_CONFIGURATION_LICENSE_EDITION",
        .current_license_configuration_license_model = "CURRENT_LICENSE_CONFIGURATION_LICENSE_MODEL",
        .current_license_configuration_license_version = "CURRENT_LICENSE_CONFIGURATION_LICENSE_VERSION",
        .current_license_configuration_metrics_source = "CURRENT_LICENSE_CONFIGURATION_METRICS_SOURCE",
        .recommendation_options_operating_system = "RECOMMENDATION_OPTIONS_OPERATING_SYSTEM",
        .recommendation_options_license_edition = "RECOMMENDATION_OPTIONS_LICENSE_EDITION",
        .recommendation_options_license_model = "RECOMMENDATION_OPTIONS_LICENSE_MODEL",
        .recommendation_options_savings_opportunity_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY",
        .recommendation_options_estimated_monthly_savings_value = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE",
        .tags = "TAGS",
    };
};
