pub const ExportableAutoScalingGroupField = enum {
    account_id,
    auto_scaling_group_arn,
    auto_scaling_group_name,
    finding,
    utilization_metrics_cpu_maximum,
    utilization_metrics_memory_maximum,
    utilization_metrics_ebs_read_ops_per_second_maximum,
    utilization_metrics_ebs_write_ops_per_second_maximum,
    utilization_metrics_ebs_read_bytes_per_second_maximum,
    utilization_metrics_ebs_write_bytes_per_second_maximum,
    utilization_metrics_disk_read_ops_per_second_maximum,
    utilization_metrics_disk_write_ops_per_second_maximum,
    utilization_metrics_disk_read_bytes_per_second_maximum,
    utilization_metrics_disk_write_bytes_per_second_maximum,
    utilization_metrics_network_in_bytes_per_second_maximum,
    utilization_metrics_network_out_bytes_per_second_maximum,
    utilization_metrics_network_packets_in_per_second_maximum,
    utilization_metrics_network_packets_out_per_second_maximum,
    lookback_period_in_days,
    current_configuration_instance_type,
    current_configuration_desired_capacity,
    current_configuration_min_size,
    current_configuration_max_size,
    current_configuration_allocation_strategy,
    current_configuration_mixed_instance_types,
    current_configuration_type,
    current_on_demand_price,
    current_standard_one_year_no_upfront_reserved_price,
    current_standard_three_year_no_upfront_reserved_price,
    current_vcpus,
    current_memory,
    current_storage,
    current_network,
    recommendation_options_configuration_instance_type,
    recommendation_options_configuration_desired_capacity,
    recommendation_options_configuration_min_size,
    recommendation_options_configuration_max_size,
    recommendation_options_configuration_estimated_instance_hour_reduction_percentage,
    recommendation_options_configuration_allocation_strategy,
    recommendation_options_configuration_mixed_instance_types,
    recommendation_options_configuration_type,
    recommendation_options_projected_utilization_metrics_cpu_maximum,
    recommendation_options_projected_utilization_metrics_memory_maximum,
    recommendation_options_performance_risk,
    recommendation_options_on_demand_price,
    recommendation_options_standard_one_year_no_upfront_reserved_price,
    recommendation_options_standard_three_year_no_upfront_reserved_price,
    recommendation_options_vcpus,
    recommendation_options_memory,
    recommendation_options_storage,
    recommendation_options_network,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    effective_recommendation_preferences_cpu_vendor_architectures,
    effective_recommendation_preferences_enhanced_infrastructure_metrics,
    effective_recommendation_preferences_inferred_workload_types,
    effective_recommendation_preferences_preferred_resources,
    effective_recommendation_preferences_lookback_period,
    inferred_workload_types,
    recommendation_options_migration_effort,
    current_instance_gpu_info,
    recommendation_options_instance_gpu_info,
    utilization_metrics_gpu_percentage_maximum,
    utilization_metrics_gpu_memory_percentage_maximum,
    recommendation_options_projected_utilization_metrics_gpu_maximum,
    recommendation_options_projected_utilization_metrics_gpu_memory_maximum,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "ACCOUNT_ID",
        .auto_scaling_group_arn = "AUTO_SCALING_GROUP_ARN",
        .auto_scaling_group_name = "AUTO_SCALING_GROUP_NAME",
        .finding = "FINDING",
        .utilization_metrics_cpu_maximum = "UTILIZATION_METRICS_CPU_MAXIMUM",
        .utilization_metrics_memory_maximum = "UTILIZATION_METRICS_MEMORY_MAXIMUM",
        .utilization_metrics_ebs_read_ops_per_second_maximum = "UTILIZATION_METRICS_EBS_READ_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_ebs_write_ops_per_second_maximum = "UTILIZATION_METRICS_EBS_WRITE_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_ebs_read_bytes_per_second_maximum = "UTILIZATION_METRICS_EBS_READ_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_ebs_write_bytes_per_second_maximum = "UTILIZATION_METRICS_EBS_WRITE_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_read_ops_per_second_maximum = "UTILIZATION_METRICS_DISK_READ_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_write_ops_per_second_maximum = "UTILIZATION_METRICS_DISK_WRITE_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_read_bytes_per_second_maximum = "UTILIZATION_METRICS_DISK_READ_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_write_bytes_per_second_maximum = "UTILIZATION_METRICS_DISK_WRITE_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_in_bytes_per_second_maximum = "UTILIZATION_METRICS_NETWORK_IN_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_out_bytes_per_second_maximum = "UTILIZATION_METRICS_NETWORK_OUT_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_packets_in_per_second_maximum = "UTILIZATION_METRICS_NETWORK_PACKETS_IN_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_packets_out_per_second_maximum = "UTILIZATION_METRICS_NETWORK_PACKETS_OUT_PER_SECOND_MAXIMUM",
        .lookback_period_in_days = "LOOKBACK_PERIOD_IN_DAYS",
        .current_configuration_instance_type = "CURRENT_CONFIGURATION_INSTANCE_TYPE",
        .current_configuration_desired_capacity = "CURRENT_CONFIGURATION_DESIRED_CAPACITY",
        .current_configuration_min_size = "CURRENT_CONFIGURATION_MIN_SIZE",
        .current_configuration_max_size = "CURRENT_CONFIGURATION_MAX_SIZE",
        .current_configuration_allocation_strategy = "CURRENT_CONFIGURATION_ALLOCATION_STRATEGY",
        .current_configuration_mixed_instance_types = "CURRENT_CONFIGURATION_MIXED_INSTANCE_TYPES",
        .current_configuration_type = "CURRENT_CONFIGURATION_TYPE",
        .current_on_demand_price = "CURRENT_ON_DEMAND_PRICE",
        .current_standard_one_year_no_upfront_reserved_price = "CURRENT_STANDARD_ONE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .current_standard_three_year_no_upfront_reserved_price = "CURRENT_STANDARD_THREE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .current_vcpus = "CURRENT_VCPUS",
        .current_memory = "CURRENT_MEMORY",
        .current_storage = "CURRENT_STORAGE",
        .current_network = "CURRENT_NETWORK",
        .recommendation_options_configuration_instance_type = "RECOMMENDATION_OPTIONS_CONFIGURATION_INSTANCE_TYPE",
        .recommendation_options_configuration_desired_capacity = "RECOMMENDATION_OPTIONS_CONFIGURATION_DESIRED_CAPACITY",
        .recommendation_options_configuration_min_size = "RECOMMENDATION_OPTIONS_CONFIGURATION_MIN_SIZE",
        .recommendation_options_configuration_max_size = "RECOMMENDATION_OPTIONS_CONFIGURATION_MAX_SIZE",
        .recommendation_options_configuration_estimated_instance_hour_reduction_percentage = "RECOMMENDATION_OPTIONS_CONFIGURATION_ESTIMATED_INSTANCE_HOUR_REDUCTION_PERCENTAGE",
        .recommendation_options_configuration_allocation_strategy = "RECOMMENDATION_OPTIONS_CONFIGURATION_ALLOCATION_STRATEGY",
        .recommendation_options_configuration_mixed_instance_types = "RECOMMENDATION_OPTIONS_CONFIGURATION_MIXED_INSTANCE_TYPES",
        .recommendation_options_configuration_type = "RECOMMENDATION_OPTIONS_CONFIGURATION_TYPE",
        .recommendation_options_projected_utilization_metrics_cpu_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_CPU_MAXIMUM",
        .recommendation_options_projected_utilization_metrics_memory_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_MEMORY_MAXIMUM",
        .recommendation_options_performance_risk = "RECOMMENDATION_OPTIONS_PERFORMANCE_RISK",
        .recommendation_options_on_demand_price = "RECOMMENDATION_OPTIONS_ON_DEMAND_PRICE",
        .recommendation_options_standard_one_year_no_upfront_reserved_price = "RECOMMENDATION_OPTIONS_STANDARD_ONE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .recommendation_options_standard_three_year_no_upfront_reserved_price = "RECOMMENDATION_OPTIONS_STANDARD_THREE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .recommendation_options_vcpus = "RECOMMENDATION_OPTIONS_VCPUS",
        .recommendation_options_memory = "RECOMMENDATION_OPTIONS_MEMORY",
        .recommendation_options_storage = "RECOMMENDATION_OPTIONS_STORAGE",
        .recommendation_options_network = "RECOMMENDATION_OPTIONS_NETWORK",
        .last_refresh_timestamp = "LAST_REFRESH_TIMESTAMP",
        .current_performance_risk = "CURRENT_PERFORMANCE_RISK",
        .recommendation_options_savings_opportunity_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY",
        .recommendation_options_estimated_monthly_savings_value = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE",
        .effective_recommendation_preferences_cpu_vendor_architectures = "EFFECTIVE_RECOMMENDATION_PREFERENCES_CPU_VENDOR_ARCHITECTURES",
        .effective_recommendation_preferences_enhanced_infrastructure_metrics = "EFFECTIVE_RECOMMENDATION_PREFERENCES_ENHANCED_INFRASTRUCTURE_METRICS",
        .effective_recommendation_preferences_inferred_workload_types = "EFFECTIVE_RECOMMENDATION_PREFERENCES_INFERRED_WORKLOAD_TYPES",
        .effective_recommendation_preferences_preferred_resources = "EFFECTIVE_RECOMMENDATION_PREFERENCES_PREFERRED_RESOURCES",
        .effective_recommendation_preferences_lookback_period = "EFFECTIVE_RECOMMENDATION_PREFERENCES_LOOKBACK_PERIOD",
        .inferred_workload_types = "INFERRED_WORKLOAD_TYPES",
        .recommendation_options_migration_effort = "RECOMMENDATION_OPTIONS_MIGRATION_EFFORT",
        .current_instance_gpu_info = "CURRENT_INSTANCE_GPU_INFO",
        .recommendation_options_instance_gpu_info = "RECOMMENDATION_OPTIONS_INSTANCE_GPU_INFO",
        .utilization_metrics_gpu_percentage_maximum = "UTILIZATION_METRICS_GPU_PERCENTAGE_MAXIMUM",
        .utilization_metrics_gpu_memory_percentage_maximum = "UTILIZATION_METRICS_GPU_MEMORY_PERCENTAGE_MAXIMUM",
        .recommendation_options_projected_utilization_metrics_gpu_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_GPU_MAXIMUM",
        .recommendation_options_projected_utilization_metrics_gpu_memory_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_GPU_MEMORY_MAXIMUM",
        .effective_recommendation_preferences_savings_estimation_mode = "EFFECTIVE_RECOMMENDATION_PREFERENCES_SAVINGS_ESTIMATION_MODE",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_AFTER_DISCOUNTS_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY_AFTER_DISCOUNTS",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE_AFTER_DISCOUNTS",
    };
};
