const std = @import("std");

pub const ExportableIdleField = enum {
    account_id,
    resource_arn,
    resource_id,
    resource_type,
    last_refresh_timestamp,
    lookback_period_in_days,
    savings_opportunity,
    savings_opportunity_after_discount,
    utilization_metrics_cpu_maximum,
    utilization_metrics_memory_maximum,
    utilization_metrics_network_out_bytes_per_second_maximum,
    utilization_metrics_network_in_bytes_per_second_maximum,
    utilization_metrics_database_connections_maximum,
    utilization_metrics_ebs_volume_read_iops_maximum,
    utilization_metrics_ebs_volume_write_iops_maximum,
    utilization_metrics_volume_read_ops_per_second_maximum,
    utilization_metrics_volume_write_ops_per_second_maximum,
    utilization_metrics_active_connection_count_maximum,
    utilization_metrics_packets_in_from_source_maximum,
    utilization_metrics_packets_in_from_destination_maximum,
    utilization_metrics_consumed_read_capacity_units_sum,
    utilization_metrics_consumed_write_capacity_units_sum,
    utilization_metrics_new_connections_sum,
    utilization_metrics_engine_cpu_utilization_maximum,
    utilization_metrics_cache_hits_sum,
    utilization_metrics_cache_misses_sum,
    utilization_metrics_keyspace_hits_sum,
    utilization_metrics_keyspace_misses_sum,
    utilization_metrics_is_idle_minimum,
    utilization_metrics_user_connected_sum,
    utilization_metrics_invocations_sum,
    utilization_metrics_get_type_cmds_sum,
    utilization_metrics_set_type_cmds_sum,
    utilization_metrics_elasti_cache_processing_units_sum,
    utilization_metrics_curr_connections_sum,
    utilization_metrics_database_connections_sum,
    finding,
    finding_description,
    tags,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .resource_arn = "ResourceArn",
        .resource_id = "ResourceId",
        .resource_type = "ResourceType",
        .last_refresh_timestamp = "LastRefreshTimestamp",
        .lookback_period_in_days = "LookbackPeriodInDays",
        .savings_opportunity = "SavingsOpportunity",
        .savings_opportunity_after_discount = "SavingsOpportunityAfterDiscount",
        .utilization_metrics_cpu_maximum = "UtilizationMetricsCpuMaximum",
        .utilization_metrics_memory_maximum = "UtilizationMetricsMemoryMaximum",
        .utilization_metrics_network_out_bytes_per_second_maximum = "UtilizationMetricsNetworkOutBytesPerSecondMaximum",
        .utilization_metrics_network_in_bytes_per_second_maximum = "UtilizationMetricsNetworkInBytesPerSecondMaximum",
        .utilization_metrics_database_connections_maximum = "UtilizationMetricsDatabaseConnectionsMaximum",
        .utilization_metrics_ebs_volume_read_iops_maximum = "UtilizationMetricsEBSVolumeReadIOPSMaximum",
        .utilization_metrics_ebs_volume_write_iops_maximum = "UtilizationMetricsEBSVolumeWriteIOPSMaximum",
        .utilization_metrics_volume_read_ops_per_second_maximum = "UtilizationMetricsVolumeReadOpsPerSecondMaximum",
        .utilization_metrics_volume_write_ops_per_second_maximum = "UtilizationMetricsVolumeWriteOpsPerSecondMaximum",
        .utilization_metrics_active_connection_count_maximum = "UtilizationMetricsActiveConnectionCountMaximum",
        .utilization_metrics_packets_in_from_source_maximum = "UtilizationMetricsPacketsInFromSourceMaximum",
        .utilization_metrics_packets_in_from_destination_maximum = "UtilizationMetricsPacketsInFromDestinationMaximum",
        .utilization_metrics_consumed_read_capacity_units_sum = "UtilizationMetricsConsumedReadCapacityUnitsSum",
        .utilization_metrics_consumed_write_capacity_units_sum = "UtilizationMetricsConsumedWriteCapacityUnitsSum",
        .utilization_metrics_new_connections_sum = "UtilizationMetricsNewConnectionsSum",
        .utilization_metrics_engine_cpu_utilization_maximum = "UtilizationMetricsEngineCPUUtilizationMaximum",
        .utilization_metrics_cache_hits_sum = "UtilizationMetricsCacheHitsSum",
        .utilization_metrics_cache_misses_sum = "UtilizationMetricsCacheMissesSum",
        .utilization_metrics_keyspace_hits_sum = "UtilizationMetricsKeyspaceHitsSum",
        .utilization_metrics_keyspace_misses_sum = "UtilizationMetricsKeyspaceMissesSum",
        .utilization_metrics_is_idle_minimum = "UtilizationMetricsIsIdleMinimum",
        .utilization_metrics_user_connected_sum = "UtilizationMetricsUserConnectedSum",
        .utilization_metrics_invocations_sum = "UtilizationMetricsInvocationsSum",
        .utilization_metrics_get_type_cmds_sum = "UtilizationMetricsGetTypeCmdsSum",
        .utilization_metrics_set_type_cmds_sum = "UtilizationMetricsSetTypeCmdsSum",
        .utilization_metrics_elasti_cache_processing_units_sum = "UtilizationMetricsElastiCacheProcessingUnitsSum",
        .utilization_metrics_curr_connections_sum = "UtilizationMetricsCurrConnectionsSum",
        .utilization_metrics_database_connections_sum = "UtilizationMetricsDatabaseConnectionsSum",
        .finding = "Finding",
        .finding_description = "FindingDescription",
        .tags = "Tags",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .account_id => "AccountId",
            .resource_arn => "ResourceArn",
            .resource_id => "ResourceId",
            .resource_type => "ResourceType",
            .last_refresh_timestamp => "LastRefreshTimestamp",
            .lookback_period_in_days => "LookbackPeriodInDays",
            .savings_opportunity => "SavingsOpportunity",
            .savings_opportunity_after_discount => "SavingsOpportunityAfterDiscount",
            .utilization_metrics_cpu_maximum => "UtilizationMetricsCpuMaximum",
            .utilization_metrics_memory_maximum => "UtilizationMetricsMemoryMaximum",
            .utilization_metrics_network_out_bytes_per_second_maximum => "UtilizationMetricsNetworkOutBytesPerSecondMaximum",
            .utilization_metrics_network_in_bytes_per_second_maximum => "UtilizationMetricsNetworkInBytesPerSecondMaximum",
            .utilization_metrics_database_connections_maximum => "UtilizationMetricsDatabaseConnectionsMaximum",
            .utilization_metrics_ebs_volume_read_iops_maximum => "UtilizationMetricsEBSVolumeReadIOPSMaximum",
            .utilization_metrics_ebs_volume_write_iops_maximum => "UtilizationMetricsEBSVolumeWriteIOPSMaximum",
            .utilization_metrics_volume_read_ops_per_second_maximum => "UtilizationMetricsVolumeReadOpsPerSecondMaximum",
            .utilization_metrics_volume_write_ops_per_second_maximum => "UtilizationMetricsVolumeWriteOpsPerSecondMaximum",
            .utilization_metrics_active_connection_count_maximum => "UtilizationMetricsActiveConnectionCountMaximum",
            .utilization_metrics_packets_in_from_source_maximum => "UtilizationMetricsPacketsInFromSourceMaximum",
            .utilization_metrics_packets_in_from_destination_maximum => "UtilizationMetricsPacketsInFromDestinationMaximum",
            .utilization_metrics_consumed_read_capacity_units_sum => "UtilizationMetricsConsumedReadCapacityUnitsSum",
            .utilization_metrics_consumed_write_capacity_units_sum => "UtilizationMetricsConsumedWriteCapacityUnitsSum",
            .utilization_metrics_new_connections_sum => "UtilizationMetricsNewConnectionsSum",
            .utilization_metrics_engine_cpu_utilization_maximum => "UtilizationMetricsEngineCPUUtilizationMaximum",
            .utilization_metrics_cache_hits_sum => "UtilizationMetricsCacheHitsSum",
            .utilization_metrics_cache_misses_sum => "UtilizationMetricsCacheMissesSum",
            .utilization_metrics_keyspace_hits_sum => "UtilizationMetricsKeyspaceHitsSum",
            .utilization_metrics_keyspace_misses_sum => "UtilizationMetricsKeyspaceMissesSum",
            .utilization_metrics_is_idle_minimum => "UtilizationMetricsIsIdleMinimum",
            .utilization_metrics_user_connected_sum => "UtilizationMetricsUserConnectedSum",
            .utilization_metrics_invocations_sum => "UtilizationMetricsInvocationsSum",
            .utilization_metrics_get_type_cmds_sum => "UtilizationMetricsGetTypeCmdsSum",
            .utilization_metrics_set_type_cmds_sum => "UtilizationMetricsSetTypeCmdsSum",
            .utilization_metrics_elasti_cache_processing_units_sum => "UtilizationMetricsElastiCacheProcessingUnitsSum",
            .utilization_metrics_curr_connections_sum => "UtilizationMetricsCurrConnectionsSum",
            .utilization_metrics_database_connections_sum => "UtilizationMetricsDatabaseConnectionsSum",
            .finding => "Finding",
            .finding_description => "FindingDescription",
            .tags => "Tags",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        const fields = @typeInfo(@TypeOf(json_field_names)).@"struct".field_names;
        inline for (fields) |field_name| {
            if (std.mem.eql(u8, str, @field(json_field_names, field_name))) {
                return @field(@This(), field_name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
