pub const ExportableInstanceField = enum {
    account_id,
    instance_arn,
    instance_name,
    finding,
    finding_reason_codes,
    lookback_period_in_days,
    current_instance_type,
    utilization_metrics_cpu_maximum,
    utilization_metrics_memory_maximum,
    utilization_metrics_ebs_read_ops_per_second_maximum,
    utilization_metrics_ebs_write_ops_per_second_maximum,
    utilization_metrics_ebs_read_bytes_per_second_maximum,
    utilization_metrics_ebs_write_bytes_per_second_maximum,
    utilization_metrics_disk_read_ops_per_second_maximum,
    utilization_metrics_disk_write_ops_per_second_maximum,
    utilization_metrics_disk_read_bytes_per_second_maximum,
    utilization_metrics_disk_write_bytes_per_second_maximum,
    utilization_metrics_network_in_bytes_per_second_maximum,
    utilization_metrics_network_out_bytes_per_second_maximum,
    utilization_metrics_network_packets_in_per_second_maximum,
    utilization_metrics_network_packets_out_per_second_maximum,
    current_on_demand_price,
    current_standard_one_year_no_upfront_reserved_price,
    current_standard_three_year_no_upfront_reserved_price,
    current_vcpus,
    current_memory,
    current_storage,
    current_network,
    recommendation_options_instance_type,
    recommendation_options_projected_utilization_metrics_cpu_maximum,
    recommendation_options_projected_utilization_metrics_memory_maximum,
    recommendation_options_platform_differences,
    recommendation_options_performance_risk,
    recommendation_options_vcpus,
    recommendation_options_memory,
    recommendation_options_storage,
    recommendation_options_network,
    recommendation_options_on_demand_price,
    recommendation_options_standard_one_year_no_upfront_reserved_price,
    recommendation_options_standard_three_year_no_upfront_reserved_price,
    recommendations_sources_recommendation_source_arn,
    recommendations_sources_recommendation_source_type,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    effective_recommendation_preferences_cpu_vendor_architectures,
    effective_recommendation_preferences_enhanced_infrastructure_metrics,
    effective_recommendation_preferences_inferred_workload_types,
    inferred_workload_types,
    recommendation_options_migration_effort,
    effective_recommendation_preferences_external_metrics_source,
    tags,
    instance_state,
    external_metric_status_code,
    external_metric_status_reason,
    current_instance_gpu_info,
    recommendation_options_instance_gpu_info,
    utilization_metrics_gpu_percentage_maximum,
    utilization_metrics_gpu_memory_percentage_maximum,
    recommendation_options_projected_utilization_metrics_gpu_percentage_maximum,
    recommendation_options_projected_utilization_metrics_gpu_memory_percentage_maximum,
    idle,
    effective_recommendation_preferences_preferred_resources,
    effective_recommendation_preferences_lookback_period,
    effective_recommendation_preferences_utilization_preferences,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "ACCOUNT_ID",
        .instance_arn = "INSTANCE_ARN",
        .instance_name = "INSTANCE_NAME",
        .finding = "FINDING",
        .finding_reason_codes = "Finding_Reason_Codes",
        .lookback_period_in_days = "LOOKBACK_PERIOD_IN_DAYS",
        .current_instance_type = "CURRENT_INSTANCE_TYPE",
        .utilization_metrics_cpu_maximum = "UTILIZATION_METRICS_CPU_MAXIMUM",
        .utilization_metrics_memory_maximum = "UTILIZATION_METRICS_MEMORY_MAXIMUM",
        .utilization_metrics_ebs_read_ops_per_second_maximum = "UTILIZATION_METRICS_EBS_READ_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_ebs_write_ops_per_second_maximum = "UTILIZATION_METRICS_EBS_WRITE_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_ebs_read_bytes_per_second_maximum = "UTILIZATION_METRICS_EBS_READ_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_ebs_write_bytes_per_second_maximum = "UTILIZATION_METRICS_EBS_WRITE_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_read_ops_per_second_maximum = "UTILIZATION_METRICS_DISK_READ_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_write_ops_per_second_maximum = "UTILIZATION_METRICS_DISK_WRITE_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_read_bytes_per_second_maximum = "UTILIZATION_METRICS_DISK_READ_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_disk_write_bytes_per_second_maximum = "UTILIZATION_METRICS_DISK_WRITE_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_in_bytes_per_second_maximum = "UTILIZATION_METRICS_NETWORK_IN_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_out_bytes_per_second_maximum = "UTILIZATION_METRICS_NETWORK_OUT_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_packets_in_per_second_maximum = "UTILIZATION_METRICS_NETWORK_PACKETS_IN_PER_SECOND_MAXIMUM",
        .utilization_metrics_network_packets_out_per_second_maximum = "UTILIZATION_METRICS_NETWORK_PACKETS_OUT_PER_SECOND_MAXIMUM",
        .current_on_demand_price = "CURRENT_ON_DEMAND_PRICE",
        .current_standard_one_year_no_upfront_reserved_price = "CURRENT_STANDARD_ONE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .current_standard_three_year_no_upfront_reserved_price = "CURRENT_STANDARD_THREE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .current_vcpus = "CURRENT_VCPUS",
        .current_memory = "CURRENT_MEMORY",
        .current_storage = "CURRENT_STORAGE",
        .current_network = "CURRENT_NETWORK",
        .recommendation_options_instance_type = "RECOMMENDATION_OPTIONS_INSTANCE_TYPE",
        .recommendation_options_projected_utilization_metrics_cpu_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_CPU_MAXIMUM",
        .recommendation_options_projected_utilization_metrics_memory_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_MEMORY_MAXIMUM",
        .recommendation_options_platform_differences = "RECOMMENDATION_OPTIONS_PLATFORM_DIFFERENCES",
        .recommendation_options_performance_risk = "RECOMMENDATION_OPTIONS_PERFORMANCE_RISK",
        .recommendation_options_vcpus = "RECOMMENDATION_OPTIONS_VCPUS",
        .recommendation_options_memory = "RECOMMENDATION_OPTIONS_MEMORY",
        .recommendation_options_storage = "RECOMMENDATION_OPTIONS_STORAGE",
        .recommendation_options_network = "RECOMMENDATION_OPTIONS_NETWORK",
        .recommendation_options_on_demand_price = "RECOMMENDATION_OPTIONS_ON_DEMAND_PRICE",
        .recommendation_options_standard_one_year_no_upfront_reserved_price = "RECOMMENDATION_OPTIONS_STANDARD_ONE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .recommendation_options_standard_three_year_no_upfront_reserved_price = "RECOMMENDATION_OPTIONS_STANDARD_THREE_YEAR_NO_UPFRONT_RESERVED_PRICE",
        .recommendations_sources_recommendation_source_arn = "RECOMMENDATIONS_SOURCES_RECOMMENDATION_SOURCE_ARN",
        .recommendations_sources_recommendation_source_type = "RECOMMENDATIONS_SOURCES_RECOMMENDATION_SOURCE_TYPE",
        .last_refresh_timestamp = "LAST_REFRESH_TIMESTAMP",
        .current_performance_risk = "CURRENT_PERFORMANCE_RISK",
        .recommendation_options_savings_opportunity_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY",
        .recommendation_options_estimated_monthly_savings_value = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE",
        .effective_recommendation_preferences_cpu_vendor_architectures = "EFFECTIVE_RECOMMENDATION_PREFERENCES_CPU_VENDOR_ARCHITECTURES",
        .effective_recommendation_preferences_enhanced_infrastructure_metrics = "EFFECTIVE_RECOMMENDATION_PREFERENCES_ENHANCED_INFRASTRUCTURE_METRICS",
        .effective_recommendation_preferences_inferred_workload_types = "EFFECTIVE_RECOMMENDATION_PREFERENCES_INFERRED_WORKLOAD_TYPES",
        .inferred_workload_types = "INFERRED_WORKLOAD_TYPES",
        .recommendation_options_migration_effort = "RECOMMENDATION_OPTIONS_MIGRATION_EFFORT",
        .effective_recommendation_preferences_external_metrics_source = "EFFECTIVE_RECOMMENDATION_PREFERENCES_EXTERNAL_METRICS_SOURCE",
        .tags = "TAGS",
        .instance_state = "INSTANCE_STATE",
        .external_metric_status_code = "EXTERNAL_METRIC_STATUS_CODE",
        .external_metric_status_reason = "EXTERNAL_METRIC_STATUS_REASON",
        .current_instance_gpu_info = "CURRENT_INSTANCE_GPU_INFO",
        .recommendation_options_instance_gpu_info = "RECOMMENDATION_OPTIONS_INSTANCE_GPU_INFO",
        .utilization_metrics_gpu_percentage_maximum = "UTILIZATION_METRICS_GPU_PERCENTAGE_MAXIMUM",
        .utilization_metrics_gpu_memory_percentage_maximum = "UTILIZATION_METRICS_GPU_MEMORY_PERCENTAGE_MAXIMUM",
        .recommendation_options_projected_utilization_metrics_gpu_percentage_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_GPU_PERCENTAGE_MAXIMUM",
        .recommendation_options_projected_utilization_metrics_gpu_memory_percentage_maximum = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_GPU_MEMORY_PERCENTAGE_MAXIMUM",
        .idle = "IDLE",
        .effective_recommendation_preferences_preferred_resources = "EFFECTIVE_RECOMMENDATION_PREFERENCES_PREFERRED_RESOURCES",
        .effective_recommendation_preferences_lookback_period = "EFFECTIVE_RECOMMENDATION_PREFERENCES_LOOKBACK_PERIOD",
        .effective_recommendation_preferences_utilization_preferences = "EFFECTIVE_RECOMMENDATION_PREFERENCES_UTILIZATION_PREFERENCES",
        .effective_recommendation_preferences_savings_estimation_mode = "EFFECTIVE_RECOMMENDATION_PREFERENCES_SAVINGS_ESTIMATION_MODE",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_AFTER_DISCOUNTS_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY_AFTER_DISCOUNTS",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE_AFTER_DISCOUNTS",
    };
};
