const std = @import("std");

pub const ExportableRDSDBField = enum {
    resource_arn,
    account_id,
    engine,
    engine_version,
    idle,
    multi_az_db_instance,
    cluster_writer,
    current_db_instance_class,
    current_storage_configuration_storage_type,
    current_storage_configuration_allocated_storage,
    current_storage_configuration_max_allocated_storage,
    current_storage_configuration_iops,
    current_storage_configuration_storage_throughput,
    current_storage_estimated_monthly_volume_iops_cost_variation,
    current_instance_on_demand_hourly_price,
    current_storage_on_demand_monthly_price,
    lookback_period_in_days,
    current_storage_estimated_cluster_instance_on_demand_monthly_cost,
    current_storage_estimated_cluster_storage_on_demand_monthly_cost,
    current_storage_estimated_cluster_storage_io_on_demand_monthly_cost,
    current_instance_performance_risk,
    utilization_metrics_cpu_maximum,
    utilization_metrics_memory_maximum,
    utilization_metrics_ebs_volume_storage_space_utilization_maximum,
    utilization_metrics_network_receive_throughput_maximum,
    utilization_metrics_network_transmit_throughput_maximum,
    utilization_metrics_ebs_volume_read_iops_maximum,
    utilization_metrics_ebs_volume_write_iops_maximum,
    utilization_metrics_ebs_volume_read_throughput_maximum,
    utilization_metrics_ebs_volume_write_throughput_maximum,
    utilization_metrics_database_connections_maximum,
    utilization_metrics_storage_network_receive_throughput_maximum,
    utilization_metrics_storage_network_transmit_throughput_maximum,
    utilization_metrics_aurora_memory_health_state_maximum,
    utilization_metrics_aurora_memory_num_declined_sql_total_maximum,
    utilization_metrics_aurora_memory_num_kill_conn_total_maximum,
    utilization_metrics_aurora_memory_num_kill_query_total_maximum,
    utilization_metrics_read_iops_ephemeral_storage_maximum,
    utilization_metrics_write_iops_ephemeral_storage_maximum,
    utilization_metrics_volume_bytes_used_average,
    utilization_metrics_volume_read_iops_average,
    utilization_metrics_volume_write_iops_average,
    instance_finding,
    instance_finding_reason_codes,
    storage_finding,
    storage_finding_reason_codes,
    instance_recommendation_options_db_instance_class,
    instance_recommendation_options_rank,
    instance_recommendation_options_performance_risk,
    instance_recommendation_options_projected_utilization_metrics_cpu_maximum,
    storage_recommendation_options_storage_type,
    storage_recommendation_options_allocated_storage,
    storage_recommendation_options_max_allocated_storage,
    storage_recommendation_options_iops,
    storage_recommendation_options_storage_throughput,
    storage_recommendation_options_rank,
    storage_recommendation_options_estimated_monthly_volume_iops_cost_variation,
    instance_recommendation_options_instance_on_demand_hourly_price,
    instance_recommendation_options_savings_opportunity_percentage,
    instance_recommendation_options_estimated_monthly_savings_currency,
    instance_recommendation_options_estimated_monthly_savings_value,
    instance_recommendation_options_savings_opportunity_after_discounts_percentage,
    instance_recommendation_options_estimated_monthly_savings_currency_after_discounts,
    instance_recommendation_options_estimated_monthly_savings_value_after_discounts,
    storage_recommendation_options_on_demand_monthly_price,
    storage_recommendation_options_estimated_cluster_instance_on_demand_monthly_cost,
    storage_recommendation_options_estimated_cluster_storage_on_demand_monthly_cost,
    storage_recommendation_options_estimated_cluster_storage_io_on_demand_monthly_cost,
    storage_recommendation_options_savings_opportunity_percentage,
    storage_recommendation_options_estimated_monthly_savings_currency,
    storage_recommendation_options_estimated_monthly_savings_value,
    storage_recommendation_options_savings_opportunity_after_discounts_percentage,
    storage_recommendation_options_estimated_monthly_savings_currency_after_discounts,
    storage_recommendation_options_estimated_monthly_savings_value_after_discounts,
    effective_recommendation_preferences_cpu_vendor_architectures,
    effective_recommendation_preferences_enhanced_infrastructure_metrics,
    effective_recommendation_preferences_lookback_period,
    effective_recommendation_preferences_savings_estimation_mode,
    last_refresh_timestamp,
    tags,
    db_cluster_identifier,
    promotion_tier,

    pub const json_field_names = .{
        .resource_arn = "ResourceArn",
        .account_id = "AccountId",
        .engine = "Engine",
        .engine_version = "EngineVersion",
        .idle = "Idle",
        .multi_az_db_instance = "MultiAZDBInstance",
        .cluster_writer = "ClusterWriter",
        .current_db_instance_class = "CurrentDBInstanceClass",
        .current_storage_configuration_storage_type = "CurrentStorageConfigurationStorageType",
        .current_storage_configuration_allocated_storage = "CurrentStorageConfigurationAllocatedStorage",
        .current_storage_configuration_max_allocated_storage = "CurrentStorageConfigurationMaxAllocatedStorage",
        .current_storage_configuration_iops = "CurrentStorageConfigurationIOPS",
        .current_storage_configuration_storage_throughput = "CurrentStorageConfigurationStorageThroughput",
        .current_storage_estimated_monthly_volume_iops_cost_variation = "CurrentStorageEstimatedMonthlyVolumeIOPsCostVariation",
        .current_instance_on_demand_hourly_price = "CurrentInstanceOnDemandHourlyPrice",
        .current_storage_on_demand_monthly_price = "CurrentStorageOnDemandMonthlyPrice",
        .lookback_period_in_days = "LookbackPeriodInDays",
        .current_storage_estimated_cluster_instance_on_demand_monthly_cost = "CurrentStorageEstimatedClusterInstanceOnDemandMonthlyCost",
        .current_storage_estimated_cluster_storage_on_demand_monthly_cost = "CurrentStorageEstimatedClusterStorageOnDemandMonthlyCost",
        .current_storage_estimated_cluster_storage_io_on_demand_monthly_cost = "CurrentStorageEstimatedClusterStorageIOOnDemandMonthlyCost",
        .current_instance_performance_risk = "CurrentInstancePerformanceRisk",
        .utilization_metrics_cpu_maximum = "UtilizationMetricsCpuMaximum",
        .utilization_metrics_memory_maximum = "UtilizationMetricsMemoryMaximum",
        .utilization_metrics_ebs_volume_storage_space_utilization_maximum = "UtilizationMetricsEBSVolumeStorageSpaceUtilizationMaximum",
        .utilization_metrics_network_receive_throughput_maximum = "UtilizationMetricsNetworkReceiveThroughputMaximum",
        .utilization_metrics_network_transmit_throughput_maximum = "UtilizationMetricsNetworkTransmitThroughputMaximum",
        .utilization_metrics_ebs_volume_read_iops_maximum = "UtilizationMetricsEBSVolumeReadIOPSMaximum",
        .utilization_metrics_ebs_volume_write_iops_maximum = "UtilizationMetricsEBSVolumeWriteIOPSMaximum",
        .utilization_metrics_ebs_volume_read_throughput_maximum = "UtilizationMetricsEBSVolumeReadThroughputMaximum",
        .utilization_metrics_ebs_volume_write_throughput_maximum = "UtilizationMetricsEBSVolumeWriteThroughputMaximum",
        .utilization_metrics_database_connections_maximum = "UtilizationMetricsDatabaseConnectionsMaximum",
        .utilization_metrics_storage_network_receive_throughput_maximum = "UtilizationMetricsStorageNetworkReceiveThroughputMaximum",
        .utilization_metrics_storage_network_transmit_throughput_maximum = "UtilizationMetricsStorageNetworkTransmitThroughputMaximum",
        .utilization_metrics_aurora_memory_health_state_maximum = "UtilizationMetricsAuroraMemoryHealthStateMaximum",
        .utilization_metrics_aurora_memory_num_declined_sql_total_maximum = "UtilizationMetricsAuroraMemoryNumDeclinedSqlTotalMaximum",
        .utilization_metrics_aurora_memory_num_kill_conn_total_maximum = "UtilizationMetricsAuroraMemoryNumKillConnTotalMaximum",
        .utilization_metrics_aurora_memory_num_kill_query_total_maximum = "UtilizationMetricsAuroraMemoryNumKillQueryTotalMaximum",
        .utilization_metrics_read_iops_ephemeral_storage_maximum = "UtilizationMetricsReadIOPSEphemeralStorageMaximum",
        .utilization_metrics_write_iops_ephemeral_storage_maximum = "UtilizationMetricsWriteIOPSEphemeralStorageMaximum",
        .utilization_metrics_volume_bytes_used_average = "UtilizationMetricsVolumeBytesUsedAverage",
        .utilization_metrics_volume_read_iops_average = "UtilizationMetricsVolumeReadIOPsAverage",
        .utilization_metrics_volume_write_iops_average = "UtilizationMetricsVolumeWriteIOPsAverage",
        .instance_finding = "InstanceFinding",
        .instance_finding_reason_codes = "InstanceFindingReasonCodes",
        .storage_finding = "StorageFinding",
        .storage_finding_reason_codes = "StorageFindingReasonCodes",
        .instance_recommendation_options_db_instance_class = "InstanceRecommendationOptionsDBInstanceClass",
        .instance_recommendation_options_rank = "InstanceRecommendationOptionsRank",
        .instance_recommendation_options_performance_risk = "InstanceRecommendationOptionsPerformanceRisk",
        .instance_recommendation_options_projected_utilization_metrics_cpu_maximum = "InstanceRecommendationOptionsProjectedUtilizationMetricsCpuMaximum",
        .storage_recommendation_options_storage_type = "StorageRecommendationOptionsStorageType",
        .storage_recommendation_options_allocated_storage = "StorageRecommendationOptionsAllocatedStorage",
        .storage_recommendation_options_max_allocated_storage = "StorageRecommendationOptionsMaxAllocatedStorage",
        .storage_recommendation_options_iops = "StorageRecommendationOptionsIOPS",
        .storage_recommendation_options_storage_throughput = "StorageRecommendationOptionsStorageThroughput",
        .storage_recommendation_options_rank = "StorageRecommendationOptionsRank",
        .storage_recommendation_options_estimated_monthly_volume_iops_cost_variation = "StorageRecommendationOptionsEstimatedMonthlyVolumeIOPsCostVariation",
        .instance_recommendation_options_instance_on_demand_hourly_price = "InstanceRecommendationOptionsInstanceOnDemandHourlyPrice",
        .instance_recommendation_options_savings_opportunity_percentage = "InstanceRecommendationOptionsSavingsOpportunityPercentage",
        .instance_recommendation_options_estimated_monthly_savings_currency = "InstanceRecommendationOptionsEstimatedMonthlySavingsCurrency",
        .instance_recommendation_options_estimated_monthly_savings_value = "InstanceRecommendationOptionsEstimatedMonthlySavingsValue",
        .instance_recommendation_options_savings_opportunity_after_discounts_percentage = "InstanceRecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
        .instance_recommendation_options_estimated_monthly_savings_currency_after_discounts = "InstanceRecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
        .instance_recommendation_options_estimated_monthly_savings_value_after_discounts = "InstanceRecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
        .storage_recommendation_options_on_demand_monthly_price = "StorageRecommendationOptionsOnDemandMonthlyPrice",
        .storage_recommendation_options_estimated_cluster_instance_on_demand_monthly_cost = "StorageRecommendationOptionsEstimatedClusterInstanceOnDemandMonthlyCost",
        .storage_recommendation_options_estimated_cluster_storage_on_demand_monthly_cost = "StorageRecommendationOptionsEstimatedClusterStorageOnDemandMonthlyCost",
        .storage_recommendation_options_estimated_cluster_storage_io_on_demand_monthly_cost = "StorageRecommendationOptionsEstimatedClusterStorageIOOnDemandMonthlyCost",
        .storage_recommendation_options_savings_opportunity_percentage = "StorageRecommendationOptionsSavingsOpportunityPercentage",
        .storage_recommendation_options_estimated_monthly_savings_currency = "StorageRecommendationOptionsEstimatedMonthlySavingsCurrency",
        .storage_recommendation_options_estimated_monthly_savings_value = "StorageRecommendationOptionsEstimatedMonthlySavingsValue",
        .storage_recommendation_options_savings_opportunity_after_discounts_percentage = "StorageRecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
        .storage_recommendation_options_estimated_monthly_savings_currency_after_discounts = "StorageRecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
        .storage_recommendation_options_estimated_monthly_savings_value_after_discounts = "StorageRecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
        .effective_recommendation_preferences_cpu_vendor_architectures = "EffectiveRecommendationPreferencesCpuVendorArchitectures",
        .effective_recommendation_preferences_enhanced_infrastructure_metrics = "EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics",
        .effective_recommendation_preferences_lookback_period = "EffectiveRecommendationPreferencesLookBackPeriod",
        .effective_recommendation_preferences_savings_estimation_mode = "EffectiveRecommendationPreferencesSavingsEstimationMode",
        .last_refresh_timestamp = "LastRefreshTimestamp",
        .tags = "Tags",
        .db_cluster_identifier = "DBClusterIdentifier",
        .promotion_tier = "PromotionTier",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .resource_arn => "ResourceArn",
            .account_id => "AccountId",
            .engine => "Engine",
            .engine_version => "EngineVersion",
            .idle => "Idle",
            .multi_az_db_instance => "MultiAZDBInstance",
            .cluster_writer => "ClusterWriter",
            .current_db_instance_class => "CurrentDBInstanceClass",
            .current_storage_configuration_storage_type => "CurrentStorageConfigurationStorageType",
            .current_storage_configuration_allocated_storage => "CurrentStorageConfigurationAllocatedStorage",
            .current_storage_configuration_max_allocated_storage => "CurrentStorageConfigurationMaxAllocatedStorage",
            .current_storage_configuration_iops => "CurrentStorageConfigurationIOPS",
            .current_storage_configuration_storage_throughput => "CurrentStorageConfigurationStorageThroughput",
            .current_storage_estimated_monthly_volume_iops_cost_variation => "CurrentStorageEstimatedMonthlyVolumeIOPsCostVariation",
            .current_instance_on_demand_hourly_price => "CurrentInstanceOnDemandHourlyPrice",
            .current_storage_on_demand_monthly_price => "CurrentStorageOnDemandMonthlyPrice",
            .lookback_period_in_days => "LookbackPeriodInDays",
            .current_storage_estimated_cluster_instance_on_demand_monthly_cost => "CurrentStorageEstimatedClusterInstanceOnDemandMonthlyCost",
            .current_storage_estimated_cluster_storage_on_demand_monthly_cost => "CurrentStorageEstimatedClusterStorageOnDemandMonthlyCost",
            .current_storage_estimated_cluster_storage_io_on_demand_monthly_cost => "CurrentStorageEstimatedClusterStorageIOOnDemandMonthlyCost",
            .current_instance_performance_risk => "CurrentInstancePerformanceRisk",
            .utilization_metrics_cpu_maximum => "UtilizationMetricsCpuMaximum",
            .utilization_metrics_memory_maximum => "UtilizationMetricsMemoryMaximum",
            .utilization_metrics_ebs_volume_storage_space_utilization_maximum => "UtilizationMetricsEBSVolumeStorageSpaceUtilizationMaximum",
            .utilization_metrics_network_receive_throughput_maximum => "UtilizationMetricsNetworkReceiveThroughputMaximum",
            .utilization_metrics_network_transmit_throughput_maximum => "UtilizationMetricsNetworkTransmitThroughputMaximum",
            .utilization_metrics_ebs_volume_read_iops_maximum => "UtilizationMetricsEBSVolumeReadIOPSMaximum",
            .utilization_metrics_ebs_volume_write_iops_maximum => "UtilizationMetricsEBSVolumeWriteIOPSMaximum",
            .utilization_metrics_ebs_volume_read_throughput_maximum => "UtilizationMetricsEBSVolumeReadThroughputMaximum",
            .utilization_metrics_ebs_volume_write_throughput_maximum => "UtilizationMetricsEBSVolumeWriteThroughputMaximum",
            .utilization_metrics_database_connections_maximum => "UtilizationMetricsDatabaseConnectionsMaximum",
            .utilization_metrics_storage_network_receive_throughput_maximum => "UtilizationMetricsStorageNetworkReceiveThroughputMaximum",
            .utilization_metrics_storage_network_transmit_throughput_maximum => "UtilizationMetricsStorageNetworkTransmitThroughputMaximum",
            .utilization_metrics_aurora_memory_health_state_maximum => "UtilizationMetricsAuroraMemoryHealthStateMaximum",
            .utilization_metrics_aurora_memory_num_declined_sql_total_maximum => "UtilizationMetricsAuroraMemoryNumDeclinedSqlTotalMaximum",
            .utilization_metrics_aurora_memory_num_kill_conn_total_maximum => "UtilizationMetricsAuroraMemoryNumKillConnTotalMaximum",
            .utilization_metrics_aurora_memory_num_kill_query_total_maximum => "UtilizationMetricsAuroraMemoryNumKillQueryTotalMaximum",
            .utilization_metrics_read_iops_ephemeral_storage_maximum => "UtilizationMetricsReadIOPSEphemeralStorageMaximum",
            .utilization_metrics_write_iops_ephemeral_storage_maximum => "UtilizationMetricsWriteIOPSEphemeralStorageMaximum",
            .utilization_metrics_volume_bytes_used_average => "UtilizationMetricsVolumeBytesUsedAverage",
            .utilization_metrics_volume_read_iops_average => "UtilizationMetricsVolumeReadIOPsAverage",
            .utilization_metrics_volume_write_iops_average => "UtilizationMetricsVolumeWriteIOPsAverage",
            .instance_finding => "InstanceFinding",
            .instance_finding_reason_codes => "InstanceFindingReasonCodes",
            .storage_finding => "StorageFinding",
            .storage_finding_reason_codes => "StorageFindingReasonCodes",
            .instance_recommendation_options_db_instance_class => "InstanceRecommendationOptionsDBInstanceClass",
            .instance_recommendation_options_rank => "InstanceRecommendationOptionsRank",
            .instance_recommendation_options_performance_risk => "InstanceRecommendationOptionsPerformanceRisk",
            .instance_recommendation_options_projected_utilization_metrics_cpu_maximum => "InstanceRecommendationOptionsProjectedUtilizationMetricsCpuMaximum",
            .storage_recommendation_options_storage_type => "StorageRecommendationOptionsStorageType",
            .storage_recommendation_options_allocated_storage => "StorageRecommendationOptionsAllocatedStorage",
            .storage_recommendation_options_max_allocated_storage => "StorageRecommendationOptionsMaxAllocatedStorage",
            .storage_recommendation_options_iops => "StorageRecommendationOptionsIOPS",
            .storage_recommendation_options_storage_throughput => "StorageRecommendationOptionsStorageThroughput",
            .storage_recommendation_options_rank => "StorageRecommendationOptionsRank",
            .storage_recommendation_options_estimated_monthly_volume_iops_cost_variation => "StorageRecommendationOptionsEstimatedMonthlyVolumeIOPsCostVariation",
            .instance_recommendation_options_instance_on_demand_hourly_price => "InstanceRecommendationOptionsInstanceOnDemandHourlyPrice",
            .instance_recommendation_options_savings_opportunity_percentage => "InstanceRecommendationOptionsSavingsOpportunityPercentage",
            .instance_recommendation_options_estimated_monthly_savings_currency => "InstanceRecommendationOptionsEstimatedMonthlySavingsCurrency",
            .instance_recommendation_options_estimated_monthly_savings_value => "InstanceRecommendationOptionsEstimatedMonthlySavingsValue",
            .instance_recommendation_options_savings_opportunity_after_discounts_percentage => "InstanceRecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
            .instance_recommendation_options_estimated_monthly_savings_currency_after_discounts => "InstanceRecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
            .instance_recommendation_options_estimated_monthly_savings_value_after_discounts => "InstanceRecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
            .storage_recommendation_options_on_demand_monthly_price => "StorageRecommendationOptionsOnDemandMonthlyPrice",
            .storage_recommendation_options_estimated_cluster_instance_on_demand_monthly_cost => "StorageRecommendationOptionsEstimatedClusterInstanceOnDemandMonthlyCost",
            .storage_recommendation_options_estimated_cluster_storage_on_demand_monthly_cost => "StorageRecommendationOptionsEstimatedClusterStorageOnDemandMonthlyCost",
            .storage_recommendation_options_estimated_cluster_storage_io_on_demand_monthly_cost => "StorageRecommendationOptionsEstimatedClusterStorageIOOnDemandMonthlyCost",
            .storage_recommendation_options_savings_opportunity_percentage => "StorageRecommendationOptionsSavingsOpportunityPercentage",
            .storage_recommendation_options_estimated_monthly_savings_currency => "StorageRecommendationOptionsEstimatedMonthlySavingsCurrency",
            .storage_recommendation_options_estimated_monthly_savings_value => "StorageRecommendationOptionsEstimatedMonthlySavingsValue",
            .storage_recommendation_options_savings_opportunity_after_discounts_percentage => "StorageRecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
            .storage_recommendation_options_estimated_monthly_savings_currency_after_discounts => "StorageRecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
            .storage_recommendation_options_estimated_monthly_savings_value_after_discounts => "StorageRecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
            .effective_recommendation_preferences_cpu_vendor_architectures => "EffectiveRecommendationPreferencesCpuVendorArchitectures",
            .effective_recommendation_preferences_enhanced_infrastructure_metrics => "EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics",
            .effective_recommendation_preferences_lookback_period => "EffectiveRecommendationPreferencesLookBackPeriod",
            .effective_recommendation_preferences_savings_estimation_mode => "EffectiveRecommendationPreferencesSavingsEstimationMode",
            .last_refresh_timestamp => "LastRefreshTimestamp",
            .tags => "Tags",
            .db_cluster_identifier => "DBClusterIdentifier",
            .promotion_tier => "PromotionTier",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
