pub const ExportableRDSDBField = enum {
    resource_arn,
    account_id,
    engine,
    engine_version,
    idle,
    multi_az_db_instance,
    cluster_writer,
    current_db_instance_class,
    current_storage_configuration_storage_type,
    current_storage_configuration_allocated_storage,
    current_storage_configuration_max_allocated_storage,
    current_storage_configuration_iops,
    current_storage_configuration_storage_throughput,
    current_storage_estimated_monthly_volume_iops_cost_variation,
    current_instance_on_demand_hourly_price,
    current_storage_on_demand_monthly_price,
    lookback_period_in_days,
    current_storage_estimated_cluster_instance_on_demand_monthly_cost,
    current_storage_estimated_cluster_storage_on_demand_monthly_cost,
    current_storage_estimated_cluster_storage_io_on_demand_monthly_cost,
    current_instance_performance_risk,
    utilization_metrics_cpu_maximum,
    utilization_metrics_memory_maximum,
    utilization_metrics_ebs_volume_storage_space_utilization_maximum,
    utilization_metrics_network_receive_throughput_maximum,
    utilization_metrics_network_transmit_throughput_maximum,
    utilization_metrics_ebs_volume_read_iops_maximum,
    utilization_metrics_ebs_volume_write_iops_maximum,
    utilization_metrics_ebs_volume_read_throughput_maximum,
    utilization_metrics_ebs_volume_write_throughput_maximum,
    utilization_metrics_database_connections_maximum,
    utilization_metrics_storage_network_receive_throughput_maximum,
    utilization_metrics_storage_network_transmit_throughput_maximum,
    utilization_metrics_aurora_memory_health_state_maximum,
    utilization_metrics_aurora_memory_num_declined_sql_total_maximum,
    utilization_metrics_aurora_memory_num_kill_conn_total_maximum,
    utilization_metrics_aurora_memory_num_kill_query_total_maximum,
    utilization_metrics_read_iops_ephemeral_storage_maximum,
    utilization_metrics_write_iops_ephemeral_storage_maximum,
    utilization_metrics_volume_bytes_used_average,
    utilization_metrics_volume_read_iops_average,
    utilization_metrics_volume_write_iops_average,
    instance_finding,
    instance_finding_reason_codes,
    storage_finding,
    storage_finding_reason_codes,
    instance_recommendation_options_db_instance_class,
    instance_recommendation_options_rank,
    instance_recommendation_options_performance_risk,
    instance_recommendation_options_projected_utilization_metrics_cpu_maximum,
    storage_recommendation_options_storage_type,
    storage_recommendation_options_allocated_storage,
    storage_recommendation_options_max_allocated_storage,
    storage_recommendation_options_iops,
    storage_recommendation_options_storage_throughput,
    storage_recommendation_options_rank,
    storage_recommendation_options_estimated_monthly_volume_iops_cost_variation,
    instance_recommendation_options_instance_on_demand_hourly_price,
    instance_recommendation_options_savings_opportunity_percentage,
    instance_recommendation_options_estimated_monthly_savings_currency,
    instance_recommendation_options_estimated_monthly_savings_value,
    instance_recommendation_options_savings_opportunity_after_discounts_percentage,
    instance_recommendation_options_estimated_monthly_savings_currency_after_discounts,
    instance_recommendation_options_estimated_monthly_savings_value_after_discounts,
    storage_recommendation_options_on_demand_monthly_price,
    storage_recommendation_options_estimated_cluster_instance_on_demand_monthly_cost,
    storage_recommendation_options_estimated_cluster_storage_on_demand_monthly_cost,
    storage_recommendation_options_estimated_cluster_storage_io_on_demand_monthly_cost,
    storage_recommendation_options_savings_opportunity_percentage,
    storage_recommendation_options_estimated_monthly_savings_currency,
    storage_recommendation_options_estimated_monthly_savings_value,
    storage_recommendation_options_savings_opportunity_after_discounts_percentage,
    storage_recommendation_options_estimated_monthly_savings_currency_after_discounts,
    storage_recommendation_options_estimated_monthly_savings_value_after_discounts,
    effective_recommendation_preferences_cpu_vendor_architectures,
    effective_recommendation_preferences_enhanced_infrastructure_metrics,
    effective_recommendation_preferences_lookback_period,
    effective_recommendation_preferences_savings_estimation_mode,
    last_refresh_timestamp,
    tags,
    db_cluster_identifier,
    promotion_tier,

    pub const json_field_names = .{
        .resource_arn = "RESOURCE_ARN",
        .account_id = "ACCOUNT_ID",
        .engine = "ENGINE",
        .engine_version = "ENGINE_VERSION",
        .idle = "IDLE",
        .multi_az_db_instance = "MULTI_AZ_DB_INSTANCE",
        .cluster_writer = "CLUSTER_WRITER",
        .current_db_instance_class = "CURRENT_DB_INSTANCE_CLASS",
        .current_storage_configuration_storage_type = "CURRENT_STORAGE_CONFIGURATION_STORAGE_TYPE",
        .current_storage_configuration_allocated_storage = "CURRENT_STORAGE_CONFIGURATION_ALLOCATED_STORAGE",
        .current_storage_configuration_max_allocated_storage = "CURRENT_STORAGE_CONFIGURATION_MAX_ALLOCATED_STORAGE",
        .current_storage_configuration_iops = "CURRENT_STORAGE_CONFIGURATION_IOPS",
        .current_storage_configuration_storage_throughput = "CURRENT_STORAGE_CONFIGURATION_STORAGE_THROUGHPUT",
        .current_storage_estimated_monthly_volume_iops_cost_variation = "CURRENT_STORAGE_ESTIMATED_MONTHLY_VOLUME_IOPS_COST_VARIATION",
        .current_instance_on_demand_hourly_price = "CURRENT_INSTANCE_ON_DEMAND_HOURLY_PRICE",
        .current_storage_on_demand_monthly_price = "CURRENT_STORAGE_ON_DEMAND_MONTHLY_PRICE",
        .lookback_period_in_days = "LOOKBACK_PERIOD_IN_DAYS",
        .current_storage_estimated_cluster_instance_on_demand_monthly_cost = "CURRENT_STORAGE_ESTIMATED_CLUSTER_INSTANCE_ON_DEMAND_MONTHLY_COST",
        .current_storage_estimated_cluster_storage_on_demand_monthly_cost = "CURRENT_STORAGE_ESTIMATED_CLUSTER_STORAGE_ON_DEMAND_MONTHLY_COST",
        .current_storage_estimated_cluster_storage_io_on_demand_monthly_cost = "CURRENT_STORAGE_ESTIMATED_CLUSTER_STORAGE_IO_ON_DEMAND_MONTHLY_COST",
        .current_instance_performance_risk = "CURRENT_INSTANCE_PERFORMANCE_RISK",
        .utilization_metrics_cpu_maximum = "UTILIZATION_METRICS_CPU_MAXIMUM",
        .utilization_metrics_memory_maximum = "UTILIZATION_METRICS_MEMORY_MAXIMUM",
        .utilization_metrics_ebs_volume_storage_space_utilization_maximum = "UTILIZATION_METRICS_EBS_VOLUME_STORAGE_SPACE_UTILIZATION_MAXIMUM",
        .utilization_metrics_network_receive_throughput_maximum = "UTILIZATION_METRICS_NETWORK_RECEIVE_THROUGHPUT_MAXIMUM",
        .utilization_metrics_network_transmit_throughput_maximum = "UTILIZATION_METRICS_NETWORK_TRANSMIT_THROUGHPUT_MAXIMUM",
        .utilization_metrics_ebs_volume_read_iops_maximum = "UTILIZATION_METRICS_EBS_VOLUME_READ_IOPS_MAXIMUM",
        .utilization_metrics_ebs_volume_write_iops_maximum = "UTILIZATION_METRICS_EBS_VOLUME_WRITE_IOPS_MAXIMUM",
        .utilization_metrics_ebs_volume_read_throughput_maximum = "UTILIZATION_METRICS_EBS_VOLUME_READ_THROUGHPUT_MAXIMUM",
        .utilization_metrics_ebs_volume_write_throughput_maximum = "UTILIZATION_METRICS_EBS_VOLUME_WRITE_THROUGHPUT_MAXIMUM",
        .utilization_metrics_database_connections_maximum = "UTILIZATION_METRICS_DATABASE_CONNECTIONS_MAXIMUM",
        .utilization_metrics_storage_network_receive_throughput_maximum = "UTILIZATION_METRICS_STORAGE_NETWORK_RECEIVE_THROUGHPUT_MAXIMUM",
        .utilization_metrics_storage_network_transmit_throughput_maximum = "UTILIZATION_METRICS_STORAGE_NETWORK_TRANSMIT_THROUGHPUT_MAXIMUM",
        .utilization_metrics_aurora_memory_health_state_maximum = "UTILIZATION_METRICS_AURORA_MEMORY_HEALTH_STATE_MAXIMUM",
        .utilization_metrics_aurora_memory_num_declined_sql_total_maximum = "UTILIZATION_METRICS_AURORA_MEMORY_NUM_DECLINED_SQL_TOTAL_MAXIMUM",
        .utilization_metrics_aurora_memory_num_kill_conn_total_maximum = "UTILIZATION_METRICS_AURORA_MEMORY_NUM_KILL_CONN_TOTAL_MAXIMUM",
        .utilization_metrics_aurora_memory_num_kill_query_total_maximum = "UTILIZATION_METRICS_AURORA_MEMORY_NUM_KILL_QUERY_TOTAL_MAXIMUM",
        .utilization_metrics_read_iops_ephemeral_storage_maximum = "UTILIZATION_METRICS_READ_IOPS_EPHEMERAL_STORAGE_MAXIMUM",
        .utilization_metrics_write_iops_ephemeral_storage_maximum = "UTILIZATION_METRICS_WRITE_IOPS_EPHEMERAL_STORAGE_MAXIMUM",
        .utilization_metrics_volume_bytes_used_average = "UTILIZATION_METRICS_VOLUME_BYTES_USED_AVERAGE",
        .utilization_metrics_volume_read_iops_average = "UTILIZATION_METRICS_VOLUME_READ_IOPS_AVERAGE",
        .utilization_metrics_volume_write_iops_average = "UTILIZATION_METRICS_VOLUME_WRITE_IOPS_AVERAGE",
        .instance_finding = "INSTANCE_FINDING",
        .instance_finding_reason_codes = "INSTANCE_FINDING_REASON_CODES",
        .storage_finding = "STORAGE_FINDING",
        .storage_finding_reason_codes = "STORAGE_FINDING_REASON_CODES",
        .instance_recommendation_options_db_instance_class = "INSTANCE_RECOMMENDATION_OPTIONS_DB_INSTANCE_CLASS",
        .instance_recommendation_options_rank = "INSTANCE_RECOMMENDATION_OPTIONS_RANK",
        .instance_recommendation_options_performance_risk = "INSTANCE_RECOMMENDATION_OPTIONS_PERFORMANCE_RISK",
        .instance_recommendation_options_projected_utilization_metrics_cpu_maximum = "INSTANCE_RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_CPU_MAXIMUM",
        .storage_recommendation_options_storage_type = "STORAGE_RECOMMENDATION_OPTIONS_STORAGE_TYPE",
        .storage_recommendation_options_allocated_storage = "STORAGE_RECOMMENDATION_OPTIONS_ALLOCATED_STORAGE",
        .storage_recommendation_options_max_allocated_storage = "STORAGE_RECOMMENDATION_OPTIONS_MAX_ALLOCATED_STORAGE",
        .storage_recommendation_options_iops = "STORAGE_RECOMMENDATION_OPTIONS_IOPS",
        .storage_recommendation_options_storage_throughput = "STORAGE_RECOMMENDATION_OPTIONS_STORAGE_THROUGHPUT",
        .storage_recommendation_options_rank = "STORAGE_RECOMMENDATION_OPTIONS_RANK",
        .storage_recommendation_options_estimated_monthly_volume_iops_cost_variation = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_VOLUME_IOPS_COST_VARIATION",
        .instance_recommendation_options_instance_on_demand_hourly_price = "INSTANCE_RECOMMENDATION_OPTIONS_INSTANCE_ON_DEMAND_HOURLY_PRICE",
        .instance_recommendation_options_savings_opportunity_percentage = "INSTANCE_RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_PERCENTAGE",
        .instance_recommendation_options_estimated_monthly_savings_currency = "INSTANCE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY",
        .instance_recommendation_options_estimated_monthly_savings_value = "INSTANCE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE",
        .instance_recommendation_options_savings_opportunity_after_discounts_percentage = "INSTANCE_RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_AFTER_DISCOUNTS_PERCENTAGE",
        .instance_recommendation_options_estimated_monthly_savings_currency_after_discounts = "INSTANCE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY_AFTER_DISCOUNTS",
        .instance_recommendation_options_estimated_monthly_savings_value_after_discounts = "INSTANCE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE_AFTER_DISCOUNTS",
        .storage_recommendation_options_on_demand_monthly_price = "STORAGE_RECOMMENDATION_OPTIONS_ON_DEMAND_MONTHLY_PRICE",
        .storage_recommendation_options_estimated_cluster_instance_on_demand_monthly_cost = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_CLUSTER_INSTANCE_ON_DEMAND_MONTHLY_COST",
        .storage_recommendation_options_estimated_cluster_storage_on_demand_monthly_cost = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_CLUSTER_STORAGE_ON_DEMAND_MONTHLY_COST",
        .storage_recommendation_options_estimated_cluster_storage_io_on_demand_monthly_cost = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_CLUSTER_STORAGE_IO_ON_DEMAND_MONTHLY_COST",
        .storage_recommendation_options_savings_opportunity_percentage = "STORAGE_RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_PERCENTAGE",
        .storage_recommendation_options_estimated_monthly_savings_currency = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY",
        .storage_recommendation_options_estimated_monthly_savings_value = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE",
        .storage_recommendation_options_savings_opportunity_after_discounts_percentage = "STORAGE_RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_AFTER_DISCOUNTS_PERCENTAGE",
        .storage_recommendation_options_estimated_monthly_savings_currency_after_discounts = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY_AFTER_DISCOUNTS",
        .storage_recommendation_options_estimated_monthly_savings_value_after_discounts = "STORAGE_RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE_AFTER_DISCOUNTS",
        .effective_recommendation_preferences_cpu_vendor_architectures = "EFFECTIVE_RECOMMENDATION_PREFERENCES_CPU_VENDOR_ARCHITECTURES",
        .effective_recommendation_preferences_enhanced_infrastructure_metrics = "EFFECTIVE_RECOMMENDATION_PREFERENCES_ENHANCED_INFRASTRUCTURE_METRICS",
        .effective_recommendation_preferences_lookback_period = "EFFECTIVE_RECOMMENDATION_PREFERENCES_LOOKBACK_PERIOD",
        .effective_recommendation_preferences_savings_estimation_mode = "EFFECTIVE_RECOMMENDATION_PREFERENCES_SAVINGS_ESTIMATION_MODE",
        .last_refresh_timestamp = "LAST_REFRESH_TIMESTAMP",
        .tags = "TAGS",
        .db_cluster_identifier = "DB_CLUSTER_IDENTIFIER",
        .promotion_tier = "PROMOTION_TIER",
    };
};
