pub const ExportableLambdaFunctionField = enum {
    account_id,
    function_arn,
    function_version,
    finding,
    finding_reason_codes,
    number_of_invocations,
    utilization_metrics_duration_maximum,
    utilization_metrics_duration_average,
    utilization_metrics_memory_maximum,
    utilization_metrics_memory_average,
    lookback_period_in_days,
    current_configuration_memory_size,
    current_configuration_timeout,
    current_cost_total,
    current_cost_average,
    recommendation_options_configuration_memory_size,
    recommendation_options_cost_low,
    recommendation_options_cost_high,
    recommendation_options_projected_utilization_metrics_duration_lower_bound,
    recommendation_options_projected_utilization_metrics_duration_upper_bound,
    recommendation_options_projected_utilization_metrics_duration_expected,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    tags,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "ACCOUNT_ID",
        .function_arn = "FUNCTION_ARN",
        .function_version = "FUNCTION_VERSION",
        .finding = "FINDING",
        .finding_reason_codes = "FINDING_REASON_CODES",
        .number_of_invocations = "NUMBER_OF_INVOCATIONS",
        .utilization_metrics_duration_maximum = "UTILIZATION_METRICS_DURATION_MAXIMUM",
        .utilization_metrics_duration_average = "UTILIZATION_METRICS_DURATION_AVERAGE",
        .utilization_metrics_memory_maximum = "UTILIZATION_METRICS_MEMORY_MAXIMUM",
        .utilization_metrics_memory_average = "UTILIZATION_METRICS_MEMORY_AVERAGE",
        .lookback_period_in_days = "LOOKBACK_PERIOD_IN_DAYS",
        .current_configuration_memory_size = "CURRENT_CONFIGURATION_MEMORY_SIZE",
        .current_configuration_timeout = "CURRENT_CONFIGURATION_TIMEOUT",
        .current_cost_total = "CURRENT_COST_TOTAL",
        .current_cost_average = "CURRENT_COST_AVERAGE",
        .recommendation_options_configuration_memory_size = "RECOMMENDATION_OPTIONS_CONFIGURATION_MEMORY_SIZE",
        .recommendation_options_cost_low = "RECOMMENDATION_OPTIONS_COST_LOW",
        .recommendation_options_cost_high = "RECOMMENDATION_OPTIONS_COST_HIGH",
        .recommendation_options_projected_utilization_metrics_duration_lower_bound = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_DURATION_LOWER_BOUND",
        .recommendation_options_projected_utilization_metrics_duration_upper_bound = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_DURATION_UPPER_BOUND",
        .recommendation_options_projected_utilization_metrics_duration_expected = "RECOMMENDATION_OPTIONS_PROJECTED_UTILIZATION_METRICS_DURATION_EXPECTED",
        .last_refresh_timestamp = "LAST_REFRESH_TIMESTAMP",
        .current_performance_risk = "CURRENT_PERFORMANCE_RISK",
        .recommendation_options_savings_opportunity_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY",
        .recommendation_options_estimated_monthly_savings_value = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE",
        .tags = "TAGS",
        .effective_recommendation_preferences_savings_estimation_mode = "EFFECTIVE_RECOMMENDATION_PREFERENCES_SAVINGS_ESTIMATION_MODE",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_AFTER_DISCOUNTS_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY_AFTER_DISCOUNTS",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE_AFTER_DISCOUNTS",
    };
};
