const std = @import("std");

pub const ExportableAutoScalingGroupField = enum {
    account_id,
    auto_scaling_group_arn,
    auto_scaling_group_name,
    finding,
    utilization_metrics_cpu_maximum,
    utilization_metrics_memory_maximum,
    utilization_metrics_ebs_read_ops_per_second_maximum,
    utilization_metrics_ebs_write_ops_per_second_maximum,
    utilization_metrics_ebs_read_bytes_per_second_maximum,
    utilization_metrics_ebs_write_bytes_per_second_maximum,
    utilization_metrics_disk_read_ops_per_second_maximum,
    utilization_metrics_disk_write_ops_per_second_maximum,
    utilization_metrics_disk_read_bytes_per_second_maximum,
    utilization_metrics_disk_write_bytes_per_second_maximum,
    utilization_metrics_network_in_bytes_per_second_maximum,
    utilization_metrics_network_out_bytes_per_second_maximum,
    utilization_metrics_network_packets_in_per_second_maximum,
    utilization_metrics_network_packets_out_per_second_maximum,
    lookback_period_in_days,
    current_configuration_instance_type,
    current_configuration_desired_capacity,
    current_configuration_min_size,
    current_configuration_max_size,
    current_configuration_allocation_strategy,
    current_configuration_mixed_instance_types,
    current_configuration_type,
    current_on_demand_price,
    current_standard_one_year_no_upfront_reserved_price,
    current_standard_three_year_no_upfront_reserved_price,
    current_vcpus,
    current_memory,
    current_storage,
    current_network,
    recommendation_options_configuration_instance_type,
    recommendation_options_configuration_desired_capacity,
    recommendation_options_configuration_min_size,
    recommendation_options_configuration_max_size,
    recommendation_options_configuration_estimated_instance_hour_reduction_percentage,
    recommendation_options_configuration_allocation_strategy,
    recommendation_options_configuration_mixed_instance_types,
    recommendation_options_configuration_type,
    recommendation_options_projected_utilization_metrics_cpu_maximum,
    recommendation_options_projected_utilization_metrics_memory_maximum,
    recommendation_options_performance_risk,
    recommendation_options_on_demand_price,
    recommendation_options_standard_one_year_no_upfront_reserved_price,
    recommendation_options_standard_three_year_no_upfront_reserved_price,
    recommendation_options_vcpus,
    recommendation_options_memory,
    recommendation_options_storage,
    recommendation_options_network,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    effective_recommendation_preferences_cpu_vendor_architectures,
    effective_recommendation_preferences_enhanced_infrastructure_metrics,
    effective_recommendation_preferences_inferred_workload_types,
    effective_recommendation_preferences_preferred_resources,
    effective_recommendation_preferences_lookback_period,
    inferred_workload_types,
    recommendation_options_migration_effort,
    current_instance_gpu_info,
    recommendation_options_instance_gpu_info,
    utilization_metrics_gpu_percentage_maximum,
    utilization_metrics_gpu_memory_percentage_maximum,
    recommendation_options_projected_utilization_metrics_gpu_maximum,
    recommendation_options_projected_utilization_metrics_gpu_memory_maximum,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .auto_scaling_group_arn = "AutoScalingGroupArn",
        .auto_scaling_group_name = "AutoScalingGroupName",
        .finding = "Finding",
        .utilization_metrics_cpu_maximum = "UtilizationMetricsCpuMaximum",
        .utilization_metrics_memory_maximum = "UtilizationMetricsMemoryMaximum",
        .utilization_metrics_ebs_read_ops_per_second_maximum = "UtilizationMetricsEbsReadOpsPerSecondMaximum",
        .utilization_metrics_ebs_write_ops_per_second_maximum = "UtilizationMetricsEbsWriteOpsPerSecondMaximum",
        .utilization_metrics_ebs_read_bytes_per_second_maximum = "UtilizationMetricsEbsReadBytesPerSecondMaximum",
        .utilization_metrics_ebs_write_bytes_per_second_maximum = "UtilizationMetricsEbsWriteBytesPerSecondMaximum",
        .utilization_metrics_disk_read_ops_per_second_maximum = "UtilizationMetricsDiskReadOpsPerSecondMaximum",
        .utilization_metrics_disk_write_ops_per_second_maximum = "UtilizationMetricsDiskWriteOpsPerSecondMaximum",
        .utilization_metrics_disk_read_bytes_per_second_maximum = "UtilizationMetricsDiskReadBytesPerSecondMaximum",
        .utilization_metrics_disk_write_bytes_per_second_maximum = "UtilizationMetricsDiskWriteBytesPerSecondMaximum",
        .utilization_metrics_network_in_bytes_per_second_maximum = "UtilizationMetricsNetworkInBytesPerSecondMaximum",
        .utilization_metrics_network_out_bytes_per_second_maximum = "UtilizationMetricsNetworkOutBytesPerSecondMaximum",
        .utilization_metrics_network_packets_in_per_second_maximum = "UtilizationMetricsNetworkPacketsInPerSecondMaximum",
        .utilization_metrics_network_packets_out_per_second_maximum = "UtilizationMetricsNetworkPacketsOutPerSecondMaximum",
        .lookback_period_in_days = "LookbackPeriodInDays",
        .current_configuration_instance_type = "CurrentConfigurationInstanceType",
        .current_configuration_desired_capacity = "CurrentConfigurationDesiredCapacity",
        .current_configuration_min_size = "CurrentConfigurationMinSize",
        .current_configuration_max_size = "CurrentConfigurationMaxSize",
        .current_configuration_allocation_strategy = "CurrentConfigurationAllocationStrategy",
        .current_configuration_mixed_instance_types = "CurrentConfigurationMixedInstanceTypes",
        .current_configuration_type = "CurrentConfigurationType",
        .current_on_demand_price = "CurrentOnDemandPrice",
        .current_standard_one_year_no_upfront_reserved_price = "CurrentStandardOneYearNoUpfrontReservedPrice",
        .current_standard_three_year_no_upfront_reserved_price = "CurrentStandardThreeYearNoUpfrontReservedPrice",
        .current_vcpus = "CurrentVCpus",
        .current_memory = "CurrentMemory",
        .current_storage = "CurrentStorage",
        .current_network = "CurrentNetwork",
        .recommendation_options_configuration_instance_type = "RecommendationOptionsConfigurationInstanceType",
        .recommendation_options_configuration_desired_capacity = "RecommendationOptionsConfigurationDesiredCapacity",
        .recommendation_options_configuration_min_size = "RecommendationOptionsConfigurationMinSize",
        .recommendation_options_configuration_max_size = "RecommendationOptionsConfigurationMaxSize",
        .recommendation_options_configuration_estimated_instance_hour_reduction_percentage = "RecommendationOptionsConfigurationEstimatedInstanceHourReductionPercentage",
        .recommendation_options_configuration_allocation_strategy = "RecommendationOptionsConfigurationAllocationStrategy",
        .recommendation_options_configuration_mixed_instance_types = "RecommendationOptionsConfigurationMixedInstanceTypes",
        .recommendation_options_configuration_type = "RecommendationOptionsConfigurationType",
        .recommendation_options_projected_utilization_metrics_cpu_maximum = "RecommendationOptionsProjectedUtilizationMetricsCpuMaximum",
        .recommendation_options_projected_utilization_metrics_memory_maximum = "RecommendationOptionsProjectedUtilizationMetricsMemoryMaximum",
        .recommendation_options_performance_risk = "RecommendationOptionsPerformanceRisk",
        .recommendation_options_on_demand_price = "RecommendationOptionsOnDemandPrice",
        .recommendation_options_standard_one_year_no_upfront_reserved_price = "RecommendationOptionsStandardOneYearNoUpfrontReservedPrice",
        .recommendation_options_standard_three_year_no_upfront_reserved_price = "RecommendationOptionsStandardThreeYearNoUpfrontReservedPrice",
        .recommendation_options_vcpus = "RecommendationOptionsVcpus",
        .recommendation_options_memory = "RecommendationOptionsMemory",
        .recommendation_options_storage = "RecommendationOptionsStorage",
        .recommendation_options_network = "RecommendationOptionsNetwork",
        .last_refresh_timestamp = "LastRefreshTimestamp",
        .current_performance_risk = "CurrentPerformanceRisk",
        .recommendation_options_savings_opportunity_percentage = "RecommendationOptionsSavingsOpportunityPercentage",
        .recommendation_options_estimated_monthly_savings_currency = "RecommendationOptionsEstimatedMonthlySavingsCurrency",
        .recommendation_options_estimated_monthly_savings_value = "RecommendationOptionsEstimatedMonthlySavingsValue",
        .effective_recommendation_preferences_cpu_vendor_architectures = "EffectiveRecommendationPreferencesCpuVendorArchitectures",
        .effective_recommendation_preferences_enhanced_infrastructure_metrics = "EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics",
        .effective_recommendation_preferences_inferred_workload_types = "EffectiveRecommendationPreferencesInferredWorkloadTypes",
        .effective_recommendation_preferences_preferred_resources = "EffectiveRecommendationPreferencesPreferredResources",
        .effective_recommendation_preferences_lookback_period = "EffectiveRecommendationPreferencesLookBackPeriod",
        .inferred_workload_types = "InferredWorkloadTypes",
        .recommendation_options_migration_effort = "RecommendationOptionsMigrationEffort",
        .current_instance_gpu_info = "CurrentInstanceGpuInfo",
        .recommendation_options_instance_gpu_info = "RecommendationOptionsInstanceGpuInfo",
        .utilization_metrics_gpu_percentage_maximum = "UtilizationMetricsGpuPercentageMaximum",
        .utilization_metrics_gpu_memory_percentage_maximum = "UtilizationMetricsGpuMemoryPercentageMaximum",
        .recommendation_options_projected_utilization_metrics_gpu_maximum = "RecommendationOptionsProjectedUtilizationMetricsGpuPercentageMaximum",
        .recommendation_options_projected_utilization_metrics_gpu_memory_maximum = "RecommendationOptionsProjectedUtilizationMetricsGpuMemoryPercentageMaximum",
        .effective_recommendation_preferences_savings_estimation_mode = "EffectiveRecommendationPreferencesSavingsEstimationMode",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .account_id => "AccountId",
            .auto_scaling_group_arn => "AutoScalingGroupArn",
            .auto_scaling_group_name => "AutoScalingGroupName",
            .finding => "Finding",
            .utilization_metrics_cpu_maximum => "UtilizationMetricsCpuMaximum",
            .utilization_metrics_memory_maximum => "UtilizationMetricsMemoryMaximum",
            .utilization_metrics_ebs_read_ops_per_second_maximum => "UtilizationMetricsEbsReadOpsPerSecondMaximum",
            .utilization_metrics_ebs_write_ops_per_second_maximum => "UtilizationMetricsEbsWriteOpsPerSecondMaximum",
            .utilization_metrics_ebs_read_bytes_per_second_maximum => "UtilizationMetricsEbsReadBytesPerSecondMaximum",
            .utilization_metrics_ebs_write_bytes_per_second_maximum => "UtilizationMetricsEbsWriteBytesPerSecondMaximum",
            .utilization_metrics_disk_read_ops_per_second_maximum => "UtilizationMetricsDiskReadOpsPerSecondMaximum",
            .utilization_metrics_disk_write_ops_per_second_maximum => "UtilizationMetricsDiskWriteOpsPerSecondMaximum",
            .utilization_metrics_disk_read_bytes_per_second_maximum => "UtilizationMetricsDiskReadBytesPerSecondMaximum",
            .utilization_metrics_disk_write_bytes_per_second_maximum => "UtilizationMetricsDiskWriteBytesPerSecondMaximum",
            .utilization_metrics_network_in_bytes_per_second_maximum => "UtilizationMetricsNetworkInBytesPerSecondMaximum",
            .utilization_metrics_network_out_bytes_per_second_maximum => "UtilizationMetricsNetworkOutBytesPerSecondMaximum",
            .utilization_metrics_network_packets_in_per_second_maximum => "UtilizationMetricsNetworkPacketsInPerSecondMaximum",
            .utilization_metrics_network_packets_out_per_second_maximum => "UtilizationMetricsNetworkPacketsOutPerSecondMaximum",
            .lookback_period_in_days => "LookbackPeriodInDays",
            .current_configuration_instance_type => "CurrentConfigurationInstanceType",
            .current_configuration_desired_capacity => "CurrentConfigurationDesiredCapacity",
            .current_configuration_min_size => "CurrentConfigurationMinSize",
            .current_configuration_max_size => "CurrentConfigurationMaxSize",
            .current_configuration_allocation_strategy => "CurrentConfigurationAllocationStrategy",
            .current_configuration_mixed_instance_types => "CurrentConfigurationMixedInstanceTypes",
            .current_configuration_type => "CurrentConfigurationType",
            .current_on_demand_price => "CurrentOnDemandPrice",
            .current_standard_one_year_no_upfront_reserved_price => "CurrentStandardOneYearNoUpfrontReservedPrice",
            .current_standard_three_year_no_upfront_reserved_price => "CurrentStandardThreeYearNoUpfrontReservedPrice",
            .current_vcpus => "CurrentVCpus",
            .current_memory => "CurrentMemory",
            .current_storage => "CurrentStorage",
            .current_network => "CurrentNetwork",
            .recommendation_options_configuration_instance_type => "RecommendationOptionsConfigurationInstanceType",
            .recommendation_options_configuration_desired_capacity => "RecommendationOptionsConfigurationDesiredCapacity",
            .recommendation_options_configuration_min_size => "RecommendationOptionsConfigurationMinSize",
            .recommendation_options_configuration_max_size => "RecommendationOptionsConfigurationMaxSize",
            .recommendation_options_configuration_estimated_instance_hour_reduction_percentage => "RecommendationOptionsConfigurationEstimatedInstanceHourReductionPercentage",
            .recommendation_options_configuration_allocation_strategy => "RecommendationOptionsConfigurationAllocationStrategy",
            .recommendation_options_configuration_mixed_instance_types => "RecommendationOptionsConfigurationMixedInstanceTypes",
            .recommendation_options_configuration_type => "RecommendationOptionsConfigurationType",
            .recommendation_options_projected_utilization_metrics_cpu_maximum => "RecommendationOptionsProjectedUtilizationMetricsCpuMaximum",
            .recommendation_options_projected_utilization_metrics_memory_maximum => "RecommendationOptionsProjectedUtilizationMetricsMemoryMaximum",
            .recommendation_options_performance_risk => "RecommendationOptionsPerformanceRisk",
            .recommendation_options_on_demand_price => "RecommendationOptionsOnDemandPrice",
            .recommendation_options_standard_one_year_no_upfront_reserved_price => "RecommendationOptionsStandardOneYearNoUpfrontReservedPrice",
            .recommendation_options_standard_three_year_no_upfront_reserved_price => "RecommendationOptionsStandardThreeYearNoUpfrontReservedPrice",
            .recommendation_options_vcpus => "RecommendationOptionsVcpus",
            .recommendation_options_memory => "RecommendationOptionsMemory",
            .recommendation_options_storage => "RecommendationOptionsStorage",
            .recommendation_options_network => "RecommendationOptionsNetwork",
            .last_refresh_timestamp => "LastRefreshTimestamp",
            .current_performance_risk => "CurrentPerformanceRisk",
            .recommendation_options_savings_opportunity_percentage => "RecommendationOptionsSavingsOpportunityPercentage",
            .recommendation_options_estimated_monthly_savings_currency => "RecommendationOptionsEstimatedMonthlySavingsCurrency",
            .recommendation_options_estimated_monthly_savings_value => "RecommendationOptionsEstimatedMonthlySavingsValue",
            .effective_recommendation_preferences_cpu_vendor_architectures => "EffectiveRecommendationPreferencesCpuVendorArchitectures",
            .effective_recommendation_preferences_enhanced_infrastructure_metrics => "EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics",
            .effective_recommendation_preferences_inferred_workload_types => "EffectiveRecommendationPreferencesInferredWorkloadTypes",
            .effective_recommendation_preferences_preferred_resources => "EffectiveRecommendationPreferencesPreferredResources",
            .effective_recommendation_preferences_lookback_period => "EffectiveRecommendationPreferencesLookBackPeriod",
            .inferred_workload_types => "InferredWorkloadTypes",
            .recommendation_options_migration_effort => "RecommendationOptionsMigrationEffort",
            .current_instance_gpu_info => "CurrentInstanceGpuInfo",
            .recommendation_options_instance_gpu_info => "RecommendationOptionsInstanceGpuInfo",
            .utilization_metrics_gpu_percentage_maximum => "UtilizationMetricsGpuPercentageMaximum",
            .utilization_metrics_gpu_memory_percentage_maximum => "UtilizationMetricsGpuMemoryPercentageMaximum",
            .recommendation_options_projected_utilization_metrics_gpu_maximum => "RecommendationOptionsProjectedUtilizationMetricsGpuPercentageMaximum",
            .recommendation_options_projected_utilization_metrics_gpu_memory_maximum => "RecommendationOptionsProjectedUtilizationMetricsGpuMemoryPercentageMaximum",
            .effective_recommendation_preferences_savings_estimation_mode => "EffectiveRecommendationPreferencesSavingsEstimationMode",
            .recommendation_options_savings_opportunity_after_discounts_percentage => "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
            .recommendation_options_estimated_monthly_savings_currency_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
            .recommendation_options_estimated_monthly_savings_value_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
