const std = @import("std");

pub const ExportableVolumeField = enum {
    account_id,
    volume_arn,
    finding,
    utilization_metrics_volume_read_ops_per_second_maximum,
    utilization_metrics_volume_write_ops_per_second_maximum,
    utilization_metrics_volume_read_bytes_per_second_maximum,
    utilization_metrics_volume_write_bytes_per_second_maximum,
    lookback_period_in_days,
    current_configuration_volume_type,
    current_configuration_volume_baseline_iops,
    current_configuration_volume_baseline_throughput,
    current_configuration_volume_burst_iops,
    current_configuration_volume_burst_throughput,
    current_configuration_volume_size,
    current_monthly_price,
    recommendation_options_configuration_volume_type,
    recommendation_options_configuration_volume_baseline_iops,
    recommendation_options_configuration_volume_baseline_throughput,
    recommendation_options_configuration_volume_burst_iops,
    recommendation_options_configuration_volume_burst_throughput,
    recommendation_options_configuration_volume_size,
    recommendation_options_monthly_price,
    recommendation_options_performance_risk,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    tags,
    root_volume,
    current_configuration_root_volume,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .volume_arn = "VolumeArn",
        .finding = "Finding",
        .utilization_metrics_volume_read_ops_per_second_maximum = "UtilizationMetricsVolumeReadOpsPerSecondMaximum",
        .utilization_metrics_volume_write_ops_per_second_maximum = "UtilizationMetricsVolumeWriteOpsPerSecondMaximum",
        .utilization_metrics_volume_read_bytes_per_second_maximum = "UtilizationMetricsVolumeReadBytesPerSecondMaximum",
        .utilization_metrics_volume_write_bytes_per_second_maximum = "UtilizationMetricsVolumeWriteBytesPerSecondMaximum",
        .lookback_period_in_days = "LookbackPeriodInDays",
        .current_configuration_volume_type = "CurrentConfigurationVolumeType",
        .current_configuration_volume_baseline_iops = "CurrentConfigurationVolumeBaselineIOPS",
        .current_configuration_volume_baseline_throughput = "CurrentConfigurationVolumeBaselineThroughput",
        .current_configuration_volume_burst_iops = "CurrentConfigurationVolumeBurstIOPS",
        .current_configuration_volume_burst_throughput = "CurrentConfigurationVolumeBurstThroughput",
        .current_configuration_volume_size = "CurrentConfigurationVolumeSize",
        .current_monthly_price = "CurrentMonthlyPrice",
        .recommendation_options_configuration_volume_type = "RecommendationOptionsConfigurationVolumeType",
        .recommendation_options_configuration_volume_baseline_iops = "RecommendationOptionsConfigurationVolumeBaselineIOPS",
        .recommendation_options_configuration_volume_baseline_throughput = "RecommendationOptionsConfigurationVolumeBaselineThroughput",
        .recommendation_options_configuration_volume_burst_iops = "RecommendationOptionsConfigurationVolumeBurstIOPS",
        .recommendation_options_configuration_volume_burst_throughput = "RecommendationOptionsConfigurationVolumeBurstThroughput",
        .recommendation_options_configuration_volume_size = "RecommendationOptionsConfigurationVolumeSize",
        .recommendation_options_monthly_price = "RecommendationOptionsMonthlyPrice",
        .recommendation_options_performance_risk = "RecommendationOptionsPerformanceRisk",
        .last_refresh_timestamp = "LastRefreshTimestamp",
        .current_performance_risk = "CurrentPerformanceRisk",
        .recommendation_options_savings_opportunity_percentage = "RecommendationOptionsSavingsOpportunityPercentage",
        .recommendation_options_estimated_monthly_savings_currency = "RecommendationOptionsEstimatedMonthlySavingsCurrency",
        .recommendation_options_estimated_monthly_savings_value = "RecommendationOptionsEstimatedMonthlySavingsValue",
        .tags = "Tags",
        .root_volume = "RootVolume",
        .current_configuration_root_volume = "CurrentConfigurationRootVolume",
        .effective_recommendation_preferences_savings_estimation_mode = "EffectiveRecommendationPreferencesSavingsEstimationMode",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .account_id => "AccountId",
            .volume_arn => "VolumeArn",
            .finding => "Finding",
            .utilization_metrics_volume_read_ops_per_second_maximum => "UtilizationMetricsVolumeReadOpsPerSecondMaximum",
            .utilization_metrics_volume_write_ops_per_second_maximum => "UtilizationMetricsVolumeWriteOpsPerSecondMaximum",
            .utilization_metrics_volume_read_bytes_per_second_maximum => "UtilizationMetricsVolumeReadBytesPerSecondMaximum",
            .utilization_metrics_volume_write_bytes_per_second_maximum => "UtilizationMetricsVolumeWriteBytesPerSecondMaximum",
            .lookback_period_in_days => "LookbackPeriodInDays",
            .current_configuration_volume_type => "CurrentConfigurationVolumeType",
            .current_configuration_volume_baseline_iops => "CurrentConfigurationVolumeBaselineIOPS",
            .current_configuration_volume_baseline_throughput => "CurrentConfigurationVolumeBaselineThroughput",
            .current_configuration_volume_burst_iops => "CurrentConfigurationVolumeBurstIOPS",
            .current_configuration_volume_burst_throughput => "CurrentConfigurationVolumeBurstThroughput",
            .current_configuration_volume_size => "CurrentConfigurationVolumeSize",
            .current_monthly_price => "CurrentMonthlyPrice",
            .recommendation_options_configuration_volume_type => "RecommendationOptionsConfigurationVolumeType",
            .recommendation_options_configuration_volume_baseline_iops => "RecommendationOptionsConfigurationVolumeBaselineIOPS",
            .recommendation_options_configuration_volume_baseline_throughput => "RecommendationOptionsConfigurationVolumeBaselineThroughput",
            .recommendation_options_configuration_volume_burst_iops => "RecommendationOptionsConfigurationVolumeBurstIOPS",
            .recommendation_options_configuration_volume_burst_throughput => "RecommendationOptionsConfigurationVolumeBurstThroughput",
            .recommendation_options_configuration_volume_size => "RecommendationOptionsConfigurationVolumeSize",
            .recommendation_options_monthly_price => "RecommendationOptionsMonthlyPrice",
            .recommendation_options_performance_risk => "RecommendationOptionsPerformanceRisk",
            .last_refresh_timestamp => "LastRefreshTimestamp",
            .current_performance_risk => "CurrentPerformanceRisk",
            .recommendation_options_savings_opportunity_percentage => "RecommendationOptionsSavingsOpportunityPercentage",
            .recommendation_options_estimated_monthly_savings_currency => "RecommendationOptionsEstimatedMonthlySavingsCurrency",
            .recommendation_options_estimated_monthly_savings_value => "RecommendationOptionsEstimatedMonthlySavingsValue",
            .tags => "Tags",
            .root_volume => "RootVolume",
            .current_configuration_root_volume => "CurrentConfigurationRootVolume",
            .effective_recommendation_preferences_savings_estimation_mode => "EffectiveRecommendationPreferencesSavingsEstimationMode",
            .recommendation_options_savings_opportunity_after_discounts_percentage => "RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage",
            .recommendation_options_estimated_monthly_savings_currency_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts",
            .recommendation_options_estimated_monthly_savings_value_after_discounts => "RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
