pub const ExportableVolumeField = enum {
    account_id,
    volume_arn,
    finding,
    utilization_metrics_volume_read_ops_per_second_maximum,
    utilization_metrics_volume_write_ops_per_second_maximum,
    utilization_metrics_volume_read_bytes_per_second_maximum,
    utilization_metrics_volume_write_bytes_per_second_maximum,
    lookback_period_in_days,
    current_configuration_volume_type,
    current_configuration_volume_baseline_iops,
    current_configuration_volume_baseline_throughput,
    current_configuration_volume_burst_iops,
    current_configuration_volume_burst_throughput,
    current_configuration_volume_size,
    current_monthly_price,
    recommendation_options_configuration_volume_type,
    recommendation_options_configuration_volume_baseline_iops,
    recommendation_options_configuration_volume_baseline_throughput,
    recommendation_options_configuration_volume_burst_iops,
    recommendation_options_configuration_volume_burst_throughput,
    recommendation_options_configuration_volume_size,
    recommendation_options_monthly_price,
    recommendation_options_performance_risk,
    last_refresh_timestamp,
    current_performance_risk,
    recommendation_options_savings_opportunity_percentage,
    recommendation_options_estimated_monthly_savings_currency,
    recommendation_options_estimated_monthly_savings_value,
    tags,
    root_volume,
    current_configuration_root_volume,
    effective_recommendation_preferences_savings_estimation_mode,
    recommendation_options_savings_opportunity_after_discounts_percentage,
    recommendation_options_estimated_monthly_savings_currency_after_discounts,
    recommendation_options_estimated_monthly_savings_value_after_discounts,

    pub const json_field_names = .{
        .account_id = "ACCOUNT_ID",
        .volume_arn = "VOLUME_ARN",
        .finding = "FINDING",
        .utilization_metrics_volume_read_ops_per_second_maximum = "UTILIZATION_METRICS_VOLUME_READ_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_volume_write_ops_per_second_maximum = "UTILIZATION_METRICS_VOLUME_WRITE_OPS_PER_SECOND_MAXIMUM",
        .utilization_metrics_volume_read_bytes_per_second_maximum = "UTILIZATION_METRICS_VOLUME_READ_BYTES_PER_SECOND_MAXIMUM",
        .utilization_metrics_volume_write_bytes_per_second_maximum = "UTILIZATION_METRICS_VOLUME_WRITE_BYTES_PER_SECOND_MAXIMUM",
        .lookback_period_in_days = "LOOKBACK_PERIOD_IN_DAYS",
        .current_configuration_volume_type = "CURRENT_CONFIGURATION_VOLUME_TYPE",
        .current_configuration_volume_baseline_iops = "CURRENT_CONFIGURATION_VOLUME_BASELINE_IOPS",
        .current_configuration_volume_baseline_throughput = "CURRENT_CONFIGURATION_VOLUME_BASELINE_THROUGHPUT",
        .current_configuration_volume_burst_iops = "CURRENT_CONFIGURATION_VOLUME_BURST_IOPS",
        .current_configuration_volume_burst_throughput = "CURRENT_CONFIGURATION_VOLUME_BURST_THROUGHPUT",
        .current_configuration_volume_size = "CURRENT_CONFIGURATION_VOLUME_SIZE",
        .current_monthly_price = "CURRENT_MONTHLY_PRICE",
        .recommendation_options_configuration_volume_type = "RECOMMENDATION_OPTIONS_CONFIGURATION_VOLUME_TYPE",
        .recommendation_options_configuration_volume_baseline_iops = "RECOMMENDATION_OPTIONS_CONFIGURATION_VOLUME_BASELINE_IOPS",
        .recommendation_options_configuration_volume_baseline_throughput = "RECOMMENDATION_OPTIONS_CONFIGURATION_VOLUME_BASELINE_THROUGHPUT",
        .recommendation_options_configuration_volume_burst_iops = "RECOMMENDATION_OPTIONS_CONFIGURATION_VOLUME_BURST_IOPS",
        .recommendation_options_configuration_volume_burst_throughput = "RECOMMENDATION_OPTIONS_CONFIGURATION_VOLUME_BURST_THROUGHPUT",
        .recommendation_options_configuration_volume_size = "RECOMMENDATION_OPTIONS_CONFIGURATION_VOLUME_SIZE",
        .recommendation_options_monthly_price = "RECOMMENDATION_OPTIONS_MONTHLY_PRICE",
        .recommendation_options_performance_risk = "RECOMMENDATION_OPTIONS_PERFORMANCE_RISK",
        .last_refresh_timestamp = "LAST_REFRESH_TIMESTAMP",
        .current_performance_risk = "CURRENT_PERFORMANCE_RISK",
        .recommendation_options_savings_opportunity_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY",
        .recommendation_options_estimated_monthly_savings_value = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE",
        .tags = "TAGS",
        .root_volume = "ROOT_VOLUME",
        .current_configuration_root_volume = "CURRENT_CONFIGURATION_ROOT_VOLUME",
        .effective_recommendation_preferences_savings_estimation_mode = "EFFECTIVE_RECOMMENDATION_PREFERENCES_SAVINGS_ESTIMATION_MODE",
        .recommendation_options_savings_opportunity_after_discounts_percentage = "RECOMMENDATION_OPTIONS_SAVINGS_OPPORTUNITY_AFTER_DISCOUNTS_PERCENTAGE",
        .recommendation_options_estimated_monthly_savings_currency_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_CURRENCY_AFTER_DISCOUNTS",
        .recommendation_options_estimated_monthly_savings_value_after_discounts = "RECOMMENDATION_OPTIONS_ESTIMATED_MONTHLY_SAVINGS_VALUE_AFTER_DISCOUNTS",
    };
};
