pub const MetricName = enum {
    cpu,
    memory,
    ebs_read_ops_per_second,
    ebs_write_ops_per_second,
    ebs_read_bytes_per_second,
    ebs_write_bytes_per_second,
    disk_read_ops_per_second,
    disk_write_ops_per_second,
    disk_read_bytes_per_second,
    disk_write_bytes_per_second,
    network_in_bytes_per_second,
    network_out_bytes_per_second,
    network_packets_in_per_second,
    network_packets_out_per_second,
    gpu_percentage,
    gpu_memory_percentage,

    pub const json_field_names = .{
        .cpu = "CPU",
        .memory = "MEMORY",
        .ebs_read_ops_per_second = "EBS_READ_OPS_PER_SECOND",
        .ebs_write_ops_per_second = "EBS_WRITE_OPS_PER_SECOND",
        .ebs_read_bytes_per_second = "EBS_READ_BYTES_PER_SECOND",
        .ebs_write_bytes_per_second = "EBS_WRITE_BYTES_PER_SECOND",
        .disk_read_ops_per_second = "DISK_READ_OPS_PER_SECOND",
        .disk_write_ops_per_second = "DISK_WRITE_OPS_PER_SECOND",
        .disk_read_bytes_per_second = "DISK_READ_BYTES_PER_SECOND",
        .disk_write_bytes_per_second = "DISK_WRITE_BYTES_PER_SECOND",
        .network_in_bytes_per_second = "NETWORK_IN_BYTES_PER_SECOND",
        .network_out_bytes_per_second = "NETWORK_OUT_BYTES_PER_SECOND",
        .network_packets_in_per_second = "NETWORK_PACKETS_IN_PER_SECOND",
        .network_packets_out_per_second = "NETWORK_PACKETS_OUT_PER_SECOND",
        .gpu_percentage = "GPU_PERCENTAGE",
        .gpu_memory_percentage = "GPU_MEMORY_PERCENTAGE",
    };
};
