pub const RDSDBMetricName = enum {
    cpu,
    memory,
    ebs_volume_storage_space_utilization,
    network_receive_throughput,
    network_transmit_throughput,
    ebs_volume_read_iops,
    ebs_volume_write_iops,
    ebs_volume_read_throughput,
    ebs_volume_write_throughput,
    database_connections,
    storage_network_receive_throughput,
    storage_network_transmit_throughput,
    aurora_memory_health_state,
    aurora_memory_num_declined_sql,
    aurora_memory_num_kill_conn_total,
    aurora_memory_num_kill_query_total,
    read_iops_ephemeral_storage,
    write_iops_ephemeral_storage,
    volume_read_iops,
    volume_bytes_used,
    volume_write_iops,

    pub const json_field_names = .{
        .cpu = "CPU",
        .memory = "MEMORY",
        .ebs_volume_storage_space_utilization = "EBS_VOLUME_STORAGE_SPACE_UTILIZATION",
        .network_receive_throughput = "NETWORK_RECEIVE_THROUGHPUT",
        .network_transmit_throughput = "NETWORK_TRANSMIT_THROUGHPUT",
        .ebs_volume_read_iops = "EBS_VOLUME_READ_IOPS",
        .ebs_volume_write_iops = "EBS_VOLUME_WRITE_IOPS",
        .ebs_volume_read_throughput = "EBS_VOLUME_READ_THROUGHPUT",
        .ebs_volume_write_throughput = "EBS_VOLUME_WRITE_THROUGHPUT",
        .database_connections = "DATABASE_CONNECTIONS",
        .storage_network_receive_throughput = "STORAGE_NETWORK_RECEIVE_THROUGHPUT",
        .storage_network_transmit_throughput = "STORAGE_NETWORK_TRANSMIT_THROUGHPUT",
        .aurora_memory_health_state = "AURORA_MEMORY_HEALTH_STATE",
        .aurora_memory_num_declined_sql = "AURORA_MEMORY_NUM_DECLINED_SQL",
        .aurora_memory_num_kill_conn_total = "AURORA_MEMORY_NUM_KILL_CONN_TOTAL",
        .aurora_memory_num_kill_query_total = "AURORA_MEMORY_NUM_KILL_QUERY_TOTAL",
        .read_iops_ephemeral_storage = "READ_IOPS_EPHEMERAL_STORAGE",
        .write_iops_ephemeral_storage = "WRITE_IOPS_EPHEMERAL_STORAGE",
        .volume_read_iops = "VOLUME_READ_IOPS",
        .volume_bytes_used = "VOLUME_BYTES_USED",
        .volume_write_iops = "VOLUME_WRITE_IOPS",
    };
};
