const BedrockKnowledgeStoreExactResponseFields = @import("bedrock_knowledge_store_exact_response_fields.zig").BedrockKnowledgeStoreExactResponseFields;

/// Contains details about the configuration of a Amazon Bedrock knowledge base.
pub const BedrockKnowledgeStoreConfiguration = struct {
    /// The base ARN of the knowledge base used.
    bedrock_knowledge_base_arn: []const u8,

    /// Specifies whether to return an exact response, or to return an answer
    /// generated by the model, using the fields you specify from the database.
    exact_response: bool = false,

    /// Contains the names of the fields used for an exact response to the user.
    exact_response_fields: ?BedrockKnowledgeStoreExactResponseFields = null,

    pub const json_field_names = .{
        .bedrock_knowledge_base_arn = "bedrockKnowledgeBaseArn",
        .exact_response = "exactResponse",
        .exact_response_fields = "exactResponseFields",
    };
};
