const ExactResponseFields = @import("exact_response_fields.zig").ExactResponseFields;

/// Contains details about the configuration of the Amazon OpenSearch Service
/// database used for the `AMAZON.QnAIntent`.
pub const OpensearchConfiguration = struct {
    /// The endpoint of the Amazon OpenSearch Service domain.
    domain_endpoint: []const u8,

    /// Specifies whether to return an exact response or to return an answer
    /// generated by the model using the fields you specify from the database.
    exact_response: bool = false,

    /// Contains the names of the fields used for an exact response to the user.
    exact_response_fields: ?ExactResponseFields = null,

    /// Contains a list of fields from the Amazon OpenSearch Service that the model
    /// can use to generate the answer to the query.
    include_fields: ?[]const []const u8 = null,

    /// The name of the Amazon OpenSearch Service index.
    index_name: []const u8,

    pub const json_field_names = .{
        .domain_endpoint = "domainEndpoint",
        .exact_response = "exactResponse",
        .exact_response_fields = "exactResponseFields",
        .include_fields = "includeFields",
        .index_name = "indexName",
    };
};
