const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Device = @import("device.zig").Device;
const MatterEndpoint = @import("matter_endpoint.zig").MatterEndpoint;
const ConnectorEventOperation = @import("connector_event_operation.zig").ConnectorEventOperation;

pub const SendConnectorEventInput = struct {
    /// The third-party device id as defined by the connector. This device id must
    /// not contain personal identifiable information (PII).
    ///
    /// This parameter is used for cloud-to-cloud devices only.
    connector_device_id: ?[]const u8 = null,

    /// The id of the connector between the third-party cloud provider and IoT
    /// managed integrations.
    connector_id: []const u8,

    /// The id for the device discovery job.
    device_discovery_id: ?[]const u8 = null,

    /// The list of devices.
    devices: ?[]const Device = null,

    /// The device endpoint.
    matter_endpoint: ?MatterEndpoint = null,

    /// The device state change event payload.
    ///
    /// This parameter will include the following three fields:
    ///
    /// * `uri`: `schema auc://<PARTNER-DEVICE-ID>/ResourcePath` (The `Resourcepath`
    ///   corresponds to an OCF resource.)
    /// * `op`: For device state changes, this field must populate as `n+d`.
    /// * `cn`: The content depends on the OCF resource referenced in
    ///   `ResourcePath`.
    message: ?[]const u8 = null,

    /// The Open Connectivity Foundation (OCF) operation requested to be performed
    /// on the managed thing.
    ///
    /// The field op can have a value of "I" or "U". The field "cn" will contain the
    /// capability types.
    operation: ConnectorEventOperation,

    /// The Open Connectivity Foundation (OCF) security specification version for
    /// the operation being requested on the managed thing. For more information,
    /// see [OCF Security
    /// Specification](https://openconnectivity.org/specs/OCF_Security_Specification_v1.0.0.pdf).
    operation_version: ?[]const u8 = null,

    /// The status code of the Open Connectivity Foundation (OCF) operation being
    /// performed on the managed thing.
    status_code: ?i32 = null,

    /// The trace request identifier. This is generated by IoT managed integrations
    /// and can be used to trace this command and its related operations in
    /// CloudWatch.
    trace_id: ?[]const u8 = null,

    /// The id of the third-party cloud provider.
    user_id: ?[]const u8 = null,

    pub const json_field_names = .{
        .connector_device_id = "ConnectorDeviceId",
        .connector_id = "ConnectorId",
        .device_discovery_id = "DeviceDiscoveryId",
        .devices = "Devices",
        .matter_endpoint = "MatterEndpoint",
        .message = "Message",
        .operation = "Operation",
        .operation_version = "OperationVersion",
        .status_code = "StatusCode",
        .trace_id = "TraceId",
        .user_id = "UserId",
    };
};

pub const SendConnectorEventOutput = struct {
    /// The id of the connector between the third-party cloud provider and IoT
    /// managed integrations.
    connector_id: []const u8,

    pub const json_field_names = .{
        .connector_id = "ConnectorId",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: SendConnectorEventInput, options: CallOptions) !SendConnectorEventOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "iotmanagedintegrations", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: SendConnectorEventInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("api.iotmanagedintegrations", "IoT Managed Integrations", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/connector-event/");
    try path_buf.appendSlice(allocator, input.connector_id);
    const path = try path_buf.toOwnedSlice(allocator);

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.connector_device_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"ConnectorDeviceId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.device_discovery_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"DeviceDiscoveryId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.devices) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"Devices\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.matter_endpoint) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"MatterEndpoint\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.message) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"Message\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"Operation\":");
    try aws.json.writeValue(@TypeOf(input.operation), input.operation, allocator, &body_buf);
    has_prev = true;
    if (input.operation_version) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"OperationVersion\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.status_code) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"StatusCode\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.trace_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"TraceId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.user_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"UserId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !SendConnectorEventOutput {
    const result: SendConnectorEventOutput = try aws.json.parseJsonObject(
        SendConnectorEventOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
