pub const WorkspaceImageErrorDetailCode = enum {
    outdated_powershell_version,
    office_installed,
    pcoip_agent_installed,
    windows_updates_enabled,
    auto_mount_disabled,
    workspaces_byol_account_not_found,
    workspaces_byol_account_disabled,
    dhcp_disabled,
    disk_free_space,
    additional_drives_attached,
    os_not_supported,
    domain_joined,
    azure_domain_joined,
    firewall_enabled,
    vmware_tools_installed,
    disk_size_exceeded,
    incompatible_partitioning,
    pending_reboot,
    auto_logon_enabled,
    realtime_universal_disabled,
    multiple_boot_partition,
    sixty_four_bit_os,
    zero_rearm_count,
    in_place_upgrade,
    anti_virus_installed,
    uefi_not_supported,
    unknown_error,
    appx_packages_installed,
    reserved_storage_in_use,
    additional_drives_present,
    windows_updates_required,
    sysprep_file_missing,
    user_profile_missing,
    insufficient_disk_space,
    environment_variables_path_missing_entries,
    domain_account_services_found,
    invalid_ip,
    remote_desktop_services_disabled,
    windows_modules_installer_disabled,
    amazon_ssm_agent_enabled,
    unsupported_security_protocol,
    multiple_user_profiles,
    staged_appx_package,
    unsupported_os_upgrade,
    insufficient_rearm_count,
    incompatible_protocol,
    incompatible_memory_integrity,
    restricted_drive_letter,

    pub const json_field_names = .{
        .outdated_powershell_version = "OUTDATED_POWERSHELL_VERSION",
        .office_installed = "OFFICE_INSTALLED",
        .pcoip_agent_installed = "PCOIP_AGENT_INSTALLED",
        .windows_updates_enabled = "WINDOWS_UPDATES_ENABLED",
        .auto_mount_disabled = "AUTO_MOUNT_DISABLED",
        .workspaces_byol_account_not_found = "WORKSPACES_BYOL_ACCOUNT_NOT_FOUND",
        .workspaces_byol_account_disabled = "WORKSPACES_BYOL_ACCOUNT_DISABLED",
        .dhcp_disabled = "DHCP_DISABLED",
        .disk_free_space = "DISK_FREE_SPACE",
        .additional_drives_attached = "ADDITIONAL_DRIVES_ATTACHED",
        .os_not_supported = "OS_NOT_SUPPORTED",
        .domain_joined = "DOMAIN_JOINED",
        .azure_domain_joined = "AZURE_DOMAIN_JOINED",
        .firewall_enabled = "FIREWALL_ENABLED",
        .vmware_tools_installed = "VMWARE_TOOLS_INSTALLED",
        .disk_size_exceeded = "DISK_SIZE_EXCEEDED",
        .incompatible_partitioning = "INCOMPATIBLE_PARTITIONING",
        .pending_reboot = "PENDING_REBOOT",
        .auto_logon_enabled = "AUTO_LOGON_ENABLED",
        .realtime_universal_disabled = "REALTIME_UNIVERSAL_DISABLED",
        .multiple_boot_partition = "MULTIPLE_BOOT_PARTITION",
        .sixty_four_bit_os = "SIXTY_FOUR_BIT_OS",
        .zero_rearm_count = "ZERO_REARM_COUNT",
        .in_place_upgrade = "IN_PLACE_UPGRADE",
        .anti_virus_installed = "ANTI_VIRUS_INSTALLED",
        .uefi_not_supported = "UEFI_NOT_SUPPORTED",
        .unknown_error = "UNKNOWN_ERROR",
        .appx_packages_installed = "APPX_PACKAGES_INSTALLED",
        .reserved_storage_in_use = "RESERVED_STORAGE_IN_USE",
        .additional_drives_present = "ADDITIONAL_DRIVES_PRESENT",
        .windows_updates_required = "WINDOWS_UPDATES_REQUIRED",
        .sysprep_file_missing = "SYSPREP_FILE_MISSING",
        .user_profile_missing = "USER_PROFILE_MISSING",
        .insufficient_disk_space = "INSUFFICIENT_DISK_SPACE",
        .environment_variables_path_missing_entries = "ENVIRONMENT_VARIABLES_PATH_MISSING_ENTRIES",
        .domain_account_services_found = "DOMAIN_ACCOUNT_SERVICES_FOUND",
        .invalid_ip = "INVALID_IP",
        .remote_desktop_services_disabled = "REMOTE_DESKTOP_SERVICES_DISABLED",
        .windows_modules_installer_disabled = "WINDOWS_MODULES_INSTALLER_DISABLED",
        .amazon_ssm_agent_enabled = "AMAZON_SSM_AGENT_ENABLED",
        .unsupported_security_protocol = "UNSUPPORTED_SECURITY_PROTOCOL",
        .multiple_user_profiles = "MULTIPLE_USER_PROFILES",
        .staged_appx_package = "STAGED_APPX_PACKAGE",
        .unsupported_os_upgrade = "UNSUPPORTED_OS_UPGRADE",
        .insufficient_rearm_count = "INSUFFICIENT_REARM_COUNT",
        .incompatible_protocol = "INCOMPATIBLE_PROTOCOL",
        .incompatible_memory_integrity = "INCOMPATIBLE_MEMORY_INTEGRITY",
        .restricted_drive_letter = "RESTRICTED_DRIVE_LETTER",
    };
};
