pub const WorkspaceState = enum {
    pending,
    available,
    impaired,
    unhealthy,
    rebooting,
    starting,
    rebuilding,
    restoring,
    maintenance,
    admin_maintenance,
    terminating,
    terminated,
    suspended,
    updating,
    stopping,
    stopped,
    @"error",

    pub const json_field_names = .{
        .pending = "PENDING",
        .available = "AVAILABLE",
        .impaired = "IMPAIRED",
        .unhealthy = "UNHEALTHY",
        .rebooting = "REBOOTING",
        .starting = "STARTING",
        .rebuilding = "REBUILDING",
        .restoring = "RESTORING",
        .maintenance = "MAINTENANCE",
        .admin_maintenance = "ADMIN_MAINTENANCE",
        .terminating = "TERMINATING",
        .terminated = "TERMINATED",
        .suspended = "SUSPENDED",
        .updating = "UPDATING",
        .stopping = "STOPPING",
        .stopped = "STOPPED",
        .@"error" = "ERROR",
    };
};
