const std = @import("std");

pub const WorkspaceImageErrorDetailCode = enum {
    outdated_powershell_version,
    office_installed,
    pcoip_agent_installed,
    windows_updates_enabled,
    auto_mount_disabled,
    workspaces_byol_account_not_found,
    workspaces_byol_account_disabled,
    dhcp_disabled,
    disk_free_space,
    additional_drives_attached,
    os_not_supported,
    domain_joined,
    azure_domain_joined,
    firewall_enabled,
    vmware_tools_installed,
    disk_size_exceeded,
    incompatible_partitioning,
    pending_reboot,
    auto_logon_enabled,
    realtime_universal_disabled,
    multiple_boot_partition,
    sixty_four_bit_os,
    zero_rearm_count,
    in_place_upgrade,
    anti_virus_installed,
    uefi_not_supported,
    unknown_error,
    appx_packages_installed,
    reserved_storage_in_use,
    additional_drives_present,
    windows_updates_required,
    sysprep_file_missing,
    user_profile_missing,
    insufficient_disk_space,
    environment_variables_path_missing_entries,
    domain_account_services_found,
    invalid_ip,
    remote_desktop_services_disabled,
    windows_modules_installer_disabled,
    amazon_ssm_agent_enabled,
    unsupported_security_protocol,
    multiple_user_profiles,
    staged_appx_package,
    unsupported_os_upgrade,
    insufficient_rearm_count,
    incompatible_protocol,
    incompatible_memory_integrity,
    restricted_drive_letter,

    pub const json_field_names = .{
        .outdated_powershell_version = "OutdatedPowershellVersion",
        .office_installed = "OfficeInstalled",
        .pcoip_agent_installed = "PCoIPAgentInstalled",
        .windows_updates_enabled = "WindowsUpdatesEnabled",
        .auto_mount_disabled = "AutoMountDisabled",
        .workspaces_byol_account_not_found = "WorkspacesBYOLAccountNotFound",
        .workspaces_byol_account_disabled = "WorkspacesBYOLAccountDisabled",
        .dhcp_disabled = "DHCPDisabled",
        .disk_free_space = "DiskFreeSpace",
        .additional_drives_attached = "AdditionalDrivesAttached",
        .os_not_supported = "OSNotSupported",
        .domain_joined = "DomainJoined",
        .azure_domain_joined = "AzureDomainJoined",
        .firewall_enabled = "FirewallEnabled",
        .vmware_tools_installed = "VMWareToolsInstalled",
        .disk_size_exceeded = "DiskSizeExceeded",
        .incompatible_partitioning = "IncompatiblePartitioning",
        .pending_reboot = "PendingReboot",
        .auto_logon_enabled = "AutoLogonEnabled",
        .realtime_universal_disabled = "RealTimeUniversalDisabled",
        .multiple_boot_partition = "MultipleBootPartition",
        .sixty_four_bit_os = "Requires64BitOS",
        .zero_rearm_count = "ZeroRearmCount",
        .in_place_upgrade = "InPlaceUpgrade",
        .anti_virus_installed = "AntiVirusInstalled",
        .uefi_not_supported = "UEFINotSupported",
        .unknown_error = "UnknownError",
        .appx_packages_installed = "AppXPackagesInstalled",
        .reserved_storage_in_use = "ReservedStorageInUse",
        .additional_drives_present = "AdditionalDrivesPresent",
        .windows_updates_required = "WindowsUpdatesRequired",
        .sysprep_file_missing = "SysPrepFileMissing",
        .user_profile_missing = "UserProfileMissing",
        .insufficient_disk_space = "InsufficientDiskSpace",
        .environment_variables_path_missing_entries = "EnvironmentVariablesPathMissingEntries",
        .domain_account_services_found = "DomainAccountServicesFound",
        .invalid_ip = "InvalidIp",
        .remote_desktop_services_disabled = "RemoteDesktopServicesDisabled",
        .windows_modules_installer_disabled = "WindowsModulesInstallerDisabled",
        .amazon_ssm_agent_enabled = "AmazonSsmAgentEnabled",
        .unsupported_security_protocol = "UnsupportedSecurityProtocol",
        .multiple_user_profiles = "MultipleUserProfiles",
        .staged_appx_package = "StagedAppxPackage",
        .unsupported_os_upgrade = "UnsupportedOsUpgrade",
        .insufficient_rearm_count = "InsufficientRearmCount",
        .incompatible_protocol = "ProtocolOSIncompatibility",
        .incompatible_memory_integrity = "MemoryIntegrityIncompatibility",
        .restricted_drive_letter = "RestrictedDriveLetterInUse",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .outdated_powershell_version => "OutdatedPowershellVersion",
            .office_installed => "OfficeInstalled",
            .pcoip_agent_installed => "PCoIPAgentInstalled",
            .windows_updates_enabled => "WindowsUpdatesEnabled",
            .auto_mount_disabled => "AutoMountDisabled",
            .workspaces_byol_account_not_found => "WorkspacesBYOLAccountNotFound",
            .workspaces_byol_account_disabled => "WorkspacesBYOLAccountDisabled",
            .dhcp_disabled => "DHCPDisabled",
            .disk_free_space => "DiskFreeSpace",
            .additional_drives_attached => "AdditionalDrivesAttached",
            .os_not_supported => "OSNotSupported",
            .domain_joined => "DomainJoined",
            .azure_domain_joined => "AzureDomainJoined",
            .firewall_enabled => "FirewallEnabled",
            .vmware_tools_installed => "VMWareToolsInstalled",
            .disk_size_exceeded => "DiskSizeExceeded",
            .incompatible_partitioning => "IncompatiblePartitioning",
            .pending_reboot => "PendingReboot",
            .auto_logon_enabled => "AutoLogonEnabled",
            .realtime_universal_disabled => "RealTimeUniversalDisabled",
            .multiple_boot_partition => "MultipleBootPartition",
            .sixty_four_bit_os => "Requires64BitOS",
            .zero_rearm_count => "ZeroRearmCount",
            .in_place_upgrade => "InPlaceUpgrade",
            .anti_virus_installed => "AntiVirusInstalled",
            .uefi_not_supported => "UEFINotSupported",
            .unknown_error => "UnknownError",
            .appx_packages_installed => "AppXPackagesInstalled",
            .reserved_storage_in_use => "ReservedStorageInUse",
            .additional_drives_present => "AdditionalDrivesPresent",
            .windows_updates_required => "WindowsUpdatesRequired",
            .sysprep_file_missing => "SysPrepFileMissing",
            .user_profile_missing => "UserProfileMissing",
            .insufficient_disk_space => "InsufficientDiskSpace",
            .environment_variables_path_missing_entries => "EnvironmentVariablesPathMissingEntries",
            .domain_account_services_found => "DomainAccountServicesFound",
            .invalid_ip => "InvalidIp",
            .remote_desktop_services_disabled => "RemoteDesktopServicesDisabled",
            .windows_modules_installer_disabled => "WindowsModulesInstallerDisabled",
            .amazon_ssm_agent_enabled => "AmazonSsmAgentEnabled",
            .unsupported_security_protocol => "UnsupportedSecurityProtocol",
            .multiple_user_profiles => "MultipleUserProfiles",
            .staged_appx_package => "StagedAppxPackage",
            .unsupported_os_upgrade => "UnsupportedOsUpgrade",
            .insufficient_rearm_count => "InsufficientRearmCount",
            .incompatible_protocol => "ProtocolOSIncompatibility",
            .incompatible_memory_integrity => "MemoryIntegrityIncompatibility",
            .restricted_drive_letter => "RestrictedDriveLetterInUse",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
