pub const MetricUnit = enum {
    seconds,
    microseconds,
    milliseconds,
    bytes,
    kilobytes,
    megabytes,
    gigabytes,
    terabytes,
    bits,
    kilobits,
    megabits,
    gigabits,
    terabits,
    percent,
    count,
    bytes_per_second,
    kilobytes_per_second,
    megabytes_per_second,
    gigabytes_per_second,
    terabytes_per_second,
    bits_per_second,
    kilobits_per_second,
    megabits_per_second,
    gigabits_per_second,
    terabits_per_second,
    count_per_second,
    none,

    pub const json_field_names = .{
        .seconds = "SECONDS",
        .microseconds = "MICROSECONDS",
        .milliseconds = "MILLISECONDS",
        .bytes = "BYTES",
        .kilobytes = "KILOBYTES",
        .megabytes = "MEGABYTES",
        .gigabytes = "GIGABYTES",
        .terabytes = "TERABYTES",
        .bits = "BITS",
        .kilobits = "KILOBITS",
        .megabits = "MEGABITS",
        .gigabits = "GIGABITS",
        .terabits = "TERABITS",
        .percent = "PERCENT",
        .count = "COUNT",
        .bytes_per_second = "BYTES_PER_SECOND",
        .kilobytes_per_second = "KILOBYTES_PER_SECOND",
        .megabytes_per_second = "MEGABYTES_PER_SECOND",
        .gigabytes_per_second = "GIGABYTES_PER_SECOND",
        .terabytes_per_second = "TERABYTES_PER_SECOND",
        .bits_per_second = "BITS_PER_SECOND",
        .kilobits_per_second = "KILOBITS_PER_SECOND",
        .megabits_per_second = "MEGABITS_PER_SECOND",
        .gigabits_per_second = "GIGABITS_PER_SECOND",
        .terabits_per_second = "TERABITS_PER_SECOND",
        .count_per_second = "COUNT_PER_SECOND",
        .none = "NONE",
    };
};
