const std = @import("std");

pub const ValidationExceptionType = enum {
    container_type_immutable,
    invalid_pagination_token,
    invalid_pagination_max_results,
    invalid_policy,
    invalid_role_arn,
    manifest_name_collision,
    encryption_method_container_type_mismatch,
    cenc_iv_incompatible,
    encryption_contract_without_audio_rendition_incompatible,
    encryption_contract_with_ism_container_incompatible,
    encryption_contract_unencrypted,
    encryption_contract_shared,
    num_manifests_low,
    num_manifests_high,
    manifest_drm_systems_incompatible,
    drm_systems_encryption_method_incompatible,
    role_arn_not_assumable,
    role_arn_length_out_of_range,
    role_arn_invalid_format,
    url_invalid,
    url_scheme,
    url_user_info,
    url_port,
    url_unknown_host,
    url_local_address,
    url_loopback_address,
    url_link_local_address,
    url_multicast_address,
    member_invalid,
    member_missing,
    member_min_value,
    member_max_value,
    member_min_length,
    member_max_length,
    member_invalid_enum_value,
    member_does_not_match_pattern,
    invalid_manifest_filter,
    invalid_drm_settings,
    invalid_time_delay_seconds,
    end_time_earlier_than_start_time,
    ts_container_type_with_dash_manifest,
    direct_mode_with_timing_source,
    none_mode_with_timing_source,
    timing_source_missing,
    update_period_smaller_than_segment_duration,
    period_triggers_none_specified_with_additional_values,
    drm_signaling_mismatch_segment_encryption_status,
    only_cmaf_input_type_allow_force_endpoint_error_configuration,
    source_disruptions_enabled_incorrectly,
    harvested_manifest_has_start_end_filter_configuration,
    harvested_manifest_not_found_on_endpoint,
    too_many_in_progress_harvest_jobs,
    harvest_job_ineligible_for_cancellation,
    invalid_harvest_job_duration,
    harvest_job_s3_destination_missing_or_incomplete,
    harvest_job_unable_to_write_to_s3_destination,
    harvest_job_customer_endpoint_read_access_denied,
    clip_start_time_with_start_or_end,
    start_tag_time_offset_invalid,
    incompatible_dash_profile_dvb_dash_configuration,
    dash_dvb_attributes_without_dvb_dash_profile,
    incompatible_dash_compactness_configuration,
    incompatible_xml_encoding,
    cmaf_exclude_segment_drm_metadata_incompatible_container_type,
    only_cmaf_input_type_allow_mqcs_input_switching,
    only_cmaf_input_type_allow_mqcs_output_configuration,
    only_cmaf_input_type_allow_preferred_input_configuration,
    ts_container_type_with_mss_manifest,
    cmaf_container_type_with_mss_manifest,
    ism_container_type_with_hls_manifest,
    ism_container_type_with_ll_hls_manifest,
    ism_container_type_with_dash_manifest,
    ism_container_type_with_scte,
    ism_container_with_key_rotation,
    batch_get_secret_value_denied,
    get_secret_value_denied,
    describe_secret_denied,
    invalid_secret_format,
    secret_is_not_one_key_value_pair,
    invalid_secret_key,
    invalid_secret_value,
    secret_arn_resource_not_found,
    decrypt_secret_failed,
    too_many_secrets,
    duplicated_secret,
    malformed_secret_arn,
    secret_from_different_account,
    secret_from_different_region,
    invalid_secret,
    resource_not_in_same_region,
    certificate_resource_not_found,
    certificate_access_denied,
    describe_certificate_failed,
    invalid_certificate_status,
    invalid_certificate_key_algorithm,
    invalid_certificate_signature_algorithm,
    missing_certificate_domain_name,
    invalid_arn,

    pub const json_field_names = .{
        .container_type_immutable = "CONTAINER_TYPE_IMMUTABLE",
        .invalid_pagination_token = "INVALID_PAGINATION_TOKEN",
        .invalid_pagination_max_results = "INVALID_PAGINATION_MAX_RESULTS",
        .invalid_policy = "INVALID_POLICY",
        .invalid_role_arn = "INVALID_ROLE_ARN",
        .manifest_name_collision = "MANIFEST_NAME_COLLISION",
        .encryption_method_container_type_mismatch = "ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH",
        .cenc_iv_incompatible = "CENC_IV_INCOMPATIBLE",
        .encryption_contract_without_audio_rendition_incompatible = "ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE",
        .encryption_contract_with_ism_container_incompatible = "ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE",
        .encryption_contract_unencrypted = "ENCRYPTION_CONTRACT_UNENCRYPTED",
        .encryption_contract_shared = "ENCRYPTION_CONTRACT_SHARED",
        .num_manifests_low = "NUM_MANIFESTS_LOW",
        .num_manifests_high = "NUM_MANIFESTS_HIGH",
        .manifest_drm_systems_incompatible = "MANIFEST_DRM_SYSTEMS_INCOMPATIBLE",
        .drm_systems_encryption_method_incompatible = "DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE",
        .role_arn_not_assumable = "ROLE_ARN_NOT_ASSUMABLE",
        .role_arn_length_out_of_range = "ROLE_ARN_LENGTH_OUT_OF_RANGE",
        .role_arn_invalid_format = "ROLE_ARN_INVALID_FORMAT",
        .url_invalid = "URL_INVALID",
        .url_scheme = "URL_SCHEME",
        .url_user_info = "URL_USER_INFO",
        .url_port = "URL_PORT",
        .url_unknown_host = "URL_UNKNOWN_HOST",
        .url_local_address = "URL_LOCAL_ADDRESS",
        .url_loopback_address = "URL_LOOPBACK_ADDRESS",
        .url_link_local_address = "URL_LINK_LOCAL_ADDRESS",
        .url_multicast_address = "URL_MULTICAST_ADDRESS",
        .member_invalid = "MEMBER_INVALID",
        .member_missing = "MEMBER_MISSING",
        .member_min_value = "MEMBER_MIN_VALUE",
        .member_max_value = "MEMBER_MAX_VALUE",
        .member_min_length = "MEMBER_MIN_LENGTH",
        .member_max_length = "MEMBER_MAX_LENGTH",
        .member_invalid_enum_value = "MEMBER_INVALID_ENUM_VALUE",
        .member_does_not_match_pattern = "MEMBER_DOES_NOT_MATCH_PATTERN",
        .invalid_manifest_filter = "INVALID_MANIFEST_FILTER",
        .invalid_drm_settings = "INVALID_DRM_SETTINGS",
        .invalid_time_delay_seconds = "INVALID_TIME_DELAY_SECONDS",
        .end_time_earlier_than_start_time = "END_TIME_EARLIER_THAN_START_TIME",
        .ts_container_type_with_dash_manifest = "TS_CONTAINER_TYPE_WITH_DASH_MANIFEST",
        .direct_mode_with_timing_source = "DIRECT_MODE_WITH_TIMING_SOURCE",
        .none_mode_with_timing_source = "NONE_MODE_WITH_TIMING_SOURCE",
        .timing_source_missing = "TIMING_SOURCE_MISSING",
        .update_period_smaller_than_segment_duration = "UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION",
        .period_triggers_none_specified_with_additional_values = "PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES",
        .drm_signaling_mismatch_segment_encryption_status = "DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS",
        .only_cmaf_input_type_allow_force_endpoint_error_configuration = "ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION",
        .source_disruptions_enabled_incorrectly = "SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY",
        .harvested_manifest_has_start_end_filter_configuration = "HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION",
        .harvested_manifest_not_found_on_endpoint = "HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT",
        .too_many_in_progress_harvest_jobs = "TOO_MANY_IN_PROGRESS_HARVEST_JOBS",
        .harvest_job_ineligible_for_cancellation = "HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION",
        .invalid_harvest_job_duration = "INVALID_HARVEST_JOB_DURATION",
        .harvest_job_s3_destination_missing_or_incomplete = "HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE",
        .harvest_job_unable_to_write_to_s3_destination = "HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION",
        .harvest_job_customer_endpoint_read_access_denied = "HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED",
        .clip_start_time_with_start_or_end = "CLIP_START_TIME_WITH_START_OR_END",
        .start_tag_time_offset_invalid = "START_TAG_TIME_OFFSET_INVALID",
        .incompatible_dash_profile_dvb_dash_configuration = "INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION",
        .dash_dvb_attributes_without_dvb_dash_profile = "DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE",
        .incompatible_dash_compactness_configuration = "INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION",
        .incompatible_xml_encoding = "INCOMPATIBLE_XML_ENCODING",
        .cmaf_exclude_segment_drm_metadata_incompatible_container_type = "CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE",
        .only_cmaf_input_type_allow_mqcs_input_switching = "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING",
        .only_cmaf_input_type_allow_mqcs_output_configuration = "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION",
        .only_cmaf_input_type_allow_preferred_input_configuration = "ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION",
        .ts_container_type_with_mss_manifest = "TS_CONTAINER_TYPE_WITH_MSS_MANIFEST",
        .cmaf_container_type_with_mss_manifest = "CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST",
        .ism_container_type_with_hls_manifest = "ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST",
        .ism_container_type_with_ll_hls_manifest = "ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST",
        .ism_container_type_with_dash_manifest = "ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST",
        .ism_container_type_with_scte = "ISM_CONTAINER_TYPE_WITH_SCTE",
        .ism_container_with_key_rotation = "ISM_CONTAINER_WITH_KEY_ROTATION",
        .batch_get_secret_value_denied = "BATCH_GET_SECRET_VALUE_DENIED",
        .get_secret_value_denied = "GET_SECRET_VALUE_DENIED",
        .describe_secret_denied = "DESCRIBE_SECRET_DENIED",
        .invalid_secret_format = "INVALID_SECRET_FORMAT",
        .secret_is_not_one_key_value_pair = "SECRET_IS_NOT_ONE_KEY_VALUE_PAIR",
        .invalid_secret_key = "INVALID_SECRET_KEY",
        .invalid_secret_value = "INVALID_SECRET_VALUE",
        .secret_arn_resource_not_found = "SECRET_ARN_RESOURCE_NOT_FOUND",
        .decrypt_secret_failed = "DECRYPT_SECRET_FAILED",
        .too_many_secrets = "TOO_MANY_SECRETS",
        .duplicated_secret = "DUPLICATED_SECRET",
        .malformed_secret_arn = "MALFORMED_SECRET_ARN",
        .secret_from_different_account = "SECRET_FROM_DIFFERENT_ACCOUNT",
        .secret_from_different_region = "SECRET_FROM_DIFFERENT_REGION",
        .invalid_secret = "INVALID_SECRET",
        .resource_not_in_same_region = "RESOURCE_NOT_IN_SAME_REGION",
        .certificate_resource_not_found = "CERTIFICATE_RESOURCE_NOT_FOUND",
        .certificate_access_denied = "CERTIFICATE_ACCESS_DENIED",
        .describe_certificate_failed = "DESCRIBE_CERTIFICATE_FAILED",
        .invalid_certificate_status = "INVALID_CERTIFICATE_STATUS",
        .invalid_certificate_key_algorithm = "INVALID_CERTIFICATE_KEY_ALGORITHM",
        .invalid_certificate_signature_algorithm = "INVALID_CERTIFICATE_SIGNATURE_ALGORITHM",
        .missing_certificate_domain_name = "MISSING_CERTIFICATE_DOMAIN_NAME",
        .invalid_arn = "INVALID_ARN",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .container_type_immutable => "CONTAINER_TYPE_IMMUTABLE",
            .invalid_pagination_token => "INVALID_PAGINATION_TOKEN",
            .invalid_pagination_max_results => "INVALID_PAGINATION_MAX_RESULTS",
            .invalid_policy => "INVALID_POLICY",
            .invalid_role_arn => "INVALID_ROLE_ARN",
            .manifest_name_collision => "MANIFEST_NAME_COLLISION",
            .encryption_method_container_type_mismatch => "ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH",
            .cenc_iv_incompatible => "CENC_IV_INCOMPATIBLE",
            .encryption_contract_without_audio_rendition_incompatible => "ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE",
            .encryption_contract_with_ism_container_incompatible => "ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE",
            .encryption_contract_unencrypted => "ENCRYPTION_CONTRACT_UNENCRYPTED",
            .encryption_contract_shared => "ENCRYPTION_CONTRACT_SHARED",
            .num_manifests_low => "NUM_MANIFESTS_LOW",
            .num_manifests_high => "NUM_MANIFESTS_HIGH",
            .manifest_drm_systems_incompatible => "MANIFEST_DRM_SYSTEMS_INCOMPATIBLE",
            .drm_systems_encryption_method_incompatible => "DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE",
            .role_arn_not_assumable => "ROLE_ARN_NOT_ASSUMABLE",
            .role_arn_length_out_of_range => "ROLE_ARN_LENGTH_OUT_OF_RANGE",
            .role_arn_invalid_format => "ROLE_ARN_INVALID_FORMAT",
            .url_invalid => "URL_INVALID",
            .url_scheme => "URL_SCHEME",
            .url_user_info => "URL_USER_INFO",
            .url_port => "URL_PORT",
            .url_unknown_host => "URL_UNKNOWN_HOST",
            .url_local_address => "URL_LOCAL_ADDRESS",
            .url_loopback_address => "URL_LOOPBACK_ADDRESS",
            .url_link_local_address => "URL_LINK_LOCAL_ADDRESS",
            .url_multicast_address => "URL_MULTICAST_ADDRESS",
            .member_invalid => "MEMBER_INVALID",
            .member_missing => "MEMBER_MISSING",
            .member_min_value => "MEMBER_MIN_VALUE",
            .member_max_value => "MEMBER_MAX_VALUE",
            .member_min_length => "MEMBER_MIN_LENGTH",
            .member_max_length => "MEMBER_MAX_LENGTH",
            .member_invalid_enum_value => "MEMBER_INVALID_ENUM_VALUE",
            .member_does_not_match_pattern => "MEMBER_DOES_NOT_MATCH_PATTERN",
            .invalid_manifest_filter => "INVALID_MANIFEST_FILTER",
            .invalid_drm_settings => "INVALID_DRM_SETTINGS",
            .invalid_time_delay_seconds => "INVALID_TIME_DELAY_SECONDS",
            .end_time_earlier_than_start_time => "END_TIME_EARLIER_THAN_START_TIME",
            .ts_container_type_with_dash_manifest => "TS_CONTAINER_TYPE_WITH_DASH_MANIFEST",
            .direct_mode_with_timing_source => "DIRECT_MODE_WITH_TIMING_SOURCE",
            .none_mode_with_timing_source => "NONE_MODE_WITH_TIMING_SOURCE",
            .timing_source_missing => "TIMING_SOURCE_MISSING",
            .update_period_smaller_than_segment_duration => "UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION",
            .period_triggers_none_specified_with_additional_values => "PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES",
            .drm_signaling_mismatch_segment_encryption_status => "DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS",
            .only_cmaf_input_type_allow_force_endpoint_error_configuration => "ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION",
            .source_disruptions_enabled_incorrectly => "SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY",
            .harvested_manifest_has_start_end_filter_configuration => "HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION",
            .harvested_manifest_not_found_on_endpoint => "HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT",
            .too_many_in_progress_harvest_jobs => "TOO_MANY_IN_PROGRESS_HARVEST_JOBS",
            .harvest_job_ineligible_for_cancellation => "HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION",
            .invalid_harvest_job_duration => "INVALID_HARVEST_JOB_DURATION",
            .harvest_job_s3_destination_missing_or_incomplete => "HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE",
            .harvest_job_unable_to_write_to_s3_destination => "HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION",
            .harvest_job_customer_endpoint_read_access_denied => "HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED",
            .clip_start_time_with_start_or_end => "CLIP_START_TIME_WITH_START_OR_END",
            .start_tag_time_offset_invalid => "START_TAG_TIME_OFFSET_INVALID",
            .incompatible_dash_profile_dvb_dash_configuration => "INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION",
            .dash_dvb_attributes_without_dvb_dash_profile => "DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE",
            .incompatible_dash_compactness_configuration => "INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION",
            .incompatible_xml_encoding => "INCOMPATIBLE_XML_ENCODING",
            .cmaf_exclude_segment_drm_metadata_incompatible_container_type => "CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE",
            .only_cmaf_input_type_allow_mqcs_input_switching => "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING",
            .only_cmaf_input_type_allow_mqcs_output_configuration => "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION",
            .only_cmaf_input_type_allow_preferred_input_configuration => "ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION",
            .ts_container_type_with_mss_manifest => "TS_CONTAINER_TYPE_WITH_MSS_MANIFEST",
            .cmaf_container_type_with_mss_manifest => "CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST",
            .ism_container_type_with_hls_manifest => "ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST",
            .ism_container_type_with_ll_hls_manifest => "ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST",
            .ism_container_type_with_dash_manifest => "ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST",
            .ism_container_type_with_scte => "ISM_CONTAINER_TYPE_WITH_SCTE",
            .ism_container_with_key_rotation => "ISM_CONTAINER_WITH_KEY_ROTATION",
            .batch_get_secret_value_denied => "BATCH_GET_SECRET_VALUE_DENIED",
            .get_secret_value_denied => "GET_SECRET_VALUE_DENIED",
            .describe_secret_denied => "DESCRIBE_SECRET_DENIED",
            .invalid_secret_format => "INVALID_SECRET_FORMAT",
            .secret_is_not_one_key_value_pair => "SECRET_IS_NOT_ONE_KEY_VALUE_PAIR",
            .invalid_secret_key => "INVALID_SECRET_KEY",
            .invalid_secret_value => "INVALID_SECRET_VALUE",
            .secret_arn_resource_not_found => "SECRET_ARN_RESOURCE_NOT_FOUND",
            .decrypt_secret_failed => "DECRYPT_SECRET_FAILED",
            .too_many_secrets => "TOO_MANY_SECRETS",
            .duplicated_secret => "DUPLICATED_SECRET",
            .malformed_secret_arn => "MALFORMED_SECRET_ARN",
            .secret_from_different_account => "SECRET_FROM_DIFFERENT_ACCOUNT",
            .secret_from_different_region => "SECRET_FROM_DIFFERENT_REGION",
            .invalid_secret => "INVALID_SECRET",
            .resource_not_in_same_region => "RESOURCE_NOT_IN_SAME_REGION",
            .certificate_resource_not_found => "CERTIFICATE_RESOURCE_NOT_FOUND",
            .certificate_access_denied => "CERTIFICATE_ACCESS_DENIED",
            .describe_certificate_failed => "DESCRIBE_CERTIFICATE_FAILED",
            .invalid_certificate_status => "INVALID_CERTIFICATE_STATUS",
            .invalid_certificate_key_algorithm => "INVALID_CERTIFICATE_KEY_ALGORITHM",
            .invalid_certificate_signature_algorithm => "INVALID_CERTIFICATE_SIGNATURE_ALGORITHM",
            .missing_certificate_domain_name => "MISSING_CERTIFICATE_DOMAIN_NAME",
            .invalid_arn => "INVALID_ARN",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
