const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Attribute = @import("attribute.zig").Attribute;

pub const CreateAssessmentTemplateInput = struct {
    /// The ARN that specifies the assessment target for which you want to create
    /// the
    /// assessment template.
    assessment_target_arn: []const u8,

    /// The user-defined name that identifies the assessment template that you want
    /// to
    /// create. You can create several assessment templates for an assessment
    /// target. The names of
    /// the assessment templates that correspond to a particular assessment target
    /// must be
    /// unique.
    assessment_template_name: []const u8,

    /// The duration of the assessment run in seconds.
    duration_in_seconds: i32,

    /// The ARNs that specify the rules packages that you want to attach to the
    /// assessment
    /// template.
    rules_package_arns: []const []const u8,

    /// The user-defined attributes that are assigned to every finding that is
    /// generated by
    /// the assessment run that uses this assessment template. An attribute is a key
    /// and value pair
    /// (an Attribute object). Within an assessment template, each key must be
    /// unique.
    user_attributes_for_findings: ?[]const Attribute = null,

    pub const json_field_names = .{
        .assessment_target_arn = "assessmentTargetArn",
        .assessment_template_name = "assessmentTemplateName",
        .duration_in_seconds = "durationInSeconds",
        .rules_package_arns = "rulesPackageArns",
        .user_attributes_for_findings = "userAttributesForFindings",
    };
};

pub const CreateAssessmentTemplateOutput = struct {
    /// The ARN that specifies the assessment template that is created.
    assessment_template_arn: []const u8,

    pub const json_field_names = .{
        .assessment_template_arn = "assessmentTemplateArn",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateAssessmentTemplateInput, options: CallOptions) !CreateAssessmentTemplateOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "inspector", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateAssessmentTemplateInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("inspector", "Inspector", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "InspectorService.CreateAssessmentTemplate");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateAssessmentTemplateOutput {
    _ = status;
    _ = headers;
    return aws.json.parseJsonObject(CreateAssessmentTemplateOutput, body, allocator);
}
