const std = @import("std");

pub const InvalidInputErrorCode = enum {
    invalid_assessment_target_arn,
    invalid_assessment_template_arn,
    invalid_assessment_run_arn,
    invalid_finding_arn,
    invalid_resource_group_arn,
    invalid_rules_package_arn,
    invalid_resource_arn,
    invalid_sns_topic_arn,
    invalid_iam_role_arn,
    invalid_assessment_target_name,
    invalid_assessment_target_name_pattern,
    invalid_assessment_template_name,
    invalid_assessment_template_name_pattern,
    invalid_assessment_template_duration,
    invalid_assessment_template_duration_range,
    invalid_assessment_run_duration_range,
    invalid_assessment_run_start_time_range,
    invalid_assessment_run_completion_time_range,
    invalid_assessment_run_state_change_time_range,
    invalid_assessment_run_state,
    invalid_tag,
    invalid_tag_key,
    invalid_tag_value,
    invalid_resource_group_tag_key,
    invalid_resource_group_tag_value,
    invalid_attribute,
    invalid_user_attribute,
    invalid_user_attribute_key,
    invalid_user_attribute_value,
    invalid_pagination_token,
    invalid_max_results,
    invalid_agent_id,
    invalid_auto_scaling_group,
    invalid_rule_name,
    invalid_severity,
    invalid_locale,
    invalid_event,
    assessment_target_name_already_taken,
    assessment_template_name_already_taken,
    invalid_number_of_assessment_target_arns,
    invalid_number_of_assessment_template_arns,
    invalid_number_of_assessment_run_arns,
    invalid_number_of_finding_arns,
    invalid_number_of_resource_group_arns,
    invalid_number_of_rules_package_arns,
    invalid_number_of_assessment_run_states,
    invalid_number_of_tags,
    invalid_number_of_resource_group_tags,
    invalid_number_of_attributes,
    invalid_number_of_user_attributes,
    invalid_number_of_agent_ids,
    invalid_number_of_auto_scaling_groups,
    invalid_number_of_rule_names,
    invalid_number_of_severities,

    pub const json_field_names = .{
        .invalid_assessment_target_arn = "INVALID_ASSESSMENT_TARGET_ARN",
        .invalid_assessment_template_arn = "INVALID_ASSESSMENT_TEMPLATE_ARN",
        .invalid_assessment_run_arn = "INVALID_ASSESSMENT_RUN_ARN",
        .invalid_finding_arn = "INVALID_FINDING_ARN",
        .invalid_resource_group_arn = "INVALID_RESOURCE_GROUP_ARN",
        .invalid_rules_package_arn = "INVALID_RULES_PACKAGE_ARN",
        .invalid_resource_arn = "INVALID_RESOURCE_ARN",
        .invalid_sns_topic_arn = "INVALID_SNS_TOPIC_ARN",
        .invalid_iam_role_arn = "INVALID_IAM_ROLE_ARN",
        .invalid_assessment_target_name = "INVALID_ASSESSMENT_TARGET_NAME",
        .invalid_assessment_target_name_pattern = "INVALID_ASSESSMENT_TARGET_NAME_PATTERN",
        .invalid_assessment_template_name = "INVALID_ASSESSMENT_TEMPLATE_NAME",
        .invalid_assessment_template_name_pattern = "INVALID_ASSESSMENT_TEMPLATE_NAME_PATTERN",
        .invalid_assessment_template_duration = "INVALID_ASSESSMENT_TEMPLATE_DURATION",
        .invalid_assessment_template_duration_range = "INVALID_ASSESSMENT_TEMPLATE_DURATION_RANGE",
        .invalid_assessment_run_duration_range = "INVALID_ASSESSMENT_RUN_DURATION_RANGE",
        .invalid_assessment_run_start_time_range = "INVALID_ASSESSMENT_RUN_START_TIME_RANGE",
        .invalid_assessment_run_completion_time_range = "INVALID_ASSESSMENT_RUN_COMPLETION_TIME_RANGE",
        .invalid_assessment_run_state_change_time_range = "INVALID_ASSESSMENT_RUN_STATE_CHANGE_TIME_RANGE",
        .invalid_assessment_run_state = "INVALID_ASSESSMENT_RUN_STATE",
        .invalid_tag = "INVALID_TAG",
        .invalid_tag_key = "INVALID_TAG_KEY",
        .invalid_tag_value = "INVALID_TAG_VALUE",
        .invalid_resource_group_tag_key = "INVALID_RESOURCE_GROUP_TAG_KEY",
        .invalid_resource_group_tag_value = "INVALID_RESOURCE_GROUP_TAG_VALUE",
        .invalid_attribute = "INVALID_ATTRIBUTE",
        .invalid_user_attribute = "INVALID_USER_ATTRIBUTE",
        .invalid_user_attribute_key = "INVALID_USER_ATTRIBUTE_KEY",
        .invalid_user_attribute_value = "INVALID_USER_ATTRIBUTE_VALUE",
        .invalid_pagination_token = "INVALID_PAGINATION_TOKEN",
        .invalid_max_results = "INVALID_MAX_RESULTS",
        .invalid_agent_id = "INVALID_AGENT_ID",
        .invalid_auto_scaling_group = "INVALID_AUTO_SCALING_GROUP",
        .invalid_rule_name = "INVALID_RULE_NAME",
        .invalid_severity = "INVALID_SEVERITY",
        .invalid_locale = "INVALID_LOCALE",
        .invalid_event = "INVALID_EVENT",
        .assessment_target_name_already_taken = "ASSESSMENT_TARGET_NAME_ALREADY_TAKEN",
        .assessment_template_name_already_taken = "ASSESSMENT_TEMPLATE_NAME_ALREADY_TAKEN",
        .invalid_number_of_assessment_target_arns = "INVALID_NUMBER_OF_ASSESSMENT_TARGET_ARNS",
        .invalid_number_of_assessment_template_arns = "INVALID_NUMBER_OF_ASSESSMENT_TEMPLATE_ARNS",
        .invalid_number_of_assessment_run_arns = "INVALID_NUMBER_OF_ASSESSMENT_RUN_ARNS",
        .invalid_number_of_finding_arns = "INVALID_NUMBER_OF_FINDING_ARNS",
        .invalid_number_of_resource_group_arns = "INVALID_NUMBER_OF_RESOURCE_GROUP_ARNS",
        .invalid_number_of_rules_package_arns = "INVALID_NUMBER_OF_RULES_PACKAGE_ARNS",
        .invalid_number_of_assessment_run_states = "INVALID_NUMBER_OF_ASSESSMENT_RUN_STATES",
        .invalid_number_of_tags = "INVALID_NUMBER_OF_TAGS",
        .invalid_number_of_resource_group_tags = "INVALID_NUMBER_OF_RESOURCE_GROUP_TAGS",
        .invalid_number_of_attributes = "INVALID_NUMBER_OF_ATTRIBUTES",
        .invalid_number_of_user_attributes = "INVALID_NUMBER_OF_USER_ATTRIBUTES",
        .invalid_number_of_agent_ids = "INVALID_NUMBER_OF_AGENT_IDS",
        .invalid_number_of_auto_scaling_groups = "INVALID_NUMBER_OF_AUTO_SCALING_GROUPS",
        .invalid_number_of_rule_names = "INVALID_NUMBER_OF_RULE_NAMES",
        .invalid_number_of_severities = "INVALID_NUMBER_OF_SEVERITIES",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .invalid_assessment_target_arn => "INVALID_ASSESSMENT_TARGET_ARN",
            .invalid_assessment_template_arn => "INVALID_ASSESSMENT_TEMPLATE_ARN",
            .invalid_assessment_run_arn => "INVALID_ASSESSMENT_RUN_ARN",
            .invalid_finding_arn => "INVALID_FINDING_ARN",
            .invalid_resource_group_arn => "INVALID_RESOURCE_GROUP_ARN",
            .invalid_rules_package_arn => "INVALID_RULES_PACKAGE_ARN",
            .invalid_resource_arn => "INVALID_RESOURCE_ARN",
            .invalid_sns_topic_arn => "INVALID_SNS_TOPIC_ARN",
            .invalid_iam_role_arn => "INVALID_IAM_ROLE_ARN",
            .invalid_assessment_target_name => "INVALID_ASSESSMENT_TARGET_NAME",
            .invalid_assessment_target_name_pattern => "INVALID_ASSESSMENT_TARGET_NAME_PATTERN",
            .invalid_assessment_template_name => "INVALID_ASSESSMENT_TEMPLATE_NAME",
            .invalid_assessment_template_name_pattern => "INVALID_ASSESSMENT_TEMPLATE_NAME_PATTERN",
            .invalid_assessment_template_duration => "INVALID_ASSESSMENT_TEMPLATE_DURATION",
            .invalid_assessment_template_duration_range => "INVALID_ASSESSMENT_TEMPLATE_DURATION_RANGE",
            .invalid_assessment_run_duration_range => "INVALID_ASSESSMENT_RUN_DURATION_RANGE",
            .invalid_assessment_run_start_time_range => "INVALID_ASSESSMENT_RUN_START_TIME_RANGE",
            .invalid_assessment_run_completion_time_range => "INVALID_ASSESSMENT_RUN_COMPLETION_TIME_RANGE",
            .invalid_assessment_run_state_change_time_range => "INVALID_ASSESSMENT_RUN_STATE_CHANGE_TIME_RANGE",
            .invalid_assessment_run_state => "INVALID_ASSESSMENT_RUN_STATE",
            .invalid_tag => "INVALID_TAG",
            .invalid_tag_key => "INVALID_TAG_KEY",
            .invalid_tag_value => "INVALID_TAG_VALUE",
            .invalid_resource_group_tag_key => "INVALID_RESOURCE_GROUP_TAG_KEY",
            .invalid_resource_group_tag_value => "INVALID_RESOURCE_GROUP_TAG_VALUE",
            .invalid_attribute => "INVALID_ATTRIBUTE",
            .invalid_user_attribute => "INVALID_USER_ATTRIBUTE",
            .invalid_user_attribute_key => "INVALID_USER_ATTRIBUTE_KEY",
            .invalid_user_attribute_value => "INVALID_USER_ATTRIBUTE_VALUE",
            .invalid_pagination_token => "INVALID_PAGINATION_TOKEN",
            .invalid_max_results => "INVALID_MAX_RESULTS",
            .invalid_agent_id => "INVALID_AGENT_ID",
            .invalid_auto_scaling_group => "INVALID_AUTO_SCALING_GROUP",
            .invalid_rule_name => "INVALID_RULE_NAME",
            .invalid_severity => "INVALID_SEVERITY",
            .invalid_locale => "INVALID_LOCALE",
            .invalid_event => "INVALID_EVENT",
            .assessment_target_name_already_taken => "ASSESSMENT_TARGET_NAME_ALREADY_TAKEN",
            .assessment_template_name_already_taken => "ASSESSMENT_TEMPLATE_NAME_ALREADY_TAKEN",
            .invalid_number_of_assessment_target_arns => "INVALID_NUMBER_OF_ASSESSMENT_TARGET_ARNS",
            .invalid_number_of_assessment_template_arns => "INVALID_NUMBER_OF_ASSESSMENT_TEMPLATE_ARNS",
            .invalid_number_of_assessment_run_arns => "INVALID_NUMBER_OF_ASSESSMENT_RUN_ARNS",
            .invalid_number_of_finding_arns => "INVALID_NUMBER_OF_FINDING_ARNS",
            .invalid_number_of_resource_group_arns => "INVALID_NUMBER_OF_RESOURCE_GROUP_ARNS",
            .invalid_number_of_rules_package_arns => "INVALID_NUMBER_OF_RULES_PACKAGE_ARNS",
            .invalid_number_of_assessment_run_states => "INVALID_NUMBER_OF_ASSESSMENT_RUN_STATES",
            .invalid_number_of_tags => "INVALID_NUMBER_OF_TAGS",
            .invalid_number_of_resource_group_tags => "INVALID_NUMBER_OF_RESOURCE_GROUP_TAGS",
            .invalid_number_of_attributes => "INVALID_NUMBER_OF_ATTRIBUTES",
            .invalid_number_of_user_attributes => "INVALID_NUMBER_OF_USER_ATTRIBUTES",
            .invalid_number_of_agent_ids => "INVALID_NUMBER_OF_AGENT_IDS",
            .invalid_number_of_auto_scaling_groups => "INVALID_NUMBER_OF_AUTO_SCALING_GROUPS",
            .invalid_number_of_rule_names => "INVALID_NUMBER_OF_RULE_NAMES",
            .invalid_number_of_severities => "INVALID_NUMBER_OF_SEVERITIES",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
