/// Contains settings that specify the location of an Amazon S3 bucket used to
/// store the output of
/// a Face Liveness session. Note that the S3 bucket must be located in the
/// caller's AWS account
/// and in the same region as the Face Liveness end-point. Additionally, the
/// Amazon S3 object keys are
/// auto-generated by the Face Liveness system.
pub const LivenessOutputConfig = struct {
    /// The path to an AWS Amazon S3 bucket used to store Face Liveness session
    /// results.
    s3_bucket: []const u8,

    /// The prefix prepended to the output files for the Face Liveness session
    /// results.
    s3_key_prefix: ?[]const u8,

    pub const json_field_names = .{
        .s3_bucket = "S3Bucket",
        .s3_key_prefix = "S3KeyPrefix",
    };
};
