pub const PluginType = enum {
    service_now,
    salesforce,
    jira,
    zendesk,
    custom,
    asana,
    atlassian_confluence,
    google_calendar,
    jira_cloud,
    microsoft_exchange,
    microsoft_teams,
    pagerduty_advance,
    salesforce_crm,
    servicenow_now_platform,
    smartsheet,
    zendesk_suite,

    pub const json_field_names = .{
        .service_now = "SERVICE_NOW",
        .salesforce = "SALESFORCE",
        .jira = "JIRA",
        .zendesk = "ZENDESK",
        .custom = "CUSTOM",
        .asana = "ASANA",
        .atlassian_confluence = "ATLASSIAN_CONFLUENCE",
        .google_calendar = "GOOGLE_CALENDAR",
        .jira_cloud = "JIRA_CLOUD",
        .microsoft_exchange = "MICROSOFT_EXCHANGE",
        .microsoft_teams = "MICROSOFT_TEAMS",
        .pagerduty_advance = "PAGERDUTY_ADVANCE",
        .salesforce_crm = "SALESFORCE_CRM",
        .servicenow_now_platform = "SERVICENOW_NOW_PLATFORM",
        .smartsheet = "SMARTSHEET",
        .zendesk_suite = "ZENDESK_SUITE",
    };
};
