const AttributeFilter = @import("attribute_filter.zig").AttributeFilter;
const CardOutputSource = @import("card_output_source.zig").CardOutputSource;
const CardType = @import("card_type.zig").CardType;

/// A card in a Amazon Q App that generates a response based on the Amazon Q
/// Business service.
pub const QQueryCard = struct {
    /// The Amazon Q Business filters applied in this query card when resolving data
    /// sources
    attribute_filter: ?AttributeFilter = null,

    /// Any dependencies or requirements for the query card.
    dependencies: []const []const u8,

    /// The unique identifier of the query card.
    id: []const u8,

    /// Any dependencies for the query card, where the dependencies are references
    /// to the collected responses.
    memory_references: ?[]const []const u8 = null,

    /// The source or type of output generated by the query card.
    output_source: CardOutputSource,

    /// The prompt or instructions displayed for the query card.
    prompt: []const u8,

    /// The title or label of the query card.
    title: []const u8,

    /// The type of the card.
    @"type": CardType,

    pub const json_field_names = .{
        .attribute_filter = "attributeFilter",
        .dependencies = "dependencies",
        .id = "id",
        .memory_references = "memoryReferences",
        .output_source = "outputSource",
        .prompt = "prompt",
        .title = "title",
        .@"type" = "type",
    };
};
