pub const StandardUnit = enum {
    microseconds,
    milliseconds,
    seconds,
    bytes,
    kilobytes,
    megabytes,
    gigabytes,
    terabytes,
    bits,
    kilobits,
    megabits,
    gigabits,
    terabits,
    percent,
    count,
    bytes_second,
    kilobytes_second,
    megabytes_second,
    gigabytes_second,
    terabytes_second,
    bits_second,
    kilobits_second,
    megabits_second,
    gigabits_second,
    terabits_second,
    count_second,
    none,

    pub const json_field_names = .{
        .microseconds = "MICROSECONDS",
        .milliseconds = "MILLISECONDS",
        .seconds = "SECONDS",
        .bytes = "BYTES",
        .kilobytes = "KILOBYTES",
        .megabytes = "MEGABYTES",
        .gigabytes = "GIGABYTES",
        .terabytes = "TERABYTES",
        .bits = "BITS",
        .kilobits = "KILOBITS",
        .megabits = "MEGABITS",
        .gigabits = "GIGABITS",
        .terabits = "TERABITS",
        .percent = "PERCENT",
        .count = "COUNT",
        .bytes_second = "BYTES_SECOND",
        .kilobytes_second = "KILOBYTES_SECOND",
        .megabytes_second = "MEGABYTES_SECOND",
        .gigabytes_second = "GIGABYTES_SECOND",
        .terabytes_second = "TERABYTES_SECOND",
        .bits_second = "BITS_SECOND",
        .kilobits_second = "KILOBITS_SECOND",
        .megabits_second = "MEGABITS_SECOND",
        .gigabits_second = "GIGABITS_SECOND",
        .terabits_second = "TERABITS_SECOND",
        .count_second = "COUNT_SECOND",
        .none = "NONE",
    };
};
