const ActionHistoryDetails = @import("action_history_details.zig").ActionHistoryDetails;
const EventType = @import("event_type.zig").EventType;
const ActionStatus = @import("action_status.zig").ActionStatus;

/// The historical records for a budget action.
pub const ActionHistory = struct {
    /// The description of the details for the event.
    action_history_details: ActionHistoryDetails,

    /// This distinguishes between whether the events are triggered by the user or
    /// are
    /// generated by the system.
    event_type: EventType,

    /// The status of action at the time of the event.
    status: ActionStatus,

    timestamp: i64,

    pub const json_field_names = .{
        .action_history_details = "ActionHistoryDetails",
        .event_type = "EventType",
        .status = "Status",
        .timestamp = "Timestamp",
    };
};
