pub const Dimension = enum {
    az,
    instance_type,
    linked_account,
    linked_account_name,
    operation,
    purchase_type,
    region,
    service,
    service_code,
    usage_type,
    usage_type_group,
    record_type,
    operating_system,
    tenancy,
    scope,
    platform,
    subscription_id,
    legal_entity_name,
    invoicing_entity,
    deployment_option,
    database_engine,
    cache_engine,
    instance_type_family,
    billing_entity,
    reservation_id,
    resource_id,
    rightsizing_type,
    savings_plans_type,
    savings_plan_arn,
    payment_option,
    reservation_modified,
    tag_key,
    cost_category_name,

    pub const json_field_names = .{
        .az = "AZ",
        .instance_type = "INSTANCE_TYPE",
        .linked_account = "LINKED_ACCOUNT",
        .linked_account_name = "LINKED_ACCOUNT_NAME",
        .operation = "OPERATION",
        .purchase_type = "PURCHASE_TYPE",
        .region = "REGION",
        .service = "SERVICE",
        .service_code = "SERVICE_CODE",
        .usage_type = "USAGE_TYPE",
        .usage_type_group = "USAGE_TYPE_GROUP",
        .record_type = "RECORD_TYPE",
        .operating_system = "OPERATING_SYSTEM",
        .tenancy = "TENANCY",
        .scope = "SCOPE",
        .platform = "PLATFORM",
        .subscription_id = "SUBSCRIPTION_ID",
        .legal_entity_name = "LEGAL_ENTITY_NAME",
        .invoicing_entity = "INVOICING_ENTITY",
        .deployment_option = "DEPLOYMENT_OPTION",
        .database_engine = "DATABASE_ENGINE",
        .cache_engine = "CACHE_ENGINE",
        .instance_type_family = "INSTANCE_TYPE_FAMILY",
        .billing_entity = "BILLING_ENTITY",
        .reservation_id = "RESERVATION_ID",
        .resource_id = "RESOURCE_ID",
        .rightsizing_type = "RIGHTSIZING_TYPE",
        .savings_plans_type = "SAVINGS_PLANS_TYPE",
        .savings_plan_arn = "SAVINGS_PLAN_ARN",
        .payment_option = "PAYMENT_OPTION",
        .reservation_modified = "RESERVATION_MODIFIED",
        .tag_key = "TAG_KEY",
        .cost_category_name = "COST_CATEGORY_NAME",
    };
};
