/// An object with the permanent IAM role identity and the temporary session
/// name.
pub const AssumedRoleUser = struct {
    /// The ARN of the IAM role that the temporary credentials authenticate to.
    arn: []const u8,

    /// The session name of the temporary session requested to STS. The value
    /// is a unique identifier that contains the role ID, a colon (`:`), and the
    /// role
    /// session name of the role that is being assumed. The role ID is generated by
    /// IAM when
    /// the role is created. The role session name part of the value follows this
    /// format:
    /// `eks-*clustername*-*podname*-*random
    /// UUID*
    /// `
    assume_role_id: []const u8,

    pub const json_field_names = .{
        .arn = "arn",
        .assume_role_id = "assumeRoleId",
    };
};
