pub const AwsOpportunityStage = enum {
    not_started,
    in_progress,
    prospect,
    engaged,
    identified,
    qualify,
    research,
    seller_engaged,
    evaluating,
    seller_registered,
    term_sheet_negotiation,
    contract_negotiation,
    onboarding,
    building_integration,
    qualified,
    on_hold,
    technical_validation,
    business_validation,
    committed,
    launched,
    deferred_to_partner,
    closed_lost,
    completed,
    closed_incomplete,

    pub const json_field_names = .{
        .not_started = "NOT_STARTED",
        .in_progress = "IN_PROGRESS",
        .prospect = "PROSPECT",
        .engaged = "ENGAGED",
        .identified = "IDENTIFIED",
        .qualify = "QUALIFY",
        .research = "RESEARCH",
        .seller_engaged = "SELLER_ENGAGED",
        .evaluating = "EVALUATING",
        .seller_registered = "SELLER_REGISTERED",
        .term_sheet_negotiation = "TERM_SHEET_NEGOTIATION",
        .contract_negotiation = "CONTRACT_NEGOTIATION",
        .onboarding = "ONBOARDING",
        .building_integration = "BUILDING_INTEGRATION",
        .qualified = "QUALIFIED",
        .on_hold = "ON_HOLD",
        .technical_validation = "TECHNICAL_VALIDATION",
        .business_validation = "BUSINESS_VALIDATION",
        .committed = "COMMITTED",
        .launched = "LAUNCHED",
        .deferred_to_partner = "DEFERRED_TO_PARTNER",
        .closed_lost = "CLOSED_LOST",
        .completed = "COMPLETED",
        .closed_incomplete = "CLOSED_INCOMPLETE",
    };
};
