const std = @import("std");

pub const AwsClosedLostReason = enum {
    administrative,
    business_associate_agreement,
    company_acquired_dissolved,
    competitive_offering,
    customer_data_requirement,
    customer_deficiency,
    customer_experience,
    delay_cancellation_of_project,
    duplicate,
    duplicate_opportunity,
    executive_blocker,
    failed_vetting,
    feature_limitation,
    financial_commercial,
    insufficient_amazon_value,
    insufficient_aws_value,
    international_constraints,
    legal_tax_regulatory,
    legal_terms_and_conditions,
    lost_to_competitor,
    lost_to_competitor_google,
    lost_to_competitor_microsoft,
    lost_to_competitor_other,
    lost_to_competitor_rackspace,
    lost_to_competitor_softlayer,
    lost_to_competitor_vmware,
    no_customer_reference,
    no_integration_resources,
    no_opportunity,
    no_perceived_value_of_mp,
    no_response,
    not_committed_to_aws,
    no_update,
    on_premises_deployment,
    other,
    other_details_in_description,
    partner_gap,
    past_due,
    people_relationship_governance,
    platform_technology_limitation,
    preference_for_competitor,
    price,
    product_technology,
    product_not_on_aws,
    security_compliance,
    self_service,
    technical_limitations,
    term_sheet_impasse,

    pub const json_field_names = .{
        .administrative = "Administrative",
        .business_associate_agreement = "Business Associate Agreement",
        .company_acquired_dissolved = "Company Acquired/Dissolved",
        .competitive_offering = "Competitive Offering",
        .customer_data_requirement = "Customer Data Requirement",
        .customer_deficiency = "Customer Deficiency",
        .customer_experience = "Customer Experience",
        .delay_cancellation_of_project = "Delay / Cancellation of Project",
        .duplicate = "Duplicate",
        .duplicate_opportunity = "Duplicate Opportunity",
        .executive_blocker = "Executive Blocker",
        .failed_vetting = "Failed Vetting",
        .feature_limitation = "Feature Limitation",
        .financial_commercial = "Financial/Commercial",
        .insufficient_amazon_value = "Insufficient Amazon Value",
        .insufficient_aws_value = "Insufficient AWS Value",
        .international_constraints = "International Constraints",
        .legal_tax_regulatory = "Legal / Tax / Regulatory",
        .legal_terms_and_conditions = "Legal Terms and Conditions",
        .lost_to_competitor = "Lost to Competitor",
        .lost_to_competitor_google = "Lost to Competitor - Google",
        .lost_to_competitor_microsoft = "Lost to Competitor - Microsoft",
        .lost_to_competitor_other = "Lost to Competitor - Other",
        .lost_to_competitor_rackspace = "Lost to Competitor - Rackspace",
        .lost_to_competitor_softlayer = "Lost to Competitor - SoftLayer",
        .lost_to_competitor_vmware = "Lost to Competitor - VMWare",
        .no_customer_reference = "No Customer Reference",
        .no_integration_resources = "No Integration Resources",
        .no_opportunity = "No Opportunity",
        .no_perceived_value_of_mp = "No Perceived Value of MP",
        .no_response = "No Response",
        .not_committed_to_aws = "Not Committed to AWS",
        .no_update = "No Update",
        .on_premises_deployment = "On Premises Deployment",
        .other = "Other",
        .other_details_in_description = "Other (Details in Description)",
        .partner_gap = "Partner Gap",
        .past_due = "Past Due",
        .people_relationship_governance = "People/Relationship/Governance",
        .platform_technology_limitation = "Platform Technology Limitation",
        .preference_for_competitor = "Preference for Competitor",
        .price = "Price",
        .product_technology = "Product/Technology",
        .product_not_on_aws = "Product Not on AWS",
        .security_compliance = "Security / Compliance",
        .self_service = "Self-Service",
        .technical_limitations = "Technical Limitations",
        .term_sheet_impasse = "Term Sheet Impasse",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .administrative => "Administrative",
            .business_associate_agreement => "Business Associate Agreement",
            .company_acquired_dissolved => "Company Acquired/Dissolved",
            .competitive_offering => "Competitive Offering",
            .customer_data_requirement => "Customer Data Requirement",
            .customer_deficiency => "Customer Deficiency",
            .customer_experience => "Customer Experience",
            .delay_cancellation_of_project => "Delay / Cancellation of Project",
            .duplicate => "Duplicate",
            .duplicate_opportunity => "Duplicate Opportunity",
            .executive_blocker => "Executive Blocker",
            .failed_vetting => "Failed Vetting",
            .feature_limitation => "Feature Limitation",
            .financial_commercial => "Financial/Commercial",
            .insufficient_amazon_value => "Insufficient Amazon Value",
            .insufficient_aws_value => "Insufficient AWS Value",
            .international_constraints => "International Constraints",
            .legal_tax_regulatory => "Legal / Tax / Regulatory",
            .legal_terms_and_conditions => "Legal Terms and Conditions",
            .lost_to_competitor => "Lost to Competitor",
            .lost_to_competitor_google => "Lost to Competitor - Google",
            .lost_to_competitor_microsoft => "Lost to Competitor - Microsoft",
            .lost_to_competitor_other => "Lost to Competitor - Other",
            .lost_to_competitor_rackspace => "Lost to Competitor - Rackspace",
            .lost_to_competitor_softlayer => "Lost to Competitor - SoftLayer",
            .lost_to_competitor_vmware => "Lost to Competitor - VMWare",
            .no_customer_reference => "No Customer Reference",
            .no_integration_resources => "No Integration Resources",
            .no_opportunity => "No Opportunity",
            .no_perceived_value_of_mp => "No Perceived Value of MP",
            .no_response => "No Response",
            .not_committed_to_aws => "Not Committed to AWS",
            .no_update => "No Update",
            .on_premises_deployment => "On Premises Deployment",
            .other => "Other",
            .other_details_in_description => "Other (Details in Description)",
            .partner_gap => "Partner Gap",
            .past_due => "Past Due",
            .people_relationship_governance => "People/Relationship/Governance",
            .platform_technology_limitation => "Platform Technology Limitation",
            .preference_for_competitor => "Preference for Competitor",
            .price => "Price",
            .product_technology => "Product/Technology",
            .product_not_on_aws => "Product Not on AWS",
            .security_compliance => "Security / Compliance",
            .self_service => "Self-Service",
            .technical_limitations => "Technical Limitations",
            .term_sheet_impasse => "Term Sheet Impasse",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
