pub const AwsClosedLostReason = enum {
    administrative,
    business_associate_agreement,
    company_acquired_dissolved,
    competitive_offering,
    customer_data_requirement,
    customer_deficiency,
    customer_experience,
    delay_cancellation_of_project,
    duplicate,
    duplicate_opportunity,
    executive_blocker,
    failed_vetting,
    feature_limitation,
    financial_commercial,
    insufficient_amazon_value,
    insufficient_aws_value,
    international_constraints,
    legal_tax_regulatory,
    legal_terms_and_conditions,
    lost_to_competitor,
    lost_to_competitor_google,
    lost_to_competitor_microsoft,
    lost_to_competitor_other,
    lost_to_competitor_rackspace,
    lost_to_competitor_softlayer,
    lost_to_competitor_vmware,
    no_customer_reference,
    no_integration_resources,
    no_opportunity,
    no_perceived_value_of_mp,
    no_response,
    not_committed_to_aws,
    no_update,
    on_premises_deployment,
    other,
    other_details_in_description,
    partner_gap,
    past_due,
    people_relationship_governance,
    platform_technology_limitation,
    preference_for_competitor,
    price,
    product_technology,
    product_not_on_aws,
    security_compliance,
    self_service,
    technical_limitations,
    term_sheet_impasse,

    pub const json_field_names = .{
        .administrative = "ADMINISTRATIVE",
        .business_associate_agreement = "BUSINESS_ASSOCIATE_AGREEMENT",
        .company_acquired_dissolved = "COMPANY_ACQUIRED_DISSOLVED",
        .competitive_offering = "COMPETITIVE_OFFERING",
        .customer_data_requirement = "CUSTOMER_DATA_REQUIREMENT",
        .customer_deficiency = "CUSTOMER_DEFICIENCY",
        .customer_experience = "CUSTOMER_EXPERIENCE",
        .delay_cancellation_of_project = "DELAY_CANCELLATION_OF_PROJECT",
        .duplicate = "DUPLICATE",
        .duplicate_opportunity = "DUPLICATE_OPPORTUNITY",
        .executive_blocker = "EXECUTIVE_BLOCKER",
        .failed_vetting = "FAILED_VETTING",
        .feature_limitation = "FEATURE_LIMITATION",
        .financial_commercial = "FINANCIAL_COMMERCIAL",
        .insufficient_amazon_value = "INSUFFICIENT_AMAZON_VALUE",
        .insufficient_aws_value = "INSUFFICIENT_AWS_VALUE",
        .international_constraints = "INTERNATIONAL_CONSTRAINTS",
        .legal_tax_regulatory = "LEGAL_TAX_REGULATORY",
        .legal_terms_and_conditions = "LEGAL_TERMS_AND_CONDITIONS",
        .lost_to_competitor = "LOST_TO_COMPETITOR",
        .lost_to_competitor_google = "LOST_TO_COMPETITOR_GOOGLE",
        .lost_to_competitor_microsoft = "LOST_TO_COMPETITOR_MICROSOFT",
        .lost_to_competitor_other = "LOST_TO_COMPETITOR_OTHER",
        .lost_to_competitor_rackspace = "LOST_TO_COMPETITOR_RACKSPACE",
        .lost_to_competitor_softlayer = "LOST_TO_COMPETITOR_SOFTLAYER",
        .lost_to_competitor_vmware = "LOST_TO_COMPETITOR_VMWARE",
        .no_customer_reference = "NO_CUSTOMER_REFERENCE",
        .no_integration_resources = "NO_INTEGRATION_RESOURCES",
        .no_opportunity = "NO_OPPORTUNITY",
        .no_perceived_value_of_mp = "NO_PERCEIVED_VALUE_OF_MP",
        .no_response = "NO_RESPONSE",
        .not_committed_to_aws = "NOT_COMMITTED_TO_AWS",
        .no_update = "NO_UPDATE",
        .on_premises_deployment = "ON_PREMISES_DEPLOYMENT",
        .other = "OTHER",
        .other_details_in_description = "OTHER_DETAILS_IN_DESCRIPTION",
        .partner_gap = "PARTNER_GAP",
        .past_due = "PAST_DUE",
        .people_relationship_governance = "PEOPLE_RELATIONSHIP_GOVERNANCE",
        .platform_technology_limitation = "PLATFORM_TECHNOLOGY_LIMITATION",
        .preference_for_competitor = "PREFERENCE_FOR_COMPETITOR",
        .price = "PRICE",
        .product_technology = "PRODUCT_TECHNOLOGY",
        .product_not_on_aws = "PRODUCT_NOT_ON_AWS",
        .security_compliance = "SECURITY_COMPLIANCE",
        .self_service = "SELF_SERVICE",
        .technical_limitations = "TECHNICAL_LIMITATIONS",
        .term_sheet_impasse = "TERM_SHEET_IMPASSE",
    };
};
