pub const ClosedLostReason = enum {
    customer_deficiency,
    delay_cancellation_of_project,
    legal_tax_regulatory,
    lost_to_competitor_google,
    lost_to_competitor_microsoft,
    lost_to_competitor_softlayer,
    lost_to_competitor_vmware,
    lost_to_competitor_other,
    no_opportunity,
    on_premises_deployment,
    partner_gap,
    price,
    security_compliance,
    technical_limitations,
    customer_experience,
    other,
    peoplerelationshipgovernance,
    producttechnology,
    financialcommercial,

    pub const json_field_names = .{
        .customer_deficiency = "CUSTOMER_DEFICIENCY",
        .delay_cancellation_of_project = "DELAY_CANCELLATION_OF_PROJECT",
        .legal_tax_regulatory = "LEGAL_TAX_REGULATORY",
        .lost_to_competitor_google = "LOST_TO_COMPETITOR_GOOGLE",
        .lost_to_competitor_microsoft = "LOST_TO_COMPETITOR_MICROSOFT",
        .lost_to_competitor_softlayer = "LOST_TO_COMPETITOR_SOFTLAYER",
        .lost_to_competitor_vmware = "LOST_TO_COMPETITOR_VMWARE",
        .lost_to_competitor_other = "LOST_TO_COMPETITOR_OTHER",
        .no_opportunity = "NO_OPPORTUNITY",
        .on_premises_deployment = "ON_PREMISES_DEPLOYMENT",
        .partner_gap = "PARTNER_GAP",
        .price = "PRICE",
        .security_compliance = "SECURITY_COMPLIANCE",
        .technical_limitations = "TECHNICAL_LIMITATIONS",
        .customer_experience = "CUSTOMER_EXPERIENCE",
        .other = "OTHER",
        .peoplerelationshipgovernance = "PEOPLERELATIONSHIPGOVERNANCE",
        .producttechnology = "PRODUCTTECHNOLOGY",
        .financialcommercial = "FINANCIALCOMMERCIAL",
    };
};
