pub const CurrencyCode = enum {
    usd,
    eur,
    gbp,
    aud,
    cad,
    cny,
    nzd,
    inr,
    jpy,
    chf,
    sek,
    aed,
    afn,
    all,
    amd,
    ang,
    aoa,
    ars,
    awg,
    azn,
    bam,
    bbd,
    bdt,
    bgn,
    bhd,
    bif,
    bmd,
    bnd,
    bob,
    bov,
    brl,
    bsd,
    btn,
    bwp,
    byn,
    bzd,
    cdf,
    che,
    chw,
    clf,
    clp,
    cop,
    cou,
    crc,
    cuc,
    cup,
    cve,
    czk,
    djf,
    dkk,
    dop,
    dzd,
    egp,
    ern,
    etb,
    fjd,
    fkp,
    gel,
    ghs,
    gip,
    gmd,
    gnf,
    gtq,
    gyd,
    hkd,
    hnl,
    hrk,
    htg,
    huf,
    idr,
    ils,
    iqd,
    irr,
    isk,
    jmd,
    jod,
    kes,
    kgs,
    khr,
    kmf,
    kpw,
    krw,
    kwd,
    kyd,
    kzt,
    lak,
    lbp,
    lkr,
    lrd,
    lsl,
    lyd,
    mad,
    mdl,
    mga,
    mkd,
    mmk,
    mnt,
    mop,
    mru,
    mur,
    mvr,
    mwk,
    mxn,
    mxv,
    myr,
    mzn,
    nad,
    ngn,
    nio,
    nok,
    npr,
    omr,
    pab,
    pen,
    pgk,
    php,
    pkr,
    pln,
    pyg,
    qar,
    ron,
    rsd,
    rub,
    rwf,
    sar,
    sbd,
    scr,
    sdg,
    sgd,
    shp,
    sll,
    sos,
    srd,
    ssp,
    stn,
    svc,
    syp,
    szl,
    thb,
    tjs,
    tmt,
    tnd,
    top,
    @"try",
    ttd,
    twd,
    tzs,
    uah,
    ugx,
    usn,
    uyi,
    uyu,
    uzs,
    vef,
    vnd,
    vuv,
    wst,
    xaf,
    xcd,
    xdr,
    xof,
    xpf,
    xsu,
    xua,
    yer,
    zar,
    zmw,
    zwl,

    pub const json_field_names = .{
        .usd = "USD",
        .eur = "EUR",
        .gbp = "GBP",
        .aud = "AUD",
        .cad = "CAD",
        .cny = "CNY",
        .nzd = "NZD",
        .inr = "INR",
        .jpy = "JPY",
        .chf = "CHF",
        .sek = "SEK",
        .aed = "AED",
        .afn = "AFN",
        .all = "ALL",
        .amd = "AMD",
        .ang = "ANG",
        .aoa = "AOA",
        .ars = "ARS",
        .awg = "AWG",
        .azn = "AZN",
        .bam = "BAM",
        .bbd = "BBD",
        .bdt = "BDT",
        .bgn = "BGN",
        .bhd = "BHD",
        .bif = "BIF",
        .bmd = "BMD",
        .bnd = "BND",
        .bob = "BOB",
        .bov = "BOV",
        .brl = "BRL",
        .bsd = "BSD",
        .btn = "BTN",
        .bwp = "BWP",
        .byn = "BYN",
        .bzd = "BZD",
        .cdf = "CDF",
        .che = "CHE",
        .chw = "CHW",
        .clf = "CLF",
        .clp = "CLP",
        .cop = "COP",
        .cou = "COU",
        .crc = "CRC",
        .cuc = "CUC",
        .cup = "CUP",
        .cve = "CVE",
        .czk = "CZK",
        .djf = "DJF",
        .dkk = "DKK",
        .dop = "DOP",
        .dzd = "DZD",
        .egp = "EGP",
        .ern = "ERN",
        .etb = "ETB",
        .fjd = "FJD",
        .fkp = "FKP",
        .gel = "GEL",
        .ghs = "GHS",
        .gip = "GIP",
        .gmd = "GMD",
        .gnf = "GNF",
        .gtq = "GTQ",
        .gyd = "GYD",
        .hkd = "HKD",
        .hnl = "HNL",
        .hrk = "HRK",
        .htg = "HTG",
        .huf = "HUF",
        .idr = "IDR",
        .ils = "ILS",
        .iqd = "IQD",
        .irr = "IRR",
        .isk = "ISK",
        .jmd = "JMD",
        .jod = "JOD",
        .kes = "KES",
        .kgs = "KGS",
        .khr = "KHR",
        .kmf = "KMF",
        .kpw = "KPW",
        .krw = "KRW",
        .kwd = "KWD",
        .kyd = "KYD",
        .kzt = "KZT",
        .lak = "LAK",
        .lbp = "LBP",
        .lkr = "LKR",
        .lrd = "LRD",
        .lsl = "LSL",
        .lyd = "LYD",
        .mad = "MAD",
        .mdl = "MDL",
        .mga = "MGA",
        .mkd = "MKD",
        .mmk = "MMK",
        .mnt = "MNT",
        .mop = "MOP",
        .mru = "MRU",
        .mur = "MUR",
        .mvr = "MVR",
        .mwk = "MWK",
        .mxn = "MXN",
        .mxv = "MXV",
        .myr = "MYR",
        .mzn = "MZN",
        .nad = "NAD",
        .ngn = "NGN",
        .nio = "NIO",
        .nok = "NOK",
        .npr = "NPR",
        .omr = "OMR",
        .pab = "PAB",
        .pen = "PEN",
        .pgk = "PGK",
        .php = "PHP",
        .pkr = "PKR",
        .pln = "PLN",
        .pyg = "PYG",
        .qar = "QAR",
        .ron = "RON",
        .rsd = "RSD",
        .rub = "RUB",
        .rwf = "RWF",
        .sar = "SAR",
        .sbd = "SBD",
        .scr = "SCR",
        .sdg = "SDG",
        .sgd = "SGD",
        .shp = "SHP",
        .sll = "SLL",
        .sos = "SOS",
        .srd = "SRD",
        .ssp = "SSP",
        .stn = "STN",
        .svc = "SVC",
        .syp = "SYP",
        .szl = "SZL",
        .thb = "THB",
        .tjs = "TJS",
        .tmt = "TMT",
        .tnd = "TND",
        .top = "TOP",
        .@"try" = "TRY",
        .ttd = "TTD",
        .twd = "TWD",
        .tzs = "TZS",
        .uah = "UAH",
        .ugx = "UGX",
        .usn = "USN",
        .uyi = "UYI",
        .uyu = "UYU",
        .uzs = "UZS",
        .vef = "VEF",
        .vnd = "VND",
        .vuv = "VUV",
        .wst = "WST",
        .xaf = "XAF",
        .xcd = "XCD",
        .xdr = "XDR",
        .xof = "XOF",
        .xpf = "XPF",
        .xsu = "XSU",
        .xua = "XUA",
        .yer = "YER",
        .zar = "ZAR",
        .zmw = "ZMW",
        .zwl = "ZWL",
    };
};
