pub const Industry = enum {
    aerospace_satellite,
    agriculture,
    automotive,
    computers_electronics,
    consumer_goods,
    education,
    energy_oil_gas,
    energy_power_utilities,
    financial_services,
    gaming,
    government,
    healthcare,
    hospitality,
    life_sciences,
    manufacturing,
    marketing_advertising,
    media_entertainment,
    mining,
    non_profit_organization,
    professional_services,
    realestate_construction,
    retail,
    software_internet,
    telecommunications,
    transportation_logistics,
    travel,
    wholesale_distribution,
    other,

    pub const json_field_names = .{
        .aerospace_satellite = "AEROSPACE_SATELLITE",
        .agriculture = "AGRICULTURE",
        .automotive = "AUTOMOTIVE",
        .computers_electronics = "COMPUTERS_ELECTRONICS",
        .consumer_goods = "CONSUMER_GOODS",
        .education = "EDUCATION",
        .energy_oil_gas = "ENERGY_OIL_GAS",
        .energy_power_utilities = "ENERGY_POWER_UTILITIES",
        .financial_services = "FINANCIAL_SERVICES",
        .gaming = "GAMING",
        .government = "GOVERNMENT",
        .healthcare = "HEALTHCARE",
        .hospitality = "HOSPITALITY",
        .life_sciences = "LIFE_SCIENCES",
        .manufacturing = "MANUFACTURING",
        .marketing_advertising = "MARKETING_ADVERTISING",
        .media_entertainment = "MEDIA_ENTERTAINMENT",
        .mining = "MINING",
        .non_profit_organization = "NON_PROFIT_ORGANIZATION",
        .professional_services = "PROFESSIONAL_SERVICES",
        .realestate_construction = "REALESTATE_CONSTRUCTION",
        .retail = "RETAIL",
        .software_internet = "SOFTWARE_INTERNET",
        .telecommunications = "TELECOMMUNICATIONS",
        .transportation_logistics = "TRANSPORTATION_LOGISTICS",
        .travel = "TRAVEL",
        .wholesale_distribution = "WHOLESALE_DISTRIBUTION",
        .other = "OTHER",
    };
};
