pub const ReasonCode = enum {
    invitation_access_denied,
    invitation_validation_failed,
    engagement_access_denied,
    opportunity_access_denied,
    resource_snapshot_job_access_denied,
    resource_snapshot_job_validation_failed,
    resource_snapshot_job_conflict,
    engagement_validation_failed,
    engagement_conflict,
    opportunity_submission_failed,
    engagement_invitation_conflict,
    internal_error,
    opportunity_validation_failed,
    opportunity_conflict,
    resource_snapshot_access_denied,
    resource_snapshot_validation_failed,
    resource_snapshot_conflict,
    service_quota_exceeded,
    request_throttled,
    context_not_found,
    customer_project_context_not_permitted,
    disqualified_lead_not_permitted,

    pub const json_field_names = .{
        .invitation_access_denied = "INVITATION_ACCESS_DENIED",
        .invitation_validation_failed = "INVITATION_VALIDATION_FAILED",
        .engagement_access_denied = "ENGAGEMENT_ACCESS_DENIED",
        .opportunity_access_denied = "OPPORTUNITY_ACCESS_DENIED",
        .resource_snapshot_job_access_denied = "RESOURCE_SNAPSHOT_JOB_ACCESS_DENIED",
        .resource_snapshot_job_validation_failed = "RESOURCE_SNAPSHOT_JOB_VALIDATION_FAILED",
        .resource_snapshot_job_conflict = "RESOURCE_SNAPSHOT_JOB_CONFLICT",
        .engagement_validation_failed = "ENGAGEMENT_VALIDATION_FAILED",
        .engagement_conflict = "ENGAGEMENT_CONFLICT",
        .opportunity_submission_failed = "OPPORTUNITY_SUBMISSION_FAILED",
        .engagement_invitation_conflict = "ENGAGEMENT_INVITATION_CONFLICT",
        .internal_error = "INTERNAL_ERROR",
        .opportunity_validation_failed = "OPPORTUNITY_VALIDATION_FAILED",
        .opportunity_conflict = "OPPORTUNITY_CONFLICT",
        .resource_snapshot_access_denied = "RESOURCE_SNAPSHOT_ACCESS_DENIED",
        .resource_snapshot_validation_failed = "RESOURCE_SNAPSHOT_VALIDATION_FAILED",
        .resource_snapshot_conflict = "RESOURCE_SNAPSHOT_CONFLICT",
        .service_quota_exceeded = "SERVICE_QUOTA_EXCEEDED",
        .request_throttled = "REQUEST_THROTTLED",
        .context_not_found = "CONTEXT_NOT_FOUND",
        .customer_project_context_not_permitted = "CUSTOMER_PROJECT_CONTEXT_NOT_PERMITTED",
        .disqualified_lead_not_permitted = "DISQUALIFIED_LEAD_NOT_PERMITTED",
    };
};
