const std = @import("std");

pub const Metric = enum {
    reservation_total_capacity_hrs_vcpu,
    reservation_total_capacity_hrs_inst,
    reservation_max_size_vcpu,
    reservation_max_size_inst,
    reservation_min_size_vcpu,
    reservation_min_size_inst,
    reservation_unused_total_capacity_hrs_vcpu,
    reservation_unused_total_capacity_hrs_inst,
    reservation_unused_total_estimated_cost,
    reservation_max_unused_size_vcpu,
    reservation_max_unused_size_inst,
    reservation_min_unused_size_vcpu,
    reservation_min_unused_size_inst,
    reservation_max_utilization,
    reservation_min_utilization,
    reservation_avg_utilization_vcpu,
    reservation_avg_utilization_inst,
    reservation_total_count,
    reservation_total_estimated_cost,
    reservation_avg_future_size_vcpu,
    reservation_avg_future_size_inst,
    reservation_min_future_size_vcpu,
    reservation_min_future_size_inst,
    reservation_max_future_size_vcpu,
    reservation_max_future_size_inst,
    reservation_avg_committed_size_vcpu,
    reservation_avg_committed_size_inst,
    reservation_max_committed_size_vcpu,
    reservation_max_committed_size_inst,
    reservation_min_committed_size_vcpu,
    reservation_min_committed_size_inst,
    reserved_total_usage_hrs_vcpu,
    reserved_total_usage_hrs_inst,
    reserved_total_estimated_cost,
    unreserved_total_usage_hrs_vcpu,
    unreserved_total_usage_hrs_inst,
    unreserved_total_estimated_cost,
    spot_total_usage_hrs_vcpu,
    spot_total_usage_hrs_inst,
    spot_total_estimated_cost,
    spot_avg_run_time_before_interruption_inst,
    spot_max_run_time_before_interruption_inst,
    spot_min_run_time_before_interruption_inst,
    spot_total_interruptions_inst,
    spot_total_interruptions_vcpu,
    spot_total_count_inst,
    spot_total_count_vcpu,
    spot_interruption_rate_inst,
    spot_interruption_rate_vcpu,

    pub const json_field_names = .{
        .reservation_total_capacity_hrs_vcpu = "reservation-total-capacity-hrs-vcpu",
        .reservation_total_capacity_hrs_inst = "reservation-total-capacity-hrs-inst",
        .reservation_max_size_vcpu = "reservation-max-size-vcpu",
        .reservation_max_size_inst = "reservation-max-size-inst",
        .reservation_min_size_vcpu = "reservation-min-size-vcpu",
        .reservation_min_size_inst = "reservation-min-size-inst",
        .reservation_unused_total_capacity_hrs_vcpu = "reservation-unused-total-capacity-hrs-vcpu",
        .reservation_unused_total_capacity_hrs_inst = "reservation-unused-total-capacity-hrs-inst",
        .reservation_unused_total_estimated_cost = "reservation-unused-total-estimated-cost",
        .reservation_max_unused_size_vcpu = "reservation-max-unused-size-vcpu",
        .reservation_max_unused_size_inst = "reservation-max-unused-size-inst",
        .reservation_min_unused_size_vcpu = "reservation-min-unused-size-vcpu",
        .reservation_min_unused_size_inst = "reservation-min-unused-size-inst",
        .reservation_max_utilization = "reservation-max-utilization",
        .reservation_min_utilization = "reservation-min-utilization",
        .reservation_avg_utilization_vcpu = "reservation-avg-utilization-vcpu",
        .reservation_avg_utilization_inst = "reservation-avg-utilization-inst",
        .reservation_total_count = "reservation-total-count",
        .reservation_total_estimated_cost = "reservation-total-estimated-cost",
        .reservation_avg_future_size_vcpu = "reservation-avg-future-size-vcpu",
        .reservation_avg_future_size_inst = "reservation-avg-future-size-inst",
        .reservation_min_future_size_vcpu = "reservation-min-future-size-vcpu",
        .reservation_min_future_size_inst = "reservation-min-future-size-inst",
        .reservation_max_future_size_vcpu = "reservation-max-future-size-vcpu",
        .reservation_max_future_size_inst = "reservation-max-future-size-inst",
        .reservation_avg_committed_size_vcpu = "reservation-avg-committed-size-vcpu",
        .reservation_avg_committed_size_inst = "reservation-avg-committed-size-inst",
        .reservation_max_committed_size_vcpu = "reservation-max-committed-size-vcpu",
        .reservation_max_committed_size_inst = "reservation-max-committed-size-inst",
        .reservation_min_committed_size_vcpu = "reservation-min-committed-size-vcpu",
        .reservation_min_committed_size_inst = "reservation-min-committed-size-inst",
        .reserved_total_usage_hrs_vcpu = "reserved-total-usage-hrs-vcpu",
        .reserved_total_usage_hrs_inst = "reserved-total-usage-hrs-inst",
        .reserved_total_estimated_cost = "reserved-total-estimated-cost",
        .unreserved_total_usage_hrs_vcpu = "unreserved-total-usage-hrs-vcpu",
        .unreserved_total_usage_hrs_inst = "unreserved-total-usage-hrs-inst",
        .unreserved_total_estimated_cost = "unreserved-total-estimated-cost",
        .spot_total_usage_hrs_vcpu = "spot-total-usage-hrs-vcpu",
        .spot_total_usage_hrs_inst = "spot-total-usage-hrs-inst",
        .spot_total_estimated_cost = "spot-total-estimated-cost",
        .spot_avg_run_time_before_interruption_inst = "spot-avg-run-time-before-interruption-inst",
        .spot_max_run_time_before_interruption_inst = "spot-max-run-time-before-interruption-inst",
        .spot_min_run_time_before_interruption_inst = "spot-min-run-time-before-interruption-inst",
        .spot_total_interruptions_inst = "spot-total-interruptions-inst",
        .spot_total_interruptions_vcpu = "spot-total-interruptions-vcpu",
        .spot_total_count_inst = "spot-total-count-inst",
        .spot_total_count_vcpu = "spot-total-count-vcpu",
        .spot_interruption_rate_inst = "spot-interruption-rate-inst",
        .spot_interruption_rate_vcpu = "spot-interruption-rate-vcpu",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .reservation_total_capacity_hrs_vcpu => "reservation-total-capacity-hrs-vcpu",
            .reservation_total_capacity_hrs_inst => "reservation-total-capacity-hrs-inst",
            .reservation_max_size_vcpu => "reservation-max-size-vcpu",
            .reservation_max_size_inst => "reservation-max-size-inst",
            .reservation_min_size_vcpu => "reservation-min-size-vcpu",
            .reservation_min_size_inst => "reservation-min-size-inst",
            .reservation_unused_total_capacity_hrs_vcpu => "reservation-unused-total-capacity-hrs-vcpu",
            .reservation_unused_total_capacity_hrs_inst => "reservation-unused-total-capacity-hrs-inst",
            .reservation_unused_total_estimated_cost => "reservation-unused-total-estimated-cost",
            .reservation_max_unused_size_vcpu => "reservation-max-unused-size-vcpu",
            .reservation_max_unused_size_inst => "reservation-max-unused-size-inst",
            .reservation_min_unused_size_vcpu => "reservation-min-unused-size-vcpu",
            .reservation_min_unused_size_inst => "reservation-min-unused-size-inst",
            .reservation_max_utilization => "reservation-max-utilization",
            .reservation_min_utilization => "reservation-min-utilization",
            .reservation_avg_utilization_vcpu => "reservation-avg-utilization-vcpu",
            .reservation_avg_utilization_inst => "reservation-avg-utilization-inst",
            .reservation_total_count => "reservation-total-count",
            .reservation_total_estimated_cost => "reservation-total-estimated-cost",
            .reservation_avg_future_size_vcpu => "reservation-avg-future-size-vcpu",
            .reservation_avg_future_size_inst => "reservation-avg-future-size-inst",
            .reservation_min_future_size_vcpu => "reservation-min-future-size-vcpu",
            .reservation_min_future_size_inst => "reservation-min-future-size-inst",
            .reservation_max_future_size_vcpu => "reservation-max-future-size-vcpu",
            .reservation_max_future_size_inst => "reservation-max-future-size-inst",
            .reservation_avg_committed_size_vcpu => "reservation-avg-committed-size-vcpu",
            .reservation_avg_committed_size_inst => "reservation-avg-committed-size-inst",
            .reservation_max_committed_size_vcpu => "reservation-max-committed-size-vcpu",
            .reservation_max_committed_size_inst => "reservation-max-committed-size-inst",
            .reservation_min_committed_size_vcpu => "reservation-min-committed-size-vcpu",
            .reservation_min_committed_size_inst => "reservation-min-committed-size-inst",
            .reserved_total_usage_hrs_vcpu => "reserved-total-usage-hrs-vcpu",
            .reserved_total_usage_hrs_inst => "reserved-total-usage-hrs-inst",
            .reserved_total_estimated_cost => "reserved-total-estimated-cost",
            .unreserved_total_usage_hrs_vcpu => "unreserved-total-usage-hrs-vcpu",
            .unreserved_total_usage_hrs_inst => "unreserved-total-usage-hrs-inst",
            .unreserved_total_estimated_cost => "unreserved-total-estimated-cost",
            .spot_total_usage_hrs_vcpu => "spot-total-usage-hrs-vcpu",
            .spot_total_usage_hrs_inst => "spot-total-usage-hrs-inst",
            .spot_total_estimated_cost => "spot-total-estimated-cost",
            .spot_avg_run_time_before_interruption_inst => "spot-avg-run-time-before-interruption-inst",
            .spot_max_run_time_before_interruption_inst => "spot-max-run-time-before-interruption-inst",
            .spot_min_run_time_before_interruption_inst => "spot-min-run-time-before-interruption-inst",
            .spot_total_interruptions_inst => "spot-total-interruptions-inst",
            .spot_total_interruptions_vcpu => "spot-total-interruptions-vcpu",
            .spot_total_count_inst => "spot-total-count-inst",
            .spot_total_count_vcpu => "spot-total-count-vcpu",
            .spot_interruption_rate_inst => "spot-interruption-rate-inst",
            .spot_interruption_rate_vcpu => "spot-interruption-rate-vcpu",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
