const std = @import("std");

pub const ResourceType = enum {
    capacity_reservation,
    client_vpn_endpoint,
    customer_gateway,
    carrier_gateway,
    coip_pool,
    declarative_policies_report,
    dedicated_host,
    dhcp_options,
    egress_only_internet_gateway,
    elastic_ip,
    elastic_gpu,
    export_image_task,
    export_instance_task,
    fleet,
    fpga_image,
    host_reservation,
    image,
    image_usage_report,
    import_image_task,
    import_snapshot_task,
    instance,
    instance_event_window,
    internet_gateway,
    ipam,
    ipam_pool,
    ipam_scope,
    ipv_4_pool_ec_2,
    ipv_6_pool_ec_2,
    key_pair,
    launch_template,
    local_gateway,
    local_gateway_route_table,
    local_gateway_virtual_interface,
    local_gateway_virtual_interface_group,
    local_gateway_route_table_vpc_association,
    local_gateway_route_table_virtual_interface_group_association,
    natgateway,
    network_acl,
    network_interface,
    network_insights_analysis,
    network_insights_path,
    network_insights_access_scope,
    network_insights_access_scope_analysis,
    outpost_lag,
    placement_group,
    prefix_list,
    replace_root_volume_task,
    reserved_instances,
    route_table,
    security_group,
    security_group_rule,
    service_link_virtual_interface,
    snapshot,
    spot_fleet_request,
    spot_instances_request,
    subnet,
    subnet_cidr_reservation,
    traffic_mirror_filter,
    traffic_mirror_session,
    traffic_mirror_target,
    transit_gateway,
    transit_gateway_attachment,
    transit_gateway_connect_peer,
    transit_gateway_multicast_domain,
    transit_gateway_policy_table,
    transit_gateway_metering_policy,
    transit_gateway_route_table,
    transit_gateway_route_table_announcement,
    volume,
    vpc,
    vpc_endpoint,
    vpc_endpoint_connection,
    vpc_endpoint_service,
    vpc_endpoint_service_permission,
    vpc_peering_connection,
    vpn_connection,
    vpn_gateway,
    vpc_flow_log,
    capacity_reservation_fleet,
    traffic_mirror_filter_rule,
    vpc_endpoint_connection_device_type,
    verified_access_instance,
    verified_access_group,
    verified_access_endpoint,
    verified_access_policy,
    verified_access_trust_provider,
    vpn_connection_device_type,
    vpc_block_public_access_exclusion,
    vpc_encryption_control,
    route_server,
    route_server_endpoint,
    route_server_peer,
    ipam_resource_discovery,
    ipam_resource_discovery_association,
    instance_connect_endpoint,
    verified_access_endpoint_target,
    ipam_external_resource_verification_token,
    capacity_block,
    mac_modification_task,
    ipam_prefix_list_resolver,
    ipam_policy,
    ipam_prefix_list_resolver_target,
    capacity_manager_data_export,
    vpn_concentrator,

    pub const json_field_names = .{
        .capacity_reservation = "capacity-reservation",
        .client_vpn_endpoint = "client-vpn-endpoint",
        .customer_gateway = "customer-gateway",
        .carrier_gateway = "carrier-gateway",
        .coip_pool = "coip-pool",
        .declarative_policies_report = "declarative-policies-report",
        .dedicated_host = "dedicated-host",
        .dhcp_options = "dhcp-options",
        .egress_only_internet_gateway = "egress-only-internet-gateway",
        .elastic_ip = "elastic-ip",
        .elastic_gpu = "elastic-gpu",
        .export_image_task = "export-image-task",
        .export_instance_task = "export-instance-task",
        .fleet = "fleet",
        .fpga_image = "fpga-image",
        .host_reservation = "host-reservation",
        .image = "image",
        .image_usage_report = "image-usage-report",
        .import_image_task = "import-image-task",
        .import_snapshot_task = "import-snapshot-task",
        .instance = "instance",
        .instance_event_window = "instance-event-window",
        .internet_gateway = "internet-gateway",
        .ipam = "ipam",
        .ipam_pool = "ipam-pool",
        .ipam_scope = "ipam-scope",
        .ipv_4_pool_ec_2 = "ipv4pool-ec2",
        .ipv_6_pool_ec_2 = "ipv6pool-ec2",
        .key_pair = "key-pair",
        .launch_template = "launch-template",
        .local_gateway = "local-gateway",
        .local_gateway_route_table = "local-gateway-route-table",
        .local_gateway_virtual_interface = "local-gateway-virtual-interface",
        .local_gateway_virtual_interface_group = "local-gateway-virtual-interface-group",
        .local_gateway_route_table_vpc_association = "local-gateway-route-table-vpc-association",
        .local_gateway_route_table_virtual_interface_group_association = "local-gateway-route-table-virtual-interface-group-association",
        .natgateway = "natgateway",
        .network_acl = "network-acl",
        .network_interface = "network-interface",
        .network_insights_analysis = "network-insights-analysis",
        .network_insights_path = "network-insights-path",
        .network_insights_access_scope = "network-insights-access-scope",
        .network_insights_access_scope_analysis = "network-insights-access-scope-analysis",
        .outpost_lag = "outpost-lag",
        .placement_group = "placement-group",
        .prefix_list = "prefix-list",
        .replace_root_volume_task = "replace-root-volume-task",
        .reserved_instances = "reserved-instances",
        .route_table = "route-table",
        .security_group = "security-group",
        .security_group_rule = "security-group-rule",
        .service_link_virtual_interface = "service-link-virtual-interface",
        .snapshot = "snapshot",
        .spot_fleet_request = "spot-fleet-request",
        .spot_instances_request = "spot-instances-request",
        .subnet = "subnet",
        .subnet_cidr_reservation = "subnet-cidr-reservation",
        .traffic_mirror_filter = "traffic-mirror-filter",
        .traffic_mirror_session = "traffic-mirror-session",
        .traffic_mirror_target = "traffic-mirror-target",
        .transit_gateway = "transit-gateway",
        .transit_gateway_attachment = "transit-gateway-attachment",
        .transit_gateway_connect_peer = "transit-gateway-connect-peer",
        .transit_gateway_multicast_domain = "transit-gateway-multicast-domain",
        .transit_gateway_policy_table = "transit-gateway-policy-table",
        .transit_gateway_metering_policy = "transit-gateway-metering-policy",
        .transit_gateway_route_table = "transit-gateway-route-table",
        .transit_gateway_route_table_announcement = "transit-gateway-route-table-announcement",
        .volume = "volume",
        .vpc = "vpc",
        .vpc_endpoint = "vpc-endpoint",
        .vpc_endpoint_connection = "vpc-endpoint-connection",
        .vpc_endpoint_service = "vpc-endpoint-service",
        .vpc_endpoint_service_permission = "vpc-endpoint-service-permission",
        .vpc_peering_connection = "vpc-peering-connection",
        .vpn_connection = "vpn-connection",
        .vpn_gateway = "vpn-gateway",
        .vpc_flow_log = "vpc-flow-log",
        .capacity_reservation_fleet = "capacity-reservation-fleet",
        .traffic_mirror_filter_rule = "traffic-mirror-filter-rule",
        .vpc_endpoint_connection_device_type = "vpc-endpoint-connection-device-type",
        .verified_access_instance = "verified-access-instance",
        .verified_access_group = "verified-access-group",
        .verified_access_endpoint = "verified-access-endpoint",
        .verified_access_policy = "verified-access-policy",
        .verified_access_trust_provider = "verified-access-trust-provider",
        .vpn_connection_device_type = "vpn-connection-device-type",
        .vpc_block_public_access_exclusion = "vpc-block-public-access-exclusion",
        .vpc_encryption_control = "vpc-encryption-control",
        .route_server = "route-server",
        .route_server_endpoint = "route-server-endpoint",
        .route_server_peer = "route-server-peer",
        .ipam_resource_discovery = "ipam-resource-discovery",
        .ipam_resource_discovery_association = "ipam-resource-discovery-association",
        .instance_connect_endpoint = "instance-connect-endpoint",
        .verified_access_endpoint_target = "verified-access-endpoint-target",
        .ipam_external_resource_verification_token = "ipam-external-resource-verification-token",
        .capacity_block = "capacity-block",
        .mac_modification_task = "mac-modification-task",
        .ipam_prefix_list_resolver = "ipam-prefix-list-resolver",
        .ipam_policy = "ipam-policy",
        .ipam_prefix_list_resolver_target = "ipam-prefix-list-resolver-target",
        .capacity_manager_data_export = "capacity-manager-data-export",
        .vpn_concentrator = "vpn-concentrator",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .capacity_reservation => "capacity-reservation",
            .client_vpn_endpoint => "client-vpn-endpoint",
            .customer_gateway => "customer-gateway",
            .carrier_gateway => "carrier-gateway",
            .coip_pool => "coip-pool",
            .declarative_policies_report => "declarative-policies-report",
            .dedicated_host => "dedicated-host",
            .dhcp_options => "dhcp-options",
            .egress_only_internet_gateway => "egress-only-internet-gateway",
            .elastic_ip => "elastic-ip",
            .elastic_gpu => "elastic-gpu",
            .export_image_task => "export-image-task",
            .export_instance_task => "export-instance-task",
            .fleet => "fleet",
            .fpga_image => "fpga-image",
            .host_reservation => "host-reservation",
            .image => "image",
            .image_usage_report => "image-usage-report",
            .import_image_task => "import-image-task",
            .import_snapshot_task => "import-snapshot-task",
            .instance => "instance",
            .instance_event_window => "instance-event-window",
            .internet_gateway => "internet-gateway",
            .ipam => "ipam",
            .ipam_pool => "ipam-pool",
            .ipam_scope => "ipam-scope",
            .ipv_4_pool_ec_2 => "ipv4pool-ec2",
            .ipv_6_pool_ec_2 => "ipv6pool-ec2",
            .key_pair => "key-pair",
            .launch_template => "launch-template",
            .local_gateway => "local-gateway",
            .local_gateway_route_table => "local-gateway-route-table",
            .local_gateway_virtual_interface => "local-gateway-virtual-interface",
            .local_gateway_virtual_interface_group => "local-gateway-virtual-interface-group",
            .local_gateway_route_table_vpc_association => "local-gateway-route-table-vpc-association",
            .local_gateway_route_table_virtual_interface_group_association => "local-gateway-route-table-virtual-interface-group-association",
            .natgateway => "natgateway",
            .network_acl => "network-acl",
            .network_interface => "network-interface",
            .network_insights_analysis => "network-insights-analysis",
            .network_insights_path => "network-insights-path",
            .network_insights_access_scope => "network-insights-access-scope",
            .network_insights_access_scope_analysis => "network-insights-access-scope-analysis",
            .outpost_lag => "outpost-lag",
            .placement_group => "placement-group",
            .prefix_list => "prefix-list",
            .replace_root_volume_task => "replace-root-volume-task",
            .reserved_instances => "reserved-instances",
            .route_table => "route-table",
            .security_group => "security-group",
            .security_group_rule => "security-group-rule",
            .service_link_virtual_interface => "service-link-virtual-interface",
            .snapshot => "snapshot",
            .spot_fleet_request => "spot-fleet-request",
            .spot_instances_request => "spot-instances-request",
            .subnet => "subnet",
            .subnet_cidr_reservation => "subnet-cidr-reservation",
            .traffic_mirror_filter => "traffic-mirror-filter",
            .traffic_mirror_session => "traffic-mirror-session",
            .traffic_mirror_target => "traffic-mirror-target",
            .transit_gateway => "transit-gateway",
            .transit_gateway_attachment => "transit-gateway-attachment",
            .transit_gateway_connect_peer => "transit-gateway-connect-peer",
            .transit_gateway_multicast_domain => "transit-gateway-multicast-domain",
            .transit_gateway_policy_table => "transit-gateway-policy-table",
            .transit_gateway_metering_policy => "transit-gateway-metering-policy",
            .transit_gateway_route_table => "transit-gateway-route-table",
            .transit_gateway_route_table_announcement => "transit-gateway-route-table-announcement",
            .volume => "volume",
            .vpc => "vpc",
            .vpc_endpoint => "vpc-endpoint",
            .vpc_endpoint_connection => "vpc-endpoint-connection",
            .vpc_endpoint_service => "vpc-endpoint-service",
            .vpc_endpoint_service_permission => "vpc-endpoint-service-permission",
            .vpc_peering_connection => "vpc-peering-connection",
            .vpn_connection => "vpn-connection",
            .vpn_gateway => "vpn-gateway",
            .vpc_flow_log => "vpc-flow-log",
            .capacity_reservation_fleet => "capacity-reservation-fleet",
            .traffic_mirror_filter_rule => "traffic-mirror-filter-rule",
            .vpc_endpoint_connection_device_type => "vpc-endpoint-connection-device-type",
            .verified_access_instance => "verified-access-instance",
            .verified_access_group => "verified-access-group",
            .verified_access_endpoint => "verified-access-endpoint",
            .verified_access_policy => "verified-access-policy",
            .verified_access_trust_provider => "verified-access-trust-provider",
            .vpn_connection_device_type => "vpn-connection-device-type",
            .vpc_block_public_access_exclusion => "vpc-block-public-access-exclusion",
            .vpc_encryption_control => "vpc-encryption-control",
            .route_server => "route-server",
            .route_server_endpoint => "route-server-endpoint",
            .route_server_peer => "route-server-peer",
            .ipam_resource_discovery => "ipam-resource-discovery",
            .ipam_resource_discovery_association => "ipam-resource-discovery-association",
            .instance_connect_endpoint => "instance-connect-endpoint",
            .verified_access_endpoint_target => "verified-access-endpoint-target",
            .ipam_external_resource_verification_token => "ipam-external-resource-verification-token",
            .capacity_block => "capacity-block",
            .mac_modification_task => "mac-modification-task",
            .ipam_prefix_list_resolver => "ipam-prefix-list-resolver",
            .ipam_policy => "ipam-policy",
            .ipam_prefix_list_resolver_target => "ipam-prefix-list-resolver-target",
            .capacity_manager_data_export => "capacity-manager-data-export",
            .vpn_concentrator => "vpn-concentrator",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
