const std = @import("std");

pub const EC2InstanceType = enum {
    t_2_micro,
    t_2_small,
    t_2_medium,
    t_2_large,
    c_3_large,
    c_3_xlarge,
    c_3_2_xlarge,
    c_3_4_xlarge,
    c_3_8_xlarge,
    c_4_large,
    c_4_xlarge,
    c_4_2_xlarge,
    c_4_4_xlarge,
    c_4_8_xlarge,
    c_5_large,
    c_5_xlarge,
    c_5_2_xlarge,
    c_5_4_xlarge,
    c_5_9_xlarge,
    c_5_12_xlarge,
    c_5_18_xlarge,
    c_5_24_xlarge,
    c_5_a_large,
    c_5_a_xlarge,
    c_5_a_2_xlarge,
    c_5_a_4_xlarge,
    c_5_a_8_xlarge,
    c_5_a_12_xlarge,
    c_5_a_16_xlarge,
    c_5_a_24_xlarge,
    r_3_large,
    r_3_xlarge,
    r_3_2_xlarge,
    r_3_4_xlarge,
    r_3_8_xlarge,
    r_4_large,
    r_4_xlarge,
    r_4_2_xlarge,
    r_4_4_xlarge,
    r_4_8_xlarge,
    r_4_16_xlarge,
    r_5_large,
    r_5_xlarge,
    r_5_2_xlarge,
    r_5_4_xlarge,
    r_5_8_xlarge,
    r_5_12_xlarge,
    r_5_16_xlarge,
    r_5_24_xlarge,
    r_5_a_large,
    r_5_a_xlarge,
    r_5_a_2_xlarge,
    r_5_a_4_xlarge,
    r_5_a_8_xlarge,
    r_5_a_12_xlarge,
    r_5_a_16_xlarge,
    r_5_a_24_xlarge,
    m_3_medium,
    m_3_large,
    m_3_xlarge,
    m_3_2_xlarge,
    m_4_large,
    m_4_xlarge,
    m_4_2_xlarge,
    m_4_4_xlarge,
    m_4_10_xlarge,
    m_5_large,
    m_5_xlarge,
    m_5_2_xlarge,
    m_5_4_xlarge,
    m_5_8_xlarge,
    m_5_12_xlarge,
    m_5_16_xlarge,
    m_5_24_xlarge,
    m_5_a_large,
    m_5_a_xlarge,
    m_5_a_2_xlarge,
    m_5_a_4_xlarge,
    m_5_a_8_xlarge,
    m_5_a_12_xlarge,
    m_5_a_16_xlarge,
    m_5_a_24_xlarge,
    c_5_d_large,
    c_5_d_xlarge,
    c_5_d_2_xlarge,
    c_5_d_4_xlarge,
    c_5_d_9_xlarge,
    c_5_d_12_xlarge,
    c_5_d_18_xlarge,
    c_5_d_24_xlarge,
    c_6_a_large,
    c_6_a_xlarge,
    c_6_a_2_xlarge,
    c_6_a_4_xlarge,
    c_6_a_8_xlarge,
    c_6_a_12_xlarge,
    c_6_a_16_xlarge,
    c_6_a_24_xlarge,
    c_6_i_large,
    c_6_i_xlarge,
    c_6_i_2_xlarge,
    c_6_i_4_xlarge,
    c_6_i_8_xlarge,
    c_6_i_12_xlarge,
    c_6_i_16_xlarge,
    c_6_i_24_xlarge,
    r_5_d_large,
    r_5_d_xlarge,
    r_5_d_2_xlarge,
    r_5_d_4_xlarge,
    r_5_d_8_xlarge,
    r_5_d_12_xlarge,
    r_5_d_16_xlarge,
    r_5_d_24_xlarge,
    m_6_g_medium,
    m_6_g_large,
    m_6_g_xlarge,
    m_6_g_2_xlarge,
    m_6_g_4_xlarge,
    m_6_g_8_xlarge,
    m_6_g_12_xlarge,
    m_6_g_16_xlarge,
    c_6_g_medium,
    c_6_g_large,
    c_6_g_xlarge,
    c_6_g_2_xlarge,
    c_6_g_4_xlarge,
    c_6_g_8_xlarge,
    c_6_g_12_xlarge,
    c_6_g_16_xlarge,
    r_6_g_medium,
    r_6_g_large,
    r_6_g_xlarge,
    r_6_g_2_xlarge,
    r_6_g_4_xlarge,
    r_6_g_8_xlarge,
    r_6_g_12_xlarge,
    r_6_g_16_xlarge,
    c_6_gn_medium,
    c_6_gn_large,
    c_6_gn_xlarge,
    c_6_gn_2_xlarge,
    c_6_gn_4_xlarge,
    c_6_gn_8_xlarge,
    c_6_gn_12_xlarge,
    c_6_gn_16_xlarge,
    c_7_g_medium,
    c_7_g_large,
    c_7_g_xlarge,
    c_7_g_2_xlarge,
    c_7_g_4_xlarge,
    c_7_g_8_xlarge,
    c_7_g_12_xlarge,
    c_7_g_16_xlarge,
    r_7_g_medium,
    r_7_g_large,
    r_7_g_xlarge,
    r_7_g_2_xlarge,
    r_7_g_4_xlarge,
    r_7_g_8_xlarge,
    r_7_g_12_xlarge,
    r_7_g_16_xlarge,
    m_7_g_medium,
    m_7_g_large,
    m_7_g_xlarge,
    m_7_g_2_xlarge,
    m_7_g_4_xlarge,
    m_7_g_8_xlarge,
    m_7_g_12_xlarge,
    m_7_g_16_xlarge,
    g_5_g_xlarge,
    g_5_g_2_xlarge,
    g_5_g_4_xlarge,
    g_5_g_8_xlarge,
    g_5_g_16_xlarge,
    r_6_i_large,
    r_6_i_xlarge,
    r_6_i_2_xlarge,
    r_6_i_4_xlarge,
    r_6_i_8_xlarge,
    r_6_i_12_xlarge,
    r_6_i_16_xlarge,
    c_6_gd_medium,
    c_6_gd_large,
    c_6_gd_xlarge,
    c_6_gd_2_xlarge,
    c_6_gd_4_xlarge,
    c_6_gd_8_xlarge,
    c_6_gd_12_xlarge,
    c_6_gd_16_xlarge,
    c_6_in_large,
    c_6_in_xlarge,
    c_6_in_2_xlarge,
    c_6_in_4_xlarge,
    c_6_in_8_xlarge,
    c_6_in_12_xlarge,
    c_6_in_16_xlarge,
    c_7_a_medium,
    c_7_a_large,
    c_7_a_xlarge,
    c_7_a_2_xlarge,
    c_7_a_4_xlarge,
    c_7_a_8_xlarge,
    c_7_a_12_xlarge,
    c_7_a_16_xlarge,
    c_7_gd_medium,
    c_7_gd_large,
    c_7_gd_xlarge,
    c_7_gd_2_xlarge,
    c_7_gd_4_xlarge,
    c_7_gd_8_xlarge,
    c_7_gd_12_xlarge,
    c_7_gd_16_xlarge,
    c_7_gn_medium,
    c_7_gn_large,
    c_7_gn_xlarge,
    c_7_gn_2_xlarge,
    c_7_gn_4_xlarge,
    c_7_gn_8_xlarge,
    c_7_gn_12_xlarge,
    c_7_gn_16_xlarge,
    c_7_i_large,
    c_7_i_xlarge,
    c_7_i_2_xlarge,
    c_7_i_4_xlarge,
    c_7_i_8_xlarge,
    c_7_i_12_xlarge,
    c_7_i_16_xlarge,
    m_6_a_large,
    m_6_a_xlarge,
    m_6_a_2_xlarge,
    m_6_a_4_xlarge,
    m_6_a_8_xlarge,
    m_6_a_12_xlarge,
    m_6_a_16_xlarge,
    m_6_gd_medium,
    m_6_gd_large,
    m_6_gd_xlarge,
    m_6_gd_2_xlarge,
    m_6_gd_4_xlarge,
    m_6_gd_8_xlarge,
    m_6_gd_12_xlarge,
    m_6_gd_16_xlarge,
    m_6_i_large,
    m_6_i_xlarge,
    m_6_i_2_xlarge,
    m_6_i_4_xlarge,
    m_6_i_8_xlarge,
    m_6_i_12_xlarge,
    m_6_i_16_xlarge,
    m_7_a_medium,
    m_7_a_large,
    m_7_a_xlarge,
    m_7_a_2_xlarge,
    m_7_a_4_xlarge,
    m_7_a_8_xlarge,
    m_7_a_12_xlarge,
    m_7_a_16_xlarge,
    m_7_gd_medium,
    m_7_gd_large,
    m_7_gd_xlarge,
    m_7_gd_2_xlarge,
    m_7_gd_4_xlarge,
    m_7_gd_8_xlarge,
    m_7_gd_12_xlarge,
    m_7_gd_16_xlarge,
    m_7_i_large,
    m_7_i_xlarge,
    m_7_i_2_xlarge,
    m_7_i_4_xlarge,
    m_7_i_8_xlarge,
    m_7_i_12_xlarge,
    m_7_i_16_xlarge,
    r_6_gd_medium,
    r_6_gd_large,
    r_6_gd_xlarge,
    r_6_gd_2_xlarge,
    r_6_gd_4_xlarge,
    r_6_gd_8_xlarge,
    r_6_gd_12_xlarge,
    r_6_gd_16_xlarge,
    r_7_a_medium,
    r_7_a_large,
    r_7_a_xlarge,
    r_7_a_2_xlarge,
    r_7_a_4_xlarge,
    r_7_a_8_xlarge,
    r_7_a_12_xlarge,
    r_7_a_16_xlarge,
    r_7_gd_medium,
    r_7_gd_large,
    r_7_gd_xlarge,
    r_7_gd_2_xlarge,
    r_7_gd_4_xlarge,
    r_7_gd_8_xlarge,
    r_7_gd_12_xlarge,
    r_7_gd_16_xlarge,
    r_7_i_large,
    r_7_i_xlarge,
    r_7_i_2_xlarge,
    r_7_i_4_xlarge,
    r_7_i_8_xlarge,
    r_7_i_12_xlarge,
    r_7_i_16_xlarge,
    r_7_i_24_xlarge,
    r_7_i_48_xlarge,
    c_5_ad_large,
    c_5_ad_xlarge,
    c_5_ad_2_xlarge,
    c_5_ad_4_xlarge,
    c_5_ad_8_xlarge,
    c_5_ad_12_xlarge,
    c_5_ad_16_xlarge,
    c_5_ad_24_xlarge,
    c_5_n_large,
    c_5_n_xlarge,
    c_5_n_2_xlarge,
    c_5_n_4_xlarge,
    c_5_n_9_xlarge,
    c_5_n_18_xlarge,
    r_5_ad_large,
    r_5_ad_xlarge,
    r_5_ad_2_xlarge,
    r_5_ad_4_xlarge,
    r_5_ad_8_xlarge,
    r_5_ad_12_xlarge,
    r_5_ad_16_xlarge,
    r_5_ad_24_xlarge,
    c_6_id_large,
    c_6_id_xlarge,
    c_6_id_2_xlarge,
    c_6_id_4_xlarge,
    c_6_id_8_xlarge,
    c_6_id_12_xlarge,
    c_6_id_16_xlarge,
    c_6_id_24_xlarge,
    c_6_id_32_xlarge,
    c_8_g_medium,
    c_8_g_large,
    c_8_g_xlarge,
    c_8_g_2_xlarge,
    c_8_g_4_xlarge,
    c_8_g_8_xlarge,
    c_8_g_12_xlarge,
    c_8_g_16_xlarge,
    c_8_g_24_xlarge,
    c_8_g_48_xlarge,
    m_5_ad_large,
    m_5_ad_xlarge,
    m_5_ad_2_xlarge,
    m_5_ad_4_xlarge,
    m_5_ad_8_xlarge,
    m_5_ad_12_xlarge,
    m_5_ad_16_xlarge,
    m_5_ad_24_xlarge,
    m_5_d_large,
    m_5_d_xlarge,
    m_5_d_2_xlarge,
    m_5_d_4_xlarge,
    m_5_d_8_xlarge,
    m_5_d_12_xlarge,
    m_5_d_16_xlarge,
    m_5_d_24_xlarge,
    m_5_dn_large,
    m_5_dn_xlarge,
    m_5_dn_2_xlarge,
    m_5_dn_4_xlarge,
    m_5_dn_8_xlarge,
    m_5_dn_12_xlarge,
    m_5_dn_16_xlarge,
    m_5_dn_24_xlarge,
    m_5_n_large,
    m_5_n_xlarge,
    m_5_n_2_xlarge,
    m_5_n_4_xlarge,
    m_5_n_8_xlarge,
    m_5_n_12_xlarge,
    m_5_n_16_xlarge,
    m_5_n_24_xlarge,
    m_6_id_large,
    m_6_id_xlarge,
    m_6_id_2_xlarge,
    m_6_id_4_xlarge,
    m_6_id_8_xlarge,
    m_6_id_12_xlarge,
    m_6_id_16_xlarge,
    m_6_id_24_xlarge,
    m_6_id_32_xlarge,
    m_6_idn_large,
    m_6_idn_xlarge,
    m_6_idn_2_xlarge,
    m_6_idn_4_xlarge,
    m_6_idn_8_xlarge,
    m_6_idn_12_xlarge,
    m_6_idn_16_xlarge,
    m_6_idn_24_xlarge,
    m_6_idn_32_xlarge,
    m_6_in_large,
    m_6_in_xlarge,
    m_6_in_2_xlarge,
    m_6_in_4_xlarge,
    m_6_in_8_xlarge,
    m_6_in_12_xlarge,
    m_6_in_16_xlarge,
    m_6_in_24_xlarge,
    m_6_in_32_xlarge,
    m_8_g_medium,
    m_8_g_large,
    m_8_g_xlarge,
    m_8_g_2_xlarge,
    m_8_g_4_xlarge,
    m_8_g_8_xlarge,
    m_8_g_12_xlarge,
    m_8_g_16_xlarge,
    m_8_g_24_xlarge,
    m_8_g_48_xlarge,
    r_5_dn_large,
    r_5_dn_xlarge,
    r_5_dn_2_xlarge,
    r_5_dn_4_xlarge,
    r_5_dn_8_xlarge,
    r_5_dn_12_xlarge,
    r_5_dn_16_xlarge,
    r_5_dn_24_xlarge,
    r_5_n_large,
    r_5_n_xlarge,
    r_5_n_2_xlarge,
    r_5_n_4_xlarge,
    r_5_n_8_xlarge,
    r_5_n_12_xlarge,
    r_5_n_16_xlarge,
    r_5_n_24_xlarge,
    r_6_a_large,
    r_6_a_xlarge,
    r_6_a_2_xlarge,
    r_6_a_4_xlarge,
    r_6_a_8_xlarge,
    r_6_a_12_xlarge,
    r_6_a_16_xlarge,
    r_6_a_24_xlarge,
    r_6_a_32_xlarge,
    r_6_a_48_xlarge,
    r_6_id_large,
    r_6_id_xlarge,
    r_6_id_2_xlarge,
    r_6_id_4_xlarge,
    r_6_id_8_xlarge,
    r_6_id_12_xlarge,
    r_6_id_16_xlarge,
    r_6_id_24_xlarge,
    r_6_id_32_xlarge,
    r_6_idn_large,
    r_6_idn_xlarge,
    r_6_idn_2_xlarge,
    r_6_idn_4_xlarge,
    r_6_idn_8_xlarge,
    r_6_idn_12_xlarge,
    r_6_idn_16_xlarge,
    r_6_idn_24_xlarge,
    r_6_idn_32_xlarge,
    r_6_in_large,
    r_6_in_xlarge,
    r_6_in_2_xlarge,
    r_6_in_4_xlarge,
    r_6_in_8_xlarge,
    r_6_in_12_xlarge,
    r_6_in_16_xlarge,
    r_6_in_24_xlarge,
    r_6_in_32_xlarge,
    r_8_g_medium,
    r_8_g_large,
    r_8_g_xlarge,
    r_8_g_2_xlarge,
    r_8_g_4_xlarge,
    r_8_g_8_xlarge,
    r_8_g_12_xlarge,
    r_8_g_16_xlarge,
    r_8_g_24_xlarge,
    r_8_g_48_xlarge,
    m_4_16_xlarge,
    c_6_a_32_xlarge,
    c_6_a_48_xlarge,
    c_6_i_32_xlarge,
    r_6_i_24_xlarge,
    r_6_i_32_xlarge,
    c_6_in_24_xlarge,
    c_6_in_32_xlarge,
    c_7_a_24_xlarge,
    c_7_a_32_xlarge,
    c_7_a_48_xlarge,
    c_7_i_24_xlarge,
    c_7_i_48_xlarge,
    m_6_a_24_xlarge,
    m_6_a_32_xlarge,
    m_6_a_48_xlarge,
    m_6_i_24_xlarge,
    m_6_i_32_xlarge,
    m_7_a_24_xlarge,
    m_7_a_32_xlarge,
    m_7_a_48_xlarge,
    m_7_i_24_xlarge,
    m_7_i_48_xlarge,
    r_7_a_24_xlarge,
    r_7_a_32_xlarge,
    r_7_a_48_xlarge,

    pub const json_field_names = .{
        .t_2_micro = "t2.micro",
        .t_2_small = "t2.small",
        .t_2_medium = "t2.medium",
        .t_2_large = "t2.large",
        .c_3_large = "c3.large",
        .c_3_xlarge = "c3.xlarge",
        .c_3_2_xlarge = "c3.2xlarge",
        .c_3_4_xlarge = "c3.4xlarge",
        .c_3_8_xlarge = "c3.8xlarge",
        .c_4_large = "c4.large",
        .c_4_xlarge = "c4.xlarge",
        .c_4_2_xlarge = "c4.2xlarge",
        .c_4_4_xlarge = "c4.4xlarge",
        .c_4_8_xlarge = "c4.8xlarge",
        .c_5_large = "c5.large",
        .c_5_xlarge = "c5.xlarge",
        .c_5_2_xlarge = "c5.2xlarge",
        .c_5_4_xlarge = "c5.4xlarge",
        .c_5_9_xlarge = "c5.9xlarge",
        .c_5_12_xlarge = "c5.12xlarge",
        .c_5_18_xlarge = "c5.18xlarge",
        .c_5_24_xlarge = "c5.24xlarge",
        .c_5_a_large = "c5a.large",
        .c_5_a_xlarge = "c5a.xlarge",
        .c_5_a_2_xlarge = "c5a.2xlarge",
        .c_5_a_4_xlarge = "c5a.4xlarge",
        .c_5_a_8_xlarge = "c5a.8xlarge",
        .c_5_a_12_xlarge = "c5a.12xlarge",
        .c_5_a_16_xlarge = "c5a.16xlarge",
        .c_5_a_24_xlarge = "c5a.24xlarge",
        .r_3_large = "r3.large",
        .r_3_xlarge = "r3.xlarge",
        .r_3_2_xlarge = "r3.2xlarge",
        .r_3_4_xlarge = "r3.4xlarge",
        .r_3_8_xlarge = "r3.8xlarge",
        .r_4_large = "r4.large",
        .r_4_xlarge = "r4.xlarge",
        .r_4_2_xlarge = "r4.2xlarge",
        .r_4_4_xlarge = "r4.4xlarge",
        .r_4_8_xlarge = "r4.8xlarge",
        .r_4_16_xlarge = "r4.16xlarge",
        .r_5_large = "r5.large",
        .r_5_xlarge = "r5.xlarge",
        .r_5_2_xlarge = "r5.2xlarge",
        .r_5_4_xlarge = "r5.4xlarge",
        .r_5_8_xlarge = "r5.8xlarge",
        .r_5_12_xlarge = "r5.12xlarge",
        .r_5_16_xlarge = "r5.16xlarge",
        .r_5_24_xlarge = "r5.24xlarge",
        .r_5_a_large = "r5a.large",
        .r_5_a_xlarge = "r5a.xlarge",
        .r_5_a_2_xlarge = "r5a.2xlarge",
        .r_5_a_4_xlarge = "r5a.4xlarge",
        .r_5_a_8_xlarge = "r5a.8xlarge",
        .r_5_a_12_xlarge = "r5a.12xlarge",
        .r_5_a_16_xlarge = "r5a.16xlarge",
        .r_5_a_24_xlarge = "r5a.24xlarge",
        .m_3_medium = "m3.medium",
        .m_3_large = "m3.large",
        .m_3_xlarge = "m3.xlarge",
        .m_3_2_xlarge = "m3.2xlarge",
        .m_4_large = "m4.large",
        .m_4_xlarge = "m4.xlarge",
        .m_4_2_xlarge = "m4.2xlarge",
        .m_4_4_xlarge = "m4.4xlarge",
        .m_4_10_xlarge = "m4.10xlarge",
        .m_5_large = "m5.large",
        .m_5_xlarge = "m5.xlarge",
        .m_5_2_xlarge = "m5.2xlarge",
        .m_5_4_xlarge = "m5.4xlarge",
        .m_5_8_xlarge = "m5.8xlarge",
        .m_5_12_xlarge = "m5.12xlarge",
        .m_5_16_xlarge = "m5.16xlarge",
        .m_5_24_xlarge = "m5.24xlarge",
        .m_5_a_large = "m5a.large",
        .m_5_a_xlarge = "m5a.xlarge",
        .m_5_a_2_xlarge = "m5a.2xlarge",
        .m_5_a_4_xlarge = "m5a.4xlarge",
        .m_5_a_8_xlarge = "m5a.8xlarge",
        .m_5_a_12_xlarge = "m5a.12xlarge",
        .m_5_a_16_xlarge = "m5a.16xlarge",
        .m_5_a_24_xlarge = "m5a.24xlarge",
        .c_5_d_large = "c5d.large",
        .c_5_d_xlarge = "c5d.xlarge",
        .c_5_d_2_xlarge = "c5d.2xlarge",
        .c_5_d_4_xlarge = "c5d.4xlarge",
        .c_5_d_9_xlarge = "c5d.9xlarge",
        .c_5_d_12_xlarge = "c5d.12xlarge",
        .c_5_d_18_xlarge = "c5d.18xlarge",
        .c_5_d_24_xlarge = "c5d.24xlarge",
        .c_6_a_large = "c6a.large",
        .c_6_a_xlarge = "c6a.xlarge",
        .c_6_a_2_xlarge = "c6a.2xlarge",
        .c_6_a_4_xlarge = "c6a.4xlarge",
        .c_6_a_8_xlarge = "c6a.8xlarge",
        .c_6_a_12_xlarge = "c6a.12xlarge",
        .c_6_a_16_xlarge = "c6a.16xlarge",
        .c_6_a_24_xlarge = "c6a.24xlarge",
        .c_6_i_large = "c6i.large",
        .c_6_i_xlarge = "c6i.xlarge",
        .c_6_i_2_xlarge = "c6i.2xlarge",
        .c_6_i_4_xlarge = "c6i.4xlarge",
        .c_6_i_8_xlarge = "c6i.8xlarge",
        .c_6_i_12_xlarge = "c6i.12xlarge",
        .c_6_i_16_xlarge = "c6i.16xlarge",
        .c_6_i_24_xlarge = "c6i.24xlarge",
        .r_5_d_large = "r5d.large",
        .r_5_d_xlarge = "r5d.xlarge",
        .r_5_d_2_xlarge = "r5d.2xlarge",
        .r_5_d_4_xlarge = "r5d.4xlarge",
        .r_5_d_8_xlarge = "r5d.8xlarge",
        .r_5_d_12_xlarge = "r5d.12xlarge",
        .r_5_d_16_xlarge = "r5d.16xlarge",
        .r_5_d_24_xlarge = "r5d.24xlarge",
        .m_6_g_medium = "m6g.medium",
        .m_6_g_large = "m6g.large",
        .m_6_g_xlarge = "m6g.xlarge",
        .m_6_g_2_xlarge = "m6g.2xlarge",
        .m_6_g_4_xlarge = "m6g.4xlarge",
        .m_6_g_8_xlarge = "m6g.8xlarge",
        .m_6_g_12_xlarge = "m6g.12xlarge",
        .m_6_g_16_xlarge = "m6g.16xlarge",
        .c_6_g_medium = "c6g.medium",
        .c_6_g_large = "c6g.large",
        .c_6_g_xlarge = "c6g.xlarge",
        .c_6_g_2_xlarge = "c6g.2xlarge",
        .c_6_g_4_xlarge = "c6g.4xlarge",
        .c_6_g_8_xlarge = "c6g.8xlarge",
        .c_6_g_12_xlarge = "c6g.12xlarge",
        .c_6_g_16_xlarge = "c6g.16xlarge",
        .r_6_g_medium = "r6g.medium",
        .r_6_g_large = "r6g.large",
        .r_6_g_xlarge = "r6g.xlarge",
        .r_6_g_2_xlarge = "r6g.2xlarge",
        .r_6_g_4_xlarge = "r6g.4xlarge",
        .r_6_g_8_xlarge = "r6g.8xlarge",
        .r_6_g_12_xlarge = "r6g.12xlarge",
        .r_6_g_16_xlarge = "r6g.16xlarge",
        .c_6_gn_medium = "c6gn.medium",
        .c_6_gn_large = "c6gn.large",
        .c_6_gn_xlarge = "c6gn.xlarge",
        .c_6_gn_2_xlarge = "c6gn.2xlarge",
        .c_6_gn_4_xlarge = "c6gn.4xlarge",
        .c_6_gn_8_xlarge = "c6gn.8xlarge",
        .c_6_gn_12_xlarge = "c6gn.12xlarge",
        .c_6_gn_16_xlarge = "c6gn.16xlarge",
        .c_7_g_medium = "c7g.medium",
        .c_7_g_large = "c7g.large",
        .c_7_g_xlarge = "c7g.xlarge",
        .c_7_g_2_xlarge = "c7g.2xlarge",
        .c_7_g_4_xlarge = "c7g.4xlarge",
        .c_7_g_8_xlarge = "c7g.8xlarge",
        .c_7_g_12_xlarge = "c7g.12xlarge",
        .c_7_g_16_xlarge = "c7g.16xlarge",
        .r_7_g_medium = "r7g.medium",
        .r_7_g_large = "r7g.large",
        .r_7_g_xlarge = "r7g.xlarge",
        .r_7_g_2_xlarge = "r7g.2xlarge",
        .r_7_g_4_xlarge = "r7g.4xlarge",
        .r_7_g_8_xlarge = "r7g.8xlarge",
        .r_7_g_12_xlarge = "r7g.12xlarge",
        .r_7_g_16_xlarge = "r7g.16xlarge",
        .m_7_g_medium = "m7g.medium",
        .m_7_g_large = "m7g.large",
        .m_7_g_xlarge = "m7g.xlarge",
        .m_7_g_2_xlarge = "m7g.2xlarge",
        .m_7_g_4_xlarge = "m7g.4xlarge",
        .m_7_g_8_xlarge = "m7g.8xlarge",
        .m_7_g_12_xlarge = "m7g.12xlarge",
        .m_7_g_16_xlarge = "m7g.16xlarge",
        .g_5_g_xlarge = "g5g.xlarge",
        .g_5_g_2_xlarge = "g5g.2xlarge",
        .g_5_g_4_xlarge = "g5g.4xlarge",
        .g_5_g_8_xlarge = "g5g.8xlarge",
        .g_5_g_16_xlarge = "g5g.16xlarge",
        .r_6_i_large = "r6i.large",
        .r_6_i_xlarge = "r6i.xlarge",
        .r_6_i_2_xlarge = "r6i.2xlarge",
        .r_6_i_4_xlarge = "r6i.4xlarge",
        .r_6_i_8_xlarge = "r6i.8xlarge",
        .r_6_i_12_xlarge = "r6i.12xlarge",
        .r_6_i_16_xlarge = "r6i.16xlarge",
        .c_6_gd_medium = "c6gd.medium",
        .c_6_gd_large = "c6gd.large",
        .c_6_gd_xlarge = "c6gd.xlarge",
        .c_6_gd_2_xlarge = "c6gd.2xlarge",
        .c_6_gd_4_xlarge = "c6gd.4xlarge",
        .c_6_gd_8_xlarge = "c6gd.8xlarge",
        .c_6_gd_12_xlarge = "c6gd.12xlarge",
        .c_6_gd_16_xlarge = "c6gd.16xlarge",
        .c_6_in_large = "c6in.large",
        .c_6_in_xlarge = "c6in.xlarge",
        .c_6_in_2_xlarge = "c6in.2xlarge",
        .c_6_in_4_xlarge = "c6in.4xlarge",
        .c_6_in_8_xlarge = "c6in.8xlarge",
        .c_6_in_12_xlarge = "c6in.12xlarge",
        .c_6_in_16_xlarge = "c6in.16xlarge",
        .c_7_a_medium = "c7a.medium",
        .c_7_a_large = "c7a.large",
        .c_7_a_xlarge = "c7a.xlarge",
        .c_7_a_2_xlarge = "c7a.2xlarge",
        .c_7_a_4_xlarge = "c7a.4xlarge",
        .c_7_a_8_xlarge = "c7a.8xlarge",
        .c_7_a_12_xlarge = "c7a.12xlarge",
        .c_7_a_16_xlarge = "c7a.16xlarge",
        .c_7_gd_medium = "c7gd.medium",
        .c_7_gd_large = "c7gd.large",
        .c_7_gd_xlarge = "c7gd.xlarge",
        .c_7_gd_2_xlarge = "c7gd.2xlarge",
        .c_7_gd_4_xlarge = "c7gd.4xlarge",
        .c_7_gd_8_xlarge = "c7gd.8xlarge",
        .c_7_gd_12_xlarge = "c7gd.12xlarge",
        .c_7_gd_16_xlarge = "c7gd.16xlarge",
        .c_7_gn_medium = "c7gn.medium",
        .c_7_gn_large = "c7gn.large",
        .c_7_gn_xlarge = "c7gn.xlarge",
        .c_7_gn_2_xlarge = "c7gn.2xlarge",
        .c_7_gn_4_xlarge = "c7gn.4xlarge",
        .c_7_gn_8_xlarge = "c7gn.8xlarge",
        .c_7_gn_12_xlarge = "c7gn.12xlarge",
        .c_7_gn_16_xlarge = "c7gn.16xlarge",
        .c_7_i_large = "c7i.large",
        .c_7_i_xlarge = "c7i.xlarge",
        .c_7_i_2_xlarge = "c7i.2xlarge",
        .c_7_i_4_xlarge = "c7i.4xlarge",
        .c_7_i_8_xlarge = "c7i.8xlarge",
        .c_7_i_12_xlarge = "c7i.12xlarge",
        .c_7_i_16_xlarge = "c7i.16xlarge",
        .m_6_a_large = "m6a.large",
        .m_6_a_xlarge = "m6a.xlarge",
        .m_6_a_2_xlarge = "m6a.2xlarge",
        .m_6_a_4_xlarge = "m6a.4xlarge",
        .m_6_a_8_xlarge = "m6a.8xlarge",
        .m_6_a_12_xlarge = "m6a.12xlarge",
        .m_6_a_16_xlarge = "m6a.16xlarge",
        .m_6_gd_medium = "m6gd.medium",
        .m_6_gd_large = "m6gd.large",
        .m_6_gd_xlarge = "m6gd.xlarge",
        .m_6_gd_2_xlarge = "m6gd.2xlarge",
        .m_6_gd_4_xlarge = "m6gd.4xlarge",
        .m_6_gd_8_xlarge = "m6gd.8xlarge",
        .m_6_gd_12_xlarge = "m6gd.12xlarge",
        .m_6_gd_16_xlarge = "m6gd.16xlarge",
        .m_6_i_large = "m6i.large",
        .m_6_i_xlarge = "m6i.xlarge",
        .m_6_i_2_xlarge = "m6i.2xlarge",
        .m_6_i_4_xlarge = "m6i.4xlarge",
        .m_6_i_8_xlarge = "m6i.8xlarge",
        .m_6_i_12_xlarge = "m6i.12xlarge",
        .m_6_i_16_xlarge = "m6i.16xlarge",
        .m_7_a_medium = "m7a.medium",
        .m_7_a_large = "m7a.large",
        .m_7_a_xlarge = "m7a.xlarge",
        .m_7_a_2_xlarge = "m7a.2xlarge",
        .m_7_a_4_xlarge = "m7a.4xlarge",
        .m_7_a_8_xlarge = "m7a.8xlarge",
        .m_7_a_12_xlarge = "m7a.12xlarge",
        .m_7_a_16_xlarge = "m7a.16xlarge",
        .m_7_gd_medium = "m7gd.medium",
        .m_7_gd_large = "m7gd.large",
        .m_7_gd_xlarge = "m7gd.xlarge",
        .m_7_gd_2_xlarge = "m7gd.2xlarge",
        .m_7_gd_4_xlarge = "m7gd.4xlarge",
        .m_7_gd_8_xlarge = "m7gd.8xlarge",
        .m_7_gd_12_xlarge = "m7gd.12xlarge",
        .m_7_gd_16_xlarge = "m7gd.16xlarge",
        .m_7_i_large = "m7i.large",
        .m_7_i_xlarge = "m7i.xlarge",
        .m_7_i_2_xlarge = "m7i.2xlarge",
        .m_7_i_4_xlarge = "m7i.4xlarge",
        .m_7_i_8_xlarge = "m7i.8xlarge",
        .m_7_i_12_xlarge = "m7i.12xlarge",
        .m_7_i_16_xlarge = "m7i.16xlarge",
        .r_6_gd_medium = "r6gd.medium",
        .r_6_gd_large = "r6gd.large",
        .r_6_gd_xlarge = "r6gd.xlarge",
        .r_6_gd_2_xlarge = "r6gd.2xlarge",
        .r_6_gd_4_xlarge = "r6gd.4xlarge",
        .r_6_gd_8_xlarge = "r6gd.8xlarge",
        .r_6_gd_12_xlarge = "r6gd.12xlarge",
        .r_6_gd_16_xlarge = "r6gd.16xlarge",
        .r_7_a_medium = "r7a.medium",
        .r_7_a_large = "r7a.large",
        .r_7_a_xlarge = "r7a.xlarge",
        .r_7_a_2_xlarge = "r7a.2xlarge",
        .r_7_a_4_xlarge = "r7a.4xlarge",
        .r_7_a_8_xlarge = "r7a.8xlarge",
        .r_7_a_12_xlarge = "r7a.12xlarge",
        .r_7_a_16_xlarge = "r7a.16xlarge",
        .r_7_gd_medium = "r7gd.medium",
        .r_7_gd_large = "r7gd.large",
        .r_7_gd_xlarge = "r7gd.xlarge",
        .r_7_gd_2_xlarge = "r7gd.2xlarge",
        .r_7_gd_4_xlarge = "r7gd.4xlarge",
        .r_7_gd_8_xlarge = "r7gd.8xlarge",
        .r_7_gd_12_xlarge = "r7gd.12xlarge",
        .r_7_gd_16_xlarge = "r7gd.16xlarge",
        .r_7_i_large = "r7i.large",
        .r_7_i_xlarge = "r7i.xlarge",
        .r_7_i_2_xlarge = "r7i.2xlarge",
        .r_7_i_4_xlarge = "r7i.4xlarge",
        .r_7_i_8_xlarge = "r7i.8xlarge",
        .r_7_i_12_xlarge = "r7i.12xlarge",
        .r_7_i_16_xlarge = "r7i.16xlarge",
        .r_7_i_24_xlarge = "r7i.24xlarge",
        .r_7_i_48_xlarge = "r7i.48xlarge",
        .c_5_ad_large = "c5ad.large",
        .c_5_ad_xlarge = "c5ad.xlarge",
        .c_5_ad_2_xlarge = "c5ad.2xlarge",
        .c_5_ad_4_xlarge = "c5ad.4xlarge",
        .c_5_ad_8_xlarge = "c5ad.8xlarge",
        .c_5_ad_12_xlarge = "c5ad.12xlarge",
        .c_5_ad_16_xlarge = "c5ad.16xlarge",
        .c_5_ad_24_xlarge = "c5ad.24xlarge",
        .c_5_n_large = "c5n.large",
        .c_5_n_xlarge = "c5n.xlarge",
        .c_5_n_2_xlarge = "c5n.2xlarge",
        .c_5_n_4_xlarge = "c5n.4xlarge",
        .c_5_n_9_xlarge = "c5n.9xlarge",
        .c_5_n_18_xlarge = "c5n.18xlarge",
        .r_5_ad_large = "r5ad.large",
        .r_5_ad_xlarge = "r5ad.xlarge",
        .r_5_ad_2_xlarge = "r5ad.2xlarge",
        .r_5_ad_4_xlarge = "r5ad.4xlarge",
        .r_5_ad_8_xlarge = "r5ad.8xlarge",
        .r_5_ad_12_xlarge = "r5ad.12xlarge",
        .r_5_ad_16_xlarge = "r5ad.16xlarge",
        .r_5_ad_24_xlarge = "r5ad.24xlarge",
        .c_6_id_large = "c6id.large",
        .c_6_id_xlarge = "c6id.xlarge",
        .c_6_id_2_xlarge = "c6id.2xlarge",
        .c_6_id_4_xlarge = "c6id.4xlarge",
        .c_6_id_8_xlarge = "c6id.8xlarge",
        .c_6_id_12_xlarge = "c6id.12xlarge",
        .c_6_id_16_xlarge = "c6id.16xlarge",
        .c_6_id_24_xlarge = "c6id.24xlarge",
        .c_6_id_32_xlarge = "c6id.32xlarge",
        .c_8_g_medium = "c8g.medium",
        .c_8_g_large = "c8g.large",
        .c_8_g_xlarge = "c8g.xlarge",
        .c_8_g_2_xlarge = "c8g.2xlarge",
        .c_8_g_4_xlarge = "c8g.4xlarge",
        .c_8_g_8_xlarge = "c8g.8xlarge",
        .c_8_g_12_xlarge = "c8g.12xlarge",
        .c_8_g_16_xlarge = "c8g.16xlarge",
        .c_8_g_24_xlarge = "c8g.24xlarge",
        .c_8_g_48_xlarge = "c8g.48xlarge",
        .m_5_ad_large = "m5ad.large",
        .m_5_ad_xlarge = "m5ad.xlarge",
        .m_5_ad_2_xlarge = "m5ad.2xlarge",
        .m_5_ad_4_xlarge = "m5ad.4xlarge",
        .m_5_ad_8_xlarge = "m5ad.8xlarge",
        .m_5_ad_12_xlarge = "m5ad.12xlarge",
        .m_5_ad_16_xlarge = "m5ad.16xlarge",
        .m_5_ad_24_xlarge = "m5ad.24xlarge",
        .m_5_d_large = "m5d.large",
        .m_5_d_xlarge = "m5d.xlarge",
        .m_5_d_2_xlarge = "m5d.2xlarge",
        .m_5_d_4_xlarge = "m5d.4xlarge",
        .m_5_d_8_xlarge = "m5d.8xlarge",
        .m_5_d_12_xlarge = "m5d.12xlarge",
        .m_5_d_16_xlarge = "m5d.16xlarge",
        .m_5_d_24_xlarge = "m5d.24xlarge",
        .m_5_dn_large = "m5dn.large",
        .m_5_dn_xlarge = "m5dn.xlarge",
        .m_5_dn_2_xlarge = "m5dn.2xlarge",
        .m_5_dn_4_xlarge = "m5dn.4xlarge",
        .m_5_dn_8_xlarge = "m5dn.8xlarge",
        .m_5_dn_12_xlarge = "m5dn.12xlarge",
        .m_5_dn_16_xlarge = "m5dn.16xlarge",
        .m_5_dn_24_xlarge = "m5dn.24xlarge",
        .m_5_n_large = "m5n.large",
        .m_5_n_xlarge = "m5n.xlarge",
        .m_5_n_2_xlarge = "m5n.2xlarge",
        .m_5_n_4_xlarge = "m5n.4xlarge",
        .m_5_n_8_xlarge = "m5n.8xlarge",
        .m_5_n_12_xlarge = "m5n.12xlarge",
        .m_5_n_16_xlarge = "m5n.16xlarge",
        .m_5_n_24_xlarge = "m5n.24xlarge",
        .m_6_id_large = "m6id.large",
        .m_6_id_xlarge = "m6id.xlarge",
        .m_6_id_2_xlarge = "m6id.2xlarge",
        .m_6_id_4_xlarge = "m6id.4xlarge",
        .m_6_id_8_xlarge = "m6id.8xlarge",
        .m_6_id_12_xlarge = "m6id.12xlarge",
        .m_6_id_16_xlarge = "m6id.16xlarge",
        .m_6_id_24_xlarge = "m6id.24xlarge",
        .m_6_id_32_xlarge = "m6id.32xlarge",
        .m_6_idn_large = "m6idn.large",
        .m_6_idn_xlarge = "m6idn.xlarge",
        .m_6_idn_2_xlarge = "m6idn.2xlarge",
        .m_6_idn_4_xlarge = "m6idn.4xlarge",
        .m_6_idn_8_xlarge = "m6idn.8xlarge",
        .m_6_idn_12_xlarge = "m6idn.12xlarge",
        .m_6_idn_16_xlarge = "m6idn.16xlarge",
        .m_6_idn_24_xlarge = "m6idn.24xlarge",
        .m_6_idn_32_xlarge = "m6idn.32xlarge",
        .m_6_in_large = "m6in.large",
        .m_6_in_xlarge = "m6in.xlarge",
        .m_6_in_2_xlarge = "m6in.2xlarge",
        .m_6_in_4_xlarge = "m6in.4xlarge",
        .m_6_in_8_xlarge = "m6in.8xlarge",
        .m_6_in_12_xlarge = "m6in.12xlarge",
        .m_6_in_16_xlarge = "m6in.16xlarge",
        .m_6_in_24_xlarge = "m6in.24xlarge",
        .m_6_in_32_xlarge = "m6in.32xlarge",
        .m_8_g_medium = "m8g.medium",
        .m_8_g_large = "m8g.large",
        .m_8_g_xlarge = "m8g.xlarge",
        .m_8_g_2_xlarge = "m8g.2xlarge",
        .m_8_g_4_xlarge = "m8g.4xlarge",
        .m_8_g_8_xlarge = "m8g.8xlarge",
        .m_8_g_12_xlarge = "m8g.12xlarge",
        .m_8_g_16_xlarge = "m8g.16xlarge",
        .m_8_g_24_xlarge = "m8g.24xlarge",
        .m_8_g_48_xlarge = "m8g.48xlarge",
        .r_5_dn_large = "r5dn.large",
        .r_5_dn_xlarge = "r5dn.xlarge",
        .r_5_dn_2_xlarge = "r5dn.2xlarge",
        .r_5_dn_4_xlarge = "r5dn.4xlarge",
        .r_5_dn_8_xlarge = "r5dn.8xlarge",
        .r_5_dn_12_xlarge = "r5dn.12xlarge",
        .r_5_dn_16_xlarge = "r5dn.16xlarge",
        .r_5_dn_24_xlarge = "r5dn.24xlarge",
        .r_5_n_large = "r5n.large",
        .r_5_n_xlarge = "r5n.xlarge",
        .r_5_n_2_xlarge = "r5n.2xlarge",
        .r_5_n_4_xlarge = "r5n.4xlarge",
        .r_5_n_8_xlarge = "r5n.8xlarge",
        .r_5_n_12_xlarge = "r5n.12xlarge",
        .r_5_n_16_xlarge = "r5n.16xlarge",
        .r_5_n_24_xlarge = "r5n.24xlarge",
        .r_6_a_large = "r6a.large",
        .r_6_a_xlarge = "r6a.xlarge",
        .r_6_a_2_xlarge = "r6a.2xlarge",
        .r_6_a_4_xlarge = "r6a.4xlarge",
        .r_6_a_8_xlarge = "r6a.8xlarge",
        .r_6_a_12_xlarge = "r6a.12xlarge",
        .r_6_a_16_xlarge = "r6a.16xlarge",
        .r_6_a_24_xlarge = "r6a.24xlarge",
        .r_6_a_32_xlarge = "r6a.32xlarge",
        .r_6_a_48_xlarge = "r6a.48xlarge",
        .r_6_id_large = "r6id.large",
        .r_6_id_xlarge = "r6id.xlarge",
        .r_6_id_2_xlarge = "r6id.2xlarge",
        .r_6_id_4_xlarge = "r6id.4xlarge",
        .r_6_id_8_xlarge = "r6id.8xlarge",
        .r_6_id_12_xlarge = "r6id.12xlarge",
        .r_6_id_16_xlarge = "r6id.16xlarge",
        .r_6_id_24_xlarge = "r6id.24xlarge",
        .r_6_id_32_xlarge = "r6id.32xlarge",
        .r_6_idn_large = "r6idn.large",
        .r_6_idn_xlarge = "r6idn.xlarge",
        .r_6_idn_2_xlarge = "r6idn.2xlarge",
        .r_6_idn_4_xlarge = "r6idn.4xlarge",
        .r_6_idn_8_xlarge = "r6idn.8xlarge",
        .r_6_idn_12_xlarge = "r6idn.12xlarge",
        .r_6_idn_16_xlarge = "r6idn.16xlarge",
        .r_6_idn_24_xlarge = "r6idn.24xlarge",
        .r_6_idn_32_xlarge = "r6idn.32xlarge",
        .r_6_in_large = "r6in.large",
        .r_6_in_xlarge = "r6in.xlarge",
        .r_6_in_2_xlarge = "r6in.2xlarge",
        .r_6_in_4_xlarge = "r6in.4xlarge",
        .r_6_in_8_xlarge = "r6in.8xlarge",
        .r_6_in_12_xlarge = "r6in.12xlarge",
        .r_6_in_16_xlarge = "r6in.16xlarge",
        .r_6_in_24_xlarge = "r6in.24xlarge",
        .r_6_in_32_xlarge = "r6in.32xlarge",
        .r_8_g_medium = "r8g.medium",
        .r_8_g_large = "r8g.large",
        .r_8_g_xlarge = "r8g.xlarge",
        .r_8_g_2_xlarge = "r8g.2xlarge",
        .r_8_g_4_xlarge = "r8g.4xlarge",
        .r_8_g_8_xlarge = "r8g.8xlarge",
        .r_8_g_12_xlarge = "r8g.12xlarge",
        .r_8_g_16_xlarge = "r8g.16xlarge",
        .r_8_g_24_xlarge = "r8g.24xlarge",
        .r_8_g_48_xlarge = "r8g.48xlarge",
        .m_4_16_xlarge = "m4.16xlarge",
        .c_6_a_32_xlarge = "c6a.32xlarge",
        .c_6_a_48_xlarge = "c6a.48xlarge",
        .c_6_i_32_xlarge = "c6i.32xlarge",
        .r_6_i_24_xlarge = "r6i.24xlarge",
        .r_6_i_32_xlarge = "r6i.32xlarge",
        .c_6_in_24_xlarge = "c6in.24xlarge",
        .c_6_in_32_xlarge = "c6in.32xlarge",
        .c_7_a_24_xlarge = "c7a.24xlarge",
        .c_7_a_32_xlarge = "c7a.32xlarge",
        .c_7_a_48_xlarge = "c7a.48xlarge",
        .c_7_i_24_xlarge = "c7i.24xlarge",
        .c_7_i_48_xlarge = "c7i.48xlarge",
        .m_6_a_24_xlarge = "m6a.24xlarge",
        .m_6_a_32_xlarge = "m6a.32xlarge",
        .m_6_a_48_xlarge = "m6a.48xlarge",
        .m_6_i_24_xlarge = "m6i.24xlarge",
        .m_6_i_32_xlarge = "m6i.32xlarge",
        .m_7_a_24_xlarge = "m7a.24xlarge",
        .m_7_a_32_xlarge = "m7a.32xlarge",
        .m_7_a_48_xlarge = "m7a.48xlarge",
        .m_7_i_24_xlarge = "m7i.24xlarge",
        .m_7_i_48_xlarge = "m7i.48xlarge",
        .r_7_a_24_xlarge = "r7a.24xlarge",
        .r_7_a_32_xlarge = "r7a.32xlarge",
        .r_7_a_48_xlarge = "r7a.48xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .t_2_micro => "t2.micro",
            .t_2_small => "t2.small",
            .t_2_medium => "t2.medium",
            .t_2_large => "t2.large",
            .c_3_large => "c3.large",
            .c_3_xlarge => "c3.xlarge",
            .c_3_2_xlarge => "c3.2xlarge",
            .c_3_4_xlarge => "c3.4xlarge",
            .c_3_8_xlarge => "c3.8xlarge",
            .c_4_large => "c4.large",
            .c_4_xlarge => "c4.xlarge",
            .c_4_2_xlarge => "c4.2xlarge",
            .c_4_4_xlarge => "c4.4xlarge",
            .c_4_8_xlarge => "c4.8xlarge",
            .c_5_large => "c5.large",
            .c_5_xlarge => "c5.xlarge",
            .c_5_2_xlarge => "c5.2xlarge",
            .c_5_4_xlarge => "c5.4xlarge",
            .c_5_9_xlarge => "c5.9xlarge",
            .c_5_12_xlarge => "c5.12xlarge",
            .c_5_18_xlarge => "c5.18xlarge",
            .c_5_24_xlarge => "c5.24xlarge",
            .c_5_a_large => "c5a.large",
            .c_5_a_xlarge => "c5a.xlarge",
            .c_5_a_2_xlarge => "c5a.2xlarge",
            .c_5_a_4_xlarge => "c5a.4xlarge",
            .c_5_a_8_xlarge => "c5a.8xlarge",
            .c_5_a_12_xlarge => "c5a.12xlarge",
            .c_5_a_16_xlarge => "c5a.16xlarge",
            .c_5_a_24_xlarge => "c5a.24xlarge",
            .r_3_large => "r3.large",
            .r_3_xlarge => "r3.xlarge",
            .r_3_2_xlarge => "r3.2xlarge",
            .r_3_4_xlarge => "r3.4xlarge",
            .r_3_8_xlarge => "r3.8xlarge",
            .r_4_large => "r4.large",
            .r_4_xlarge => "r4.xlarge",
            .r_4_2_xlarge => "r4.2xlarge",
            .r_4_4_xlarge => "r4.4xlarge",
            .r_4_8_xlarge => "r4.8xlarge",
            .r_4_16_xlarge => "r4.16xlarge",
            .r_5_large => "r5.large",
            .r_5_xlarge => "r5.xlarge",
            .r_5_2_xlarge => "r5.2xlarge",
            .r_5_4_xlarge => "r5.4xlarge",
            .r_5_8_xlarge => "r5.8xlarge",
            .r_5_12_xlarge => "r5.12xlarge",
            .r_5_16_xlarge => "r5.16xlarge",
            .r_5_24_xlarge => "r5.24xlarge",
            .r_5_a_large => "r5a.large",
            .r_5_a_xlarge => "r5a.xlarge",
            .r_5_a_2_xlarge => "r5a.2xlarge",
            .r_5_a_4_xlarge => "r5a.4xlarge",
            .r_5_a_8_xlarge => "r5a.8xlarge",
            .r_5_a_12_xlarge => "r5a.12xlarge",
            .r_5_a_16_xlarge => "r5a.16xlarge",
            .r_5_a_24_xlarge => "r5a.24xlarge",
            .m_3_medium => "m3.medium",
            .m_3_large => "m3.large",
            .m_3_xlarge => "m3.xlarge",
            .m_3_2_xlarge => "m3.2xlarge",
            .m_4_large => "m4.large",
            .m_4_xlarge => "m4.xlarge",
            .m_4_2_xlarge => "m4.2xlarge",
            .m_4_4_xlarge => "m4.4xlarge",
            .m_4_10_xlarge => "m4.10xlarge",
            .m_5_large => "m5.large",
            .m_5_xlarge => "m5.xlarge",
            .m_5_2_xlarge => "m5.2xlarge",
            .m_5_4_xlarge => "m5.4xlarge",
            .m_5_8_xlarge => "m5.8xlarge",
            .m_5_12_xlarge => "m5.12xlarge",
            .m_5_16_xlarge => "m5.16xlarge",
            .m_5_24_xlarge => "m5.24xlarge",
            .m_5_a_large => "m5a.large",
            .m_5_a_xlarge => "m5a.xlarge",
            .m_5_a_2_xlarge => "m5a.2xlarge",
            .m_5_a_4_xlarge => "m5a.4xlarge",
            .m_5_a_8_xlarge => "m5a.8xlarge",
            .m_5_a_12_xlarge => "m5a.12xlarge",
            .m_5_a_16_xlarge => "m5a.16xlarge",
            .m_5_a_24_xlarge => "m5a.24xlarge",
            .c_5_d_large => "c5d.large",
            .c_5_d_xlarge => "c5d.xlarge",
            .c_5_d_2_xlarge => "c5d.2xlarge",
            .c_5_d_4_xlarge => "c5d.4xlarge",
            .c_5_d_9_xlarge => "c5d.9xlarge",
            .c_5_d_12_xlarge => "c5d.12xlarge",
            .c_5_d_18_xlarge => "c5d.18xlarge",
            .c_5_d_24_xlarge => "c5d.24xlarge",
            .c_6_a_large => "c6a.large",
            .c_6_a_xlarge => "c6a.xlarge",
            .c_6_a_2_xlarge => "c6a.2xlarge",
            .c_6_a_4_xlarge => "c6a.4xlarge",
            .c_6_a_8_xlarge => "c6a.8xlarge",
            .c_6_a_12_xlarge => "c6a.12xlarge",
            .c_6_a_16_xlarge => "c6a.16xlarge",
            .c_6_a_24_xlarge => "c6a.24xlarge",
            .c_6_i_large => "c6i.large",
            .c_6_i_xlarge => "c6i.xlarge",
            .c_6_i_2_xlarge => "c6i.2xlarge",
            .c_6_i_4_xlarge => "c6i.4xlarge",
            .c_6_i_8_xlarge => "c6i.8xlarge",
            .c_6_i_12_xlarge => "c6i.12xlarge",
            .c_6_i_16_xlarge => "c6i.16xlarge",
            .c_6_i_24_xlarge => "c6i.24xlarge",
            .r_5_d_large => "r5d.large",
            .r_5_d_xlarge => "r5d.xlarge",
            .r_5_d_2_xlarge => "r5d.2xlarge",
            .r_5_d_4_xlarge => "r5d.4xlarge",
            .r_5_d_8_xlarge => "r5d.8xlarge",
            .r_5_d_12_xlarge => "r5d.12xlarge",
            .r_5_d_16_xlarge => "r5d.16xlarge",
            .r_5_d_24_xlarge => "r5d.24xlarge",
            .m_6_g_medium => "m6g.medium",
            .m_6_g_large => "m6g.large",
            .m_6_g_xlarge => "m6g.xlarge",
            .m_6_g_2_xlarge => "m6g.2xlarge",
            .m_6_g_4_xlarge => "m6g.4xlarge",
            .m_6_g_8_xlarge => "m6g.8xlarge",
            .m_6_g_12_xlarge => "m6g.12xlarge",
            .m_6_g_16_xlarge => "m6g.16xlarge",
            .c_6_g_medium => "c6g.medium",
            .c_6_g_large => "c6g.large",
            .c_6_g_xlarge => "c6g.xlarge",
            .c_6_g_2_xlarge => "c6g.2xlarge",
            .c_6_g_4_xlarge => "c6g.4xlarge",
            .c_6_g_8_xlarge => "c6g.8xlarge",
            .c_6_g_12_xlarge => "c6g.12xlarge",
            .c_6_g_16_xlarge => "c6g.16xlarge",
            .r_6_g_medium => "r6g.medium",
            .r_6_g_large => "r6g.large",
            .r_6_g_xlarge => "r6g.xlarge",
            .r_6_g_2_xlarge => "r6g.2xlarge",
            .r_6_g_4_xlarge => "r6g.4xlarge",
            .r_6_g_8_xlarge => "r6g.8xlarge",
            .r_6_g_12_xlarge => "r6g.12xlarge",
            .r_6_g_16_xlarge => "r6g.16xlarge",
            .c_6_gn_medium => "c6gn.medium",
            .c_6_gn_large => "c6gn.large",
            .c_6_gn_xlarge => "c6gn.xlarge",
            .c_6_gn_2_xlarge => "c6gn.2xlarge",
            .c_6_gn_4_xlarge => "c6gn.4xlarge",
            .c_6_gn_8_xlarge => "c6gn.8xlarge",
            .c_6_gn_12_xlarge => "c6gn.12xlarge",
            .c_6_gn_16_xlarge => "c6gn.16xlarge",
            .c_7_g_medium => "c7g.medium",
            .c_7_g_large => "c7g.large",
            .c_7_g_xlarge => "c7g.xlarge",
            .c_7_g_2_xlarge => "c7g.2xlarge",
            .c_7_g_4_xlarge => "c7g.4xlarge",
            .c_7_g_8_xlarge => "c7g.8xlarge",
            .c_7_g_12_xlarge => "c7g.12xlarge",
            .c_7_g_16_xlarge => "c7g.16xlarge",
            .r_7_g_medium => "r7g.medium",
            .r_7_g_large => "r7g.large",
            .r_7_g_xlarge => "r7g.xlarge",
            .r_7_g_2_xlarge => "r7g.2xlarge",
            .r_7_g_4_xlarge => "r7g.4xlarge",
            .r_7_g_8_xlarge => "r7g.8xlarge",
            .r_7_g_12_xlarge => "r7g.12xlarge",
            .r_7_g_16_xlarge => "r7g.16xlarge",
            .m_7_g_medium => "m7g.medium",
            .m_7_g_large => "m7g.large",
            .m_7_g_xlarge => "m7g.xlarge",
            .m_7_g_2_xlarge => "m7g.2xlarge",
            .m_7_g_4_xlarge => "m7g.4xlarge",
            .m_7_g_8_xlarge => "m7g.8xlarge",
            .m_7_g_12_xlarge => "m7g.12xlarge",
            .m_7_g_16_xlarge => "m7g.16xlarge",
            .g_5_g_xlarge => "g5g.xlarge",
            .g_5_g_2_xlarge => "g5g.2xlarge",
            .g_5_g_4_xlarge => "g5g.4xlarge",
            .g_5_g_8_xlarge => "g5g.8xlarge",
            .g_5_g_16_xlarge => "g5g.16xlarge",
            .r_6_i_large => "r6i.large",
            .r_6_i_xlarge => "r6i.xlarge",
            .r_6_i_2_xlarge => "r6i.2xlarge",
            .r_6_i_4_xlarge => "r6i.4xlarge",
            .r_6_i_8_xlarge => "r6i.8xlarge",
            .r_6_i_12_xlarge => "r6i.12xlarge",
            .r_6_i_16_xlarge => "r6i.16xlarge",
            .c_6_gd_medium => "c6gd.medium",
            .c_6_gd_large => "c6gd.large",
            .c_6_gd_xlarge => "c6gd.xlarge",
            .c_6_gd_2_xlarge => "c6gd.2xlarge",
            .c_6_gd_4_xlarge => "c6gd.4xlarge",
            .c_6_gd_8_xlarge => "c6gd.8xlarge",
            .c_6_gd_12_xlarge => "c6gd.12xlarge",
            .c_6_gd_16_xlarge => "c6gd.16xlarge",
            .c_6_in_large => "c6in.large",
            .c_6_in_xlarge => "c6in.xlarge",
            .c_6_in_2_xlarge => "c6in.2xlarge",
            .c_6_in_4_xlarge => "c6in.4xlarge",
            .c_6_in_8_xlarge => "c6in.8xlarge",
            .c_6_in_12_xlarge => "c6in.12xlarge",
            .c_6_in_16_xlarge => "c6in.16xlarge",
            .c_7_a_medium => "c7a.medium",
            .c_7_a_large => "c7a.large",
            .c_7_a_xlarge => "c7a.xlarge",
            .c_7_a_2_xlarge => "c7a.2xlarge",
            .c_7_a_4_xlarge => "c7a.4xlarge",
            .c_7_a_8_xlarge => "c7a.8xlarge",
            .c_7_a_12_xlarge => "c7a.12xlarge",
            .c_7_a_16_xlarge => "c7a.16xlarge",
            .c_7_gd_medium => "c7gd.medium",
            .c_7_gd_large => "c7gd.large",
            .c_7_gd_xlarge => "c7gd.xlarge",
            .c_7_gd_2_xlarge => "c7gd.2xlarge",
            .c_7_gd_4_xlarge => "c7gd.4xlarge",
            .c_7_gd_8_xlarge => "c7gd.8xlarge",
            .c_7_gd_12_xlarge => "c7gd.12xlarge",
            .c_7_gd_16_xlarge => "c7gd.16xlarge",
            .c_7_gn_medium => "c7gn.medium",
            .c_7_gn_large => "c7gn.large",
            .c_7_gn_xlarge => "c7gn.xlarge",
            .c_7_gn_2_xlarge => "c7gn.2xlarge",
            .c_7_gn_4_xlarge => "c7gn.4xlarge",
            .c_7_gn_8_xlarge => "c7gn.8xlarge",
            .c_7_gn_12_xlarge => "c7gn.12xlarge",
            .c_7_gn_16_xlarge => "c7gn.16xlarge",
            .c_7_i_large => "c7i.large",
            .c_7_i_xlarge => "c7i.xlarge",
            .c_7_i_2_xlarge => "c7i.2xlarge",
            .c_7_i_4_xlarge => "c7i.4xlarge",
            .c_7_i_8_xlarge => "c7i.8xlarge",
            .c_7_i_12_xlarge => "c7i.12xlarge",
            .c_7_i_16_xlarge => "c7i.16xlarge",
            .m_6_a_large => "m6a.large",
            .m_6_a_xlarge => "m6a.xlarge",
            .m_6_a_2_xlarge => "m6a.2xlarge",
            .m_6_a_4_xlarge => "m6a.4xlarge",
            .m_6_a_8_xlarge => "m6a.8xlarge",
            .m_6_a_12_xlarge => "m6a.12xlarge",
            .m_6_a_16_xlarge => "m6a.16xlarge",
            .m_6_gd_medium => "m6gd.medium",
            .m_6_gd_large => "m6gd.large",
            .m_6_gd_xlarge => "m6gd.xlarge",
            .m_6_gd_2_xlarge => "m6gd.2xlarge",
            .m_6_gd_4_xlarge => "m6gd.4xlarge",
            .m_6_gd_8_xlarge => "m6gd.8xlarge",
            .m_6_gd_12_xlarge => "m6gd.12xlarge",
            .m_6_gd_16_xlarge => "m6gd.16xlarge",
            .m_6_i_large => "m6i.large",
            .m_6_i_xlarge => "m6i.xlarge",
            .m_6_i_2_xlarge => "m6i.2xlarge",
            .m_6_i_4_xlarge => "m6i.4xlarge",
            .m_6_i_8_xlarge => "m6i.8xlarge",
            .m_6_i_12_xlarge => "m6i.12xlarge",
            .m_6_i_16_xlarge => "m6i.16xlarge",
            .m_7_a_medium => "m7a.medium",
            .m_7_a_large => "m7a.large",
            .m_7_a_xlarge => "m7a.xlarge",
            .m_7_a_2_xlarge => "m7a.2xlarge",
            .m_7_a_4_xlarge => "m7a.4xlarge",
            .m_7_a_8_xlarge => "m7a.8xlarge",
            .m_7_a_12_xlarge => "m7a.12xlarge",
            .m_7_a_16_xlarge => "m7a.16xlarge",
            .m_7_gd_medium => "m7gd.medium",
            .m_7_gd_large => "m7gd.large",
            .m_7_gd_xlarge => "m7gd.xlarge",
            .m_7_gd_2_xlarge => "m7gd.2xlarge",
            .m_7_gd_4_xlarge => "m7gd.4xlarge",
            .m_7_gd_8_xlarge => "m7gd.8xlarge",
            .m_7_gd_12_xlarge => "m7gd.12xlarge",
            .m_7_gd_16_xlarge => "m7gd.16xlarge",
            .m_7_i_large => "m7i.large",
            .m_7_i_xlarge => "m7i.xlarge",
            .m_7_i_2_xlarge => "m7i.2xlarge",
            .m_7_i_4_xlarge => "m7i.4xlarge",
            .m_7_i_8_xlarge => "m7i.8xlarge",
            .m_7_i_12_xlarge => "m7i.12xlarge",
            .m_7_i_16_xlarge => "m7i.16xlarge",
            .r_6_gd_medium => "r6gd.medium",
            .r_6_gd_large => "r6gd.large",
            .r_6_gd_xlarge => "r6gd.xlarge",
            .r_6_gd_2_xlarge => "r6gd.2xlarge",
            .r_6_gd_4_xlarge => "r6gd.4xlarge",
            .r_6_gd_8_xlarge => "r6gd.8xlarge",
            .r_6_gd_12_xlarge => "r6gd.12xlarge",
            .r_6_gd_16_xlarge => "r6gd.16xlarge",
            .r_7_a_medium => "r7a.medium",
            .r_7_a_large => "r7a.large",
            .r_7_a_xlarge => "r7a.xlarge",
            .r_7_a_2_xlarge => "r7a.2xlarge",
            .r_7_a_4_xlarge => "r7a.4xlarge",
            .r_7_a_8_xlarge => "r7a.8xlarge",
            .r_7_a_12_xlarge => "r7a.12xlarge",
            .r_7_a_16_xlarge => "r7a.16xlarge",
            .r_7_gd_medium => "r7gd.medium",
            .r_7_gd_large => "r7gd.large",
            .r_7_gd_xlarge => "r7gd.xlarge",
            .r_7_gd_2_xlarge => "r7gd.2xlarge",
            .r_7_gd_4_xlarge => "r7gd.4xlarge",
            .r_7_gd_8_xlarge => "r7gd.8xlarge",
            .r_7_gd_12_xlarge => "r7gd.12xlarge",
            .r_7_gd_16_xlarge => "r7gd.16xlarge",
            .r_7_i_large => "r7i.large",
            .r_7_i_xlarge => "r7i.xlarge",
            .r_7_i_2_xlarge => "r7i.2xlarge",
            .r_7_i_4_xlarge => "r7i.4xlarge",
            .r_7_i_8_xlarge => "r7i.8xlarge",
            .r_7_i_12_xlarge => "r7i.12xlarge",
            .r_7_i_16_xlarge => "r7i.16xlarge",
            .r_7_i_24_xlarge => "r7i.24xlarge",
            .r_7_i_48_xlarge => "r7i.48xlarge",
            .c_5_ad_large => "c5ad.large",
            .c_5_ad_xlarge => "c5ad.xlarge",
            .c_5_ad_2_xlarge => "c5ad.2xlarge",
            .c_5_ad_4_xlarge => "c5ad.4xlarge",
            .c_5_ad_8_xlarge => "c5ad.8xlarge",
            .c_5_ad_12_xlarge => "c5ad.12xlarge",
            .c_5_ad_16_xlarge => "c5ad.16xlarge",
            .c_5_ad_24_xlarge => "c5ad.24xlarge",
            .c_5_n_large => "c5n.large",
            .c_5_n_xlarge => "c5n.xlarge",
            .c_5_n_2_xlarge => "c5n.2xlarge",
            .c_5_n_4_xlarge => "c5n.4xlarge",
            .c_5_n_9_xlarge => "c5n.9xlarge",
            .c_5_n_18_xlarge => "c5n.18xlarge",
            .r_5_ad_large => "r5ad.large",
            .r_5_ad_xlarge => "r5ad.xlarge",
            .r_5_ad_2_xlarge => "r5ad.2xlarge",
            .r_5_ad_4_xlarge => "r5ad.4xlarge",
            .r_5_ad_8_xlarge => "r5ad.8xlarge",
            .r_5_ad_12_xlarge => "r5ad.12xlarge",
            .r_5_ad_16_xlarge => "r5ad.16xlarge",
            .r_5_ad_24_xlarge => "r5ad.24xlarge",
            .c_6_id_large => "c6id.large",
            .c_6_id_xlarge => "c6id.xlarge",
            .c_6_id_2_xlarge => "c6id.2xlarge",
            .c_6_id_4_xlarge => "c6id.4xlarge",
            .c_6_id_8_xlarge => "c6id.8xlarge",
            .c_6_id_12_xlarge => "c6id.12xlarge",
            .c_6_id_16_xlarge => "c6id.16xlarge",
            .c_6_id_24_xlarge => "c6id.24xlarge",
            .c_6_id_32_xlarge => "c6id.32xlarge",
            .c_8_g_medium => "c8g.medium",
            .c_8_g_large => "c8g.large",
            .c_8_g_xlarge => "c8g.xlarge",
            .c_8_g_2_xlarge => "c8g.2xlarge",
            .c_8_g_4_xlarge => "c8g.4xlarge",
            .c_8_g_8_xlarge => "c8g.8xlarge",
            .c_8_g_12_xlarge => "c8g.12xlarge",
            .c_8_g_16_xlarge => "c8g.16xlarge",
            .c_8_g_24_xlarge => "c8g.24xlarge",
            .c_8_g_48_xlarge => "c8g.48xlarge",
            .m_5_ad_large => "m5ad.large",
            .m_5_ad_xlarge => "m5ad.xlarge",
            .m_5_ad_2_xlarge => "m5ad.2xlarge",
            .m_5_ad_4_xlarge => "m5ad.4xlarge",
            .m_5_ad_8_xlarge => "m5ad.8xlarge",
            .m_5_ad_12_xlarge => "m5ad.12xlarge",
            .m_5_ad_16_xlarge => "m5ad.16xlarge",
            .m_5_ad_24_xlarge => "m5ad.24xlarge",
            .m_5_d_large => "m5d.large",
            .m_5_d_xlarge => "m5d.xlarge",
            .m_5_d_2_xlarge => "m5d.2xlarge",
            .m_5_d_4_xlarge => "m5d.4xlarge",
            .m_5_d_8_xlarge => "m5d.8xlarge",
            .m_5_d_12_xlarge => "m5d.12xlarge",
            .m_5_d_16_xlarge => "m5d.16xlarge",
            .m_5_d_24_xlarge => "m5d.24xlarge",
            .m_5_dn_large => "m5dn.large",
            .m_5_dn_xlarge => "m5dn.xlarge",
            .m_5_dn_2_xlarge => "m5dn.2xlarge",
            .m_5_dn_4_xlarge => "m5dn.4xlarge",
            .m_5_dn_8_xlarge => "m5dn.8xlarge",
            .m_5_dn_12_xlarge => "m5dn.12xlarge",
            .m_5_dn_16_xlarge => "m5dn.16xlarge",
            .m_5_dn_24_xlarge => "m5dn.24xlarge",
            .m_5_n_large => "m5n.large",
            .m_5_n_xlarge => "m5n.xlarge",
            .m_5_n_2_xlarge => "m5n.2xlarge",
            .m_5_n_4_xlarge => "m5n.4xlarge",
            .m_5_n_8_xlarge => "m5n.8xlarge",
            .m_5_n_12_xlarge => "m5n.12xlarge",
            .m_5_n_16_xlarge => "m5n.16xlarge",
            .m_5_n_24_xlarge => "m5n.24xlarge",
            .m_6_id_large => "m6id.large",
            .m_6_id_xlarge => "m6id.xlarge",
            .m_6_id_2_xlarge => "m6id.2xlarge",
            .m_6_id_4_xlarge => "m6id.4xlarge",
            .m_6_id_8_xlarge => "m6id.8xlarge",
            .m_6_id_12_xlarge => "m6id.12xlarge",
            .m_6_id_16_xlarge => "m6id.16xlarge",
            .m_6_id_24_xlarge => "m6id.24xlarge",
            .m_6_id_32_xlarge => "m6id.32xlarge",
            .m_6_idn_large => "m6idn.large",
            .m_6_idn_xlarge => "m6idn.xlarge",
            .m_6_idn_2_xlarge => "m6idn.2xlarge",
            .m_6_idn_4_xlarge => "m6idn.4xlarge",
            .m_6_idn_8_xlarge => "m6idn.8xlarge",
            .m_6_idn_12_xlarge => "m6idn.12xlarge",
            .m_6_idn_16_xlarge => "m6idn.16xlarge",
            .m_6_idn_24_xlarge => "m6idn.24xlarge",
            .m_6_idn_32_xlarge => "m6idn.32xlarge",
            .m_6_in_large => "m6in.large",
            .m_6_in_xlarge => "m6in.xlarge",
            .m_6_in_2_xlarge => "m6in.2xlarge",
            .m_6_in_4_xlarge => "m6in.4xlarge",
            .m_6_in_8_xlarge => "m6in.8xlarge",
            .m_6_in_12_xlarge => "m6in.12xlarge",
            .m_6_in_16_xlarge => "m6in.16xlarge",
            .m_6_in_24_xlarge => "m6in.24xlarge",
            .m_6_in_32_xlarge => "m6in.32xlarge",
            .m_8_g_medium => "m8g.medium",
            .m_8_g_large => "m8g.large",
            .m_8_g_xlarge => "m8g.xlarge",
            .m_8_g_2_xlarge => "m8g.2xlarge",
            .m_8_g_4_xlarge => "m8g.4xlarge",
            .m_8_g_8_xlarge => "m8g.8xlarge",
            .m_8_g_12_xlarge => "m8g.12xlarge",
            .m_8_g_16_xlarge => "m8g.16xlarge",
            .m_8_g_24_xlarge => "m8g.24xlarge",
            .m_8_g_48_xlarge => "m8g.48xlarge",
            .r_5_dn_large => "r5dn.large",
            .r_5_dn_xlarge => "r5dn.xlarge",
            .r_5_dn_2_xlarge => "r5dn.2xlarge",
            .r_5_dn_4_xlarge => "r5dn.4xlarge",
            .r_5_dn_8_xlarge => "r5dn.8xlarge",
            .r_5_dn_12_xlarge => "r5dn.12xlarge",
            .r_5_dn_16_xlarge => "r5dn.16xlarge",
            .r_5_dn_24_xlarge => "r5dn.24xlarge",
            .r_5_n_large => "r5n.large",
            .r_5_n_xlarge => "r5n.xlarge",
            .r_5_n_2_xlarge => "r5n.2xlarge",
            .r_5_n_4_xlarge => "r5n.4xlarge",
            .r_5_n_8_xlarge => "r5n.8xlarge",
            .r_5_n_12_xlarge => "r5n.12xlarge",
            .r_5_n_16_xlarge => "r5n.16xlarge",
            .r_5_n_24_xlarge => "r5n.24xlarge",
            .r_6_a_large => "r6a.large",
            .r_6_a_xlarge => "r6a.xlarge",
            .r_6_a_2_xlarge => "r6a.2xlarge",
            .r_6_a_4_xlarge => "r6a.4xlarge",
            .r_6_a_8_xlarge => "r6a.8xlarge",
            .r_6_a_12_xlarge => "r6a.12xlarge",
            .r_6_a_16_xlarge => "r6a.16xlarge",
            .r_6_a_24_xlarge => "r6a.24xlarge",
            .r_6_a_32_xlarge => "r6a.32xlarge",
            .r_6_a_48_xlarge => "r6a.48xlarge",
            .r_6_id_large => "r6id.large",
            .r_6_id_xlarge => "r6id.xlarge",
            .r_6_id_2_xlarge => "r6id.2xlarge",
            .r_6_id_4_xlarge => "r6id.4xlarge",
            .r_6_id_8_xlarge => "r6id.8xlarge",
            .r_6_id_12_xlarge => "r6id.12xlarge",
            .r_6_id_16_xlarge => "r6id.16xlarge",
            .r_6_id_24_xlarge => "r6id.24xlarge",
            .r_6_id_32_xlarge => "r6id.32xlarge",
            .r_6_idn_large => "r6idn.large",
            .r_6_idn_xlarge => "r6idn.xlarge",
            .r_6_idn_2_xlarge => "r6idn.2xlarge",
            .r_6_idn_4_xlarge => "r6idn.4xlarge",
            .r_6_idn_8_xlarge => "r6idn.8xlarge",
            .r_6_idn_12_xlarge => "r6idn.12xlarge",
            .r_6_idn_16_xlarge => "r6idn.16xlarge",
            .r_6_idn_24_xlarge => "r6idn.24xlarge",
            .r_6_idn_32_xlarge => "r6idn.32xlarge",
            .r_6_in_large => "r6in.large",
            .r_6_in_xlarge => "r6in.xlarge",
            .r_6_in_2_xlarge => "r6in.2xlarge",
            .r_6_in_4_xlarge => "r6in.4xlarge",
            .r_6_in_8_xlarge => "r6in.8xlarge",
            .r_6_in_12_xlarge => "r6in.12xlarge",
            .r_6_in_16_xlarge => "r6in.16xlarge",
            .r_6_in_24_xlarge => "r6in.24xlarge",
            .r_6_in_32_xlarge => "r6in.32xlarge",
            .r_8_g_medium => "r8g.medium",
            .r_8_g_large => "r8g.large",
            .r_8_g_xlarge => "r8g.xlarge",
            .r_8_g_2_xlarge => "r8g.2xlarge",
            .r_8_g_4_xlarge => "r8g.4xlarge",
            .r_8_g_8_xlarge => "r8g.8xlarge",
            .r_8_g_12_xlarge => "r8g.12xlarge",
            .r_8_g_16_xlarge => "r8g.16xlarge",
            .r_8_g_24_xlarge => "r8g.24xlarge",
            .r_8_g_48_xlarge => "r8g.48xlarge",
            .m_4_16_xlarge => "m4.16xlarge",
            .c_6_a_32_xlarge => "c6a.32xlarge",
            .c_6_a_48_xlarge => "c6a.48xlarge",
            .c_6_i_32_xlarge => "c6i.32xlarge",
            .r_6_i_24_xlarge => "r6i.24xlarge",
            .r_6_i_32_xlarge => "r6i.32xlarge",
            .c_6_in_24_xlarge => "c6in.24xlarge",
            .c_6_in_32_xlarge => "c6in.32xlarge",
            .c_7_a_24_xlarge => "c7a.24xlarge",
            .c_7_a_32_xlarge => "c7a.32xlarge",
            .c_7_a_48_xlarge => "c7a.48xlarge",
            .c_7_i_24_xlarge => "c7i.24xlarge",
            .c_7_i_48_xlarge => "c7i.48xlarge",
            .m_6_a_24_xlarge => "m6a.24xlarge",
            .m_6_a_32_xlarge => "m6a.32xlarge",
            .m_6_a_48_xlarge => "m6a.48xlarge",
            .m_6_i_24_xlarge => "m6i.24xlarge",
            .m_6_i_32_xlarge => "m6i.32xlarge",
            .m_7_a_24_xlarge => "m7a.24xlarge",
            .m_7_a_32_xlarge => "m7a.32xlarge",
            .m_7_a_48_xlarge => "m7a.48xlarge",
            .m_7_i_24_xlarge => "m7i.24xlarge",
            .m_7_i_48_xlarge => "m7i.48xlarge",
            .r_7_a_24_xlarge => "r7a.24xlarge",
            .r_7_a_32_xlarge => "r7a.32xlarge",
            .r_7_a_48_xlarge => "r7a.48xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        @setEvalBranchQuota(1615);
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
