const std = @import("std");

pub const GameServerGroupInstanceType = enum {
    c_4_large,
    c_4_xlarge,
    c_4_2_xlarge,
    c_4_4_xlarge,
    c_4_8_xlarge,
    c_5_large,
    c_5_xlarge,
    c_5_2_xlarge,
    c_5_4_xlarge,
    c_5_9_xlarge,
    c_5_12_xlarge,
    c_5_18_xlarge,
    c_5_24_xlarge,
    c_5_a_large,
    c_5_a_xlarge,
    c_5_a_2_xlarge,
    c_5_a_4_xlarge,
    c_5_a_8_xlarge,
    c_5_a_12_xlarge,
    c_5_a_16_xlarge,
    c_5_a_24_xlarge,
    c_6_g_medium,
    c_6_g_large,
    c_6_g_xlarge,
    c_6_g_2_xlarge,
    c_6_g_4_xlarge,
    c_6_g_8_xlarge,
    c_6_g_12_xlarge,
    c_6_g_16_xlarge,
    r_4_large,
    r_4_xlarge,
    r_4_2_xlarge,
    r_4_4_xlarge,
    r_4_8_xlarge,
    r_4_16_xlarge,
    r_5_large,
    r_5_xlarge,
    r_5_2_xlarge,
    r_5_4_xlarge,
    r_5_8_xlarge,
    r_5_12_xlarge,
    r_5_16_xlarge,
    r_5_24_xlarge,
    r_5_a_large,
    r_5_a_xlarge,
    r_5_a_2_xlarge,
    r_5_a_4_xlarge,
    r_5_a_8_xlarge,
    r_5_a_12_xlarge,
    r_5_a_16_xlarge,
    r_5_a_24_xlarge,
    r_6_g_medium,
    r_6_g_large,
    r_6_g_xlarge,
    r_6_g_2_xlarge,
    r_6_g_4_xlarge,
    r_6_g_8_xlarge,
    r_6_g_12_xlarge,
    r_6_g_16_xlarge,
    m_4_large,
    m_4_xlarge,
    m_4_2_xlarge,
    m_4_4_xlarge,
    m_4_10_xlarge,
    m_5_large,
    m_5_xlarge,
    m_5_2_xlarge,
    m_5_4_xlarge,
    m_5_8_xlarge,
    m_5_12_xlarge,
    m_5_16_xlarge,
    m_5_24_xlarge,
    m_5_a_large,
    m_5_a_xlarge,
    m_5_a_2_xlarge,
    m_5_a_4_xlarge,
    m_5_a_8_xlarge,
    m_5_a_12_xlarge,
    m_5_a_16_xlarge,
    m_5_a_24_xlarge,
    m_6_g_medium,
    m_6_g_large,
    m_6_g_xlarge,
    m_6_g_2_xlarge,
    m_6_g_4_xlarge,
    m_6_g_8_xlarge,
    m_6_g_12_xlarge,
    m_6_g_16_xlarge,

    pub const json_field_names = .{
        .c_4_large = "c4.large",
        .c_4_xlarge = "c4.xlarge",
        .c_4_2_xlarge = "c4.2xlarge",
        .c_4_4_xlarge = "c4.4xlarge",
        .c_4_8_xlarge = "c4.8xlarge",
        .c_5_large = "c5.large",
        .c_5_xlarge = "c5.xlarge",
        .c_5_2_xlarge = "c5.2xlarge",
        .c_5_4_xlarge = "c5.4xlarge",
        .c_5_9_xlarge = "c5.9xlarge",
        .c_5_12_xlarge = "c5.12xlarge",
        .c_5_18_xlarge = "c5.18xlarge",
        .c_5_24_xlarge = "c5.24xlarge",
        .c_5_a_large = "c5a.large",
        .c_5_a_xlarge = "c5a.xlarge",
        .c_5_a_2_xlarge = "c5a.2xlarge",
        .c_5_a_4_xlarge = "c5a.4xlarge",
        .c_5_a_8_xlarge = "c5a.8xlarge",
        .c_5_a_12_xlarge = "c5a.12xlarge",
        .c_5_a_16_xlarge = "c5a.16xlarge",
        .c_5_a_24_xlarge = "c5a.24xlarge",
        .c_6_g_medium = "c6g.medium",
        .c_6_g_large = "c6g.large",
        .c_6_g_xlarge = "c6g.xlarge",
        .c_6_g_2_xlarge = "c6g.2xlarge",
        .c_6_g_4_xlarge = "c6g.4xlarge",
        .c_6_g_8_xlarge = "c6g.8xlarge",
        .c_6_g_12_xlarge = "c6g.12xlarge",
        .c_6_g_16_xlarge = "c6g.16xlarge",
        .r_4_large = "r4.large",
        .r_4_xlarge = "r4.xlarge",
        .r_4_2_xlarge = "r4.2xlarge",
        .r_4_4_xlarge = "r4.4xlarge",
        .r_4_8_xlarge = "r4.8xlarge",
        .r_4_16_xlarge = "r4.16xlarge",
        .r_5_large = "r5.large",
        .r_5_xlarge = "r5.xlarge",
        .r_5_2_xlarge = "r5.2xlarge",
        .r_5_4_xlarge = "r5.4xlarge",
        .r_5_8_xlarge = "r5.8xlarge",
        .r_5_12_xlarge = "r5.12xlarge",
        .r_5_16_xlarge = "r5.16xlarge",
        .r_5_24_xlarge = "r5.24xlarge",
        .r_5_a_large = "r5a.large",
        .r_5_a_xlarge = "r5a.xlarge",
        .r_5_a_2_xlarge = "r5a.2xlarge",
        .r_5_a_4_xlarge = "r5a.4xlarge",
        .r_5_a_8_xlarge = "r5a.8xlarge",
        .r_5_a_12_xlarge = "r5a.12xlarge",
        .r_5_a_16_xlarge = "r5a.16xlarge",
        .r_5_a_24_xlarge = "r5a.24xlarge",
        .r_6_g_medium = "r6g.medium",
        .r_6_g_large = "r6g.large",
        .r_6_g_xlarge = "r6g.xlarge",
        .r_6_g_2_xlarge = "r6g.2xlarge",
        .r_6_g_4_xlarge = "r6g.4xlarge",
        .r_6_g_8_xlarge = "r6g.8xlarge",
        .r_6_g_12_xlarge = "r6g.12xlarge",
        .r_6_g_16_xlarge = "r6g.16xlarge",
        .m_4_large = "m4.large",
        .m_4_xlarge = "m4.xlarge",
        .m_4_2_xlarge = "m4.2xlarge",
        .m_4_4_xlarge = "m4.4xlarge",
        .m_4_10_xlarge = "m4.10xlarge",
        .m_5_large = "m5.large",
        .m_5_xlarge = "m5.xlarge",
        .m_5_2_xlarge = "m5.2xlarge",
        .m_5_4_xlarge = "m5.4xlarge",
        .m_5_8_xlarge = "m5.8xlarge",
        .m_5_12_xlarge = "m5.12xlarge",
        .m_5_16_xlarge = "m5.16xlarge",
        .m_5_24_xlarge = "m5.24xlarge",
        .m_5_a_large = "m5a.large",
        .m_5_a_xlarge = "m5a.xlarge",
        .m_5_a_2_xlarge = "m5a.2xlarge",
        .m_5_a_4_xlarge = "m5a.4xlarge",
        .m_5_a_8_xlarge = "m5a.8xlarge",
        .m_5_a_12_xlarge = "m5a.12xlarge",
        .m_5_a_16_xlarge = "m5a.16xlarge",
        .m_5_a_24_xlarge = "m5a.24xlarge",
        .m_6_g_medium = "m6g.medium",
        .m_6_g_large = "m6g.large",
        .m_6_g_xlarge = "m6g.xlarge",
        .m_6_g_2_xlarge = "m6g.2xlarge",
        .m_6_g_4_xlarge = "m6g.4xlarge",
        .m_6_g_8_xlarge = "m6g.8xlarge",
        .m_6_g_12_xlarge = "m6g.12xlarge",
        .m_6_g_16_xlarge = "m6g.16xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .c_4_large => "c4.large",
            .c_4_xlarge => "c4.xlarge",
            .c_4_2_xlarge => "c4.2xlarge",
            .c_4_4_xlarge => "c4.4xlarge",
            .c_4_8_xlarge => "c4.8xlarge",
            .c_5_large => "c5.large",
            .c_5_xlarge => "c5.xlarge",
            .c_5_2_xlarge => "c5.2xlarge",
            .c_5_4_xlarge => "c5.4xlarge",
            .c_5_9_xlarge => "c5.9xlarge",
            .c_5_12_xlarge => "c5.12xlarge",
            .c_5_18_xlarge => "c5.18xlarge",
            .c_5_24_xlarge => "c5.24xlarge",
            .c_5_a_large => "c5a.large",
            .c_5_a_xlarge => "c5a.xlarge",
            .c_5_a_2_xlarge => "c5a.2xlarge",
            .c_5_a_4_xlarge => "c5a.4xlarge",
            .c_5_a_8_xlarge => "c5a.8xlarge",
            .c_5_a_12_xlarge => "c5a.12xlarge",
            .c_5_a_16_xlarge => "c5a.16xlarge",
            .c_5_a_24_xlarge => "c5a.24xlarge",
            .c_6_g_medium => "c6g.medium",
            .c_6_g_large => "c6g.large",
            .c_6_g_xlarge => "c6g.xlarge",
            .c_6_g_2_xlarge => "c6g.2xlarge",
            .c_6_g_4_xlarge => "c6g.4xlarge",
            .c_6_g_8_xlarge => "c6g.8xlarge",
            .c_6_g_12_xlarge => "c6g.12xlarge",
            .c_6_g_16_xlarge => "c6g.16xlarge",
            .r_4_large => "r4.large",
            .r_4_xlarge => "r4.xlarge",
            .r_4_2_xlarge => "r4.2xlarge",
            .r_4_4_xlarge => "r4.4xlarge",
            .r_4_8_xlarge => "r4.8xlarge",
            .r_4_16_xlarge => "r4.16xlarge",
            .r_5_large => "r5.large",
            .r_5_xlarge => "r5.xlarge",
            .r_5_2_xlarge => "r5.2xlarge",
            .r_5_4_xlarge => "r5.4xlarge",
            .r_5_8_xlarge => "r5.8xlarge",
            .r_5_12_xlarge => "r5.12xlarge",
            .r_5_16_xlarge => "r5.16xlarge",
            .r_5_24_xlarge => "r5.24xlarge",
            .r_5_a_large => "r5a.large",
            .r_5_a_xlarge => "r5a.xlarge",
            .r_5_a_2_xlarge => "r5a.2xlarge",
            .r_5_a_4_xlarge => "r5a.4xlarge",
            .r_5_a_8_xlarge => "r5a.8xlarge",
            .r_5_a_12_xlarge => "r5a.12xlarge",
            .r_5_a_16_xlarge => "r5a.16xlarge",
            .r_5_a_24_xlarge => "r5a.24xlarge",
            .r_6_g_medium => "r6g.medium",
            .r_6_g_large => "r6g.large",
            .r_6_g_xlarge => "r6g.xlarge",
            .r_6_g_2_xlarge => "r6g.2xlarge",
            .r_6_g_4_xlarge => "r6g.4xlarge",
            .r_6_g_8_xlarge => "r6g.8xlarge",
            .r_6_g_12_xlarge => "r6g.12xlarge",
            .r_6_g_16_xlarge => "r6g.16xlarge",
            .m_4_large => "m4.large",
            .m_4_xlarge => "m4.xlarge",
            .m_4_2_xlarge => "m4.2xlarge",
            .m_4_4_xlarge => "m4.4xlarge",
            .m_4_10_xlarge => "m4.10xlarge",
            .m_5_large => "m5.large",
            .m_5_xlarge => "m5.xlarge",
            .m_5_2_xlarge => "m5.2xlarge",
            .m_5_4_xlarge => "m5.4xlarge",
            .m_5_8_xlarge => "m5.8xlarge",
            .m_5_12_xlarge => "m5.12xlarge",
            .m_5_16_xlarge => "m5.16xlarge",
            .m_5_24_xlarge => "m5.24xlarge",
            .m_5_a_large => "m5a.large",
            .m_5_a_xlarge => "m5a.xlarge",
            .m_5_a_2_xlarge => "m5a.2xlarge",
            .m_5_a_4_xlarge => "m5a.4xlarge",
            .m_5_a_8_xlarge => "m5a.8xlarge",
            .m_5_a_12_xlarge => "m5a.12xlarge",
            .m_5_a_16_xlarge => "m5a.16xlarge",
            .m_5_a_24_xlarge => "m5a.24xlarge",
            .m_6_g_medium => "m6g.medium",
            .m_6_g_large => "m6g.large",
            .m_6_g_xlarge => "m6g.xlarge",
            .m_6_g_2_xlarge => "m6g.2xlarge",
            .m_6_g_4_xlarge => "m6g.4xlarge",
            .m_6_g_8_xlarge => "m6g.8xlarge",
            .m_6_g_12_xlarge => "m6g.12xlarge",
            .m_6_g_16_xlarge => "m6g.16xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
