const std = @import("std");

pub const LinuxCapability = enum {
    audit_control,
    audit_write,
    block_suspend,
    chown,
    dac_override,
    dac_read_search,
    fowner,
    fsetid,
    ipc_lock,
    ipc_owner,
    kill,
    lease,
    linux_immutable,
    mac_admin,
    mac_override,
    mknod,
    net_admin,
    net_bind_service,
    net_broadcast,
    net_raw,
    setfcap,
    setgid,
    setpcap,
    setuid,
    sys_admin,
    sys_boot,
    sys_chroot,
    sys_module,
    sys_nice,
    sys_pacct,
    sys_ptrace,
    sys_rawio,
    sys_resource,
    sys_time,
    sys_tty_config,
    syslog,
    wake_alarm,

    pub const json_field_names = .{
        .audit_control = "AUDIT_CONTROL",
        .audit_write = "AUDIT_WRITE",
        .block_suspend = "BLOCK_SUSPEND",
        .chown = "CHOWN",
        .dac_override = "DAC_OVERRIDE",
        .dac_read_search = "DAC_READ_SEARCH",
        .fowner = "FOWNER",
        .fsetid = "FSETID",
        .ipc_lock = "IPC_LOCK",
        .ipc_owner = "IPC_OWNER",
        .kill = "KILL",
        .lease = "LEASE",
        .linux_immutable = "LINUX_IMMUTABLE",
        .mac_admin = "MAC_ADMIN",
        .mac_override = "MAC_OVERRIDE",
        .mknod = "MKNOD",
        .net_admin = "NET_ADMIN",
        .net_bind_service = "NET_BIND_SERVICE",
        .net_broadcast = "NET_BROADCAST",
        .net_raw = "NET_RAW",
        .setfcap = "SETFCAP",
        .setgid = "SETGID",
        .setpcap = "SETPCAP",
        .setuid = "SETUID",
        .sys_admin = "SYS_ADMIN",
        .sys_boot = "SYS_BOOT",
        .sys_chroot = "SYS_CHROOT",
        .sys_module = "SYS_MODULE",
        .sys_nice = "SYS_NICE",
        .sys_pacct = "SYS_PACCT",
        .sys_ptrace = "SYS_PTRACE",
        .sys_rawio = "SYS_RAWIO",
        .sys_resource = "SYS_RESOURCE",
        .sys_time = "SYS_TIME",
        .sys_tty_config = "SYS_TTY_CONFIG",
        .syslog = "SYSLOG",
        .wake_alarm = "WAKE_ALARM",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .audit_control => "AUDIT_CONTROL",
            .audit_write => "AUDIT_WRITE",
            .block_suspend => "BLOCK_SUSPEND",
            .chown => "CHOWN",
            .dac_override => "DAC_OVERRIDE",
            .dac_read_search => "DAC_READ_SEARCH",
            .fowner => "FOWNER",
            .fsetid => "FSETID",
            .ipc_lock => "IPC_LOCK",
            .ipc_owner => "IPC_OWNER",
            .kill => "KILL",
            .lease => "LEASE",
            .linux_immutable => "LINUX_IMMUTABLE",
            .mac_admin => "MAC_ADMIN",
            .mac_override => "MAC_OVERRIDE",
            .mknod => "MKNOD",
            .net_admin => "NET_ADMIN",
            .net_bind_service => "NET_BIND_SERVICE",
            .net_broadcast => "NET_BROADCAST",
            .net_raw => "NET_RAW",
            .setfcap => "SETFCAP",
            .setgid => "SETGID",
            .setpcap => "SETPCAP",
            .setuid => "SETUID",
            .sys_admin => "SYS_ADMIN",
            .sys_boot => "SYS_BOOT",
            .sys_chroot => "SYS_CHROOT",
            .sys_module => "SYS_MODULE",
            .sys_nice => "SYS_NICE",
            .sys_pacct => "SYS_PACCT",
            .sys_ptrace => "SYS_PTRACE",
            .sys_rawio => "SYS_RAWIO",
            .sys_resource => "SYS_RESOURCE",
            .sys_time => "SYS_TIME",
            .sys_tty_config => "SYS_TTY_CONFIG",
            .syslog => "SYSLOG",
            .wake_alarm => "WAKE_ALARM",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
