const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const ServiceError = @import("errors.zig").ServiceError;
const ChecksumAlgorithm = @import("checksum_algorithm.zig").ChecksumAlgorithm;

pub const PutSnapshotBlockInput = struct {
    /// The data to write to the block.
    ///
    /// The block data is not signed as part of the Signature Version 4 signing
    /// process. As a
    /// result, you must generate and provide a Base64-encoded SHA256 checksum for
    /// the block
    /// data using the **x-amz-Checksum** header. Also, you
    /// must specify the checksum algorithm using the **x-amz-Checksum-Algorithm**
    /// header. The checksum that you provide is part of the Signature Version 4
    /// signing process.
    /// It is validated against a checksum generated by Amazon EBS to ensure the
    /// validity and authenticity
    /// of the data. If the checksums do not correspond, the request fails. For more
    /// information,
    /// see [
    /// Using checksums with the EBS direct
    /// APIs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html#ebsapis-using-checksums) in the *Amazon Elastic Compute Cloud User
    /// Guide*.
    block_data: []const u8,

    /// The block index of the block in which to write the data. A block index is a
    /// logical
    /// index in units of `512` KiB blocks. To identify the block index, divide
    /// the logical offset of the data in the logical volume by the block size
    /// (logical offset of
    /// data/`524288`). The logical offset of the data must be `512`
    /// KiB aligned.
    block_index: i32,

    /// A Base64-encoded SHA256 checksum of the data. Only SHA256 checksums are
    /// supported.
    checksum: []const u8,

    /// The algorithm used to generate the checksum. Currently, the only supported
    /// algorithm
    /// is `SHA256`.
    checksum_algorithm: ChecksumAlgorithm,

    /// The size of the data to write to the block, in bytes. Currently, the only
    /// supported
    /// size is `524288` bytes.
    ///
    /// Valid values: `524288`
    data_length: i32,

    /// The progress of the write process, as a percentage.
    progress: ?i32 = null,

    /// The ID of the snapshot.
    ///
    /// If the specified snapshot is encrypted, you must have permission to use
    /// the KMS key that was used to encrypt the snapshot. For more information,
    /// see [
    /// Using
    /// encryption](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html) in the *Amazon Elastic Compute Cloud User
    /// Guide*..
    snapshot_id: []const u8,

    pub const json_field_names = .{
        .block_data = "BlockData",
        .block_index = "BlockIndex",
        .checksum = "Checksum",
        .checksum_algorithm = "ChecksumAlgorithm",
        .data_length = "DataLength",
        .progress = "Progress",
        .snapshot_id = "SnapshotId",
    };
};

pub const PutSnapshotBlockOutput = struct {
    /// The SHA256 checksum generated for the block data by Amazon EBS.
    checksum: ?[]const u8 = null,

    /// The algorithm used by Amazon EBS to generate the checksum.
    checksum_algorithm: ?ChecksumAlgorithm = null,

    pub const json_field_names = .{
        .checksum = "Checksum",
        .checksum_algorithm = "ChecksumAlgorithm",
    };
};

pub const Options = struct {
    diagnostic: ?*ServiceError = null,
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: PutSnapshotBlockInput, options: Options) !PutSnapshotBlockOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(alloc);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "ebs");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: PutSnapshotBlockInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("ebs", "EBS", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    var path_buf: std.ArrayList(u8) = .{};
    try path_buf.appendSlice(allocator, "/snapshots/");
    try path_buf.appendSlice(allocator, input.snapshot_id);
    try path_buf.appendSlice(allocator, "/blocks/");
    try path_buf.appendSlice(allocator, input.block_index);
    const path = try path_buf.toOwnedSlice(allocator);

    const body = input.block_data;

    var request = aws.http.Request.init(host);
    request.method = .PUT;
    request.path = path;
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");
    try request.headers.put(allocator, "x-amz-Checksum", input.checksum);
    try request.headers.put(allocator, "x-amz-Checksum-Algorithm", @tagName(input.checksum_algorithm));
    {
        const num_str = std.fmt.allocPrint(allocator, "{d}", .{input.data_length}) catch "";
        try request.headers.put(allocator, "x-amz-Data-Length", num_str);
    }
    if (input.progress) |v| {
        {
            const num_str = std.fmt.allocPrint(allocator, "{d}", .{v}) catch "";
            try request.headers.put(allocator, "x-amz-Progress", num_str);
        }
    }

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !PutSnapshotBlockOutput {
    var result: PutSnapshotBlockOutput = .{};
    _ = body;
    _ = status;
    if (headers.get("x-amz-checksum")) |value| {
        result.checksum = try allocator.dupe(u8, value);
    }
    if (headers.get("x-amz-checksum-algorithm")) |value| {
        result.checksum_algorithm = std.meta.stringToEnum(ChecksumAlgorithm, value);
    }

    return result;
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AccessDeniedException")) {
        return .{ .arena = arena, .kind = .{ .access_denied_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConcurrentLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .concurrent_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConflictException")) {
        return .{ .arena = arena, .kind = .{ .conflict_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InternalServerException")) {
        return .{ .arena = arena, .kind = .{ .internal_server_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "RequestThrottledException")) {
        return .{ .arena = arena, .kind = .{ .request_throttled_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .resource_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ServiceQuotaExceededException")) {
        return .{ .arena = arena, .kind = .{ .service_quota_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ValidationException")) {
        return .{ .arena = arena, .kind = .{ .validation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
