pub const AccessCheckResourceType = enum {
    dynamodb_table,
    dynamodb_stream,
    efs_filesystem,
    opensearchservice_domain,
    kinesis_data_stream,
    kinesis_stream_consumer,
    kms_key,
    lambda_function,
    s3_bucket,
    s3_access_point,
    s3_express_directorybucket,
    s3_glacier,
    s3_outposts_bucket,
    s3_outposts_access_point,
    secretsmanager_secret,
    sns_topic,
    sqs_queue,
    role_trust,
    s3_table_bucket,
    api_gateway_rest_api,
    code_artifact_domain,
    backup_vault,
    cloudtrail_dashboard,
    cloudtrail_event_data_store,
    s3_table,
    s3_express_access_point,

    pub const json_field_names = .{
        .dynamodb_table = "DYNAMODB_TABLE",
        .dynamodb_stream = "DYNAMODB_STREAM",
        .efs_filesystem = "EFS_FILESYSTEM",
        .opensearchservice_domain = "OPENSEARCHSERVICE_DOMAIN",
        .kinesis_data_stream = "KINESIS_DATA_STREAM",
        .kinesis_stream_consumer = "KINESIS_STREAM_CONSUMER",
        .kms_key = "KMS_KEY",
        .lambda_function = "LAMBDA_FUNCTION",
        .s3_bucket = "S3_BUCKET",
        .s3_access_point = "S3_ACCESS_POINT",
        .s3_express_directorybucket = "S3EXPRESS_DIRECTORYBUCKET",
        .s3_glacier = "S3_GLACIER",
        .s3_outposts_bucket = "S3_OUTPOSTS_BUCKET",
        .s3_outposts_access_point = "S3_OUTPOSTS_ACCESS_POINT",
        .secretsmanager_secret = "SECRETSMANAGER_SECRET",
        .sns_topic = "SNS_TOPIC",
        .sqs_queue = "SQS_QUEUE",
        .role_trust = "ROLE_TRUST",
        .s3_table_bucket = "S3_TABLE_BUCKET",
        .api_gateway_rest_api = "API_GATEWAY_REST_API",
        .code_artifact_domain = "CODE_ARTIFACT_DOMAIN",
        .backup_vault = "BACKUP_VAULT",
        .cloudtrail_dashboard = "CLOUDTRAIL_DASHBOARD",
        .cloudtrail_event_data_store = "CLOUDTRAIL_EVENT_DATA_STORE",
        .s3_table = "S3_TABLE",
        .s3_express_access_point = "S3_EXPRESS_ACCESS_POINT",
    };
};
