pub const ResourceType = enum {
    aws_s3_bucket,
    aws_iam_role,
    aws_sqs_queue,
    aws_lambda_function,
    aws_lambda_layerversion,
    aws_kms_key,
    aws_secretsmanager_secret,
    aws_efs_filesystem,
    aws_ec2_snapshot,
    aws_ecr_repository,
    aws_rds_dbsnapshot,
    aws_rds_dbclustersnapshot,
    aws_sns_topic,
    aws_s3_express_directorybucket,
    aws_dynamodb_table,
    aws_dynamodb_stream,
    aws_iam_user,

    pub const json_field_names = .{
        .aws_s3_bucket = "AWS_S3_BUCKET",
        .aws_iam_role = "AWS_IAM_ROLE",
        .aws_sqs_queue = "AWS_SQS_QUEUE",
        .aws_lambda_function = "AWS_LAMBDA_FUNCTION",
        .aws_lambda_layerversion = "AWS_LAMBDA_LAYERVERSION",
        .aws_kms_key = "AWS_KMS_KEY",
        .aws_secretsmanager_secret = "AWS_SECRETSMANAGER_SECRET",
        .aws_efs_filesystem = "AWS_EFS_FILESYSTEM",
        .aws_ec2_snapshot = "AWS_EC2_SNAPSHOT",
        .aws_ecr_repository = "AWS_ECR_REPOSITORY",
        .aws_rds_dbsnapshot = "AWS_RDS_DBSNAPSHOT",
        .aws_rds_dbclustersnapshot = "AWS_RDS_DBCLUSTERSNAPSHOT",
        .aws_sns_topic = "AWS_SNS_TOPIC",
        .aws_s3_express_directorybucket = "AWS_S3EXPRESS_DIRECTORYBUCKET",
        .aws_dynamodb_table = "AWS_DYNAMODB_TABLE",
        .aws_dynamodb_stream = "AWS_DYNAMODB_STREAM",
        .aws_iam_user = "AWS_IAM_USER",
    };
};
