pub const ActionConnectorType = enum {
    generic_http,
    servicenow_now_platform,
    salesforce_crm,
    microsoft_outlook,
    pagerduty_advance,
    jira_cloud,
    atlassian_confluence,
    amazon_s3,
    amazon_bedrock_agent_runtime,
    amazon_bedrock_runtime,
    amazon_bedrock_data_automation_runtime,
    amazon_textract,
    amazon_comprehend,
    amazon_comprehend_medical,
    microsoft_onedrive,
    microsoft_sharepoint,
    microsoft_teams,
    sap_businesspartner,
    sap_productmasterdata,
    sap_physicalinventory,
    sap_billofmaterials,
    sap_materialstock,
    zendesk_suite,
    smartsheet,
    slack,
    asana,
    bamboo_hr,

    pub const json_field_names = .{
        .generic_http = "GENERIC_HTTP",
        .servicenow_now_platform = "SERVICENOW_NOW_PLATFORM",
        .salesforce_crm = "SALESFORCE_CRM",
        .microsoft_outlook = "MICROSOFT_OUTLOOK",
        .pagerduty_advance = "PAGERDUTY_ADVANCE",
        .jira_cloud = "JIRA_CLOUD",
        .atlassian_confluence = "ATLASSIAN_CONFLUENCE",
        .amazon_s3 = "AMAZON_S3",
        .amazon_bedrock_agent_runtime = "AMAZON_BEDROCK_AGENT_RUNTIME",
        .amazon_bedrock_runtime = "AMAZON_BEDROCK_RUNTIME",
        .amazon_bedrock_data_automation_runtime = "AMAZON_BEDROCK_DATA_AUTOMATION_RUNTIME",
        .amazon_textract = "AMAZON_TEXTRACT",
        .amazon_comprehend = "AMAZON_COMPREHEND",
        .amazon_comprehend_medical = "AMAZON_COMPREHEND_MEDICAL",
        .microsoft_onedrive = "MICROSOFT_ONEDRIVE",
        .microsoft_sharepoint = "MICROSOFT_SHAREPOINT",
        .microsoft_teams = "MICROSOFT_TEAMS",
        .sap_businesspartner = "SAP_BUSINESSPARTNER",
        .sap_productmasterdata = "SAP_PRODUCTMASTERDATA",
        .sap_physicalinventory = "SAP_PHYSICALINVENTORY",
        .sap_billofmaterials = "SAP_BILLOFMATERIALS",
        .sap_materialstock = "SAP_MATERIALSTOCK",
        .zendesk_suite = "ZENDESK_SUITE",
        .smartsheet = "SMARTSHEET",
        .slack = "SLACK",
        .asana = "ASANA",
        .bamboo_hr = "BAMBOO_HR",
    };
};
