pub const AssetBundleExportJobDataSourcePropertyToOverride = enum {
    name,
    disable_ssl,
    secret_arn,
    username,
    password,
    domain,
    work_group,
    host,
    port,
    database,
    data_set_name,
    catalog,
    instance_id,
    cluster_id,
    manifest_file_location,
    warehouse,
    role_arn,
    product_type,

    pub const json_field_names = .{
        .name = "NAME",
        .disable_ssl = "DISABLE_SSL",
        .secret_arn = "SECRET_ARN",
        .username = "USERNAME",
        .password = "PASSWORD",
        .domain = "DOMAIN",
        .work_group = "WORK_GROUP",
        .host = "HOST",
        .port = "PORT",
        .database = "DATABASE",
        .data_set_name = "DATA_SET_NAME",
        .catalog = "CATALOG",
        .instance_id = "INSTANCE_ID",
        .cluster_id = "CLUSTER_ID",
        .manifest_file_location = "MANIFEST_FILE_LOCATION",
        .warehouse = "WAREHOUSE",
        .role_arn = "ROLE_ARN",
        .product_type = "PRODUCT_TYPE",
    };
};
