pub const DataSourceType = enum {
    adobe_analytics,
    amazon_elasticsearch,
    athena,
    aurora,
    aurora_postgresql,
    aws_iot_analytics,
    github,
    jira,
    mariadb,
    mysql,
    oracle,
    postgresql,
    presto,
    redshift,
    s3,
    salesforce,
    servicenow,
    snowflake,
    spark,
    sqlserver,
    teradata,
    twitter,
    timestream,
    amazon_opensearch,
    exasol,
    databricks,
    starburst,
    trino,
    bigquery,
    googlesheets,
    google_drive,
    confluence,
    sharepoint,
    one_drive,
    web_crawler,
    s3_knowledge_base,
    qbusiness,

    pub const json_field_names = .{
        .adobe_analytics = "ADOBE_ANALYTICS",
        .amazon_elasticsearch = "AMAZON_ELASTICSEARCH",
        .athena = "ATHENA",
        .aurora = "AURORA",
        .aurora_postgresql = "AURORA_POSTGRESQL",
        .aws_iot_analytics = "AWS_IOT_ANALYTICS",
        .github = "GITHUB",
        .jira = "JIRA",
        .mariadb = "MARIADB",
        .mysql = "MYSQL",
        .oracle = "ORACLE",
        .postgresql = "POSTGRESQL",
        .presto = "PRESTO",
        .redshift = "REDSHIFT",
        .s3 = "S3",
        .salesforce = "SALESFORCE",
        .servicenow = "SERVICENOW",
        .snowflake = "SNOWFLAKE",
        .spark = "SPARK",
        .sqlserver = "SQLSERVER",
        .teradata = "TERADATA",
        .twitter = "TWITTER",
        .timestream = "TIMESTREAM",
        .amazon_opensearch = "AMAZON_OPENSEARCH",
        .exasol = "EXASOL",
        .databricks = "DATABRICKS",
        .starburst = "STARBURST",
        .trino = "TRINO",
        .bigquery = "BIGQUERY",
        .googlesheets = "GOOGLESHEETS",
        .google_drive = "GOOGLE_DRIVE",
        .confluence = "CONFLUENCE",
        .sharepoint = "SHAREPOINT",
        .one_drive = "ONE_DRIVE",
        .web_crawler = "WEB_CRAWLER",
        .s3_knowledge_base = "S3_KNOWLEDGE_BASE",
        .qbusiness = "QBUSINESS",
    };
};
