const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const AutomationJobStatus = @import("automation_job_status.zig").AutomationJobStatus;

pub const DescribeAutomationJobInput = struct {
    /// The ID of the automation group that contains the automation.
    automation_group_id: []const u8,

    /// The ID of the automation that the job belongs to.
    automation_id: []const u8,

    /// The ID of the Amazon Web Services account that contains the automation job.
    aws_account_id: []const u8,

    /// A Boolean value that indicates whether to include the input payload in the
    /// response. If set to `true`, the input payload will be included. If set to
    /// `false`, the input payload will be returned as `null`.
    include_input_payload: ?bool = null,

    /// A Boolean value that indicates whether to include the output payload in the
    /// response. If set to `true`, the output payload will be included. If set to
    /// `false`, the output payload will be returned as `null`.
    include_output_payload: ?bool = null,

    /// The ID of the automation job to describe.
    job_id: []const u8,

    pub const json_field_names = .{
        .automation_group_id = "AutomationGroupId",
        .automation_id = "AutomationId",
        .aws_account_id = "AwsAccountId",
        .include_input_payload = "IncludeInputPayload",
        .include_output_payload = "IncludeOutputPayload",
        .job_id = "JobId",
    };
};

pub const DescribeAutomationJobOutput = struct {
    /// The Amazon Resource Name (ARN) of the automation job.
    arn: []const u8,

    /// The time that the automation job was created.
    created_at: ?i64 = null,

    /// The time that the automation job finished running.
    ended_at: ?i64 = null,

    /// The input payload that was provided when the automation job was started.
    /// This field is only included when `IncludeInputPayload` is set to `true` in
    /// the request.
    input_payload: ?[]const u8 = null,

    /// The current status of the automation job.
    job_status: AutomationJobStatus,

    /// The output payload that was generated by the automation job. This field is
    /// only included when `IncludeOutputPayload` is set to `true` in the request.
    output_payload: ?[]const u8 = null,

    /// The Amazon Web Services request ID for this operation.
    request_id: ?[]const u8 = null,

    /// The time that the automation job started running.
    started_at: ?i64 = null,

    pub const json_field_names = .{
        .arn = "Arn",
        .created_at = "CreatedAt",
        .ended_at = "EndedAt",
        .input_payload = "InputPayload",
        .job_status = "JobStatus",
        .output_payload = "OutputPayload",
        .request_id = "RequestId",
        .started_at = "StartedAt",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: DescribeAutomationJobInput, options: CallOptions) !DescribeAutomationJobOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "quicksight", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: DescribeAutomationJobInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("quicksight", "QuickSight", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/accounts/");
    try path_buf.appendSlice(allocator, input.aws_account_id);
    try path_buf.appendSlice(allocator, "/automation-groups/");
    try path_buf.appendSlice(allocator, input.automation_group_id);
    try path_buf.appendSlice(allocator, "/automations/");
    try path_buf.appendSlice(allocator, input.automation_id);
    try path_buf.appendSlice(allocator, "/jobs/");
    try path_buf.appendSlice(allocator, input.job_id);
    const path = try path_buf.toOwnedSlice(allocator);

    var query_buf: std.ArrayList(u8) = .empty;
    var query_has_prev = false;
    if (input.include_input_payload) |v| {
        if (query_has_prev) try query_buf.appendSlice(allocator, "&");
        try query_buf.appendSlice(allocator, "includeInputPayload=");
        try query_buf.appendSlice(allocator, if (v) "true" else "false");
        query_has_prev = true;
    }
    if (input.include_output_payload) |v| {
        if (query_has_prev) try query_buf.appendSlice(allocator, "&");
        try query_buf.appendSlice(allocator, "includeOutputPayload=");
        try query_buf.appendSlice(allocator, if (v) "true" else "false");
        query_has_prev = true;
    }
    const query = try query_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(ep.host);
    request.method = .GET;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    request.query = query;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !DescribeAutomationJobOutput {
    const result: DescribeAutomationJobOutput = try aws.json.parseJsonObject(
        DescribeAutomationJobOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
