pub const Icon = enum {
    caret_up,
    caret_down,
    plus,
    minus,
    arrow_up,
    arrow_down,
    arrow_left,
    arrow_up_left,
    arrow_down_left,
    arrow_right,
    arrow_up_right,
    arrow_down_right,
    face_up,
    face_down,
    face_flat,
    one_bar,
    two_bar,
    three_bar,
    circle,
    triangle,
    square,
    flag,
    thumbs_up,
    thumbs_down,
    checkmark,
    x,

    pub const json_field_names = .{
        .caret_up = "CARET_UP",
        .caret_down = "CARET_DOWN",
        .plus = "PLUS",
        .minus = "MINUS",
        .arrow_up = "ARROW_UP",
        .arrow_down = "ARROW_DOWN",
        .arrow_left = "ARROW_LEFT",
        .arrow_up_left = "ARROW_UP_LEFT",
        .arrow_down_left = "ARROW_DOWN_LEFT",
        .arrow_right = "ARROW_RIGHT",
        .arrow_up_right = "ARROW_UP_RIGHT",
        .arrow_down_right = "ARROW_DOWN_RIGHT",
        .face_up = "FACE_UP",
        .face_down = "FACE_DOWN",
        .face_flat = "FACE_FLAT",
        .one_bar = "ONE_BAR",
        .two_bar = "TWO_BAR",
        .three_bar = "THREE_BAR",
        .circle = "CIRCLE",
        .triangle = "TRIANGLE",
        .square = "SQUARE",
        .flag = "FLAG",
        .thumbs_up = "THUMBS_UP",
        .thumbs_down = "THUMBS_DOWN",
        .checkmark = "CHECKMARK",
        .x = "X",
    };
};
