const RecommendationCategory = @import("recommendation_category.zig").RecommendationCategory;
const RuleMetadata = @import("rule_metadata.zig").RuleMetadata;
const Severity = @import("severity.zig").Severity;

/// Information about recommendations.
pub const RecommendationSummary = struct {
    /// A description of the recommendation generated by CodeGuru Reviewer for the
    /// lines of code between
    /// the start line and the end line.
    description: ?[]const u8,

    /// Last line where the recommendation is applicable in the source commit or
    /// source branch.
    /// For a single line comment the start line and end line values are the same.
    end_line: ?i32,

    /// Name of the file on which a recommendation is provided.
    file_path: ?[]const u8,

    /// The type of a recommendation.
    recommendation_category: ?RecommendationCategory,

    /// The recommendation ID that can be used to track the provided
    /// recommendations. Later on
    /// it can be used to collect the feedback.
    recommendation_id: ?[]const u8,

    /// Metadata about a rule. Rule metadata includes an ID, a name, a list of tags,
    /// and a short and long description. CodeGuru Reviewer uses rules to analyze
    /// code. A rule's recommendation is included in analysis results if code is
    /// detected that violates the rule.
    rule_metadata: ?RuleMetadata,

    /// The severity of the issue in the code that generated this recommendation.
    severity: ?Severity,

    /// Start line from where the recommendation is applicable in the source commit
    /// or source
    /// branch.
    start_line: ?i32,

    pub const json_field_names = .{
        .description = "Description",
        .end_line = "EndLine",
        .file_path = "FilePath",
        .recommendation_category = "RecommendationCategory",
        .recommendation_id = "RecommendationId",
        .rule_metadata = "RuleMetadata",
        .severity = "Severity",
        .start_line = "StartLine",
    };
};
