const DocumentationPartLocation = @import("documentation_part_location.zig").DocumentationPartLocation;

/// A documentation part for a targeted API entity.
pub const DocumentationPart = struct {
    /// The DocumentationPart identifier, generated by API Gateway when the
    /// `DocumentationPart` is created.
    id: ?[]const u8,

    /// The location of the API entity to which the documentation applies. Valid
    /// fields depend on the targeted API entity type. All the valid location fields
    /// are not required. If not explicitly specified, a valid location field is
    /// treated as a wildcard and associated documentation content may be inherited
    /// by matching entities, unless overridden.
    location: ?DocumentationPartLocation,

    /// A content map of API-specific key-value pairs describing the targeted API
    /// entity. The map must be encoded as a JSON string, e.g., `"{ \"description\":
    /// \"The API does ...\" }"`. Only OpenAPI-compliant documentation-related
    /// fields from the properties map are exported and, hence, published as part of
    /// the API entity definitions, while the original documentation parts are
    /// exported in a OpenAPI extension of `x-amazon-apigateway-documentation`.
    properties: ?[]const u8,

    pub const json_field_names = .{
        .id = "id",
        .location = "location",
        .properties = "properties",
    };
};
