const aws = @import("aws");

const GatewayResponseType = @import("gateway_response_type.zig").GatewayResponseType;

/// A gateway response of a given response type and status code, with optional
/// response parameters and mapping templates.
pub const GatewayResponse = struct {
    /// A Boolean flag to indicate whether this GatewayResponse is the default
    /// gateway response (`true`) or not (`false`). A default gateway response is
    /// one generated by API Gateway without any customization by an API developer.
    default_response: bool = false,

    /// Response parameters (paths, query strings and headers) of the
    /// GatewayResponse as a
    /// string-to-string map of key-value pairs.
    response_parameters: ?[]const aws.map.StringMapEntry = null,

    /// Response templates of the GatewayResponse as a string-to-string map of
    /// key-value pairs.
    response_templates: ?[]const aws.map.StringMapEntry = null,

    /// The response type of the associated GatewayResponse.
    response_type: ?GatewayResponseType = null,

    /// The HTTP status code for this GatewayResponse.
    status_code: ?[]const u8 = null,

    pub const json_field_names = .{
        .default_response = "defaultResponse",
        .response_parameters = "responseParameters",
        .response_templates = "responseTemplates",
        .response_type = "responseType",
        .status_code = "statusCode",
    };
};
