/// The region of the S3 bucket that Amazon Web Services delivers the report
/// into.
pub const AWSRegion = enum {
    cape_town,
    hong_kong,
    mumbai,
    hyderabad,
    singapore,
    sydney,
    jakarta,
    tokyo,
    seoul,
    osaka,
    canada_central,
    frankfurt,
    zurich,
    ireland,
    london,
    paris,
    stockholm,
    milano,
    spain,
    uae,
    bahrain,
    sao_paulo,
    us_standard,
    ohio,
    northern_california,
    oregon,
    beijing,
    ningxia,

    pub const json_field_names = .{
        .cape_town = "CAPE_TOWN",
        .hong_kong = "HONG_KONG",
        .mumbai = "MUMBAI",
        .hyderabad = "HYDERABAD",
        .singapore = "SINGAPORE",
        .sydney = "SYDNEY",
        .jakarta = "JAKARTA",
        .tokyo = "TOKYO",
        .seoul = "SEOUL",
        .osaka = "OSAKA",
        .canada_central = "CANADA_CENTRAL",
        .frankfurt = "FRANKFURT",
        .zurich = "ZURICH",
        .ireland = "IRELAND",
        .london = "LONDON",
        .paris = "PARIS",
        .stockholm = "STOCKHOLM",
        .milano = "MILANO",
        .spain = "SPAIN",
        .uae = "UAE",
        .bahrain = "BAHRAIN",
        .sao_paulo = "SAO_PAULO",
        .us_standard = "US_STANDARD",
        .ohio = "OHIO",
        .northern_california = "NORTHERN_CALIFORNIA",
        .oregon = "OREGON",
        .beijing = "BEIJING",
        .ningxia = "NINGXIA",
    };
};
