pub const RecommendationType = enum {
    knowledge_content,
    generative_response,
    generative_answer,
    detected_intent,
    generative_answer_chunk,
    blocked_generative_answer_chunk,
    intent_answer_chunk,
    blocked_intent_answer_chunk,
    email_response_chunk,
    email_overview_chunk,
    email_generative_answer_chunk,
    case_summarization_chunk,
    blocked_case_summarization_chunk,
    suggested_message,
    notes_chunk,
    blocked_notes_chunk,

    pub const json_field_names = .{
        .knowledge_content = "KNOWLEDGE_CONTENT",
        .generative_response = "GENERATIVE_RESPONSE",
        .generative_answer = "GENERATIVE_ANSWER",
        .detected_intent = "DETECTED_INTENT",
        .generative_answer_chunk = "GENERATIVE_ANSWER_CHUNK",
        .blocked_generative_answer_chunk = "BLOCKED_GENERATIVE_ANSWER_CHUNK",
        .intent_answer_chunk = "INTENT_ANSWER_CHUNK",
        .blocked_intent_answer_chunk = "BLOCKED_INTENT_ANSWER_CHUNK",
        .email_response_chunk = "EMAIL_RESPONSE_CHUNK",
        .email_overview_chunk = "EMAIL_OVERVIEW_CHUNK",
        .email_generative_answer_chunk = "EMAIL_GENERATIVE_ANSWER_CHUNK",
        .case_summarization_chunk = "CASE_SUMMARIZATION_CHUNK",
        .blocked_case_summarization_chunk = "BLOCKED_CASE_SUMMARIZATION_CHUNK",
        .suggested_message = "SUGGESTED_MESSAGE",
        .notes_chunk = "NOTES_CHUNK",
        .blocked_notes_chunk = "BLOCKED_NOTES_CHUNK",
    };
};
