pub const InvalidInputExceptionReason = enum {
    invalid_party_type_target,
    invalid_syntax_organization,
    invalid_syntax_policy,
    invalid_enum,
    invalid_enum_policy_type,
    invalid_list_member,
    max_length_exceeded,
    max_value_exceeded,
    min_length_exceeded,
    min_value_exceeded,
    immutable_policy,
    invalid_pattern,
    invalid_pattern_target_id,
    input_required,
    invalid_pagination_token,
    max_filter_limit_exceeded,
    moving_account_between_different_roots,
    invalid_full_name_target,
    unrecognized_service_principal,
    invalid_role_name,
    invalid_system_tags_parameter,
    duplicate_tag_key,
    target_not_supported,
    invalid_email_address_target,
    invalid_resource_policy_json,
    invalid_principal,
    unsupported_action_in_resource_policy,
    unsupported_policy_type_in_resource_policy,
    unsupported_resource_in_resource_policy,
    non_detachable_policy,
    caller_required_field_missing,
    unsupported_action_in_responsibility_transfer,
    start_date_not_beginning_of_month,
    start_date_not_beginning_of_day,
    start_date_too_early,
    start_date_too_late,
    invalid_start_date,
    end_date_not_end_of_month,
    end_date_too_early,
    invalid_end_date,

    pub const json_field_names = .{
        .invalid_party_type_target = "INVALID_PARTY_TYPE_TARGET",
        .invalid_syntax_organization = "INVALID_SYNTAX_ORGANIZATION",
        .invalid_syntax_policy = "INVALID_SYNTAX_POLICY",
        .invalid_enum = "INVALID_ENUM",
        .invalid_enum_policy_type = "INVALID_ENUM_POLICY_TYPE",
        .invalid_list_member = "INVALID_LIST_MEMBER",
        .max_length_exceeded = "MAX_LENGTH_EXCEEDED",
        .max_value_exceeded = "MAX_VALUE_EXCEEDED",
        .min_length_exceeded = "MIN_LENGTH_EXCEEDED",
        .min_value_exceeded = "MIN_VALUE_EXCEEDED",
        .immutable_policy = "IMMUTABLE_POLICY",
        .invalid_pattern = "INVALID_PATTERN",
        .invalid_pattern_target_id = "INVALID_PATTERN_TARGET_ID",
        .input_required = "INPUT_REQUIRED",
        .invalid_pagination_token = "INVALID_PAGINATION_TOKEN",
        .max_filter_limit_exceeded = "MAX_FILTER_LIMIT_EXCEEDED",
        .moving_account_between_different_roots = "MOVING_ACCOUNT_BETWEEN_DIFFERENT_ROOTS",
        .invalid_full_name_target = "INVALID_FULL_NAME_TARGET",
        .unrecognized_service_principal = "UNRECOGNIZED_SERVICE_PRINCIPAL",
        .invalid_role_name = "INVALID_ROLE_NAME",
        .invalid_system_tags_parameter = "INVALID_SYSTEM_TAGS_PARAMETER",
        .duplicate_tag_key = "DUPLICATE_TAG_KEY",
        .target_not_supported = "TARGET_NOT_SUPPORTED",
        .invalid_email_address_target = "INVALID_EMAIL_ADDRESS_TARGET",
        .invalid_resource_policy_json = "INVALID_RESOURCE_POLICY_JSON",
        .invalid_principal = "INVALID_PRINCIPAL",
        .unsupported_action_in_resource_policy = "UNSUPPORTED_ACTION_IN_RESOURCE_POLICY",
        .unsupported_policy_type_in_resource_policy = "UNSUPPORTED_POLICY_TYPE_IN_RESOURCE_POLICY",
        .unsupported_resource_in_resource_policy = "UNSUPPORTED_RESOURCE_IN_RESOURCE_POLICY",
        .non_detachable_policy = "NON_DETACHABLE_POLICY",
        .caller_required_field_missing = "CALLER_REQUIRED_FIELD_MISSING",
        .unsupported_action_in_responsibility_transfer = "UNSUPPORTED_ACTION_IN_RESPONSIBILITY_TRANSFER",
        .start_date_not_beginning_of_month = "START_DATE_NOT_BEGINNING_OF_MONTH",
        .start_date_not_beginning_of_day = "START_DATE_NOT_BEGINNING_OF_DAY",
        .start_date_too_early = "START_DATE_TOO_EARLY",
        .start_date_too_late = "START_DATE_TOO_LATE",
        .invalid_start_date = "INVALID_START_DATE",
        .end_date_not_end_of_month = "END_DATE_NOT_END_OF_MONTH",
        .end_date_too_early = "END_DATE_TOO_EARLY",
        .invalid_end_date = "INVALID_END_DATE",
    };
};
