pub const PolicyType = enum {
    service_control_policy,
    resource_control_policy,
    tag_policy,
    backup_policy,
    aiservices_opt_out_policy,
    chatbot_policy,
    declarative_policy_ec2,
    securityhub_policy,
    inspector_policy,
    upgrade_rollout_policy,
    bedrock_policy,
    s3_policy,
    network_security_director_policy,

    pub const json_field_names = .{
        .service_control_policy = "SERVICE_CONTROL_POLICY",
        .resource_control_policy = "RESOURCE_CONTROL_POLICY",
        .tag_policy = "TAG_POLICY",
        .backup_policy = "BACKUP_POLICY",
        .aiservices_opt_out_policy = "AISERVICES_OPT_OUT_POLICY",
        .chatbot_policy = "CHATBOT_POLICY",
        .declarative_policy_ec2 = "DECLARATIVE_POLICY_EC2",
        .securityhub_policy = "SECURITYHUB_POLICY",
        .inspector_policy = "INSPECTOR_POLICY",
        .upgrade_rollout_policy = "UPGRADE_ROLLOUT_POLICY",
        .bedrock_policy = "BEDROCK_POLICY",
        .s3_policy = "S3_POLICY",
        .network_security_director_policy = "NETWORK_SECURITY_DIRECTOR_POLICY",
    };
};
