pub const UlimitName = enum {
    core,
    cpu,
    data,
    fsize,
    locks,
    memlock,
    msgqueue,
    nice,
    nofile,
    nproc,
    rss,
    rtprio,
    rttime,
    sigpending,
    stack,

    pub const json_field_names = .{
        .core = "CORE",
        .cpu = "CPU",
        .data = "DATA",
        .fsize = "FSIZE",
        .locks = "LOCKS",
        .memlock = "MEMLOCK",
        .msgqueue = "MSGQUEUE",
        .nice = "NICE",
        .nofile = "NOFILE",
        .nproc = "NPROC",
        .rss = "RSS",
        .rtprio = "RTPRIO",
        .rttime = "RTTIME",
        .sigpending = "SIGPENDING",
        .stack = "STACK",
    };
};
