pub const HeaderEnum = enum {
    accept,
    accept_charset,
    accept_datetime,
    accept_encoding,
    accept_language,
    authorization,
    cloud_front_forwarded_proto,
    cloud_front_is_desktop_viewer,
    cloud_front_is_mobile_viewer,
    cloud_front_is_smart_tv_viewer,
    cloud_front_is_tablet_viewer,
    cloud_front_viewer_country,
    host,
    origin,
    referer,

    pub const json_field_names = .{
        .accept = "accept",
        .accept_charset = "acceptCharset",
        .accept_datetime = "acceptDatetime",
        .accept_encoding = "acceptEncoding",
        .accept_language = "acceptLanguage",
        .authorization = "authorization",
        .cloud_front_forwarded_proto = "cloudFrontForwardedProto",
        .cloud_front_is_desktop_viewer = "cloudFrontIsDesktopViewer",
        .cloud_front_is_mobile_viewer = "cloudFrontIsMobileViewer",
        .cloud_front_is_smart_tv_viewer = "cloudFrontIsSmartTVViewer",
        .cloud_front_is_tablet_viewer = "cloudFrontIsTabletViewer",
        .cloud_front_viewer_country = "cloudFrontViewerCountry",
        .host = "host",
        .origin = "origin",
        .referer = "referer",
    };
};
