pub const MetricUnit = enum {
    seconds,
    microseconds,
    milliseconds,
    bytes,
    kilobytes,
    megabytes,
    gigabytes,
    terabytes,
    bits,
    kilobits,
    megabits,
    gigabits,
    terabits,
    percent,
    count,
    bytes_second,
    kilobytes_second,
    megabytes_second,
    gigabytes_second,
    terabytes_second,
    bits_second,
    kilobits_second,
    megabits_second,
    gigabits_second,
    terabits_second,
    count_second,
    none,

    pub const json_field_names = .{
        .seconds = "Seconds",
        .microseconds = "Microseconds",
        .milliseconds = "Milliseconds",
        .bytes = "Bytes",
        .kilobytes = "Kilobytes",
        .megabytes = "Megabytes",
        .gigabytes = "Gigabytes",
        .terabytes = "Terabytes",
        .bits = "Bits",
        .kilobits = "Kilobits",
        .megabits = "Megabits",
        .gigabits = "Gigabits",
        .terabits = "Terabits",
        .percent = "Percent",
        .count = "Count",
        .bytes_second = "BytesSecond",
        .kilobytes_second = "KilobytesSecond",
        .megabytes_second = "MegabytesSecond",
        .gigabytes_second = "GigabytesSecond",
        .terabytes_second = "TerabytesSecond",
        .bits_second = "BitsSecond",
        .kilobits_second = "KilobitsSecond",
        .megabits_second = "MegabitsSecond",
        .gigabits_second = "GigabitsSecond",
        .terabits_second = "TerabitsSecond",
        .count_second = "CountSecond",
        .none = "None",
    };
};
