pub const MetricName = enum {
    cpu_utilization,
    network_in,
    network_out,
    status_check_failed,
    status_check_failed_instance,
    status_check_failed_system,
    client_tls_negotiation_error_count,
    healthy_host_count,
    unhealthy_host_count,
    http_code_lb_4_xx_count,
    http_code_lb_5_xx_count,
    http_code_instance_2_xx_count,
    http_code_instance_3_xx_count,
    http_code_instance_4_xx_count,
    http_code_instance_5_xx_count,
    instance_response_time,
    rejected_connection_count,
    request_count,
    database_connections,
    disk_queue_depth,
    free_storage_space,
    network_receive_throughput,
    network_transmit_throughput,
    burst_capacity_time,
    burst_capacity_percentage,

    pub const json_field_names = .{
        .cpu_utilization = "CPUUtilization",
        .network_in = "NetworkIn",
        .network_out = "NetworkOut",
        .status_check_failed = "StatusCheckFailed",
        .status_check_failed_instance = "StatusCheckFailed_Instance",
        .status_check_failed_system = "StatusCheckFailed_System",
        .client_tls_negotiation_error_count = "ClientTLSNegotiationErrorCount",
        .healthy_host_count = "HealthyHostCount",
        .unhealthy_host_count = "UnhealthyHostCount",
        .http_code_lb_4_xx_count = "HTTPCode_LB_4XX_Count",
        .http_code_lb_5_xx_count = "HTTPCode_LB_5XX_Count",
        .http_code_instance_2_xx_count = "HTTPCode_Instance_2XX_Count",
        .http_code_instance_3_xx_count = "HTTPCode_Instance_3XX_Count",
        .http_code_instance_4_xx_count = "HTTPCode_Instance_4XX_Count",
        .http_code_instance_5_xx_count = "HTTPCode_Instance_5XX_Count",
        .instance_response_time = "InstanceResponseTime",
        .rejected_connection_count = "RejectedConnectionCount",
        .request_count = "RequestCount",
        .database_connections = "DatabaseConnections",
        .disk_queue_depth = "DiskQueueDepth",
        .free_storage_space = "FreeStorageSpace",
        .network_receive_throughput = "NetworkReceiveThroughput",
        .network_transmit_throughput = "NetworkTransmitThroughput",
        .burst_capacity_time = "BurstCapacityTime",
        .burst_capacity_percentage = "BurstCapacityPercentage",
    };
};
