const std = @import("std");

pub const OperationType = enum {
    delete_known_host_keys,
    delete_instance,
    create_instance,
    stop_instance,
    start_instance,
    reboot_instance,
    open_instance_public_ports,
    put_instance_public_ports,
    close_instance_public_ports,
    allocate_static_ip,
    release_static_ip,
    attach_static_ip,
    detach_static_ip,
    update_domain_entry,
    delete_domain_entry,
    create_domain,
    delete_domain,
    create_instance_snapshot,
    delete_instance_snapshot,
    create_instances_from_snapshot,
    create_load_balancer,
    delete_load_balancer,
    attach_instances_to_load_balancer,
    detach_instances_from_load_balancer,
    update_load_balancer_attribute,
    create_load_balancer_tls_certificate,
    delete_load_balancer_tls_certificate,
    attach_load_balancer_tls_certificate,
    create_disk,
    delete_disk,
    attach_disk,
    detach_disk,
    create_disk_snapshot,
    delete_disk_snapshot,
    create_disk_from_snapshot,
    create_relational_database,
    update_relational_database,
    delete_relational_database,
    create_relational_database_from_snapshot,
    create_relational_database_snapshot,
    delete_relational_database_snapshot,
    update_relational_database_parameters,
    start_relational_database,
    reboot_relational_database,
    stop_relational_database,
    enable_add_on,
    disable_add_on,
    put_alarm,
    get_alarms,
    delete_alarm,
    test_alarm,
    create_contact_method,
    get_contact_methods,
    send_contact_method_verification,
    delete_contact_method,
    create_distribution,
    update_distribution,
    delete_distribution,
    reset_distribution_cache,
    attach_certificate_to_distribution,
    detach_certificate_from_distribution,
    update_distribution_bundle,
    set_ip_address_type,
    create_certificate,
    delete_certificate,
    create_container_service,
    update_container_service,
    delete_container_service,
    create_container_service_deployment,
    create_container_service_registry_login,
    register_container_image,
    delete_container_image,
    create_bucket,
    delete_bucket,
    create_bucket_access_key,
    delete_bucket_access_key,
    update_bucket_bundle,
    update_bucket,
    set_resource_access_for_bucket,
    update_instance_metadata_options,
    start_gui_session,
    stop_gui_session,
    setup_instance_https,

    pub const json_field_names = .{
        .delete_known_host_keys = "DeleteKnownHostKeys",
        .delete_instance = "DeleteInstance",
        .create_instance = "CreateInstance",
        .stop_instance = "StopInstance",
        .start_instance = "StartInstance",
        .reboot_instance = "RebootInstance",
        .open_instance_public_ports = "OpenInstancePublicPorts",
        .put_instance_public_ports = "PutInstancePublicPorts",
        .close_instance_public_ports = "CloseInstancePublicPorts",
        .allocate_static_ip = "AllocateStaticIp",
        .release_static_ip = "ReleaseStaticIp",
        .attach_static_ip = "AttachStaticIp",
        .detach_static_ip = "DetachStaticIp",
        .update_domain_entry = "UpdateDomainEntry",
        .delete_domain_entry = "DeleteDomainEntry",
        .create_domain = "CreateDomain",
        .delete_domain = "DeleteDomain",
        .create_instance_snapshot = "CreateInstanceSnapshot",
        .delete_instance_snapshot = "DeleteInstanceSnapshot",
        .create_instances_from_snapshot = "CreateInstancesFromSnapshot",
        .create_load_balancer = "CreateLoadBalancer",
        .delete_load_balancer = "DeleteLoadBalancer",
        .attach_instances_to_load_balancer = "AttachInstancesToLoadBalancer",
        .detach_instances_from_load_balancer = "DetachInstancesFromLoadBalancer",
        .update_load_balancer_attribute = "UpdateLoadBalancerAttribute",
        .create_load_balancer_tls_certificate = "CreateLoadBalancerTlsCertificate",
        .delete_load_balancer_tls_certificate = "DeleteLoadBalancerTlsCertificate",
        .attach_load_balancer_tls_certificate = "AttachLoadBalancerTlsCertificate",
        .create_disk = "CreateDisk",
        .delete_disk = "DeleteDisk",
        .attach_disk = "AttachDisk",
        .detach_disk = "DetachDisk",
        .create_disk_snapshot = "CreateDiskSnapshot",
        .delete_disk_snapshot = "DeleteDiskSnapshot",
        .create_disk_from_snapshot = "CreateDiskFromSnapshot",
        .create_relational_database = "CreateRelationalDatabase",
        .update_relational_database = "UpdateRelationalDatabase",
        .delete_relational_database = "DeleteRelationalDatabase",
        .create_relational_database_from_snapshot = "CreateRelationalDatabaseFromSnapshot",
        .create_relational_database_snapshot = "CreateRelationalDatabaseSnapshot",
        .delete_relational_database_snapshot = "DeleteRelationalDatabaseSnapshot",
        .update_relational_database_parameters = "UpdateRelationalDatabaseParameters",
        .start_relational_database = "StartRelationalDatabase",
        .reboot_relational_database = "RebootRelationalDatabase",
        .stop_relational_database = "StopRelationalDatabase",
        .enable_add_on = "EnableAddOn",
        .disable_add_on = "DisableAddOn",
        .put_alarm = "PutAlarm",
        .get_alarms = "GetAlarms",
        .delete_alarm = "DeleteAlarm",
        .test_alarm = "TestAlarm",
        .create_contact_method = "CreateContactMethod",
        .get_contact_methods = "GetContactMethods",
        .send_contact_method_verification = "SendContactMethodVerification",
        .delete_contact_method = "DeleteContactMethod",
        .create_distribution = "CreateDistribution",
        .update_distribution = "UpdateDistribution",
        .delete_distribution = "DeleteDistribution",
        .reset_distribution_cache = "ResetDistributionCache",
        .attach_certificate_to_distribution = "AttachCertificateToDistribution",
        .detach_certificate_from_distribution = "DetachCertificateFromDistribution",
        .update_distribution_bundle = "UpdateDistributionBundle",
        .set_ip_address_type = "SetIpAddressType",
        .create_certificate = "CreateCertificate",
        .delete_certificate = "DeleteCertificate",
        .create_container_service = "CreateContainerService",
        .update_container_service = "UpdateContainerService",
        .delete_container_service = "DeleteContainerService",
        .create_container_service_deployment = "CreateContainerServiceDeployment",
        .create_container_service_registry_login = "CreateContainerServiceRegistryLogin",
        .register_container_image = "RegisterContainerImage",
        .delete_container_image = "DeleteContainerImage",
        .create_bucket = "CreateBucket",
        .delete_bucket = "DeleteBucket",
        .create_bucket_access_key = "CreateBucketAccessKey",
        .delete_bucket_access_key = "DeleteBucketAccessKey",
        .update_bucket_bundle = "UpdateBucketBundle",
        .update_bucket = "UpdateBucket",
        .set_resource_access_for_bucket = "SetResourceAccessForBucket",
        .update_instance_metadata_options = "UpdateInstanceMetadataOptions",
        .start_gui_session = "StartGUISession",
        .stop_gui_session = "StopGUISession",
        .setup_instance_https = "SetupInstanceHttps",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .delete_known_host_keys => "DeleteKnownHostKeys",
            .delete_instance => "DeleteInstance",
            .create_instance => "CreateInstance",
            .stop_instance => "StopInstance",
            .start_instance => "StartInstance",
            .reboot_instance => "RebootInstance",
            .open_instance_public_ports => "OpenInstancePublicPorts",
            .put_instance_public_ports => "PutInstancePublicPorts",
            .close_instance_public_ports => "CloseInstancePublicPorts",
            .allocate_static_ip => "AllocateStaticIp",
            .release_static_ip => "ReleaseStaticIp",
            .attach_static_ip => "AttachStaticIp",
            .detach_static_ip => "DetachStaticIp",
            .update_domain_entry => "UpdateDomainEntry",
            .delete_domain_entry => "DeleteDomainEntry",
            .create_domain => "CreateDomain",
            .delete_domain => "DeleteDomain",
            .create_instance_snapshot => "CreateInstanceSnapshot",
            .delete_instance_snapshot => "DeleteInstanceSnapshot",
            .create_instances_from_snapshot => "CreateInstancesFromSnapshot",
            .create_load_balancer => "CreateLoadBalancer",
            .delete_load_balancer => "DeleteLoadBalancer",
            .attach_instances_to_load_balancer => "AttachInstancesToLoadBalancer",
            .detach_instances_from_load_balancer => "DetachInstancesFromLoadBalancer",
            .update_load_balancer_attribute => "UpdateLoadBalancerAttribute",
            .create_load_balancer_tls_certificate => "CreateLoadBalancerTlsCertificate",
            .delete_load_balancer_tls_certificate => "DeleteLoadBalancerTlsCertificate",
            .attach_load_balancer_tls_certificate => "AttachLoadBalancerTlsCertificate",
            .create_disk => "CreateDisk",
            .delete_disk => "DeleteDisk",
            .attach_disk => "AttachDisk",
            .detach_disk => "DetachDisk",
            .create_disk_snapshot => "CreateDiskSnapshot",
            .delete_disk_snapshot => "DeleteDiskSnapshot",
            .create_disk_from_snapshot => "CreateDiskFromSnapshot",
            .create_relational_database => "CreateRelationalDatabase",
            .update_relational_database => "UpdateRelationalDatabase",
            .delete_relational_database => "DeleteRelationalDatabase",
            .create_relational_database_from_snapshot => "CreateRelationalDatabaseFromSnapshot",
            .create_relational_database_snapshot => "CreateRelationalDatabaseSnapshot",
            .delete_relational_database_snapshot => "DeleteRelationalDatabaseSnapshot",
            .update_relational_database_parameters => "UpdateRelationalDatabaseParameters",
            .start_relational_database => "StartRelationalDatabase",
            .reboot_relational_database => "RebootRelationalDatabase",
            .stop_relational_database => "StopRelationalDatabase",
            .enable_add_on => "EnableAddOn",
            .disable_add_on => "DisableAddOn",
            .put_alarm => "PutAlarm",
            .get_alarms => "GetAlarms",
            .delete_alarm => "DeleteAlarm",
            .test_alarm => "TestAlarm",
            .create_contact_method => "CreateContactMethod",
            .get_contact_methods => "GetContactMethods",
            .send_contact_method_verification => "SendContactMethodVerification",
            .delete_contact_method => "DeleteContactMethod",
            .create_distribution => "CreateDistribution",
            .update_distribution => "UpdateDistribution",
            .delete_distribution => "DeleteDistribution",
            .reset_distribution_cache => "ResetDistributionCache",
            .attach_certificate_to_distribution => "AttachCertificateToDistribution",
            .detach_certificate_from_distribution => "DetachCertificateFromDistribution",
            .update_distribution_bundle => "UpdateDistributionBundle",
            .set_ip_address_type => "SetIpAddressType",
            .create_certificate => "CreateCertificate",
            .delete_certificate => "DeleteCertificate",
            .create_container_service => "CreateContainerService",
            .update_container_service => "UpdateContainerService",
            .delete_container_service => "DeleteContainerService",
            .create_container_service_deployment => "CreateContainerServiceDeployment",
            .create_container_service_registry_login => "CreateContainerServiceRegistryLogin",
            .register_container_image => "RegisterContainerImage",
            .delete_container_image => "DeleteContainerImage",
            .create_bucket => "CreateBucket",
            .delete_bucket => "DeleteBucket",
            .create_bucket_access_key => "CreateBucketAccessKey",
            .delete_bucket_access_key => "DeleteBucketAccessKey",
            .update_bucket_bundle => "UpdateBucketBundle",
            .update_bucket => "UpdateBucket",
            .set_resource_access_for_bucket => "SetResourceAccessForBucket",
            .update_instance_metadata_options => "UpdateInstanceMetadataOptions",
            .start_gui_session => "StartGUISession",
            .stop_gui_session => "StopGUISession",
            .setup_instance_https => "SetupInstanceHttps",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
