pub const RegionName = enum {
    us_east_1,
    us_east_2,
    us_west_1,
    us_west_2,
    eu_west_1,
    eu_west_2,
    eu_west_3,
    eu_central_1,
    ca_central_1,
    ap_south_1,
    ap_southeast_1,
    ap_southeast_2,
    ap_northeast_1,
    ap_northeast_2,
    eu_north_1,
    ap_southeast_3,

    pub const json_field_names = .{
        .us_east_1 = "US_EAST_1",
        .us_east_2 = "US_EAST_2",
        .us_west_1 = "US_WEST_1",
        .us_west_2 = "US_WEST_2",
        .eu_west_1 = "EU_WEST_1",
        .eu_west_2 = "EU_WEST_2",
        .eu_west_3 = "EU_WEST_3",
        .eu_central_1 = "EU_CENTRAL_1",
        .ca_central_1 = "CA_CENTRAL_1",
        .ap_south_1 = "AP_SOUTH_1",
        .ap_southeast_1 = "AP_SOUTHEAST_1",
        .ap_southeast_2 = "AP_SOUTHEAST_2",
        .ap_northeast_1 = "AP_NORTHEAST_1",
        .ap_northeast_2 = "AP_NORTHEAST_2",
        .eu_north_1 = "EU_NORTH_1",
        .ap_southeast_3 = "AP_SOUTHEAST_3",
    };
};
