pub const BackupVaultEvent = enum {
    backup_job_started,
    backup_job_completed,
    backup_job_successful,
    backup_job_failed,
    backup_job_expired,
    restore_job_started,
    restore_job_completed,
    restore_job_successful,
    restore_job_failed,
    copy_job_started,
    copy_job_successful,
    copy_job_failed,
    recovery_point_modified,
    backup_plan_created,
    backup_plan_modified,
    s3_backup_object_failed,
    s3_restore_object_failed,
    continuous_backup_interrupted,
    recovery_point_index_completed,
    recovery_point_index_deleted,
    recovery_point_indexing_failed,

    pub const json_field_names = .{
        .backup_job_started = "BACKUP_JOB_STARTED",
        .backup_job_completed = "BACKUP_JOB_COMPLETED",
        .backup_job_successful = "BACKUP_JOB_SUCCESSFUL",
        .backup_job_failed = "BACKUP_JOB_FAILED",
        .backup_job_expired = "BACKUP_JOB_EXPIRED",
        .restore_job_started = "RESTORE_JOB_STARTED",
        .restore_job_completed = "RESTORE_JOB_COMPLETED",
        .restore_job_successful = "RESTORE_JOB_SUCCESSFUL",
        .restore_job_failed = "RESTORE_JOB_FAILED",
        .copy_job_started = "COPY_JOB_STARTED",
        .copy_job_successful = "COPY_JOB_SUCCESSFUL",
        .copy_job_failed = "COPY_JOB_FAILED",
        .recovery_point_modified = "RECOVERY_POINT_MODIFIED",
        .backup_plan_created = "BACKUP_PLAN_CREATED",
        .backup_plan_modified = "BACKUP_PLAN_MODIFIED",
        .s3_backup_object_failed = "S3_BACKUP_OBJECT_FAILED",
        .s3_restore_object_failed = "S3_RESTORE_OBJECT_FAILED",
        .continuous_backup_interrupted = "CONTINUOUS_BACKUP_INTERRUPTED",
        .recovery_point_index_completed = "RECOVERY_POINT_INDEX_COMPLETED",
        .recovery_point_index_deleted = "RECOVERY_POINT_INDEX_DELETED",
        .recovery_point_indexing_failed = "RECOVERY_POINT_INDEXING_FAILED",
    };
};
