const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const ServiceError = @import("errors.zig").ServiceError;
const RestoreJobCreator = @import("restore_job_creator.zig").RestoreJobCreator;
const RestoreDeletionStatus = @import("restore_deletion_status.zig").RestoreDeletionStatus;
const RestoreJobStatus = @import("restore_job_status.zig").RestoreJobStatus;
const RestoreValidationStatus = @import("restore_validation_status.zig").RestoreValidationStatus;

pub const DescribeRestoreJobInput = struct {
    /// Uniquely identifies the job that restores a recovery point.
    restore_job_id: []const u8,

    pub const json_field_names = .{
        .restore_job_id = "RestoreJobId",
    };
};

pub const DescribeRestoreJobOutput = struct {
    /// Returns the account ID that owns the restore job.
    account_id: ?[]const u8 = null,

    /// The size, in bytes, of the restored resource.
    backup_size_in_bytes: ?i64 = null,

    /// The Amazon Resource Name (ARN) of the backup vault containing the recovery
    /// point being restored. This helps identify vault access policies and
    /// permissions.
    backup_vault_arn: ?[]const u8 = null,

    /// The date and time that a job to restore a recovery point is completed, in
    /// Unix format
    /// and Coordinated Universal Time (UTC). The value of `CompletionDate` is
    /// accurate
    /// to milliseconds. For example, the value 1516925490.087 represents Friday,
    /// January 26, 2018
    /// 12:11:30.087 AM.
    completion_date: ?i64 = null,

    /// Contains identifying information about the creation of a restore job.
    created_by: ?RestoreJobCreator = null,

    /// The Amazon Resource Name (ARN) of the resource that
    /// was created by the restore job.
    ///
    /// The format of the ARN depends on the resource type of the backed-up
    /// resource.
    created_resource_arn: ?[]const u8 = null,

    /// The date and time that a restore job is created, in Unix format and
    /// Coordinated
    /// Universal Time (UTC). The value of `CreationDate` is accurate to
    /// milliseconds.
    /// For example, the value 1516925490.087 represents Friday, January 26, 2018
    /// 12:11:30.087
    /// AM.
    creation_date: ?i64 = null,

    /// The status of the data generated by the restore test.
    deletion_status: ?RestoreDeletionStatus = null,

    /// This describes the restore job deletion status.
    deletion_status_message: ?[]const u8 = null,

    /// The amount of time in minutes that a job restoring a recovery point is
    /// expected to
    /// take.
    expected_completion_time_minutes: ?i64 = null,

    /// Specifies the IAM role ARN used to create the target recovery point; for
    /// example,
    /// `arn:aws:iam::123456789012:role/S3Access`.
    iam_role_arn: ?[]const u8 = null,

    /// This is a boolean value indicating whether the restore job is a parent
    /// (composite) restore job.
    is_parent: bool = false,

    /// This is the unique identifier of the parent restore job for the selected
    /// restore job.
    parent_job_id: ?[]const u8 = null,

    /// Contains an estimated percentage that is complete of a job at the time the
    /// job status
    /// was queried.
    percent_done: ?[]const u8 = null,

    /// An ARN that uniquely identifies a recovery point; for example,
    /// `arn:aws:backup:us-east-1:123456789012:recovery-point:1EB3B5E7-9EB0-435A-A80B-108B488B0D45`.
    recovery_point_arn: ?[]const u8 = null,

    /// The creation date of the recovery point made by the specifed restore job.
    recovery_point_creation_date: ?i64 = null,

    /// Returns metadata associated with a restore job listed by resource type.
    resource_type: ?[]const u8 = null,

    /// Uniquely identifies the job that restores a recovery point.
    restore_job_id: ?[]const u8 = null,

    /// The Amazon Resource Name (ARN) of the original resource that was backed up.
    /// This provides context about what resource is being restored.
    source_resource_arn: ?[]const u8 = null,

    /// Status code specifying the state of the job that is initiated by Backup to
    /// restore a recovery point.
    status: ?RestoreJobStatus = null,

    /// A message showing the status of a job to restore a recovery point.
    status_message: ?[]const u8 = null,

    /// The status of validation run on the indicated
    /// restore job.
    validation_status: ?RestoreValidationStatus = null,

    /// The status message.
    validation_status_message: ?[]const u8 = null,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .backup_size_in_bytes = "BackupSizeInBytes",
        .backup_vault_arn = "BackupVaultArn",
        .completion_date = "CompletionDate",
        .created_by = "CreatedBy",
        .created_resource_arn = "CreatedResourceArn",
        .creation_date = "CreationDate",
        .deletion_status = "DeletionStatus",
        .deletion_status_message = "DeletionStatusMessage",
        .expected_completion_time_minutes = "ExpectedCompletionTimeMinutes",
        .iam_role_arn = "IamRoleArn",
        .is_parent = "IsParent",
        .parent_job_id = "ParentJobId",
        .percent_done = "PercentDone",
        .recovery_point_arn = "RecoveryPointArn",
        .recovery_point_creation_date = "RecoveryPointCreationDate",
        .resource_type = "ResourceType",
        .restore_job_id = "RestoreJobId",
        .source_resource_arn = "SourceResourceArn",
        .status = "Status",
        .status_message = "StatusMessage",
        .validation_status = "ValidationStatus",
        .validation_status_message = "ValidationStatusMessage",
    };
};

pub const Options = struct {
    diagnostic: ?*ServiceError = null,
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: DescribeRestoreJobInput, options: Options) !DescribeRestoreJobOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(alloc);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "backup");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(response.body, response.status, client.allocator) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(response.body, response.status, response.headers, allocator);
    return result;
}

fn serializeRequest(alloc: std.mem.Allocator, input: DescribeRestoreJobInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("backup", "Backup", alloc);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    var path_buf: std.ArrayList(u8) = .{};
    try path_buf.appendSlice(alloc, "/restore-jobs/");
    try path_buf.appendSlice(alloc, input.restore_job_id);
    const path = try path_buf.toOwnedSlice(alloc);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(host);
    request.method = .GET;
    request.path = path;
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(alloc, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(body: []const u8, status: u16, headers: anytype, alloc: std.mem.Allocator) !DescribeRestoreJobOutput {
    var result: DescribeRestoreJobOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(DescribeRestoreJobOutput, body, alloc);
    }
    _ = status;
    _ = headers;

    return result;
}

fn parseErrorResponse(body: []const u8, status: u16, alloc: std.mem.Allocator) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(alloc);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AlreadyExistsException")) {
        return .{ .arena = arena, .kind = .{ .already_exists_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConflictException")) {
        return .{ .arena = arena, .kind = .{ .conflict_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DependencyFailureException")) {
        return .{ .arena = arena, .kind = .{ .dependency_failure_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidParameterValueException")) {
        return .{ .arena = arena, .kind = .{ .invalid_parameter_value_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidRequestException")) {
        return .{ .arena = arena, .kind = .{ .invalid_request_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidResourceStateException")) {
        return .{ .arena = arena, .kind = .{ .invalid_resource_state_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "LimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MissingParameterValueException")) {
        return .{ .arena = arena, .kind = .{ .missing_parameter_value_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .resource_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ServiceUnavailableException")) {
        return .{ .arena = arena, .kind = .{ .service_unavailable_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
