const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const RestoreJobCreator = @import("restore_job_creator.zig").RestoreJobCreator;
const RestoreDeletionStatus = @import("restore_deletion_status.zig").RestoreDeletionStatus;
const RestoreJobStatus = @import("restore_job_status.zig").RestoreJobStatus;
const RestoreValidationStatus = @import("restore_validation_status.zig").RestoreValidationStatus;

pub const DescribeRestoreJobInput = struct {
    /// Uniquely identifies the job that restores a recovery point.
    restore_job_id: []const u8,

    pub const json_field_names = .{
        .restore_job_id = "RestoreJobId",
    };
};

pub const DescribeRestoreJobOutput = struct {
    /// Returns the account ID that owns the restore job.
    account_id: ?[]const u8 = null,

    /// The size, in bytes, of the restored resource.
    backup_size_in_bytes: ?i64 = null,

    /// The Amazon Resource Name (ARN) of the backup vault containing the recovery
    /// point being restored. This helps identify vault access policies and
    /// permissions.
    backup_vault_arn: ?[]const u8 = null,

    /// The date and time that a job to restore a recovery point is completed, in
    /// Unix format
    /// and Coordinated Universal Time (UTC). The value of `CompletionDate` is
    /// accurate
    /// to milliseconds. For example, the value 1516925490.087 represents Friday,
    /// January 26, 2018
    /// 12:11:30.087 AM.
    completion_date: ?i64 = null,

    /// Contains identifying information about the creation of a restore job.
    created_by: ?RestoreJobCreator = null,

    /// The Amazon Resource Name (ARN) of the resource that
    /// was created by the restore job.
    ///
    /// The format of the ARN depends on the resource type of the backed-up
    /// resource.
    created_resource_arn: ?[]const u8 = null,

    /// The date and time that a restore job is created, in Unix format and
    /// Coordinated
    /// Universal Time (UTC). The value of `CreationDate` is accurate to
    /// milliseconds.
    /// For example, the value 1516925490.087 represents Friday, January 26, 2018
    /// 12:11:30.087
    /// AM.
    creation_date: ?i64 = null,

    /// The status of the data generated by the restore test.
    deletion_status: ?RestoreDeletionStatus = null,

    /// This describes the restore job deletion status.
    deletion_status_message: ?[]const u8 = null,

    /// The amount of time in minutes that a job restoring a recovery point is
    /// expected to
    /// take.
    expected_completion_time_minutes: ?i64 = null,

    /// Specifies the IAM role ARN used to create the target recovery point; for
    /// example,
    /// `arn:aws:iam::123456789012:role/S3Access`.
    iam_role_arn: ?[]const u8 = null,

    /// This is a boolean value indicating whether the restore job is a parent
    /// (composite) restore job.
    is_parent: ?bool = null,

    /// This is the unique identifier of the parent restore job for the selected
    /// restore job.
    parent_job_id: ?[]const u8 = null,

    /// Contains an estimated percentage that is complete of a job at the time the
    /// job status
    /// was queried.
    percent_done: ?[]const u8 = null,

    /// An ARN that uniquely identifies a recovery point; for example,
    /// `arn:aws:backup:us-east-1:123456789012:recovery-point:1EB3B5E7-9EB0-435A-A80B-108B488B0D45`.
    recovery_point_arn: ?[]const u8 = null,

    /// The creation date of the recovery point made by the specifed restore job.
    recovery_point_creation_date: ?i64 = null,

    /// Returns metadata associated with a restore job listed by resource type.
    resource_type: ?[]const u8 = null,

    /// Uniquely identifies the job that restores a recovery point.
    restore_job_id: ?[]const u8 = null,

    /// The Amazon Resource Name (ARN) of the original resource that was backed up.
    /// This provides context about what resource is being restored.
    source_resource_arn: ?[]const u8 = null,

    /// Status code specifying the state of the job that is initiated by Backup to
    /// restore a recovery point.
    status: ?RestoreJobStatus = null,

    /// A message showing the status of a job to restore a recovery point.
    status_message: ?[]const u8 = null,

    /// The status of validation run on the indicated
    /// restore job.
    validation_status: ?RestoreValidationStatus = null,

    /// The status message.
    validation_status_message: ?[]const u8 = null,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .backup_size_in_bytes = "BackupSizeInBytes",
        .backup_vault_arn = "BackupVaultArn",
        .completion_date = "CompletionDate",
        .created_by = "CreatedBy",
        .created_resource_arn = "CreatedResourceArn",
        .creation_date = "CreationDate",
        .deletion_status = "DeletionStatus",
        .deletion_status_message = "DeletionStatusMessage",
        .expected_completion_time_minutes = "ExpectedCompletionTimeMinutes",
        .iam_role_arn = "IamRoleArn",
        .is_parent = "IsParent",
        .parent_job_id = "ParentJobId",
        .percent_done = "PercentDone",
        .recovery_point_arn = "RecoveryPointArn",
        .recovery_point_creation_date = "RecoveryPointCreationDate",
        .resource_type = "ResourceType",
        .restore_job_id = "RestoreJobId",
        .source_resource_arn = "SourceResourceArn",
        .status = "Status",
        .status_message = "StatusMessage",
        .validation_status = "ValidationStatus",
        .validation_status_message = "ValidationStatusMessage",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: DescribeRestoreJobInput, options: CallOptions) !DescribeRestoreJobOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "backup", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: DescribeRestoreJobInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("backup", "Backup", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/restore-jobs/");
    try path_buf.appendSlice(allocator, input.restore_job_id);
    const path = try path_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(ep.host);
    request.method = .GET;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !DescribeRestoreJobOutput {
    const result: DescribeRestoreJobOutput = try aws.json.parseJsonObject(
        DescribeRestoreJobOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
