const ScanJobCreator = @import("scan_job_creator.zig").ScanJobCreator;
const MalwareScanner = @import("malware_scanner.zig").MalwareScanner;
const ScanResourceType = @import("scan_resource_type.zig").ScanResourceType;
const ScanMode = @import("scan_mode.zig").ScanMode;
const ScanResultInfo = @import("scan_result_info.zig").ScanResultInfo;
const ScanState = @import("scan_state.zig").ScanState;

/// Contains metadata about a scan job, including information about the scanning
/// process, results, and associated resources.
pub const ScanJob = struct {
    /// The account ID that owns the scan job.
    account_id: []const u8,

    /// An Amazon Resource Name (ARN) that uniquely identifies a backup vault; for
    /// example,
    /// `arn:aws:backup:us-east-1:123456789012:backup-vault:aBackupVault`.
    backup_vault_arn: []const u8,

    /// The name of a logical container where backups are stored. Backup vaults are
    /// identified
    /// by names that are unique to the account used to create them and the Amazon
    /// Web Services
    /// Region where they are created.
    backup_vault_name: []const u8,

    /// The date and time that a scan job is completed, in Unix format and
    /// Coordinated
    /// Universal Time (UTC). The value of `CompletionDate` is accurate to
    /// milliseconds.
    /// For example, the value 1516925490.087 represents Friday, January 26, 2018
    /// 12:11:30.087
    /// AM.
    completion_date: ?i64,

    /// Contains identifying information about the creation of a scan job.
    created_by: ScanJobCreator,

    /// The date and time that a scan job is created, in Unix format and Coordinated
    /// Universal Time (UTC). The value of `CreationDate` is accurate to
    /// milliseconds.
    /// For example, the value 1516925490.087 represents Friday, January 26, 2018
    /// 12:11:30.087
    /// AM.
    creation_date: i64,

    /// Specifies the IAM role ARN used to create the scan job; for example,
    /// `arn:aws:iam::123456789012:role/S3Access`.
    iam_role_arn: []const u8,

    /// The scanning engine used for the scan job. Currently only `GUARDDUTY` is
    /// supported.
    malware_scanner: MalwareScanner,

    /// An ARN that uniquely identifies the recovery point being scanned; for
    /// example,
    /// `arn:aws:backup:us-east-1:123456789012:recovery-point:1EB3B5E7-9EB0-435A-A80B-108B488B0D45`.
    recovery_point_arn: []const u8,

    /// An ARN that uniquely identifies the source resource of the recovery point
    /// being scanned.
    resource_arn: []const u8,

    /// The non-unique name of the resource that belongs to the specified backup.
    resource_name: []const u8,

    /// The type of Amazon Web Services resource being scanned; for example, an
    /// Amazon Elastic Block Store
    /// (Amazon EBS) volume or an Amazon Relational Database Service (Amazon RDS)
    /// database.
    resource_type: ScanResourceType,

    /// An ARN that uniquely identifies the base recovery point for scanning. This
    /// field is populated
    /// when an incremental scan job has taken place.
    scan_base_recovery_point_arn: ?[]const u8,

    /// The scan ID generated by the malware scanner for the corresponding scan job.
    scan_id: ?[]const u8,

    /// The unique identifier that identifies the scan job request to Backup.
    scan_job_id: []const u8,

    /// Specifies the scan type use for the scan job.
    ///
    /// Includes:
    ///
    /// `FULL_SCAN` will scan the entire data lineage within the backup.
    ///
    /// `INCREMENTAL_SCAN` will scan the data difference between the target recovery
    /// point and base recovery point ARN.
    scan_mode: ScanMode,

    /// Specifies the scanner IAM role ARN used for the scan job.
    scanner_role_arn: []const u8,

    /// Contains the scan results information, including the status of threats found
    /// during scanning.
    scan_result: ?ScanResultInfo,

    /// The current state of the scan job.
    ///
    /// Valid values: `CREATED` | `RUNNING` | `COMPLETED` |
    /// `COMPLETED_WITH_ISSUES` | `FAILED` | `CANCELED`.
    state: ?ScanState,

    /// A detailed message explaining the status of the scan job.
    status_message: ?[]const u8,

    pub const json_field_names = .{
        .account_id = "AccountId",
        .backup_vault_arn = "BackupVaultArn",
        .backup_vault_name = "BackupVaultName",
        .completion_date = "CompletionDate",
        .created_by = "CreatedBy",
        .creation_date = "CreationDate",
        .iam_role_arn = "IamRoleArn",
        .malware_scanner = "MalwareScanner",
        .recovery_point_arn = "RecoveryPointArn",
        .resource_arn = "ResourceArn",
        .resource_name = "ResourceName",
        .resource_type = "ResourceType",
        .scan_base_recovery_point_arn = "ScanBaseRecoveryPointArn",
        .scan_id = "ScanId",
        .scan_job_id = "ScanJobId",
        .scan_mode = "ScanMode",
        .scanner_role_arn = "ScannerRoleArn",
        .scan_result = "ScanResult",
        .state = "State",
        .status_message = "StatusMessage",
    };
};
