const std = @import("std");

pub const TextTransformationType = enum {
    none,
    compress_white_space,
    html_entity_decode,
    lowercase,
    cmd_line,
    url_decode,
    base64_decode,
    hex_decode,
    md5,
    replace_comments,
    escape_seq_decode,
    sql_hex_decode,
    css_decode,
    js_decode,
    normalize_path,
    normalize_path_win,
    remove_nulls,
    replace_nulls,
    base64_decode_ext,
    url_decode_uni,
    utf8_to_unicode,
    remove_whitespace,
    trim,
    trim_left,
    trim_right,
    remove_comments_char,
    uppercase,
    cmd_line_win,
    cmd_line_unix,
    js_decode_ext,
    sha256,

    pub const json_field_names = .{
        .none = "NONE",
        .compress_white_space = "COMPRESS_WHITE_SPACE",
        .html_entity_decode = "HTML_ENTITY_DECODE",
        .lowercase = "LOWERCASE",
        .cmd_line = "CMD_LINE",
        .url_decode = "URL_DECODE",
        .base64_decode = "BASE64_DECODE",
        .hex_decode = "HEX_DECODE",
        .md5 = "MD5",
        .replace_comments = "REPLACE_COMMENTS",
        .escape_seq_decode = "ESCAPE_SEQ_DECODE",
        .sql_hex_decode = "SQL_HEX_DECODE",
        .css_decode = "CSS_DECODE",
        .js_decode = "JS_DECODE",
        .normalize_path = "NORMALIZE_PATH",
        .normalize_path_win = "NORMALIZE_PATH_WIN",
        .remove_nulls = "REMOVE_NULLS",
        .replace_nulls = "REPLACE_NULLS",
        .base64_decode_ext = "BASE64_DECODE_EXT",
        .url_decode_uni = "URL_DECODE_UNI",
        .utf8_to_unicode = "UTF8_TO_UNICODE",
        .remove_whitespace = "REMOVE_WHITESPACE",
        .trim = "TRIM",
        .trim_left = "TRIM_LEFT",
        .trim_right = "TRIM_RIGHT",
        .remove_comments_char = "REMOVE_COMMENTS_CHAR",
        .uppercase = "UPPERCASE",
        .cmd_line_win = "CMD_LINE_WIN",
        .cmd_line_unix = "CMD_LINE_UNIX",
        .js_decode_ext = "JS_DECODE_EXT",
        .sha256 = "SHA256",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .none => "NONE",
            .compress_white_space => "COMPRESS_WHITE_SPACE",
            .html_entity_decode => "HTML_ENTITY_DECODE",
            .lowercase => "LOWERCASE",
            .cmd_line => "CMD_LINE",
            .url_decode => "URL_DECODE",
            .base64_decode => "BASE64_DECODE",
            .hex_decode => "HEX_DECODE",
            .md5 => "MD5",
            .replace_comments => "REPLACE_COMMENTS",
            .escape_seq_decode => "ESCAPE_SEQ_DECODE",
            .sql_hex_decode => "SQL_HEX_DECODE",
            .css_decode => "CSS_DECODE",
            .js_decode => "JS_DECODE",
            .normalize_path => "NORMALIZE_PATH",
            .normalize_path_win => "NORMALIZE_PATH_WIN",
            .remove_nulls => "REMOVE_NULLS",
            .replace_nulls => "REPLACE_NULLS",
            .base64_decode_ext => "BASE64_DECODE_EXT",
            .url_decode_uni => "URL_DECODE_UNI",
            .utf8_to_unicode => "UTF8_TO_UNICODE",
            .remove_whitespace => "REMOVE_WHITESPACE",
            .trim => "TRIM",
            .trim_left => "TRIM_LEFT",
            .trim_right => "TRIM_RIGHT",
            .remove_comments_char => "REMOVE_COMMENTS_CHAR",
            .uppercase => "UPPERCASE",
            .cmd_line_win => "CMD_LINE_WIN",
            .cmd_line_unix => "CMD_LINE_UNIX",
            .js_decode_ext => "JS_DECODE_EXT",
            .sha256 => "SHA256",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        const fields = @typeInfo(@TypeOf(json_field_names)).@"struct".field_names;
        inline for (fields) |field_name| {
            if (std.mem.eql(u8, str, @field(json_field_names, field_name))) {
                return @field(@This(), field_name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
