pub const TextTransformationType = enum {
    none,
    compress_white_space,
    html_entity_decode,
    lowercase,
    cmd_line,
    url_decode,
    base64_decode,
    hex_decode,
    md5,
    replace_comments,
    escape_seq_decode,
    sql_hex_decode,
    css_decode,
    js_decode,
    normalize_path,
    normalize_path_win,
    remove_nulls,
    replace_nulls,
    base64_decode_ext,
    url_decode_uni,
    utf8_to_unicode,

    pub const json_field_names = .{
        .none = "NONE",
        .compress_white_space = "COMPRESS_WHITE_SPACE",
        .html_entity_decode = "HTML_ENTITY_DECODE",
        .lowercase = "LOWERCASE",
        .cmd_line = "CMD_LINE",
        .url_decode = "URL_DECODE",
        .base64_decode = "BASE64_DECODE",
        .hex_decode = "HEX_DECODE",
        .md5 = "MD5",
        .replace_comments = "REPLACE_COMMENTS",
        .escape_seq_decode = "ESCAPE_SEQ_DECODE",
        .sql_hex_decode = "SQL_HEX_DECODE",
        .css_decode = "CSS_DECODE",
        .js_decode = "JS_DECODE",
        .normalize_path = "NORMALIZE_PATH",
        .normalize_path_win = "NORMALIZE_PATH_WIN",
        .remove_nulls = "REMOVE_NULLS",
        .replace_nulls = "REPLACE_NULLS",
        .base64_decode_ext = "BASE64_DECODE_EXT",
        .url_decode_uni = "URL_DECODE_UNI",
        .utf8_to_unicode = "UTF8_TO_UNICODE",
    };
};
