pub const HandlerErrorCode = enum {
    not_updatable,
    invalid_request,
    access_denied,
    unauthorized_tagging_operation,
    invalid_credentials,
    already_exists,
    not_found,
    resource_conflict,
    throttling,
    service_limit_exceeded,
    not_stabilized,
    general_service_exception,
    service_internal_error,
    service_timeout,
    network_failure,
    internal_failure,

    pub const json_field_names = .{
        .not_updatable = "NOT_UPDATABLE",
        .invalid_request = "INVALID_REQUEST",
        .access_denied = "ACCESS_DENIED",
        .unauthorized_tagging_operation = "UNAUTHORIZED_TAGGING_OPERATION",
        .invalid_credentials = "INVALID_CREDENTIALS",
        .already_exists = "ALREADY_EXISTS",
        .not_found = "NOT_FOUND",
        .resource_conflict = "RESOURCE_CONFLICT",
        .throttling = "THROTTLING",
        .service_limit_exceeded = "SERVICE_LIMIT_EXCEEDED",
        .not_stabilized = "NOT_STABILIZED",
        .general_service_exception = "GENERAL_SERVICE_EXCEPTION",
        .service_internal_error = "SERVICE_INTERNAL_ERROR",
        .service_timeout = "SERVICE_TIMEOUT",
        .network_failure = "NETWORK_FAILURE",
        .internal_failure = "INTERNAL_FAILURE",
    };
};
