pub const AppType = enum {
    dot_net_framework,
    java,
    sql_server,
    iis,
    oracle,
    other,
    tomcat,
    jboss,
    spring,
    mongodb,
    db_2,
    mariadb,
    mysql,
    sybase,
    postgresqlserver,
    cassandra,
    websphere,
    weblogic,
    visualbasic,
    unknown,
    dotnetcore,
    dotnet,

    pub const json_field_names = .{
        .dot_net_framework = "dotNetFramework",
        .java = "java",
        .sql_server = "sqlServer",
        .iis = "IIS",
        .oracle = "oracle",
        .other = "other",
        .tomcat = "tomcat",
        .jboss = "jboss",
        .spring = "spring",
        .mongodb = "mongodb",
        .db_2 = "db2",
        .mariadb = "mariadb",
        .mysql = "mysql",
        .sybase = "sybase",
        .postgresqlserver = "postgresqlserver",
        .cassandra = "cassandra",
        .websphere = "websphere",
        .weblogic = "weblogic",
        .visualbasic = "visualbasic",
        .unknown = "unknown",
        .dotnetcore = "dotnetcore",
        .dotnet = "dotnet",
    };
};
