const aws = @import("aws");

const AuthorizationType = @import("authorization_type.zig").AuthorizationType;
const ParameterConstraints = @import("parameter_constraints.zig").ParameterConstraints;

/// Creates a new Route resource to represent a route.
pub const CreateRouteRequest = struct {
    /// The API identifier.
    api_id: []const u8,

    /// Specifies whether an API key is required for the route. Supported only for
    /// WebSocket APIs.
    api_key_required: ?bool = null,

    /// The authorization scopes supported by this route.
    authorization_scopes: ?[]const []const u8 = null,

    /// The authorization type for the route. For WebSocket APIs, valid values are
    /// NONE for open access, AWS_IAM for using AWS IAM permissions, and CUSTOM for
    /// using a Lambda authorizer For HTTP APIs, valid values are NONE for open
    /// access, JWT for using JSON Web Tokens, AWS_IAM for using AWS IAM
    /// permissions, and CUSTOM for using a Lambda authorizer.
    authorization_type: ?AuthorizationType = null,

    /// The identifier of the Authorizer resource to be associated with this route.
    /// The authorizer identifier is generated by API Gateway when you created the
    /// authorizer.
    authorizer_id: ?[]const u8 = null,

    /// The model selection expression for the route. Supported only for WebSocket
    /// APIs.
    model_selection_expression: ?[]const u8 = null,

    /// The operation name for the route.
    operation_name: ?[]const u8 = null,

    /// The request models for the route. Supported only for WebSocket APIs.
    request_models: ?[]const aws.map.StringMapEntry = null,

    /// The request parameters for the route. Supported only for WebSocket APIs.
    request_parameters: ?[]const aws.map.MapEntry(ParameterConstraints) = null,

    /// The route key for the route.
    route_key: []const u8,

    /// The route response selection expression for the route. Supported only for
    /// WebSocket APIs.
    route_response_selection_expression: ?[]const u8 = null,

    /// The target for the route.
    target: ?[]const u8 = null,

    pub const json_field_names = .{
        .api_id = "ApiId",
        .api_key_required = "ApiKeyRequired",
        .authorization_scopes = "AuthorizationScopes",
        .authorization_type = "AuthorizationType",
        .authorizer_id = "AuthorizerId",
        .model_selection_expression = "ModelSelectionExpression",
        .operation_name = "OperationName",
        .request_models = "RequestModels",
        .request_parameters = "RequestParameters",
        .route_key = "RouteKey",
        .route_response_selection_expression = "RouteResponseSelectionExpression",
        .target = "Target",
    };
};
