const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const ServiceError = @import("errors.zig").ServiceError;
const AuthorizationType = @import("authorization_type.zig").AuthorizationType;
const ParameterConstraints = @import("parameter_constraints.zig").ParameterConstraints;

pub const GetRouteInput = struct {
    /// The API identifier.
    api_id: []const u8,

    /// The route ID.
    route_id: []const u8,

    pub const json_field_names = .{
        .api_id = "ApiId",
        .route_id = "RouteId",
    };
};

pub const GetRouteOutput = struct {
    /// Specifies whether a route is managed by API Gateway. If you created an API
    /// using quick create, the $default route is managed by API Gateway. You can't
    /// modify the $default route key.
    api_gateway_managed: ?bool = null,

    /// Specifies whether an API key is required for this route. Supported only for
    /// WebSocket APIs.
    api_key_required: ?bool = null,

    /// A list of authorization scopes configured on a route. The scopes are used
    /// with a JWT authorizer to authorize the method invocation. The authorization
    /// works by matching the route scopes against the scopes parsed from the access
    /// token in the incoming request. The method invocation is authorized if any
    /// route scope matches a claimed scope in the access token. Otherwise, the
    /// invocation is not authorized. When the route scope is configured, the client
    /// must provide an access token instead of an identity token for authorization
    /// purposes.
    authorization_scopes: ?[]const []const u8 = null,

    /// The authorization type for the route. For WebSocket APIs, valid values are
    /// NONE for open access, AWS_IAM for using AWS IAM permissions, and CUSTOM for
    /// using a Lambda authorizer For HTTP APIs, valid values are NONE for open
    /// access, JWT for using JSON Web Tokens, AWS_IAM for using AWS IAM
    /// permissions, and CUSTOM for using a Lambda authorizer.
    authorization_type: ?AuthorizationType = null,

    /// The identifier of the Authorizer resource to be associated with this route.
    /// The authorizer identifier is generated by API Gateway when you created the
    /// authorizer.
    authorizer_id: ?[]const u8 = null,

    /// The model selection expression for the route. Supported only for WebSocket
    /// APIs.
    model_selection_expression: ?[]const u8 = null,

    /// The operation name for the route.
    operation_name: ?[]const u8 = null,

    /// The request models for the route. Supported only for WebSocket APIs.
    request_models: ?[]const aws.map.StringMapEntry = null,

    /// The request parameters for the route. Supported only for WebSocket APIs.
    request_parameters: ?[]const aws.map.MapEntry(ParameterConstraints) = null,

    /// The route ID.
    route_id: ?[]const u8 = null,

    /// The route key for the route.
    route_key: ?[]const u8 = null,

    /// The route response selection expression for the route. Supported only for
    /// WebSocket APIs.
    route_response_selection_expression: ?[]const u8 = null,

    /// The target for the route.
    target: ?[]const u8 = null,

    pub const json_field_names = .{
        .api_gateway_managed = "ApiGatewayManaged",
        .api_key_required = "ApiKeyRequired",
        .authorization_scopes = "AuthorizationScopes",
        .authorization_type = "AuthorizationType",
        .authorizer_id = "AuthorizerId",
        .model_selection_expression = "ModelSelectionExpression",
        .operation_name = "OperationName",
        .request_models = "RequestModels",
        .request_parameters = "RequestParameters",
        .route_id = "RouteId",
        .route_key = "RouteKey",
        .route_response_selection_expression = "RouteResponseSelectionExpression",
        .target = "Target",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetRouteInput, options: CallOptions) !GetRouteOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "apigateway");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetRouteInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("apigateway", "ApiGatewayV2", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    var path_buf: std.ArrayList(u8) = .{};
    try path_buf.appendSlice(allocator, "/v2/apis/");
    try path_buf.appendSlice(allocator, input.api_id);
    try path_buf.appendSlice(allocator, "/routes/");
    try path_buf.appendSlice(allocator, input.route_id);
    const path = try path_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(host);
    request.method = .GET;
    request.path = path;
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetRouteOutput {
    var result: GetRouteOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(GetRouteOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AccessDeniedException")) {
        return .{ .arena = arena, .kind = .{ .access_denied_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "BadRequestException")) {
        return .{ .arena = arena, .kind = .{ .bad_request_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConflictException")) {
        return .{ .arena = arena, .kind = .{ .conflict_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "NotFoundException")) {
        return .{ .arena = arena, .kind = .{ .not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TooManyRequestsException")) {
        return .{ .arena = arena, .kind = .{ .too_many_requests_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
