pub const AudioFormat = enum {
    mp3,
    opus,
    wav,
    aac,
    flac,
    mp4,
    ogg,
    mkv,
    mka,
    x_aac,
    m4_a,
    mpeg,
    mpga,
    pcm,
    webm,

    pub const json_field_names = .{
        .mp3 = "MP3",
        .opus = "OPUS",
        .wav = "WAV",
        .aac = "AAC",
        .flac = "FLAC",
        .mp4 = "MP4",
        .ogg = "OGG",
        .mkv = "MKV",
        .mka = "MKA",
        .x_aac = "X_AAC",
        .m4_a = "M4A",
        .mpeg = "MPEG",
        .mpga = "MPGA",
        .pcm = "PCM",
        .webm = "WEBM",
    };
};
