/// Contains the generated text content that corresponds to or is supported by a
/// citation from a source document.
pub const CitationGeneratedContent = union(enum) {
    /// The text content that was generated by the model and is supported by the
    /// associated citation.
    text: ?[]const u8,

    pub const json_field_names = .{
        .text = "text",
    };
};
