const ConverseMetrics = @import("converse_metrics.zig").ConverseMetrics;
const ConverseOutput = @import("converse_output.zig").ConverseOutput;
const PerformanceConfiguration = @import("performance_configuration.zig").PerformanceConfiguration;
const ServiceTier = @import("service_tier.zig").ServiceTier;
const StopReason = @import("stop_reason.zig").StopReason;
const ConverseTrace = @import("converse_trace.zig").ConverseTrace;
const TokenUsage = @import("token_usage.zig").TokenUsage;

pub const ConverseResponse = struct {
    /// Additional fields in the response that are unique to the model.
    additional_model_response_fields: ?[]const u8 = null,

    /// Metrics for the call to `Converse`.
    metrics: ConverseMetrics,

    /// The result from the call to `Converse`.
    output: ConverseOutput,

    /// Model performance settings for the request.
    performance_config: ?PerformanceConfiguration = null,

    /// Specifies the processing tier configuration used for serving the request.
    service_tier: ?ServiceTier = null,

    /// The reason why the model stopped generating output.
    stop_reason: StopReason,

    /// A trace object that contains information about the Guardrail behavior.
    trace: ?ConverseTrace = null,

    /// The total number of tokens used in the call to `Converse`. The total
    /// includes the tokens input to the model and the tokens generated by the
    /// model.
    usage: TokenUsage,

    pub const json_field_names = .{
        .additional_model_response_fields = "additionalModelResponseFields",
        .metrics = "metrics",
        .output = "output",
        .performance_config = "performanceConfig",
        .service_tier = "serviceTier",
        .stop_reason = "stopReason",
        .trace = "trace",
        .usage = "usage",
    };
};
