const std = @import("std");

pub const GuardrailPiiEntityType = enum {
    address,
    age,
    aws_access_key,
    aws_secret_key,
    ca_health_number,
    ca_social_insurance_number,
    credit_debit_card_cvv,
    credit_debit_card_expiry,
    credit_debit_card_number,
    driver_id,
    email,
    international_bank_account_number,
    ip_address,
    license_plate,
    mac_address,
    name,
    password,
    phone,
    pin,
    swift_code,
    uk_national_health_service_number,
    uk_national_insurance_number,
    uk_unique_taxpayer_reference_number,
    url,
    username,
    us_bank_account_number,
    us_bank_routing_number,
    us_individual_tax_identification_number,
    us_passport_number,
    us_social_security_number,
    vehicle_identification_number,

    pub const json_field_names = .{
        .address = "ADDRESS",
        .age = "AGE",
        .aws_access_key = "AWS_ACCESS_KEY",
        .aws_secret_key = "AWS_SECRET_KEY",
        .ca_health_number = "CA_HEALTH_NUMBER",
        .ca_social_insurance_number = "CA_SOCIAL_INSURANCE_NUMBER",
        .credit_debit_card_cvv = "CREDIT_DEBIT_CARD_CVV",
        .credit_debit_card_expiry = "CREDIT_DEBIT_CARD_EXPIRY",
        .credit_debit_card_number = "CREDIT_DEBIT_CARD_NUMBER",
        .driver_id = "DRIVER_ID",
        .email = "EMAIL",
        .international_bank_account_number = "INTERNATIONAL_BANK_ACCOUNT_NUMBER",
        .ip_address = "IP_ADDRESS",
        .license_plate = "LICENSE_PLATE",
        .mac_address = "MAC_ADDRESS",
        .name = "NAME",
        .password = "PASSWORD",
        .phone = "PHONE",
        .pin = "PIN",
        .swift_code = "SWIFT_CODE",
        .uk_national_health_service_number = "UK_NATIONAL_HEALTH_SERVICE_NUMBER",
        .uk_national_insurance_number = "UK_NATIONAL_INSURANCE_NUMBER",
        .uk_unique_taxpayer_reference_number = "UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER",
        .url = "URL",
        .username = "USERNAME",
        .us_bank_account_number = "US_BANK_ACCOUNT_NUMBER",
        .us_bank_routing_number = "US_BANK_ROUTING_NUMBER",
        .us_individual_tax_identification_number = "US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER",
        .us_passport_number = "US_PASSPORT_NUMBER",
        .us_social_security_number = "US_SOCIAL_SECURITY_NUMBER",
        .vehicle_identification_number = "VEHICLE_IDENTIFICATION_NUMBER",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .address => "ADDRESS",
            .age => "AGE",
            .aws_access_key => "AWS_ACCESS_KEY",
            .aws_secret_key => "AWS_SECRET_KEY",
            .ca_health_number => "CA_HEALTH_NUMBER",
            .ca_social_insurance_number => "CA_SOCIAL_INSURANCE_NUMBER",
            .credit_debit_card_cvv => "CREDIT_DEBIT_CARD_CVV",
            .credit_debit_card_expiry => "CREDIT_DEBIT_CARD_EXPIRY",
            .credit_debit_card_number => "CREDIT_DEBIT_CARD_NUMBER",
            .driver_id => "DRIVER_ID",
            .email => "EMAIL",
            .international_bank_account_number => "INTERNATIONAL_BANK_ACCOUNT_NUMBER",
            .ip_address => "IP_ADDRESS",
            .license_plate => "LICENSE_PLATE",
            .mac_address => "MAC_ADDRESS",
            .name => "NAME",
            .password => "PASSWORD",
            .phone => "PHONE",
            .pin => "PIN",
            .swift_code => "SWIFT_CODE",
            .uk_national_health_service_number => "UK_NATIONAL_HEALTH_SERVICE_NUMBER",
            .uk_national_insurance_number => "UK_NATIONAL_INSURANCE_NUMBER",
            .uk_unique_taxpayer_reference_number => "UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER",
            .url => "URL",
            .username => "USERNAME",
            .us_bank_account_number => "US_BANK_ACCOUNT_NUMBER",
            .us_bank_routing_number => "US_BANK_ROUTING_NUMBER",
            .us_individual_tax_identification_number => "US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER",
            .us_passport_number => "US_PASSPORT_NUMBER",
            .us_social_security_number => "US_SOCIAL_SECURITY_NUMBER",
            .vehicle_identification_number => "VEHICLE_IDENTIFICATION_NUMBER",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
