/// Contains content regarding the reasoning that is carried out by the model
/// with respect to the content in the content block. Reasoning refers to a
/// Chain of Thought (CoT) that the model generates to enhance the accuracy of
/// its final response.
pub const ReasoningContentBlockDelta = union(enum) {
    /// The content in the reasoning that was encrypted by the model provider for
    /// safety reasons. The encryption doesn't affect the quality of responses.
    redacted_content: ?[]const u8,
    /// A token that verifies that the reasoning text was generated by the model. If
    /// you pass a reasoning block back to the API in a multi-turn conversation,
    /// include the text and its signature unmodified.
    signature: ?[]const u8,
    /// The reasoning that the model used to return the output.
    text: ?[]const u8,

    pub const json_field_names = .{
        .redacted_content = "redactedContent",
        .signature = "signature",
        .text = "text",
    };
};
