const CacheDetail = @import("cache_detail.zig").CacheDetail;

/// The tokens used in a message API inference call.
pub const TokenUsage = struct {
    /// Detailed breakdown of cache writes by TTL. Empty if no cache creation
    /// occurred. Sorted by TTL duration (1h before 5m).
    cache_details: ?[]const CacheDetail,

    /// The number of input tokens read from the cache for the request.
    cache_read_input_tokens: ?i32,

    /// The number of input tokens written to the cache for the request.
    cache_write_input_tokens: ?i32,

    /// The number of tokens sent in the request to the model.
    input_tokens: i32,

    /// The number of tokens that the model generated for the request.
    output_tokens: i32,

    /// The total of input tokens and tokens generated by the model.
    total_tokens: i32,

    pub const json_field_names = .{
        .cache_details = "cacheDetails",
        .cache_read_input_tokens = "cacheReadInputTokens",
        .cache_write_input_tokens = "cacheWriteInputTokens",
        .input_tokens = "inputTokens",
        .output_tokens = "outputTokens",
        .total_tokens = "totalTokens",
    };
};
