pub const StatefulRuleProtocol = enum {
    any,
    tcp,
    udp,
    icmp,
    http,
    ftp,
    tls,
    smb,
    dns,
    dcerpc,
    ssh,
    smtp,
    imap,
    msn,
    krb5,
    ikev2,
    tftp,
    ntp,
    dhcp,
    http2,
    quic,

    pub const json_field_names = .{
        .any = "ANY",
        .tcp = "TCP",
        .udp = "UDP",
        .icmp = "ICMP",
        .http = "HTTP",
        .ftp = "FTP",
        .tls = "TLS",
        .smb = "SMB",
        .dns = "DNS",
        .dcerpc = "DCERPC",
        .ssh = "SSH",
        .smtp = "SMTP",
        .imap = "IMAP",
        .msn = "MSN",
        .krb5 = "KRB5",
        .ikev2 = "IKEV2",
        .tftp = "TFTP",
        .ntp = "NTP",
        .dhcp = "DHCP",
        .http2 = "HTTP2",
        .quic = "QUIC",
    };
};
