const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const ExecutorState = @import("executor_state.zig").ExecutorState;
const ExecutorsSummary = @import("executors_summary.zig").ExecutorsSummary;

pub const ListExecutorsInput = struct {
    /// A filter for a specific executor state. A description of each state follows.
    ///
    /// `CREATING` - The executor is being started, including acquiring
    /// resources.
    ///
    /// `CREATED` - The executor has been started.
    ///
    /// `REGISTERED` - The executor has been registered.
    ///
    /// `TERMINATING` - The executor is in the process of shutting down.
    ///
    /// `TERMINATED` - The executor is no longer running.
    ///
    /// `FAILED` - Due to a failure, the executor is no longer running.
    executor_state_filter: ?ExecutorState = null,

    /// The maximum number of executors to return.
    max_results: ?i32 = null,

    /// A token generated by the Athena service that specifies where to continue
    /// pagination if a previous request was truncated. To obtain the next set of
    /// pages, pass in
    /// the `NextToken` from the response object of the previous page call.
    next_token: ?[]const u8 = null,

    /// The session ID.
    session_id: []const u8,

    pub const json_field_names = .{
        .executor_state_filter = "ExecutorStateFilter",
        .max_results = "MaxResults",
        .next_token = "NextToken",
        .session_id = "SessionId",
    };
};

pub const ListExecutorsOutput = struct {
    /// Contains summary information about the executor.
    executors_summary: ?[]const ExecutorsSummary = null,

    /// A token generated by the Athena service that specifies where to continue
    /// pagination if a previous request was truncated. To obtain the next set of
    /// pages, pass in
    /// the `NextToken` from the response object of the previous page call.
    next_token: ?[]const u8 = null,

    /// The session ID.
    session_id: []const u8,

    pub const json_field_names = .{
        .executors_summary = "ExecutorsSummary",
        .next_token = "NextToken",
        .session_id = "SessionId",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: ListExecutorsInput, options: CallOptions) !ListExecutorsOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "athena", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: ListExecutorsInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("athena", "Athena", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "AmazonAthena.ListExecutors");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !ListExecutorsOutput {
    _ = status;
    _ = headers;
    return aws.json.parseJsonObject(ListExecutorsOutput, body, allocator);
}
