const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const ServiceError = @import("errors.zig").ServiceError;
const TableMetadata = @import("table_metadata.zig").TableMetadata;

pub const ListTableMetadataInput = struct {
    /// The name of the data catalog for which table metadata should be returned.
    catalog_name: []const u8,

    /// The name of the database for which table metadata should be returned.
    database_name: []const u8,

    /// A regex filter that pattern-matches table names. If no expression is
    /// supplied,
    /// metadata for all tables are listed.
    expression: ?[]const u8 = null,

    /// Specifies the maximum number of results to return.
    max_results: ?i32 = null,

    /// A token generated by the Athena service that specifies where to continue
    /// pagination if a previous request was truncated. To obtain the next set of
    /// pages, pass in
    /// the NextToken from the response object of the previous page call.
    next_token: ?[]const u8 = null,

    /// The name of the workgroup for which the metadata is being fetched. Required
    /// if
    /// requesting an IAM Identity Center enabled Glue Data Catalog.
    work_group: ?[]const u8 = null,

    pub const json_field_names = .{
        .catalog_name = "CatalogName",
        .database_name = "DatabaseName",
        .expression = "Expression",
        .max_results = "MaxResults",
        .next_token = "NextToken",
        .work_group = "WorkGroup",
    };
};

pub const ListTableMetadataOutput = struct {
    /// A token generated by the Athena service that specifies where to continue
    /// pagination if a previous request was truncated. To obtain the next set of
    /// pages, pass in
    /// the NextToken from the response object of the previous page call.
    next_token: ?[]const u8 = null,

    /// A list of table metadata.
    table_metadata_list: ?[]const TableMetadata = null,

    pub const json_field_names = .{
        .next_token = "NextToken",
        .table_metadata_list = "TableMetadataList",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: ListTableMetadataInput, options: CallOptions) !ListTableMetadataOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "athena");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: ListTableMetadataInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("athena", "Athena", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(host);
    request.method = .POST;
    request.path = "/";
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "AmazonAthena.ListTableMetadata");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !ListTableMetadataOutput {
    _ = status;
    _ = headers;
    if (body.len == 0) return .{};
    return aws.json.parseJsonObject(ListTableMetadataOutput, body, allocator);
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "InternalServerException")) {
        return .{ .arena = arena, .kind = .{ .internal_server_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidRequestException")) {
        return .{ .arena = arena, .kind = .{ .invalid_request_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MetadataException")) {
        return .{ .arena = arena, .kind = .{ .metadata_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .resource_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "SessionAlreadyExistsException")) {
        return .{ .arena = arena, .kind = .{ .session_already_exists_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TooManyRequestsException")) {
        return .{ .arena = arena, .kind = .{ .too_many_requests_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
