const SessionSummary = @import("session_summary.zig").SessionSummary;

pub const ListSessionsResponse = struct {
    /// A token generated by the Athena service that specifies where to continue
    /// pagination if a previous request was truncated. To obtain the next set of
    /// pages, pass in
    /// the `NextToken` from the response object of the previous page call.
    next_token: ?[]const u8 = null,

    /// A list of sessions.
    sessions: ?[]const SessionSummary = null,

    pub const json_field_names = .{
        .next_token = "NextToken",
        .sessions = "Sessions",
    };
};
