pub const AutomationExecutionStatus = enum {
    pending,
    inprogress,
    waiting,
    success,
    timedout,
    cancelling,
    cancelled,
    failed,
    pending_approval,
    approved,
    rejected,
    scheduled,
    runbook_inprogress,
    pending_change_calendar_override,
    change_calendar_override_approved,
    change_calendar_override_rejected,
    completed_with_success,
    completed_with_failure,
    exited,

    pub const json_field_names = .{
        .pending = "PENDING",
        .inprogress = "INPROGRESS",
        .waiting = "WAITING",
        .success = "SUCCESS",
        .timedout = "TIMEDOUT",
        .cancelling = "CANCELLING",
        .cancelled = "CANCELLED",
        .failed = "FAILED",
        .pending_approval = "PENDING_APPROVAL",
        .approved = "APPROVED",
        .rejected = "REJECTED",
        .scheduled = "SCHEDULED",
        .runbook_inprogress = "RUNBOOK_INPROGRESS",
        .pending_change_calendar_override = "PENDING_CHANGE_CALENDAR_OVERRIDE",
        .change_calendar_override_approved = "CHANGE_CALENDAR_OVERRIDE_APPROVED",
        .change_calendar_override_rejected = "CHANGE_CALENDAR_OVERRIDE_REJECTED",
        .completed_with_success = "COMPLETED_WITH_SUCCESS",
        .completed_with_failure = "COMPLETED_WITH_FAILURE",
        .exited = "EXITED",
    };
};
