pub const DocumentType = enum {
    command,
    policy,
    automation,
    session,
    package,
    application_configuration,
    application_configuration_schema,
    deployment_strategy,
    change_calendar,
    change_template,
    problem_analysis,
    problem_analysis_template,
    cloud_formation,
    conformance_pack_template,
    quick_setup,
    manual_approval_policy,
    auto_approval_policy,

    pub const json_field_names = .{
        .command = "Command",
        .policy = "Policy",
        .automation = "Automation",
        .session = "Session",
        .package = "Package",
        .application_configuration = "ApplicationConfiguration",
        .application_configuration_schema = "ApplicationConfigurationSchema",
        .deployment_strategy = "DeploymentStrategy",
        .change_calendar = "ChangeCalendar",
        .change_template = "ChangeTemplate",
        .problem_analysis = "ProblemAnalysis",
        .problem_analysis_template = "ProblemAnalysisTemplate",
        .cloud_formation = "CloudFormation",
        .conformance_pack_template = "ConformancePackTemplate",
        .quick_setup = "QuickSetup",
        .manual_approval_policy = "ManualApprovalPolicy",
        .auto_approval_policy = "AutoApprovalPolicy",
    };
};
