pub const NodeFilterKey = enum {
    agent_type,
    agent_version,
    computer_name,
    instance_id,
    instance_status,
    ip_address,
    managed_status,
    platform_name,
    platform_type,
    platform_version,
    resource_type,
    organizational_unit_id,
    organizational_unit_path,
    region,
    account_id,

    pub const json_field_names = .{
        .agent_type = "AGENT_TYPE",
        .agent_version = "AGENT_VERSION",
        .computer_name = "COMPUTER_NAME",
        .instance_id = "INSTANCE_ID",
        .instance_status = "INSTANCE_STATUS",
        .ip_address = "IP_ADDRESS",
        .managed_status = "MANAGED_STATUS",
        .platform_name = "PLATFORM_NAME",
        .platform_type = "PLATFORM_TYPE",
        .platform_version = "PLATFORM_VERSION",
        .resource_type = "RESOURCE_TYPE",
        .organizational_unit_id = "ORGANIZATIONAL_UNIT_ID",
        .organizational_unit_path = "ORGANIZATIONAL_UNIT_PATH",
        .region = "REGION",
        .account_id = "ACCOUNT_ID",
    };
};
