pub const OperatingSystem = enum {
    windows,
    amazon_linux,
    amazon_linux_2,
    amazon_linux_2022,
    ubuntu,
    redhat_enterprise_linux,
    suse,
    cent_os,
    oracle_linux,
    debian,
    mac_os,
    raspbian,
    rocky_linux,
    alma_linux,
    amazon_linux_2023,

    pub const json_field_names = .{
        .windows = "Windows",
        .amazon_linux = "AmazonLinux",
        .amazon_linux_2 = "AmazonLinux2",
        .amazon_linux_2022 = "AmazonLinux2022",
        .ubuntu = "Ubuntu",
        .redhat_enterprise_linux = "RedhatEnterpriseLinux",
        .suse = "Suse",
        .cent_os = "CentOS",
        .oracle_linux = "OracleLinux",
        .debian = "Debian",
        .mac_os = "MacOS",
        .raspbian = "Raspbian",
        .rocky_linux = "Rocky_Linux",
        .alma_linux = "AlmaLinux",
        .amazon_linux_2023 = "AmazonLinux2023",
    };
};
