pub const OpsItemStatus = enum {
    open,
    in_progress,
    resolved,
    pending,
    timed_out,
    cancelling,
    cancelled,
    failed,
    completed_with_success,
    completed_with_failure,
    scheduled,
    runbook_in_progress,
    pending_change_calendar_override,
    change_calendar_override_approved,
    change_calendar_override_rejected,
    pending_approval,
    approved,
    revoked,
    rejected,
    closed,

    pub const json_field_names = .{
        .open = "OPEN",
        .in_progress = "IN_PROGRESS",
        .resolved = "RESOLVED",
        .pending = "PENDING",
        .timed_out = "TIMED_OUT",
        .cancelling = "CANCELLING",
        .cancelled = "CANCELLED",
        .failed = "FAILED",
        .completed_with_success = "COMPLETED_WITH_SUCCESS",
        .completed_with_failure = "COMPLETED_WITH_FAILURE",
        .scheduled = "SCHEDULED",
        .runbook_in_progress = "RUNBOOK_IN_PROGRESS",
        .pending_change_calendar_override = "PENDING_CHANGE_CALENDAR_OVERRIDE",
        .change_calendar_override_approved = "CHANGE_CALENDAR_OVERRIDE_APPROVED",
        .change_calendar_override_rejected = "CHANGE_CALENDAR_OVERRIDE_REJECTED",
        .pending_approval = "PENDING_APPROVAL",
        .approved = "APPROVED",
        .revoked = "REVOKED",
        .rejected = "REJECTED",
        .closed = "CLOSED",
    };
};
