const std = @import("std");

pub const OpsItemFilterKey = enum {
    status,
    created_by,
    source,
    priority,
    title,
    opsitem_id,
    created_time,
    last_modified_time,
    actual_start_time,
    actual_end_time,
    planned_start_time,
    planned_end_time,
    operational_data,
    operational_data_key,
    operational_data_value,
    resource_id,
    automation_id,
    category,
    severity,
    opsitem_type,
    access_request_requester_arn,
    access_request_requester_id,
    access_request_approver_arn,
    access_request_approver_id,
    access_request_source_account_id,
    access_request_source_ops_item_id,
    access_request_source_region,
    access_request_is_replica,
    access_request_target_resource_id,
    change_request_requester_arn,
    change_request_requester_name,
    change_request_approver_arn,
    change_request_approver_name,
    change_request_template,
    change_request_targets_resource_group,
    insight_type,
    account_id,

    pub const json_field_names = .{
        .status = "Status",
        .created_by = "CreatedBy",
        .source = "Source",
        .priority = "Priority",
        .title = "Title",
        .opsitem_id = "OpsItemId",
        .created_time = "CreatedTime",
        .last_modified_time = "LastModifiedTime",
        .actual_start_time = "ActualStartTime",
        .actual_end_time = "ActualEndTime",
        .planned_start_time = "PlannedStartTime",
        .planned_end_time = "PlannedEndTime",
        .operational_data = "OperationalData",
        .operational_data_key = "OperationalDataKey",
        .operational_data_value = "OperationalDataValue",
        .resource_id = "ResourceId",
        .automation_id = "AutomationId",
        .category = "Category",
        .severity = "Severity",
        .opsitem_type = "OpsItemType",
        .access_request_requester_arn = "AccessRequestByRequesterArn",
        .access_request_requester_id = "AccessRequestByRequesterId",
        .access_request_approver_arn = "AccessRequestByApproverArn",
        .access_request_approver_id = "AccessRequestByApproverId",
        .access_request_source_account_id = "AccessRequestBySourceAccountId",
        .access_request_source_ops_item_id = "AccessRequestBySourceOpsItemId",
        .access_request_source_region = "AccessRequestBySourceRegion",
        .access_request_is_replica = "AccessRequestByIsReplica",
        .access_request_target_resource_id = "AccessRequestByTargetResourceId",
        .change_request_requester_arn = "ChangeRequestByRequesterArn",
        .change_request_requester_name = "ChangeRequestByRequesterName",
        .change_request_approver_arn = "ChangeRequestByApproverArn",
        .change_request_approver_name = "ChangeRequestByApproverName",
        .change_request_template = "ChangeRequestByTemplate",
        .change_request_targets_resource_group = "ChangeRequestByTargetsResourceGroup",
        .insight_type = "InsightByType",
        .account_id = "AccountId",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .status => "Status",
            .created_by => "CreatedBy",
            .source => "Source",
            .priority => "Priority",
            .title => "Title",
            .opsitem_id => "OpsItemId",
            .created_time => "CreatedTime",
            .last_modified_time => "LastModifiedTime",
            .actual_start_time => "ActualStartTime",
            .actual_end_time => "ActualEndTime",
            .planned_start_time => "PlannedStartTime",
            .planned_end_time => "PlannedEndTime",
            .operational_data => "OperationalData",
            .operational_data_key => "OperationalDataKey",
            .operational_data_value => "OperationalDataValue",
            .resource_id => "ResourceId",
            .automation_id => "AutomationId",
            .category => "Category",
            .severity => "Severity",
            .opsitem_type => "OpsItemType",
            .access_request_requester_arn => "AccessRequestByRequesterArn",
            .access_request_requester_id => "AccessRequestByRequesterId",
            .access_request_approver_arn => "AccessRequestByApproverArn",
            .access_request_approver_id => "AccessRequestByApproverId",
            .access_request_source_account_id => "AccessRequestBySourceAccountId",
            .access_request_source_ops_item_id => "AccessRequestBySourceOpsItemId",
            .access_request_source_region => "AccessRequestBySourceRegion",
            .access_request_is_replica => "AccessRequestByIsReplica",
            .access_request_target_resource_id => "AccessRequestByTargetResourceId",
            .change_request_requester_arn => "ChangeRequestByRequesterArn",
            .change_request_requester_name => "ChangeRequestByRequesterName",
            .change_request_approver_arn => "ChangeRequestByApproverArn",
            .change_request_approver_name => "ChangeRequestByApproverName",
            .change_request_template => "ChangeRequestByTemplate",
            .change_request_targets_resource_group => "ChangeRequestByTargetsResourceGroup",
            .insight_type => "InsightByType",
            .account_id => "AccountId",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
