pub const OpsItemFilterKey = enum {
    status,
    created_by,
    source,
    priority,
    title,
    opsitem_id,
    created_time,
    last_modified_time,
    actual_start_time,
    actual_end_time,
    planned_start_time,
    planned_end_time,
    operational_data,
    operational_data_key,
    operational_data_value,
    resource_id,
    automation_id,
    category,
    severity,
    opsitem_type,
    access_request_requester_arn,
    access_request_requester_id,
    access_request_approver_arn,
    access_request_approver_id,
    access_request_source_account_id,
    access_request_source_ops_item_id,
    access_request_source_region,
    access_request_is_replica,
    access_request_target_resource_id,
    change_request_requester_arn,
    change_request_requester_name,
    change_request_approver_arn,
    change_request_approver_name,
    change_request_template,
    change_request_targets_resource_group,
    insight_type,
    account_id,

    pub const json_field_names = .{
        .status = "STATUS",
        .created_by = "CREATED_BY",
        .source = "SOURCE",
        .priority = "PRIORITY",
        .title = "TITLE",
        .opsitem_id = "OPSITEM_ID",
        .created_time = "CREATED_TIME",
        .last_modified_time = "LAST_MODIFIED_TIME",
        .actual_start_time = "ACTUAL_START_TIME",
        .actual_end_time = "ACTUAL_END_TIME",
        .planned_start_time = "PLANNED_START_TIME",
        .planned_end_time = "PLANNED_END_TIME",
        .operational_data = "OPERATIONAL_DATA",
        .operational_data_key = "OPERATIONAL_DATA_KEY",
        .operational_data_value = "OPERATIONAL_DATA_VALUE",
        .resource_id = "RESOURCE_ID",
        .automation_id = "AUTOMATION_ID",
        .category = "CATEGORY",
        .severity = "SEVERITY",
        .opsitem_type = "OPSITEM_TYPE",
        .access_request_requester_arn = "ACCESS_REQUEST_REQUESTER_ARN",
        .access_request_requester_id = "ACCESS_REQUEST_REQUESTER_ID",
        .access_request_approver_arn = "ACCESS_REQUEST_APPROVER_ARN",
        .access_request_approver_id = "ACCESS_REQUEST_APPROVER_ID",
        .access_request_source_account_id = "ACCESS_REQUEST_SOURCE_ACCOUNT_ID",
        .access_request_source_ops_item_id = "ACCESS_REQUEST_SOURCE_OPS_ITEM_ID",
        .access_request_source_region = "ACCESS_REQUEST_SOURCE_REGION",
        .access_request_is_replica = "ACCESS_REQUEST_IS_REPLICA",
        .access_request_target_resource_id = "ACCESS_REQUEST_TARGET_RESOURCE_ID",
        .change_request_requester_arn = "CHANGE_REQUEST_REQUESTER_ARN",
        .change_request_requester_name = "CHANGE_REQUEST_REQUESTER_NAME",
        .change_request_approver_arn = "CHANGE_REQUEST_APPROVER_ARN",
        .change_request_approver_name = "CHANGE_REQUEST_APPROVER_NAME",
        .change_request_template = "CHANGE_REQUEST_TEMPLATE",
        .change_request_targets_resource_group = "CHANGE_REQUEST_TARGETS_RESOURCE_GROUP",
        .insight_type = "INSIGHT_TYPE",
        .account_id = "ACCOUNT_ID",
    };
};
