pub const PatchFilterKey = enum {
    arch,
    advisory_id,
    bugzilla_id,
    patch_set,
    product,
    product_family,
    classification,
    cve_id,
    epoch,
    msrc_severity,
    name,
    patch_id,
    section,
    priority,
    repository,
    release,
    severity,
    security,
    version,

    pub const json_field_names = .{
        .arch = "Arch",
        .advisory_id = "AdvisoryId",
        .bugzilla_id = "BugzillaId",
        .patch_set = "PatchSet",
        .product = "Product",
        .product_family = "ProductFamily",
        .classification = "Classification",
        .cve_id = "CVEId",
        .epoch = "Epoch",
        .msrc_severity = "MsrcSeverity",
        .name = "Name",
        .patch_id = "PatchId",
        .section = "Section",
        .priority = "Priority",
        .repository = "Repository",
        .release = "Release",
        .severity = "Severity",
        .security = "Security",
        .version = "Version",
    };
};
