const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const ExecutionInputs = @import("execution_inputs.zig").ExecutionInputs;

pub const StartExecutionPreviewInput = struct {
    /// The name of the Automation runbook to run. The result of the execution
    /// preview indicates
    /// what the impact would be of running this runbook.
    document_name: []const u8,

    /// The version of the Automation runbook to run. The default value is
    /// `$DEFAULT`.
    document_version: ?[]const u8 = null,

    /// Information about the inputs that can be specified for the preview
    /// operation.
    execution_inputs: ?ExecutionInputs = null,

    pub const json_field_names = .{
        .document_name = "DocumentName",
        .document_version = "DocumentVersion",
        .execution_inputs = "ExecutionInputs",
    };
};

pub const StartExecutionPreviewOutput = struct {
    /// The ID of the execution preview generated by the system.
    execution_preview_id: ?[]const u8 = null,

    pub const json_field_names = .{
        .execution_preview_id = "ExecutionPreviewId",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: StartExecutionPreviewInput, options: CallOptions) !StartExecutionPreviewOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "ssm", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: StartExecutionPreviewInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("ssm", "SSM", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "AmazonSSM.StartExecutionPreview");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !StartExecutionPreviewOutput {
    _ = status;
    _ = headers;
    if (body.len == 0) return .{};
    return aws.json.parseJsonObject(StartExecutionPreviewOutput, body, allocator);
}
