const std = @import("std");

pub const LanguageCode = enum {
    af_za,
    ar_ae,
    ar_sa,
    da_dk,
    de_ch,
    de_de,
    en_ab,
    en_au,
    en_gb,
    en_ie,
    en_in,
    en_us,
    en_wl,
    es_es,
    es_us,
    fa_ir,
    fr_ca,
    fr_fr,
    he_il,
    hi_in,
    id_id,
    it_it,
    ja_jp,
    ko_kr,
    ms_my,
    nl_nl,
    pt_br,
    pt_pt,
    ru_ru,
    ta_in,
    te_in,
    tr_tr,
    zh_cn,
    zh_tw,
    th_th,
    en_za,
    en_nz,
    vi_vn,
    sv_se,
    ab_ge,
    ast_es,
    az_az,
    ba_ru,
    be_by,
    bg_bg,
    bn_in,
    bs_ba,
    ca_es,
    ckb_iq,
    ckb_ir,
    cs_cz,
    cy_wl,
    el_gr,
    et_ee,
    et_et,
    eu_es,
    fi_fi,
    gl_es,
    gu_in,
    ha_ng,
    hr_hr,
    hu_hu,
    hy_am,
    is_is,
    ka_ge,
    kab_dz,
    kk_kz,
    kn_in,
    ky_kg,
    lg_in,
    lt_lt,
    lv_lv,
    mhr_ru,
    mi_nz,
    mk_mk,
    ml_in,
    mn_mn,
    mr_in,
    mt_mt,
    no_no,
    or_in,
    pa_in,
    pl_pl,
    ps_af,
    ro_ro,
    rw_rw,
    si_lk,
    sk_sk,
    sl_si,
    so_so,
    sr_rs,
    su_id,
    sw_bi,
    sw_ke,
    sw_rw,
    sw_tz,
    sw_ug,
    tl_ph,
    tt_ru,
    ug_cn,
    uk_ua,
    uz_uz,
    wo_sn,
    zh_hk,
    zu_za,

    pub const json_field_names = .{
        .af_za = "af-ZA",
        .ar_ae = "ar-AE",
        .ar_sa = "ar-SA",
        .da_dk = "da-DK",
        .de_ch = "de-CH",
        .de_de = "de-DE",
        .en_ab = "en-AB",
        .en_au = "en-AU",
        .en_gb = "en-GB",
        .en_ie = "en-IE",
        .en_in = "en-IN",
        .en_us = "en-US",
        .en_wl = "en-WL",
        .es_es = "es-ES",
        .es_us = "es-US",
        .fa_ir = "fa-IR",
        .fr_ca = "fr-CA",
        .fr_fr = "fr-FR",
        .he_il = "he-IL",
        .hi_in = "hi-IN",
        .id_id = "id-ID",
        .it_it = "it-IT",
        .ja_jp = "ja-JP",
        .ko_kr = "ko-KR",
        .ms_my = "ms-MY",
        .nl_nl = "nl-NL",
        .pt_br = "pt-BR",
        .pt_pt = "pt-PT",
        .ru_ru = "ru-RU",
        .ta_in = "ta-IN",
        .te_in = "te-IN",
        .tr_tr = "tr-TR",
        .zh_cn = "zh-CN",
        .zh_tw = "zh-TW",
        .th_th = "th-TH",
        .en_za = "en-ZA",
        .en_nz = "en-NZ",
        .vi_vn = "vi-VN",
        .sv_se = "sv-SE",
        .ab_ge = "ab-GE",
        .ast_es = "ast-ES",
        .az_az = "az-AZ",
        .ba_ru = "ba-RU",
        .be_by = "be-BY",
        .bg_bg = "bg-BG",
        .bn_in = "bn-IN",
        .bs_ba = "bs-BA",
        .ca_es = "ca-ES",
        .ckb_iq = "ckb-IQ",
        .ckb_ir = "ckb-IR",
        .cs_cz = "cs-CZ",
        .cy_wl = "cy-WL",
        .el_gr = "el-GR",
        .et_ee = "et-EE",
        .et_et = "et-ET",
        .eu_es = "eu-ES",
        .fi_fi = "fi-FI",
        .gl_es = "gl-ES",
        .gu_in = "gu-IN",
        .ha_ng = "ha-NG",
        .hr_hr = "hr-HR",
        .hu_hu = "hu-HU",
        .hy_am = "hy-AM",
        .is_is = "is-IS",
        .ka_ge = "ka-GE",
        .kab_dz = "kab-DZ",
        .kk_kz = "kk-KZ",
        .kn_in = "kn-IN",
        .ky_kg = "ky-KG",
        .lg_in = "lg-IN",
        .lt_lt = "lt-LT",
        .lv_lv = "lv-LV",
        .mhr_ru = "mhr-RU",
        .mi_nz = "mi-NZ",
        .mk_mk = "mk-MK",
        .ml_in = "ml-IN",
        .mn_mn = "mn-MN",
        .mr_in = "mr-IN",
        .mt_mt = "mt-MT",
        .no_no = "no-NO",
        .or_in = "or-IN",
        .pa_in = "pa-IN",
        .pl_pl = "pl-PL",
        .ps_af = "ps-AF",
        .ro_ro = "ro-RO",
        .rw_rw = "rw-RW",
        .si_lk = "si-LK",
        .sk_sk = "sk-SK",
        .sl_si = "sl-SI",
        .so_so = "so-SO",
        .sr_rs = "sr-RS",
        .su_id = "su-ID",
        .sw_bi = "sw-BI",
        .sw_ke = "sw-KE",
        .sw_rw = "sw-RW",
        .sw_tz = "sw-TZ",
        .sw_ug = "sw-UG",
        .tl_ph = "tl-PH",
        .tt_ru = "tt-RU",
        .ug_cn = "ug-CN",
        .uk_ua = "uk-UA",
        .uz_uz = "uz-UZ",
        .wo_sn = "wo-SN",
        .zh_hk = "zh-HK",
        .zu_za = "zu-ZA",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .af_za => "af-ZA",
            .ar_ae => "ar-AE",
            .ar_sa => "ar-SA",
            .da_dk => "da-DK",
            .de_ch => "de-CH",
            .de_de => "de-DE",
            .en_ab => "en-AB",
            .en_au => "en-AU",
            .en_gb => "en-GB",
            .en_ie => "en-IE",
            .en_in => "en-IN",
            .en_us => "en-US",
            .en_wl => "en-WL",
            .es_es => "es-ES",
            .es_us => "es-US",
            .fa_ir => "fa-IR",
            .fr_ca => "fr-CA",
            .fr_fr => "fr-FR",
            .he_il => "he-IL",
            .hi_in => "hi-IN",
            .id_id => "id-ID",
            .it_it => "it-IT",
            .ja_jp => "ja-JP",
            .ko_kr => "ko-KR",
            .ms_my => "ms-MY",
            .nl_nl => "nl-NL",
            .pt_br => "pt-BR",
            .pt_pt => "pt-PT",
            .ru_ru => "ru-RU",
            .ta_in => "ta-IN",
            .te_in => "te-IN",
            .tr_tr => "tr-TR",
            .zh_cn => "zh-CN",
            .zh_tw => "zh-TW",
            .th_th => "th-TH",
            .en_za => "en-ZA",
            .en_nz => "en-NZ",
            .vi_vn => "vi-VN",
            .sv_se => "sv-SE",
            .ab_ge => "ab-GE",
            .ast_es => "ast-ES",
            .az_az => "az-AZ",
            .ba_ru => "ba-RU",
            .be_by => "be-BY",
            .bg_bg => "bg-BG",
            .bn_in => "bn-IN",
            .bs_ba => "bs-BA",
            .ca_es => "ca-ES",
            .ckb_iq => "ckb-IQ",
            .ckb_ir => "ckb-IR",
            .cs_cz => "cs-CZ",
            .cy_wl => "cy-WL",
            .el_gr => "el-GR",
            .et_ee => "et-EE",
            .et_et => "et-ET",
            .eu_es => "eu-ES",
            .fi_fi => "fi-FI",
            .gl_es => "gl-ES",
            .gu_in => "gu-IN",
            .ha_ng => "ha-NG",
            .hr_hr => "hr-HR",
            .hu_hu => "hu-HU",
            .hy_am => "hy-AM",
            .is_is => "is-IS",
            .ka_ge => "ka-GE",
            .kab_dz => "kab-DZ",
            .kk_kz => "kk-KZ",
            .kn_in => "kn-IN",
            .ky_kg => "ky-KG",
            .lg_in => "lg-IN",
            .lt_lt => "lt-LT",
            .lv_lv => "lv-LV",
            .mhr_ru => "mhr-RU",
            .mi_nz => "mi-NZ",
            .mk_mk => "mk-MK",
            .ml_in => "ml-IN",
            .mn_mn => "mn-MN",
            .mr_in => "mr-IN",
            .mt_mt => "mt-MT",
            .no_no => "no-NO",
            .or_in => "or-IN",
            .pa_in => "pa-IN",
            .pl_pl => "pl-PL",
            .ps_af => "ps-AF",
            .ro_ro => "ro-RO",
            .rw_rw => "rw-RW",
            .si_lk => "si-LK",
            .sk_sk => "sk-SK",
            .sl_si => "sl-SI",
            .so_so => "so-SO",
            .sr_rs => "sr-RS",
            .su_id => "su-ID",
            .sw_bi => "sw-BI",
            .sw_ke => "sw-KE",
            .sw_rw => "sw-RW",
            .sw_tz => "sw-TZ",
            .sw_ug => "sw-UG",
            .tl_ph => "tl-PH",
            .tt_ru => "tt-RU",
            .ug_cn => "ug-CN",
            .uk_ua => "uk-UA",
            .uz_uz => "uz-UZ",
            .wo_sn => "wo-SN",
            .zh_hk => "zh-HK",
            .zu_za => "zu-ZA",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
