/// Temporal Filter Strength
pub const TemporalFilterStrength = enum {
    auto,
    strength_1,
    strength_2,
    strength_3,
    strength_4,
    strength_5,
    strength_6,
    strength_7,
    strength_8,
    strength_9,
    strength_10,
    strength_11,
    strength_12,
    strength_13,
    strength_14,
    strength_15,
    strength_16,

    pub const json_field_names = .{
        .auto = "AUTO",
        .strength_1 = "STRENGTH_1",
        .strength_2 = "STRENGTH_2",
        .strength_3 = "STRENGTH_3",
        .strength_4 = "STRENGTH_4",
        .strength_5 = "STRENGTH_5",
        .strength_6 = "STRENGTH_6",
        .strength_7 = "STRENGTH_7",
        .strength_8 = "STRENGTH_8",
        .strength_9 = "STRENGTH_9",
        .strength_10 = "STRENGTH_10",
        .strength_11 = "STRENGTH_11",
        .strength_12 = "STRENGTH_12",
        .strength_13 = "STRENGTH_13",
        .strength_14 = "STRENGTH_14",
        .strength_15 = "STRENGTH_15",
        .strength_16 = "STRENGTH_16",
    };
};
