/// The token consumption statistics for language model operations during
/// evaluation. Provides detailed breakdown of input, output, and total tokens
/// used for cost tracking and performance monitoring.
pub const TokenUsage = struct {
    /// The number of tokens consumed for input processing during the evaluation.
    /// Includes tokens from the evaluation prompt, agent traces, and any additional
    /// context provided to the evaluator model.
    input_tokens: ?i32,

    /// The number of tokens generated by the evaluator model in its response.
    /// Includes tokens for the score, explanation, and any additional output
    /// produced during the evaluation process.
    output_tokens: ?i32,

    /// The total number of tokens consumed during the evaluation, calculated as the
    /// sum of input and output tokens. Used for cost calculation and rate limiting
    /// within the service limits.
    total_tokens: ?i32,

    pub const json_field_names = .{
        .input_tokens = "inputTokens",
        .output_tokens = "outputTokens",
        .total_tokens = "totalTokens",
    };
};
