/// The output for a single tool description recommendation.
pub const ToolDescriptionOutput = struct {
    /// The optimized tool description text generated by the recommendation.
    recommended_tool_description: ?[]const u8 = null,

    /// The name of the tool.
    tool_name: []const u8,

    pub const json_field_names = .{
        .recommended_tool_description = "recommendedToolDescription",
        .tool_name = "toolName",
    };
};
