pub const FlowNodeType = enum {
    input,
    output,
    knowledge_base,
    condition,
    lex,
    prompt,
    lambda_function,
    storage,
    agent,
    retrieval,
    iterator,
    collector,
    inline_code,
    loop,
    loop_input,
    loop_controller,

    pub const json_field_names = .{
        .input = "INPUT",
        .output = "OUTPUT",
        .knowledge_base = "KNOWLEDGE_BASE",
        .condition = "CONDITION",
        .lex = "LEX",
        .prompt = "PROMPT",
        .lambda_function = "LAMBDA_FUNCTION",
        .storage = "STORAGE",
        .agent = "AGENT",
        .retrieval = "RETRIEVAL",
        .iterator = "ITERATOR",
        .collector = "COLLECTOR",
        .inline_code = "INLINE_CODE",
        .loop = "LOOP",
        .loop_input = "LOOP_INPUT",
        .loop_controller = "LOOP_CONTROLLER",
    };
};
