const std = @import("std");

pub const FlowValidationType = enum {
    cyclic_connection,
    duplicate_connections,
    duplicate_condition_expression,
    unreachable_node,
    unknown_connection_source,
    unknown_connection_source_output,
    unknown_connection_target,
    unknown_connection_target_input,
    unknown_connection_condition,
    malformed_condition_expression,
    malformed_node_input_expression,
    mismatched_node_input_type,
    mismatched_node_output_type,
    incompatible_connection_data_type,
    missing_connection_configuration,
    missing_default_condition,
    missing_ending_nodes,
    missing_node_configuration,
    missing_node_input,
    missing_node_output,
    missing_starting_nodes,
    multiple_node_input_connections,
    unfulfilled_node_input,
    unsatisfied_connection_conditions,
    unspecified,
    unknown_node_input,
    unknown_node_output,
    missing_loop_input_node,
    missing_loop_controller_node,
    multiple_loop_input_nodes,
    multiple_loop_controller_nodes,
    loop_incompatible_node_type,
    invalid_loop_boundary,

    pub const json_field_names = .{
        .cyclic_connection = "CyclicConnection",
        .duplicate_connections = "DuplicateConnections",
        .duplicate_condition_expression = "DuplicateConditionExpression",
        .unreachable_node = "UnreachableNode",
        .unknown_connection_source = "UnknownConnectionSource",
        .unknown_connection_source_output = "UnknownConnectionSourceOutput",
        .unknown_connection_target = "UnknownConnectionTarget",
        .unknown_connection_target_input = "UnknownConnectionTargetInput",
        .unknown_connection_condition = "UnknownConnectionCondition",
        .malformed_condition_expression = "MalformedConditionExpression",
        .malformed_node_input_expression = "MalformedNodeInputExpression",
        .mismatched_node_input_type = "MismatchedNodeInputType",
        .mismatched_node_output_type = "MismatchedNodeOutputType",
        .incompatible_connection_data_type = "IncompatibleConnectionDataType",
        .missing_connection_configuration = "MissingConnectionConfiguration",
        .missing_default_condition = "MissingDefaultCondition",
        .missing_ending_nodes = "MissingEndingNodes",
        .missing_node_configuration = "MissingNodeConfiguration",
        .missing_node_input = "MissingNodeInput",
        .missing_node_output = "MissingNodeOutput",
        .missing_starting_nodes = "MissingStartingNodes",
        .multiple_node_input_connections = "MultipleNodeInputConnections",
        .unfulfilled_node_input = "UnfulfilledNodeInput",
        .unsatisfied_connection_conditions = "UnsatisfiedConnectionConditions",
        .unspecified = "Unspecified",
        .unknown_node_input = "UnknownNodeInput",
        .unknown_node_output = "UnknownNodeOutput",
        .missing_loop_input_node = "MissingLoopInputNode",
        .missing_loop_controller_node = "MissingLoopControllerNode",
        .multiple_loop_input_nodes = "MultipleLoopInputNodes",
        .multiple_loop_controller_nodes = "MultipleLoopControllerNodes",
        .loop_incompatible_node_type = "LoopIncompatibleNodeType",
        .invalid_loop_boundary = "InvalidLoopBoundary",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .cyclic_connection => "CyclicConnection",
            .duplicate_connections => "DuplicateConnections",
            .duplicate_condition_expression => "DuplicateConditionExpression",
            .unreachable_node => "UnreachableNode",
            .unknown_connection_source => "UnknownConnectionSource",
            .unknown_connection_source_output => "UnknownConnectionSourceOutput",
            .unknown_connection_target => "UnknownConnectionTarget",
            .unknown_connection_target_input => "UnknownConnectionTargetInput",
            .unknown_connection_condition => "UnknownConnectionCondition",
            .malformed_condition_expression => "MalformedConditionExpression",
            .malformed_node_input_expression => "MalformedNodeInputExpression",
            .mismatched_node_input_type => "MismatchedNodeInputType",
            .mismatched_node_output_type => "MismatchedNodeOutputType",
            .incompatible_connection_data_type => "IncompatibleConnectionDataType",
            .missing_connection_configuration => "MissingConnectionConfiguration",
            .missing_default_condition => "MissingDefaultCondition",
            .missing_ending_nodes => "MissingEndingNodes",
            .missing_node_configuration => "MissingNodeConfiguration",
            .missing_node_input => "MissingNodeInput",
            .missing_node_output => "MissingNodeOutput",
            .missing_starting_nodes => "MissingStartingNodes",
            .multiple_node_input_connections => "MultipleNodeInputConnections",
            .unfulfilled_node_input => "UnfulfilledNodeInput",
            .unsatisfied_connection_conditions => "UnsatisfiedConnectionConditions",
            .unspecified => "Unspecified",
            .unknown_node_input => "UnknownNodeInput",
            .unknown_node_output => "UnknownNodeOutput",
            .missing_loop_input_node => "MissingLoopInputNode",
            .missing_loop_controller_node => "MissingLoopControllerNode",
            .multiple_loop_input_nodes => "MultipleLoopInputNodes",
            .multiple_loop_controller_nodes => "MultipleLoopControllerNodes",
            .loop_incompatible_node_type => "LoopIncompatibleNodeType",
            .invalid_loop_boundary => "InvalidLoopBoundary",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
