pub const FlowValidationType = enum {
    cyclic_connection,
    duplicate_connections,
    duplicate_condition_expression,
    unreachable_node,
    unknown_connection_source,
    unknown_connection_source_output,
    unknown_connection_target,
    unknown_connection_target_input,
    unknown_connection_condition,
    malformed_condition_expression,
    malformed_node_input_expression,
    mismatched_node_input_type,
    mismatched_node_output_type,
    incompatible_connection_data_type,
    missing_connection_configuration,
    missing_default_condition,
    missing_ending_nodes,
    missing_node_configuration,
    missing_node_input,
    missing_node_output,
    missing_starting_nodes,
    multiple_node_input_connections,
    unfulfilled_node_input,
    unsatisfied_connection_conditions,
    unspecified,
    unknown_node_input,
    unknown_node_output,
    missing_loop_input_node,
    missing_loop_controller_node,
    multiple_loop_input_nodes,
    multiple_loop_controller_nodes,
    loop_incompatible_node_type,
    invalid_loop_boundary,

    pub const json_field_names = .{
        .cyclic_connection = "CYCLIC_CONNECTION",
        .duplicate_connections = "DUPLICATE_CONNECTIONS",
        .duplicate_condition_expression = "DUPLICATE_CONDITION_EXPRESSION",
        .unreachable_node = "UNREACHABLE_NODE",
        .unknown_connection_source = "UNKNOWN_CONNECTION_SOURCE",
        .unknown_connection_source_output = "UNKNOWN_CONNECTION_SOURCE_OUTPUT",
        .unknown_connection_target = "UNKNOWN_CONNECTION_TARGET",
        .unknown_connection_target_input = "UNKNOWN_CONNECTION_TARGET_INPUT",
        .unknown_connection_condition = "UNKNOWN_CONNECTION_CONDITION",
        .malformed_condition_expression = "MALFORMED_CONDITION_EXPRESSION",
        .malformed_node_input_expression = "MALFORMED_NODE_INPUT_EXPRESSION",
        .mismatched_node_input_type = "MISMATCHED_NODE_INPUT_TYPE",
        .mismatched_node_output_type = "MISMATCHED_NODE_OUTPUT_TYPE",
        .incompatible_connection_data_type = "INCOMPATIBLE_CONNECTION_DATA_TYPE",
        .missing_connection_configuration = "MISSING_CONNECTION_CONFIGURATION",
        .missing_default_condition = "MISSING_DEFAULT_CONDITION",
        .missing_ending_nodes = "MISSING_ENDING_NODES",
        .missing_node_configuration = "MISSING_NODE_CONFIGURATION",
        .missing_node_input = "MISSING_NODE_INPUT",
        .missing_node_output = "MISSING_NODE_OUTPUT",
        .missing_starting_nodes = "MISSING_STARTING_NODES",
        .multiple_node_input_connections = "MULTIPLE_NODE_INPUT_CONNECTIONS",
        .unfulfilled_node_input = "UNFULFILLED_NODE_INPUT",
        .unsatisfied_connection_conditions = "UNSATISFIED_CONNECTION_CONDITIONS",
        .unspecified = "UNSPECIFIED",
        .unknown_node_input = "UNKNOWN_NODE_INPUT",
        .unknown_node_output = "UNKNOWN_NODE_OUTPUT",
        .missing_loop_input_node = "MISSING_LOOP_INPUT_NODE",
        .missing_loop_controller_node = "MISSING_LOOP_CONTROLLER_NODE",
        .multiple_loop_input_nodes = "MULTIPLE_LOOP_INPUT_NODES",
        .multiple_loop_controller_nodes = "MULTIPLE_LOOP_CONTROLLER_NODES",
        .loop_incompatible_node_type = "LOOP_INCOMPATIBLE_NODE_TYPE",
        .invalid_loop_boundary = "INVALID_LOOP_BOUNDARY",
    };
};
