const RecommendationLifecycleStage = @import("recommendation_lifecycle_stage.zig").RecommendationLifecycleStage;
const RecommendationPillar = @import("recommendation_pillar.zig").RecommendationPillar;
const RecommendationPillarSpecificAggregates = @import("recommendation_pillar_specific_aggregates.zig").RecommendationPillarSpecificAggregates;
const RecommendationResourcesAggregates = @import("recommendation_resources_aggregates.zig").RecommendationResourcesAggregates;
const RecommendationSource = @import("recommendation_source.zig").RecommendationSource;
const RecommendationStatus = @import("recommendation_status.zig").RecommendationStatus;
const StatusReason = @import("status_reason.zig").StatusReason;
const RecommendationType = @import("recommendation_type.zig").RecommendationType;

/// Summary of Recommendation for an Account
pub const RecommendationSummary = struct {
    /// The ARN of the Recommendation
    arn: []const u8,

    /// The AWS Services that the Recommendation applies to
    aws_services: ?[]const []const u8 = null,

    /// The AWS Trusted Advisor Check ARN that relates to the Recommendation
    check_arn: ?[]const u8 = null,

    /// When the Recommendation was created, if created by AWS Trusted Advisor
    /// Priority
    created_at: ?i64 = null,

    /// The ID which identifies where the Recommendation was produced
    id: []const u8,

    /// When the Recommendation was last updated
    last_updated_at: ?i64 = null,

    /// The lifecycle stage from AWS Trusted Advisor Priority
    lifecycle_stage: ?RecommendationLifecycleStage = null,

    /// The name of the AWS Trusted Advisor Recommendation
    name: []const u8,

    /// The Pillars that the Recommendation is optimizing
    pillars: []const RecommendationPillar,

    /// The pillar aggregations for cost savings
    pillar_specific_aggregates: ?RecommendationPillarSpecificAggregates = null,

    /// An aggregation of all resources
    resources_aggregates: RecommendationResourcesAggregates,

    /// The source of the Recommendation
    source: RecommendationSource,

    /// The status of the Recommendation
    status: RecommendationStatus,

    /// This attribute provides additional details about potential discrepancies in
    /// check status determination.
    status_reason: ?StatusReason = null,

    /// Whether the Recommendation was automated or generated by AWS Trusted Advisor
    /// Priority
    @"type": RecommendationType,

    pub const json_field_names = .{
        .arn = "arn",
        .aws_services = "awsServices",
        .check_arn = "checkArn",
        .created_at = "createdAt",
        .id = "id",
        .last_updated_at = "lastUpdatedAt",
        .lifecycle_stage = "lifecycleStage",
        .name = "name",
        .pillars = "pillars",
        .pillar_specific_aggregates = "pillarSpecificAggregates",
        .resources_aggregates = "resourcesAggregates",
        .source = "source",
        .status = "status",
        .status_reason = "statusReason",
        .@"type" = "type",
    };
};
