const aws = @import("aws");
const std = @import("std");

const query_forecast = @import("query_forecast.zig");
const query_what_if_forecast = @import("query_what_if_forecast.zig");

pub const Client = struct {
    allocator: std.mem.Allocator,
    config: *aws.Config,
    http_client: aws.http.HttpClient,

    const Self = @This();
    pub const sdk_id = "forecastquery";

    pub fn init(allocator: std.mem.Allocator, config: *aws.Config) Self {
        return .{
            .allocator = allocator,
            .config = config,
            .http_client = aws.http.HttpClient.init(allocator),
        };
    }

    pub fn initWithOptions(allocator: std.mem.Allocator, config: *aws.Config, options: aws.http.RequestOptions) Self {
        return .{
            .allocator = allocator,
            .config = config,
            .http_client = aws.http.HttpClient.initWithOptions(allocator, options),
        };
    }

    pub fn deinit(self: *Self) void {
        self.http_client.deinit();
    }

    /// Retrieves a forecast for a single item, filtered by the supplied criteria.
    ///
    /// The criteria is a key-value pair. The key is either `item_id` (or the
    /// equivalent non-timestamp, non-target field) from the `TARGET_TIME_SERIES`
    /// dataset,
    /// or one of the forecast dimensions specified as part of the
    /// `FeaturizationConfig`
    /// object.
    ///
    /// By default, `QueryForecast` returns the complete date range for the filtered
    /// forecast. You can request a specific date range.
    ///
    /// To get the full forecast, use the
    /// [CreateForecastExportJob](https://docs.aws.amazon.com/en_us/forecast/latest/dg/API_CreateForecastExportJob.html) operation.
    ///
    /// The forecasts generated by Amazon Forecast are in the same timezone as the
    /// dataset that was
    /// used to create the predictor.
    pub fn queryForecast(self: *Self, allocator: std.mem.Allocator, input: query_forecast.QueryForecastInput, options: query_forecast.Options) !query_forecast.QueryForecastOutput {
        return query_forecast.execute(self, allocator, input, options);
    }

    /// Retrieves a what-if forecast.
    pub fn queryWhatIfForecast(self: *Self, allocator: std.mem.Allocator, input: query_what_if_forecast.QueryWhatIfForecastInput, options: query_what_if_forecast.Options) !query_what_if_forecast.QueryWhatIfForecastOutput {
        return query_what_if_forecast.execute(self, allocator, input, options);
    }
};
