pub const ErrorResourceType = enum {
    environment,
    application,
    route,
    service,
    transit_gateway,
    transit_gateway_attachment,
    api_gateway,
    nlb,
    target_group,
    load_balancer_listener,
    vpc_link,
    lambda,
    vpc,
    subnet,
    route_table,
    security_group,
    vpc_endpoint_service_configuration,
    resource_share,
    iam_role,

    pub const json_field_names = .{
        .environment = "ENVIRONMENT",
        .application = "APPLICATION",
        .route = "ROUTE",
        .service = "SERVICE",
        .transit_gateway = "TRANSIT_GATEWAY",
        .transit_gateway_attachment = "TRANSIT_GATEWAY_ATTACHMENT",
        .api_gateway = "API_GATEWAY",
        .nlb = "NLB",
        .target_group = "TARGET_GROUP",
        .load_balancer_listener = "LOAD_BALANCER_LISTENER",
        .vpc_link = "VPC_LINK",
        .lambda = "LAMBDA",
        .vpc = "VPC",
        .subnet = "SUBNET",
        .route_table = "ROUTE_TABLE",
        .security_group = "SECURITY_GROUP",
        .vpc_endpoint_service_configuration = "VPC_ENDPOINT_SERVICE_CONFIGURATION",
        .resource_share = "RESOURCE_SHARE",
        .iam_role = "IAM_ROLE",
    };
};
