const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const SourceUrlType = @import("source_url_type.zig").SourceUrlType;
const JobSummary = @import("job_summary.zig").JobSummary;

pub const StartDeploymentInput = struct {
    /// The unique ID for an Amplify app.
    app_id: []const u8,

    /// The name of the branch to use for the deployment job.
    branch_name: []const u8,

    /// The job ID for this deployment that is generated by the `CreateDeployment`
    /// request.
    job_id: ?[]const u8 = null,

    /// The source URL for the deployment that is used when calling
    /// `StartDeployment` without `CreateDeployment`. The source URL
    /// can be either an HTTP GET URL that is publicly accessible and downloads a
    /// single .zip
    /// file, or an Amazon S3 bucket and prefix.
    source_url: ?[]const u8 = null,

    /// The type of source specified by the `sourceURL`. If the value is
    /// `ZIP`, the source is a .zip file. If the value is
    /// `BUCKET_PREFIX`, the source is an Amazon S3 bucket and prefix. If
    /// no value is specified, the default is `ZIP`.
    source_url_type: ?SourceUrlType = null,

    pub const json_field_names = .{
        .app_id = "appId",
        .branch_name = "branchName",
        .job_id = "jobId",
        .source_url = "sourceUrl",
        .source_url_type = "sourceUrlType",
    };
};

pub const StartDeploymentOutput = struct {
    /// The summary for the job.
    job_summary: ?JobSummary = null,

    pub const json_field_names = .{
        .job_summary = "jobSummary",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: StartDeploymentInput, options: CallOptions) !StartDeploymentOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "amplify", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: StartDeploymentInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("amplify", "Amplify", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/apps/");
    try path_buf.appendSlice(allocator, input.app_id);
    try path_buf.appendSlice(allocator, "/branches/");
    try path_buf.appendSlice(allocator, input.branch_name);
    try path_buf.appendSlice(allocator, "/deployments/start");
    const path = try path_buf.toOwnedSlice(allocator);

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.job_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"jobId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.source_url) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"sourceUrl\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.source_url_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"sourceUrlType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !StartDeploymentOutput {
    const result: StartDeploymentOutput = try aws.json.parseJsonObject(
        StartDeploymentOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
