pub const Status = enum {
    creating,
    active,
    deleting,
    updating,
    vpc_endpoint_limit_exceeded,
    ip_address_limit_exceeded,
    invalid_security_group_id,
    invalid_subnet_id,
    inaccessible_encryption_creds,
    inaccessible_secret_arn,
    inaccessible_vpc_endpoint,
    incompatible_network,
    merging,
    modifying,
    splitting,
    copying,
    starting,
    stopping,
    stopped,
    maintenance,
    inaccessible_encryption_credentials_recoverable,

    pub const json_field_names = .{
        .creating = "CREATING",
        .active = "ACTIVE",
        .deleting = "DELETING",
        .updating = "UPDATING",
        .vpc_endpoint_limit_exceeded = "VPC_ENDPOINT_LIMIT_EXCEEDED",
        .ip_address_limit_exceeded = "IP_ADDRESS_LIMIT_EXCEEDED",
        .invalid_security_group_id = "INVALID_SECURITY_GROUP_ID",
        .invalid_subnet_id = "INVALID_SUBNET_ID",
        .inaccessible_encryption_creds = "INACCESSIBLE_ENCRYPTION_CREDS",
        .inaccessible_secret_arn = "INACCESSIBLE_SECRET_ARN",
        .inaccessible_vpc_endpoint = "INACCESSIBLE_VPC_ENDPOINT",
        .incompatible_network = "INCOMPATIBLE_NETWORK",
        .merging = "MERGING",
        .modifying = "MODIFYING",
        .splitting = "SPLITTING",
        .copying = "COPYING",
        .starting = "STARTING",
        .stopping = "STOPPING",
        .stopped = "STOPPED",
        .maintenance = "MAINTENANCE",
        .inaccessible_encryption_credentials_recoverable = "INACCESSIBLE_ENCRYPTION_CREDENTIALS_RECOVERABLE",
    };
};
