/// The details about an event generated by an SaaS partner.
pub const PutPartnerEventsRequestEntry = struct {
    /// A valid JSON string. There is no other schema imposed. The JSON string may
    /// contain fields
    /// and nested subobjects.
    detail: ?[]const u8,

    /// A free-form string used to decide what fields to expect in the event detail.
    detail_type: ?[]const u8,

    /// Amazon Web Services resources, identified by Amazon Resource Name (ARN),
    /// which the event primarily
    /// concerns. Any number, including zero, may be present.
    resources: ?[]const []const u8,

    /// The event source that is generating the entry.
    source: ?[]const u8,

    /// The date and time of the event.
    time: ?i64,

    pub const json_field_names = .{
        .detail = "Detail",
        .detail_type = "DetailType",
        .resources = "Resources",
        .source = "Source",
        .time = "Time",
    };
};
