const std = @import("std");

pub const ErrorCode = enum {
    activation_key_expired,
    activation_key_invalid,
    activation_key_not_found,
    gateway_internal_error,
    gateway_not_connected,
    gateway_not_found,
    gateway_proxy_network_connection_busy,
    authentication_failure,
    bandwidth_throttle_schedule_not_found,
    blocked,
    cannot_export_snapshot,
    chap_credential_not_found,
    disk_already_allocated,
    disk_does_not_exist,
    disk_size_greater_than_volume_max_size,
    disk_size_less_than_volume_size,
    disk_size_not_gig_aligned,
    duplicate_certificate_info,
    duplicate_schedule,
    endpoint_not_found,
    iam_not_supported,
    initiator_invalid,
    initiator_not_found,
    internal_error,
    invalid_gateway,
    invalid_endpoint,
    invalid_parameters,
    invalid_schedule,
    local_storage_limit_exceeded,
    lun_already_allocated_,
    lun_invalid,
    join_domain_in_progress,
    maximum_content_length_exceeded,
    maximum_tape_cartridge_count_exceeded,
    maximum_volume_count_exceeded,
    network_configuration_changed,
    no_disks_available,
    not_implemented,
    not_supported,
    operation_aborted,
    outdated_gateway,
    parameters_not_implemented,
    region_invalid,
    request_timeout,
    service_unavailable,
    snapshot_deleted,
    snapshot_id_invalid,
    snapshot_in_progress,
    snapshot_not_found,
    snapshot_schedule_not_found,
    staging_area_full,
    storage_failure,
    tape_cartridge_not_found,
    target_already_exists,
    target_invalid,
    target_not_found,
    unauthorized_operation,
    volume_already_exists,
    volume_id_invalid,
    volume_in_use,
    volume_not_found,
    volume_not_ready,

    pub const json_field_names = .{
        .activation_key_expired = "ActivationKeyExpired",
        .activation_key_invalid = "ActivationKeyInvalid",
        .activation_key_not_found = "ActivationKeyNotFound",
        .gateway_internal_error = "GatewayInternalError",
        .gateway_not_connected = "GatewayNotConnected",
        .gateway_not_found = "GatewayNotFound",
        .gateway_proxy_network_connection_busy = "GatewayProxyNetworkConnectionBusy",
        .authentication_failure = "AuthenticationFailure",
        .bandwidth_throttle_schedule_not_found = "BandwidthThrottleScheduleNotFound",
        .blocked = "Blocked",
        .cannot_export_snapshot = "CannotExportSnapshot",
        .chap_credential_not_found = "ChapCredentialNotFound",
        .disk_already_allocated = "DiskAlreadyAllocated",
        .disk_does_not_exist = "DiskDoesNotExist",
        .disk_size_greater_than_volume_max_size = "DiskSizeGreaterThanVolumeMaxSize",
        .disk_size_less_than_volume_size = "DiskSizeLessThanVolumeSize",
        .disk_size_not_gig_aligned = "DiskSizeNotGigAligned",
        .duplicate_certificate_info = "DuplicateCertificateInfo",
        .duplicate_schedule = "DuplicateSchedule",
        .endpoint_not_found = "EndpointNotFound",
        .iam_not_supported = "IAMNotSupported",
        .initiator_invalid = "InitiatorInvalid",
        .initiator_not_found = "InitiatorNotFound",
        .internal_error = "InternalError",
        .invalid_gateway = "InvalidGateway",
        .invalid_endpoint = "InvalidEndpoint",
        .invalid_parameters = "InvalidParameters",
        .invalid_schedule = "InvalidSchedule",
        .local_storage_limit_exceeded = "LocalStorageLimitExceeded",
        .lun_already_allocated_ = "LunAlreadyAllocated ",
        .lun_invalid = "LunInvalid",
        .join_domain_in_progress = "JoinDomainInProgress",
        .maximum_content_length_exceeded = "MaximumContentLengthExceeded",
        .maximum_tape_cartridge_count_exceeded = "MaximumTapeCartridgeCountExceeded",
        .maximum_volume_count_exceeded = "MaximumVolumeCountExceeded",
        .network_configuration_changed = "NetworkConfigurationChanged",
        .no_disks_available = "NoDisksAvailable",
        .not_implemented = "NotImplemented",
        .not_supported = "NotSupported",
        .operation_aborted = "OperationAborted",
        .outdated_gateway = "OutdatedGateway",
        .parameters_not_implemented = "ParametersNotImplemented",
        .region_invalid = "RegionInvalid",
        .request_timeout = "RequestTimeout",
        .service_unavailable = "ServiceUnavailable",
        .snapshot_deleted = "SnapshotDeleted",
        .snapshot_id_invalid = "SnapshotIdInvalid",
        .snapshot_in_progress = "SnapshotInProgress",
        .snapshot_not_found = "SnapshotNotFound",
        .snapshot_schedule_not_found = "SnapshotScheduleNotFound",
        .staging_area_full = "StagingAreaFull",
        .storage_failure = "StorageFailure",
        .tape_cartridge_not_found = "TapeCartridgeNotFound",
        .target_already_exists = "TargetAlreadyExists",
        .target_invalid = "TargetInvalid",
        .target_not_found = "TargetNotFound",
        .unauthorized_operation = "UnauthorizedOperation",
        .volume_already_exists = "VolumeAlreadyExists",
        .volume_id_invalid = "VolumeIdInvalid",
        .volume_in_use = "VolumeInUse",
        .volume_not_found = "VolumeNotFound",
        .volume_not_ready = "VolumeNotReady",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .activation_key_expired => "ActivationKeyExpired",
            .activation_key_invalid => "ActivationKeyInvalid",
            .activation_key_not_found => "ActivationKeyNotFound",
            .gateway_internal_error => "GatewayInternalError",
            .gateway_not_connected => "GatewayNotConnected",
            .gateway_not_found => "GatewayNotFound",
            .gateway_proxy_network_connection_busy => "GatewayProxyNetworkConnectionBusy",
            .authentication_failure => "AuthenticationFailure",
            .bandwidth_throttle_schedule_not_found => "BandwidthThrottleScheduleNotFound",
            .blocked => "Blocked",
            .cannot_export_snapshot => "CannotExportSnapshot",
            .chap_credential_not_found => "ChapCredentialNotFound",
            .disk_already_allocated => "DiskAlreadyAllocated",
            .disk_does_not_exist => "DiskDoesNotExist",
            .disk_size_greater_than_volume_max_size => "DiskSizeGreaterThanVolumeMaxSize",
            .disk_size_less_than_volume_size => "DiskSizeLessThanVolumeSize",
            .disk_size_not_gig_aligned => "DiskSizeNotGigAligned",
            .duplicate_certificate_info => "DuplicateCertificateInfo",
            .duplicate_schedule => "DuplicateSchedule",
            .endpoint_not_found => "EndpointNotFound",
            .iam_not_supported => "IAMNotSupported",
            .initiator_invalid => "InitiatorInvalid",
            .initiator_not_found => "InitiatorNotFound",
            .internal_error => "InternalError",
            .invalid_gateway => "InvalidGateway",
            .invalid_endpoint => "InvalidEndpoint",
            .invalid_parameters => "InvalidParameters",
            .invalid_schedule => "InvalidSchedule",
            .local_storage_limit_exceeded => "LocalStorageLimitExceeded",
            .lun_already_allocated_ => "LunAlreadyAllocated ",
            .lun_invalid => "LunInvalid",
            .join_domain_in_progress => "JoinDomainInProgress",
            .maximum_content_length_exceeded => "MaximumContentLengthExceeded",
            .maximum_tape_cartridge_count_exceeded => "MaximumTapeCartridgeCountExceeded",
            .maximum_volume_count_exceeded => "MaximumVolumeCountExceeded",
            .network_configuration_changed => "NetworkConfigurationChanged",
            .no_disks_available => "NoDisksAvailable",
            .not_implemented => "NotImplemented",
            .not_supported => "NotSupported",
            .operation_aborted => "OperationAborted",
            .outdated_gateway => "OutdatedGateway",
            .parameters_not_implemented => "ParametersNotImplemented",
            .region_invalid => "RegionInvalid",
            .request_timeout => "RequestTimeout",
            .service_unavailable => "ServiceUnavailable",
            .snapshot_deleted => "SnapshotDeleted",
            .snapshot_id_invalid => "SnapshotIdInvalid",
            .snapshot_in_progress => "SnapshotInProgress",
            .snapshot_not_found => "SnapshotNotFound",
            .snapshot_schedule_not_found => "SnapshotScheduleNotFound",
            .staging_area_full => "StagingAreaFull",
            .storage_failure => "StorageFailure",
            .tape_cartridge_not_found => "TapeCartridgeNotFound",
            .target_already_exists => "TargetAlreadyExists",
            .target_invalid => "TargetInvalid",
            .target_not_found => "TargetNotFound",
            .unauthorized_operation => "UnauthorizedOperation",
            .volume_already_exists => "VolumeAlreadyExists",
            .volume_id_invalid => "VolumeIdInvalid",
            .volume_in_use => "VolumeInUse",
            .volume_not_found => "VolumeNotFound",
            .volume_not_ready => "VolumeNotReady",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
