const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const DeletionMode = @import("deletion_mode.zig").DeletionMode;
const serde = @import("serde.zig");

pub const DeleteStackInput = struct {
    /// A unique identifier for this `DeleteStack` request. Specify this token if
    /// you
    /// plan to retry requests so that CloudFormation knows that you're not
    /// attempting to delete a stack
    /// with the same name. You might retry `DeleteStack` requests to ensure that
    /// CloudFormation successfully received them.
    ///
    /// All events initiated by a given stack operation are assigned the same client
    /// request
    /// token, which you can use to track operations. For example, if you execute a
    /// `CreateStack` operation with the token `token1`, then all the
    /// `StackEvents` generated by that operation will have
    /// `ClientRequestToken` set as `token1`.
    ///
    /// In the console, stack operations display the client request token on the
    /// Events tab. Stack
    /// operations that are initiated from the console use the token format
    /// *Console-StackOperation-ID*, which helps you easily identify the stack
    /// operation . For example, if you create a stack using the console, each stack
    /// event would be
    /// assigned the same token in the following format:
    /// `Console-CreateStack-7f59c3cf-00d2-40c7-b2ff-e75db0987002`.
    client_request_token: ?[]const u8 = null,

    /// Specifies the deletion mode for the stack. Possible values are:
    ///
    /// * `STANDARD` - Use the standard behavior. Specifying this value is the same
    /// as not specifying this parameter.
    ///
    /// * `FORCE_DELETE_STACK` - Delete the stack if it's stuck in a
    /// `DELETE_FAILED` state due to resource deletion failure.
    deletion_mode: ?DeletionMode = null,

    /// For stacks in the `DELETE_FAILED` state, a list of resource logical IDs that
    /// are associated with the resources you want to retain. During deletion,
    /// CloudFormation deletes the
    /// stack but doesn't delete the retained resources.
    ///
    /// Retaining resources is useful when you can't delete a resource, such as a
    /// non-empty S3
    /// bucket, but you want to delete the stack.
    retain_resources: ?[]const []const u8 = null,

    /// The Amazon Resource Name (ARN) of an IAM role that CloudFormation assumes to
    /// delete the
    /// stack. CloudFormation uses the role's credentials to make calls on your
    /// behalf.
    ///
    /// If you don't specify a value, CloudFormation uses the role that was
    /// previously associated with
    /// the stack. If no role is available, CloudFormation uses a temporary session
    /// that's generated from
    /// your user credentials.
    role_arn: ?[]const u8 = null,

    /// The name or the unique stack ID that's associated with the stack.
    stack_name: []const u8,
};

pub const DeleteStackOutput = struct {};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: DeleteStackInput, options: CallOptions) !DeleteStackOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "cloudformation", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: DeleteStackInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("cloudformation", "CloudFormation", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var body_buf: std.ArrayList(u8) = .empty;

    try body_buf.appendSlice(allocator, "Action=DeleteStack&Version=2010-05-15");
    if (input.client_request_token) |v| {
        try body_buf.appendSlice(allocator, "&ClientRequestToken=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    if (input.deletion_mode) |v| {
        try body_buf.appendSlice(allocator, "&DeletionMode=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v.wireName());
    }
    if (input.retain_resources) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            var prefix_buf: [256]u8 = undefined;
            const field_prefix = std.fmt.bufPrint(&prefix_buf, "&RetainResources.member.{d}=", .{n}) catch continue;
            try body_buf.appendSlice(allocator, field_prefix);
            try aws.url.appendUrlEncoded(allocator, &body_buf, item);
        }
    }
    if (input.role_arn) |v| {
        try body_buf.appendSlice(allocator, "&RoleARN=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    try body_buf.appendSlice(allocator, "&StackName=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.stack_name);

    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-www-form-urlencoded");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !DeleteStackOutput {
    _ = status;
    _ = headers;
    _ = body;
    _ = allocator;
    const result: DeleteStackOutput = .{};

    return result;
}
