const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const assertionEncryptionModeType = @import("assertion_encryption_mode_type.zig").assertionEncryptionModeType;
const Tag = @import("tag.zig").Tag;
const serde = @import("serde.zig");

pub const CreateSAMLProviderInput = struct {
    /// The private key generated from your external identity provider. The private
    /// key must
    /// be a .pem file that uses AES-GCM or AES-CBC encryption algorithm to decrypt
    /// SAML
    /// assertions.
    add_private_key: ?[]const u8 = null,

    /// Specifies the encryption setting for the SAML provider.
    assertion_encryption_mode: ?assertionEncryptionModeType = null,

    /// The name of the provider to create.
    ///
    /// This parameter allows (through its [regex
    /// pattern](http://wikipedia.org/wiki/regex)) a string of characters consisting
    /// of upper and lowercase alphanumeric
    /// characters with no spaces. You can also include any of the following
    /// characters: _+=,.@-
    name: []const u8,

    /// An XML document generated by an identity provider (IdP) that supports SAML
    /// 2.0. The
    /// document includes the issuer's name, expiration information, and keys that
    /// can be used
    /// to validate the SAML authentication response (assertions) that are received
    /// from the
    /// IdP. You must generate the metadata document using the identity management
    /// software that
    /// is used as your organization's IdP.
    ///
    /// For more information, see [About SAML 2.0-based
    /// federation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html) in the *IAM User Guide*
    saml_metadata_document: []const u8,

    /// A list of tags that you want to attach to the new IAM SAML provider.
    /// Each tag consists of a key name and an associated value. For more
    /// information about tagging, see [Tagging IAM
    /// resources](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html) in
    /// the
    /// *IAM User Guide*.
    ///
    /// If any one of the tags is invalid or if you exceed the allowed maximum
    /// number of tags, then the entire request
    /// fails and the resource is not created.
    tags: ?[]const Tag = null,
};

pub const CreateSAMLProviderOutput = struct {
    /// The Amazon Resource Name (ARN) of the new SAML provider resource in IAM.
    saml_provider_arn: ?[]const u8 = null,

    /// A list of tags that are attached to the new IAM SAML provider. The returned
    /// list of tags is sorted by tag key.
    /// For more information about tagging, see [Tagging IAM
    /// resources](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html) in
    /// the
    /// *IAM User Guide*.
    tags: ?[]const Tag = null,
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateSAMLProviderInput, options: CallOptions) !CreateSAMLProviderOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "iam", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateSAMLProviderInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("iam", "IAM", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var body_buf: std.ArrayList(u8) = .empty;

    try body_buf.appendSlice(allocator, "Action=CreateSAMLProvider&Version=2010-05-08");
    if (input.add_private_key) |v| {
        try body_buf.appendSlice(allocator, "&AddPrivateKey=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    if (input.assertion_encryption_mode) |v| {
        try body_buf.appendSlice(allocator, "&AssertionEncryptionMode=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v.wireName());
    }
    try body_buf.appendSlice(allocator, "&Name=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.name);
    try body_buf.appendSlice(allocator, "&SAMLMetadataDocument=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.saml_metadata_document);
    if (input.tags) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            {
                var prefix_buf: [256]u8 = undefined;
                const field_prefix = std.fmt.bufPrint(&prefix_buf, "&Tags.member.{d}.Key=", .{n}) catch continue;
                try body_buf.appendSlice(allocator, field_prefix);
                try aws.url.appendUrlEncoded(allocator, &body_buf, item.key);
            }
            {
                var prefix_buf: [256]u8 = undefined;
                const field_prefix = std.fmt.bufPrint(&prefix_buf, "&Tags.member.{d}.Value=", .{n}) catch continue;
                try body_buf.appendSlice(allocator, field_prefix);
                try aws.url.appendUrlEncoded(allocator, &body_buf, item.value);
            }
        }
    }

    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-www-form-urlencoded");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateSAMLProviderOutput {
    _ = status;
    _ = headers;
    var reader = aws.xml.Reader.init(body);

    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "CreateSAMLProviderResult")) break;
            },
            else => {},
        }
    }

    var result: CreateSAMLProviderOutput = .{};
    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "SAMLProviderArn")) {
                    result.saml_provider_arn = try allocator.dupe(u8, try reader.readElementText());
                } else if (std.mem.eql(u8, e.local, "Tags")) {
                    result.tags = try serde.deserializetagListType(allocator, &reader, "member");
                } else {
                    try reader.skipElement();
                }
            },
            .element_end => break,
            else => {},
        }
    }

    return result;
}
