const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const sortKeyType = @import("sort_key_type.zig").sortKeyType;
const AccessDetail = @import("access_detail.zig").AccessDetail;
const ErrorDetails = @import("error_details.zig").ErrorDetails;
const jobStatusType = @import("job_status_type.zig").jobStatusType;
const serde = @import("serde.zig");

pub const GetOrganizationsAccessReportInput = struct {
    /// The identifier of the request generated by the
    /// [GenerateOrganizationsAccessReport](https://docs.aws.amazon.com/IAM/latest/APIReference/API_GenerateOrganizationsAccessReport.html) operation.
    job_id: []const u8,

    /// Use this parameter only when paginating results and only after
    /// you receive a response indicating that the results are truncated. Set it to
    /// the value of the
    /// `Marker` element in the response that you received to indicate where the
    /// next call
    /// should start.
    marker: ?[]const u8 = null,

    /// Use this only when paginating results to indicate the
    /// maximum number of items you want in the response. If additional items exist
    /// beyond the maximum
    /// you specify, the `IsTruncated` response element is `true`.
    ///
    /// If you do not include this parameter, the number of items defaults to 100.
    /// Note that
    /// IAM might return fewer results, even when there are more results available.
    /// In that case, the
    /// `IsTruncated` response element returns `true`, and `Marker`
    /// contains a value to include in the subsequent call that tells the service
    /// where to continue
    /// from.
    max_items: ?i32 = null,

    /// The key that is used to sort the results. If you choose the namespace key,
    /// the results
    /// are returned in alphabetical order. If you choose the time key, the results
    /// are sorted
    /// numerically by the date and time.
    sort_key: ?sortKeyType = null,
};

pub const GetOrganizationsAccessReportOutput = struct {
    /// An object that contains details about the most recent attempt to access the
    /// service.
    access_details: ?[]const AccessDetail = null,

    error_details: ?ErrorDetails = null,

    /// A flag that indicates whether there are more items to return. If your
    /// results were truncated, you can make a subsequent pagination request using
    /// the `Marker`
    /// request parameter to retrieve more items. Note that IAM might return fewer
    /// than the
    /// `MaxItems` number of results even when there are more results available. We
    /// recommend
    /// that you check `IsTruncated` after every call to ensure that you receive all
    /// your
    /// results.
    is_truncated: ?bool = null,

    /// The date and time, in [ISO 8601 date-time
    /// format](http://www.iso.org/iso/iso8601), when the generated report job was
    /// completed or failed.
    ///
    /// This field is null if the job is still in progress, as indicated by a job
    /// status value
    /// of `IN_PROGRESS`.
    job_completion_date: ?i64 = null,

    /// The date and time, in [ISO 8601 date-time
    /// format](http://www.iso.org/iso/iso8601), when the report job was created.
    job_creation_date: i64,

    /// The status of the job.
    job_status: jobStatusType,

    /// When `IsTruncated` is `true`, this element
    /// is present and contains the value to use for the `Marker` parameter in a
    /// subsequent
    /// pagination request.
    marker: ?[]const u8 = null,

    /// The number of services that the applicable SCPs allow account principals to
    /// access.
    number_of_services_accessible: ?i32 = null,

    /// The number of services that account principals are allowed but did not
    /// attempt to
    /// access.
    number_of_services_not_accessed: ?i32 = null,
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetOrganizationsAccessReportInput, options: CallOptions) !GetOrganizationsAccessReportOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "iam", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetOrganizationsAccessReportInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("iam", "IAM", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var body_buf: std.ArrayList(u8) = .empty;

    try body_buf.appendSlice(allocator, "Action=GetOrganizationsAccessReport&Version=2010-05-08");
    try body_buf.appendSlice(allocator, "&JobId=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.job_id);
    if (input.marker) |v| {
        try body_buf.appendSlice(allocator, "&Marker=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    if (input.max_items) |v| {
        try body_buf.appendSlice(allocator, "&MaxItems=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, std.fmt.allocPrint(allocator, "{d}", .{v}) catch "");
    }
    if (input.sort_key) |v| {
        try body_buf.appendSlice(allocator, "&SortKey=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v.wireName());
    }

    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-www-form-urlencoded");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetOrganizationsAccessReportOutput {
    _ = status;
    _ = headers;
    var reader = aws.xml.Reader.init(body);

    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "GetOrganizationsAccessReportResult")) break;
            },
            else => {},
        }
    }

    var result: GetOrganizationsAccessReportOutput = .{};
    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "AccessDetails")) {
                    result.access_details = try serde.deserializeAccessDetails(allocator, &reader, "member");
                } else if (std.mem.eql(u8, e.local, "ErrorDetails")) {
                    result.error_details = try serde.deserializeErrorDetails(allocator, &reader);
                } else if (std.mem.eql(u8, e.local, "IsTruncated")) {
                    result.is_truncated = std.mem.eql(u8, try reader.readElementText(), "true");
                } else if (std.mem.eql(u8, e.local, "JobCompletionDate")) {
                    result.job_completion_date = aws.date.parseIso8601(try reader.readElementText()) catch null;
                } else if (std.mem.eql(u8, e.local, "JobCreationDate")) {
                    result.job_creation_date = aws.date.parseIso8601(try reader.readElementText()) catch null;
                } else if (std.mem.eql(u8, e.local, "JobStatus")) {
                    result.job_status = jobStatusType.fromWireName(try reader.readElementText());
                } else if (std.mem.eql(u8, e.local, "Marker")) {
                    result.marker = try allocator.dupe(u8, try reader.readElementText());
                } else if (std.mem.eql(u8, e.local, "NumberOfServicesAccessible")) {
                    result.number_of_services_accessible = std.fmt.parseInt(i32, try reader.readElementText(), 10) catch null;
                } else if (std.mem.eql(u8, e.local, "NumberOfServicesNotAccessed")) {
                    result.number_of_services_not_accessed = std.fmt.parseInt(i32, try reader.readElementText(), 10) catch null;
                } else {
                    try reader.skipElement();
                }
            },
            .element_end => break,
            else => {},
        }
    }

    return result;
}
