const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const assertionEncryptionModeType = @import("assertion_encryption_mode_type.zig").assertionEncryptionModeType;

pub const UpdateSAMLProviderInput = struct {
    /// Specifies the new private key from your external identity provider. The
    /// private key
    /// must be a .pem file that uses AES-GCM or AES-CBC encryption algorithm to
    /// decrypt SAML
    /// assertions.
    add_private_key: ?[]const u8 = null,

    /// Specifies the encryption setting for the SAML provider.
    assertion_encryption_mode: ?assertionEncryptionModeType = null,

    /// The Key ID of the private key to remove.
    remove_private_key: ?[]const u8 = null,

    /// An XML document generated by an identity provider (IdP) that supports SAML
    /// 2.0. The
    /// document includes the issuer's name, expiration information, and keys that
    /// can be used
    /// to validate the SAML authentication response (assertions) that are received
    /// from the
    /// IdP. You must generate the metadata document using the identity management
    /// software that
    /// is used as your IdP.
    saml_metadata_document: ?[]const u8 = null,

    /// The Amazon Resource Name (ARN) of the SAML provider to update.
    ///
    /// For more information about ARNs, see [Amazon Resource Names
    /// (ARNs)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) in the *Amazon Web Services General Reference*.
    saml_provider_arn: []const u8,
};

pub const UpdateSAMLProviderOutput = struct {
    /// The Amazon Resource Name (ARN) of the SAML provider that was updated.
    saml_provider_arn: ?[]const u8 = null,
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: UpdateSAMLProviderInput, options: CallOptions) !UpdateSAMLProviderOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "iam", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: UpdateSAMLProviderInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("iam", "IAM", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var body_buf: std.ArrayList(u8) = .empty;

    try body_buf.appendSlice(allocator, "Action=UpdateSAMLProvider&Version=2010-05-08");
    if (input.add_private_key) |v| {
        try body_buf.appendSlice(allocator, "&AddPrivateKey=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    if (input.assertion_encryption_mode) |v| {
        try body_buf.appendSlice(allocator, "&AssertionEncryptionMode=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v.wireName());
    }
    if (input.remove_private_key) |v| {
        try body_buf.appendSlice(allocator, "&RemovePrivateKey=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    if (input.saml_metadata_document) |v| {
        try body_buf.appendSlice(allocator, "&SAMLMetadataDocument=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    try body_buf.appendSlice(allocator, "&SAMLProviderArn=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.saml_provider_arn);

    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-www-form-urlencoded");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !UpdateSAMLProviderOutput {
    _ = status;
    _ = headers;
    var reader = aws.xml.Reader.init(body);

    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "UpdateSAMLProviderResult")) break;
            },
            else => {},
        }
    }

    var result: UpdateSAMLProviderOutput = .{};
    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "SAMLProviderArn")) {
                    result.saml_provider_arn = try allocator.dupe(u8, try reader.readElementText());
                } else {
                    try reader.skipElement();
                }
            },
            .element_end => break,
            else => {},
        }
    }

    return result;
}
