pub const ResourceType = enum {
    ec2_instance,
    lambda_function,
    ebs_volume,
    ecs_service,
    ec2_auto_scaling_group,
    ec2_instance_savings_plans,
    compute_savings_plans,
    sage_maker_savings_plans,
    ec2_reserved_instances,
    rds_reserved_instances,
    open_search_reserved_instances,
    redshift_reserved_instances,
    elasti_cache_reserved_instances,
    rds_db_instance_storage,
    rds_db_instance,
    aurora_db_cluster_storage,
    dynamo_db_reserved_capacity,
    memory_db_reserved_instances,
    nat_gateway,

    pub const json_field_names = .{
        .ec2_instance = "EC2_INSTANCE",
        .lambda_function = "LAMBDA_FUNCTION",
        .ebs_volume = "EBS_VOLUME",
        .ecs_service = "ECS_SERVICE",
        .ec2_auto_scaling_group = "EC2_AUTO_SCALING_GROUP",
        .ec2_instance_savings_plans = "EC2_INSTANCE_SAVINGS_PLANS",
        .compute_savings_plans = "COMPUTE_SAVINGS_PLANS",
        .sage_maker_savings_plans = "SAGE_MAKER_SAVINGS_PLANS",
        .ec2_reserved_instances = "EC2_RESERVED_INSTANCES",
        .rds_reserved_instances = "RDS_RESERVED_INSTANCES",
        .open_search_reserved_instances = "OPEN_SEARCH_RESERVED_INSTANCES",
        .redshift_reserved_instances = "REDSHIFT_RESERVED_INSTANCES",
        .elasti_cache_reserved_instances = "ELASTI_CACHE_RESERVED_INSTANCES",
        .rds_db_instance_storage = "RDS_DB_INSTANCE_STORAGE",
        .rds_db_instance = "RDS_DB_INSTANCE",
        .aurora_db_cluster_storage = "AURORA_DB_CLUSTER_STORAGE",
        .dynamo_db_reserved_capacity = "DYNAMO_DB_RESERVED_CAPACITY",
        .memory_db_reserved_instances = "MEMORY_DB_RESERVED_INSTANCES",
        .nat_gateway = "NAT_GATEWAY",
    };
};
