const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const AwsAdditionalDetails = @import("aws_additional_details.zig").AwsAdditionalDetails;

pub const CreateTokenWithIAMInput = struct {
    /// Used only when calling this API for the JWT Bearer grant type. This value
    /// specifies the
    /// JSON Web Token (JWT) issued by a trusted token issuer. To authorize a
    /// trusted token issuer,
    /// configure the JWT Bearer GrantOptions for the application.
    assertion: ?[]const u8 = null,

    /// The unique identifier string for the client or application. This value is an
    /// application
    /// ARN that has OAuth grants configured.
    client_id: []const u8,

    /// Used only when calling this API for the Authorization Code grant type. This
    /// short-lived
    /// code is used to identify this authorization request. The code is obtained
    /// through a redirect
    /// from IAM Identity Center to a redirect URI persisted in the Authorization
    /// Code GrantOptions for the
    /// application.
    code: ?[]const u8 = null,

    /// Used only when calling this API for the Authorization Code grant type. This
    /// value is
    /// generated by the client and presented to validate the original code
    /// challenge value the client
    /// passed at authorization time.
    code_verifier: ?[]const u8 = null,

    /// Supports the following OAuth grant types: Authorization Code, Refresh Token,
    /// JWT Bearer,
    /// and Token Exchange. Specify one of the following values, depending on the
    /// grant type that you
    /// want:
    ///
    /// * Authorization Code - `authorization_code`
    ///
    /// * Refresh Token - `refresh_token`
    ///
    /// * JWT Bearer - `urn:ietf:params:oauth:grant-type:jwt-bearer`
    ///
    /// * Token Exchange - `urn:ietf:params:oauth:grant-type:token-exchange`
    grant_type: []const u8,

    /// Used only when calling this API for the Authorization Code grant type. This
    /// value
    /// specifies the location of the client or application that has registered to
    /// receive the
    /// authorization code.
    redirect_uri: ?[]const u8 = null,

    /// Used only when calling this API for the Refresh Token grant type. This token
    /// is used to
    /// refresh short-lived tokens, such as the access token, that might expire.
    ///
    /// For more information about the features and limitations of the current IAM
    /// Identity Center OIDC
    /// implementation, see *Considerations for Using this Guide* in the [IAM
    /// Identity Center
    /// OIDC API
    /// Reference](https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/Welcome.html).
    refresh_token: ?[]const u8 = null,

    /// Used only when calling this API for the Token Exchange grant type. This
    /// value specifies
    /// the type of token that the requester can receive. The following values are
    /// supported:
    ///
    /// * Access Token - `urn:ietf:params:oauth:token-type:access_token`
    ///
    /// * Refresh Token - `urn:ietf:params:oauth:token-type:refresh_token`
    requested_token_type: ?[]const u8 = null,

    /// The list of scopes for which authorization is requested. The access token
    /// that is issued
    /// is limited to the scopes that are granted. If the value is not specified,
    /// IAM Identity Center authorizes all
    /// scopes configured for the application, including the following default
    /// scopes:
    /// `openid`, `aws`, `sts:identity_context`.
    scope: ?[]const []const u8 = null,

    /// Used only when calling this API for the Token Exchange grant type. This
    /// value specifies
    /// the subject of the exchange. The value of the subject token must be an
    /// access token issued by
    /// IAM Identity Center to a different client or application. The access token
    /// must have authorized scopes that
    /// indicate the requested application as a target audience.
    subject_token: ?[]const u8 = null,

    /// Used only when calling this API for the Token Exchange grant type. This
    /// value specifies
    /// the type of token that is passed as the subject of the exchange. The
    /// following value is
    /// supported:
    ///
    /// * Access Token - `urn:ietf:params:oauth:token-type:access_token`
    subject_token_type: ?[]const u8 = null,

    pub const json_field_names = .{
        .assertion = "assertion",
        .client_id = "clientId",
        .code = "code",
        .code_verifier = "codeVerifier",
        .grant_type = "grantType",
        .redirect_uri = "redirectUri",
        .refresh_token = "refreshToken",
        .requested_token_type = "requestedTokenType",
        .scope = "scope",
        .subject_token = "subjectToken",
        .subject_token_type = "subjectTokenType",
    };
};

pub const CreateTokenWithIAMOutput = struct {
    /// A bearer token to access Amazon Web Services accounts and applications
    /// assigned to a user.
    access_token: ?[]const u8 = null,

    /// A structure containing information from IAM Identity Center managed user and
    /// group
    /// information.
    aws_additional_details: ?AwsAdditionalDetails = null,

    /// Indicates the time in seconds when an access token will expire.
    expires_in: ?i32 = null,

    /// A JSON Web Token (JWT) that identifies the user associated with the issued
    /// access token.
    id_token: ?[]const u8 = null,

    /// Indicates the type of tokens that are issued by IAM Identity Center. The
    /// following values are supported:
    ///
    /// * Access Token - `urn:ietf:params:oauth:token-type:access_token`
    ///
    /// * Refresh Token - `urn:ietf:params:oauth:token-type:refresh_token`
    issued_token_type: ?[]const u8 = null,

    /// A token that, if present, can be used to refresh a previously issued access
    /// token that
    /// might have expired.
    ///
    /// For more information about the features and limitations of the current IAM
    /// Identity Center OIDC
    /// implementation, see *Considerations for Using this Guide* in the [IAM
    /// Identity Center
    /// OIDC API
    /// Reference](https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/Welcome.html).
    refresh_token: ?[]const u8 = null,

    /// The list of scopes for which authorization is granted. The access token that
    /// is issued is
    /// limited to the scopes that are granted.
    scope: ?[]const []const u8 = null,

    /// Used to notify the requester that the returned token is an access token. The
    /// supported
    /// token type is `Bearer`.
    token_type: ?[]const u8 = null,

    pub const json_field_names = .{
        .access_token = "accessToken",
        .aws_additional_details = "awsAdditionalDetails",
        .expires_in = "expiresIn",
        .id_token = "idToken",
        .issued_token_type = "issuedTokenType",
        .refresh_token = "refreshToken",
        .scope = "scope",
        .token_type = "tokenType",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateTokenWithIAMInput, options: CallOptions) !CreateTokenWithIAMOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "sso-oauth", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateTokenWithIAMInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("oidc", "SSO OIDC", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/token";

    var query_buf: std.ArrayList(u8) = .empty;
    var query_has_prev = false;
    try query_buf.appendSlice(allocator, "aws_iam=t");
    query_has_prev = true;
    const query = try query_buf.toOwnedSlice(allocator);

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.assertion) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"assertion\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"clientId\":");
    try aws.json.writeValue(@TypeOf(input.client_id), input.client_id, allocator, &body_buf);
    has_prev = true;
    if (input.code) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"code\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.code_verifier) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"codeVerifier\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"grantType\":");
    try aws.json.writeValue(@TypeOf(input.grant_type), input.grant_type, allocator, &body_buf);
    has_prev = true;
    if (input.redirect_uri) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"redirectUri\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.refresh_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"refreshToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.requested_token_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"requestedTokenType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.scope) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"scope\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.subject_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"subjectToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.subject_token_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"subjectTokenType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    request.query = query;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateTokenWithIAMOutput {
    const result: CreateTokenWithIAMOutput = try aws.json.parseJsonObject(
        CreateTokenWithIAMOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
