const PrincipalType = @import("principal_type.zig").PrincipalType;
const StatusValues = @import("status_values.zig").StatusValues;
const TargetType = @import("target_type.zig").TargetType;

/// The status of the creation or deletion operation of an assignment that a
/// principal needs to access an account.
pub const AccountAssignmentOperationStatus = struct {
    /// The date that the permission set was created.
    created_date: ?i64 = null,

    /// The message that contains an error or exception in case of an operation
    /// failure.
    failure_reason: ?[]const u8 = null,

    /// The ARN of the permission set. For more information about ARNs, see [Amazon
    /// Resource Names (ARNs) and Amazon Web Services Service
    /// Namespaces](/general/latest/gr/aws-arns-and-namespaces.html) in the *Amazon
    /// Web Services General Reference*.
    permission_set_arn: ?[]const u8 = null,

    /// An identifier for an object in IAM Identity Center, such as a user or group.
    /// PrincipalIds are GUIDs (For example, f81d4fae-7dec-11d0-a765-00a0c91e6bf6).
    /// For more information about PrincipalIds in IAM Identity Center, see the [IAM
    /// Identity Center Identity Store API
    /// Reference](/singlesignon/latest/IdentityStoreAPIReference/welcome.html).
    principal_id: ?[]const u8 = null,

    /// The entity type for which the assignment will be created.
    principal_type: ?PrincipalType = null,

    /// The identifier for tracking the request operation that is generated by the
    /// universally unique identifier (UUID) workflow.
    request_id: ?[]const u8 = null,

    /// The status of the permission set provisioning process.
    status: ?StatusValues = null,

    /// TargetID is an Amazon Web Services account identifier, (For example,
    /// 123456789012).
    target_id: ?[]const u8 = null,

    /// The entity type for which the assignment will be created.
    target_type: ?TargetType = null,

    pub const json_field_names = .{
        .created_date = "CreatedDate",
        .failure_reason = "FailureReason",
        .permission_set_arn = "PermissionSetArn",
        .principal_id = "PrincipalId",
        .principal_type = "PrincipalType",
        .request_id = "RequestId",
        .status = "Status",
        .target_id = "TargetId",
        .target_type = "TargetType",
    };
};
