const StatusValues = @import("status_values.zig").StatusValues;

/// Provides information about the permission set provisioning status.
pub const PermissionSetProvisioningStatusMetadata = struct {
    /// The date that the permission set was created.
    created_date: ?i64,

    /// The identifier for tracking the request operation that is generated by the
    /// universally unique identifier (UUID) workflow.
    request_id: ?[]const u8,

    /// The status of the permission set provisioning process.
    status: ?StatusValues,

    pub const json_field_names = .{
        .created_date = "CreatedDate",
        .request_id = "RequestId",
        .status = "Status",
    };
};
