pub const RouteSpanAdditionalFeature = enum {
    best_case_duration,
    car_access,
    country,
    distance,
    duration,
    dynamic_speed,
    functional_classification,
    gates,
    incidents,
    names,
    notices,
    pedestrian_access,
    railway_crossings,
    region,
    road_attributes,
    route_numbers,
    scooter_access,
    speed_limit,
    toll_systems,
    truck_access,
    truck_road_types,
    typical_duration,
    zones,
    consumption,

    pub const json_field_names = .{
        .best_case_duration = "BEST_CASE_DURATION",
        .car_access = "CAR_ACCESS",
        .country = "COUNTRY",
        .distance = "DISTANCE",
        .duration = "DURATION",
        .dynamic_speed = "DYNAMIC_SPEED",
        .functional_classification = "FUNCTIONAL_CLASSIFICATION",
        .gates = "GATES",
        .incidents = "INCIDENTS",
        .names = "NAMES",
        .notices = "NOTICES",
        .pedestrian_access = "PEDESTRIAN_ACCESS",
        .railway_crossings = "RAILWAY_CROSSINGS",
        .region = "REGION",
        .road_attributes = "ROAD_ATTRIBUTES",
        .route_numbers = "ROUTE_NUMBERS",
        .scooter_access = "SCOOTER_ACCESS",
        .speed_limit = "SPEED_LIMIT",
        .toll_systems = "TOLL_SYSTEMS",
        .truck_access = "TRUCK_ACCESS",
        .truck_road_types = "TRUCK_ROAD_TYPES",
        .typical_duration = "TYPICAL_DURATION",
        .zones = "ZONES",
        .consumption = "CONSUMPTION",
    };
};
