pub const RouteVehicleNoticeCode = enum {
    accurate_polyline_unavailable,
    other,
    potential_violated_avoid_toll_road_usage,
    potential_violated_carpool_usage,
    potential_violated_turn_restriction_usage,
    potential_violated_vehicle_restriction_usage,
    potential_violated_zone_restriction_usage,
    seasonal_closure,
    tolls_data_temporarily_unavailable,
    tolls_data_unavailable,
    toll_transponder,
    violated_avoid_controlled_access_highway,
    violated_avoid_difficult_turns,
    violated_avoid_dirt_road,
    violated_avoid_seasonal_closure,
    violated_avoid_toll_road,
    violated_avoid_toll_transponder,
    violated_avoid_truck_road_type,
    violated_avoid_tunnel,
    violated_avoid_u_turns,
    violated_blocked_road,
    violated_carpool,
    violated_emergency_gate,
    violated_start_direction,
    violated_turn_restriction,
    violated_vehicle_restriction,
    violated_zone_restriction,

    pub const json_field_names = .{
        .accurate_polyline_unavailable = "ACCURATE_POLYLINE_UNAVAILABLE",
        .other = "OTHER",
        .potential_violated_avoid_toll_road_usage = "POTENTIAL_VIOLATED_AVOID_TOLL_ROAD_USAGE",
        .potential_violated_carpool_usage = "POTENTIAL_VIOLATED_CARPOOL_USAGE",
        .potential_violated_turn_restriction_usage = "POTENTIAL_VIOLATED_TURN_RESTRICTION_USAGE",
        .potential_violated_vehicle_restriction_usage = "POTENTIAL_VIOLATED_VEHICLE_RESTRICTION_USAGE",
        .potential_violated_zone_restriction_usage = "POTENTIAL_VIOLATED_ZONE_RESTRICTION_USAGE",
        .seasonal_closure = "SEASONAL_CLOSURE",
        .tolls_data_temporarily_unavailable = "TOLLS_DATA_TEMPORARILY_UNAVAILABLE",
        .tolls_data_unavailable = "TOLLS_DATA_UNAVAILABLE",
        .toll_transponder = "TOLL_TRANSPONDER",
        .violated_avoid_controlled_access_highway = "VIOLATED_AVOID_CONTROLLED_ACCESS_HIGHWAY",
        .violated_avoid_difficult_turns = "VIOLATED_AVOID_DIFFICULT_TURNS",
        .violated_avoid_dirt_road = "VIOLATED_AVOID_DIRT_ROAD",
        .violated_avoid_seasonal_closure = "VIOLATED_AVOID_SEASONAL_CLOSURE",
        .violated_avoid_toll_road = "VIOLATED_AVOID_TOLL_ROAD",
        .violated_avoid_toll_transponder = "VIOLATED_AVOID_TOLL_TRANSPONDER",
        .violated_avoid_truck_road_type = "VIOLATED_AVOID_TRUCK_ROAD_TYPE",
        .violated_avoid_tunnel = "VIOLATED_AVOID_TUNNEL",
        .violated_avoid_u_turns = "VIOLATED_AVOID_U_TURNS",
        .violated_blocked_road = "VIOLATED_BLOCKED_ROAD",
        .violated_carpool = "VIOLATED_CARPOOL",
        .violated_emergency_gate = "VIOLATED_EMERGENCY_GATE",
        .violated_start_direction = "VIOLATED_START_DIRECTION",
        .violated_turn_restriction = "VIOLATED_TURN_RESTRICTION",
        .violated_vehicle_restriction = "VIOLATED_VEHICLE_RESTRICTION",
        .violated_zone_restriction = "VIOLATED_ZONE_RESTRICTION",
    };
};
