pub const SalesforceStandardObjectName = enum {
    account,
    campaign,
    case,
    contact,
    contract,
    document,
    group,
    idea,
    lead,
    opportunity,
    partner,
    pricebook,
    product,
    profile,
    solution,
    task,
    user,

    pub const json_field_names = .{
        .account = "ACCOUNT",
        .campaign = "CAMPAIGN",
        .case = "CASE",
        .contact = "CONTACT",
        .contract = "CONTRACT",
        .document = "DOCUMENT",
        .group = "GROUP",
        .idea = "IDEA",
        .lead = "LEAD",
        .opportunity = "OPPORTUNITY",
        .partner = "PARTNER",
        .pricebook = "PRICEBOOK",
        .product = "PRODUCT",
        .profile = "PROFILE",
        .solution = "SOLUTION",
        .task = "TASK",
        .user = "USER",
    };
};
