pub const ESPartitionInstanceType = enum {
    m_3_medium_elasticsearch,
    m_3_large_elasticsearch,
    m_3_xlarge_elasticsearch,
    m_3_2_xlarge_elasticsearch,
    m_4_large_elasticsearch,
    m_4_xlarge_elasticsearch,
    m_4_2_xlarge_elasticsearch,
    m_4_4_xlarge_elasticsearch,
    m_4_10_xlarge_elasticsearch,
    m_5_large_elasticsearch,
    m_5_xlarge_elasticsearch,
    m_5_2_xlarge_elasticsearch,
    m_5_4_xlarge_elasticsearch,
    m_5_12_xlarge_elasticsearch,
    r_5_large_elasticsearch,
    r_5_xlarge_elasticsearch,
    r_5_2_xlarge_elasticsearch,
    r_5_4_xlarge_elasticsearch,
    r_5_12_xlarge_elasticsearch,
    c_5_large_elasticsearch,
    c_5_xlarge_elasticsearch,
    c_5_2_xlarge_elasticsearch,
    c_5_4_xlarge_elasticsearch,
    c_5_9_xlarge_elasticsearch,
    c_5_18_xlarge_elasticsearch,
    ultrawarm_1_medium_elasticsearch,
    ultrawarm_1_large_elasticsearch,
    t_2_micro_elasticsearch,
    t_2_small_elasticsearch,
    t_2_medium_elasticsearch,
    r_3_large_elasticsearch,
    r_3_xlarge_elasticsearch,
    r_3_2_xlarge_elasticsearch,
    r_3_4_xlarge_elasticsearch,
    r_3_8_xlarge_elasticsearch,
    i_2_xlarge_elasticsearch,
    i_2_2_xlarge_elasticsearch,
    d_2_xlarge_elasticsearch,
    d_2_2_xlarge_elasticsearch,
    d_2_4_xlarge_elasticsearch,
    d_2_8_xlarge_elasticsearch,
    c_4_large_elasticsearch,
    c_4_xlarge_elasticsearch,
    c_4_2_xlarge_elasticsearch,
    c_4_4_xlarge_elasticsearch,
    c_4_8_xlarge_elasticsearch,
    r_4_large_elasticsearch,
    r_4_xlarge_elasticsearch,
    r_4_2_xlarge_elasticsearch,
    r_4_4_xlarge_elasticsearch,
    r_4_8_xlarge_elasticsearch,
    r_4_16_xlarge_elasticsearch,
    i_3_large_elasticsearch,
    i_3_xlarge_elasticsearch,
    i_3_2_xlarge_elasticsearch,
    i_3_4_xlarge_elasticsearch,
    i_3_8_xlarge_elasticsearch,
    i_3_16_xlarge_elasticsearch,

    pub const json_field_names = .{
        .m_3_medium_elasticsearch = "m3_medium_elasticsearch",
        .m_3_large_elasticsearch = "m3_large_elasticsearch",
        .m_3_xlarge_elasticsearch = "m3_xlarge_elasticsearch",
        .m_3_2_xlarge_elasticsearch = "m3_2xlarge_elasticsearch",
        .m_4_large_elasticsearch = "m4_large_elasticsearch",
        .m_4_xlarge_elasticsearch = "m4_xlarge_elasticsearch",
        .m_4_2_xlarge_elasticsearch = "m4_2xlarge_elasticsearch",
        .m_4_4_xlarge_elasticsearch = "m4_4xlarge_elasticsearch",
        .m_4_10_xlarge_elasticsearch = "m4_10xlarge_elasticsearch",
        .m_5_large_elasticsearch = "m5_large_elasticsearch",
        .m_5_xlarge_elasticsearch = "m5_xlarge_elasticsearch",
        .m_5_2_xlarge_elasticsearch = "m5_2xlarge_elasticsearch",
        .m_5_4_xlarge_elasticsearch = "m5_4xlarge_elasticsearch",
        .m_5_12_xlarge_elasticsearch = "m5_12xlarge_elasticsearch",
        .r_5_large_elasticsearch = "r5_large_elasticsearch",
        .r_5_xlarge_elasticsearch = "r5_xlarge_elasticsearch",
        .r_5_2_xlarge_elasticsearch = "r5_2xlarge_elasticsearch",
        .r_5_4_xlarge_elasticsearch = "r5_4xlarge_elasticsearch",
        .r_5_12_xlarge_elasticsearch = "r5_12xlarge_elasticsearch",
        .c_5_large_elasticsearch = "c5_large_elasticsearch",
        .c_5_xlarge_elasticsearch = "c5_xlarge_elasticsearch",
        .c_5_2_xlarge_elasticsearch = "c5_2xlarge_elasticsearch",
        .c_5_4_xlarge_elasticsearch = "c5_4xlarge_elasticsearch",
        .c_5_9_xlarge_elasticsearch = "c5_9xlarge_elasticsearch",
        .c_5_18_xlarge_elasticsearch = "c5_18xlarge_elasticsearch",
        .ultrawarm_1_medium_elasticsearch = "ultrawarm1_medium_elasticsearch",
        .ultrawarm_1_large_elasticsearch = "ultrawarm1_large_elasticsearch",
        .t_2_micro_elasticsearch = "t2_micro_elasticsearch",
        .t_2_small_elasticsearch = "t2_small_elasticsearch",
        .t_2_medium_elasticsearch = "t2_medium_elasticsearch",
        .r_3_large_elasticsearch = "r3_large_elasticsearch",
        .r_3_xlarge_elasticsearch = "r3_xlarge_elasticsearch",
        .r_3_2_xlarge_elasticsearch = "r3_2xlarge_elasticsearch",
        .r_3_4_xlarge_elasticsearch = "r3_4xlarge_elasticsearch",
        .r_3_8_xlarge_elasticsearch = "r3_8xlarge_elasticsearch",
        .i_2_xlarge_elasticsearch = "i2_xlarge_elasticsearch",
        .i_2_2_xlarge_elasticsearch = "i2_2xlarge_elasticsearch",
        .d_2_xlarge_elasticsearch = "d2_xlarge_elasticsearch",
        .d_2_2_xlarge_elasticsearch = "d2_2xlarge_elasticsearch",
        .d_2_4_xlarge_elasticsearch = "d2_4xlarge_elasticsearch",
        .d_2_8_xlarge_elasticsearch = "d2_8xlarge_elasticsearch",
        .c_4_large_elasticsearch = "c4_large_elasticsearch",
        .c_4_xlarge_elasticsearch = "c4_xlarge_elasticsearch",
        .c_4_2_xlarge_elasticsearch = "c4_2xlarge_elasticsearch",
        .c_4_4_xlarge_elasticsearch = "c4_4xlarge_elasticsearch",
        .c_4_8_xlarge_elasticsearch = "c4_8xlarge_elasticsearch",
        .r_4_large_elasticsearch = "r4_large_elasticsearch",
        .r_4_xlarge_elasticsearch = "r4_xlarge_elasticsearch",
        .r_4_2_xlarge_elasticsearch = "r4_2xlarge_elasticsearch",
        .r_4_4_xlarge_elasticsearch = "r4_4xlarge_elasticsearch",
        .r_4_8_xlarge_elasticsearch = "r4_8xlarge_elasticsearch",
        .r_4_16_xlarge_elasticsearch = "r4_16xlarge_elasticsearch",
        .i_3_large_elasticsearch = "i3_large_elasticsearch",
        .i_3_xlarge_elasticsearch = "i3_xlarge_elasticsearch",
        .i_3_2_xlarge_elasticsearch = "i3_2xlarge_elasticsearch",
        .i_3_4_xlarge_elasticsearch = "i3_4xlarge_elasticsearch",
        .i_3_8_xlarge_elasticsearch = "i3_8xlarge_elasticsearch",
        .i_3_16_xlarge_elasticsearch = "i3_16xlarge_elasticsearch",
    };
};
