const std = @import("std");

pub const ESPartitionInstanceType = enum {
    m_3_medium_elasticsearch,
    m_3_large_elasticsearch,
    m_3_xlarge_elasticsearch,
    m_3_2_xlarge_elasticsearch,
    m_4_large_elasticsearch,
    m_4_xlarge_elasticsearch,
    m_4_2_xlarge_elasticsearch,
    m_4_4_xlarge_elasticsearch,
    m_4_10_xlarge_elasticsearch,
    m_5_large_elasticsearch,
    m_5_xlarge_elasticsearch,
    m_5_2_xlarge_elasticsearch,
    m_5_4_xlarge_elasticsearch,
    m_5_12_xlarge_elasticsearch,
    r_5_large_elasticsearch,
    r_5_xlarge_elasticsearch,
    r_5_2_xlarge_elasticsearch,
    r_5_4_xlarge_elasticsearch,
    r_5_12_xlarge_elasticsearch,
    c_5_large_elasticsearch,
    c_5_xlarge_elasticsearch,
    c_5_2_xlarge_elasticsearch,
    c_5_4_xlarge_elasticsearch,
    c_5_9_xlarge_elasticsearch,
    c_5_18_xlarge_elasticsearch,
    ultrawarm_1_medium_elasticsearch,
    ultrawarm_1_large_elasticsearch,
    t_2_micro_elasticsearch,
    t_2_small_elasticsearch,
    t_2_medium_elasticsearch,
    r_3_large_elasticsearch,
    r_3_xlarge_elasticsearch,
    r_3_2_xlarge_elasticsearch,
    r_3_4_xlarge_elasticsearch,
    r_3_8_xlarge_elasticsearch,
    i_2_xlarge_elasticsearch,
    i_2_2_xlarge_elasticsearch,
    d_2_xlarge_elasticsearch,
    d_2_2_xlarge_elasticsearch,
    d_2_4_xlarge_elasticsearch,
    d_2_8_xlarge_elasticsearch,
    c_4_large_elasticsearch,
    c_4_xlarge_elasticsearch,
    c_4_2_xlarge_elasticsearch,
    c_4_4_xlarge_elasticsearch,
    c_4_8_xlarge_elasticsearch,
    r_4_large_elasticsearch,
    r_4_xlarge_elasticsearch,
    r_4_2_xlarge_elasticsearch,
    r_4_4_xlarge_elasticsearch,
    r_4_8_xlarge_elasticsearch,
    r_4_16_xlarge_elasticsearch,
    i_3_large_elasticsearch,
    i_3_xlarge_elasticsearch,
    i_3_2_xlarge_elasticsearch,
    i_3_4_xlarge_elasticsearch,
    i_3_8_xlarge_elasticsearch,
    i_3_16_xlarge_elasticsearch,

    pub const json_field_names = .{
        .m_3_medium_elasticsearch = "m3.medium.elasticsearch",
        .m_3_large_elasticsearch = "m3.large.elasticsearch",
        .m_3_xlarge_elasticsearch = "m3.xlarge.elasticsearch",
        .m_3_2_xlarge_elasticsearch = "m3.2xlarge.elasticsearch",
        .m_4_large_elasticsearch = "m4.large.elasticsearch",
        .m_4_xlarge_elasticsearch = "m4.xlarge.elasticsearch",
        .m_4_2_xlarge_elasticsearch = "m4.2xlarge.elasticsearch",
        .m_4_4_xlarge_elasticsearch = "m4.4xlarge.elasticsearch",
        .m_4_10_xlarge_elasticsearch = "m4.10xlarge.elasticsearch",
        .m_5_large_elasticsearch = "m5.large.elasticsearch",
        .m_5_xlarge_elasticsearch = "m5.xlarge.elasticsearch",
        .m_5_2_xlarge_elasticsearch = "m5.2xlarge.elasticsearch",
        .m_5_4_xlarge_elasticsearch = "m5.4xlarge.elasticsearch",
        .m_5_12_xlarge_elasticsearch = "m5.12xlarge.elasticsearch",
        .r_5_large_elasticsearch = "r5.large.elasticsearch",
        .r_5_xlarge_elasticsearch = "r5.xlarge.elasticsearch",
        .r_5_2_xlarge_elasticsearch = "r5.2xlarge.elasticsearch",
        .r_5_4_xlarge_elasticsearch = "r5.4xlarge.elasticsearch",
        .r_5_12_xlarge_elasticsearch = "r5.12xlarge.elasticsearch",
        .c_5_large_elasticsearch = "c5.large.elasticsearch",
        .c_5_xlarge_elasticsearch = "c5.xlarge.elasticsearch",
        .c_5_2_xlarge_elasticsearch = "c5.2xlarge.elasticsearch",
        .c_5_4_xlarge_elasticsearch = "c5.4xlarge.elasticsearch",
        .c_5_9_xlarge_elasticsearch = "c5.9xlarge.elasticsearch",
        .c_5_18_xlarge_elasticsearch = "c5.18xlarge.elasticsearch",
        .ultrawarm_1_medium_elasticsearch = "ultrawarm1.medium.elasticsearch",
        .ultrawarm_1_large_elasticsearch = "ultrawarm1.large.elasticsearch",
        .t_2_micro_elasticsearch = "t2.micro.elasticsearch",
        .t_2_small_elasticsearch = "t2.small.elasticsearch",
        .t_2_medium_elasticsearch = "t2.medium.elasticsearch",
        .r_3_large_elasticsearch = "r3.large.elasticsearch",
        .r_3_xlarge_elasticsearch = "r3.xlarge.elasticsearch",
        .r_3_2_xlarge_elasticsearch = "r3.2xlarge.elasticsearch",
        .r_3_4_xlarge_elasticsearch = "r3.4xlarge.elasticsearch",
        .r_3_8_xlarge_elasticsearch = "r3.8xlarge.elasticsearch",
        .i_2_xlarge_elasticsearch = "i2.xlarge.elasticsearch",
        .i_2_2_xlarge_elasticsearch = "i2.2xlarge.elasticsearch",
        .d_2_xlarge_elasticsearch = "d2.xlarge.elasticsearch",
        .d_2_2_xlarge_elasticsearch = "d2.2xlarge.elasticsearch",
        .d_2_4_xlarge_elasticsearch = "d2.4xlarge.elasticsearch",
        .d_2_8_xlarge_elasticsearch = "d2.8xlarge.elasticsearch",
        .c_4_large_elasticsearch = "c4.large.elasticsearch",
        .c_4_xlarge_elasticsearch = "c4.xlarge.elasticsearch",
        .c_4_2_xlarge_elasticsearch = "c4.2xlarge.elasticsearch",
        .c_4_4_xlarge_elasticsearch = "c4.4xlarge.elasticsearch",
        .c_4_8_xlarge_elasticsearch = "c4.8xlarge.elasticsearch",
        .r_4_large_elasticsearch = "r4.large.elasticsearch",
        .r_4_xlarge_elasticsearch = "r4.xlarge.elasticsearch",
        .r_4_2_xlarge_elasticsearch = "r4.2xlarge.elasticsearch",
        .r_4_4_xlarge_elasticsearch = "r4.4xlarge.elasticsearch",
        .r_4_8_xlarge_elasticsearch = "r4.8xlarge.elasticsearch",
        .r_4_16_xlarge_elasticsearch = "r4.16xlarge.elasticsearch",
        .i_3_large_elasticsearch = "i3.large.elasticsearch",
        .i_3_xlarge_elasticsearch = "i3.xlarge.elasticsearch",
        .i_3_2_xlarge_elasticsearch = "i3.2xlarge.elasticsearch",
        .i_3_4_xlarge_elasticsearch = "i3.4xlarge.elasticsearch",
        .i_3_8_xlarge_elasticsearch = "i3.8xlarge.elasticsearch",
        .i_3_16_xlarge_elasticsearch = "i3.16xlarge.elasticsearch",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .m_3_medium_elasticsearch => "m3.medium.elasticsearch",
            .m_3_large_elasticsearch => "m3.large.elasticsearch",
            .m_3_xlarge_elasticsearch => "m3.xlarge.elasticsearch",
            .m_3_2_xlarge_elasticsearch => "m3.2xlarge.elasticsearch",
            .m_4_large_elasticsearch => "m4.large.elasticsearch",
            .m_4_xlarge_elasticsearch => "m4.xlarge.elasticsearch",
            .m_4_2_xlarge_elasticsearch => "m4.2xlarge.elasticsearch",
            .m_4_4_xlarge_elasticsearch => "m4.4xlarge.elasticsearch",
            .m_4_10_xlarge_elasticsearch => "m4.10xlarge.elasticsearch",
            .m_5_large_elasticsearch => "m5.large.elasticsearch",
            .m_5_xlarge_elasticsearch => "m5.xlarge.elasticsearch",
            .m_5_2_xlarge_elasticsearch => "m5.2xlarge.elasticsearch",
            .m_5_4_xlarge_elasticsearch => "m5.4xlarge.elasticsearch",
            .m_5_12_xlarge_elasticsearch => "m5.12xlarge.elasticsearch",
            .r_5_large_elasticsearch => "r5.large.elasticsearch",
            .r_5_xlarge_elasticsearch => "r5.xlarge.elasticsearch",
            .r_5_2_xlarge_elasticsearch => "r5.2xlarge.elasticsearch",
            .r_5_4_xlarge_elasticsearch => "r5.4xlarge.elasticsearch",
            .r_5_12_xlarge_elasticsearch => "r5.12xlarge.elasticsearch",
            .c_5_large_elasticsearch => "c5.large.elasticsearch",
            .c_5_xlarge_elasticsearch => "c5.xlarge.elasticsearch",
            .c_5_2_xlarge_elasticsearch => "c5.2xlarge.elasticsearch",
            .c_5_4_xlarge_elasticsearch => "c5.4xlarge.elasticsearch",
            .c_5_9_xlarge_elasticsearch => "c5.9xlarge.elasticsearch",
            .c_5_18_xlarge_elasticsearch => "c5.18xlarge.elasticsearch",
            .ultrawarm_1_medium_elasticsearch => "ultrawarm1.medium.elasticsearch",
            .ultrawarm_1_large_elasticsearch => "ultrawarm1.large.elasticsearch",
            .t_2_micro_elasticsearch => "t2.micro.elasticsearch",
            .t_2_small_elasticsearch => "t2.small.elasticsearch",
            .t_2_medium_elasticsearch => "t2.medium.elasticsearch",
            .r_3_large_elasticsearch => "r3.large.elasticsearch",
            .r_3_xlarge_elasticsearch => "r3.xlarge.elasticsearch",
            .r_3_2_xlarge_elasticsearch => "r3.2xlarge.elasticsearch",
            .r_3_4_xlarge_elasticsearch => "r3.4xlarge.elasticsearch",
            .r_3_8_xlarge_elasticsearch => "r3.8xlarge.elasticsearch",
            .i_2_xlarge_elasticsearch => "i2.xlarge.elasticsearch",
            .i_2_2_xlarge_elasticsearch => "i2.2xlarge.elasticsearch",
            .d_2_xlarge_elasticsearch => "d2.xlarge.elasticsearch",
            .d_2_2_xlarge_elasticsearch => "d2.2xlarge.elasticsearch",
            .d_2_4_xlarge_elasticsearch => "d2.4xlarge.elasticsearch",
            .d_2_8_xlarge_elasticsearch => "d2.8xlarge.elasticsearch",
            .c_4_large_elasticsearch => "c4.large.elasticsearch",
            .c_4_xlarge_elasticsearch => "c4.xlarge.elasticsearch",
            .c_4_2_xlarge_elasticsearch => "c4.2xlarge.elasticsearch",
            .c_4_4_xlarge_elasticsearch => "c4.4xlarge.elasticsearch",
            .c_4_8_xlarge_elasticsearch => "c4.8xlarge.elasticsearch",
            .r_4_large_elasticsearch => "r4.large.elasticsearch",
            .r_4_xlarge_elasticsearch => "r4.xlarge.elasticsearch",
            .r_4_2_xlarge_elasticsearch => "r4.2xlarge.elasticsearch",
            .r_4_4_xlarge_elasticsearch => "r4.4xlarge.elasticsearch",
            .r_4_8_xlarge_elasticsearch => "r4.8xlarge.elasticsearch",
            .r_4_16_xlarge_elasticsearch => "r4.16xlarge.elasticsearch",
            .i_3_large_elasticsearch => "i3.large.elasticsearch",
            .i_3_xlarge_elasticsearch => "i3.xlarge.elasticsearch",
            .i_3_2_xlarge_elasticsearch => "i3.2xlarge.elasticsearch",
            .i_3_4_xlarge_elasticsearch => "i3.4xlarge.elasticsearch",
            .i_3_8_xlarge_elasticsearch => "i3.8xlarge.elasticsearch",
            .i_3_16_xlarge_elasticsearch => "i3.16xlarge.elasticsearch",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
