const std = @import("std");

pub const ValidationExceptionReason = enum {
    missing_billing_adjustments,
    billing_adjustments_limit_exceeded,
    missing_invoice_id,
    invalid_adjustment_amount,
    missing_adjustment_amount,
    invalid_reason_code,
    missing_reason_code,
    missing_description,
    invalid_invoice_adjustment_period,
    invalid_currency_code,
    missing_currency_code,
    exceeded_maximum_adjustment_amount,
    missing_billing_adjustment_request_entry,
    multiple_agreement_ids,
    invalid_agreement_cancellation_request_id,
    missing_agreement_cancellation_request_id,
    missing_reason,
    invalid_reason,
    invalid_status,
    invalid_agreement_id,
    missing_agreement_id,
    invalid_catalog,
    invalid_filters,
    invalid_filter_name,
    missing_filter_name,
    invalid_filter_values,
    missing_filter_values,
    invalid_sort_by,
    invalid_sort_order,
    invalid_next_token,
    invalid_max_results,
    invalid_term_id,
    missing_term_id,
    missing_name,
    invalid_name,
    invalid_description,
    missing_charge_amount,
    invalid_charge_amount,
    missing_payment_request_id,
    invalid_payment_request_id,
    missing_party_type,
    invalid_party_type,
    unsupported_filters,
    invalid_client_token,
    invalid_intent,
    missing_intent,
    invalid_source_agreement_identifier,
    missing_source_agreement_identifier,
    invalid_agreement_proposal_identifier,
    missing_agreement_proposal_identifier,
    invalid_requested_terms,
    missing_requested_terms,
    invalid_requested_term_id,
    missing_requested_term_id,
    invalid_requested_term_configuration,
    missing_requested_term_configuration,
    invalid_agreement_request_id,
    missing_agreement_request_id,
    invalid_purchase_orders,
    missing_purchase_orders,
    invalid_charge_id,
    missing_charge_id,
    invalid_charge_revision,
    missing_charge_revision,
    invalid_agreement_type,
    invalid_purchase_order_reference,
    inactive_agreement,
    superseded_agreement_proposal,
    expired_agreement_proposal,
    missing_mandatory_terms,
    incompatible_terms,
    missing_usage_agreement,
    invalid_incremental_charge,
    missing_account_address,
    unsupported_action,
    invalid_rejection_reason,
    invalid_payment_request_status,
    other,
    duplicate_charges,
    unsupported_account_plan,
    duplicate_agreement_in_organization,
    missing_purchase_order_reference,

    pub const json_field_names = .{
        .missing_billing_adjustments = "MISSING_BILLING_ADJUSTMENTS",
        .billing_adjustments_limit_exceeded = "BILLING_ADJUSTMENTS_LIMIT_EXCEEDED",
        .missing_invoice_id = "MISSING_INVOICE_ID",
        .invalid_adjustment_amount = "INVALID_ADJUSTMENT_AMOUNT",
        .missing_adjustment_amount = "MISSING_ADJUSTMENT_AMOUNT",
        .invalid_reason_code = "INVALID_REASON_CODE",
        .missing_reason_code = "MISSING_REASON_CODE",
        .missing_description = "MISSING_DESCRIPTION",
        .invalid_invoice_adjustment_period = "INVALID_INVOICE_ADJUSTMENT_PERIOD",
        .invalid_currency_code = "INVALID_CURRENCY_CODE",
        .missing_currency_code = "MISSING_CURRENCY_CODE",
        .exceeded_maximum_adjustment_amount = "EXCEEDED_MAXIMUM_ADJUSTMENT_AMOUNT",
        .missing_billing_adjustment_request_entry = "MISSING_BILLING_ADJUSTMENT_REQUEST_ENTRY",
        .multiple_agreement_ids = "MULTIPLE_AGREEMENT_IDS",
        .invalid_agreement_cancellation_request_id = "INVALID_AGREEMENT_CANCELLATION_REQUEST_ID",
        .missing_agreement_cancellation_request_id = "MISSING_AGREEMENT_CANCELLATION_REQUEST_ID",
        .missing_reason = "MISSING_REASON",
        .invalid_reason = "INVALID_REASON",
        .invalid_status = "INVALID_STATUS",
        .invalid_agreement_id = "INVALID_AGREEMENT_ID",
        .missing_agreement_id = "MISSING_AGREEMENT_ID",
        .invalid_catalog = "INVALID_CATALOG",
        .invalid_filters = "INVALID_FILTERS",
        .invalid_filter_name = "INVALID_FILTER_NAME",
        .missing_filter_name = "MISSING_FILTER_NAME",
        .invalid_filter_values = "INVALID_FILTER_VALUES",
        .missing_filter_values = "MISSING_FILTER_VALUES",
        .invalid_sort_by = "INVALID_SORT_BY",
        .invalid_sort_order = "INVALID_SORT_ORDER",
        .invalid_next_token = "INVALID_NEXT_TOKEN",
        .invalid_max_results = "INVALID_MAX_RESULTS",
        .invalid_term_id = "INVALID_TERM_ID",
        .missing_term_id = "MISSING_TERM_ID",
        .missing_name = "MISSING_NAME",
        .invalid_name = "INVALID_NAME",
        .invalid_description = "INVALID_DESCRIPTION",
        .missing_charge_amount = "MISSING_CHARGE_AMOUNT",
        .invalid_charge_amount = "INVALID_CHARGE_AMOUNT",
        .missing_payment_request_id = "MISSING_PAYMENT_REQUEST_ID",
        .invalid_payment_request_id = "INVALID_PAYMENT_REQUEST_ID",
        .missing_party_type = "MISSING_PARTY_TYPE",
        .invalid_party_type = "INVALID_PARTY_TYPE",
        .unsupported_filters = "UNSUPPORTED_FILTERS",
        .invalid_client_token = "INVALID_CLIENT_TOKEN",
        .invalid_intent = "INVALID_INTENT",
        .missing_intent = "MISSING_INTENT",
        .invalid_source_agreement_identifier = "INVALID_SOURCE_AGREEMENT_IDENTIFIER",
        .missing_source_agreement_identifier = "MISSING_SOURCE_AGREEMENT_IDENTIFIER",
        .invalid_agreement_proposal_identifier = "INVALID_AGREEMENT_PROPOSAL_IDENTIFIER",
        .missing_agreement_proposal_identifier = "MISSING_AGREEMENT_PROPOSAL_IDENTIFIER",
        .invalid_requested_terms = "INVALID_REQUESTED_TERMS",
        .missing_requested_terms = "MISSING_REQUESTED_TERMS",
        .invalid_requested_term_id = "INVALID_REQUESTED_TERM_ID",
        .missing_requested_term_id = "MISSING_REQUESTED_TERM_ID",
        .invalid_requested_term_configuration = "INVALID_REQUESTED_TERM_CONFIGURATION",
        .missing_requested_term_configuration = "MISSING_REQUESTED_TERM_CONFIGURATION",
        .invalid_agreement_request_id = "INVALID_AGREEMENT_REQUEST_ID",
        .missing_agreement_request_id = "MISSING_AGREEMENT_REQUEST_ID",
        .invalid_purchase_orders = "INVALID_PURCHASE_ORDERS",
        .missing_purchase_orders = "MISSING_PURCHASE_ORDERS",
        .invalid_charge_id = "INVALID_CHARGE_ID",
        .missing_charge_id = "MISSING_CHARGE_ID",
        .invalid_charge_revision = "INVALID_CHARGE_REVISION",
        .missing_charge_revision = "MISSING_CHARGE_REVISION",
        .invalid_agreement_type = "INVALID_AGREEMENT_TYPE",
        .invalid_purchase_order_reference = "INVALID_PURCHASE_ORDER_REFERENCE",
        .inactive_agreement = "INACTIVE_AGREEMENT",
        .superseded_agreement_proposal = "SUPERSEDED_AGREEMENT_PROPOSAL",
        .expired_agreement_proposal = "EXPIRED_AGREEMENT_PROPOSAL",
        .missing_mandatory_terms = "MISSING_MANDATORY_TERMS",
        .incompatible_terms = "INCOMPATIBLE_TERMS",
        .missing_usage_agreement = "MISSING_USAGE_AGREEMENT",
        .invalid_incremental_charge = "INVALID_INCREMENTAL_CHARGE",
        .missing_account_address = "MISSING_ACCOUNT_ADDRESS",
        .unsupported_action = "UNSUPPORTED_ACTION",
        .invalid_rejection_reason = "INVALID_REJECTION_REASON",
        .invalid_payment_request_status = "INVALID_PAYMENT_REQUEST_STATUS",
        .other = "OTHER",
        .duplicate_charges = "DUPLICATE_CHARGES",
        .unsupported_account_plan = "UNSUPPORTED_ACCOUNT_PLAN",
        .duplicate_agreement_in_organization = "DUPLICATE_AGREEMENT_IN_ORGANIZATION",
        .missing_purchase_order_reference = "MISSING_PURCHASE_ORDER_REFERENCE",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .missing_billing_adjustments => "MISSING_BILLING_ADJUSTMENTS",
            .billing_adjustments_limit_exceeded => "BILLING_ADJUSTMENTS_LIMIT_EXCEEDED",
            .missing_invoice_id => "MISSING_INVOICE_ID",
            .invalid_adjustment_amount => "INVALID_ADJUSTMENT_AMOUNT",
            .missing_adjustment_amount => "MISSING_ADJUSTMENT_AMOUNT",
            .invalid_reason_code => "INVALID_REASON_CODE",
            .missing_reason_code => "MISSING_REASON_CODE",
            .missing_description => "MISSING_DESCRIPTION",
            .invalid_invoice_adjustment_period => "INVALID_INVOICE_ADJUSTMENT_PERIOD",
            .invalid_currency_code => "INVALID_CURRENCY_CODE",
            .missing_currency_code => "MISSING_CURRENCY_CODE",
            .exceeded_maximum_adjustment_amount => "EXCEEDED_MAXIMUM_ADJUSTMENT_AMOUNT",
            .missing_billing_adjustment_request_entry => "MISSING_BILLING_ADJUSTMENT_REQUEST_ENTRY",
            .multiple_agreement_ids => "MULTIPLE_AGREEMENT_IDS",
            .invalid_agreement_cancellation_request_id => "INVALID_AGREEMENT_CANCELLATION_REQUEST_ID",
            .missing_agreement_cancellation_request_id => "MISSING_AGREEMENT_CANCELLATION_REQUEST_ID",
            .missing_reason => "MISSING_REASON",
            .invalid_reason => "INVALID_REASON",
            .invalid_status => "INVALID_STATUS",
            .invalid_agreement_id => "INVALID_AGREEMENT_ID",
            .missing_agreement_id => "MISSING_AGREEMENT_ID",
            .invalid_catalog => "INVALID_CATALOG",
            .invalid_filters => "INVALID_FILTERS",
            .invalid_filter_name => "INVALID_FILTER_NAME",
            .missing_filter_name => "MISSING_FILTER_NAME",
            .invalid_filter_values => "INVALID_FILTER_VALUES",
            .missing_filter_values => "MISSING_FILTER_VALUES",
            .invalid_sort_by => "INVALID_SORT_BY",
            .invalid_sort_order => "INVALID_SORT_ORDER",
            .invalid_next_token => "INVALID_NEXT_TOKEN",
            .invalid_max_results => "INVALID_MAX_RESULTS",
            .invalid_term_id => "INVALID_TERM_ID",
            .missing_term_id => "MISSING_TERM_ID",
            .missing_name => "MISSING_NAME",
            .invalid_name => "INVALID_NAME",
            .invalid_description => "INVALID_DESCRIPTION",
            .missing_charge_amount => "MISSING_CHARGE_AMOUNT",
            .invalid_charge_amount => "INVALID_CHARGE_AMOUNT",
            .missing_payment_request_id => "MISSING_PAYMENT_REQUEST_ID",
            .invalid_payment_request_id => "INVALID_PAYMENT_REQUEST_ID",
            .missing_party_type => "MISSING_PARTY_TYPE",
            .invalid_party_type => "INVALID_PARTY_TYPE",
            .unsupported_filters => "UNSUPPORTED_FILTERS",
            .invalid_client_token => "INVALID_CLIENT_TOKEN",
            .invalid_intent => "INVALID_INTENT",
            .missing_intent => "MISSING_INTENT",
            .invalid_source_agreement_identifier => "INVALID_SOURCE_AGREEMENT_IDENTIFIER",
            .missing_source_agreement_identifier => "MISSING_SOURCE_AGREEMENT_IDENTIFIER",
            .invalid_agreement_proposal_identifier => "INVALID_AGREEMENT_PROPOSAL_IDENTIFIER",
            .missing_agreement_proposal_identifier => "MISSING_AGREEMENT_PROPOSAL_IDENTIFIER",
            .invalid_requested_terms => "INVALID_REQUESTED_TERMS",
            .missing_requested_terms => "MISSING_REQUESTED_TERMS",
            .invalid_requested_term_id => "INVALID_REQUESTED_TERM_ID",
            .missing_requested_term_id => "MISSING_REQUESTED_TERM_ID",
            .invalid_requested_term_configuration => "INVALID_REQUESTED_TERM_CONFIGURATION",
            .missing_requested_term_configuration => "MISSING_REQUESTED_TERM_CONFIGURATION",
            .invalid_agreement_request_id => "INVALID_AGREEMENT_REQUEST_ID",
            .missing_agreement_request_id => "MISSING_AGREEMENT_REQUEST_ID",
            .invalid_purchase_orders => "INVALID_PURCHASE_ORDERS",
            .missing_purchase_orders => "MISSING_PURCHASE_ORDERS",
            .invalid_charge_id => "INVALID_CHARGE_ID",
            .missing_charge_id => "MISSING_CHARGE_ID",
            .invalid_charge_revision => "INVALID_CHARGE_REVISION",
            .missing_charge_revision => "MISSING_CHARGE_REVISION",
            .invalid_agreement_type => "INVALID_AGREEMENT_TYPE",
            .invalid_purchase_order_reference => "INVALID_PURCHASE_ORDER_REFERENCE",
            .inactive_agreement => "INACTIVE_AGREEMENT",
            .superseded_agreement_proposal => "SUPERSEDED_AGREEMENT_PROPOSAL",
            .expired_agreement_proposal => "EXPIRED_AGREEMENT_PROPOSAL",
            .missing_mandatory_terms => "MISSING_MANDATORY_TERMS",
            .incompatible_terms => "INCOMPATIBLE_TERMS",
            .missing_usage_agreement => "MISSING_USAGE_AGREEMENT",
            .invalid_incremental_charge => "INVALID_INCREMENTAL_CHARGE",
            .missing_account_address => "MISSING_ACCOUNT_ADDRESS",
            .unsupported_action => "UNSUPPORTED_ACTION",
            .invalid_rejection_reason => "INVALID_REJECTION_REASON",
            .invalid_payment_request_status => "INVALID_PAYMENT_REQUEST_STATUS",
            .other => "OTHER",
            .duplicate_charges => "DUPLICATE_CHARGES",
            .unsupported_account_plan => "UNSUPPORTED_ACCOUNT_PLAN",
            .duplicate_agreement_in_organization => "DUPLICATE_AGREEMENT_IN_ORGANIZATION",
            .missing_purchase_order_reference => "MISSING_PURCHASE_ORDER_REFERENCE",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
