const aws = @import("aws");

const PrivateKeySource = @import("private_key_source.zig").PrivateKeySource;
const SigningAlgorithm = @import("signing_algorithm.zig").SigningAlgorithm;

/// The private key configuration for private_key_jwt client authentication.
pub const PrivateKeyJwtConfig = struct {
    /// A map of additional claims to include in the JWT client assertion header.
    /// Standard header claims such as `alg` and `typ` cannot be added.
    additional_header_claims: ?[]const aws.map.StringMapEntry = null,

    /// A map of additional claims to include in the JWT client assertion payload.
    /// Payload claims generated by the service, such as `iss`, `sub`, `jti`, and
    /// `exp`, cannot be added.
    additional_payload_claims: ?[]const aws.map.StringMapEntry = null,

    /// The private key source for the JWT client assertion.
    private_key_source: ?PrivateKeySource = null,

    /// The algorithm used to sign the JWT client assertion. Valid values are
    /// `RS256`, `PS256`, and `ES256`.
    signing_algorithm: ?SigningAlgorithm = null,

    pub const json_field_names = .{
        .additional_header_claims = "additionalHeaderClaims",
        .additional_payload_claims = "additionalPayloadClaims",
        .private_key_source = "privateKeySource",
        .signing_algorithm = "signingAlgorithm",
    };
};
