pub const DataIntegrationEventType = enum {
    forecast,
    inventory_level,
    inbound_order,
    inbound_order_line,
    inbound_order_line_schedule,
    outbound_order_line,
    outbound_shipment,
    process_header,
    process_operation,
    process_product,
    reservation,
    shipment,
    shipment_stop,
    shipment_stop_order,
    supply_plan,
    dataset,

    pub const json_field_names = .{
        .forecast = "FORECAST",
        .inventory_level = "INVENTORY_LEVEL",
        .inbound_order = "INBOUND_ORDER",
        .inbound_order_line = "INBOUND_ORDER_LINE",
        .inbound_order_line_schedule = "INBOUND_ORDER_LINE_SCHEDULE",
        .outbound_order_line = "OUTBOUND_ORDER_LINE",
        .outbound_shipment = "OUTBOUND_SHIPMENT",
        .process_header = "PROCESS_HEADER",
        .process_operation = "PROCESS_OPERATION",
        .process_product = "PROCESS_PRODUCT",
        .reservation = "RESERVATION",
        .shipment = "SHIPMENT",
        .shipment_stop = "SHIPMENT_STOP",
        .shipment_stop_order = "SHIPMENT_STOP_ORDER",
        .supply_plan = "SUPPLY_PLAN",
        .dataset = "DATASET",
    };
};
