const BridgePlacement = @import("bridge_placement.zig").BridgePlacement;
const ConnectionStatus = @import("connection_status.zig").ConnectionStatus;
const MessageDetail = @import("message_detail.zig").MessageDetail;
const InstanceState = @import("instance_state.zig").InstanceState;

/// The settings for an instance in a gateway.
pub const GatewayInstance = struct {
    /// The availability of the instance to host new bridges. The bridgePlacement
    /// property can be LOCKED or AVAILABLE. If it is LOCKED, no new bridges can be
    /// deployed to this instance. If it is AVAILABLE, new bridges can be deployed
    /// to this instance.
    bridge_placement: BridgePlacement,

    /// The connection state of the instance.
    connection_status: ConnectionStatus,

    /// The Amazon Resource Name (ARN) of the instance.
    gateway_arn: []const u8,

    /// The ARN of the gateway.
    gateway_instance_arn: []const u8,

    /// The instance ID generated by the SSM install. This will begin with "mi-".
    instance_id: []const u8,

    /// Messages with information about the gateway.
    instance_messages: ?[]const MessageDetail = null,

    /// The status of the instance.
    instance_state: InstanceState,

    /// The running bridge count.
    running_bridge_count: i32,

    pub const json_field_names = .{
        .bridge_placement = "BridgePlacement",
        .connection_status = "ConnectionStatus",
        .gateway_arn = "GatewayArn",
        .gateway_instance_arn = "GatewayInstanceArn",
        .instance_id = "InstanceId",
        .instance_messages = "InstanceMessages",
        .instance_state = "InstanceState",
        .running_bridge_count = "RunningBridgeCount",
    };
};
