const InstanceState = @import("instance_state.zig").InstanceState;

/// A summary of an instance.
pub const ListedGatewayInstance = struct {
    /// The Amazon Resource Name (ARN) of the gateway.
    gateway_arn: []const u8,

    /// The Amazon Resource Name (ARN) of the instance.
    gateway_instance_arn: []const u8,

    /// The managed instance ID generated by the SSM install. This will begin with
    /// "mi-".
    instance_id: []const u8,

    /// The status of the instance.
    instance_state: ?InstanceState = null,

    pub const json_field_names = .{
        .gateway_arn = "GatewayArn",
        .gateway_instance_arn = "GatewayInstanceArn",
        .instance_id = "InstanceId",
        .instance_state = "InstanceState",
    };
};
