pub const PlaceType = enum {
    country,
    region,
    sub_region,
    locality,
    district,
    sub_district,
    postal_code,
    block,
    sub_block,
    intersection,
    street,
    point_of_interest,
    point_address,
    interpolated_address,
    secondary_address,
    inferred_secondary_address,

    pub const json_field_names = .{
        .country = "COUNTRY",
        .region = "REGION",
        .sub_region = "SUB_REGION",
        .locality = "LOCALITY",
        .district = "DISTRICT",
        .sub_district = "SUB_DISTRICT",
        .postal_code = "POSTAL_CODE",
        .block = "BLOCK",
        .sub_block = "SUB_BLOCK",
        .intersection = "INTERSECTION",
        .street = "STREET",
        .point_of_interest = "POINT_OF_INTEREST",
        .point_address = "POINT_ADDRESS",
        .interpolated_address = "INTERPOLATED_ADDRESS",
        .secondary_address = "SECONDARY_ADDRESS",
        .inferred_secondary_address = "INFERRED_SECONDARY_ADDRESS",
    };
};
