const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;

pub const CreateMLEndpointInput = struct {
    /// A unique identifier for the new inference endpoint. The default is an
    /// autogenerated timestamped name.
    id: ?[]const u8 = null,

    /// The minimum number of Amazon EC2 instances to deploy to an endpoint for
    /// prediction. The default is 1
    instance_count: ?i32 = null,

    /// The type of Neptune ML instance to use for online servicing. The default is
    /// `ml.m5.xlarge`. Choosing the ML instance for an inference endpoint depends
    /// on the task type, the graph size, and your budget.
    instance_type: ?[]const u8 = null,

    /// The job Id of the completed model-training job that has created the model
    /// that the inference endpoint will point to. You must supply either the
    /// `mlModelTrainingJobId` or the `mlModelTransformJobId`.
    ml_model_training_job_id: ?[]const u8 = null,

    /// The job Id of the completed model-transform job. You must supply either the
    /// `mlModelTrainingJobId` or the `mlModelTransformJobId`.
    ml_model_transform_job_id: ?[]const u8 = null,

    /// Model type for training. By default the Neptune ML model is automatically
    /// based on the `modelType` used in data processing, but you can specify a
    /// different model type here. The default is `rgcn` for heterogeneous graphs
    /// and `kge` for knowledge graphs. The only valid value for heterogeneous
    /// graphs is `rgcn`. Valid values for knowledge graphs are: `kge`, `transe`,
    /// `distmult`, and `rotate`.
    model_name: ?[]const u8 = null,

    /// The ARN of an IAM role providing Neptune access to SageMaker and Amazon S3
    /// resources. This must be listed in your DB cluster parameter group or an
    /// error will be thrown.
    neptune_iam_role_arn: ?[]const u8 = null,

    /// If set to `true`, `update` indicates that this is an update request. The
    /// default is `false`. You must supply either the `mlModelTrainingJobId` or the
    /// `mlModelTransformJobId`.
    update: ?bool = null,

    /// The Amazon Key Management Service (Amazon KMS) key that SageMaker uses to
    /// encrypt data on the storage volume attached to the ML compute instances that
    /// run the training job. The default is None.
    volume_encryption_kms_key: ?[]const u8 = null,

    pub const json_field_names = .{
        .id = "id",
        .instance_count = "instanceCount",
        .instance_type = "instanceType",
        .ml_model_training_job_id = "mlModelTrainingJobId",
        .ml_model_transform_job_id = "mlModelTransformJobId",
        .model_name = "modelName",
        .neptune_iam_role_arn = "neptuneIamRoleArn",
        .update = "update",
        .volume_encryption_kms_key = "volumeEncryptionKMSKey",
    };
};

pub const CreateMLEndpointOutput = struct {
    /// The ARN for the new inference endpoint.
    arn: ?[]const u8 = null,

    /// The endpoint creation time, in milliseconds.
    creation_time_in_millis: ?i64 = null,

    /// The unique ID of the new inference endpoint.
    id: ?[]const u8 = null,

    pub const json_field_names = .{
        .arn = "arn",
        .creation_time_in_millis = "creationTimeInMillis",
        .id = "id",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateMLEndpointInput, options: CallOptions) !CreateMLEndpointOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "neptune-db", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateMLEndpointInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("neptune-db", "neptunedata", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/ml/endpoints";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"id\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.instance_count) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"instanceCount\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.instance_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"instanceType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.ml_model_training_job_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"mlModelTrainingJobId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.ml_model_transform_job_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"mlModelTransformJobId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.model_name) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"modelName\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.neptune_iam_role_arn) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"neptuneIamRoleArn\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.update) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"update\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.volume_encryption_kms_key) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"volumeEncryptionKMSKey\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateMLEndpointOutput {
    var result: CreateMLEndpointOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(CreateMLEndpointOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}
