/// A structure containing the fast reset token used to initiate a fast reset.
pub const FastResetToken = struct {
    /// A UUID generated by the database in the `initiateDatabaseReset` action, and
    /// then consumed by the `performDatabaseReset` to reset the database.
    token: ?[]const u8 = null,

    pub const json_field_names = .{
        .token = "token",
    };
};
