pub const S3BucketRegion = enum {
    us_east_1,
    us_east_2,
    us_west_1,
    us_west_2,
    ca_central_1,
    sa_east_1,
    eu_north_1,
    eu_west_1,
    eu_west_2,
    eu_west_3,
    eu_central_1,
    me_south_1,
    af_south_1,
    ap_east_1,
    ap_northeast_1,
    ap_northeast_2,
    ap_southeast_1,
    ap_southeast_2,
    ap_south_1,
    cn_north_1,
    cn_northwest_1,
    us_gov_west_1,
    us_gov_east_1,
    ca_west_1,
    eu_south_2,
    il_central_1,
    me_central_1,
    ap_northeast_3,
    ap_southeast_3,
    ap_southeast_4,
    ap_southeast_5,
    ap_southeast_7,
    mx_central_1,
    ap_east_2,
    ap_south_2,
    eu_central_2,

    pub const json_field_names = .{
        .us_east_1 = "US_EAST_1",
        .us_east_2 = "US_EAST_2",
        .us_west_1 = "US_WEST_1",
        .us_west_2 = "US_WEST_2",
        .ca_central_1 = "CA_CENTRAL_1",
        .sa_east_1 = "SA_EAST_1",
        .eu_north_1 = "EU_NORTH_1",
        .eu_west_1 = "EU_WEST_1",
        .eu_west_2 = "EU_WEST_2",
        .eu_west_3 = "EU_WEST_3",
        .eu_central_1 = "EU_CENTRAL_1",
        .me_south_1 = "ME_SOUTH_1",
        .af_south_1 = "AF_SOUTH_1",
        .ap_east_1 = "AP_EAST_1",
        .ap_northeast_1 = "AP_NORTHEAST_1",
        .ap_northeast_2 = "AP_NORTHEAST_2",
        .ap_southeast_1 = "AP_SOUTHEAST_1",
        .ap_southeast_2 = "AP_SOUTHEAST_2",
        .ap_south_1 = "AP_SOUTH_1",
        .cn_north_1 = "CN_NORTH_1",
        .cn_northwest_1 = "CN_NORTHWEST_1",
        .us_gov_west_1 = "US_GOV_WEST_1",
        .us_gov_east_1 = "US_GOV_EAST_1",
        .ca_west_1 = "CA_WEST_1",
        .eu_south_2 = "EU_SOUTH_2",
        .il_central_1 = "IL_CENTRAL_1",
        .me_central_1 = "ME_CENTRAL_1",
        .ap_northeast_3 = "AP_NORTHEAST_3",
        .ap_southeast_3 = "AP_SOUTHEAST_3",
        .ap_southeast_4 = "AP_SOUTHEAST_4",
        .ap_southeast_5 = "AP_SOUTHEAST_5",
        .ap_southeast_7 = "AP_SOUTHEAST_7",
        .mx_central_1 = "MX_CENTRAL_1",
        .ap_east_2 = "AP_EAST_2",
        .ap_south_2 = "AP_SOUTH_2",
        .eu_central_2 = "EU_CENTRAL_2",
    };
};
