const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const ServiceError = @import("errors.zig").ServiceError;
const CustomModelTrainingParameters = @import("custom_model_training_parameters.zig").CustomModelTrainingParameters;

pub const StartMLModelTrainingJobInput = struct {
    /// The type of ML instance used in preparing and managing training of ML
    /// models. This is a CPU instance chosen based on memory requirements for
    /// processing the training data and model.
    base_processing_instance_type: ?[]const u8 = null,

    /// The configuration for custom model training. This is a JSON object.
    custom_model_training_parameters: ?CustomModelTrainingParameters = null,

    /// The job ID of the completed data-processing job that has created the data
    /// that the training will work with.
    data_processing_job_id: []const u8,

    /// Optimizes the cost of training machine-learning models by using Amazon
    /// Elastic Compute Cloud spot instances. The default is `False`.
    enable_managed_spot_training: ?bool = null,

    /// A unique identifier for the new job. The default is An autogenerated UUID.
    id: ?[]const u8 = null,

    /// Maximum total number of training jobs to start for the hyperparameter tuning
    /// job. The default is 2. Neptune ML automatically tunes the hyperparameters of
    /// the machine learning model. To obtain a model that performs well, use at
    /// least 10 jobs (in other words, set `maxHPONumberOfTrainingJobs` to 10). In
    /// general, the more tuning runs, the better the results.
    max_hpo_number_of_training_jobs: ?i32 = null,

    /// Maximum number of parallel training jobs to start for the hyperparameter
    /// tuning job. The default is 2. The number of parallel jobs you can run is
    /// limited by the available resources on your training instance.
    max_hpo_parallel_training_jobs: ?i32 = null,

    /// The ARN of an IAM role that provides Neptune access to SageMaker and Amazon
    /// S3 resources. This must be listed in your DB cluster parameter group or an
    /// error will occur.
    neptune_iam_role_arn: ?[]const u8 = null,

    /// The job ID of a completed model-training job that you want to update
    /// incrementally based on updated data.
    previous_model_training_job_id: ?[]const u8 = null,

    /// The Amazon Key Management Service (KMS) key that SageMaker uses to encrypt
    /// the output of the processing job. The default is none.
    s_3_output_encryption_kms_key: ?[]const u8 = null,

    /// The ARN of an IAM role for SageMaker execution.This must be listed in your
    /// DB cluster parameter group or an error will occur.
    sagemaker_iam_role_arn: ?[]const u8 = null,

    /// The VPC security group IDs. The default is None.
    security_group_ids: ?[]const []const u8 = null,

    /// The IDs of the subnets in the Neptune VPC. The default is None.
    subnets: ?[]const []const u8 = null,

    /// The type of ML instance used for model training. All Neptune ML models
    /// support CPU, GPU, and multiGPU training. The default is `ml.p3.2xlarge`.
    /// Choosing the right instance type for training depends on the task type,
    /// graph size, and your budget.
    training_instance_type: ?[]const u8 = null,

    /// The disk volume size of the training instance. Both input data and the
    /// output model are stored on disk, so the volume size must be large enough to
    /// hold both data sets. The default is 0. If not specified or 0, Neptune ML
    /// selects a disk volume size based on the recommendation generated in the data
    /// processing step.
    training_instance_volume_size_in_gb: ?i32 = null,

    /// Timeout in seconds for the training job. The default is 86,400 (1 day).
    training_time_out_in_seconds: ?i32 = null,

    /// The location in Amazon S3 where the model artifacts are to be stored.
    train_model_s3_location: []const u8,

    /// The Amazon Key Management Service (KMS) key that SageMaker uses to encrypt
    /// data on the storage volume attached to the ML compute instances that run the
    /// training job. The default is None.
    volume_encryption_kms_key: ?[]const u8 = null,

    pub const json_field_names = .{
        .base_processing_instance_type = "baseProcessingInstanceType",
        .custom_model_training_parameters = "customModelTrainingParameters",
        .data_processing_job_id = "dataProcessingJobId",
        .enable_managed_spot_training = "enableManagedSpotTraining",
        .id = "id",
        .max_hpo_number_of_training_jobs = "maxHPONumberOfTrainingJobs",
        .max_hpo_parallel_training_jobs = "maxHPOParallelTrainingJobs",
        .neptune_iam_role_arn = "neptuneIamRoleArn",
        .previous_model_training_job_id = "previousModelTrainingJobId",
        .s_3_output_encryption_kms_key = "s3OutputEncryptionKMSKey",
        .sagemaker_iam_role_arn = "sagemakerIamRoleArn",
        .security_group_ids = "securityGroupIds",
        .subnets = "subnets",
        .training_instance_type = "trainingInstanceType",
        .training_instance_volume_size_in_gb = "trainingInstanceVolumeSizeInGB",
        .training_time_out_in_seconds = "trainingTimeOutInSeconds",
        .train_model_s3_location = "trainModelS3Location",
        .volume_encryption_kms_key = "volumeEncryptionKMSKey",
    };
};

pub const StartMLModelTrainingJobOutput = struct {
    /// The ARN of the new model training job.
    arn: ?[]const u8 = null,

    /// The model training job creation time, in milliseconds.
    creation_time_in_millis: ?i64 = null,

    /// The unique ID of the new model training job.
    id: ?[]const u8 = null,

    pub const json_field_names = .{
        .arn = "arn",
        .creation_time_in_millis = "creationTimeInMillis",
        .id = "id",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: StartMLModelTrainingJobInput, options: CallOptions) !StartMLModelTrainingJobOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(alloc);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "neptunedata");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: StartMLModelTrainingJobInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("neptunedata", "neptunedata", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    const path = "/ml/modeltraining";

    var body_buf: std.ArrayList(u8) = .{};
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.base_processing_instance_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"baseProcessingInstanceType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.custom_model_training_parameters) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"customModelTrainingParameters\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"dataProcessingJobId\":");
    try aws.json.writeValue(@TypeOf(input.data_processing_job_id), input.data_processing_job_id, allocator, &body_buf);
    has_prev = true;
    if (input.enable_managed_spot_training) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"enableManagedSpotTraining\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"id\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.max_hpo_number_of_training_jobs) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"maxHPONumberOfTrainingJobs\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.max_hpo_parallel_training_jobs) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"maxHPOParallelTrainingJobs\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.neptune_iam_role_arn) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"neptuneIamRoleArn\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.previous_model_training_job_id) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"previousModelTrainingJobId\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.s_3_output_encryption_kms_key) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"s3OutputEncryptionKMSKey\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.sagemaker_iam_role_arn) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"sagemakerIamRoleArn\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.security_group_ids) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"securityGroupIds\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.subnets) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"subnets\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.training_instance_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"trainingInstanceType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.training_instance_volume_size_in_gb) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"trainingInstanceVolumeSizeInGB\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.training_time_out_in_seconds) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"trainingTimeOutInSeconds\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"trainModelS3Location\":");
    try aws.json.writeValue(@TypeOf(input.train_model_s3_location), input.train_model_s3_location, allocator, &body_buf);
    has_prev = true;
    if (input.volume_encryption_kms_key) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"volumeEncryptionKMSKey\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(host);
    request.method = .POST;
    request.path = path;
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !StartMLModelTrainingJobOutput {
    var result: StartMLModelTrainingJobOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(StartMLModelTrainingJobOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AccessDeniedException")) {
        return .{ .arena = arena, .kind = .{ .access_denied_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "BadRequestException")) {
        return .{ .arena = arena, .kind = .{ .bad_request_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "BulkLoadIdNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .bulk_load_id_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "CancelledByUserException")) {
        return .{ .arena = arena, .kind = .{ .cancelled_by_user_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ClientTimeoutException")) {
        return .{ .arena = arena, .kind = .{ .client_timeout_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConcurrentModificationException")) {
        return .{ .arena = arena, .kind = .{ .concurrent_modification_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConstraintViolationException")) {
        return .{ .arena = arena, .kind = .{ .constraint_violation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ExpiredStreamException")) {
        return .{ .arena = arena, .kind = .{ .expired_stream_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "FailureByQueryException")) {
        return .{ .arena = arena, .kind = .{ .failure_by_query_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "IllegalArgumentException")) {
        return .{ .arena = arena, .kind = .{ .illegal_argument_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InternalFailureException")) {
        return .{ .arena = arena, .kind = .{ .internal_failure_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidArgumentException")) {
        return .{ .arena = arena, .kind = .{ .invalid_argument_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidNumericDataException")) {
        return .{ .arena = arena, .kind = .{ .invalid_numeric_data_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidParameterException")) {
        return .{ .arena = arena, .kind = .{ .invalid_parameter_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "LoadUrlAccessDeniedException")) {
        return .{ .arena = arena, .kind = .{ .load_url_access_denied_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MalformedQueryException")) {
        return .{ .arena = arena, .kind = .{ .malformed_query_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MemoryLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .memory_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MethodNotAllowedException")) {
        return .{ .arena = arena, .kind = .{ .method_not_allowed_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MissingParameterException")) {
        return .{ .arena = arena, .kind = .{ .missing_parameter_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MLResourceNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .ml_resource_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ParsingException")) {
        return .{ .arena = arena, .kind = .{ .parsing_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "PreconditionsFailedException")) {
        return .{ .arena = arena, .kind = .{ .preconditions_failed_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "QueryLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .query_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "QueryLimitException")) {
        return .{ .arena = arena, .kind = .{ .query_limit_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "QueryTooLargeException")) {
        return .{ .arena = arena, .kind = .{ .query_too_large_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ReadOnlyViolationException")) {
        return .{ .arena = arena, .kind = .{ .read_only_violation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "S3Exception")) {
        return .{ .arena = arena, .kind = .{ .s3_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ServerShutdownException")) {
        return .{ .arena = arena, .kind = .{ .server_shutdown_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "StatisticsNotAvailableException")) {
        return .{ .arena = arena, .kind = .{ .statistics_not_available_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "StreamRecordsNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .stream_records_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ThrottlingException")) {
        return .{ .arena = arena, .kind = .{ .throttling_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TimeLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .time_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TooManyRequestsException")) {
        return .{ .arena = arena, .kind = .{ .too_many_requests_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "UnsupportedOperationException")) {
        return .{ .arena = arena, .kind = .{ .unsupported_operation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
