pub const SignalDecoderFailureReason = enum {
    duplicate_signal,
    conflicting_signal,
    signal_to_add_already_exists,
    signal_not_associated_with_network_interface,
    network_interface_type_incompatible_with_signal_decoder_type,
    signal_not_in_model,
    can_signal_info_is_null,
    obd_signal_info_is_null,
    no_decoder_info_for_signal_in_model,
    message_signal_info_is_null,
    signal_decoder_type_incompatible_with_message_signal_type,
    struct_size_mismatch,
    no_signal_in_catalog_for_decoder_signal,
    signal_decoder_incompatible_with_signal_catalog,
    empty_message_signal,
    custom_decoding_signal_info_is_null,

    pub const json_field_names = .{
        .duplicate_signal = "DUPLICATE_SIGNAL",
        .conflicting_signal = "CONFLICTING_SIGNAL",
        .signal_to_add_already_exists = "SIGNAL_TO_ADD_ALREADY_EXISTS",
        .signal_not_associated_with_network_interface = "SIGNAL_NOT_ASSOCIATED_WITH_NETWORK_INTERFACE",
        .network_interface_type_incompatible_with_signal_decoder_type = "NETWORK_INTERFACE_TYPE_INCOMPATIBLE_WITH_SIGNAL_DECODER_TYPE",
        .signal_not_in_model = "SIGNAL_NOT_IN_MODEL",
        .can_signal_info_is_null = "CAN_SIGNAL_INFO_IS_NULL",
        .obd_signal_info_is_null = "OBD_SIGNAL_INFO_IS_NULL",
        .no_decoder_info_for_signal_in_model = "NO_DECODER_INFO_FOR_SIGNAL_IN_MODEL",
        .message_signal_info_is_null = "MESSAGE_SIGNAL_INFO_IS_NULL",
        .signal_decoder_type_incompatible_with_message_signal_type = "SIGNAL_DECODER_TYPE_INCOMPATIBLE_WITH_MESSAGE_SIGNAL_TYPE",
        .struct_size_mismatch = "STRUCT_SIZE_MISMATCH",
        .no_signal_in_catalog_for_decoder_signal = "NO_SIGNAL_IN_CATALOG_FOR_DECODER_SIGNAL",
        .signal_decoder_incompatible_with_signal_catalog = "SIGNAL_DECODER_INCOMPATIBLE_WITH_SIGNAL_CATALOG",
        .empty_message_signal = "EMPTY_MESSAGE_SIGNAL",
        .custom_decoding_signal_info_is_null = "CUSTOM_DECODING_SIGNAL_INFO_IS_NULL",
    };
};
