const std = @import("std");

pub const Codec = enum {
    unknown,
    aac,
    ac3,
    amr,
    eac3,
    flac,
    mp2,
    mp3,
    opus,
    pcm,
    vorbis,
    wma,
    wma2,
    wmapro,
    av1,
    avc,
    dv,
    h263,
    hevc,
    jpeg2000,
    mjpeg,
    mpeg1,
    mp4_v,
    mpeg2,
    prores,
    qtrle,
    theora,
    uncompressed,
    vc1,
    vc3,
    vfw,
    vp8,
    vp9,
    c608,
    c708,
    webvtt,

    pub const json_field_names = .{
        .unknown = "UNKNOWN",
        .aac = "AAC",
        .ac3 = "AC3",
        .amr = "AMR",
        .eac3 = "EAC3",
        .flac = "FLAC",
        .mp2 = "MP2",
        .mp3 = "MP3",
        .opus = "OPUS",
        .pcm = "PCM",
        .vorbis = "VORBIS",
        .wma = "WMA",
        .wma2 = "WMA2",
        .wmapro = "WMAPRO",
        .av1 = "AV1",
        .avc = "AVC",
        .dv = "DV",
        .h263 = "H263",
        .hevc = "HEVC",
        .jpeg2000 = "JPEG2000",
        .mjpeg = "MJPEG",
        .mpeg1 = "MPEG1",
        .mp4_v = "MP4V",
        .mpeg2 = "MPEG2",
        .prores = "PRORES",
        .qtrle = "QTRLE",
        .theora = "THEORA",
        .uncompressed = "UNCOMPRESSED",
        .vc1 = "VC1",
        .vc3 = "VC3",
        .vfw = "VFW",
        .vp8 = "VP8",
        .vp9 = "VP9",
        .c608 = "C608",
        .c708 = "C708",
        .webvtt = "WEBVTT",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .unknown => "UNKNOWN",
            .aac => "AAC",
            .ac3 => "AC3",
            .amr => "AMR",
            .eac3 => "EAC3",
            .flac => "FLAC",
            .mp2 => "MP2",
            .mp3 => "MP3",
            .opus => "OPUS",
            .pcm => "PCM",
            .vorbis => "VORBIS",
            .wma => "WMA",
            .wma2 => "WMA2",
            .wmapro => "WMAPRO",
            .av1 => "AV1",
            .avc => "AVC",
            .dv => "DV",
            .h263 => "H263",
            .hevc => "HEVC",
            .jpeg2000 => "JPEG2000",
            .mjpeg => "MJPEG",
            .mpeg1 => "MPEG1",
            .mp4_v => "MP4V",
            .mpeg2 => "MPEG2",
            .prores => "PRORES",
            .qtrle => "QTRLE",
            .theora => "THEORA",
            .uncompressed => "UNCOMPRESSED",
            .vc1 => "VC1",
            .vc3 => "VC3",
            .vfw => "VFW",
            .vp8 => "VP8",
            .vp9 => "VP9",
            .c608 => "C608",
            .c708 => "C708",
            .webvtt => "WEBVTT",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        const fields = @typeInfo(@TypeOf(json_field_names)).@"struct".field_names;
        inline for (fields) |field_name| {
            if (std.mem.eql(u8, str, @field(json_field_names, field_name))) {
                return @field(@This(), field_name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
