/// Specify the language, using an ISO 639-2 three-letter code in all capital
/// letters. You can find a list of codes at:
/// https://www.loc.gov/standards/iso639-2/php/code_list.php
pub const LanguageCode = enum {
    eng,
    spa,
    fra,
    deu,
    ger,
    zho,
    ara,
    hin,
    jpn,
    rus,
    por,
    ita,
    urd,
    vie,
    kor,
    pan,
    abk,
    aar,
    afr,
    aka,
    sqi,
    amh,
    arg,
    hye,
    @"asm",
    ava,
    ave,
    aym,
    aze,
    bam,
    bak,
    eus,
    bel,
    ben,
    bih,
    bis,
    bos,
    bre,
    bul,
    mya,
    cat,
    khm,
    cha,
    che,
    nya,
    chu,
    chv,
    cor,
    cos,
    cre,
    hrv,
    ces,
    dan,
    div,
    nld,
    dzo,
    enm,
    epo,
    est,
    ewe,
    fao,
    fij,
    fin,
    frm,
    ful,
    gla,
    glg,
    lug,
    kat,
    ell,
    grn,
    guj,
    hat,
    hau,
    heb,
    her,
    hmo,
    hun,
    isl,
    ido,
    ibo,
    ind,
    ina,
    ile,
    iku,
    ipk,
    gle,
    jav,
    kal,
    kan,
    kau,
    kas,
    kaz,
    kik,
    kin,
    kir,
    kom,
    kon,
    kua,
    kur,
    lao,
    lat,
    lav,
    lim,
    lin,
    lit,
    lub,
    ltz,
    mkd,
    mlg,
    msa,
    mal,
    mlt,
    glv,
    mri,
    mar,
    mah,
    mon,
    nau,
    nav,
    nde,
    nbl,
    ndo,
    nep,
    sme,
    nor,
    nob,
    nno,
    oci,
    oji,
    ori,
    orm,
    oss,
    pli,
    fas,
    pol,
    pus,
    que,
    qaa,
    ron,
    roh,
    run,
    smo,
    sag,
    san,
    srd,
    srb,
    sna,
    iii,
    snd,
    sin,
    slk,
    slv,
    som,
    sot,
    sun,
    swa,
    ssw,
    swe,
    tgl,
    tah,
    tgk,
    tam,
    tat,
    tel,
    tha,
    bod,
    tir,
    ton,
    tso,
    tsn,
    tur,
    tuk,
    twi,
    uig,
    ukr,
    uzb,
    ven,
    vol,
    wln,
    cym,
    fry,
    wol,
    xho,
    yid,
    yor,
    zha,
    zul,
    orj,
    qpc,
    tng,
    srp,

    pub const json_field_names = .{
        .eng = "ENG",
        .spa = "SPA",
        .fra = "FRA",
        .deu = "DEU",
        .ger = "GER",
        .zho = "ZHO",
        .ara = "ARA",
        .hin = "HIN",
        .jpn = "JPN",
        .rus = "RUS",
        .por = "POR",
        .ita = "ITA",
        .urd = "URD",
        .vie = "VIE",
        .kor = "KOR",
        .pan = "PAN",
        .abk = "ABK",
        .aar = "AAR",
        .afr = "AFR",
        .aka = "AKA",
        .sqi = "SQI",
        .amh = "AMH",
        .arg = "ARG",
        .hye = "HYE",
        .@"asm" = "ASM",
        .ava = "AVA",
        .ave = "AVE",
        .aym = "AYM",
        .aze = "AZE",
        .bam = "BAM",
        .bak = "BAK",
        .eus = "EUS",
        .bel = "BEL",
        .ben = "BEN",
        .bih = "BIH",
        .bis = "BIS",
        .bos = "BOS",
        .bre = "BRE",
        .bul = "BUL",
        .mya = "MYA",
        .cat = "CAT",
        .khm = "KHM",
        .cha = "CHA",
        .che = "CHE",
        .nya = "NYA",
        .chu = "CHU",
        .chv = "CHV",
        .cor = "COR",
        .cos = "COS",
        .cre = "CRE",
        .hrv = "HRV",
        .ces = "CES",
        .dan = "DAN",
        .div = "DIV",
        .nld = "NLD",
        .dzo = "DZO",
        .enm = "ENM",
        .epo = "EPO",
        .est = "EST",
        .ewe = "EWE",
        .fao = "FAO",
        .fij = "FIJ",
        .fin = "FIN",
        .frm = "FRM",
        .ful = "FUL",
        .gla = "GLA",
        .glg = "GLG",
        .lug = "LUG",
        .kat = "KAT",
        .ell = "ELL",
        .grn = "GRN",
        .guj = "GUJ",
        .hat = "HAT",
        .hau = "HAU",
        .heb = "HEB",
        .her = "HER",
        .hmo = "HMO",
        .hun = "HUN",
        .isl = "ISL",
        .ido = "IDO",
        .ibo = "IBO",
        .ind = "IND",
        .ina = "INA",
        .ile = "ILE",
        .iku = "IKU",
        .ipk = "IPK",
        .gle = "GLE",
        .jav = "JAV",
        .kal = "KAL",
        .kan = "KAN",
        .kau = "KAU",
        .kas = "KAS",
        .kaz = "KAZ",
        .kik = "KIK",
        .kin = "KIN",
        .kir = "KIR",
        .kom = "KOM",
        .kon = "KON",
        .kua = "KUA",
        .kur = "KUR",
        .lao = "LAO",
        .lat = "LAT",
        .lav = "LAV",
        .lim = "LIM",
        .lin = "LIN",
        .lit = "LIT",
        .lub = "LUB",
        .ltz = "LTZ",
        .mkd = "MKD",
        .mlg = "MLG",
        .msa = "MSA",
        .mal = "MAL",
        .mlt = "MLT",
        .glv = "GLV",
        .mri = "MRI",
        .mar = "MAR",
        .mah = "MAH",
        .mon = "MON",
        .nau = "NAU",
        .nav = "NAV",
        .nde = "NDE",
        .nbl = "NBL",
        .ndo = "NDO",
        .nep = "NEP",
        .sme = "SME",
        .nor = "NOR",
        .nob = "NOB",
        .nno = "NNO",
        .oci = "OCI",
        .oji = "OJI",
        .ori = "ORI",
        .orm = "ORM",
        .oss = "OSS",
        .pli = "PLI",
        .fas = "FAS",
        .pol = "POL",
        .pus = "PUS",
        .que = "QUE",
        .qaa = "QAA",
        .ron = "RON",
        .roh = "ROH",
        .run = "RUN",
        .smo = "SMO",
        .sag = "SAG",
        .san = "SAN",
        .srd = "SRD",
        .srb = "SRB",
        .sna = "SNA",
        .iii = "III",
        .snd = "SND",
        .sin = "SIN",
        .slk = "SLK",
        .slv = "SLV",
        .som = "SOM",
        .sot = "SOT",
        .sun = "SUN",
        .swa = "SWA",
        .ssw = "SSW",
        .swe = "SWE",
        .tgl = "TGL",
        .tah = "TAH",
        .tgk = "TGK",
        .tam = "TAM",
        .tat = "TAT",
        .tel = "TEL",
        .tha = "THA",
        .bod = "BOD",
        .tir = "TIR",
        .ton = "TON",
        .tso = "TSO",
        .tsn = "TSN",
        .tur = "TUR",
        .tuk = "TUK",
        .twi = "TWI",
        .uig = "UIG",
        .ukr = "UKR",
        .uzb = "UZB",
        .ven = "VEN",
        .vol = "VOL",
        .wln = "WLN",
        .cym = "CYM",
        .fry = "FRY",
        .wol = "WOL",
        .xho = "XHO",
        .yid = "YID",
        .yor = "YOR",
        .zha = "ZHA",
        .zul = "ZUL",
        .orj = "ORJ",
        .qpc = "QPC",
        .tng = "TNG",
        .srp = "SRP",
    };
};
