const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const ServiceError = @import("errors.zig").ServiceError;
const ActionType = @import("action_type.zig").ActionType;

pub const GetProfileHistoryRecordInput = struct {
    /// The unique name of the domain for which to return a profile history record.
    domain_name: []const u8,

    /// The unique identifier of the profile history record to return.
    id: []const u8,

    /// The unique identifier of the profile for which to return a history record.
    profile_id: []const u8,

    pub const json_field_names = .{
        .domain_name = "DomainName",
        .id = "Id",
        .profile_id = "ProfileId",
    };
};

pub const GetProfileHistoryRecordOutput = struct {
    /// The action type of the profile history record.
    action_type: ActionType,

    /// A string containing the customer profile, profile object, or profile key
    /// content.
    content: ?[]const u8 = null,

    /// The timestamp of when the profile history record was created.
    created_at: i64,

    /// The unique identifier of the profile history record.
    id: []const u8,

    /// The timestamp of when the profile history record was last updated.
    last_updated_at: ?i64 = null,

    /// The name of the profile object type.
    object_type_name: []const u8,

    /// The Amazon Resource Name (ARN) of the person or service principal who
    /// performed the action.
    performed_by: ?[]const u8 = null,

    /// The unique identifier of the profile object generated by the service.
    profile_object_unique_key: ?[]const u8 = null,

    pub const json_field_names = .{
        .action_type = "ActionType",
        .content = "Content",
        .created_at = "CreatedAt",
        .id = "Id",
        .last_updated_at = "LastUpdatedAt",
        .object_type_name = "ObjectTypeName",
        .performed_by = "PerformedBy",
        .profile_object_unique_key = "ProfileObjectUniqueKey",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetProfileHistoryRecordInput, options: CallOptions) !GetProfileHistoryRecordOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "profile");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetProfileHistoryRecordInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("profile", "Customer Profiles", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    var path_buf: std.ArrayList(u8) = .{};
    try path_buf.appendSlice(allocator, "/domains/");
    try path_buf.appendSlice(allocator, input.domain_name);
    try path_buf.appendSlice(allocator, "/profiles/");
    try path_buf.appendSlice(allocator, input.profile_id);
    try path_buf.appendSlice(allocator, "/history-records/");
    try path_buf.appendSlice(allocator, input.id);
    const path = try path_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(host);
    request.method = .GET;
    request.path = path;
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetProfileHistoryRecordOutput {
    var result: GetProfileHistoryRecordOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(GetProfileHistoryRecordOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AccessDeniedException")) {
        return .{ .arena = arena, .kind = .{ .access_denied_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "BadRequestException")) {
        return .{ .arena = arena, .kind = .{ .bad_request_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InternalServerException")) {
        return .{ .arena = arena, .kind = .{ .internal_server_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .resource_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ThrottlingException")) {
        return .{ .arena = arena, .kind = .{ .throttling_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
