/// A ProfileObject in a list of ProfileObjects.
pub const ListProfileObjectsItem = struct {
    /// A JSON representation of a ProfileObject that belongs to a profile.
    object: ?[]const u8 = null,

    /// Specifies the kind of object being added to a profile, such as
    /// "Salesforce-Account."
    object_type_name: ?[]const u8 = null,

    /// The unique identifier of the ProfileObject generated by the service.
    profile_object_unique_key: ?[]const u8 = null,

    pub const json_field_names = .{
        .object = "Object",
        .object_type_name = "ObjectTypeName",
        .profile_object_unique_key = "ProfileObjectUniqueKey",
    };
};
