const ActionType = @import("action_type.zig").ActionType;

/// Contains profile history record metadata.
pub const ProfileHistoryRecord = struct {
    /// The action type of the profile history record.
    action_type: ActionType,

    /// The timestamp of when the profile history record was created.
    created_at: i64,

    /// The unique identifier of the profile history record.
    id: []const u8,

    /// The timestamp of when the profile history record was last updated.
    last_updated_at: ?i64 = null,

    /// The name of the profile object type.
    object_type_name: []const u8,

    /// The Amazon Resource Name (ARN) of the person or service principal who
    /// performed the action.
    performed_by: ?[]const u8 = null,

    /// The unique identifier of the profile object generated by the service.
    profile_object_unique_key: ?[]const u8 = null,

    pub const json_field_names = .{
        .action_type = "ActionType",
        .created_at = "CreatedAt",
        .id = "Id",
        .last_updated_at = "LastUpdatedAt",
        .object_type_name = "ObjectTypeName",
        .performed_by = "PerformedBy",
        .profile_object_unique_key = "ProfileObjectUniqueKey",
    };
};
