pub const StandardIdentifier = enum {
    profile,
    asset,
    case,
    order,
    communication_record,
    air_preference,
    hotel_preference,
    air_booking,
    air_segment,
    hotel_reservation,
    hotel_stay_revenue,
    loyalty,
    loyalty_transaction,
    loyalty_promotion,
    unique,
    secondary,
    lookup_only,
    new_only,

    pub const json_field_names = .{
        .profile = "PROFILE",
        .asset = "ASSET",
        .case = "CASE",
        .order = "ORDER",
        .communication_record = "COMMUNICATION_RECORD",
        .air_preference = "AIR_PREFERENCE",
        .hotel_preference = "HOTEL_PREFERENCE",
        .air_booking = "AIR_BOOKING",
        .air_segment = "AIR_SEGMENT",
        .hotel_reservation = "HOTEL_RESERVATION",
        .hotel_stay_revenue = "HOTEL_STAY_REVENUE",
        .loyalty = "LOYALTY",
        .loyalty_transaction = "LOYALTY_TRANSACTION",
        .loyalty_promotion = "LOYALTY_PROMOTION",
        .unique = "UNIQUE",
        .secondary = "SECONDARY",
        .lookup_only = "LOOKUP_ONLY",
        .new_only = "NEW_ONLY",
    };
};
