pub const ConnectorType = enum {
    salesforce,
    singular,
    slack,
    redshift,
    s3,
    marketo,
    googleanalytics,
    zendesk,
    servicenow,
    datadog,
    trendmicro,
    snowflake,
    dynatrace,
    infornexus,
    amplitude,
    veeva,
    eventbridge,
    lookoutmetrics,
    upsolver,
    honeycode,
    customerprofiles,
    sapodata,
    customconnector,
    pardot,

    pub const json_field_names = .{
        .salesforce = "SALESFORCE",
        .singular = "SINGULAR",
        .slack = "SLACK",
        .redshift = "REDSHIFT",
        .s3 = "S3",
        .marketo = "MARKETO",
        .googleanalytics = "GOOGLEANALYTICS",
        .zendesk = "ZENDESK",
        .servicenow = "SERVICENOW",
        .datadog = "DATADOG",
        .trendmicro = "TRENDMICRO",
        .snowflake = "SNOWFLAKE",
        .dynatrace = "DYNATRACE",
        .infornexus = "INFORNEXUS",
        .amplitude = "AMPLITUDE",
        .veeva = "VEEVA",
        .eventbridge = "EVENTBRIDGE",
        .lookoutmetrics = "LOOKOUTMETRICS",
        .upsolver = "UPSOLVER",
        .honeycode = "HONEYCODE",
        .customerprofiles = "CUSTOMERPROFILES",
        .sapodata = "SAPODATA",
        .customconnector = "CUSTOMCONNECTOR",
        .pardot = "PARDOT",
    };
};
