const std = @import("std");

pub const ConnectionType = enum {
    jdbc,
    sftp,
    mongodb,
    kafka,
    network,
    marketplace,
    custom,
    salesforce,
    view_validation_redshift,
    view_validation_athena,
    googleads,
    googlesheets,
    googleanalytics4,
    servicenow,
    marketo,
    sapodata,
    zendesk,
    jiracloud,
    netsuiteerp,
    hubspot,
    facebookads,
    instagramads,
    zohocrm,
    salesforcepardot,
    salesforcemarketingcloud,
    adobeanalytics,
    slack,
    linkedin,
    mixpanel,
    asana,
    stripe,
    smartsheet,
    datadog,
    woocommerce,
    intercom,
    snapchatads,
    paypal,
    quickbooks,
    facebookpageinsights,
    freshdesk,
    twilio,
    docusignmonitor,
    freshsales,
    zoom,
    googlesearchconsole,
    salesforcecommercecloud,
    sapconcur,
    dynatrace,
    microsoftdynamic365_financeandops,
    microsoftteams,
    blackbaudraiseredgenxt,
    mailchimp,
    gitlab,
    pendo,
    productboard,
    circleci,
    pipedive,
    sendgrid,
    azurecosmos,
    azuresql,
    bigquery,
    blackbaud,
    clouderahive,
    clouderaimpala,
    cloudwatch,
    cloudwatchmetrics,
    cmdb,
    datalakegen2,
    db2,
    db2_as400,
    documentdb,
    domo,
    dynamodb,
    googlecloudstorage,
    hbase,
    kustomer,
    microsoftdynamics365_crm,
    monday,
    mysql,
    okta,
    opensearch,
    oracle,
    pipedrive,
    postgresql,
    saphana,
    sqlserver,
    synapse,
    teradata,
    teradatanos,
    timestream,
    tpcds,
    vertica,

    pub const json_field_names = .{
        .jdbc = "JDBC",
        .sftp = "SFTP",
        .mongodb = "MONGODB",
        .kafka = "KAFKA",
        .network = "NETWORK",
        .marketplace = "MARKETPLACE",
        .custom = "CUSTOM",
        .salesforce = "SALESFORCE",
        .view_validation_redshift = "VIEW_VALIDATION_REDSHIFT",
        .view_validation_athena = "VIEW_VALIDATION_ATHENA",
        .googleads = "GOOGLEADS",
        .googlesheets = "GOOGLESHEETS",
        .googleanalytics4 = "GOOGLEANALYTICS4",
        .servicenow = "SERVICENOW",
        .marketo = "MARKETO",
        .sapodata = "SAPODATA",
        .zendesk = "ZENDESK",
        .jiracloud = "JIRACLOUD",
        .netsuiteerp = "NETSUITEERP",
        .hubspot = "HUBSPOT",
        .facebookads = "FACEBOOKADS",
        .instagramads = "INSTAGRAMADS",
        .zohocrm = "ZOHOCRM",
        .salesforcepardot = "SALESFORCEPARDOT",
        .salesforcemarketingcloud = "SALESFORCEMARKETINGCLOUD",
        .adobeanalytics = "ADOBEANALYTICS",
        .slack = "SLACK",
        .linkedin = "LINKEDIN",
        .mixpanel = "MIXPANEL",
        .asana = "ASANA",
        .stripe = "STRIPE",
        .smartsheet = "SMARTSHEET",
        .datadog = "DATADOG",
        .woocommerce = "WOOCOMMERCE",
        .intercom = "INTERCOM",
        .snapchatads = "SNAPCHATADS",
        .paypal = "PAYPAL",
        .quickbooks = "QUICKBOOKS",
        .facebookpageinsights = "FACEBOOKPAGEINSIGHTS",
        .freshdesk = "FRESHDESK",
        .twilio = "TWILIO",
        .docusignmonitor = "DOCUSIGNMONITOR",
        .freshsales = "FRESHSALES",
        .zoom = "ZOOM",
        .googlesearchconsole = "GOOGLESEARCHCONSOLE",
        .salesforcecommercecloud = "SALESFORCECOMMERCECLOUD",
        .sapconcur = "SAPCONCUR",
        .dynatrace = "DYNATRACE",
        .microsoftdynamic365_financeandops = "MICROSOFTDYNAMIC365FINANCEANDOPS",
        .microsoftteams = "MICROSOFTTEAMS",
        .blackbaudraiseredgenxt = "BLACKBAUDRAISEREDGENXT",
        .mailchimp = "MAILCHIMP",
        .gitlab = "GITLAB",
        .pendo = "PENDO",
        .productboard = "PRODUCTBOARD",
        .circleci = "CIRCLECI",
        .pipedive = "PIPEDIVE",
        .sendgrid = "SENDGRID",
        .azurecosmos = "AZURECOSMOS",
        .azuresql = "AZURESQL",
        .bigquery = "BIGQUERY",
        .blackbaud = "BLACKBAUD",
        .clouderahive = "CLOUDERAHIVE",
        .clouderaimpala = "CLOUDERAIMPALA",
        .cloudwatch = "CLOUDWATCH",
        .cloudwatchmetrics = "CLOUDWATCHMETRICS",
        .cmdb = "CMDB",
        .datalakegen2 = "DATALAKEGEN2",
        .db2 = "DB2",
        .db2_as400 = "DB2AS400",
        .documentdb = "DOCUMENTDB",
        .domo = "DOMO",
        .dynamodb = "DYNAMODB",
        .googlecloudstorage = "GOOGLECLOUDSTORAGE",
        .hbase = "HBASE",
        .kustomer = "KUSTOMER",
        .microsoftdynamics365_crm = "MICROSOFTDYNAMICS365CRM",
        .monday = "MONDAY",
        .mysql = "MYSQL",
        .okta = "OKTA",
        .opensearch = "OPENSEARCH",
        .oracle = "ORACLE",
        .pipedrive = "PIPEDRIVE",
        .postgresql = "POSTGRESQL",
        .saphana = "SAPHANA",
        .sqlserver = "SQLSERVER",
        .synapse = "SYNAPSE",
        .teradata = "TERADATA",
        .teradatanos = "TERADATANOS",
        .timestream = "TIMESTREAM",
        .tpcds = "TPCDS",
        .vertica = "VERTICA",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .jdbc => "JDBC",
            .sftp => "SFTP",
            .mongodb => "MONGODB",
            .kafka => "KAFKA",
            .network => "NETWORK",
            .marketplace => "MARKETPLACE",
            .custom => "CUSTOM",
            .salesforce => "SALESFORCE",
            .view_validation_redshift => "VIEW_VALIDATION_REDSHIFT",
            .view_validation_athena => "VIEW_VALIDATION_ATHENA",
            .googleads => "GOOGLEADS",
            .googlesheets => "GOOGLESHEETS",
            .googleanalytics4 => "GOOGLEANALYTICS4",
            .servicenow => "SERVICENOW",
            .marketo => "MARKETO",
            .sapodata => "SAPODATA",
            .zendesk => "ZENDESK",
            .jiracloud => "JIRACLOUD",
            .netsuiteerp => "NETSUITEERP",
            .hubspot => "HUBSPOT",
            .facebookads => "FACEBOOKADS",
            .instagramads => "INSTAGRAMADS",
            .zohocrm => "ZOHOCRM",
            .salesforcepardot => "SALESFORCEPARDOT",
            .salesforcemarketingcloud => "SALESFORCEMARKETINGCLOUD",
            .adobeanalytics => "ADOBEANALYTICS",
            .slack => "SLACK",
            .linkedin => "LINKEDIN",
            .mixpanel => "MIXPANEL",
            .asana => "ASANA",
            .stripe => "STRIPE",
            .smartsheet => "SMARTSHEET",
            .datadog => "DATADOG",
            .woocommerce => "WOOCOMMERCE",
            .intercom => "INTERCOM",
            .snapchatads => "SNAPCHATADS",
            .paypal => "PAYPAL",
            .quickbooks => "QUICKBOOKS",
            .facebookpageinsights => "FACEBOOKPAGEINSIGHTS",
            .freshdesk => "FRESHDESK",
            .twilio => "TWILIO",
            .docusignmonitor => "DOCUSIGNMONITOR",
            .freshsales => "FRESHSALES",
            .zoom => "ZOOM",
            .googlesearchconsole => "GOOGLESEARCHCONSOLE",
            .salesforcecommercecloud => "SALESFORCECOMMERCECLOUD",
            .sapconcur => "SAPCONCUR",
            .dynatrace => "DYNATRACE",
            .microsoftdynamic365_financeandops => "MICROSOFTDYNAMIC365FINANCEANDOPS",
            .microsoftteams => "MICROSOFTTEAMS",
            .blackbaudraiseredgenxt => "BLACKBAUDRAISEREDGENXT",
            .mailchimp => "MAILCHIMP",
            .gitlab => "GITLAB",
            .pendo => "PENDO",
            .productboard => "PRODUCTBOARD",
            .circleci => "CIRCLECI",
            .pipedive => "PIPEDIVE",
            .sendgrid => "SENDGRID",
            .azurecosmos => "AZURECOSMOS",
            .azuresql => "AZURESQL",
            .bigquery => "BIGQUERY",
            .blackbaud => "BLACKBAUD",
            .clouderahive => "CLOUDERAHIVE",
            .clouderaimpala => "CLOUDERAIMPALA",
            .cloudwatch => "CLOUDWATCH",
            .cloudwatchmetrics => "CLOUDWATCHMETRICS",
            .cmdb => "CMDB",
            .datalakegen2 => "DATALAKEGEN2",
            .db2 => "DB2",
            .db2_as400 => "DB2AS400",
            .documentdb => "DOCUMENTDB",
            .domo => "DOMO",
            .dynamodb => "DYNAMODB",
            .googlecloudstorage => "GOOGLECLOUDSTORAGE",
            .hbase => "HBASE",
            .kustomer => "KUSTOMER",
            .microsoftdynamics365_crm => "MICROSOFTDYNAMICS365CRM",
            .monday => "MONDAY",
            .mysql => "MYSQL",
            .okta => "OKTA",
            .opensearch => "OPENSEARCH",
            .oracle => "ORACLE",
            .pipedrive => "PIPEDRIVE",
            .postgresql => "POSTGRESQL",
            .saphana => "SAPHANA",
            .sqlserver => "SQLSERVER",
            .synapse => "SYNAPSE",
            .teradata => "TERADATA",
            .teradatanos => "TERADATANOS",
            .timestream => "TIMESTREAM",
            .tpcds => "TPCDS",
            .vertica => "VERTICA",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
