pub const FieldDataType = enum {
    int,
    smallint,
    bigint,
    float,
    long,
    date,
    boolean,
    map,
    array,
    string,
    timestamp,
    decimal,
    byte,
    short,
    double,
    @"struct",
    binary,
    @"union",

    pub const json_field_names = .{
        .int = "INT",
        .smallint = "SMALLINT",
        .bigint = "BIGINT",
        .float = "FLOAT",
        .long = "LONG",
        .date = "DATE",
        .boolean = "BOOLEAN",
        .map = "MAP",
        .array = "ARRAY",
        .string = "STRING",
        .timestamp = "TIMESTAMP",
        .decimal = "DECIMAL",
        .byte = "BYTE",
        .short = "SHORT",
        .double = "DOUBLE",
        .@"struct" = "STRUCT",
        .binary = "BINARY",
        .@"union" = "UNION",
    };
};
