const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Language = @import("language.zig").Language;
const Location = @import("location.zig").Location;
const MappingEntry = @import("mapping_entry.zig").MappingEntry;
const CatalogEntry = @import("catalog_entry.zig").CatalogEntry;

pub const GetPlanInput = struct {
    /// A map to hold additional optional key-value parameters.
    ///
    /// Currently, these key-value pairs are supported:
    ///
    /// * `inferSchema`  —  Specifies whether to set `inferSchema` to true or false
    ///   for the default script generated by an Glue job. For example, to set
    ///   `inferSchema` to true, pass the following key value pair:
    ///
    /// `--additional-plan-options-map '{"inferSchema":"true"}'`
    additional_plan_options_map: ?[]const aws.map.StringMapEntry = null,

    /// The programming language of the code to perform the mapping.
    language: ?Language = null,

    /// The parameters for the mapping.
    location: ?Location = null,

    /// The list of mappings from a source table to target tables.
    mapping: []const MappingEntry,

    /// The target tables.
    sinks: ?[]const CatalogEntry = null,

    /// The source table.
    source: CatalogEntry,

    pub const json_field_names = .{
        .additional_plan_options_map = "AdditionalPlanOptionsMap",
        .language = "Language",
        .location = "Location",
        .mapping = "Mapping",
        .sinks = "Sinks",
        .source = "Source",
    };
};

pub const GetPlanOutput = struct {
    /// A Python script to perform the mapping.
    python_script: ?[]const u8 = null,

    /// The Scala code to perform the mapping.
    scala_code: ?[]const u8 = null,

    pub const json_field_names = .{
        .python_script = "PythonScript",
        .scala_code = "ScalaCode",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetPlanInput, options: CallOptions) !GetPlanOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "glue", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetPlanInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("glue", "Glue", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "AWSGlue.GetPlan");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetPlanOutput {
    _ = status;
    _ = headers;
    if (body.len == 0) return .{};
    return aws.json.parseJsonObject(GetPlanOutput, body, allocator);
}
