pub const EntitySubType = enum {
    name,
    dx_name,
    dosage,
    route_or_mode,
    form,
    frequency,
    duration,
    generic_name,
    brand_name,
    strength,
    rate,
    acuity,
    test_name,
    test_value,
    test_units,
    test_unit,
    procedure_name,
    treatment_name,
    date,
    age,
    contact_point,
    phone_or_fax,
    email,
    identifier,
    id,
    url,
    address,
    profession,
    system_organ_site,
    direction,
    quality,
    quantity,
    time_expression,
    time_to_medication_name,
    time_to_dx_name,
    time_to_test_name,
    time_to_procedure_name,
    time_to_treatment_name,
    amount,
    gender,
    race_ethnicity,
    allergies,
    tobacco_use,
    alcohol_consumption,
    rec_drug_use,

    pub const json_field_names = .{
        .name = "NAME",
        .dx_name = "DX_NAME",
        .dosage = "DOSAGE",
        .route_or_mode = "ROUTE_OR_MODE",
        .form = "FORM",
        .frequency = "FREQUENCY",
        .duration = "DURATION",
        .generic_name = "GENERIC_NAME",
        .brand_name = "BRAND_NAME",
        .strength = "STRENGTH",
        .rate = "RATE",
        .acuity = "ACUITY",
        .test_name = "TEST_NAME",
        .test_value = "TEST_VALUE",
        .test_units = "TEST_UNITS",
        .test_unit = "TEST_UNIT",
        .procedure_name = "PROCEDURE_NAME",
        .treatment_name = "TREATMENT_NAME",
        .date = "DATE",
        .age = "AGE",
        .contact_point = "CONTACT_POINT",
        .phone_or_fax = "PHONE_OR_FAX",
        .email = "EMAIL",
        .identifier = "IDENTIFIER",
        .id = "ID",
        .url = "URL",
        .address = "ADDRESS",
        .profession = "PROFESSION",
        .system_organ_site = "SYSTEM_ORGAN_SITE",
        .direction = "DIRECTION",
        .quality = "QUALITY",
        .quantity = "QUANTITY",
        .time_expression = "TIME_EXPRESSION",
        .time_to_medication_name = "TIME_TO_MEDICATION_NAME",
        .time_to_dx_name = "TIME_TO_DX_NAME",
        .time_to_test_name = "TIME_TO_TEST_NAME",
        .time_to_procedure_name = "TIME_TO_PROCEDURE_NAME",
        .time_to_treatment_name = "TIME_TO_TREATMENT_NAME",
        .amount = "AMOUNT",
        .gender = "GENDER",
        .race_ethnicity = "RACE_ETHNICITY",
        .allergies = "ALLERGIES",
        .tobacco_use = "TOBACCO_USE",
        .alcohol_consumption = "ALCOHOL_CONSUMPTION",
        .rec_drug_use = "REC_DRUG_USE",
    };
};
