pub const RelationshipType = enum {
    every,
    with_dosage,
    administered_via,
    @"for",
    negative,
    overlap,
    dosage,
    route_or_mode,
    form,
    frequency,
    duration,
    strength,
    rate,
    acuity,
    test_value,
    test_units,
    test_unit,
    direction,
    system_organ_site,
    amount,
    usage,
    quality,

    pub const json_field_names = .{
        .every = "EVERY",
        .with_dosage = "WITH_DOSAGE",
        .administered_via = "ADMINISTERED_VIA",
        .@"for" = "FOR",
        .negative = "NEGATIVE",
        .overlap = "OVERLAP",
        .dosage = "DOSAGE",
        .route_or_mode = "ROUTE_OR_MODE",
        .form = "FORM",
        .frequency = "FREQUENCY",
        .duration = "DURATION",
        .strength = "STRENGTH",
        .rate = "RATE",
        .acuity = "ACUITY",
        .test_value = "TEST_VALUE",
        .test_units = "TEST_UNITS",
        .test_unit = "TEST_UNIT",
        .direction = "DIRECTION",
        .system_organ_site = "SYSTEM_ORGAN_SITE",
        .amount = "AMOUNT",
        .usage = "USAGE",
        .quality = "QUALITY",
    };
};
