const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const VariantImportItemDetail = @import("variant_import_item_detail.zig").VariantImportItemDetail;
const JobStatus = @import("job_status.zig").JobStatus;

pub const GetVariantImportJobInput = struct {
    /// The job's ID.
    job_id: []const u8,

    pub const json_field_names = .{
        .job_id = "jobId",
    };
};

pub const GetVariantImportJobOutput = struct {
    /// The annotation schema generated by the parsed annotation data.
    annotation_fields: ?[]const aws.map.StringMapEntry = null,

    /// When the job completed.
    completion_time: ?i64 = null,

    /// When the job was created.
    creation_time: i64,

    /// The job's destination variant store.
    destination_name: []const u8,

    /// The job's ID.
    id: []const u8,

    /// The job's items.
    items: ?[]const VariantImportItemDetail = null,

    /// The job's service role ARN.
    role_arn: []const u8,

    /// The job's left normalization setting.
    run_left_normalization: ?bool = null,

    /// The job's status.
    status: JobStatus,

    /// The job's status message.
    status_message: []const u8,

    /// When the job was updated.
    update_time: i64,

    pub const json_field_names = .{
        .annotation_fields = "annotationFields",
        .completion_time = "completionTime",
        .creation_time = "creationTime",
        .destination_name = "destinationName",
        .id = "id",
        .items = "items",
        .role_arn = "roleArn",
        .run_left_normalization = "runLeftNormalization",
        .status = "status",
        .status_message = "statusMessage",
        .update_time = "updateTime",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetVariantImportJobInput, options: CallOptions) !GetVariantImportJobOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "omics", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetVariantImportJobInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("omics", "Omics", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/import/variant/");
    try path_buf.appendSlice(allocator, input.job_id);
    const path = try path_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(ep.host);
    request.method = .GET;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetVariantImportJobOutput {
    const result: GetVariantImportJobOutput = try aws.json.parseJsonObject(
        GetVariantImportJobOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
