const aws = @import("aws");

const JobStatus = @import("job_status.zig").JobStatus;

/// A variant import job.
pub const VariantImportJobItem = struct {
    /// The annotation schema generated by the parsed annotation data.
    annotation_fields: ?[]const aws.map.StringMapEntry = null,

    /// When the job completed.
    completion_time: ?i64 = null,

    /// When the job was created.
    creation_time: i64,

    /// The job's destination variant store.
    destination_name: []const u8,

    /// The job's ID.
    id: []const u8,

    /// The job's service role ARN.
    role_arn: []const u8,

    /// The job's left normalization setting.
    run_left_normalization: bool = false,

    /// The job's status.
    status: JobStatus,

    /// When the job was updated.
    update_time: i64,

    pub const json_field_names = .{
        .annotation_fields = "annotationFields",
        .completion_time = "completionTime",
        .creation_time = "creationTime",
        .destination_name = "destinationName",
        .id = "id",
        .role_arn = "roleArn",
        .run_left_normalization = "runLeftNormalization",
        .status = "status",
        .update_time = "updateTime",
    };
};
