/// Specifies configuration information for a DataSync-managed secret, such as
/// an
/// authentication token, secret key, password, or Kerberos keytab that DataSync
/// uses
/// to access a specific storage location, with a customer-managed KMS key.
///
/// You can use either `CmkSecretConfig` or `CustomSecretConfig` to
/// provide credentials for a `CreateLocation` request. Do not provide both
/// parameters for the same request.
pub const CmkSecretConfig = struct {
    /// Specifies the ARN for the customer-managed KMS key that DataSync uses to
    /// encrypt the DataSync-managed secret stored for
    /// `SecretArn`. DataSync provides this key to Secrets Manager.
    kms_key_arn: ?[]const u8,

    /// Specifies the ARN for the DataSync-managed Secrets Manager secret that
    /// that is used to access a specific storage location. This property is
    /// generated by DataSync and is read-only. DataSync encrypts this secret with
    /// the KMS key that you specify for `KmsKeyArn`.
    secret_arn: ?[]const u8,

    pub const json_field_names = .{
        .kms_key_arn = "KmsKeyArn",
        .secret_arn = "SecretArn",
    };
};
