pub const InstanceType = enum {
    ml_m4_xlarge,
    ml_m4_2_xlarge,
    ml_m4_4_xlarge,
    ml_m4_10_xlarge,
    ml_m4_16_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_m5_large,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_12_xlarge,
    ml_m5_24_xlarge,
    ml_c4_xlarge,
    ml_c4_2_xlarge,
    ml_c4_4_xlarge,
    ml_c4_8_xlarge,
    ml_p2_xlarge,
    ml_p2_8_xlarge,
    ml_p2_16_xlarge,
    ml_p3_2_xlarge,
    ml_p3_8_xlarge,
    ml_p3_16_xlarge,
    ml_p3_dn_24_xlarge,
    ml_p4_d_24_xlarge,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_18_xlarge,
    ml_c5_n_xlarge,
    ml_c5_n_2_xlarge,
    ml_c5_n_4_xlarge,
    ml_c5_n_9_xlarge,
    ml_c5_n_18_xlarge,

    pub const json_field_names = .{
        .ml_m4_xlarge = "ML_M4_XLARGE",
        .ml_m4_2_xlarge = "ML_M4_2XLARGE",
        .ml_m4_4_xlarge = "ML_M4_4XLARGE",
        .ml_m4_10_xlarge = "ML_M4_10XLARGE",
        .ml_m4_16_xlarge = "ML_M4_16XLARGE",
        .ml_g4_dn_xlarge = "ML_G4DN_XLARGE",
        .ml_g4_dn_2_xlarge = "ML_G4DN_2XLARGE",
        .ml_g4_dn_4_xlarge = "ML_G4DN_4XLARGE",
        .ml_g4_dn_8_xlarge = "ML_G4DN_8XLARGE",
        .ml_g4_dn_12_xlarge = "ML_G4DN_12XLARGE",
        .ml_g4_dn_16_xlarge = "ML_G4DN_16XLARGE",
        .ml_m5_large = "ML_M5_LARGE",
        .ml_m5_xlarge = "ML_M5_XLARGE",
        .ml_m5_2_xlarge = "ML_M5_2XLARGE",
        .ml_m5_4_xlarge = "ML_M5_4XLARGE",
        .ml_m5_12_xlarge = "ML_M5_12XLARGE",
        .ml_m5_24_xlarge = "ML_M5_24XLARGE",
        .ml_c4_xlarge = "ML_C4_XLARGE",
        .ml_c4_2_xlarge = "ML_C4_2XLARGE",
        .ml_c4_4_xlarge = "ML_C4_4XLARGE",
        .ml_c4_8_xlarge = "ML_C4_8XLARGE",
        .ml_p2_xlarge = "ML_P2_XLARGE",
        .ml_p2_8_xlarge = "ML_P2_8XLARGE",
        .ml_p2_16_xlarge = "ML_P2_16XLARGE",
        .ml_p3_2_xlarge = "ML_P3_2XLARGE",
        .ml_p3_8_xlarge = "ML_P3_8XLARGE",
        .ml_p3_16_xlarge = "ML_P3_16XLARGE",
        .ml_p3_dn_24_xlarge = "ML_P3DN_24XLARGE",
        .ml_p4_d_24_xlarge = "ML_P4D_24XLARGE",
        .ml_c5_xlarge = "ML_C5_XLARGE",
        .ml_c5_2_xlarge = "ML_C5_2XLARGE",
        .ml_c5_4_xlarge = "ML_C5_4XLARGE",
        .ml_c5_9_xlarge = "ML_C5_9XLARGE",
        .ml_c5_18_xlarge = "ML_C5_18XLARGE",
        .ml_c5_n_xlarge = "ML_C5N_XLARGE",
        .ml_c5_n_2_xlarge = "ML_C5N_2XLARGE",
        .ml_c5_n_4_xlarge = "ML_C5N_4XLARGE",
        .ml_c5_n_9_xlarge = "ML_C5N_9XLARGE",
        .ml_c5_n_18_xlarge = "ML_C5N_18XLARGE",
    };
};
