const std = @import("std");

pub const InstanceType = enum {
    ml_t3_large,
    ml_t3_xlarge,
    ml_t3_2_xlarge,
    ml_m4_xlarge,
    ml_m4_2_xlarge,
    ml_m4_4_xlarge,
    ml_m4_10_xlarge,
    ml_m4_16_xlarge,
    ml_m5_large,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_12_xlarge,
    ml_m5_24_xlarge,
    ml_c4_xlarge,
    ml_c4_2_xlarge,
    ml_c4_4_xlarge,
    ml_c4_8_xlarge,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_18_xlarge,
    ml_c5_n_xlarge,
    ml_c5_n_2_xlarge,
    ml_c5_n_4_xlarge,
    ml_c5_n_9_xlarge,
    ml_c5_n_18_xlarge,
    ml_p2_xlarge,
    ml_p2_8_xlarge,
    ml_p2_16_xlarge,
    ml_p3_2_xlarge,
    ml_p3_8_xlarge,
    ml_p3_16_xlarge,
    ml_p3_dn_24_xlarge,
    ml_p4_d_24_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_12_xlarge,
    ml_g6_16_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,
    ml_g6_e_xlarge,
    ml_g6_e_2_xlarge,
    ml_g6_e_4_xlarge,
    ml_g6_e_8_xlarge,
    ml_g6_e_12_xlarge,
    ml_g6_e_16_xlarge,
    ml_g6_e_24_xlarge,
    ml_g6_e_48_xlarge,

    pub const json_field_names = .{
        .ml_t3_large = "ml.t3.large",
        .ml_t3_xlarge = "ml.t3.xlarge",
        .ml_t3_2_xlarge = "ml.t3.2xlarge",
        .ml_m4_xlarge = "ml.m4.xlarge",
        .ml_m4_2_xlarge = "ml.m4.2xlarge",
        .ml_m4_4_xlarge = "ml.m4.4xlarge",
        .ml_m4_10_xlarge = "ml.m4.10xlarge",
        .ml_m4_16_xlarge = "ml.m4.16xlarge",
        .ml_m5_large = "ml.m5.large",
        .ml_m5_xlarge = "ml.m5.xlarge",
        .ml_m5_2_xlarge = "ml.m5.2xlarge",
        .ml_m5_4_xlarge = "ml.m5.4xlarge",
        .ml_m5_12_xlarge = "ml.m5.12xlarge",
        .ml_m5_24_xlarge = "ml.m5.24xlarge",
        .ml_c4_xlarge = "ml.c4.xlarge",
        .ml_c4_2_xlarge = "ml.c4.2xlarge",
        .ml_c4_4_xlarge = "ml.c4.4xlarge",
        .ml_c4_8_xlarge = "ml.c4.8xlarge",
        .ml_c5_xlarge = "ml.c5.xlarge",
        .ml_c5_2_xlarge = "ml.c5.2xlarge",
        .ml_c5_4_xlarge = "ml.c5.4xlarge",
        .ml_c5_9_xlarge = "ml.c5.9xlarge",
        .ml_c5_18_xlarge = "ml.c5.18xlarge",
        .ml_c5_n_xlarge = "ml.c5n.xlarge",
        .ml_c5_n_2_xlarge = "ml.c5n.2xlarge",
        .ml_c5_n_4_xlarge = "ml.c5n.4xlarge",
        .ml_c5_n_9_xlarge = "ml.c5n.9xlarge",
        .ml_c5_n_18_xlarge = "ml.c5n.18xlarge",
        .ml_p2_xlarge = "ml.p2.xlarge",
        .ml_p2_8_xlarge = "ml.p2.8xlarge",
        .ml_p2_16_xlarge = "ml.p2.16xlarge",
        .ml_p3_2_xlarge = "ml.p3.2xlarge",
        .ml_p3_8_xlarge = "ml.p3.8xlarge",
        .ml_p3_16_xlarge = "ml.p3.16xlarge",
        .ml_p3_dn_24_xlarge = "ml.p3dn.24xlarge",
        .ml_p4_d_24_xlarge = "ml.p4d.24xlarge",
        .ml_g4_dn_xlarge = "ml.g4dn.xlarge",
        .ml_g4_dn_2_xlarge = "ml.g4dn.2xlarge",
        .ml_g4_dn_4_xlarge = "ml.g4dn.4xlarge",
        .ml_g4_dn_8_xlarge = "ml.g4dn.8xlarge",
        .ml_g4_dn_12_xlarge = "ml.g4dn.12xlarge",
        .ml_g4_dn_16_xlarge = "ml.g4dn.16xlarge",
        .ml_g6_xlarge = "ml.g6.xlarge",
        .ml_g6_2_xlarge = "ml.g6.2xlarge",
        .ml_g6_4_xlarge = "ml.g6.4xlarge",
        .ml_g6_8_xlarge = "ml.g6.8xlarge",
        .ml_g6_12_xlarge = "ml.g6.12xlarge",
        .ml_g6_16_xlarge = "ml.g6.16xlarge",
        .ml_g6_24_xlarge = "ml.g6.24xlarge",
        .ml_g6_48_xlarge = "ml.g6.48xlarge",
        .ml_g6_e_xlarge = "ml.g6e.xlarge",
        .ml_g6_e_2_xlarge = "ml.g6e.2xlarge",
        .ml_g6_e_4_xlarge = "ml.g6e.4xlarge",
        .ml_g6_e_8_xlarge = "ml.g6e.8xlarge",
        .ml_g6_e_12_xlarge = "ml.g6e.12xlarge",
        .ml_g6_e_16_xlarge = "ml.g6e.16xlarge",
        .ml_g6_e_24_xlarge = "ml.g6e.24xlarge",
        .ml_g6_e_48_xlarge = "ml.g6e.48xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .ml_t3_large => "ml.t3.large",
            .ml_t3_xlarge => "ml.t3.xlarge",
            .ml_t3_2_xlarge => "ml.t3.2xlarge",
            .ml_m4_xlarge => "ml.m4.xlarge",
            .ml_m4_2_xlarge => "ml.m4.2xlarge",
            .ml_m4_4_xlarge => "ml.m4.4xlarge",
            .ml_m4_10_xlarge => "ml.m4.10xlarge",
            .ml_m4_16_xlarge => "ml.m4.16xlarge",
            .ml_m5_large => "ml.m5.large",
            .ml_m5_xlarge => "ml.m5.xlarge",
            .ml_m5_2_xlarge => "ml.m5.2xlarge",
            .ml_m5_4_xlarge => "ml.m5.4xlarge",
            .ml_m5_12_xlarge => "ml.m5.12xlarge",
            .ml_m5_24_xlarge => "ml.m5.24xlarge",
            .ml_c4_xlarge => "ml.c4.xlarge",
            .ml_c4_2_xlarge => "ml.c4.2xlarge",
            .ml_c4_4_xlarge => "ml.c4.4xlarge",
            .ml_c4_8_xlarge => "ml.c4.8xlarge",
            .ml_c5_xlarge => "ml.c5.xlarge",
            .ml_c5_2_xlarge => "ml.c5.2xlarge",
            .ml_c5_4_xlarge => "ml.c5.4xlarge",
            .ml_c5_9_xlarge => "ml.c5.9xlarge",
            .ml_c5_18_xlarge => "ml.c5.18xlarge",
            .ml_c5_n_xlarge => "ml.c5n.xlarge",
            .ml_c5_n_2_xlarge => "ml.c5n.2xlarge",
            .ml_c5_n_4_xlarge => "ml.c5n.4xlarge",
            .ml_c5_n_9_xlarge => "ml.c5n.9xlarge",
            .ml_c5_n_18_xlarge => "ml.c5n.18xlarge",
            .ml_p2_xlarge => "ml.p2.xlarge",
            .ml_p2_8_xlarge => "ml.p2.8xlarge",
            .ml_p2_16_xlarge => "ml.p2.16xlarge",
            .ml_p3_2_xlarge => "ml.p3.2xlarge",
            .ml_p3_8_xlarge => "ml.p3.8xlarge",
            .ml_p3_16_xlarge => "ml.p3.16xlarge",
            .ml_p3_dn_24_xlarge => "ml.p3dn.24xlarge",
            .ml_p4_d_24_xlarge => "ml.p4d.24xlarge",
            .ml_g4_dn_xlarge => "ml.g4dn.xlarge",
            .ml_g4_dn_2_xlarge => "ml.g4dn.2xlarge",
            .ml_g4_dn_4_xlarge => "ml.g4dn.4xlarge",
            .ml_g4_dn_8_xlarge => "ml.g4dn.8xlarge",
            .ml_g4_dn_12_xlarge => "ml.g4dn.12xlarge",
            .ml_g4_dn_16_xlarge => "ml.g4dn.16xlarge",
            .ml_g6_xlarge => "ml.g6.xlarge",
            .ml_g6_2_xlarge => "ml.g6.2xlarge",
            .ml_g6_4_xlarge => "ml.g6.4xlarge",
            .ml_g6_8_xlarge => "ml.g6.8xlarge",
            .ml_g6_12_xlarge => "ml.g6.12xlarge",
            .ml_g6_16_xlarge => "ml.g6.16xlarge",
            .ml_g6_24_xlarge => "ml.g6.24xlarge",
            .ml_g6_48_xlarge => "ml.g6.48xlarge",
            .ml_g6_e_xlarge => "ml.g6e.xlarge",
            .ml_g6_e_2_xlarge => "ml.g6e.2xlarge",
            .ml_g6_e_4_xlarge => "ml.g6e.4xlarge",
            .ml_g6_e_8_xlarge => "ml.g6e.8xlarge",
            .ml_g6_e_12_xlarge => "ml.g6e.12xlarge",
            .ml_g6_e_16_xlarge => "ml.g6e.16xlarge",
            .ml_g6_e_24_xlarge => "ml.g6e.24xlarge",
            .ml_g6_e_48_xlarge => "ml.g6e.48xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
