pub const LimitName = enum {
    products_per_account,
    data_sets_per_account,
    data_sets_per_product,
    revisions_per_data_set,
    assets_per_revision,
    assets_per_import_job_from_amazon_s3,
    asset_per_export_job_from_amazon_s3,
    asset_size_in_gb,
    concurrent_in_progress_jobs_to_export_assets_to_amazon_s3,
    concurrent_in_progress_jobs_to_export_assets_to_a_signed_url,
    concurrent_in_progress_jobs_to_import_assets_from_amazon_s3,
    concurrent_in_progress_jobs_to_import_assets_from_a_signed_url,
    concurrent_in_progress_jobs_to_export_revisions_to_amazon_s3,
    event_actions_per_account,
    auto_export_event_actions_per_data_set,
    amazon_redshift_datashare_assets_per_import_job_from_redshift,
    concurrent_in_progress_jobs_to_import_assets_from_amazon_redshift_datashares,
    revisions_per_amazon_redshift_datashare_data_set,
    amazon_redshift_datashare_assets_per_revision,
    concurrent_in_progress_jobs_to_import_assets_from_an_api_gateway_api,
    amazon_api_gateway_api_assets_per_revision,
    revisions_per_amazon_api_gateway_api_data_set,
    concurrent_in_progress_jobs_to_import_assets_from_an_aws_lake_formation_tag_policy,
    aws_lake_formation_data_permission_assets_per_revision,
    revisions_per_aws_lake_formation_data_permission_data_set,
    revisions_per_amazon_s3_data_access_data_set,
    amazon_s3_data_access_assets_per_revision,
    concurrent_in_progress_jobs_to_create_amazon_s3_data_access_assets_from_s3_buckets,
    active_and_pending_data_grants,
    pending_data_grants_per_consumer,

    pub const json_field_names = .{
        .products_per_account = "Products_per_account",
        .data_sets_per_account = "Data_sets_per_account",
        .data_sets_per_product = "Data_sets_per_product",
        .revisions_per_data_set = "Revisions_per_data_set",
        .assets_per_revision = "Assets_per_revision",
        .assets_per_import_job_from_amazon_s3 = "Assets_per_import_job_from_Amazon_S3",
        .asset_per_export_job_from_amazon_s3 = "Asset_per_export_job_from_Amazon_S3",
        .asset_size_in_gb = "Asset_size_in_GB",
        .concurrent_in_progress_jobs_to_export_assets_to_amazon_s3 = "Concurrent_in_progress_jobs_to_export_assets_to_Amazon_S3",
        .concurrent_in_progress_jobs_to_export_assets_to_a_signed_url = "Concurrent_in_progress_jobs_to_export_assets_to_a_signed_URL",
        .concurrent_in_progress_jobs_to_import_assets_from_amazon_s3 = "Concurrent_in_progress_jobs_to_import_assets_from_Amazon_S3",
        .concurrent_in_progress_jobs_to_import_assets_from_a_signed_url = "Concurrent_in_progress_jobs_to_import_assets_from_a_signed_URL",
        .concurrent_in_progress_jobs_to_export_revisions_to_amazon_s3 = "Concurrent_in_progress_jobs_to_export_revisions_to_Amazon_S3",
        .event_actions_per_account = "Event_actions_per_account",
        .auto_export_event_actions_per_data_set = "Auto_export_event_actions_per_data_set",
        .amazon_redshift_datashare_assets_per_import_job_from_redshift = "Amazon_Redshift_datashare_assets_per_import_job_from_Redshift",
        .concurrent_in_progress_jobs_to_import_assets_from_amazon_redshift_datashares = "Concurrent_in_progress_jobs_to_import_assets_from_Amazon_Redshift_datashares",
        .revisions_per_amazon_redshift_datashare_data_set = "Revisions_per_Amazon_Redshift_datashare_data_set",
        .amazon_redshift_datashare_assets_per_revision = "Amazon_Redshift_datashare_assets_per_revision",
        .concurrent_in_progress_jobs_to_import_assets_from_an_api_gateway_api = "Concurrent_in_progress_jobs_to_import_assets_from_an_API_Gateway_API",
        .amazon_api_gateway_api_assets_per_revision = "Amazon_API_Gateway_API_assets_per_revision",
        .revisions_per_amazon_api_gateway_api_data_set = "Revisions_per_Amazon_API_Gateway_API_data_set",
        .concurrent_in_progress_jobs_to_import_assets_from_an_aws_lake_formation_tag_policy = "Concurrent_in_progress_jobs_to_import_assets_from_an_AWS_Lake_Formation_tag_policy",
        .aws_lake_formation_data_permission_assets_per_revision = "AWS_Lake_Formation_data_permission_assets_per_revision",
        .revisions_per_aws_lake_formation_data_permission_data_set = "Revisions_per_AWS_Lake_Formation_data_permission_data_set",
        .revisions_per_amazon_s3_data_access_data_set = "Revisions_per_Amazon_S3_data_access_data_set",
        .amazon_s3_data_access_assets_per_revision = "Amazon_S3_data_access_assets_per_revision",
        .concurrent_in_progress_jobs_to_create_amazon_s3_data_access_assets_from_s3_buckets = "Concurrent_in_progress_jobs_to_create_Amazon_S3_data_access_assets_from_S3_buckets",
        .active_and_pending_data_grants = "Active_and_pending_data_grants",
        .pending_data_grants_per_consumer = "Pending_data_grants_per_consumer",
    };
};
