pub const ViolationReason = enum {
    web_acl_missing_rule_group,
    resource_missing_web_acl,
    resource_incorrect_web_acl,
    resource_missing_shield_protection,
    resource_missing_webacl_or_shield_protection,
    resource_missing_security_group,
    resource_violates_audit_security_group,
    security_group_unused,
    security_group_redundant,
    fms_created_security_group_edited,
    missing_firewall,
    missing_firewall_subnet_in_az,
    missing_expected_route_table,
    network_firewall_policy_modified,
    firewall_subnet_is_out_of_scope,
    internet_gateway_missing_expected_route,
    firewall_subnet_missing_expected_route,
    unexpected_firewall_routes,
    unexpected_target_gateway_routes,
    traffic_inspection_crosses_az_boundary,
    invalid_route_configuration,
    missing_target_gateway,
    internet_traffic_not_inspected,
    black_hole_route_detected,
    black_hole_route_detected_in_firewall_subnet,
    resource_missing_dns_firewall,
    route_has_out_of_scope_endpoint,
    firewall_subnet_missing_vpc_endpoint,
    invalid_network_acl_entry,
    web_acl_configuration_or_scope_of_use,

    pub const json_field_names = .{
        .web_acl_missing_rule_group = "WebAclMissingRuleGroup",
        .resource_missing_web_acl = "ResourceMissingWebAcl",
        .resource_incorrect_web_acl = "ResourceIncorrectWebAcl",
        .resource_missing_shield_protection = "ResourceMissingShieldProtection",
        .resource_missing_webacl_or_shield_protection = "ResourceMissingWebaclOrShieldProtection",
        .resource_missing_security_group = "ResourceMissingSecurityGroup",
        .resource_violates_audit_security_group = "ResourceViolatesAuditSecurityGroup",
        .security_group_unused = "SecurityGroupUnused",
        .security_group_redundant = "SecurityGroupRedundant",
        .fms_created_security_group_edited = "FMSCreatedSecurityGroupEdited",
        .missing_firewall = "MissingFirewall",
        .missing_firewall_subnet_in_az = "MissingFirewallSubnetInAZ",
        .missing_expected_route_table = "MissingExpectedRouteTable",
        .network_firewall_policy_modified = "NetworkFirewallPolicyModified",
        .firewall_subnet_is_out_of_scope = "FirewallSubnetIsOutOfScope",
        .internet_gateway_missing_expected_route = "InternetGatewayMissingExpectedRoute",
        .firewall_subnet_missing_expected_route = "FirewallSubnetMissingExpectedRoute",
        .unexpected_firewall_routes = "UnexpectedFirewallRoutes",
        .unexpected_target_gateway_routes = "UnexpectedTargetGatewayRoutes",
        .traffic_inspection_crosses_az_boundary = "TrafficInspectionCrossesAZBoundary",
        .invalid_route_configuration = "InvalidRouteConfiguration",
        .missing_target_gateway = "MissingTargetGateway",
        .internet_traffic_not_inspected = "InternetTrafficNotInspected",
        .black_hole_route_detected = "BlackHoleRouteDetected",
        .black_hole_route_detected_in_firewall_subnet = "BlackHoleRouteDetectedInFirewallSubnet",
        .resource_missing_dns_firewall = "ResourceMissingDnsFirewall",
        .route_has_out_of_scope_endpoint = "RouteHasOutOfScopeEndpoint",
        .firewall_subnet_missing_vpc_endpoint = "FirewallSubnetMissingVPCEndpoint",
        .invalid_network_acl_entry = "InvalidNetworkAclEntry",
        .web_acl_configuration_or_scope_of_use = "WebACLConfigurationOrScopeOfUse",
    };
};
