const ErrorObject = @import("error_object.zig").ErrorObject;

/// Contains details about a callback operation in a durable execution,
/// including the callback token and timeout configuration.
pub const CallbackDetails = struct {
    /// The callback ID. Callback IDs are generated by the `DurableContext` when a
    /// durable function calls `ctx.waitForCallback`.
    callback_id: ?[]const u8 = null,

    /// An error object that contains details about the failure.
    @"error": ?ErrorObject = null,

    /// The response payload from the callback operation as a string.
    result: ?[]const u8 = null,

    pub const json_field_names = .{
        .callback_id = "CallbackId",
        .@"error" = "Error",
        .result = "Result",
    };
};
