/// Contains details about a callback operation that has started, including
/// timing information and callback metadata.
pub const CallbackStartedDetails = struct {
    /// The callback ID. Callback IDs are generated by the `DurableContext` when a
    /// durable function calls `ctx.waitForCallback`.
    callback_id: []const u8,

    /// The heartbeat timeout value, in seconds.
    heartbeat_timeout: ?i32 = null,

    /// The timeout value, in seconds.
    timeout: ?i32 = null,

    pub const json_field_names = .{
        .callback_id = "CallbackId",
        .heartbeat_timeout = "HeartbeatTimeout",
        .timeout = "Timeout",
    };
};
