pub const EventType = enum {
    execution_started,
    execution_succeeded,
    execution_failed,
    execution_timed_out,
    execution_stopped,
    context_started,
    context_succeeded,
    context_failed,
    wait_started,
    wait_succeeded,
    wait_cancelled,
    step_started,
    step_succeeded,
    step_failed,
    chained_invoke_started,
    chained_invoke_succeeded,
    chained_invoke_failed,
    chained_invoke_timed_out,
    chained_invoke_stopped,
    callback_started,
    callback_succeeded,
    callback_failed,
    callback_timed_out,
    invocation_completed,

    pub const json_field_names = .{
        .execution_started = "ExecutionStarted",
        .execution_succeeded = "ExecutionSucceeded",
        .execution_failed = "ExecutionFailed",
        .execution_timed_out = "ExecutionTimedOut",
        .execution_stopped = "ExecutionStopped",
        .context_started = "ContextStarted",
        .context_succeeded = "ContextSucceeded",
        .context_failed = "ContextFailed",
        .wait_started = "WaitStarted",
        .wait_succeeded = "WaitSucceeded",
        .wait_cancelled = "WaitCancelled",
        .step_started = "StepStarted",
        .step_succeeded = "StepSucceeded",
        .step_failed = "StepFailed",
        .chained_invoke_started = "ChainedInvokeStarted",
        .chained_invoke_succeeded = "ChainedInvokeSucceeded",
        .chained_invoke_failed = "ChainedInvokeFailed",
        .chained_invoke_timed_out = "ChainedInvokeTimedOut",
        .chained_invoke_stopped = "ChainedInvokeStopped",
        .callback_started = "CallbackStarted",
        .callback_succeeded = "CallbackSucceeded",
        .callback_failed = "CallbackFailed",
        .callback_timed_out = "CallbackTimedOut",
        .invocation_completed = "InvocationCompleted",
    };
};
