const std = @import("std");

pub const Runtime = enum {
    nodejs,
    nodejs_43,
    nodejs_610,
    nodejs_810,
    nodejs_10_x,
    nodejs_12_x,
    nodejs_14_x,
    nodejs_16_x,
    java_8,
    java_8_al_2,
    java_11,
    python_27,
    python_36,
    python_37,
    python_38,
    python_39,
    dotnetcore_10,
    dotnetcore_20,
    dotnetcore_21,
    dotnetcore_31,
    dotnet_6,
    dotnet_8,
    nodejs_43_edge,
    go_1_x,
    ruby_25,
    ruby_27,
    provided,
    providedal_2,
    nodejs_18_x,
    python_310,
    java_17,
    ruby_32,
    ruby_33,
    ruby_34,
    python_311,
    nodejs_20_x,
    providedal_2023,
    python_312,
    java_21,
    python_313,
    nodejs_22_x,
    nodejs_24_x,
    python_314,
    java_25,
    dotnet_10,

    pub const json_field_names = .{
        .nodejs = "nodejs",
        .nodejs_43 = "nodejs4.3",
        .nodejs_610 = "nodejs6.10",
        .nodejs_810 = "nodejs8.10",
        .nodejs_10_x = "nodejs10.x",
        .nodejs_12_x = "nodejs12.x",
        .nodejs_14_x = "nodejs14.x",
        .nodejs_16_x = "nodejs16.x",
        .java_8 = "java8",
        .java_8_al_2 = "java8.al2",
        .java_11 = "java11",
        .python_27 = "python2.7",
        .python_36 = "python3.6",
        .python_37 = "python3.7",
        .python_38 = "python3.8",
        .python_39 = "python3.9",
        .dotnetcore_10 = "dotnetcore1.0",
        .dotnetcore_20 = "dotnetcore2.0",
        .dotnetcore_21 = "dotnetcore2.1",
        .dotnetcore_31 = "dotnetcore3.1",
        .dotnet_6 = "dotnet6",
        .dotnet_8 = "dotnet8",
        .nodejs_43_edge = "nodejs4.3-edge",
        .go_1_x = "go1.x",
        .ruby_25 = "ruby2.5",
        .ruby_27 = "ruby2.7",
        .provided = "provided",
        .providedal_2 = "provided.al2",
        .nodejs_18_x = "nodejs18.x",
        .python_310 = "python3.10",
        .java_17 = "java17",
        .ruby_32 = "ruby3.2",
        .ruby_33 = "ruby3.3",
        .ruby_34 = "ruby3.4",
        .python_311 = "python3.11",
        .nodejs_20_x = "nodejs20.x",
        .providedal_2023 = "provided.al2023",
        .python_312 = "python3.12",
        .java_21 = "java21",
        .python_313 = "python3.13",
        .nodejs_22_x = "nodejs22.x",
        .nodejs_24_x = "nodejs24.x",
        .python_314 = "python3.14",
        .java_25 = "java25",
        .dotnet_10 = "dotnet10",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .nodejs => "nodejs",
            .nodejs_43 => "nodejs4.3",
            .nodejs_610 => "nodejs6.10",
            .nodejs_810 => "nodejs8.10",
            .nodejs_10_x => "nodejs10.x",
            .nodejs_12_x => "nodejs12.x",
            .nodejs_14_x => "nodejs14.x",
            .nodejs_16_x => "nodejs16.x",
            .java_8 => "java8",
            .java_8_al_2 => "java8.al2",
            .java_11 => "java11",
            .python_27 => "python2.7",
            .python_36 => "python3.6",
            .python_37 => "python3.7",
            .python_38 => "python3.8",
            .python_39 => "python3.9",
            .dotnetcore_10 => "dotnetcore1.0",
            .dotnetcore_20 => "dotnetcore2.0",
            .dotnetcore_21 => "dotnetcore2.1",
            .dotnetcore_31 => "dotnetcore3.1",
            .dotnet_6 => "dotnet6",
            .dotnet_8 => "dotnet8",
            .nodejs_43_edge => "nodejs4.3-edge",
            .go_1_x => "go1.x",
            .ruby_25 => "ruby2.5",
            .ruby_27 => "ruby2.7",
            .provided => "provided",
            .providedal_2 => "provided.al2",
            .nodejs_18_x => "nodejs18.x",
            .python_310 => "python3.10",
            .java_17 => "java17",
            .ruby_32 => "ruby3.2",
            .ruby_33 => "ruby3.3",
            .ruby_34 => "ruby3.4",
            .python_311 => "python3.11",
            .nodejs_20_x => "nodejs20.x",
            .providedal_2023 => "provided.al2023",
            .python_312 => "python3.12",
            .java_21 => "java21",
            .python_313 => "python3.13",
            .nodejs_22_x => "nodejs22.x",
            .nodejs_24_x => "nodejs24.x",
            .python_314 => "python3.14",
            .java_25 => "java25",
            .dotnet_10 => "dotnet10",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
