pub const StateReasonCode = enum {
    idle,
    creating,
    restoring,
    eni_limit_exceeded,
    insufficient_role_permissions,
    invalid_configuration,
    internal_error,
    subnet_out_of_ip_addresses,
    invalid_subnet,
    invalid_security_group,
    image_deleted,
    image_access_denied,
    invalid_image,
    kms_key_access_denied,
    kms_key_not_found,
    invalid_state_kms_key,
    disabled_kms_key,
    efsio_error,
    efs_mount_connectivity_error,
    efs_mount_failure,
    efs_mount_timeout,
    invalid_runtime,
    invalid_zip_file_exception,
    function_error,
    draining_durable_executions,
    vcpu_limit_exceeded,
    capacity_provider_scaling_limit_exceeded,
    insufficient_capacity,
    ec2_request_limit_exceeded,
    function_error_init_timeout,
    function_error_runtime_init_error,
    function_error_extension_init_error,
    function_error_invalid_entry_point,
    function_error_invalid_working_directory,
    function_error_permission_denied,
    function_error_too_many_extensions,
    function_error_init_resource_exhausted,
    disallowed_by_vpc_encryption_control,

    pub const json_field_names = .{
        .idle = "Idle",
        .creating = "Creating",
        .restoring = "Restoring",
        .eni_limit_exceeded = "EniLimitExceeded",
        .insufficient_role_permissions = "InsufficientRolePermissions",
        .invalid_configuration = "InvalidConfiguration",
        .internal_error = "InternalError",
        .subnet_out_of_ip_addresses = "SubnetOutOfIPAddresses",
        .invalid_subnet = "InvalidSubnet",
        .invalid_security_group = "InvalidSecurityGroup",
        .image_deleted = "ImageDeleted",
        .image_access_denied = "ImageAccessDenied",
        .invalid_image = "InvalidImage",
        .kms_key_access_denied = "KMSKeyAccessDenied",
        .kms_key_not_found = "KMSKeyNotFound",
        .invalid_state_kms_key = "InvalidStateKMSKey",
        .disabled_kms_key = "DisabledKMSKey",
        .efsio_error = "EFSIOError",
        .efs_mount_connectivity_error = "EFSMountConnectivityError",
        .efs_mount_failure = "EFSMountFailure",
        .efs_mount_timeout = "EFSMountTimeout",
        .invalid_runtime = "InvalidRuntime",
        .invalid_zip_file_exception = "InvalidZipFileException",
        .function_error = "FunctionError",
        .draining_durable_executions = "DrainingDurableExecutions",
        .vcpu_limit_exceeded = "VcpuLimitExceeded",
        .capacity_provider_scaling_limit_exceeded = "CapacityProviderScalingLimitExceeded",
        .insufficient_capacity = "InsufficientCapacity",
        .ec2_request_limit_exceeded = "EC2RequestLimitExceeded",
        .function_error_init_timeout = "FunctionErrorInitTimeout",
        .function_error_runtime_init_error = "FunctionErrorRuntimeInitError",
        .function_error_extension_init_error = "FunctionErrorExtensionInitError",
        .function_error_invalid_entry_point = "FunctionErrorInvalidEntryPoint",
        .function_error_invalid_working_directory = "FunctionErrorInvalidWorkingDirectory",
        .function_error_permission_denied = "FunctionErrorPermissionDenied",
        .function_error_too_many_extensions = "FunctionErrorTooManyExtensions",
        .function_error_init_resource_exhausted = "FunctionErrorInitResourceExhausted",
        .disallowed_by_vpc_encryption_control = "DisallowedByVpcEncryptionControl",
    };
};
