const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const ServiceError = @import("errors.zig").ServiceError;
const AutoRollbackConfiguration = @import("auto_rollback_configuration.zig").AutoRollbackConfiguration;
const FileExistsBehavior = @import("file_exists_behavior.zig").FileExistsBehavior;
const AlarmConfiguration = @import("alarm_configuration.zig").AlarmConfiguration;
const RevisionLocation = @import("revision_location.zig").RevisionLocation;
const TargetInstances = @import("target_instances.zig").TargetInstances;

pub const CreateDeploymentInput = struct {
    /// The name of an CodeDeploy application associated with the user or Amazon Web
    /// Services account.
    application_name: []const u8,

    /// Configuration information for an automatic rollback that is added when a
    /// deployment is
    /// created.
    auto_rollback_configuration: ?AutoRollbackConfiguration = null,

    /// The name of a deployment configuration associated with the user or Amazon
    /// Web Services account.
    ///
    /// If not specified, the value configured in the deployment group is used as
    /// the default.
    /// If the deployment group does not have a deployment configuration associated
    /// with it,
    /// `CodeDeployDefault`.`OneAtATime` is used by default.
    deployment_config_name: ?[]const u8 = null,

    /// The name of the deployment group.
    deployment_group_name: ?[]const u8 = null,

    /// A comment about the deployment.
    description: ?[]const u8 = null,

    /// Information about how CodeDeploy handles files that already exist in a
    /// deployment target location but weren't part of the previous successful
    /// deployment.
    ///
    /// The `fileExistsBehavior` parameter takes any of the following
    /// values:
    ///
    /// * DISALLOW: The deployment fails. This is also the default behavior if no
    ///   option
    /// is specified.
    ///
    /// * OVERWRITE: The version of the file from the application revision currently
    /// being deployed replaces the version already on the instance.
    ///
    /// * RETAIN: The version of the file already on the instance is kept and used
    ///   as
    /// part of the new deployment.
    file_exists_behavior: ?FileExistsBehavior = null,

    /// If true, then if an `ApplicationStop`, `BeforeBlockTraffic`, or
    /// `AfterBlockTraffic` deployment lifecycle event to an instance fails, then
    /// the deployment continues to the next deployment lifecycle event. For
    /// example, if
    /// `ApplicationStop` fails, the deployment continues with
    /// `DownloadBundle`. If `BeforeBlockTraffic` fails, the
    /// deployment continues with `BlockTraffic`. If `AfterBlockTraffic`
    /// fails, the deployment continues with `ApplicationStop`.
    ///
    /// If false or not specified, then if a lifecycle event fails during a
    /// deployment to an
    /// instance, that deployment fails. If deployment to that instance is part of
    /// an overall
    /// deployment and the number of healthy hosts is not less than the minimum
    /// number of
    /// healthy hosts, then a deployment to the next instance is attempted.
    ///
    /// During a deployment, the CodeDeploy agent runs the scripts specified for
    /// `ApplicationStop`, `BeforeBlockTraffic`, and
    /// `AfterBlockTraffic` in the AppSpec file from the previous successful
    /// deployment. (All other scripts are run from the AppSpec file in the current
    /// deployment.)
    /// If one of these scripts contains an error and does not run successfully, the
    /// deployment
    /// can fail.
    ///
    /// If the cause of the failure is a script from the last successful deployment
    /// that will
    /// never run successfully, create a new deployment and use
    /// `ignoreApplicationStopFailures` to specify that the
    /// `ApplicationStop`, `BeforeBlockTraffic`, and
    /// `AfterBlockTraffic` failures should be ignored.
    ignore_application_stop_failures: ?bool = null,

    /// Allows you to specify information about alarms associated with a deployment.
    /// The alarm
    /// configuration that you specify here will override the alarm configuration at
    /// the
    /// deployment group level. Consider overriding the alarm configuration if you
    /// have set up
    /// alarms at the deployment group level that are causing deployment failures.
    /// In this case,
    /// you would call `CreateDeployment` to create a new deployment that uses a
    /// previous application revision that is known to work, and set its alarm
    /// configuration to
    /// turn off alarm polling. Turning off alarm polling ensures that the new
    /// deployment
    /// proceeds without being blocked by the alarm that was generated by the
    /// previous, failed,
    /// deployment.
    ///
    /// If you specify an `overrideAlarmConfiguration`, you need the
    /// `UpdateDeploymentGroup`
    /// IAM permission when calling `CreateDeployment`.
    override_alarm_configuration: ?AlarmConfiguration = null,

    /// The type and location of the revision to deploy.
    revision: ?RevisionLocation = null,

    /// Information about the instances that belong to the replacement environment
    /// in a
    /// blue/green deployment.
    target_instances: ?TargetInstances = null,

    /// Indicates whether to deploy to all instances or only to instances that are
    /// not
    /// running the latest application revision.
    update_outdated_instances_only: ?bool = null,

    pub const json_field_names = .{
        .application_name = "applicationName",
        .auto_rollback_configuration = "autoRollbackConfiguration",
        .deployment_config_name = "deploymentConfigName",
        .deployment_group_name = "deploymentGroupName",
        .description = "description",
        .file_exists_behavior = "fileExistsBehavior",
        .ignore_application_stop_failures = "ignoreApplicationStopFailures",
        .override_alarm_configuration = "overrideAlarmConfiguration",
        .revision = "revision",
        .target_instances = "targetInstances",
        .update_outdated_instances_only = "updateOutdatedInstancesOnly",
    };
};

pub const CreateDeploymentOutput = struct {
    /// The unique ID of a deployment.
    deployment_id: ?[]const u8 = null,

    pub const json_field_names = .{
        .deployment_id = "deploymentId",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateDeploymentInput, options: CallOptions) !CreateDeploymentOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "codedeploy");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateDeploymentInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("codedeploy", "CodeDeploy", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(host);
    request.method = .POST;
    request.path = "/";
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "CodeDeploy_20141006.CreateDeployment");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateDeploymentOutput {
    _ = status;
    _ = headers;
    if (body.len == 0) return .{};
    return aws.json.parseJsonObject(CreateDeploymentOutput, body, allocator);
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AlarmsLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .alarms_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ApplicationAlreadyExistsException")) {
        return .{ .arena = arena, .kind = .{ .application_already_exists_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ApplicationDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .application_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ApplicationLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .application_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ApplicationNameRequiredException")) {
        return .{ .arena = arena, .kind = .{ .application_name_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ArnNotSupportedException")) {
        return .{ .arena = arena, .kind = .{ .arn_not_supported_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "BatchLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .batch_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "BucketNameFilterRequiredException")) {
        return .{ .arena = arena, .kind = .{ .bucket_name_filter_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentAlreadyCompletedException")) {
        return .{ .arena = arena, .kind = .{ .deployment_already_completed_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentConfigAlreadyExistsException")) {
        return .{ .arena = arena, .kind = .{ .deployment_config_already_exists_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentConfigDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .deployment_config_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentConfigInUseException")) {
        return .{ .arena = arena, .kind = .{ .deployment_config_in_use_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentConfigLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .deployment_config_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentConfigNameRequiredException")) {
        return .{ .arena = arena, .kind = .{ .deployment_config_name_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .deployment_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentGroupAlreadyExistsException")) {
        return .{ .arena = arena, .kind = .{ .deployment_group_already_exists_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentGroupDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .deployment_group_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentGroupLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .deployment_group_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentGroupNameRequiredException")) {
        return .{ .arena = arena, .kind = .{ .deployment_group_name_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentIdRequiredException")) {
        return .{ .arena = arena, .kind = .{ .deployment_id_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentIsNotInReadyStateException")) {
        return .{ .arena = arena, .kind = .{ .deployment_is_not_in_ready_state_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .deployment_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentNotStartedException")) {
        return .{ .arena = arena, .kind = .{ .deployment_not_started_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentTargetDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .deployment_target_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentTargetIdRequiredException")) {
        return .{ .arena = arena, .kind = .{ .deployment_target_id_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DeploymentTargetListSizeExceededException")) {
        return .{ .arena = arena, .kind = .{ .deployment_target_list_size_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "DescriptionTooLongException")) {
        return .{ .arena = arena, .kind = .{ .description_too_long_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ECSServiceMappingLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .ecs_service_mapping_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "GitHubAccountTokenDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .git_hub_account_token_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "GitHubAccountTokenNameRequiredException")) {
        return .{ .arena = arena, .kind = .{ .git_hub_account_token_name_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "IamArnRequiredException")) {
        return .{ .arena = arena, .kind = .{ .iam_arn_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "IamSessionArnAlreadyRegisteredException")) {
        return .{ .arena = arena, .kind = .{ .iam_session_arn_already_registered_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "IamUserArnAlreadyRegisteredException")) {
        return .{ .arena = arena, .kind = .{ .iam_user_arn_already_registered_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "IamUserArnRequiredException")) {
        return .{ .arena = arena, .kind = .{ .iam_user_arn_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InstanceDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .instance_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InstanceIdRequiredException")) {
        return .{ .arena = arena, .kind = .{ .instance_id_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InstanceLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .instance_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InstanceNameAlreadyRegisteredException")) {
        return .{ .arena = arena, .kind = .{ .instance_name_already_registered_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InstanceNameRequiredException")) {
        return .{ .arena = arena, .kind = .{ .instance_name_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InstanceNotRegisteredException")) {
        return .{ .arena = arena, .kind = .{ .instance_not_registered_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidAlarmConfigException")) {
        return .{ .arena = arena, .kind = .{ .invalid_alarm_config_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidApplicationNameException")) {
        return .{ .arena = arena, .kind = .{ .invalid_application_name_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidArnException")) {
        return .{ .arena = arena, .kind = .{ .invalid_arn_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidAutoRollbackConfigException")) {
        return .{ .arena = arena, .kind = .{ .invalid_auto_rollback_config_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidAutoScalingGroupException")) {
        return .{ .arena = arena, .kind = .{ .invalid_auto_scaling_group_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidBlueGreenDeploymentConfigurationException")) {
        return .{ .arena = arena, .kind = .{ .invalid_blue_green_deployment_configuration_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidBucketNameFilterException")) {
        return .{ .arena = arena, .kind = .{ .invalid_bucket_name_filter_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidComputePlatformException")) {
        return .{ .arena = arena, .kind = .{ .invalid_compute_platform_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeployedStateFilterException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployed_state_filter_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentConfigNameException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_config_name_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentGroupNameException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_group_name_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentIdException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_id_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentInstanceTypeException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_instance_type_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentStatusException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_status_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentStyleException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_style_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentTargetIdException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_target_id_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidDeploymentWaitTypeException")) {
        return .{ .arena = arena, .kind = .{ .invalid_deployment_wait_type_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidEC2TagCombinationException")) {
        return .{ .arena = arena, .kind = .{ .invalid_ec2_tag_combination_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidEC2TagException")) {
        return .{ .arena = arena, .kind = .{ .invalid_ec2_tag_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidECSServiceException")) {
        return .{ .arena = arena, .kind = .{ .invalid_ecs_service_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidExternalIdException")) {
        return .{ .arena = arena, .kind = .{ .invalid_external_id_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidFileExistsBehaviorException")) {
        return .{ .arena = arena, .kind = .{ .invalid_file_exists_behavior_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidGitHubAccountTokenException")) {
        return .{ .arena = arena, .kind = .{ .invalid_git_hub_account_token_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidGitHubAccountTokenNameException")) {
        return .{ .arena = arena, .kind = .{ .invalid_git_hub_account_token_name_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidIamSessionArnException")) {
        return .{ .arena = arena, .kind = .{ .invalid_iam_session_arn_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidIamUserArnException")) {
        return .{ .arena = arena, .kind = .{ .invalid_iam_user_arn_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidIgnoreApplicationStopFailuresValueException")) {
        return .{ .arena = arena, .kind = .{ .invalid_ignore_application_stop_failures_value_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidInputException")) {
        return .{ .arena = arena, .kind = .{ .invalid_input_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidInstanceNameException")) {
        return .{ .arena = arena, .kind = .{ .invalid_instance_name_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidInstanceStatusException")) {
        return .{ .arena = arena, .kind = .{ .invalid_instance_status_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidInstanceTypeException")) {
        return .{ .arena = arena, .kind = .{ .invalid_instance_type_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidKeyPrefixFilterException")) {
        return .{ .arena = arena, .kind = .{ .invalid_key_prefix_filter_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidLifecycleEventHookExecutionIdException")) {
        return .{ .arena = arena, .kind = .{ .invalid_lifecycle_event_hook_execution_id_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidLifecycleEventHookExecutionStatusException")) {
        return .{ .arena = arena, .kind = .{ .invalid_lifecycle_event_hook_execution_status_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidLoadBalancerInfoException")) {
        return .{ .arena = arena, .kind = .{ .invalid_load_balancer_info_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidMinimumHealthyHostValueException")) {
        return .{ .arena = arena, .kind = .{ .invalid_minimum_healthy_host_value_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidNextTokenException")) {
        return .{ .arena = arena, .kind = .{ .invalid_next_token_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidOnPremisesTagCombinationException")) {
        return .{ .arena = arena, .kind = .{ .invalid_on_premises_tag_combination_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidOperationException")) {
        return .{ .arena = arena, .kind = .{ .invalid_operation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidRegistrationStatusException")) {
        return .{ .arena = arena, .kind = .{ .invalid_registration_status_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidRevisionException")) {
        return .{ .arena = arena, .kind = .{ .invalid_revision_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidRoleException")) {
        return .{ .arena = arena, .kind = .{ .invalid_role_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidSortByException")) {
        return .{ .arena = arena, .kind = .{ .invalid_sort_by_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidSortOrderException")) {
        return .{ .arena = arena, .kind = .{ .invalid_sort_order_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTagException")) {
        return .{ .arena = arena, .kind = .{ .invalid_tag_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTagFilterException")) {
        return .{ .arena = arena, .kind = .{ .invalid_tag_filter_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTagsToAddException")) {
        return .{ .arena = arena, .kind = .{ .invalid_tags_to_add_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTargetFilterNameException")) {
        return .{ .arena = arena, .kind = .{ .invalid_target_filter_name_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTargetGroupPairException")) {
        return .{ .arena = arena, .kind = .{ .invalid_target_group_pair_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTargetInstancesException")) {
        return .{ .arena = arena, .kind = .{ .invalid_target_instances_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTimeRangeException")) {
        return .{ .arena = arena, .kind = .{ .invalid_time_range_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTrafficRoutingConfigurationException")) {
        return .{ .arena = arena, .kind = .{ .invalid_traffic_routing_configuration_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidTriggerConfigException")) {
        return .{ .arena = arena, .kind = .{ .invalid_trigger_config_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidUpdateOutdatedInstancesOnlyValueException")) {
        return .{ .arena = arena, .kind = .{ .invalid_update_outdated_instances_only_value_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InvalidZonalDeploymentConfigurationException")) {
        return .{ .arena = arena, .kind = .{ .invalid_zonal_deployment_configuration_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "LifecycleEventAlreadyCompletedException")) {
        return .{ .arena = arena, .kind = .{ .lifecycle_event_already_completed_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "LifecycleHookLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .lifecycle_hook_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "MultipleIamArnsProvidedException")) {
        return .{ .arena = arena, .kind = .{ .multiple_iam_arns_provided_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "OperationNotSupportedException")) {
        return .{ .arena = arena, .kind = .{ .operation_not_supported_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceArnRequiredException")) {
        return .{ .arena = arena, .kind = .{ .resource_arn_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceValidationException")) {
        return .{ .arena = arena, .kind = .{ .resource_validation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "RevisionDoesNotExistException")) {
        return .{ .arena = arena, .kind = .{ .revision_does_not_exist_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "RevisionRequiredException")) {
        return .{ .arena = arena, .kind = .{ .revision_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "RoleRequiredException")) {
        return .{ .arena = arena, .kind = .{ .role_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TagLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .tag_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TagRequiredException")) {
        return .{ .arena = arena, .kind = .{ .tag_required_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TagSetListLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .tag_set_list_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ThrottlingException")) {
        return .{ .arena = arena, .kind = .{ .throttling_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TriggerTargetsLimitExceededException")) {
        return .{ .arena = arena, .kind = .{ .trigger_targets_limit_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "UnsupportedActionForDeploymentTypeException")) {
        return .{ .arena = arena, .kind = .{ .unsupported_action_for_deployment_type_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
