pub const ErrorCode = enum {
    agent_issue,
    alarm_active,
    application_missing,
    autoscaling_validation_error,
    auto_scaling_configuration,
    auto_scaling_iam_role_permissions,
    codedeploy_resource_cannot_be_found,
    customer_application_unhealthy,
    deployment_group_missing,
    ecs_update_error,
    elastic_load_balancing_invalid,
    elb_invalid_instance,
    health_constraints,
    health_constraints_invalid,
    hook_execution_failure,
    iam_role_missing,
    iam_role_permissions,
    internal_error,
    invalid_ecs_service,
    invalid_lambda_configuration,
    invalid_lambda_function,
    invalid_revision,
    manual_stop,
    missing_blue_green_deployment_configuration,
    missing_elb_information,
    missing_github_token,
    no_ec2_subscription,
    no_instances,
    over_max_instances,
    resource_limit_exceeded,
    revision_missing,
    throttled,
    timeout,
    cloudformation_stack_failure,

    pub const json_field_names = .{
        .agent_issue = "AGENT_ISSUE",
        .alarm_active = "ALARM_ACTIVE",
        .application_missing = "APPLICATION_MISSING",
        .autoscaling_validation_error = "AUTOSCALING_VALIDATION_ERROR",
        .auto_scaling_configuration = "AUTO_SCALING_CONFIGURATION",
        .auto_scaling_iam_role_permissions = "AUTO_SCALING_IAM_ROLE_PERMISSIONS",
        .codedeploy_resource_cannot_be_found = "CODEDEPLOY_RESOURCE_CANNOT_BE_FOUND",
        .customer_application_unhealthy = "CUSTOMER_APPLICATION_UNHEALTHY",
        .deployment_group_missing = "DEPLOYMENT_GROUP_MISSING",
        .ecs_update_error = "ECS_UPDATE_ERROR",
        .elastic_load_balancing_invalid = "ELASTIC_LOAD_BALANCING_INVALID",
        .elb_invalid_instance = "ELB_INVALID_INSTANCE",
        .health_constraints = "HEALTH_CONSTRAINTS",
        .health_constraints_invalid = "HEALTH_CONSTRAINTS_INVALID",
        .hook_execution_failure = "HOOK_EXECUTION_FAILURE",
        .iam_role_missing = "IAM_ROLE_MISSING",
        .iam_role_permissions = "IAM_ROLE_PERMISSIONS",
        .internal_error = "INTERNAL_ERROR",
        .invalid_ecs_service = "INVALID_ECS_SERVICE",
        .invalid_lambda_configuration = "INVALID_LAMBDA_CONFIGURATION",
        .invalid_lambda_function = "INVALID_LAMBDA_FUNCTION",
        .invalid_revision = "INVALID_REVISION",
        .manual_stop = "MANUAL_STOP",
        .missing_blue_green_deployment_configuration = "MISSING_BLUE_GREEN_DEPLOYMENT_CONFIGURATION",
        .missing_elb_information = "MISSING_ELB_INFORMATION",
        .missing_github_token = "MISSING_GITHUB_TOKEN",
        .no_ec2_subscription = "NO_EC2_SUBSCRIPTION",
        .no_instances = "NO_INSTANCES",
        .over_max_instances = "OVER_MAX_INSTANCES",
        .resource_limit_exceeded = "RESOURCE_LIMIT_EXCEEDED",
        .revision_missing = "REVISION_MISSING",
        .throttled = "THROTTLED",
        .timeout = "TIMEOUT",
        .cloudformation_stack_failure = "CLOUDFORMATION_STACK_FAILURE",
    };
};
