pub const DataSetType = enum {
    customer_subscriber_hourly_monthly_subscriptions,
    customer_subscriber_annual_subscriptions,
    daily_business_usage_by_instance_type,
    daily_business_fees,
    daily_business_free_trial_conversions,
    daily_business_new_instances,
    daily_business_new_product_subscribers,
    daily_business_canceled_product_subscribers,
    monthly_revenue_billing_and_revenue_data,
    monthly_revenue_annual_subscriptions,
    monthly_revenue_field_demonstration_usage,
    monthly_revenue_flexible_payment_schedule,
    disbursed_amount_by_product,
    disbursed_amount_by_product_with_uncollected_funds,
    disbursed_amount_by_instance_hours,
    disbursed_amount_by_customer_geo,
    disbursed_amount_by_age_of_uncollected_funds,
    disbursed_amount_by_age_of_disbursed_funds,
    disbursed_amount_by_age_of_past_due_funds,
    disbursed_amount_by_uncollected_funds_breakdown,
    customer_profile_by_industry,
    customer_profile_by_revenue,
    customer_profile_by_geography,
    sales_compensation_billed_revenue,
    us_sales_and_use_tax_records,

    pub const json_field_names = .{
        .customer_subscriber_hourly_monthly_subscriptions = "CUSTOMER_SUBSCRIBER_HOURLY_MONTHLY_SUBSCRIPTIONS",
        .customer_subscriber_annual_subscriptions = "CUSTOMER_SUBSCRIBER_ANNUAL_SUBSCRIPTIONS",
        .daily_business_usage_by_instance_type = "DAILY_BUSINESS_USAGE_BY_INSTANCE_TYPE",
        .daily_business_fees = "DAILY_BUSINESS_FEES",
        .daily_business_free_trial_conversions = "DAILY_BUSINESS_FREE_TRIAL_CONVERSIONS",
        .daily_business_new_instances = "DAILY_BUSINESS_NEW_INSTANCES",
        .daily_business_new_product_subscribers = "DAILY_BUSINESS_NEW_PRODUCT_SUBSCRIBERS",
        .daily_business_canceled_product_subscribers = "DAILY_BUSINESS_CANCELED_PRODUCT_SUBSCRIBERS",
        .monthly_revenue_billing_and_revenue_data = "MONTHLY_REVENUE_BILLING_AND_REVENUE_DATA",
        .monthly_revenue_annual_subscriptions = "MONTHLY_REVENUE_ANNUAL_SUBSCRIPTIONS",
        .monthly_revenue_field_demonstration_usage = "MONTHLY_REVENUE_FIELD_DEMONSTRATION_USAGE",
        .monthly_revenue_flexible_payment_schedule = "MONTHLY_REVENUE_FLEXIBLE_PAYMENT_SCHEDULE",
        .disbursed_amount_by_product = "DISBURSED_AMOUNT_BY_PRODUCT",
        .disbursed_amount_by_product_with_uncollected_funds = "DISBURSED_AMOUNT_BY_PRODUCT_WITH_UNCOLLECTED_FUNDS",
        .disbursed_amount_by_instance_hours = "DISBURSED_AMOUNT_BY_INSTANCE_HOURS",
        .disbursed_amount_by_customer_geo = "DISBURSED_AMOUNT_BY_CUSTOMER_GEO",
        .disbursed_amount_by_age_of_uncollected_funds = "DISBURSED_AMOUNT_BY_AGE_OF_UNCOLLECTED_FUNDS",
        .disbursed_amount_by_age_of_disbursed_funds = "DISBURSED_AMOUNT_BY_AGE_OF_DISBURSED_FUNDS",
        .disbursed_amount_by_age_of_past_due_funds = "DISBURSED_AMOUNT_BY_AGE_OF_PAST_DUE_FUNDS",
        .disbursed_amount_by_uncollected_funds_breakdown = "DISBURSED_AMOUNT_BY_UNCOLLECTED_FUNDS_BREAKDOWN",
        .customer_profile_by_industry = "CUSTOMER_PROFILE_BY_INDUSTRY",
        .customer_profile_by_revenue = "CUSTOMER_PROFILE_BY_REVENUE",
        .customer_profile_by_geography = "CUSTOMER_PROFILE_BY_GEOGRAPHY",
        .sales_compensation_billed_revenue = "SALES_COMPENSATION_BILLED_REVENUE",
        .us_sales_and_use_tax_records = "US_SALES_AND_USE_TAX_RECORDS",
    };
};
