pub const GrantOperation = enum {
    decrypt,
    encrypt,
    generate_data_key,
    generate_data_key_without_plaintext,
    re_encrypt_from,
    re_encrypt_to,
    sign,
    verify,
    get_public_key,
    create_grant,
    retire_grant,
    describe_key,
    generate_data_key_pair,
    generate_data_key_pair_without_plaintext,
    generate_mac,
    verify_mac,
    derive_shared_secret,

    pub const json_field_names = .{
        .decrypt = "Decrypt",
        .encrypt = "Encrypt",
        .generate_data_key = "GenerateDataKey",
        .generate_data_key_without_plaintext = "GenerateDataKeyWithoutPlaintext",
        .re_encrypt_from = "ReEncryptFrom",
        .re_encrypt_to = "ReEncryptTo",
        .sign = "Sign",
        .verify = "Verify",
        .get_public_key = "GetPublicKey",
        .create_grant = "CreateGrant",
        .retire_grant = "RetireGrant",
        .describe_key = "DescribeKey",
        .generate_data_key_pair = "GenerateDataKeyPair",
        .generate_data_key_pair_without_plaintext = "GenerateDataKeyPairWithoutPlaintext",
        .generate_mac = "GenerateMac",
        .verify_mac = "VerifyMac",
        .derive_shared_secret = "DeriveSharedSecret",
    };
};
