pub const CodegenGenericDataFieldDataType = enum {
    id,
    string,
    int,
    float,
    aws_date,
    aws_time,
    aws_date_time,
    aws_timestamp,
    aws_email,
    aws_url,
    aws_ip_address,
    boolean,
    aws_json,
    aws_phone,
    @"enum",
    model,
    non_model,

    pub const json_field_names = .{
        .id = "ID",
        .string = "STRING",
        .int = "INT",
        .float = "FLOAT",
        .aws_date = "AWS_DATE",
        .aws_time = "AWS_TIME",
        .aws_date_time = "AWS_DATE_TIME",
        .aws_timestamp = "AWS_TIMESTAMP",
        .aws_email = "AWS_EMAIL",
        .aws_url = "AWS_URL",
        .aws_ip_address = "AWS_IP_ADDRESS",
        .boolean = "BOOLEAN",
        .aws_json = "AWS_JSON",
        .aws_phone = "AWS_PHONE",
        .@"enum" = "ENUM",
        .model = "MODEL",
        .non_model = "NON_MODEL",
    };
};
