pub const ApiCacheType = enum {
    t2_small,
    t2_medium,
    r4_large,
    r4_xlarge,
    r4_2_xlarge,
    r4_4_xlarge,
    r4_8_xlarge,
    small,
    medium,
    large,
    xlarge,
    large_2_x,
    large_4_x,
    large_8_x,
    large_12_x,

    pub const json_field_names = .{
        .t2_small = "T2_SMALL",
        .t2_medium = "T2_MEDIUM",
        .r4_large = "R4_LARGE",
        .r4_xlarge = "R4_XLARGE",
        .r4_2_xlarge = "R4_2XLARGE",
        .r4_4_xlarge = "R4_4XLARGE",
        .r4_8_xlarge = "R4_8XLARGE",
        .small = "SMALL",
        .medium = "MEDIUM",
        .large = "LARGE",
        .xlarge = "XLARGE",
        .large_2_x = "LARGE_2X",
        .large_4_x = "LARGE_4X",
        .large_8_x = "LARGE_8X",
        .large_12_x = "LARGE_12X",
    };
};
