const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const SourceApiAssociationStatus = @import("source_api_association_status.zig").SourceApiAssociationStatus;

pub const DisassociateSourceGraphqlApiInput = struct {
    /// The ID generated by the AppSync service for the source API association.
    association_id: []const u8,

    /// The identifier of the AppSync Merged API. This is generated by the AppSync
    /// service. In
    /// most cases, Merged APIs (especially in your account) only require the API ID
    /// value or ARN
    /// of the merged API. However, Merged APIs in other accounts (cross-account use
    /// cases)
    /// strictly require the full resource ARN of the merged API.
    merged_api_identifier: []const u8,

    pub const json_field_names = .{
        .association_id = "associationId",
        .merged_api_identifier = "mergedApiIdentifier",
    };
};

pub const DisassociateSourceGraphqlApiOutput = struct {
    /// The state of the source API association.
    source_api_association_status: ?SourceApiAssociationStatus = null,

    pub const json_field_names = .{
        .source_api_association_status = "sourceApiAssociationStatus",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: DisassociateSourceGraphqlApiInput, options: CallOptions) !DisassociateSourceGraphqlApiOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "appsync", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: DisassociateSourceGraphqlApiInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("appsync", "AppSync", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/v1/mergedApis/");
    try path_buf.appendSlice(allocator, input.merged_api_identifier);
    try path_buf.appendSlice(allocator, "/sourceApiAssociations/");
    try path_buf.appendSlice(allocator, input.association_id);
    const path = try path_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(ep.host);
    request.method = .DELETE;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !DisassociateSourceGraphqlApiOutput {
    const result: DisassociateSourceGraphqlApiOutput = try aws.json.parseJsonObject(
        DisassociateSourceGraphqlApiOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
