const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const TypeDefinitionFormat = @import("type_definition_format.zig").TypeDefinitionFormat;
const Type = @import("type.zig").Type;

pub const ListTypesByAssociationInput = struct {
    /// The ID generated by the AppSync service for the source API association.
    association_id: []const u8,

    /// The format type.
    format: TypeDefinitionFormat,

    /// The maximum number of results that you want the request to return.
    max_results: ?i32 = null,

    /// The identifier of the AppSync Merged API. This is generated by the AppSync
    /// service. In
    /// most cases, Merged APIs (especially in your account) only require the API ID
    /// value or ARN
    /// of the merged API. However, Merged APIs in other accounts (cross-account use
    /// cases)
    /// strictly require the full resource ARN of the merged API.
    merged_api_identifier: []const u8,

    /// An identifier that was returned from the previous call to this operation,
    /// which you can
    /// use to return the next set of items in the list.
    next_token: ?[]const u8 = null,

    pub const json_field_names = .{
        .association_id = "associationId",
        .format = "format",
        .max_results = "maxResults",
        .merged_api_identifier = "mergedApiIdentifier",
        .next_token = "nextToken",
    };
};

pub const ListTypesByAssociationOutput = struct {
    /// An identifier that was returned from the previous call to this operation,
    /// which you can
    /// use to return the next set of items in the list.
    next_token: ?[]const u8 = null,

    /// The `Type` objects.
    types: ?[]const Type = null,

    pub const json_field_names = .{
        .next_token = "nextToken",
        .types = "types",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: ListTypesByAssociationInput, options: CallOptions) !ListTypesByAssociationOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "appsync", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: ListTypesByAssociationInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("appsync", "AppSync", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/v1/mergedApis/");
    try path_buf.appendSlice(allocator, input.merged_api_identifier);
    try path_buf.appendSlice(allocator, "/sourceApiAssociations/");
    try path_buf.appendSlice(allocator, input.association_id);
    try path_buf.appendSlice(allocator, "/types");
    const path = try path_buf.toOwnedSlice(allocator);

    var query_buf: std.ArrayList(u8) = .empty;
    var query_has_prev = false;
    if (query_has_prev) try query_buf.appendSlice(allocator, "&");
    try query_buf.appendSlice(allocator, "format=");
    try aws.url.appendUrlEncoded(allocator, &query_buf, input.format.wireName());
    query_has_prev = true;
    if (input.max_results) |v| {
        if (query_has_prev) try query_buf.appendSlice(allocator, "&");
        try query_buf.appendSlice(allocator, "maxResults=");
        {
            const num_str = std.fmt.allocPrint(allocator, "{d}", .{v}) catch "";
            try query_buf.appendSlice(allocator, num_str);
        }
        query_has_prev = true;
    }
    if (input.next_token) |v| {
        if (query_has_prev) try query_buf.appendSlice(allocator, "&");
        try query_buf.appendSlice(allocator, "nextToken=");
        try aws.url.appendUrlEncoded(allocator, &query_buf, v);
        query_has_prev = true;
    }
    const query = try query_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(ep.host);
    request.method = .GET;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    request.query = query;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !ListTypesByAssociationOutput {
    const result: ListTypesByAssociationOutput = try aws.json.parseJsonObject(
        ListTypesByAssociationOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
