/// Describes the ARNs and IDs of associations, Merged APIs, and source APIs.
pub const SourceApiAssociationSummary = struct {
    /// The Amazon Resource Name (ARN) of the source API association.
    association_arn: ?[]const u8,

    /// The ID generated by the AppSync service for the source API association.
    association_id: ?[]const u8,

    /// The description field.
    description: ?[]const u8,

    /// The Amazon Resource Name (ARN) of the AppSync Merged API.
    merged_api_arn: ?[]const u8,

    /// The ID of the AppSync Merged API.
    merged_api_id: ?[]const u8,

    /// The Amazon Resource Name (ARN) of the AppSync Source API.
    source_api_arn: ?[]const u8,

    /// The ID of the AppSync source API.
    source_api_id: ?[]const u8,

    pub const json_field_names = .{
        .association_arn = "associationArn",
        .association_id = "associationId",
        .description = "description",
        .merged_api_arn = "mergedApiArn",
        .merged_api_id = "mergedApiId",
        .source_api_arn = "sourceApiArn",
        .source_api_id = "sourceApiId",
    };
};
