pub const CommunicationType = enum {
    case_created,
    case_updated,
    case_acknowledged,
    case_closed,
    case_updated_to_service_managed,
    case_update_case_status,
    case_pending_customer_action_reminder,
    case_attachment_url_uploaded,
    case_comment_added,
    case_comment_updated,
    membership_created,
    membership_updated,
    membership_cancelled,
    register_delegated_administrator,
    deregister_delegated_administrator,
    disable_aws_service_access,

    pub const json_field_names = .{
        .case_created = "CASE_CREATED",
        .case_updated = "CASE_UPDATED",
        .case_acknowledged = "CASE_ACKNOWLEDGED",
        .case_closed = "CASE_CLOSED",
        .case_updated_to_service_managed = "CASE_UPDATED_TO_SERVICE_MANAGED",
        .case_update_case_status = "CASE_UPDATE_CASE_STATUS",
        .case_pending_customer_action_reminder = "CASE_PENDING_CUSTOMER_ACTION_REMINDER",
        .case_attachment_url_uploaded = "CASE_ATTACHMENT_URL_UPLOADED",
        .case_comment_added = "CASE_COMMENT_ADDED",
        .case_comment_updated = "CASE_COMMENT_UPDATED",
        .membership_created = "MEMBERSHIP_CREATED",
        .membership_updated = "MEMBERSHIP_UPDATED",
        .membership_cancelled = "MEMBERSHIP_CANCELLED",
        .register_delegated_administrator = "REGISTER_DELEGATED_ADMINISTRATOR",
        .deregister_delegated_administrator = "DEREGISTER_DELEGATED_ADMINISTRATOR",
        .disable_aws_service_access = "DISABLE_AWS_SERVICE_ACCESS",
    };
};
