const std = @import("std");

pub const CurrencyCode = enum {
    aed,
    amd,
    ars,
    aud,
    awg,
    azn,
    bbd,
    bdt,
    bgn,
    bmd,
    bnd,
    bob,
    brl,
    bsd,
    byr,
    bzd,
    cad,
    chf,
    clp,
    cny,
    cop,
    crc,
    czk,
    dkk,
    dop,
    eek,
    egp,
    eur,
    gbp,
    gel,
    ghs,
    gtq,
    gyd,
    hkd,
    hnl,
    hrk,
    htg,
    huf,
    idr,
    ils,
    inr,
    isk,
    jmd,
    jpy,
    kes,
    khr,
    krw,
    kyd,
    kzt,
    lbp,
    lkr,
    ltl,
    lvl,
    mad,
    mnt,
    mop,
    mur,
    mvr,
    mxn,
    myr,
    nad,
    ngn,
    nio,
    nok,
    nzd,
    pab,
    pen,
    php,
    pkr,
    pln,
    pyg,
    qar,
    ron,
    rub,
    sar,
    sek,
    sgd,
    sit,
    skk,
    thb,
    tnd,
    @"try",
    ttd,
    twd,
    tzs,
    uah,
    usd,
    uyu,
    uzs,
    vnd,
    xaf,
    xcd,
    xof,
    xpf,
    zar,

    pub const json_field_names = .{
        .aed = "AED",
        .amd = "AMD",
        .ars = "ARS",
        .aud = "AUD",
        .awg = "AWG",
        .azn = "AZN",
        .bbd = "BBD",
        .bdt = "BDT",
        .bgn = "BGN",
        .bmd = "BMD",
        .bnd = "BND",
        .bob = "BOB",
        .brl = "BRL",
        .bsd = "BSD",
        .byr = "BYR",
        .bzd = "BZD",
        .cad = "CAD",
        .chf = "CHF",
        .clp = "CLP",
        .cny = "CNY",
        .cop = "COP",
        .crc = "CRC",
        .czk = "CZK",
        .dkk = "DKK",
        .dop = "DOP",
        .eek = "EEK",
        .egp = "EGP",
        .eur = "EUR",
        .gbp = "GBP",
        .gel = "GEL",
        .ghs = "GHS",
        .gtq = "GTQ",
        .gyd = "GYD",
        .hkd = "HKD",
        .hnl = "HNL",
        .hrk = "HRK",
        .htg = "HTG",
        .huf = "HUF",
        .idr = "IDR",
        .ils = "ILS",
        .inr = "INR",
        .isk = "ISK",
        .jmd = "JMD",
        .jpy = "JPY",
        .kes = "KES",
        .khr = "KHR",
        .krw = "KRW",
        .kyd = "KYD",
        .kzt = "KZT",
        .lbp = "LBP",
        .lkr = "LKR",
        .ltl = "LTL",
        .lvl = "LVL",
        .mad = "MAD",
        .mnt = "MNT",
        .mop = "MOP",
        .mur = "MUR",
        .mvr = "MVR",
        .mxn = "MXN",
        .myr = "MYR",
        .nad = "NAD",
        .ngn = "NGN",
        .nio = "NIO",
        .nok = "NOK",
        .nzd = "NZD",
        .pab = "PAB",
        .pen = "PEN",
        .php = "PHP",
        .pkr = "PKR",
        .pln = "PLN",
        .pyg = "PYG",
        .qar = "QAR",
        .ron = "RON",
        .rub = "RUB",
        .sar = "SAR",
        .sek = "SEK",
        .sgd = "SGD",
        .sit = "SIT",
        .skk = "SKK",
        .thb = "THB",
        .tnd = "TND",
        .@"try" = "TRY",
        .ttd = "TTD",
        .twd = "TWD",
        .tzs = "TZS",
        .uah = "UAH",
        .usd = "USD",
        .uyu = "UYU",
        .uzs = "UZS",
        .vnd = "VND",
        .xaf = "XAF",
        .xcd = "XCD",
        .xof = "XOF",
        .xpf = "XPF",
        .zar = "ZAR",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .aed => "AED",
            .amd => "AMD",
            .ars => "ARS",
            .aud => "AUD",
            .awg => "AWG",
            .azn => "AZN",
            .bbd => "BBD",
            .bdt => "BDT",
            .bgn => "BGN",
            .bmd => "BMD",
            .bnd => "BND",
            .bob => "BOB",
            .brl => "BRL",
            .bsd => "BSD",
            .byr => "BYR",
            .bzd => "BZD",
            .cad => "CAD",
            .chf => "CHF",
            .clp => "CLP",
            .cny => "CNY",
            .cop => "COP",
            .crc => "CRC",
            .czk => "CZK",
            .dkk => "DKK",
            .dop => "DOP",
            .eek => "EEK",
            .egp => "EGP",
            .eur => "EUR",
            .gbp => "GBP",
            .gel => "GEL",
            .ghs => "GHS",
            .gtq => "GTQ",
            .gyd => "GYD",
            .hkd => "HKD",
            .hnl => "HNL",
            .hrk => "HRK",
            .htg => "HTG",
            .huf => "HUF",
            .idr => "IDR",
            .ils => "ILS",
            .inr => "INR",
            .isk => "ISK",
            .jmd => "JMD",
            .jpy => "JPY",
            .kes => "KES",
            .khr => "KHR",
            .krw => "KRW",
            .kyd => "KYD",
            .kzt => "KZT",
            .lbp => "LBP",
            .lkr => "LKR",
            .ltl => "LTL",
            .lvl => "LVL",
            .mad => "MAD",
            .mnt => "MNT",
            .mop => "MOP",
            .mur => "MUR",
            .mvr => "MVR",
            .mxn => "MXN",
            .myr => "MYR",
            .nad => "NAD",
            .ngn => "NGN",
            .nio => "NIO",
            .nok => "NOK",
            .nzd => "NZD",
            .pab => "PAB",
            .pen => "PEN",
            .php => "PHP",
            .pkr => "PKR",
            .pln => "PLN",
            .pyg => "PYG",
            .qar => "QAR",
            .ron => "RON",
            .rub => "RUB",
            .sar => "SAR",
            .sek => "SEK",
            .sgd => "SGD",
            .sit => "SIT",
            .skk => "SKK",
            .thb => "THB",
            .tnd => "TND",
            .@"try" => "TRY",
            .ttd => "TTD",
            .twd => "TWD",
            .tzs => "TZS",
            .uah => "UAH",
            .usd => "USD",
            .uyu => "UYU",
            .uzs => "UZS",
            .vnd => "VND",
            .xaf => "XAF",
            .xcd => "XCD",
            .xof => "XOF",
            .xpf => "XPF",
            .zar => "ZAR",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
