pub const FindingResourceType = enum {
    ec2_instance,
    ec2_network_interface,
    s3_bucket,
    s3_object,
    access_key,
    eks_cluster,
    kubernetes_workload,
    container,
    ecs_cluster,
    ecs_task,
    autoscaling_auto_scaling_group,
    iam_instance_profile,
    cloudformation_stack,
    ec2_launch_template,
    ec2_vpc,
    ec2_image,

    pub const json_field_names = .{
        .ec2_instance = "EC2_INSTANCE",
        .ec2_network_interface = "EC2_NETWORK_INTERFACE",
        .s3_bucket = "S3_BUCKET",
        .s3_object = "S3_OBJECT",
        .access_key = "ACCESS_KEY",
        .eks_cluster = "EKS_CLUSTER",
        .kubernetes_workload = "KUBERNETES_WORKLOAD",
        .container = "CONTAINER",
        .ecs_cluster = "ECS_CLUSTER",
        .ecs_task = "ECS_TASK",
        .autoscaling_auto_scaling_group = "AUTOSCALING_AUTO_SCALING_GROUP",
        .iam_instance_profile = "IAM_INSTANCE_PROFILE",
        .cloudformation_stack = "CLOUDFORMATION_STACK",
        .ec2_launch_template = "EC2_LAUNCH_TEMPLATE",
        .ec2_vpc = "EC2_VPC",
        .ec2_image = "EC2_IMAGE",
    };
};
