const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const ThreatIntelSetFormat = @import("threat_intel_set_format.zig").ThreatIntelSetFormat;
const ThreatIntelSetStatus = @import("threat_intel_set_status.zig").ThreatIntelSetStatus;

pub const GetThreatIntelSetInput = struct {
    /// The unique ID of the detector that is associated with the threatIntelSet.
    ///
    /// To find the `detectorId` in the current Region, see the Settings page in the
    /// GuardDuty console, or run the
    /// [ListDetectors](https://docs.aws.amazon.com/guardduty/latest/APIReference/API_ListDetectors.html) API.
    detector_id: []const u8,

    /// The unique ID of the threatIntelSet that you want to get.
    threat_intel_set_id: []const u8,

    pub const json_field_names = .{
        .detector_id = "DetectorId",
        .threat_intel_set_id = "ThreatIntelSetId",
    };
};

pub const GetThreatIntelSetOutput = struct {
    /// The Amazon Web Services account ID that owns the Amazon S3 bucket specified
    /// in the **location** parameter. This field appears in the response only if it
    /// was provided during ThreatIntelSet creation or update.
    expected_bucket_owner: ?[]const u8 = null,

    /// The format of the threatIntelSet.
    format: ThreatIntelSetFormat,

    /// The URI of the file that contains the ThreatIntelSet.
    location: []const u8,

    /// A user-friendly ThreatIntelSet name displayed in all findings that are
    /// generated by activity that involves IP addresses included in this
    /// ThreatIntelSet.
    name: []const u8,

    /// The status of threatIntelSet file uploaded.
    status: ThreatIntelSetStatus,

    /// The tags of the threat list resource.
    tags: ?[]const aws.map.StringMapEntry = null,

    pub const json_field_names = .{
        .expected_bucket_owner = "ExpectedBucketOwner",
        .format = "Format",
        .location = "Location",
        .name = "Name",
        .status = "Status",
        .tags = "Tags",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetThreatIntelSetInput, options: CallOptions) !GetThreatIntelSetOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "guardduty", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetThreatIntelSetInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("guardduty", "GuardDuty", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/detector/");
    try path_buf.appendSlice(allocator, input.detector_id);
    try path_buf.appendSlice(allocator, "/threatintelset/");
    try path_buf.appendSlice(allocator, input.threat_intel_set_id);
    const path = try path_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(ep.host);
    request.method = .GET;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetThreatIntelSetOutput {
    const result: GetThreatIntelSetOutput = try aws.json.parseJsonObject(
        GetThreatIntelSetOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
