const DetectionRuleDataSource = @import("detection_rule_data_source.zig").DetectionRuleDataSource;
const RuleLanguage = @import("rule_language.zig").RuleLanguage;
const RuleSchema = @import("rule_schema.zig").RuleSchema;
const DetectionRuleSeverity = @import("detection_rule_severity.zig").DetectionRuleSeverity;

/// Contains summary information about a custom detection rule.
pub const RuleSummary = struct {
    /// The Amazon Resource Name (ARN) of the rule.
    arn: []const u8,

    /// The timestamp when the rule was created.
    created_at: i64,

    /// The data source that the rule analyzes.
    data_source: DetectionRuleDataSource,

    /// A description of what the rule detects.
    description: []const u8,

    /// The language used for the detection logic expression.
    language: ?RuleLanguage = null,

    /// The display name of the rule.
    name: []const u8,

    /// The unique identifier for the rule.
    rule_id: []const u8,

    /// The schema version used by the rule definition.
    schema: ?RuleSchema = null,

    /// The Amazon Web Services service associated with the rule.
    service: []const u8,

    /// The severity level assigned to findings generated by this rule.
    severity: DetectionRuleSeverity,

    /// The MITRE ATT&CK tactic associated with the rule.
    tactic: []const u8,

    /// The MITRE ATT&CK technique associated with the rule.
    technique: []const u8,

    /// The timestamp when the rule was last updated.
    updated_at: ?i64 = null,

    pub const json_field_names = .{
        .arn = "Arn",
        .created_at = "CreatedAt",
        .data_source = "DataSource",
        .description = "Description",
        .language = "Language",
        .name = "Name",
        .rule_id = "RuleId",
        .schema = "Schema",
        .service = "Service",
        .severity = "Severity",
        .tactic = "Tactic",
        .technique = "Technique",
        .updated_at = "UpdatedAt",
    };
};
