pub const UsageFeature = enum {
    flow_logs,
    cloud_trail,
    dns_logs,
    s3_data_events,
    eks_audit_logs,
    ebs_malware_protection,
    rds_login_events,
    lambda_network_logs,
    eks_runtime_monitoring,
    fargate_runtime_monitoring,
    ec2_runtime_monitoring,
    rds_dbi_protection_provisioned,
    rds_dbi_protection_serverless,

    pub const json_field_names = .{
        .flow_logs = "FLOW_LOGS",
        .cloud_trail = "CLOUD_TRAIL",
        .dns_logs = "DNS_LOGS",
        .s3_data_events = "S3_DATA_EVENTS",
        .eks_audit_logs = "EKS_AUDIT_LOGS",
        .ebs_malware_protection = "EBS_MALWARE_PROTECTION",
        .rds_login_events = "RDS_LOGIN_EVENTS",
        .lambda_network_logs = "LAMBDA_NETWORK_LOGS",
        .eks_runtime_monitoring = "EKS_RUNTIME_MONITORING",
        .fargate_runtime_monitoring = "FARGATE_RUNTIME_MONITORING",
        .ec2_runtime_monitoring = "EC2_RUNTIME_MONITORING",
        .rds_dbi_protection_provisioned = "RDS_DBI_PROTECTION_PROVISIONED",
        .rds_dbi_protection_serverless = "RDS_DBI_PROTECTION_SERVERLESS",
    };
};
