const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Tag = @import("tag.zig").Tag;
const EventSubscription = @import("event_subscription.zig").EventSubscription;
const serde = @import("serde.zig");

pub const CreateEventSubscriptionInput = struct {
    /// A boolean value; set to `true` to activate the subscription, and set to
    /// `false` to create the subscription but not activate it.
    enabled: ?bool = null,

    /// Specifies the Amazon Redshift event categories to be published by the event
    /// notification
    /// subscription.
    ///
    /// Values: configuration, management, monitoring, security, pending
    event_categories: ?[]const []const u8 = null,

    /// Specifies the Amazon Redshift event severity to be published by the event
    /// notification
    /// subscription.
    ///
    /// Values: ERROR, INFO
    severity: ?[]const u8 = null,

    /// The Amazon Resource Name (ARN) of the Amazon SNS topic used to transmit the
    /// event
    /// notifications. The ARN is created by Amazon SNS when you create a topic and
    /// subscribe to
    /// it.
    sns_topic_arn: []const u8,

    /// A list of one or more identifiers of Amazon Redshift source objects. All of
    /// the objects
    /// must be of the same type as was specified in the source type parameter. The
    /// event
    /// subscription will return only events generated by the specified objects. If
    /// not
    /// specified, then events are returned for all objects within the source type
    /// specified.
    ///
    /// Example: my-cluster-1, my-cluster-2
    ///
    /// Example: my-snapshot-20131010
    source_ids: ?[]const []const u8 = null,

    /// The type of source that will be generating the events. For example, if you
    /// want to
    /// be notified of events generated by a cluster, you would set this parameter
    /// to cluster.
    /// If this value is not specified, events are returned for all Amazon Redshift
    /// objects in your
    /// Amazon Web Services account. You must specify a source type in order to
    /// specify source IDs.
    ///
    /// Valid values: cluster, cluster-parameter-group, cluster-security-group,
    /// cluster-snapshot, and scheduled-action.
    source_type: ?[]const u8 = null,

    /// The name of the event subscription to be created.
    ///
    /// Constraints:
    ///
    /// * Cannot be null, empty, or blank.
    ///
    /// * Must contain from 1 to 255 alphanumeric characters or hyphens.
    ///
    /// * First character must be a letter.
    ///
    /// * Cannot end with a hyphen or contain two consecutive hyphens.
    subscription_name: []const u8,

    /// A list of tag instances.
    tags: ?[]const Tag = null,
};

pub const CreateEventSubscriptionOutput = struct {
    event_subscription: ?EventSubscription = null,
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateEventSubscriptionInput, options: CallOptions) !CreateEventSubscriptionOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "redshift", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateEventSubscriptionInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("redshift", "Redshift", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var body_buf: std.ArrayList(u8) = .empty;

    try body_buf.appendSlice(allocator, "Action=CreateEventSubscription&Version=2012-12-01");
    if (input.enabled) |v| {
        try body_buf.appendSlice(allocator, "&Enabled=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, if (v) "true" else "false");
    }
    if (input.event_categories) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            var prefix_buf: [256]u8 = undefined;
            const field_prefix = std.fmt.bufPrint(&prefix_buf, "&EventCategories.EventCategory.{d}=", .{n}) catch continue;
            try body_buf.appendSlice(allocator, field_prefix);
            try aws.url.appendUrlEncoded(allocator, &body_buf, item);
        }
    }
    if (input.severity) |v| {
        try body_buf.appendSlice(allocator, "&Severity=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    try body_buf.appendSlice(allocator, "&SnsTopicArn=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.sns_topic_arn);
    if (input.source_ids) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            var prefix_buf: [256]u8 = undefined;
            const field_prefix = std.fmt.bufPrint(&prefix_buf, "&SourceIds.SourceId.{d}=", .{n}) catch continue;
            try body_buf.appendSlice(allocator, field_prefix);
            try aws.url.appendUrlEncoded(allocator, &body_buf, item);
        }
    }
    if (input.source_type) |v| {
        try body_buf.appendSlice(allocator, "&SourceType=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    try body_buf.appendSlice(allocator, "&SubscriptionName=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.subscription_name);
    if (input.tags) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            {
                var prefix_buf: [256]u8 = undefined;
                if (item.key) |fv_1| {
                    const field_prefix = std.fmt.bufPrint(&prefix_buf, "&Tags.Tag.{d}.Key=", .{n}) catch continue;
                    try body_buf.appendSlice(allocator, field_prefix);
                    try aws.url.appendUrlEncoded(allocator, &body_buf, fv_1);
                }
            }
            {
                var prefix_buf: [256]u8 = undefined;
                if (item.value) |fv_1| {
                    const field_prefix = std.fmt.bufPrint(&prefix_buf, "&Tags.Tag.{d}.Value=", .{n}) catch continue;
                    try body_buf.appendSlice(allocator, field_prefix);
                    try aws.url.appendUrlEncoded(allocator, &body_buf, fv_1);
                }
            }
        }
    }

    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-www-form-urlencoded");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateEventSubscriptionOutput {
    _ = status;
    _ = headers;
    var reader = aws.xml.Reader.init(body);

    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "CreateEventSubscriptionResult")) break;
            },
            else => {},
        }
    }

    var result: CreateEventSubscriptionOutput = .{};
    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "EventSubscription")) {
                    result.event_subscription = try serde.deserializeEventSubscription(allocator, &reader);
                } else {
                    try reader.skipElement();
                }
            },
            .element_end => break,
            else => {},
        }
    }

    return result;
}
