pub const LanguageCode = enum {
    en_us,
    en_gb,
    es_us,
    fr_ca,
    fr_fr,
    en_au,
    it_it,
    de_de,
    pt_br,
    ja_jp,
    ko_kr,
    zh_cn,
    th_th,
    es_es,
    ar_sa,
    pt_pt,
    ca_es,
    ar_ae,
    hi_in,
    zh_hk,
    nl_nl,
    no_no,
    sv_se,
    pl_pl,
    fi_fi,
    zh_tw,
    en_in,
    en_ie,
    en_nz,
    en_ab,
    en_za,
    en_wl,
    de_ch,
    af_za,
    eu_es,
    hr_hr,
    cs_cz,
    da_dk,
    fa_ir,
    gl_es,
    el_gr,
    he_il,
    id_id,
    lv_lv,
    ms_my,
    ro_ro,
    ru_ru,
    sr_rs,
    sk_sk,
    so_so,
    tl_ph,
    uk_ua,
    vi_vn,
    zu_za,
    am_et,
    be_by,
    bg_bg,
    bn_in,
    bs_ba,
    ckb_iq,
    ckb_ir,
    cy_wl,
    es_mx,
    et_et,
    fa_af,
    gu_in,
    ht_ht,
    hu_hu,
    hy_am,
    is_is,
    jv_id,
    ka_ge,
    kab_dz,
    kk_kz,
    km_kh,
    kn_in,
    lg_in,
    lt_lt,
    mk_mk,
    ml_in,
    mr_in,
    my_mm,
    ne_np,
    or_in,
    pa_in,
    ps_af,
    si_lk,
    sl_si,
    sq_al,
    su_id,
    sw_bi,
    sw_ke,
    sw_rw,
    sw_tz,
    sw_ug,
    ta_in,
    te_in,
    tr_tr,
    uz_uz,

    pub const json_field_names = .{
        .en_us = "EN_US",
        .en_gb = "EN_GB",
        .es_us = "ES_US",
        .fr_ca = "FR_CA",
        .fr_fr = "FR_FR",
        .en_au = "EN_AU",
        .it_it = "IT_IT",
        .de_de = "DE_DE",
        .pt_br = "PT_BR",
        .ja_jp = "JA_JP",
        .ko_kr = "KO_KR",
        .zh_cn = "ZH_CN",
        .th_th = "TH_TH",
        .es_es = "ES_ES",
        .ar_sa = "AR_SA",
        .pt_pt = "PT_PT",
        .ca_es = "CA_ES",
        .ar_ae = "AR_AE",
        .hi_in = "HI_IN",
        .zh_hk = "ZH_HK",
        .nl_nl = "NL_NL",
        .no_no = "NO_NO",
        .sv_se = "SV_SE",
        .pl_pl = "PL_PL",
        .fi_fi = "FI_FI",
        .zh_tw = "ZH_TW",
        .en_in = "EN_IN",
        .en_ie = "EN_IE",
        .en_nz = "EN_NZ",
        .en_ab = "EN_AB",
        .en_za = "EN_ZA",
        .en_wl = "EN_WL",
        .de_ch = "DE_CH",
        .af_za = "AF_ZA",
        .eu_es = "EU_ES",
        .hr_hr = "HR_HR",
        .cs_cz = "CS_CZ",
        .da_dk = "DA_DK",
        .fa_ir = "FA_IR",
        .gl_es = "GL_ES",
        .el_gr = "EL_GR",
        .he_il = "HE_IL",
        .id_id = "ID_ID",
        .lv_lv = "LV_LV",
        .ms_my = "MS_MY",
        .ro_ro = "RO_RO",
        .ru_ru = "RU_RU",
        .sr_rs = "SR_RS",
        .sk_sk = "SK_SK",
        .so_so = "SO_SO",
        .tl_ph = "TL_PH",
        .uk_ua = "UK_UA",
        .vi_vn = "VI_VN",
        .zu_za = "ZU_ZA",
        .am_et = "AM_ET",
        .be_by = "BE_BY",
        .bg_bg = "BG_BG",
        .bn_in = "BN_IN",
        .bs_ba = "BS_BA",
        .ckb_iq = "CKB_IQ",
        .ckb_ir = "CKB_IR",
        .cy_wl = "CY_WL",
        .es_mx = "ES_MX",
        .et_et = "ET_ET",
        .fa_af = "FA_AF",
        .gu_in = "GU_IN",
        .ht_ht = "HT_HT",
        .hu_hu = "HU_HU",
        .hy_am = "HY_AM",
        .is_is = "IS_IS",
        .jv_id = "JV_ID",
        .ka_ge = "KA_GE",
        .kab_dz = "KAB_DZ",
        .kk_kz = "KK_KZ",
        .km_kh = "KM_KH",
        .kn_in = "KN_IN",
        .lg_in = "LG_IN",
        .lt_lt = "LT_LT",
        .mk_mk = "MK_MK",
        .ml_in = "ML_IN",
        .mr_in = "MR_IN",
        .my_mm = "MY_MM",
        .ne_np = "NE_NP",
        .or_in = "OR_IN",
        .pa_in = "PA_IN",
        .ps_af = "PS_AF",
        .si_lk = "SI_LK",
        .sl_si = "SL_SI",
        .sq_al = "SQ_AL",
        .su_id = "SU_ID",
        .sw_bi = "SW_BI",
        .sw_ke = "SW_KE",
        .sw_rw = "SW_RW",
        .sw_tz = "SW_TZ",
        .sw_ug = "SW_UG",
        .ta_in = "TA_IN",
        .te_in = "TE_IN",
        .tr_tr = "TR_TR",
        .uz_uz = "UZ_UZ",
    };
};
