const std = @import("std");

pub const OpenSearchPartitionInstanceType = enum {
    m_3_medium_search,
    m_3_large_search,
    m_3_xlarge_search,
    m_3_2_xlarge_search,
    m_4_large_search,
    m_4_xlarge_search,
    m_4_2_xlarge_search,
    m_4_4_xlarge_search,
    m_4_10_xlarge_search,
    m_5_large_search,
    m_5_xlarge_search,
    m_5_2_xlarge_search,
    m_5_4_xlarge_search,
    m_5_12_xlarge_search,
    m_5_24_xlarge_search,
    r_5_large_search,
    r_5_xlarge_search,
    r_5_2_xlarge_search,
    r_5_4_xlarge_search,
    r_5_12_xlarge_search,
    r_5_24_xlarge_search,
    c_5_large_search,
    c_5_xlarge_search,
    c_5_2_xlarge_search,
    c_5_4_xlarge_search,
    c_5_9_xlarge_search,
    c_5_18_xlarge_search,
    t_3_nano_search,
    t_3_micro_search,
    t_3_small_search,
    t_3_medium_search,
    t_3_large_search,
    t_3_xlarge_search,
    t_3_2_xlarge_search,
    or_1_medium_search,
    or_1_large_search,
    or_1_xlarge_search,
    or_1_2_xlarge_search,
    or_1_4_xlarge_search,
    or_1_8_xlarge_search,
    or_1_12_xlarge_search,
    or_1_16_xlarge_search,
    ultrawarm_1_medium_search,
    ultrawarm_1_large_search,
    ultrawarm_1_xlarge_search,
    t_2_micro_search,
    t_2_small_search,
    t_2_medium_search,
    r_3_large_search,
    r_3_xlarge_search,
    r_3_2_xlarge_search,
    r_3_4_xlarge_search,
    r_3_8_xlarge_search,
    i_2_xlarge_search,
    i_2_2_xlarge_search,
    d_2_xlarge_search,
    d_2_2_xlarge_search,
    d_2_4_xlarge_search,
    d_2_8_xlarge_search,
    c_4_large_search,
    c_4_xlarge_search,
    c_4_2_xlarge_search,
    c_4_4_xlarge_search,
    c_4_8_xlarge_search,
    r_4_large_search,
    r_4_xlarge_search,
    r_4_2_xlarge_search,
    r_4_4_xlarge_search,
    r_4_8_xlarge_search,
    r_4_16_xlarge_search,
    i_3_large_search,
    i_3_xlarge_search,
    i_3_2_xlarge_search,
    i_3_4_xlarge_search,
    i_3_8_xlarge_search,
    i_3_16_xlarge_search,
    r_6_g_large_search,
    r_6_g_xlarge_search,
    r_6_g_2_xlarge_search,
    r_6_g_4_xlarge_search,
    r_6_g_8_xlarge_search,
    r_6_g_12_xlarge_search,
    m_6_g_large_search,
    m_6_g_xlarge_search,
    m_6_g_2_xlarge_search,
    m_6_g_4_xlarge_search,
    m_6_g_8_xlarge_search,
    m_6_g_12_xlarge_search,
    c_6_g_large_search,
    c_6_g_xlarge_search,
    c_6_g_2_xlarge_search,
    c_6_g_4_xlarge_search,
    c_6_g_8_xlarge_search,
    c_6_g_12_xlarge_search,
    r_6_gd_large_search,
    r_6_gd_xlarge_search,
    r_6_gd_2_xlarge_search,
    r_6_gd_4_xlarge_search,
    r_6_gd_8_xlarge_search,
    r_6_gd_12_xlarge_search,
    r_6_gd_16_xlarge_search,
    t_4_g_small_search,
    t_4_g_medium_search,

    pub const json_field_names = .{
        .m_3_medium_search = "m3.medium.search",
        .m_3_large_search = "m3.large.search",
        .m_3_xlarge_search = "m3.xlarge.search",
        .m_3_2_xlarge_search = "m3.2xlarge.search",
        .m_4_large_search = "m4.large.search",
        .m_4_xlarge_search = "m4.xlarge.search",
        .m_4_2_xlarge_search = "m4.2xlarge.search",
        .m_4_4_xlarge_search = "m4.4xlarge.search",
        .m_4_10_xlarge_search = "m4.10xlarge.search",
        .m_5_large_search = "m5.large.search",
        .m_5_xlarge_search = "m5.xlarge.search",
        .m_5_2_xlarge_search = "m5.2xlarge.search",
        .m_5_4_xlarge_search = "m5.4xlarge.search",
        .m_5_12_xlarge_search = "m5.12xlarge.search",
        .m_5_24_xlarge_search = "m5.24xlarge.search",
        .r_5_large_search = "r5.large.search",
        .r_5_xlarge_search = "r5.xlarge.search",
        .r_5_2_xlarge_search = "r5.2xlarge.search",
        .r_5_4_xlarge_search = "r5.4xlarge.search",
        .r_5_12_xlarge_search = "r5.12xlarge.search",
        .r_5_24_xlarge_search = "r5.24xlarge.search",
        .c_5_large_search = "c5.large.search",
        .c_5_xlarge_search = "c5.xlarge.search",
        .c_5_2_xlarge_search = "c5.2xlarge.search",
        .c_5_4_xlarge_search = "c5.4xlarge.search",
        .c_5_9_xlarge_search = "c5.9xlarge.search",
        .c_5_18_xlarge_search = "c5.18xlarge.search",
        .t_3_nano_search = "t3.nano.search",
        .t_3_micro_search = "t3.micro.search",
        .t_3_small_search = "t3.small.search",
        .t_3_medium_search = "t3.medium.search",
        .t_3_large_search = "t3.large.search",
        .t_3_xlarge_search = "t3.xlarge.search",
        .t_3_2_xlarge_search = "t3.2xlarge.search",
        .or_1_medium_search = "or1.medium.search",
        .or_1_large_search = "or1.large.search",
        .or_1_xlarge_search = "or1.xlarge.search",
        .or_1_2_xlarge_search = "or1.2xlarge.search",
        .or_1_4_xlarge_search = "or1.4xlarge.search",
        .or_1_8_xlarge_search = "or1.8xlarge.search",
        .or_1_12_xlarge_search = "or1.12xlarge.search",
        .or_1_16_xlarge_search = "or1.16xlarge.search",
        .ultrawarm_1_medium_search = "ultrawarm1.medium.search",
        .ultrawarm_1_large_search = "ultrawarm1.large.search",
        .ultrawarm_1_xlarge_search = "ultrawarm1.xlarge.search",
        .t_2_micro_search = "t2.micro.search",
        .t_2_small_search = "t2.small.search",
        .t_2_medium_search = "t2.medium.search",
        .r_3_large_search = "r3.large.search",
        .r_3_xlarge_search = "r3.xlarge.search",
        .r_3_2_xlarge_search = "r3.2xlarge.search",
        .r_3_4_xlarge_search = "r3.4xlarge.search",
        .r_3_8_xlarge_search = "r3.8xlarge.search",
        .i_2_xlarge_search = "i2.xlarge.search",
        .i_2_2_xlarge_search = "i2.2xlarge.search",
        .d_2_xlarge_search = "d2.xlarge.search",
        .d_2_2_xlarge_search = "d2.2xlarge.search",
        .d_2_4_xlarge_search = "d2.4xlarge.search",
        .d_2_8_xlarge_search = "d2.8xlarge.search",
        .c_4_large_search = "c4.large.search",
        .c_4_xlarge_search = "c4.xlarge.search",
        .c_4_2_xlarge_search = "c4.2xlarge.search",
        .c_4_4_xlarge_search = "c4.4xlarge.search",
        .c_4_8_xlarge_search = "c4.8xlarge.search",
        .r_4_large_search = "r4.large.search",
        .r_4_xlarge_search = "r4.xlarge.search",
        .r_4_2_xlarge_search = "r4.2xlarge.search",
        .r_4_4_xlarge_search = "r4.4xlarge.search",
        .r_4_8_xlarge_search = "r4.8xlarge.search",
        .r_4_16_xlarge_search = "r4.16xlarge.search",
        .i_3_large_search = "i3.large.search",
        .i_3_xlarge_search = "i3.xlarge.search",
        .i_3_2_xlarge_search = "i3.2xlarge.search",
        .i_3_4_xlarge_search = "i3.4xlarge.search",
        .i_3_8_xlarge_search = "i3.8xlarge.search",
        .i_3_16_xlarge_search = "i3.16xlarge.search",
        .r_6_g_large_search = "r6g.large.search",
        .r_6_g_xlarge_search = "r6g.xlarge.search",
        .r_6_g_2_xlarge_search = "r6g.2xlarge.search",
        .r_6_g_4_xlarge_search = "r6g.4xlarge.search",
        .r_6_g_8_xlarge_search = "r6g.8xlarge.search",
        .r_6_g_12_xlarge_search = "r6g.12xlarge.search",
        .m_6_g_large_search = "m6g.large.search",
        .m_6_g_xlarge_search = "m6g.xlarge.search",
        .m_6_g_2_xlarge_search = "m6g.2xlarge.search",
        .m_6_g_4_xlarge_search = "m6g.4xlarge.search",
        .m_6_g_8_xlarge_search = "m6g.8xlarge.search",
        .m_6_g_12_xlarge_search = "m6g.12xlarge.search",
        .c_6_g_large_search = "c6g.large.search",
        .c_6_g_xlarge_search = "c6g.xlarge.search",
        .c_6_g_2_xlarge_search = "c6g.2xlarge.search",
        .c_6_g_4_xlarge_search = "c6g.4xlarge.search",
        .c_6_g_8_xlarge_search = "c6g.8xlarge.search",
        .c_6_g_12_xlarge_search = "c6g.12xlarge.search",
        .r_6_gd_large_search = "r6gd.large.search",
        .r_6_gd_xlarge_search = "r6gd.xlarge.search",
        .r_6_gd_2_xlarge_search = "r6gd.2xlarge.search",
        .r_6_gd_4_xlarge_search = "r6gd.4xlarge.search",
        .r_6_gd_8_xlarge_search = "r6gd.8xlarge.search",
        .r_6_gd_12_xlarge_search = "r6gd.12xlarge.search",
        .r_6_gd_16_xlarge_search = "r6gd.16xlarge.search",
        .t_4_g_small_search = "t4g.small.search",
        .t_4_g_medium_search = "t4g.medium.search",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .m_3_medium_search => "m3.medium.search",
            .m_3_large_search => "m3.large.search",
            .m_3_xlarge_search => "m3.xlarge.search",
            .m_3_2_xlarge_search => "m3.2xlarge.search",
            .m_4_large_search => "m4.large.search",
            .m_4_xlarge_search => "m4.xlarge.search",
            .m_4_2_xlarge_search => "m4.2xlarge.search",
            .m_4_4_xlarge_search => "m4.4xlarge.search",
            .m_4_10_xlarge_search => "m4.10xlarge.search",
            .m_5_large_search => "m5.large.search",
            .m_5_xlarge_search => "m5.xlarge.search",
            .m_5_2_xlarge_search => "m5.2xlarge.search",
            .m_5_4_xlarge_search => "m5.4xlarge.search",
            .m_5_12_xlarge_search => "m5.12xlarge.search",
            .m_5_24_xlarge_search => "m5.24xlarge.search",
            .r_5_large_search => "r5.large.search",
            .r_5_xlarge_search => "r5.xlarge.search",
            .r_5_2_xlarge_search => "r5.2xlarge.search",
            .r_5_4_xlarge_search => "r5.4xlarge.search",
            .r_5_12_xlarge_search => "r5.12xlarge.search",
            .r_5_24_xlarge_search => "r5.24xlarge.search",
            .c_5_large_search => "c5.large.search",
            .c_5_xlarge_search => "c5.xlarge.search",
            .c_5_2_xlarge_search => "c5.2xlarge.search",
            .c_5_4_xlarge_search => "c5.4xlarge.search",
            .c_5_9_xlarge_search => "c5.9xlarge.search",
            .c_5_18_xlarge_search => "c5.18xlarge.search",
            .t_3_nano_search => "t3.nano.search",
            .t_3_micro_search => "t3.micro.search",
            .t_3_small_search => "t3.small.search",
            .t_3_medium_search => "t3.medium.search",
            .t_3_large_search => "t3.large.search",
            .t_3_xlarge_search => "t3.xlarge.search",
            .t_3_2_xlarge_search => "t3.2xlarge.search",
            .or_1_medium_search => "or1.medium.search",
            .or_1_large_search => "or1.large.search",
            .or_1_xlarge_search => "or1.xlarge.search",
            .or_1_2_xlarge_search => "or1.2xlarge.search",
            .or_1_4_xlarge_search => "or1.4xlarge.search",
            .or_1_8_xlarge_search => "or1.8xlarge.search",
            .or_1_12_xlarge_search => "or1.12xlarge.search",
            .or_1_16_xlarge_search => "or1.16xlarge.search",
            .ultrawarm_1_medium_search => "ultrawarm1.medium.search",
            .ultrawarm_1_large_search => "ultrawarm1.large.search",
            .ultrawarm_1_xlarge_search => "ultrawarm1.xlarge.search",
            .t_2_micro_search => "t2.micro.search",
            .t_2_small_search => "t2.small.search",
            .t_2_medium_search => "t2.medium.search",
            .r_3_large_search => "r3.large.search",
            .r_3_xlarge_search => "r3.xlarge.search",
            .r_3_2_xlarge_search => "r3.2xlarge.search",
            .r_3_4_xlarge_search => "r3.4xlarge.search",
            .r_3_8_xlarge_search => "r3.8xlarge.search",
            .i_2_xlarge_search => "i2.xlarge.search",
            .i_2_2_xlarge_search => "i2.2xlarge.search",
            .d_2_xlarge_search => "d2.xlarge.search",
            .d_2_2_xlarge_search => "d2.2xlarge.search",
            .d_2_4_xlarge_search => "d2.4xlarge.search",
            .d_2_8_xlarge_search => "d2.8xlarge.search",
            .c_4_large_search => "c4.large.search",
            .c_4_xlarge_search => "c4.xlarge.search",
            .c_4_2_xlarge_search => "c4.2xlarge.search",
            .c_4_4_xlarge_search => "c4.4xlarge.search",
            .c_4_8_xlarge_search => "c4.8xlarge.search",
            .r_4_large_search => "r4.large.search",
            .r_4_xlarge_search => "r4.xlarge.search",
            .r_4_2_xlarge_search => "r4.2xlarge.search",
            .r_4_4_xlarge_search => "r4.4xlarge.search",
            .r_4_8_xlarge_search => "r4.8xlarge.search",
            .r_4_16_xlarge_search => "r4.16xlarge.search",
            .i_3_large_search => "i3.large.search",
            .i_3_xlarge_search => "i3.xlarge.search",
            .i_3_2_xlarge_search => "i3.2xlarge.search",
            .i_3_4_xlarge_search => "i3.4xlarge.search",
            .i_3_8_xlarge_search => "i3.8xlarge.search",
            .i_3_16_xlarge_search => "i3.16xlarge.search",
            .r_6_g_large_search => "r6g.large.search",
            .r_6_g_xlarge_search => "r6g.xlarge.search",
            .r_6_g_2_xlarge_search => "r6g.2xlarge.search",
            .r_6_g_4_xlarge_search => "r6g.4xlarge.search",
            .r_6_g_8_xlarge_search => "r6g.8xlarge.search",
            .r_6_g_12_xlarge_search => "r6g.12xlarge.search",
            .m_6_g_large_search => "m6g.large.search",
            .m_6_g_xlarge_search => "m6g.xlarge.search",
            .m_6_g_2_xlarge_search => "m6g.2xlarge.search",
            .m_6_g_4_xlarge_search => "m6g.4xlarge.search",
            .m_6_g_8_xlarge_search => "m6g.8xlarge.search",
            .m_6_g_12_xlarge_search => "m6g.12xlarge.search",
            .c_6_g_large_search => "c6g.large.search",
            .c_6_g_xlarge_search => "c6g.xlarge.search",
            .c_6_g_2_xlarge_search => "c6g.2xlarge.search",
            .c_6_g_4_xlarge_search => "c6g.4xlarge.search",
            .c_6_g_8_xlarge_search => "c6g.8xlarge.search",
            .c_6_g_12_xlarge_search => "c6g.12xlarge.search",
            .r_6_gd_large_search => "r6gd.large.search",
            .r_6_gd_xlarge_search => "r6gd.xlarge.search",
            .r_6_gd_2_xlarge_search => "r6gd.2xlarge.search",
            .r_6_gd_4_xlarge_search => "r6gd.4xlarge.search",
            .r_6_gd_8_xlarge_search => "r6gd.8xlarge.search",
            .r_6_gd_12_xlarge_search => "r6gd.12xlarge.search",
            .r_6_gd_16_xlarge_search => "r6gd.16xlarge.search",
            .t_4_g_small_search => "t4g.small.search",
            .t_4_g_medium_search => "t4g.medium.search",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
