pub const OpenSearchPartitionInstanceType = enum {
    m_3_medium_search,
    m_3_large_search,
    m_3_xlarge_search,
    m_3_2_xlarge_search,
    m_4_large_search,
    m_4_xlarge_search,
    m_4_2_xlarge_search,
    m_4_4_xlarge_search,
    m_4_10_xlarge_search,
    m_5_large_search,
    m_5_xlarge_search,
    m_5_2_xlarge_search,
    m_5_4_xlarge_search,
    m_5_12_xlarge_search,
    m_5_24_xlarge_search,
    r_5_large_search,
    r_5_xlarge_search,
    r_5_2_xlarge_search,
    r_5_4_xlarge_search,
    r_5_12_xlarge_search,
    r_5_24_xlarge_search,
    c_5_large_search,
    c_5_xlarge_search,
    c_5_2_xlarge_search,
    c_5_4_xlarge_search,
    c_5_9_xlarge_search,
    c_5_18_xlarge_search,
    t_3_nano_search,
    t_3_micro_search,
    t_3_small_search,
    t_3_medium_search,
    t_3_large_search,
    t_3_xlarge_search,
    t_3_2_xlarge_search,
    or_1_medium_search,
    or_1_large_search,
    or_1_xlarge_search,
    or_1_2_xlarge_search,
    or_1_4_xlarge_search,
    or_1_8_xlarge_search,
    or_1_12_xlarge_search,
    or_1_16_xlarge_search,
    ultrawarm_1_medium_search,
    ultrawarm_1_large_search,
    ultrawarm_1_xlarge_search,
    t_2_micro_search,
    t_2_small_search,
    t_2_medium_search,
    r_3_large_search,
    r_3_xlarge_search,
    r_3_2_xlarge_search,
    r_3_4_xlarge_search,
    r_3_8_xlarge_search,
    i_2_xlarge_search,
    i_2_2_xlarge_search,
    d_2_xlarge_search,
    d_2_2_xlarge_search,
    d_2_4_xlarge_search,
    d_2_8_xlarge_search,
    c_4_large_search,
    c_4_xlarge_search,
    c_4_2_xlarge_search,
    c_4_4_xlarge_search,
    c_4_8_xlarge_search,
    r_4_large_search,
    r_4_xlarge_search,
    r_4_2_xlarge_search,
    r_4_4_xlarge_search,
    r_4_8_xlarge_search,
    r_4_16_xlarge_search,
    i_3_large_search,
    i_3_xlarge_search,
    i_3_2_xlarge_search,
    i_3_4_xlarge_search,
    i_3_8_xlarge_search,
    i_3_16_xlarge_search,
    r_6_g_large_search,
    r_6_g_xlarge_search,
    r_6_g_2_xlarge_search,
    r_6_g_4_xlarge_search,
    r_6_g_8_xlarge_search,
    r_6_g_12_xlarge_search,
    m_6_g_large_search,
    m_6_g_xlarge_search,
    m_6_g_2_xlarge_search,
    m_6_g_4_xlarge_search,
    m_6_g_8_xlarge_search,
    m_6_g_12_xlarge_search,
    c_6_g_large_search,
    c_6_g_xlarge_search,
    c_6_g_2_xlarge_search,
    c_6_g_4_xlarge_search,
    c_6_g_8_xlarge_search,
    c_6_g_12_xlarge_search,
    r_6_gd_large_search,
    r_6_gd_xlarge_search,
    r_6_gd_2_xlarge_search,
    r_6_gd_4_xlarge_search,
    r_6_gd_8_xlarge_search,
    r_6_gd_12_xlarge_search,
    r_6_gd_16_xlarge_search,
    t_4_g_small_search,
    t_4_g_medium_search,

    pub const json_field_names = .{
        .m_3_medium_search = "m3_medium_search",
        .m_3_large_search = "m3_large_search",
        .m_3_xlarge_search = "m3_xlarge_search",
        .m_3_2_xlarge_search = "m3_2xlarge_search",
        .m_4_large_search = "m4_large_search",
        .m_4_xlarge_search = "m4_xlarge_search",
        .m_4_2_xlarge_search = "m4_2xlarge_search",
        .m_4_4_xlarge_search = "m4_4xlarge_search",
        .m_4_10_xlarge_search = "m4_10xlarge_search",
        .m_5_large_search = "m5_large_search",
        .m_5_xlarge_search = "m5_xlarge_search",
        .m_5_2_xlarge_search = "m5_2xlarge_search",
        .m_5_4_xlarge_search = "m5_4xlarge_search",
        .m_5_12_xlarge_search = "m5_12xlarge_search",
        .m_5_24_xlarge_search = "m5_24xlarge_search",
        .r_5_large_search = "r5_large_search",
        .r_5_xlarge_search = "r5_xlarge_search",
        .r_5_2_xlarge_search = "r5_2xlarge_search",
        .r_5_4_xlarge_search = "r5_4xlarge_search",
        .r_5_12_xlarge_search = "r5_12xlarge_search",
        .r_5_24_xlarge_search = "r5_24xlarge_search",
        .c_5_large_search = "c5_large_search",
        .c_5_xlarge_search = "c5_xlarge_search",
        .c_5_2_xlarge_search = "c5_2xlarge_search",
        .c_5_4_xlarge_search = "c5_4xlarge_search",
        .c_5_9_xlarge_search = "c5_9xlarge_search",
        .c_5_18_xlarge_search = "c5_18xlarge_search",
        .t_3_nano_search = "t3_nano_search",
        .t_3_micro_search = "t3_micro_search",
        .t_3_small_search = "t3_small_search",
        .t_3_medium_search = "t3_medium_search",
        .t_3_large_search = "t3_large_search",
        .t_3_xlarge_search = "t3_xlarge_search",
        .t_3_2_xlarge_search = "t3_2xlarge_search",
        .or_1_medium_search = "or1_medium_search",
        .or_1_large_search = "or1_large_search",
        .or_1_xlarge_search = "or1_xlarge_search",
        .or_1_2_xlarge_search = "or1_2xlarge_search",
        .or_1_4_xlarge_search = "or1_4xlarge_search",
        .or_1_8_xlarge_search = "or1_8xlarge_search",
        .or_1_12_xlarge_search = "or1_12xlarge_search",
        .or_1_16_xlarge_search = "or1_16xlarge_search",
        .ultrawarm_1_medium_search = "ultrawarm1_medium_search",
        .ultrawarm_1_large_search = "ultrawarm1_large_search",
        .ultrawarm_1_xlarge_search = "ultrawarm1_xlarge_search",
        .t_2_micro_search = "t2_micro_search",
        .t_2_small_search = "t2_small_search",
        .t_2_medium_search = "t2_medium_search",
        .r_3_large_search = "r3_large_search",
        .r_3_xlarge_search = "r3_xlarge_search",
        .r_3_2_xlarge_search = "r3_2xlarge_search",
        .r_3_4_xlarge_search = "r3_4xlarge_search",
        .r_3_8_xlarge_search = "r3_8xlarge_search",
        .i_2_xlarge_search = "i2_xlarge_search",
        .i_2_2_xlarge_search = "i2_2xlarge_search",
        .d_2_xlarge_search = "d2_xlarge_search",
        .d_2_2_xlarge_search = "d2_2xlarge_search",
        .d_2_4_xlarge_search = "d2_4xlarge_search",
        .d_2_8_xlarge_search = "d2_8xlarge_search",
        .c_4_large_search = "c4_large_search",
        .c_4_xlarge_search = "c4_xlarge_search",
        .c_4_2_xlarge_search = "c4_2xlarge_search",
        .c_4_4_xlarge_search = "c4_4xlarge_search",
        .c_4_8_xlarge_search = "c4_8xlarge_search",
        .r_4_large_search = "r4_large_search",
        .r_4_xlarge_search = "r4_xlarge_search",
        .r_4_2_xlarge_search = "r4_2xlarge_search",
        .r_4_4_xlarge_search = "r4_4xlarge_search",
        .r_4_8_xlarge_search = "r4_8xlarge_search",
        .r_4_16_xlarge_search = "r4_16xlarge_search",
        .i_3_large_search = "i3_large_search",
        .i_3_xlarge_search = "i3_xlarge_search",
        .i_3_2_xlarge_search = "i3_2xlarge_search",
        .i_3_4_xlarge_search = "i3_4xlarge_search",
        .i_3_8_xlarge_search = "i3_8xlarge_search",
        .i_3_16_xlarge_search = "i3_16xlarge_search",
        .r_6_g_large_search = "r6g_large_search",
        .r_6_g_xlarge_search = "r6g_xlarge_search",
        .r_6_g_2_xlarge_search = "r6g_2xlarge_search",
        .r_6_g_4_xlarge_search = "r6g_4xlarge_search",
        .r_6_g_8_xlarge_search = "r6g_8xlarge_search",
        .r_6_g_12_xlarge_search = "r6g_12xlarge_search",
        .m_6_g_large_search = "m6g_large_search",
        .m_6_g_xlarge_search = "m6g_xlarge_search",
        .m_6_g_2_xlarge_search = "m6g_2xlarge_search",
        .m_6_g_4_xlarge_search = "m6g_4xlarge_search",
        .m_6_g_8_xlarge_search = "m6g_8xlarge_search",
        .m_6_g_12_xlarge_search = "m6g_12xlarge_search",
        .c_6_g_large_search = "c6g_large_search",
        .c_6_g_xlarge_search = "c6g_xlarge_search",
        .c_6_g_2_xlarge_search = "c6g_2xlarge_search",
        .c_6_g_4_xlarge_search = "c6g_4xlarge_search",
        .c_6_g_8_xlarge_search = "c6g_8xlarge_search",
        .c_6_g_12_xlarge_search = "c6g_12xlarge_search",
        .r_6_gd_large_search = "r6gd_large_search",
        .r_6_gd_xlarge_search = "r6gd_xlarge_search",
        .r_6_gd_2_xlarge_search = "r6gd_2xlarge_search",
        .r_6_gd_4_xlarge_search = "r6gd_4xlarge_search",
        .r_6_gd_8_xlarge_search = "r6gd_8xlarge_search",
        .r_6_gd_12_xlarge_search = "r6gd_12xlarge_search",
        .r_6_gd_16_xlarge_search = "r6gd_16xlarge_search",
        .t_4_g_small_search = "t4g_small_search",
        .t_4_g_medium_search = "t4g_medium_search",
    };
};
