const ReplicationTaskAssessmentRunProgress = @import("replication_task_assessment_run_progress.zig").ReplicationTaskAssessmentRunProgress;
const ReplicationTaskAssessmentRunResultStatistic = @import("replication_task_assessment_run_result_statistic.zig").ReplicationTaskAssessmentRunResultStatistic;

/// The results returned in `describe-replications` to display the results of
/// the
/// premigration assessment from the replication configuration.
pub const PremigrationAssessmentStatus = struct {
    assessment_progress: ?ReplicationTaskAssessmentRunProgress = null,

    /// A configurable setting you can set to `true` (the defualt setting) or
    /// `false`. Use this setting to to stop the replication from starting
    /// automatically if the assessment fails. This can help you evaluate the issue
    /// that is
    /// preventing the replication from running successfully.
    fail_on_assessment_failure: bool = false,

    /// The last message generated by an individual assessment failure.
    last_failure_message: ?[]const u8 = null,

    /// The Amazon Resource Name (ARN) of this assessment run.
    premigration_assessment_run_arn: ?[]const u8 = null,

    /// The date which the assessment run was created.
    premigration_assessment_run_creation_date: ?i64 = null,

    /// The supported values are `SSE_KMS` and `SSE_S3`. If these values
    /// are not provided, then the files are not encrypted at rest. For more
    /// information, see
    /// [Creating Amazon Web Services KMS
    /// keys to encrypt Amazon S3 target
    /// objects](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.KMSKeys).
    result_encryption_mode: ?[]const u8 = null,

    /// The ARN of a custom KMS encryption key that you specify when you set
    /// `ResultEncryptionMode` to `SSE_KMS`.
    result_kms_key_arn: ?[]const u8 = null,

    /// The Amazon S3 bucket that Database Migration Service Serverless created to
    /// store the results of this
    /// assessment run.
    result_location_bucket: ?[]const u8 = null,

    /// The folder within an Amazon S3 bucket where you want Database Migration
    /// Service to store the results of
    /// this assessment run.
    result_location_folder: ?[]const u8 = null,

    result_statistic: ?ReplicationTaskAssessmentRunResultStatistic = null,

    /// This describes the assessment run status. The status can be one of the
    /// following
    /// values:
    ///
    /// * `cancelling`: The assessment run was canceled.
    ///
    /// * `deleting`: The assessment run was deleted.
    ///
    /// * `failed`: At least one individual assessment completed with a failed
    /// status.
    ///
    /// * `error-provisioning`: An internal error occurred while resources were
    /// provisioned (during the `provisioning` status).
    ///
    /// * `error-executing` An internal error occurred while individual
    /// assessments ran (during the `running` status).
    ///
    /// * `invalid state`: The assessment run is in an unknown state.
    ///
    /// * `passed`: All individual assessments have completed and none have a
    /// failed status.
    ///
    /// * `provisioning`: The resources required to run individual assessments
    /// are being provisioned.
    ///
    /// * `running`: Individual assessments are being run.
    ///
    /// * `starting`: The assessment run is starting, but resources are not yet
    /// being provisioned for individual assessments.
    ///
    /// * `warning`: At least one individual assessment completed with a warning
    /// status.
    status: ?[]const u8 = null,

    pub const json_field_names = .{
        .assessment_progress = "AssessmentProgress",
        .fail_on_assessment_failure = "FailOnAssessmentFailure",
        .last_failure_message = "LastFailureMessage",
        .premigration_assessment_run_arn = "PremigrationAssessmentRunArn",
        .premigration_assessment_run_creation_date = "PremigrationAssessmentRunCreationDate",
        .result_encryption_mode = "ResultEncryptionMode",
        .result_kms_key_arn = "ResultKmsKeyArn",
        .result_location_bucket = "ResultLocationBucket",
        .result_location_folder = "ResultLocationFolder",
        .result_statistic = "ResultStatistic",
        .status = "Status",
    };
};
