pub const VocabularyLanguageCode = enum {
    ar_ae,
    de_ch,
    de_de,
    en_ab,
    en_au,
    en_gb,
    en_ie,
    en_in,
    en_us,
    en_wl,
    es_es,
    es_us,
    fr_ca,
    fr_fr,
    hi_in,
    it_it,
    ja_jp,
    ko_kr,
    pt_br,
    pt_pt,
    zh_cn,
    en_nz,
    en_za,
    ca_es,
    da_dk,
    fi_fi,
    id_id,
    ms_my,
    nl_nl,
    no_no,
    pl_pl,
    sv_se,
    tl_ph,

    pub const json_field_names = .{
        .ar_ae = "AR_AE",
        .de_ch = "DE_CH",
        .de_de = "DE_DE",
        .en_ab = "EN_AB",
        .en_au = "EN_AU",
        .en_gb = "EN_GB",
        .en_ie = "EN_IE",
        .en_in = "EN_IN",
        .en_us = "EN_US",
        .en_wl = "EN_WL",
        .es_es = "ES_ES",
        .es_us = "ES_US",
        .fr_ca = "FR_CA",
        .fr_fr = "FR_FR",
        .hi_in = "HI_IN",
        .it_it = "IT_IT",
        .ja_jp = "JA_JP",
        .ko_kr = "KO_KR",
        .pt_br = "PT_BR",
        .pt_pt = "PT_PT",
        .zh_cn = "ZH_CN",
        .en_nz = "EN_NZ",
        .en_za = "EN_ZA",
        .ca_es = "CA_ES",
        .da_dk = "DA_DK",
        .fi_fi = "FI_FI",
        .id_id = "ID_ID",
        .ms_my = "MS_MY",
        .nl_nl = "NL_NL",
        .no_no = "NO_NO",
        .pl_pl = "PL_PL",
        .sv_se = "SV_SE",
        .tl_ph = "TL_PH",
    };
};
