const std = @import("std");

pub const VocabularyLanguageCode = enum {
    ar_ae,
    de_ch,
    de_de,
    en_ab,
    en_au,
    en_gb,
    en_ie,
    en_in,
    en_us,
    en_wl,
    es_es,
    es_us,
    fr_ca,
    fr_fr,
    hi_in,
    it_it,
    ja_jp,
    ko_kr,
    pt_br,
    pt_pt,
    zh_cn,
    en_nz,
    en_za,
    ca_es,
    da_dk,
    fi_fi,
    id_id,
    ms_my,
    nl_nl,
    no_no,
    pl_pl,
    sv_se,
    tl_ph,

    pub const json_field_names = .{
        .ar_ae = "ar-AE",
        .de_ch = "de-CH",
        .de_de = "de-DE",
        .en_ab = "en-AB",
        .en_au = "en-AU",
        .en_gb = "en-GB",
        .en_ie = "en-IE",
        .en_in = "en-IN",
        .en_us = "en-US",
        .en_wl = "en-WL",
        .es_es = "es-ES",
        .es_us = "es-US",
        .fr_ca = "fr-CA",
        .fr_fr = "fr-FR",
        .hi_in = "hi-IN",
        .it_it = "it-IT",
        .ja_jp = "ja-JP",
        .ko_kr = "ko-KR",
        .pt_br = "pt-BR",
        .pt_pt = "pt-PT",
        .zh_cn = "zh-CN",
        .en_nz = "en-NZ",
        .en_za = "en-ZA",
        .ca_es = "ca-ES",
        .da_dk = "da-DK",
        .fi_fi = "fi-FI",
        .id_id = "id-ID",
        .ms_my = "ms-MY",
        .nl_nl = "nl-NL",
        .no_no = "no-NO",
        .pl_pl = "pl-PL",
        .sv_se = "sv-SE",
        .tl_ph = "tl-PH",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .ar_ae => "ar-AE",
            .de_ch => "de-CH",
            .de_de => "de-DE",
            .en_ab => "en-AB",
            .en_au => "en-AU",
            .en_gb => "en-GB",
            .en_ie => "en-IE",
            .en_in => "en-IN",
            .en_us => "en-US",
            .en_wl => "en-WL",
            .es_es => "es-ES",
            .es_us => "es-US",
            .fr_ca => "fr-CA",
            .fr_fr => "fr-FR",
            .hi_in => "hi-IN",
            .it_it => "it-IT",
            .ja_jp => "ja-JP",
            .ko_kr => "ko-KR",
            .pt_br => "pt-BR",
            .pt_pt => "pt-PT",
            .zh_cn => "zh-CN",
            .en_nz => "en-NZ",
            .en_za => "en-ZA",
            .ca_es => "ca-ES",
            .da_dk => "da-DK",
            .fi_fi => "fi-FI",
            .id_id => "id-ID",
            .ms_my => "ms-MY",
            .nl_nl => "nl-NL",
            .no_no => "no-NO",
            .pl_pl => "pl-PL",
            .sv_se => "sv-SE",
            .tl_ph => "tl-PH",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
