pub const Category = enum {
    cults,
    gambling,
    nudity,
    pornography,
    sex_education,
    tasteless,
    violence,
    download_sites,
    image_sharing,
    peer_to_peer,
    streaming_media_and_downloads,
    generative_ai,
    criminal_activity,
    hacking,
    hate_and_intolerance,
    illegal_drug,
    illegal_software,
    school_cheating,
    self_harm,
    weapons,
    chat,
    games,
    instant_messaging,
    professional_network,
    social_networking,
    web_based_email,
    parked_domains,

    pub const json_field_names = .{
        .cults = "CULTS",
        .gambling = "GAMBLING",
        .nudity = "NUDITY",
        .pornography = "PORNOGRAPHY",
        .sex_education = "SEX_EDUCATION",
        .tasteless = "TASTELESS",
        .violence = "VIOLENCE",
        .download_sites = "DOWNLOAD_SITES",
        .image_sharing = "IMAGE_SHARING",
        .peer_to_peer = "PEER_TO_PEER",
        .streaming_media_and_downloads = "STREAMING_MEDIA_AND_DOWNLOADS",
        .generative_ai = "GENERATIVE_AI",
        .criminal_activity = "CRIMINAL_ACTIVITY",
        .hacking = "HACKING",
        .hate_and_intolerance = "HATE_AND_INTOLERANCE",
        .illegal_drug = "ILLEGAL_DRUG",
        .illegal_software = "ILLEGAL_SOFTWARE",
        .school_cheating = "SCHOOL_CHEATING",
        .self_harm = "SELF_HARM",
        .weapons = "WEAPONS",
        .chat = "CHAT",
        .games = "GAMES",
        .instant_messaging = "INSTANT_MESSAGING",
        .professional_network = "PROFESSIONAL_NETWORK",
        .social_networking = "SOCIAL_NETWORKING",
        .web_based_email = "WEB_BASED_EMAIL",
        .parked_domains = "PARKED_DOMAINS",
    };
};
