const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const InlineRedactionConfiguration = @import("inline_redaction_configuration.zig").InlineRedactionConfiguration;
const Tag = @import("tag.zig").Tag;

pub const CreateDataProtectionSettingsInput = struct {
    /// Additional encryption context of the data protection settings.
    additional_encryption_context: ?[]const aws.map.StringMapEntry = null,

    /// A unique, case-sensitive identifier that you provide to ensure the
    /// idempotency of the request. Idempotency ensures that an API request
    /// completes only once. With an idempotent request, if the original request
    /// completes successfully, subsequent retries with the same client token
    /// returns the result from the original successful request.
    ///
    /// If you do not specify a client token, one is automatically generated by the
    /// Amazon Web Services SDK.
    client_token: ?[]const u8 = null,

    /// The custom managed key of the data protection settings.
    customer_managed_key: ?[]const u8 = null,

    /// The description of the data protection settings.
    description: ?[]const u8 = null,

    /// The display name of the data protection settings.
    display_name: ?[]const u8 = null,

    /// The inline redaction configuration of the data protection settings that will
    /// be applied to all sessions.
    inline_redaction_configuration: ?InlineRedactionConfiguration = null,

    /// The tags to add to the data protection settings resource. A tag is a
    /// key-value pair.
    tags: ?[]const Tag = null,

    pub const json_field_names = .{
        .additional_encryption_context = "additionalEncryptionContext",
        .client_token = "clientToken",
        .customer_managed_key = "customerManagedKey",
        .description = "description",
        .display_name = "displayName",
        .inline_redaction_configuration = "inlineRedactionConfiguration",
        .tags = "tags",
    };
};

pub const CreateDataProtectionSettingsOutput = struct {
    /// The ARN of the data protection settings resource.
    data_protection_settings_arn: []const u8,

    pub const json_field_names = .{
        .data_protection_settings_arn = "dataProtectionSettingsArn",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateDataProtectionSettingsInput, options: CallOptions) !CreateDataProtectionSettingsOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "workspaces-web", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateDataProtectionSettingsInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("workspaces-web", "WorkSpaces Web", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/dataProtectionSettings";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.additional_encryption_context) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"additionalEncryptionContext\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.client_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"clientToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.customer_managed_key) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"customerManagedKey\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.description) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"description\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.display_name) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"displayName\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.inline_redaction_configuration) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"inlineRedactionConfiguration\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.tags) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"tags\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateDataProtectionSettingsOutput {
    const result: CreateDataProtectionSettingsOutput = try aws.json.parseJsonObject(
        CreateDataProtectionSettingsOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
