const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const AuthenticationType = @import("authentication_type.zig").AuthenticationType;
const InstanceType = @import("instance_type.zig").InstanceType;
const Tag = @import("tag.zig").Tag;

pub const CreatePortalInput = struct {
    /// The additional encryption context of the portal.
    additional_encryption_context: ?[]const aws.map.StringMapEntry = null,

    /// The type of authentication integration points used when signing into the web
    /// portal. Defaults to `Standard`.
    ///
    /// `Standard` web portals are authenticated directly through your identity
    /// provider. You need to call `CreateIdentityProvider` to integrate your
    /// identity provider with your web portal. User and group access to your web
    /// portal is controlled through your identity provider.
    ///
    /// `IAM Identity Center` web portals are authenticated through IAM Identity
    /// Center. Identity sources (including external identity provider integration),
    /// plus user and group access to your web portal, can be configured in the IAM
    /// Identity Center.
    authentication_type: ?AuthenticationType = null,

    /// A unique, case-sensitive identifier that you provide to ensure the
    /// idempotency of the request. Idempotency ensures that an API request
    /// completes only once. With an idempotent request, if the original request
    /// completes successfully, subsequent retries with the same client token
    /// returns the result from the original successful request.
    ///
    /// If you do not specify a client token, one is automatically generated by the
    /// Amazon Web Services SDK.
    client_token: ?[]const u8 = null,

    /// The customer managed key of the web portal.
    customer_managed_key: ?[]const u8 = null,

    /// The name of the web portal. This is not visible to users who log into the
    /// web portal.
    display_name: ?[]const u8 = null,

    /// The type and resources of the underlying instance.
    instance_type: ?InstanceType = null,

    /// The maximum number of concurrent sessions for the portal.
    max_concurrent_sessions: ?i32 = null,

    /// The custom domain of the web portal that users access in order to start
    /// streaming sessions.
    portal_custom_domain: ?[]const u8 = null,

    /// The tags to add to the web portal. A tag is a key-value pair.
    tags: ?[]const Tag = null,

    pub const json_field_names = .{
        .additional_encryption_context = "additionalEncryptionContext",
        .authentication_type = "authenticationType",
        .client_token = "clientToken",
        .customer_managed_key = "customerManagedKey",
        .display_name = "displayName",
        .instance_type = "instanceType",
        .max_concurrent_sessions = "maxConcurrentSessions",
        .portal_custom_domain = "portalCustomDomain",
        .tags = "tags",
    };
};

pub const CreatePortalOutput = struct {
    /// The ARN of the web portal.
    portal_arn: []const u8,

    /// The endpoint URL of the web portal that users access in order to start
    /// streaming sessions.
    portal_endpoint: []const u8,

    pub const json_field_names = .{
        .portal_arn = "portalArn",
        .portal_endpoint = "portalEndpoint",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreatePortalInput, options: CallOptions) !CreatePortalOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "workspaces-web", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreatePortalInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("workspaces-web", "WorkSpaces Web", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/portals";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.additional_encryption_context) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"additionalEncryptionContext\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.authentication_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"authenticationType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.client_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"clientToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.customer_managed_key) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"customerManagedKey\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.display_name) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"displayName\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.instance_type) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"instanceType\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.max_concurrent_sessions) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"maxConcurrentSessions\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.portal_custom_domain) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"portalCustomDomain\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.tags) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"tags\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreatePortalOutput {
    const result: CreatePortalOutput = try aws.json.parseJsonObject(
        CreatePortalOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
