const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Tag = @import("tag.zig").Tag;
const WebContentFilteringPolicy = @import("web_content_filtering_policy.zig").WebContentFilteringPolicy;

pub const CreateBrowserSettingsInput = struct {
    /// Additional encryption context of the browser settings.
    additional_encryption_context: ?[]const aws.map.StringMapEntry = null,

    /// A JSON string containing Chrome Enterprise policies that will be applied to
    /// all streaming sessions.
    browser_policy: ?[]const u8 = null,

    /// A unique, case-sensitive identifier that you provide to ensure the
    /// idempotency of the request. Idempotency ensures that an API request
    /// completes only once. With an idempotent request, if the original request
    /// completes successfully, subsequent retries with the same client token
    /// returns the result from the original successful request.
    ///
    /// If you do not specify a client token, one is automatically generated by the
    /// Amazon Web Services SDK.
    client_token: ?[]const u8 = null,

    /// The custom managed key of the browser settings.
    customer_managed_key: ?[]const u8 = null,

    /// The tags to add to the browser settings resource. A tag is a key-value pair.
    tags: ?[]const Tag = null,

    /// The policy that specifies which URLs end users are allowed to access or
    /// which URLs or domain categories they are restricted from accessing for
    /// enhanced security.
    web_content_filtering_policy: ?WebContentFilteringPolicy = null,

    pub const json_field_names = .{
        .additional_encryption_context = "additionalEncryptionContext",
        .browser_policy = "browserPolicy",
        .client_token = "clientToken",
        .customer_managed_key = "customerManagedKey",
        .tags = "tags",
        .web_content_filtering_policy = "webContentFilteringPolicy",
    };
};

pub const CreateBrowserSettingsOutput = struct {
    /// The ARN of the browser settings.
    browser_settings_arn: []const u8,

    pub const json_field_names = .{
        .browser_settings_arn = "browserSettingsArn",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateBrowserSettingsInput, options: CallOptions) !CreateBrowserSettingsOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "workspaces-web", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateBrowserSettingsInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("workspaces-web", "WorkSpaces Web", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/browserSettings";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.additional_encryption_context) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"additionalEncryptionContext\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.browser_policy) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"browserPolicy\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.client_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"clientToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.customer_managed_key) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"customerManagedKey\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.tags) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"tags\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.web_content_filtering_policy) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"webContentFilteringPolicy\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateBrowserSettingsOutput {
    var result: CreateBrowserSettingsOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(CreateBrowserSettingsOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}
