const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const ServiceError = @import("errors.zig").ServiceError;
const IdentityProviderType = @import("identity_provider_type.zig").IdentityProviderType;
const Tag = @import("tag.zig").Tag;

pub const CreateIdentityProviderInput = struct {
    /// A unique, case-sensitive identifier that you provide to ensure the
    /// idempotency of the request. Idempotency ensures that an API request
    /// completes only once. With an idempotent request, if the original request
    /// completes successfully, subsequent retries with the same client token
    /// returns the result from the original successful request.
    ///
    /// If you do not specify a client token, one is automatically generated by the
    /// Amazon Web Services SDK.
    client_token: ?[]const u8 = null,

    /// The identity provider details. The following list describes the provider
    /// detail keys for each identity provider type.
    ///
    /// * For Google and Login with Amazon:
    ///
    /// * `client_id`
    /// * `client_secret`
    /// * `authorize_scopes`
    ///
    /// * For Facebook:
    ///
    /// * `client_id`
    /// * `client_secret`
    /// * `authorize_scopes`
    /// * `api_version`
    ///
    /// * For Sign in with Apple:
    ///
    /// * `client_id`
    /// * `team_id`
    /// * `key_id`
    /// * `private_key`
    /// * `authorize_scopes`
    ///
    /// * For OIDC providers:
    ///
    /// * `client_id`
    /// * `client_secret`
    /// * `attributes_request_method`
    /// * `oidc_issuer`
    /// * `authorize_scopes`
    /// * `authorize_url` *if not available from discovery URL specified by
    ///   `oidc_issuer` key*
    /// * `token_url` *if not available from discovery URL specified by
    ///   `oidc_issuer` key*
    /// * `attributes_url` *if not available from discovery URL specified by
    ///   `oidc_issuer` key*
    /// * `jwks_uri` *if not available from discovery URL specified by `oidc_issuer`
    ///   key*
    ///
    /// * For SAML providers:
    ///
    /// * `MetadataFile` OR `MetadataURL`
    /// * `IDPSignout` (boolean) *optional*
    /// * `IDPInit` (boolean) *optional*
    /// * `RequestSigningAlgorithm` (string) *optional* - Only accepts `rsa-sha256`
    /// * `EncryptedResponses` (boolean) *optional*
    identity_provider_details: []const aws.map.StringMapEntry,

    /// The identity provider name.
    identity_provider_name: []const u8,

    /// The identity provider type.
    identity_provider_type: IdentityProviderType,

    /// The ARN of the web portal.
    portal_arn: []const u8,

    /// The tags to add to the identity provider resource. A tag is a key-value
    /// pair.
    tags: ?[]const Tag = null,

    pub const json_field_names = .{
        .client_token = "clientToken",
        .identity_provider_details = "identityProviderDetails",
        .identity_provider_name = "identityProviderName",
        .identity_provider_type = "identityProviderType",
        .portal_arn = "portalArn",
        .tags = "tags",
    };
};

pub const CreateIdentityProviderOutput = struct {
    /// The ARN of the identity provider.
    identity_provider_arn: []const u8,

    pub const json_field_names = .{
        .identity_provider_arn = "identityProviderArn",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateIdentityProviderInput, options: CallOptions) !CreateIdentityProviderOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "workspaces-web");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateIdentityProviderInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("workspaces-web", "WorkSpaces Web", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    const path = "/identityProviders";

    var body_buf: std.ArrayList(u8) = .{};
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.client_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"clientToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"identityProviderDetails\":");
    try aws.json.writeValue(@TypeOf(input.identity_provider_details), input.identity_provider_details, allocator, &body_buf);
    has_prev = true;
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"identityProviderName\":");
    try aws.json.writeValue(@TypeOf(input.identity_provider_name), input.identity_provider_name, allocator, &body_buf);
    has_prev = true;
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"identityProviderType\":");
    try aws.json.writeValue(@TypeOf(input.identity_provider_type), input.identity_provider_type, allocator, &body_buf);
    has_prev = true;
    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"portalArn\":");
    try aws.json.writeValue(@TypeOf(input.portal_arn), input.portal_arn, allocator, &body_buf);
    has_prev = true;
    if (input.tags) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"tags\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(host);
    request.method = .POST;
    request.path = path;
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateIdentityProviderOutput {
    var result: CreateIdentityProviderOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(CreateIdentityProviderOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AccessDeniedException")) {
        return .{ .arena = arena, .kind = .{ .access_denied_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConflictException")) {
        return .{ .arena = arena, .kind = .{ .conflict_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InternalServerException")) {
        return .{ .arena = arena, .kind = .{ .internal_server_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .resource_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ServiceQuotaExceededException")) {
        return .{ .arena = arena, .kind = .{ .service_quota_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ThrottlingException")) {
        return .{ .arena = arena, .kind = .{ .throttling_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "TooManyTagsException")) {
        return .{ .arena = arena, .kind = .{ .too_many_tags_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ValidationException")) {
        return .{ .arena = arena, .kind = .{ .validation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
