pub const Event = enum {
    website_interact,
    file_download_from_secure_browser_to_remote_disk,
    file_transfer_from_remote_to_local_disk,
    file_transfer_from_local_to_remote_disk,
    file_upload_from_remote_disk_to_secure_browser,
    content_paste_to_website,
    content_transfer_from_local_to_remote_clipboard,
    content_copy_from_website,
    url_load,
    tab_open,
    tab_close,
    print_job_submit,
    session_connect,
    session_start,
    session_disconnect,
    session_end,
    url_block_by_content_filter,

    pub const json_field_names = .{
        .website_interact = "WEBSITE_INTERACT",
        .file_download_from_secure_browser_to_remote_disk = "FILE_DOWNLOAD_FROM_SECURE_BROWSER_TO_REMOTE_DISK",
        .file_transfer_from_remote_to_local_disk = "FILE_TRANSFER_FROM_REMOTE_TO_LOCAL_DISK",
        .file_transfer_from_local_to_remote_disk = "FILE_TRANSFER_FROM_LOCAL_TO_REMOTE_DISK",
        .file_upload_from_remote_disk_to_secure_browser = "FILE_UPLOAD_FROM_REMOTE_DISK_TO_SECURE_BROWSER",
        .content_paste_to_website = "CONTENT_PASTE_TO_WEBSITE",
        .content_transfer_from_local_to_remote_clipboard = "CONTENT_TRANSFER_FROM_LOCAL_TO_REMOTE_CLIPBOARD",
        .content_copy_from_website = "CONTENT_COPY_FROM_WEBSITE",
        .url_load = "URL_LOAD",
        .tab_open = "TAB_OPEN",
        .tab_close = "TAB_CLOSE",
        .print_job_submit = "PRINT_JOB_SUBMIT",
        .session_connect = "SESSION_CONNECT",
        .session_start = "SESSION_START",
        .session_disconnect = "SESSION_DISCONNECT",
        .session_end = "SESSION_END",
        .url_block_by_content_filter = "URL_BLOCK_BY_CONTENT_FILTER",
    };
};
