const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const WebContentFilteringPolicy = @import("web_content_filtering_policy.zig").WebContentFilteringPolicy;
const BrowserSettings = @import("browser_settings.zig").BrowserSettings;

pub const UpdateBrowserSettingsInput = struct {
    /// A JSON string containing Chrome Enterprise policies that will be applied to
    /// all streaming sessions.
    browser_policy: ?[]const u8 = null,

    /// The ARN of the browser settings.
    browser_settings_arn: []const u8,

    /// A unique, case-sensitive identifier that you provide to ensure the
    /// idempotency of the request. Idempotency ensures that an API request
    /// completes only once. With an idempotent request, if the original request
    /// completes successfully, subsequent retries with the same client token return
    /// the result from the original successful request.
    ///
    /// If you do not specify a client token, one is automatically generated by the
    /// Amazon Web Services SDK.
    client_token: ?[]const u8 = null,

    /// The policy that specifies which URLs end users are allowed to access or
    /// which URLs or domain categories they are restricted from accessing for
    /// enhanced security.
    web_content_filtering_policy: ?WebContentFilteringPolicy = null,

    pub const json_field_names = .{
        .browser_policy = "browserPolicy",
        .browser_settings_arn = "browserSettingsArn",
        .client_token = "clientToken",
        .web_content_filtering_policy = "webContentFilteringPolicy",
    };
};

pub const UpdateBrowserSettingsOutput = struct {
    /// The browser settings.
    browser_settings: ?BrowserSettings = null,

    pub const json_field_names = .{
        .browser_settings = "browserSettings",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: UpdateBrowserSettingsInput, options: CallOptions) !UpdateBrowserSettingsOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "workspaces-web", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: UpdateBrowserSettingsInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("workspaces-web", "WorkSpaces Web", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/browserSettings/");
    try path_buf.appendSlice(allocator, input.browser_settings_arn);
    const path = try path_buf.toOwnedSlice(allocator);

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (input.browser_policy) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"browserPolicy\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.client_token) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"clientToken\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.web_content_filtering_policy) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"webContentFilteringPolicy\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .PATCH;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !UpdateBrowserSettingsOutput {
    var result: UpdateBrowserSettingsOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(UpdateBrowserSettingsOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}
