const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const DataLakeConfiguration = @import("data_lake_configuration.zig").DataLakeConfiguration;
const DataLakeResource = @import("data_lake_resource.zig").DataLakeResource;

pub const UpdateDataLakeInput = struct {
    /// Specifies the Region or Regions that will contribute data to the rollup
    /// region.
    configurations: []const DataLakeConfiguration,

    /// The Amazon Resource Name (ARN) used to create and update the Glue table.
    /// This table contains partitions generated by the ingestion and normalization
    /// of
    /// Amazon Web Services log sources and custom sources.
    meta_store_manager_role_arn: ?[]const u8 = null,

    pub const json_field_names = .{
        .configurations = "configurations",
        .meta_store_manager_role_arn = "metaStoreManagerRoleArn",
    };
};

pub const UpdateDataLakeOutput = struct {
    /// The created Security Lake configuration object.
    data_lakes: ?[]const DataLakeResource = null,

    pub const json_field_names = .{
        .data_lakes = "dataLakes",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: UpdateDataLakeInput, options: CallOptions) !UpdateDataLakeOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "securitylake", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: UpdateDataLakeInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("securitylake", "SecurityLake", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/v1/datalake";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"configurations\":");
    try aws.json.writeValue(@TypeOf(input.configurations), input.configurations, allocator, &body_buf);
    has_prev = true;
    if (input.meta_store_manager_role_arn) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"metaStoreManagerRoleArn\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .PUT;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !UpdateDataLakeOutput {
    const result: UpdateDataLakeOutput = try aws.json.parseJsonObject(
        UpdateDataLakeOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
