pub const GroupByField = enum {
    activity_name,
    cloud_account_uid,
    cloud_provider,
    cloud_region,
    compliance_assessments_name,
    compliance_status,
    compliance_control,
    finding_info_title,
    finding_info_related_events_traits_category,
    finding_info_types,
    metadata_product_name,
    metadata_product_uid,
    resources_type,
    resources_uid,
    severity,
    status,
    vulnerabilities_fix_coverage,
    class_name,
    vulnerabilities_affected_packages_name,
    finding_info_analytic_name,
    compliance_standards,
    cloud_account_name,
    vendor_attributes_severity,

    pub const json_field_names = .{
        .activity_name = "ACTIVITY_NAME",
        .cloud_account_uid = "CLOUD_ACCOUNT_UID",
        .cloud_provider = "CLOUD_PROVIDER",
        .cloud_region = "CLOUD_REGION",
        .compliance_assessments_name = "COMPLIANCE_ASSESSMENTS_NAME",
        .compliance_status = "COMPLIANCE_STATUS",
        .compliance_control = "COMPLIANCE_CONTROL",
        .finding_info_title = "FINDING_INFO_TITLE",
        .finding_info_related_events_traits_category = "FINDING_INFO_RELATED_EVENTS_TRAITS_CATEGORY",
        .finding_info_types = "FINDING_INFO_TYPES",
        .metadata_product_name = "METADATA_PRODUCT_NAME",
        .metadata_product_uid = "METADATA_PRODUCT_UID",
        .resources_type = "RESOURCES_TYPE",
        .resources_uid = "RESOURCES_UID",
        .severity = "SEVERITY",
        .status = "STATUS",
        .vulnerabilities_fix_coverage = "VULNERABILITIES_FIX_COVERAGE",
        .class_name = "CLASS_NAME",
        .vulnerabilities_affected_packages_name = "VULNERABILITIES_AFFECTED_PACKAGES_NAME",
        .finding_info_analytic_name = "FINDING_INFO_ANALYTIC_NAME",
        .compliance_standards = "COMPLIANCE_STANDARDS",
        .cloud_account_name = "CLOUD_ACCOUNT_NAME",
        .vendor_attributes_severity = "VENDOR_ATTRIBUTES_SEVERITY",
    };
};
