const std = @import("std");

pub const OcsfStringField = enum {
    metadata_uid,
    activity_name,
    cloud_account_uid,
    cloud_provider,
    cloud_region,
    compliance_assessments_category,
    compliance_assessments_name,
    compliance_control,
    compliance_status,
    compliance_standards,
    finding_info_desc,
    finding_info_src_url,
    finding_info_title,
    finding_info_types,
    finding_info_uid,
    finding_info_related_events_traits_category,
    finding_info_related_events_uid,
    finding_info_related_events_product_uid,
    finding_info_related_events_title,
    metadata_product_name,
    metadata_product_uid,
    metadata_product_vendor_name,
    remediation_desc,
    remediation_references,
    resources_cloud_partition,
    resources_region,
    resources_type,
    resources_uid,
    severity,
    status,
    comment,
    vulnerabilities_fix_coverage,
    class_name,
    databucket_encryption_details_algorithm,
    databucket_encryption_details_key_uid,
    databucket_file_data_classifications_classifier_details_type,
    evidences_actor_user_account_uid,
    evidences_api_operation,
    evidences_api_response_error_message,
    evidences_api_service_name,
    evidences_connection_info_direction,
    evidences_connection_info_protocol_name,
    evidences_dst_endpoint_autonomous_system_name,
    evidences_dst_endpoint_location_city,
    evidences_dst_endpoint_location_country,
    evidences_src_endpoint_autonomous_system_name,
    evidences_src_endpoint_hostname,
    evidences_src_endpoint_location_city,
    evidences_src_endpoint_location_country,
    finding_info_analytic_name,
    malware_name,
    malware_scan_info_uid,
    malware_severity,
    resources_cloud_function_layers_uid_alt,
    resources_cloud_function_runtime,
    resources_cloud_function_user_uid,
    resources_device_encryption_details_key_uid,
    resources_device_image_uid,
    resources_image_architecture,
    resources_image_registry_uid,
    resources_image_repository_name,
    resources_image_uid,
    resources_subnet_info_uid,
    resources_vpc_uid,
    vulnerabilities_affected_code_file_path,
    vulnerabilities_affected_packages_name,
    vulnerabilities_cve_epss_score,
    vulnerabilities_cve_uid,
    vulnerabilities_related_vulnerabilities,
    cloud_account_name,
    vendor_attributes_severity,

    pub const json_field_names = .{
        .metadata_uid = "metadata.uid",
        .activity_name = "activity_name",
        .cloud_account_uid = "cloud.account.uid",
        .cloud_provider = "cloud.provider",
        .cloud_region = "cloud.region",
        .compliance_assessments_category = "compliance.assessments.category",
        .compliance_assessments_name = "compliance.assessments.name",
        .compliance_control = "compliance.control",
        .compliance_status = "compliance.status",
        .compliance_standards = "compliance.standards",
        .finding_info_desc = "finding_info.desc",
        .finding_info_src_url = "finding_info.src_url",
        .finding_info_title = "finding_info.title",
        .finding_info_types = "finding_info.types",
        .finding_info_uid = "finding_info.uid",
        .finding_info_related_events_traits_category = "finding_info.related_events.traits.category",
        .finding_info_related_events_uid = "finding_info.related_events.uid",
        .finding_info_related_events_product_uid = "finding_info.related_events.product.uid",
        .finding_info_related_events_title = "finding_info.related_events.title",
        .metadata_product_name = "metadata.product.name",
        .metadata_product_uid = "metadata.product.uid",
        .metadata_product_vendor_name = "metadata.product.vendor_name",
        .remediation_desc = "remediation.desc",
        .remediation_references = "remediation.references",
        .resources_cloud_partition = "resources.cloud_partition",
        .resources_region = "resources.region",
        .resources_type = "resources.type",
        .resources_uid = "resources.uid",
        .severity = "severity",
        .status = "status",
        .comment = "comment",
        .vulnerabilities_fix_coverage = "vulnerabilities.fix_coverage",
        .class_name = "class_name",
        .databucket_encryption_details_algorithm = "databucket.encryption_details.algorithm",
        .databucket_encryption_details_key_uid = "databucket.encryption_details.key_uid",
        .databucket_file_data_classifications_classifier_details_type = "databucket.file.data_classifications.classifier_details.type",
        .evidences_actor_user_account_uid = "evidences.actor.user.account.uid",
        .evidences_api_operation = "evidences.api.operation",
        .evidences_api_response_error_message = "evidences.api.response.error_message",
        .evidences_api_service_name = "evidences.api.service.name",
        .evidences_connection_info_direction = "evidences.connection_info.direction",
        .evidences_connection_info_protocol_name = "evidences.connection_info.protocol_name",
        .evidences_dst_endpoint_autonomous_system_name = "evidences.dst_endpoint.autonomous_system.name",
        .evidences_dst_endpoint_location_city = "evidences.dst_endpoint.location.city",
        .evidences_dst_endpoint_location_country = "evidences.dst_endpoint.location.country",
        .evidences_src_endpoint_autonomous_system_name = "evidences.src_endpoint.autonomous_system.name",
        .evidences_src_endpoint_hostname = "evidences.src_endpoint.hostname",
        .evidences_src_endpoint_location_city = "evidences.src_endpoint.location.city",
        .evidences_src_endpoint_location_country = "evidences.src_endpoint.location.country",
        .finding_info_analytic_name = "finding_info.analytic.name",
        .malware_name = "malware.name",
        .malware_scan_info_uid = "malware_scan_info.uid",
        .malware_severity = "malware.severity",
        .resources_cloud_function_layers_uid_alt = "resources.cloud_function.layers.uid_alt",
        .resources_cloud_function_runtime = "resources.cloud_function.runtime",
        .resources_cloud_function_user_uid = "resources.cloud_function.user.uid",
        .resources_device_encryption_details_key_uid = "resources.device.encryption_details.key_uid",
        .resources_device_image_uid = "resources.device.image.uid",
        .resources_image_architecture = "resources.image.architecture",
        .resources_image_registry_uid = "resources.image.registry_uid",
        .resources_image_repository_name = "resources.image.repository_name",
        .resources_image_uid = "resources.image.uid",
        .resources_subnet_info_uid = "resources.subnet_info.uid",
        .resources_vpc_uid = "resources.vpc_uid",
        .vulnerabilities_affected_code_file_path = "vulnerabilities.affected_code.file.path",
        .vulnerabilities_affected_packages_name = "vulnerabilities.affected_packages.name",
        .vulnerabilities_cve_epss_score = "vulnerabilities.cve.epss.score",
        .vulnerabilities_cve_uid = "vulnerabilities.cve.uid",
        .vulnerabilities_related_vulnerabilities = "vulnerabilities.related_vulnerabilities",
        .cloud_account_name = "cloud.account.name",
        .vendor_attributes_severity = "vendor_attributes.severity",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .metadata_uid => "metadata.uid",
            .activity_name => "activity_name",
            .cloud_account_uid => "cloud.account.uid",
            .cloud_provider => "cloud.provider",
            .cloud_region => "cloud.region",
            .compliance_assessments_category => "compliance.assessments.category",
            .compliance_assessments_name => "compliance.assessments.name",
            .compliance_control => "compliance.control",
            .compliance_status => "compliance.status",
            .compliance_standards => "compliance.standards",
            .finding_info_desc => "finding_info.desc",
            .finding_info_src_url => "finding_info.src_url",
            .finding_info_title => "finding_info.title",
            .finding_info_types => "finding_info.types",
            .finding_info_uid => "finding_info.uid",
            .finding_info_related_events_traits_category => "finding_info.related_events.traits.category",
            .finding_info_related_events_uid => "finding_info.related_events.uid",
            .finding_info_related_events_product_uid => "finding_info.related_events.product.uid",
            .finding_info_related_events_title => "finding_info.related_events.title",
            .metadata_product_name => "metadata.product.name",
            .metadata_product_uid => "metadata.product.uid",
            .metadata_product_vendor_name => "metadata.product.vendor_name",
            .remediation_desc => "remediation.desc",
            .remediation_references => "remediation.references",
            .resources_cloud_partition => "resources.cloud_partition",
            .resources_region => "resources.region",
            .resources_type => "resources.type",
            .resources_uid => "resources.uid",
            .severity => "severity",
            .status => "status",
            .comment => "comment",
            .vulnerabilities_fix_coverage => "vulnerabilities.fix_coverage",
            .class_name => "class_name",
            .databucket_encryption_details_algorithm => "databucket.encryption_details.algorithm",
            .databucket_encryption_details_key_uid => "databucket.encryption_details.key_uid",
            .databucket_file_data_classifications_classifier_details_type => "databucket.file.data_classifications.classifier_details.type",
            .evidences_actor_user_account_uid => "evidences.actor.user.account.uid",
            .evidences_api_operation => "evidences.api.operation",
            .evidences_api_response_error_message => "evidences.api.response.error_message",
            .evidences_api_service_name => "evidences.api.service.name",
            .evidences_connection_info_direction => "evidences.connection_info.direction",
            .evidences_connection_info_protocol_name => "evidences.connection_info.protocol_name",
            .evidences_dst_endpoint_autonomous_system_name => "evidences.dst_endpoint.autonomous_system.name",
            .evidences_dst_endpoint_location_city => "evidences.dst_endpoint.location.city",
            .evidences_dst_endpoint_location_country => "evidences.dst_endpoint.location.country",
            .evidences_src_endpoint_autonomous_system_name => "evidences.src_endpoint.autonomous_system.name",
            .evidences_src_endpoint_hostname => "evidences.src_endpoint.hostname",
            .evidences_src_endpoint_location_city => "evidences.src_endpoint.location.city",
            .evidences_src_endpoint_location_country => "evidences.src_endpoint.location.country",
            .finding_info_analytic_name => "finding_info.analytic.name",
            .malware_name => "malware.name",
            .malware_scan_info_uid => "malware_scan_info.uid",
            .malware_severity => "malware.severity",
            .resources_cloud_function_layers_uid_alt => "resources.cloud_function.layers.uid_alt",
            .resources_cloud_function_runtime => "resources.cloud_function.runtime",
            .resources_cloud_function_user_uid => "resources.cloud_function.user.uid",
            .resources_device_encryption_details_key_uid => "resources.device.encryption_details.key_uid",
            .resources_device_image_uid => "resources.device.image.uid",
            .resources_image_architecture => "resources.image.architecture",
            .resources_image_registry_uid => "resources.image.registry_uid",
            .resources_image_repository_name => "resources.image.repository_name",
            .resources_image_uid => "resources.image.uid",
            .resources_subnet_info_uid => "resources.subnet_info.uid",
            .resources_vpc_uid => "resources.vpc_uid",
            .vulnerabilities_affected_code_file_path => "vulnerabilities.affected_code.file.path",
            .vulnerabilities_affected_packages_name => "vulnerabilities.affected_packages.name",
            .vulnerabilities_cve_epss_score => "vulnerabilities.cve.epss.score",
            .vulnerabilities_cve_uid => "vulnerabilities.cve.uid",
            .vulnerabilities_related_vulnerabilities => "vulnerabilities.related_vulnerabilities",
            .cloud_account_name => "cloud.account.name",
            .vendor_attributes_severity => "vendor_attributes.severity",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
