pub const OcsfStringField = enum {
    metadata_uid,
    activity_name,
    cloud_account_uid,
    cloud_provider,
    cloud_region,
    compliance_assessments_category,
    compliance_assessments_name,
    compliance_control,
    compliance_status,
    compliance_standards,
    finding_info_desc,
    finding_info_src_url,
    finding_info_title,
    finding_info_types,
    finding_info_uid,
    finding_info_related_events_traits_category,
    finding_info_related_events_uid,
    finding_info_related_events_product_uid,
    finding_info_related_events_title,
    metadata_product_name,
    metadata_product_uid,
    metadata_product_vendor_name,
    remediation_desc,
    remediation_references,
    resources_cloud_partition,
    resources_region,
    resources_type,
    resources_uid,
    severity,
    status,
    comment,
    vulnerabilities_fix_coverage,
    class_name,
    databucket_encryption_details_algorithm,
    databucket_encryption_details_key_uid,
    databucket_file_data_classifications_classifier_details_type,
    evidences_actor_user_account_uid,
    evidences_api_operation,
    evidences_api_response_error_message,
    evidences_api_service_name,
    evidences_connection_info_direction,
    evidences_connection_info_protocol_name,
    evidences_dst_endpoint_autonomous_system_name,
    evidences_dst_endpoint_location_city,
    evidences_dst_endpoint_location_country,
    evidences_src_endpoint_autonomous_system_name,
    evidences_src_endpoint_hostname,
    evidences_src_endpoint_location_city,
    evidences_src_endpoint_location_country,
    finding_info_analytic_name,
    malware_name,
    malware_scan_info_uid,
    malware_severity,
    resources_cloud_function_layers_uid_alt,
    resources_cloud_function_runtime,
    resources_cloud_function_user_uid,
    resources_device_encryption_details_key_uid,
    resources_device_image_uid,
    resources_image_architecture,
    resources_image_registry_uid,
    resources_image_repository_name,
    resources_image_uid,
    resources_subnet_info_uid,
    resources_vpc_uid,
    vulnerabilities_affected_code_file_path,
    vulnerabilities_affected_packages_name,
    vulnerabilities_cve_epss_score,
    vulnerabilities_cve_uid,
    vulnerabilities_related_vulnerabilities,
    cloud_account_name,
    vendor_attributes_severity,

    pub const json_field_names = .{
        .metadata_uid = "METADATA_UID",
        .activity_name = "ACTIVITY_NAME",
        .cloud_account_uid = "CLOUD_ACCOUNT_UID",
        .cloud_provider = "CLOUD_PROVIDER",
        .cloud_region = "CLOUD_REGION",
        .compliance_assessments_category = "COMPLIANCE_ASSESSMENTS_CATEGORY",
        .compliance_assessments_name = "COMPLIANCE_ASSESSMENTS_NAME",
        .compliance_control = "COMPLIANCE_CONTROL",
        .compliance_status = "COMPLIANCE_STATUS",
        .compliance_standards = "COMPLIANCE_STANDARDS",
        .finding_info_desc = "FINDING_INFO_DESC",
        .finding_info_src_url = "FINDING_INFO_SRC_URL",
        .finding_info_title = "FINDING_INFO_TITLE",
        .finding_info_types = "FINDING_INFO_TYPES",
        .finding_info_uid = "FINDING_INFO_UID",
        .finding_info_related_events_traits_category = "FINDING_INFO_RELATED_EVENTS_TRAITS_CATEGORY",
        .finding_info_related_events_uid = "FINDING_INFO_RELATED_EVENTS_UID",
        .finding_info_related_events_product_uid = "FINDING_INFO_RELATED_EVENTS_PRODUCT_UID",
        .finding_info_related_events_title = "FINDING_INFO_RELATED_EVENTS_TITLE",
        .metadata_product_name = "METADATA_PRODUCT_NAME",
        .metadata_product_uid = "METADATA_PRODUCT_UID",
        .metadata_product_vendor_name = "METADATA_PRODUCT_VENDOR_NAME",
        .remediation_desc = "REMEDIATION_DESC",
        .remediation_references = "REMEDIATION_REFERENCES",
        .resources_cloud_partition = "RESOURCES_CLOUD_PARTITION",
        .resources_region = "RESOURCES_REGION",
        .resources_type = "RESOURCES_TYPE",
        .resources_uid = "RESOURCES_UID",
        .severity = "SEVERITY",
        .status = "STATUS",
        .comment = "COMMENT",
        .vulnerabilities_fix_coverage = "VULNERABILITIES_FIX_COVERAGE",
        .class_name = "CLASS_NAME",
        .databucket_encryption_details_algorithm = "DATABUCKET_ENCRYPTION_DETAILS_ALGORITHM",
        .databucket_encryption_details_key_uid = "DATABUCKET_ENCRYPTION_DETAILS_KEY_UID",
        .databucket_file_data_classifications_classifier_details_type = "DATABUCKET_FILE_DATA_CLASSIFICATIONS_CLASSIFIER_DETAILS_TYPE",
        .evidences_actor_user_account_uid = "EVIDENCES_ACTOR_USER_ACCOUNT_UID",
        .evidences_api_operation = "EVIDENCES_API_OPERATION",
        .evidences_api_response_error_message = "EVIDENCES_API_RESPONSE_ERROR_MESSAGE",
        .evidences_api_service_name = "EVIDENCES_API_SERVICE_NAME",
        .evidences_connection_info_direction = "EVIDENCES_CONNECTION_INFO_DIRECTION",
        .evidences_connection_info_protocol_name = "EVIDENCES_CONNECTION_INFO_PROTOCOL_NAME",
        .evidences_dst_endpoint_autonomous_system_name = "EVIDENCES_DST_ENDPOINT_AUTONOMOUS_SYSTEM_NAME",
        .evidences_dst_endpoint_location_city = "EVIDENCES_DST_ENDPOINT_LOCATION_CITY",
        .evidences_dst_endpoint_location_country = "EVIDENCES_DST_ENDPOINT_LOCATION_COUNTRY",
        .evidences_src_endpoint_autonomous_system_name = "EVIDENCES_SRC_ENDPOINT_AUTONOMOUS_SYSTEM_NAME",
        .evidences_src_endpoint_hostname = "EVIDENCES_SRC_ENDPOINT_HOSTNAME",
        .evidences_src_endpoint_location_city = "EVIDENCES_SRC_ENDPOINT_LOCATION_CITY",
        .evidences_src_endpoint_location_country = "EVIDENCES_SRC_ENDPOINT_LOCATION_COUNTRY",
        .finding_info_analytic_name = "FINDING_INFO_ANALYTIC_NAME",
        .malware_name = "MALWARE_NAME",
        .malware_scan_info_uid = "MALWARE_SCAN_INFO_UID",
        .malware_severity = "MALWARE_SEVERITY",
        .resources_cloud_function_layers_uid_alt = "RESOURCES_CLOUD_FUNCTION_LAYERS_UID_ALT",
        .resources_cloud_function_runtime = "RESOURCES_CLOUD_FUNCTION_RUNTIME",
        .resources_cloud_function_user_uid = "RESOURCES_CLOUD_FUNCTION_USER_UID",
        .resources_device_encryption_details_key_uid = "RESOURCES_DEVICE_ENCRYPTION_DETAILS_KEY_UID",
        .resources_device_image_uid = "RESOURCES_DEVICE_IMAGE_UID",
        .resources_image_architecture = "RESOURCES_IMAGE_ARCHITECTURE",
        .resources_image_registry_uid = "RESOURCES_IMAGE_REGISTRY_UID",
        .resources_image_repository_name = "RESOURCES_IMAGE_REPOSITORY_NAME",
        .resources_image_uid = "RESOURCES_IMAGE_UID",
        .resources_subnet_info_uid = "RESOURCES_SUBNET_INFO_UID",
        .resources_vpc_uid = "RESOURCES_VPC_UID",
        .vulnerabilities_affected_code_file_path = "VULNERABILITIES_AFFECTED_CODE_FILE_PATH",
        .vulnerabilities_affected_packages_name = "VULNERABILITIES_AFFECTED_PACKAGES_NAME",
        .vulnerabilities_cve_epss_score = "VULNERABILITIES_CVE_EPSS_SCORE",
        .vulnerabilities_cve_uid = "VULNERABILITIES_CVE_UID",
        .vulnerabilities_related_vulnerabilities = "VULNERABILITIES_RELATED_VULNERABILITIES",
        .cloud_account_name = "CLOUD_ACCOUNT_NAME",
        .vendor_attributes_severity = "VENDOR_ATTRIBUTES_SEVERITY",
    };
};
