const BatchSegmentJobInput = @import("batch_segment_job_input.zig").BatchSegmentJobInput;
const BatchSegmentJobOutput = @import("batch_segment_job_output.zig").BatchSegmentJobOutput;

/// Contains information on a batch segment job.
pub const BatchSegmentJob = struct {
    /// The Amazon Resource Name (ARN) of the batch segment job.
    batch_segment_job_arn: ?[]const u8 = null,

    /// The time at which the batch segment job was created.
    creation_date_time: ?i64 = null,

    /// If the batch segment job failed, the reason for the failure.
    failure_reason: ?[]const u8 = null,

    /// The ARN of the filter used on the batch segment job.
    filter_arn: ?[]const u8 = null,

    /// The Amazon S3 path that leads to the input data used to generate the batch
    /// segment job.
    job_input: ?BatchSegmentJobInput = null,

    /// The name of the batch segment job.
    job_name: ?[]const u8 = null,

    /// The Amazon S3 bucket that contains the output data generated by the batch
    /// segment job.
    job_output: ?BatchSegmentJobOutput = null,

    /// The time at which the batch segment job last updated.
    last_updated_date_time: ?i64 = null,

    /// The number of predicted users generated by the batch segment job for each
    /// line of input data. The maximum number of users per segment is 5 million.
    num_results: ?i32 = null,

    /// The ARN of the Amazon Identity and Access Management (IAM) role that
    /// requested the batch segment job.
    role_arn: ?[]const u8 = null,

    /// The Amazon Resource Name (ARN) of the solution version used by the batch
    /// segment job to generate batch segments.
    solution_version_arn: ?[]const u8 = null,

    /// The status of the batch segment job. The status is one of the following
    /// values:
    ///
    /// * PENDING
    ///
    /// * IN PROGRESS
    ///
    /// * ACTIVE
    ///
    /// * CREATE FAILED
    status: ?[]const u8 = null,

    pub const json_field_names = .{
        .batch_segment_job_arn = "batchSegmentJobArn",
        .creation_date_time = "creationDateTime",
        .failure_reason = "failureReason",
        .filter_arn = "filterArn",
        .job_input = "jobInput",
        .job_name = "jobName",
        .job_output = "jobOutput",
        .last_updated_date_time = "lastUpdatedDateTime",
        .num_results = "numResults",
        .role_arn = "roleArn",
        .solution_version_arn = "solutionVersionArn",
        .status = "status",
    };
};
