const BatchInferenceJobConfig = @import("batch_inference_job_config.zig").BatchInferenceJobConfig;
const BatchInferenceJobMode = @import("batch_inference_job_mode.zig").BatchInferenceJobMode;
const BatchInferenceJobInput = @import("batch_inference_job_input.zig").BatchInferenceJobInput;
const BatchInferenceJobOutput = @import("batch_inference_job_output.zig").BatchInferenceJobOutput;
const ThemeGenerationConfig = @import("theme_generation_config.zig").ThemeGenerationConfig;

/// Contains information on a batch inference job.
pub const BatchInferenceJob = struct {
    /// The Amazon Resource Name (ARN) of the batch inference job.
    batch_inference_job_arn: ?[]const u8,

    /// A string to string map of the configuration details of a batch inference
    /// job.
    batch_inference_job_config: ?BatchInferenceJobConfig,

    /// The job's mode.
    batch_inference_job_mode: ?BatchInferenceJobMode,

    /// The time at which the batch inference job was created.
    creation_date_time: ?i64,

    /// If the batch inference job failed, the reason for the failure.
    failure_reason: ?[]const u8,

    /// The ARN of the filter used on the batch inference job.
    filter_arn: ?[]const u8,

    /// The Amazon S3 path that leads to the input data used to generate the batch
    /// inference
    /// job.
    job_input: ?BatchInferenceJobInput,

    /// The name of the batch inference job.
    job_name: ?[]const u8,

    /// The Amazon S3 bucket that contains the output data generated by the batch
    /// inference job.
    job_output: ?BatchInferenceJobOutput,

    /// The time at which the batch inference job was last updated.
    last_updated_date_time: ?i64,

    /// The number of recommendations generated by the batch inference job. This
    /// number includes
    /// the error messages generated for failed input records.
    num_results: ?i32,

    /// The ARN of the Amazon Identity and Access Management (IAM) role that
    /// requested the batch inference job.
    role_arn: ?[]const u8,

    /// The Amazon Resource Name (ARN) of the solution version from which the batch
    /// inference job
    /// was created.
    solution_version_arn: ?[]const u8,

    /// The status of the batch inference job. The status is one of the following
    /// values:
    ///
    /// * PENDING
    ///
    /// * IN PROGRESS
    ///
    /// * ACTIVE
    ///
    /// * CREATE FAILED
    status: ?[]const u8,

    /// The job's theme generation settings.
    theme_generation_config: ?ThemeGenerationConfig,

    pub const json_field_names = .{
        .batch_inference_job_arn = "batchInferenceJobArn",
        .batch_inference_job_config = "batchInferenceJobConfig",
        .batch_inference_job_mode = "batchInferenceJobMode",
        .creation_date_time = "creationDateTime",
        .failure_reason = "failureReason",
        .filter_arn = "filterArn",
        .job_input = "jobInput",
        .job_name = "jobName",
        .job_output = "jobOutput",
        .last_updated_date_time = "lastUpdatedDateTime",
        .num_results = "numResults",
        .role_arn = "roleArn",
        .solution_version_arn = "solutionVersionArn",
        .status = "status",
        .theme_generation_config = "themeGenerationConfig",
    };
};
