pub const ValidationExceptionReason = enum {
    invalid_expires_in,
    invalid_status,
    missing_value,
    invalid_token,
    invalid_resource_identifier,
    invalid_az,
    unsupported_az,
    invalid_alarm_condition,
    invalid_condition_type,
    invalid_practice_blocker,
    fis_experiment_update_not_allowed,
    autoshift_update_not_allowed,
    unsupported_practice_cancel_shift_type,
    invalid_practice_allowed_window,
    conflicting_practice_windows,

    pub const json_field_names = .{
        .invalid_expires_in = "INVALID_EXPIRES_IN",
        .invalid_status = "INVALID_STATUS",
        .missing_value = "MISSING_VALUE",
        .invalid_token = "INVALID_TOKEN",
        .invalid_resource_identifier = "INVALID_RESOURCE_IDENTIFIER",
        .invalid_az = "INVALID_AZ",
        .unsupported_az = "UNSUPPORTED_AZ",
        .invalid_alarm_condition = "INVALID_ALARM_CONDITION",
        .invalid_condition_type = "INVALID_CONDITION_TYPE",
        .invalid_practice_blocker = "INVALID_PRACTICE_BLOCKER",
        .fis_experiment_update_not_allowed = "FIS_EXPERIMENT_UPDATE_NOT_ALLOWED",
        .autoshift_update_not_allowed = "AUTOSHIFT_UPDATE_NOT_ALLOWED",
        .unsupported_practice_cancel_shift_type = "UNSUPPORTED_PRACTICE_CANCEL_SHIFT_TYPE",
        .invalid_practice_allowed_window = "INVALID_PRACTICE_ALLOWED_WINDOW",
        .conflicting_practice_windows = "CONFLICTING_PRACTICE_WINDOWS",
    };
};
