const GuardrailAction = @import("guardrail_action.zig").GuardrailAction;

/// A warning generated by a guardrail during agentic retrieval.
pub const AgenticRetrieveGuardrailWarning = struct {
    /// The action taken by the guardrail.
    action: GuardrailAction,

    /// The unique identifier of the guardrail.
    id: []const u8,

    /// A message describing the guardrail evaluation result.
    message: ?[]const u8 = null,

    /// The version of the guardrail.
    version: []const u8,

    pub const json_field_names = .{
        .action = "action",
        .id = "id",
        .message = "message",
        .version = "version",
    };
};
