const Metadata = @import("metadata.zig").Metadata;

/// Contains the JSON-formatted string returned by the API invoked by the code
/// interpreter.
pub const CodeInterpreterInvocationOutput = struct {
    /// Contains the error returned from code execution.
    execution_error: ?[]const u8 = null,

    /// Contains the successful output returned from code execution
    execution_output: ?[]const u8 = null,

    /// Indicates if the execution of the code timed out.
    execution_timeout: ?bool = null,

    /// Contains output files, if generated by code execution.
    files: ?[]const []const u8 = null,

    /// Contains information about the output from the code interpreter.
    metadata: ?Metadata = null,

    pub const json_field_names = .{
        .execution_error = "executionError",
        .execution_output = "executionOutput",
        .execution_timeout = "executionTimeout",
        .files = "files",
        .metadata = "metadata",
    };
};
