pub const SavingsPlanRateUnit = enum {
    hours,
    lambda_gb_second,
    request,
    acu_hr,
    read_request_units,
    write_request_units,
    read_capacity_unit_hrs,
    write_capacity_unit_hrs,
    replicated_write_request_units,
    replicated_write_capacity_unit_hrs,
    gb_hours,
    dpu,
    elasti_cache_processing_unit,
    dcu_hr,
    ncu_hr,

    pub const json_field_names = .{
        .hours = "HOURS",
        .lambda_gb_second = "LAMBDA_GB_SECOND",
        .request = "REQUEST",
        .acu_hr = "ACU_HR",
        .read_request_units = "READ_REQUEST_UNITS",
        .write_request_units = "WRITE_REQUEST_UNITS",
        .read_capacity_unit_hrs = "READ_CAPACITY_UNIT_HRS",
        .write_capacity_unit_hrs = "WRITE_CAPACITY_UNIT_HRS",
        .replicated_write_request_units = "REPLICATED_WRITE_REQUEST_UNITS",
        .replicated_write_capacity_unit_hrs = "REPLICATED_WRITE_CAPACITY_UNIT_HRS",
        .gb_hours = "GB_HOURS",
        .dpu = "DPU",
        .elasti_cache_processing_unit = "ELASTI_CACHE_PROCESSING_UNIT",
        .dcu_hr = "DCU_HR",
        .ncu_hr = "NCU_HR",
    };
};
