const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const SessionStatusString = @import("session_status_string.zig").SessionStatusString;
const SessionData = @import("session_data.zig").SessionData;

pub const ListSessionsInput = struct {
    /// The cluster identifier. Only sessions on this cluster are returned. When
    /// providing `ClusterIdentifier`, then `WorkgroupName` can't be specified.
    cluster_identifier: ?[]const u8 = null,

    /// The name of the database. Only sessions connected to this database are
    /// returned.
    database: ?[]const u8 = null,

    /// The maximum number of sessions to return in the response. If more sessions
    /// exist than fit in one response, the operation returns `NextToken` to
    /// paginate the results.
    max_results: ?i32 = null,

    /// A value that indicates the starting point for the next set of response
    /// records in a subsequent request. If a value is returned in a response, you
    /// can retrieve the next set of records by providing this returned NextToken
    /// value in the next NextToken parameter and retrying the command. If the
    /// NextToken field is empty, all response records have been retrieved for the
    /// request.
    next_token: ?[]const u8 = null,

    /// Specifies whether to return all sessions created by the caller's IAM role,
    /// including sessions from previous IAM sessions. If false, only sessions
    /// created in the current IAM session are returned. The default is true.
    role_level: ?bool = null,

    /// The identifier of a specific session to return metadata for. This value is a
    /// universally unique identifier (UUID) generated by Amazon Redshift Data API.
    /// When you provide `SessionId`, you can't specify `Status`,
    /// `ClusterIdentifier`, `WorkgroupName`, or `Database`.
    session_id: ?[]const u8 = null,

    /// The status of the sessions to list. If no status is specified, sessions with
    /// a status of `AVAILABLE` or `BUSY` are returned. Status values are defined as
    /// follows:
    ///
    /// * AVAILABLE – The session is open and ready to run a SQL statement.
    /// * BUSY – The session is currently running a SQL statement.
    /// * CLOSED – The session is closed and can no longer run SQL statements.
    status: ?SessionStatusString = null,

    /// The serverless workgroup name or Amazon Resource Name (ARN). Only sessions
    /// on this workgroup are returned. When providing `WorkgroupName`, then
    /// `ClusterIdentifier` can't be specified.
    workgroup_name: ?[]const u8 = null,

    pub const json_field_names = .{
        .cluster_identifier = "ClusterIdentifier",
        .database = "Database",
        .max_results = "MaxResults",
        .next_token = "NextToken",
        .role_level = "RoleLevel",
        .session_id = "SessionId",
        .status = "Status",
        .workgroup_name = "WorkgroupName",
    };
};

pub const ListSessionsOutput = struct {
    /// A value that indicates the starting point for the next set of response
    /// records in a subsequent request. If a value is returned in a response, you
    /// can retrieve the next set of records by providing this returned NextToken
    /// value in the next NextToken parameter and retrying the command. If the
    /// NextToken field is empty, all response records have been retrieved for the
    /// request.
    next_token: ?[]const u8 = null,

    /// The sessions that match the request.
    sessions: ?[]const SessionData = null,

    pub const json_field_names = .{
        .next_token = "NextToken",
        .sessions = "Sessions",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: ListSessionsInput, options: CallOptions) !ListSessionsOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "redshift-data", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: ListSessionsInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("redshift-data", "Redshift Data", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "RedshiftData.ListSessions");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !ListSessionsOutput {
    _ = status;
    _ = headers;
    return aws.json.parseJsonObject(ListSessionsOutput, body, allocator);
}
