const SqlParameter = @import("sql_parameter.zig").SqlParameter;
const ResultFormatString = @import("result_format_string.zig").ResultFormatString;
const StatusString = @import("status_string.zig").StatusString;

/// The SQL statement to run.
pub const StatementData = struct {
    /// The date and time (UTC) the statement was created.
    created_at: ?i64,

    /// The SQL statement identifier. This value is a universally unique identifier
    /// (UUID) generated by Amazon Redshift Data API.
    id: []const u8,

    /// A value that indicates whether the statement is a batch query request.
    is_batch_statement: ?bool,

    /// The parameters used in a SQL statement.
    query_parameters: ?[]const SqlParameter,

    /// The SQL statement.
    query_string: ?[]const u8,

    /// One or more SQL statements. Each query string in the array corresponds to
    /// one of the queries in a batch query request.
    query_strings: ?[]const []const u8,

    /// The data format of the result of the SQL statement.
    result_format: ?ResultFormatString,

    /// The name or Amazon Resource Name (ARN) of the secret that enables access to
    /// the database.
    secret_arn: ?[]const u8,

    /// The session identifier of the query.
    session_id: ?[]const u8,

    /// The name of the SQL statement.
    statement_name: ?[]const u8,

    /// The status of the SQL statement. An example is the that the SQL statement
    /// finished.
    status: ?StatusString,

    /// The date and time (UTC) that the statement metadata was last updated.
    updated_at: ?i64,

    pub const json_field_names = .{
        .created_at = "CreatedAt",
        .id = "Id",
        .is_batch_statement = "IsBatchStatement",
        .query_parameters = "QueryParameters",
        .query_string = "QueryString",
        .query_strings = "QueryStrings",
        .result_format = "ResultFormat",
        .secret_arn = "SecretArn",
        .session_id = "SessionId",
        .statement_name = "StatementName",
        .status = "Status",
        .updated_at = "UpdatedAt",
    };
};
