const StatementStatusString = @import("statement_status_string.zig").StatementStatusString;

/// Information about an SQL statement.
pub const SubStatementData = struct {
    /// The date and time (UTC) the statement was created.
    created_at: ?i64,

    /// The amount of time in nanoseconds that the statement ran.
    duration: i64 = 0,

    /// The error message from the cluster if the SQL statement encountered an error
    /// while running.
    @"error": ?[]const u8,

    /// A value that indicates whether the statement has a result set. The result
    /// set can be empty. The value is true for an empty result set.
    has_result_set: ?bool,

    /// The identifier of the SQL statement. This value is a universally unique
    /// identifier (UUID) generated by Amazon Redshift Data API. A suffix indicates
    /// the number of the SQL statement. For example,
    /// `d9b6c0c9-0747-4bf4-b142-e8883122f766:2` has a suffix of `:2` that indicates
    /// the second SQL statement of a batch query.
    id: []const u8,

    /// The SQL statement text.
    query_string: ?[]const u8,

    /// The SQL statement identifier. This value is a universally unique identifier
    /// (UUID) generated by Amazon Redshift Data API.
    redshift_query_id: i64 = 0,

    /// Either the number of rows returned from the SQL statement or the number of
    /// rows affected. If result size is greater than zero, the result rows can be
    /// the number of rows affected by SQL statements such as INSERT, UPDATE,
    /// DELETE, COPY, and others. A `-1` indicates the value is null.
    result_rows: i64 = 0,

    /// The size in bytes of the returned results. A `-1` indicates the value is
    /// null.
    result_size: i64 = 0,

    /// The status of the SQL statement. An example is the that the SQL statement
    /// finished.
    status: ?StatementStatusString,

    /// The date and time (UTC) that the statement metadata was last updated.
    updated_at: ?i64,

    pub const json_field_names = .{
        .created_at = "CreatedAt",
        .duration = "Duration",
        .@"error" = "Error",
        .has_result_set = "HasResultSet",
        .id = "Id",
        .query_string = "QueryString",
        .redshift_query_id = "RedshiftQueryId",
        .result_rows = "ResultRows",
        .result_size = "ResultSize",
        .status = "Status",
        .updated_at = "UpdatedAt",
    };
};
