const std = @import("std");

pub const ResourceType = enum {
    customer_gateway,
    eip,
    host,
    instance,
    internet_gateway,
    network_acl,
    network_interface,
    route_table,
    security_group,
    subnet,
    trail,
    volume,
    vpc,
    vpn_connection,
    vpn_gateway,
    registered_ha_instance,
    nat_gateway,
    egress_only_internet_gateway,
    vpc_endpoint,
    vpc_endpoint_service,
    flow_log,
    vpc_peering_connection,
    domain,
    group,
    policy,
    role,
    user,
    load_balancer_v2,
    certificate,
    db_instance,
    db_subnet_group,
    db_security_group,
    db_snapshot,
    db_cluster,
    db_cluster_snapshot,
    event_subscription,
    bucket,
    account_public_access_block,
    cluster,
    cluster_snapshot,
    cluster_parameter_group,
    cluster_security_group,
    cluster_subnet_group,
    redshift_event_subscription,
    managed_instance_inventory,
    alarm,
    stack,
    load_balancer,
    auto_scaling_group,
    launch_configuration,
    scaling_policy,
    scheduled_action,
    table,
    project,
    rate_based_rule,
    rule,
    rule_group,
    web_acl,
    regional_rate_based_rule,
    regional_rule,
    regional_rule_group,
    regional_web_acl,
    distribution,
    streaming_distribution,
    function,
    network_firewall_firewall,
    network_firewall_firewall_policy,
    network_firewall_rule_group,
    application,
    application_version,
    environment,
    web_aclv2,
    rule_group_v2,
    ip_set_v2,
    regex_pattern_set_v2,
    managed_rule_set_v2,
    encryption_config,
    association_compliance,
    patch_compliance,
    protection,
    regional_protection,
    conformance_pack_compliance,
    resource_compliance,
    stage,
    rest_api,
    stage_v2,
    api,
    pipeline,
    cloud_formation_provisioned_product,
    cloud_formation_product,
    portfolio,
    queue,
    key,
    qldb_ledger,
    secret,
    topic,
    file_data,
    backup_plan,
    backup_selection,
    backup_vault,
    backup_recovery_point,
    ecr_repository,
    ecs_cluster,
    ecs_service,
    ecs_task_definition,
    efs_access_point,
    efs_file_system,
    eks_cluster,
    open_search_domain,
    transit_gateway,
    kinesis_stream,
    kinesis_stream_consumer,
    code_deploy_application,
    code_deploy_deployment_config,
    code_deploy_deployment_group,
    launch_template,
    ecr_public_repository,
    guard_duty_detector,
    emr_security_configuration,
    sage_maker_code_repository,
    route_53_resolver_resolver_endpoint,
    route_53_resolver_resolver_rule,
    route_53_resolver_resolver_rule_association,
    dms_replication_subnet_group,
    dms_event_subscription,
    msk_cluster,
    step_functions_activity,
    work_spaces_workspace,
    work_spaces_connection_alias,
    sage_maker_model,
    listener_v2,
    step_functions_state_machine,
    batch_job_queue,
    batch_compute_environment,
    access_analyzer_analyzer,
    athena_work_group,
    athena_data_catalog,
    detective_graph,
    global_accelerator_accelerator,
    global_accelerator_endpoint_group,
    global_accelerator_listener,
    transit_gateway_attachment,
    transit_gateway_route_table,
    dms_certificate,
    app_config_application,
    app_sync_graph_ql_api,
    data_sync_location_smb,
    data_sync_location_f_sx_lustre,
    data_sync_location_s3,
    data_sync_location_efs,
    data_sync_task,
    data_sync_location_nfs,
    network_insights_access_scope_analysis,
    eks_fargate_profile,
    glue_job,
    guard_duty_threat_intel_set,
    guard_duty_ip_set,
    sage_maker_workteam,
    sage_maker_notebook_instance_lifecycle_config,
    service_discovery_service,
    service_discovery_public_dns_namespace,
    ses_contact_list,
    ses_configuration_set,
    route_53_hosted_zone,
    io_t_events_input,
    io_t_events_detector_model,
    io_t_events_alarm_model,
    service_discovery_http_namespace,
    events_event_bus,
    image_builder_container_recipe,
    image_builder_distribution_configuration,
    image_builder_infrastructure_configuration,
    data_sync_location_object_storage,
    data_sync_location_hdfs,
    glue_classifier,
    route_53_recovery_readiness_cell,
    route_53_recovery_readiness_readiness_check,
    ecr_registry_policy,
    backup_report_plan,
    lightsail_certificate,
    rum_app_monitor,
    events_endpoint,
    ses_receipt_rule_set,
    events_archive,
    events_api_destination,
    lightsail_disk,
    fis_experiment_template,
    data_sync_location_f_sx_windows,
    ses_receipt_filter,
    guard_duty_filter,
    ses_template,
    amazon_mq_broker,
    app_config_environment,
    app_config_configuration_profile,
    cloud_9_environment_ec2,
    event_schemas_registry,
    event_schemas_registry_policy,
    event_schemas_discoverer,
    fraud_detector_label,
    fraud_detector_entity_type,
    fraud_detector_variable,
    fraud_detector_outcome,
    io_t_authorizer,
    io_t_security_profile,
    io_t_role_alias,
    io_t_dimension,
    io_t_analytics_datastore,
    lightsail_bucket,
    lightsail_static_ip,
    media_package_packaging_group,
    route_53_recovery_readiness_recovery_group,
    resilience_hub_resiliency_policy,
    transfer_workflow,
    eks_identity_provider_config,
    eks_addon,
    glue_ml_transform,
    io_t_policy,
    io_t_mitigation_action,
    io_t_twin_maker_workspace,
    io_t_twin_maker_entity,
    io_t_analytics_dataset,
    io_t_analytics_pipeline,
    io_t_analytics_channel,
    io_t_site_wise_dashboard,
    io_t_site_wise_project,
    io_t_site_wise_portal,
    io_t_site_wise_asset_model,
    ivs_channel,
    ivs_recording_configuration,
    ivs_playback_key_pair,
    kinesis_analytics_v2_application,
    rds_global_cluster,
    s3_multi_region_access_point,
    device_farm_test_grid_project,
    budgets_budgets_action,
    lex_bot,
    code_guru_reviewer_repository_association,
    io_t_custom_metric,
    route_53_resolver_firewall_domain_list,
    robo_maker_robot_application_version,
    ec2_traffic_mirror_session,
    io_t_site_wise_gateway,
    lex_bot_alias,
    lookout_metrics_alert,
    io_t_account_audit_configuration,
    ec2_traffic_mirror_target,
    s3_storage_lens,
    io_t_scheduled_audit,
    events_connection,
    event_schemas_schema,
    media_package_packaging_configuration,
    kinesis_video_signaling_channel,
    app_stream_directory_config,
    lookout_vision_project,
    route_53_recovery_control_cluster,
    route_53_recovery_control_safety_rule,
    route_53_recovery_control_control_panel,
    route_53_recovery_control_routing_control,
    route_53_recovery_readiness_resource_set,
    robo_maker_simulation_application,
    robo_maker_robot_application,
    health_lake_fhir_datastore,
    pinpoint_segment,
    pinpoint_application_settings,
    events_rule,
    ec2_dhcp_options,
    ec2_network_insights_path,
    ec2_traffic_mirror_filter,
    ec2_ipam,
    io_t_twin_maker_scene,
    network_manager_transit_gateway_registration,
    customer_profiles_domain,
    auto_scaling_warm_pool,
    connect_phone_number,
    app_config_deployment_strategy,
    app_flow_flow,
    audit_manager_assessment,
    cloud_watch_metric_stream,
    device_farm_instance_profile,
    device_farm_project,
    ec2_ec2_fleet,
    ec2_subnet_route_table_association,
    ecr_pull_through_cache_rule,
    ground_station_config,
    image_builder_image_pipeline,
    io_t_fleet_metric,
    io_t_wireless_service_profile,
    network_manager_device,
    network_manager_global_network,
    network_manager_link,
    network_manager_site,
    panorama_package,
    pinpoint_app,
    redshift_scheduled_action,
    route_53_resolver_firewall_rule_group_association,
    sage_maker_app_image_config,
    sage_maker_image,
    ecs_task_set,
    cassandra_keyspace,
    signer_signing_profile,
    amplify_app,
    app_mesh_virtual_node,
    app_mesh_virtual_service,
    app_runner_vpc_connector,
    app_stream_application,
    code_artifact_repository,
    ec2_prefix_list,
    ec2_spot_fleet,
    evidently_project,
    forecast_dataset,
    iamsaml_provider,
    iam_server_certificate,
    pinpoint_campaign,
    pinpoint_in_app_template,
    sage_maker_domain,
    transfer_agreement,
    transfer_connector,
    kinesis_firehose_delivery_stream,
    amplify_branch,
    app_integrations_event_integration,
    app_mesh_route,
    athena_prepared_statement,
    ec2_ipam_scope,
    evidently_launch,
    forecast_dataset_group,
    greengrass_v2_component_version,
    ground_station_mission_profile,
    media_connect_flow_entitlement,
    media_connect_flow_vpc_interface,
    media_tailor_playback_configuration,
    msk_configuration,
    personalize_dataset,
    personalize_schema,
    personalize_solution,
    pinpoint_email_template,
    pinpoint_event_stream,
    resilience_hub_app,
    acmpca_certificate_authority,
    app_config_hosted_configuration_version,
    app_mesh_virtual_gateway,
    app_mesh_virtual_router,
    app_runner_service,
    customer_profiles_object_type,
    dms_endpoint,
    ec2_capacity_reservation,
    ec2_client_vpn_endpoint,
    kendra_index,
    kinesis_video_stream,
    logs_destination,
    pinpoint_email_channel,
    s3_access_point,
    network_manager_customer_gateway_association,
    network_manager_link_association,
    io_t_wireless_multicast_group,
    personalize_dataset_group,
    io_t_twin_maker_component_type,
    code_build_report_group,
    sage_maker_feature_group,
    msk_batch_scram_secret,
    app_stream_stack,
    io_t_job_template,
    io_t_wireless_fuota_task,
    io_t_provisioning_template,
    inspector_v2_filter,
    route_53_resolver_resolver_query_logging_config_association,
    service_discovery_instance,
    transfer_certificate,
    media_connect_flow_source,
    aps_rule_groups_namespace,
    code_guru_profiler_profiling_group,
    route_53_resolver_resolver_query_logging_config,
    batch_scheduling_policy,
    acmpca_certificate_authority_activation,
    app_mesh_gateway_route,
    app_mesh_mesh,
    connect_instance,
    connect_quick_connect,
    ec2_carrier_gateway,
    ec2_ipam_pool,
    ec2_transit_gateway_connect,
    ec2_transit_gateway_multicast_domain,
    ecs_capacity_provider,
    iam_instance_profile,
    io_tca_certificate,
    io_t_twin_maker_sync_job,
    kafka_connect_connector,
    lambda_code_signing_config,
    network_manager_connect_peer,
    resource_explorer_2_index,
    app_stream_fleet,
    cognito_user_pool,
    cognito_user_pool_client,
    cognito_user_pool_group,
    ec2_network_insights_access_scope,
    ec2_network_insights_analysis,
    grafana_workspace,
    ground_station_dataflow_endpoint_group,
    image_builder_image_recipe,
    kms_alias,
    m2_environment,
    quick_sight_data_source,
    quick_sight_template,
    quick_sight_theme,
    rds_option_group,
    redshift_endpoint_access,
    route_53_resolver_firewall_rule_group,
    ssm_document,
    app_config_extension_association,
    app_integrations_application,
    app_sync_api_cache,
    bedrock_guardrail,
    bedrock_knowledge_base,
    cognito_identity_pool,
    connect_rule,
    connect_user,
    ec2_client_vpn_target_network_association,
    ec2_eip_association,
    ec2_ipam_resource_discovery,
    ec2_ipam_resource_discovery_association,
    ec2_instance_connect_endpoint,
    ec2_snapshot_block_public_access,
    ec2_vpc_block_public_access_exclusion,
    ec2_vpc_block_public_access_options,
    ec2_vpc_endpoint_connection_notification,
    ec2_vpn_connection_route,
    evidently_segment,
    iamoidc_provider,
    inspector_v2_activation,
    msk_cluster_policy,
    msk_vpc_connection,
    media_connect_gateway,
    memory_db_subnet_group,
    open_search_serverless_collection,
    open_search_serverless_vpc_endpoint,
    redshift_endpoint_authorization,
    route_53_profiles_profile,
    s3_storage_lens_group,
    s3_express_bucket_policy,
    s3_express_directory_bucket,
    sage_maker_inference_experiment,
    security_hub_standard,
    transfer_profile,
    cloud_formation_stack_set,
    media_package_v2_channel,
    s3_access_grants_location,
    s3_access_grant,
    s3_access_grants_instance,
    emr_serverless_application,
    config_aggregation_authorization,
    bedrock_application_inference_profile,
    api_gateway_v2_integration,
    sage_maker_mlflow_tracking_server,
    sage_maker_model_bias_job_definition,
    secrets_manager_rotation_schedule,
    deadline_queue_fleet_association,
    ecr_repository_creation_template,
    cloud_formation_lambda_hook,
    ec2_subnet_network_acl_association,
    api_gateway_usage_plan,
    app_config_extension,
    deadline_fleet,
    emr_studio,
    s3_tables_table_bucket,
    cloud_front_realtime_log_config,
    backup_gateway_hypervisor,
    bcm_data_exports_export,
    cloud_formation_guard_hook,
    cloud_front_public_key,
    cloud_trail_event_data_store,
    entity_resolution_id_mapping_workflow,
    entity_resolution_schema_mapping,
    io_t_domain_configuration,
    pca_connector_ad_directory_registration,
    rds_integration,
    config_conformance_pack,
    roles_anywhere_profile,
    code_artifact_domain,
    backup_restore_testing_plan,
    config_stored_query,
    sage_maker_data_quality_job_definition,
    sage_maker_model_explainability_job_definition,
    sage_maker_model_quality_job_definition,
    sage_maker_studio_lifecycle_config,
    ses_dedicated_ip_pool,
    ses_mail_manager_traffic_policy,
    ssm_resource_data_sync,
    bedrock_agent_core_runtime,
    bedrock_agent_core_browser_custom,
    elastic_load_balancing_v2_target_group,
    emr_containers_virtual_cluster,
    entity_resolution_matching_workflow,
    io_t_core_device_advisor_suite_definition,
    ec2_security_group_vpc_association,
    ec2_verified_access_instance,
    kafka_connect_custom_plugin,
    network_manager_transit_gateway_peering,
    open_search_serverless_security_config,
    redshift_integration,
    roles_anywhere_trust_anchor,
    route_53_profiles_profile_association,
    ssm_incidents_response_plan,
    transfer_server,
    glue_database,
    organizations_organizational_unit,
    ec2_ipam_pool_cidr,
    ec2_vpc_gateway_attachment,
    bedrock_prompt,
    comprehend_flywheel,
    data_sync_agent,
    media_tailor_live_source,
    msk_serverless_cluster,
    io_t_site_wise_asset,
    b2_bi_capability,
    cloud_front_key_value_store,
    deadline_monitor,
    guard_duty_malware_protection_plan,
    location_api_key,
    media_package_v2_origin_endpoint,
    pca_connector_ad_connector,
    s3_tables_table_bucket_policy,
    secrets_manager_resource_policy,
    ssm_contacts_contact,
    io_t_thing_group,
    image_builder_lifecycle_policy,
    game_lift_build,
    ecr_replication_configuration,
    ec2_subnet_cidr_block,
    connect_security_profile,
    clean_rooms_ml_training_dataset,
    app_stream_app_block_builder,
    route_53_dnssec,
    sage_maker_user_profile,
    api_gateway_method,

    pub const json_field_names = .{
        .customer_gateway = "AWS::EC2::CustomerGateway",
        .eip = "AWS::EC2::EIP",
        .host = "AWS::EC2::Host",
        .instance = "AWS::EC2::Instance",
        .internet_gateway = "AWS::EC2::InternetGateway",
        .network_acl = "AWS::EC2::NetworkAcl",
        .network_interface = "AWS::EC2::NetworkInterface",
        .route_table = "AWS::EC2::RouteTable",
        .security_group = "AWS::EC2::SecurityGroup",
        .subnet = "AWS::EC2::Subnet",
        .trail = "AWS::CloudTrail::Trail",
        .volume = "AWS::EC2::Volume",
        .vpc = "AWS::EC2::VPC",
        .vpn_connection = "AWS::EC2::VPNConnection",
        .vpn_gateway = "AWS::EC2::VPNGateway",
        .registered_ha_instance = "AWS::EC2::RegisteredHAInstance",
        .nat_gateway = "AWS::EC2::NatGateway",
        .egress_only_internet_gateway = "AWS::EC2::EgressOnlyInternetGateway",
        .vpc_endpoint = "AWS::EC2::VPCEndpoint",
        .vpc_endpoint_service = "AWS::EC2::VPCEndpointService",
        .flow_log = "AWS::EC2::FlowLog",
        .vpc_peering_connection = "AWS::EC2::VPCPeeringConnection",
        .domain = "AWS::Elasticsearch::Domain",
        .group = "AWS::IAM::Group",
        .policy = "AWS::IAM::Policy",
        .role = "AWS::IAM::Role",
        .user = "AWS::IAM::User",
        .load_balancer_v2 = "AWS::ElasticLoadBalancingV2::LoadBalancer",
        .certificate = "AWS::ACM::Certificate",
        .db_instance = "AWS::RDS::DBInstance",
        .db_subnet_group = "AWS::RDS::DBSubnetGroup",
        .db_security_group = "AWS::RDS::DBSecurityGroup",
        .db_snapshot = "AWS::RDS::DBSnapshot",
        .db_cluster = "AWS::RDS::DBCluster",
        .db_cluster_snapshot = "AWS::RDS::DBClusterSnapshot",
        .event_subscription = "AWS::RDS::EventSubscription",
        .bucket = "AWS::S3::Bucket",
        .account_public_access_block = "AWS::S3::AccountPublicAccessBlock",
        .cluster = "AWS::Redshift::Cluster",
        .cluster_snapshot = "AWS::Redshift::ClusterSnapshot",
        .cluster_parameter_group = "AWS::Redshift::ClusterParameterGroup",
        .cluster_security_group = "AWS::Redshift::ClusterSecurityGroup",
        .cluster_subnet_group = "AWS::Redshift::ClusterSubnetGroup",
        .redshift_event_subscription = "AWS::Redshift::EventSubscription",
        .managed_instance_inventory = "AWS::SSM::ManagedInstanceInventory",
        .alarm = "AWS::CloudWatch::Alarm",
        .stack = "AWS::CloudFormation::Stack",
        .load_balancer = "AWS::ElasticLoadBalancing::LoadBalancer",
        .auto_scaling_group = "AWS::AutoScaling::AutoScalingGroup",
        .launch_configuration = "AWS::AutoScaling::LaunchConfiguration",
        .scaling_policy = "AWS::AutoScaling::ScalingPolicy",
        .scheduled_action = "AWS::AutoScaling::ScheduledAction",
        .table = "AWS::DynamoDB::Table",
        .project = "AWS::CodeBuild::Project",
        .rate_based_rule = "AWS::WAF::RateBasedRule",
        .rule = "AWS::WAF::Rule",
        .rule_group = "AWS::WAF::RuleGroup",
        .web_acl = "AWS::WAF::WebACL",
        .regional_rate_based_rule = "AWS::WAFRegional::RateBasedRule",
        .regional_rule = "AWS::WAFRegional::Rule",
        .regional_rule_group = "AWS::WAFRegional::RuleGroup",
        .regional_web_acl = "AWS::WAFRegional::WebACL",
        .distribution = "AWS::CloudFront::Distribution",
        .streaming_distribution = "AWS::CloudFront::StreamingDistribution",
        .function = "AWS::Lambda::Function",
        .network_firewall_firewall = "AWS::NetworkFirewall::Firewall",
        .network_firewall_firewall_policy = "AWS::NetworkFirewall::FirewallPolicy",
        .network_firewall_rule_group = "AWS::NetworkFirewall::RuleGroup",
        .application = "AWS::ElasticBeanstalk::Application",
        .application_version = "AWS::ElasticBeanstalk::ApplicationVersion",
        .environment = "AWS::ElasticBeanstalk::Environment",
        .web_aclv2 = "AWS::WAFv2::WebACL",
        .rule_group_v2 = "AWS::WAFv2::RuleGroup",
        .ip_set_v2 = "AWS::WAFv2::IPSet",
        .regex_pattern_set_v2 = "AWS::WAFv2::RegexPatternSet",
        .managed_rule_set_v2 = "AWS::WAFv2::ManagedRuleSet",
        .encryption_config = "AWS::XRay::EncryptionConfig",
        .association_compliance = "AWS::SSM::AssociationCompliance",
        .patch_compliance = "AWS::SSM::PatchCompliance",
        .protection = "AWS::Shield::Protection",
        .regional_protection = "AWS::ShieldRegional::Protection",
        .conformance_pack_compliance = "AWS::Config::ConformancePackCompliance",
        .resource_compliance = "AWS::Config::ResourceCompliance",
        .stage = "AWS::ApiGateway::Stage",
        .rest_api = "AWS::ApiGateway::RestApi",
        .stage_v2 = "AWS::ApiGatewayV2::Stage",
        .api = "AWS::ApiGatewayV2::Api",
        .pipeline = "AWS::CodePipeline::Pipeline",
        .cloud_formation_provisioned_product = "AWS::ServiceCatalog::CloudFormationProvisionedProduct",
        .cloud_formation_product = "AWS::ServiceCatalog::CloudFormationProduct",
        .portfolio = "AWS::ServiceCatalog::Portfolio",
        .queue = "AWS::SQS::Queue",
        .key = "AWS::KMS::Key",
        .qldb_ledger = "AWS::QLDB::Ledger",
        .secret = "AWS::SecretsManager::Secret",
        .topic = "AWS::SNS::Topic",
        .file_data = "AWS::SSM::FileData",
        .backup_plan = "AWS::Backup::BackupPlan",
        .backup_selection = "AWS::Backup::BackupSelection",
        .backup_vault = "AWS::Backup::BackupVault",
        .backup_recovery_point = "AWS::Backup::RecoveryPoint",
        .ecr_repository = "AWS::ECR::Repository",
        .ecs_cluster = "AWS::ECS::Cluster",
        .ecs_service = "AWS::ECS::Service",
        .ecs_task_definition = "AWS::ECS::TaskDefinition",
        .efs_access_point = "AWS::EFS::AccessPoint",
        .efs_file_system = "AWS::EFS::FileSystem",
        .eks_cluster = "AWS::EKS::Cluster",
        .open_search_domain = "AWS::OpenSearch::Domain",
        .transit_gateway = "AWS::EC2::TransitGateway",
        .kinesis_stream = "AWS::Kinesis::Stream",
        .kinesis_stream_consumer = "AWS::Kinesis::StreamConsumer",
        .code_deploy_application = "AWS::CodeDeploy::Application",
        .code_deploy_deployment_config = "AWS::CodeDeploy::DeploymentConfig",
        .code_deploy_deployment_group = "AWS::CodeDeploy::DeploymentGroup",
        .launch_template = "AWS::EC2::LaunchTemplate",
        .ecr_public_repository = "AWS::ECR::PublicRepository",
        .guard_duty_detector = "AWS::GuardDuty::Detector",
        .emr_security_configuration = "AWS::EMR::SecurityConfiguration",
        .sage_maker_code_repository = "AWS::SageMaker::CodeRepository",
        .route_53_resolver_resolver_endpoint = "AWS::Route53Resolver::ResolverEndpoint",
        .route_53_resolver_resolver_rule = "AWS::Route53Resolver::ResolverRule",
        .route_53_resolver_resolver_rule_association = "AWS::Route53Resolver::ResolverRuleAssociation",
        .dms_replication_subnet_group = "AWS::DMS::ReplicationSubnetGroup",
        .dms_event_subscription = "AWS::DMS::EventSubscription",
        .msk_cluster = "AWS::MSK::Cluster",
        .step_functions_activity = "AWS::StepFunctions::Activity",
        .work_spaces_workspace = "AWS::WorkSpaces::Workspace",
        .work_spaces_connection_alias = "AWS::WorkSpaces::ConnectionAlias",
        .sage_maker_model = "AWS::SageMaker::Model",
        .listener_v2 = "AWS::ElasticLoadBalancingV2::Listener",
        .step_functions_state_machine = "AWS::StepFunctions::StateMachine",
        .batch_job_queue = "AWS::Batch::JobQueue",
        .batch_compute_environment = "AWS::Batch::ComputeEnvironment",
        .access_analyzer_analyzer = "AWS::AccessAnalyzer::Analyzer",
        .athena_work_group = "AWS::Athena::WorkGroup",
        .athena_data_catalog = "AWS::Athena::DataCatalog",
        .detective_graph = "AWS::Detective::Graph",
        .global_accelerator_accelerator = "AWS::GlobalAccelerator::Accelerator",
        .global_accelerator_endpoint_group = "AWS::GlobalAccelerator::EndpointGroup",
        .global_accelerator_listener = "AWS::GlobalAccelerator::Listener",
        .transit_gateway_attachment = "AWS::EC2::TransitGatewayAttachment",
        .transit_gateway_route_table = "AWS::EC2::TransitGatewayRouteTable",
        .dms_certificate = "AWS::DMS::Certificate",
        .app_config_application = "AWS::AppConfig::Application",
        .app_sync_graph_ql_api = "AWS::AppSync::GraphQLApi",
        .data_sync_location_smb = "AWS::DataSync::LocationSMB",
        .data_sync_location_f_sx_lustre = "AWS::DataSync::LocationFSxLustre",
        .data_sync_location_s3 = "AWS::DataSync::LocationS3",
        .data_sync_location_efs = "AWS::DataSync::LocationEFS",
        .data_sync_task = "AWS::DataSync::Task",
        .data_sync_location_nfs = "AWS::DataSync::LocationNFS",
        .network_insights_access_scope_analysis = "AWS::EC2::NetworkInsightsAccessScopeAnalysis",
        .eks_fargate_profile = "AWS::EKS::FargateProfile",
        .glue_job = "AWS::Glue::Job",
        .guard_duty_threat_intel_set = "AWS::GuardDuty::ThreatIntelSet",
        .guard_duty_ip_set = "AWS::GuardDuty::IPSet",
        .sage_maker_workteam = "AWS::SageMaker::Workteam",
        .sage_maker_notebook_instance_lifecycle_config = "AWS::SageMaker::NotebookInstanceLifecycleConfig",
        .service_discovery_service = "AWS::ServiceDiscovery::Service",
        .service_discovery_public_dns_namespace = "AWS::ServiceDiscovery::PublicDnsNamespace",
        .ses_contact_list = "AWS::SES::ContactList",
        .ses_configuration_set = "AWS::SES::ConfigurationSet",
        .route_53_hosted_zone = "AWS::Route53::HostedZone",
        .io_t_events_input = "AWS::IoTEvents::Input",
        .io_t_events_detector_model = "AWS::IoTEvents::DetectorModel",
        .io_t_events_alarm_model = "AWS::IoTEvents::AlarmModel",
        .service_discovery_http_namespace = "AWS::ServiceDiscovery::HttpNamespace",
        .events_event_bus = "AWS::Events::EventBus",
        .image_builder_container_recipe = "AWS::ImageBuilder::ContainerRecipe",
        .image_builder_distribution_configuration = "AWS::ImageBuilder::DistributionConfiguration",
        .image_builder_infrastructure_configuration = "AWS::ImageBuilder::InfrastructureConfiguration",
        .data_sync_location_object_storage = "AWS::DataSync::LocationObjectStorage",
        .data_sync_location_hdfs = "AWS::DataSync::LocationHDFS",
        .glue_classifier = "AWS::Glue::Classifier",
        .route_53_recovery_readiness_cell = "AWS::Route53RecoveryReadiness::Cell",
        .route_53_recovery_readiness_readiness_check = "AWS::Route53RecoveryReadiness::ReadinessCheck",
        .ecr_registry_policy = "AWS::ECR::RegistryPolicy",
        .backup_report_plan = "AWS::Backup::ReportPlan",
        .lightsail_certificate = "AWS::Lightsail::Certificate",
        .rum_app_monitor = "AWS::RUM::AppMonitor",
        .events_endpoint = "AWS::Events::Endpoint",
        .ses_receipt_rule_set = "AWS::SES::ReceiptRuleSet",
        .events_archive = "AWS::Events::Archive",
        .events_api_destination = "AWS::Events::ApiDestination",
        .lightsail_disk = "AWS::Lightsail::Disk",
        .fis_experiment_template = "AWS::FIS::ExperimentTemplate",
        .data_sync_location_f_sx_windows = "AWS::DataSync::LocationFSxWindows",
        .ses_receipt_filter = "AWS::SES::ReceiptFilter",
        .guard_duty_filter = "AWS::GuardDuty::Filter",
        .ses_template = "AWS::SES::Template",
        .amazon_mq_broker = "AWS::AmazonMQ::Broker",
        .app_config_environment = "AWS::AppConfig::Environment",
        .app_config_configuration_profile = "AWS::AppConfig::ConfigurationProfile",
        .cloud_9_environment_ec2 = "AWS::Cloud9::EnvironmentEC2",
        .event_schemas_registry = "AWS::EventSchemas::Registry",
        .event_schemas_registry_policy = "AWS::EventSchemas::RegistryPolicy",
        .event_schemas_discoverer = "AWS::EventSchemas::Discoverer",
        .fraud_detector_label = "AWS::FraudDetector::Label",
        .fraud_detector_entity_type = "AWS::FraudDetector::EntityType",
        .fraud_detector_variable = "AWS::FraudDetector::Variable",
        .fraud_detector_outcome = "AWS::FraudDetector::Outcome",
        .io_t_authorizer = "AWS::IoT::Authorizer",
        .io_t_security_profile = "AWS::IoT::SecurityProfile",
        .io_t_role_alias = "AWS::IoT::RoleAlias",
        .io_t_dimension = "AWS::IoT::Dimension",
        .io_t_analytics_datastore = "AWS::IoTAnalytics::Datastore",
        .lightsail_bucket = "AWS::Lightsail::Bucket",
        .lightsail_static_ip = "AWS::Lightsail::StaticIp",
        .media_package_packaging_group = "AWS::MediaPackage::PackagingGroup",
        .route_53_recovery_readiness_recovery_group = "AWS::Route53RecoveryReadiness::RecoveryGroup",
        .resilience_hub_resiliency_policy = "AWS::ResilienceHub::ResiliencyPolicy",
        .transfer_workflow = "AWS::Transfer::Workflow",
        .eks_identity_provider_config = "AWS::EKS::IdentityProviderConfig",
        .eks_addon = "AWS::EKS::Addon",
        .glue_ml_transform = "AWS::Glue::MLTransform",
        .io_t_policy = "AWS::IoT::Policy",
        .io_t_mitigation_action = "AWS::IoT::MitigationAction",
        .io_t_twin_maker_workspace = "AWS::IoTTwinMaker::Workspace",
        .io_t_twin_maker_entity = "AWS::IoTTwinMaker::Entity",
        .io_t_analytics_dataset = "AWS::IoTAnalytics::Dataset",
        .io_t_analytics_pipeline = "AWS::IoTAnalytics::Pipeline",
        .io_t_analytics_channel = "AWS::IoTAnalytics::Channel",
        .io_t_site_wise_dashboard = "AWS::IoTSiteWise::Dashboard",
        .io_t_site_wise_project = "AWS::IoTSiteWise::Project",
        .io_t_site_wise_portal = "AWS::IoTSiteWise::Portal",
        .io_t_site_wise_asset_model = "AWS::IoTSiteWise::AssetModel",
        .ivs_channel = "AWS::IVS::Channel",
        .ivs_recording_configuration = "AWS::IVS::RecordingConfiguration",
        .ivs_playback_key_pair = "AWS::IVS::PlaybackKeyPair",
        .kinesis_analytics_v2_application = "AWS::KinesisAnalyticsV2::Application",
        .rds_global_cluster = "AWS::RDS::GlobalCluster",
        .s3_multi_region_access_point = "AWS::S3::MultiRegionAccessPoint",
        .device_farm_test_grid_project = "AWS::DeviceFarm::TestGridProject",
        .budgets_budgets_action = "AWS::Budgets::BudgetsAction",
        .lex_bot = "AWS::Lex::Bot",
        .code_guru_reviewer_repository_association = "AWS::CodeGuruReviewer::RepositoryAssociation",
        .io_t_custom_metric = "AWS::IoT::CustomMetric",
        .route_53_resolver_firewall_domain_list = "AWS::Route53Resolver::FirewallDomainList",
        .robo_maker_robot_application_version = "AWS::RoboMaker::RobotApplicationVersion",
        .ec2_traffic_mirror_session = "AWS::EC2::TrafficMirrorSession",
        .io_t_site_wise_gateway = "AWS::IoTSiteWise::Gateway",
        .lex_bot_alias = "AWS::Lex::BotAlias",
        .lookout_metrics_alert = "AWS::LookoutMetrics::Alert",
        .io_t_account_audit_configuration = "AWS::IoT::AccountAuditConfiguration",
        .ec2_traffic_mirror_target = "AWS::EC2::TrafficMirrorTarget",
        .s3_storage_lens = "AWS::S3::StorageLens",
        .io_t_scheduled_audit = "AWS::IoT::ScheduledAudit",
        .events_connection = "AWS::Events::Connection",
        .event_schemas_schema = "AWS::EventSchemas::Schema",
        .media_package_packaging_configuration = "AWS::MediaPackage::PackagingConfiguration",
        .kinesis_video_signaling_channel = "AWS::KinesisVideo::SignalingChannel",
        .app_stream_directory_config = "AWS::AppStream::DirectoryConfig",
        .lookout_vision_project = "AWS::LookoutVision::Project",
        .route_53_recovery_control_cluster = "AWS::Route53RecoveryControl::Cluster",
        .route_53_recovery_control_safety_rule = "AWS::Route53RecoveryControl::SafetyRule",
        .route_53_recovery_control_control_panel = "AWS::Route53RecoveryControl::ControlPanel",
        .route_53_recovery_control_routing_control = "AWS::Route53RecoveryControl::RoutingControl",
        .route_53_recovery_readiness_resource_set = "AWS::Route53RecoveryReadiness::ResourceSet",
        .robo_maker_simulation_application = "AWS::RoboMaker::SimulationApplication",
        .robo_maker_robot_application = "AWS::RoboMaker::RobotApplication",
        .health_lake_fhir_datastore = "AWS::HealthLake::FHIRDatastore",
        .pinpoint_segment = "AWS::Pinpoint::Segment",
        .pinpoint_application_settings = "AWS::Pinpoint::ApplicationSettings",
        .events_rule = "AWS::Events::Rule",
        .ec2_dhcp_options = "AWS::EC2::DHCPOptions",
        .ec2_network_insights_path = "AWS::EC2::NetworkInsightsPath",
        .ec2_traffic_mirror_filter = "AWS::EC2::TrafficMirrorFilter",
        .ec2_ipam = "AWS::EC2::IPAM",
        .io_t_twin_maker_scene = "AWS::IoTTwinMaker::Scene",
        .network_manager_transit_gateway_registration = "AWS::NetworkManager::TransitGatewayRegistration",
        .customer_profiles_domain = "AWS::CustomerProfiles::Domain",
        .auto_scaling_warm_pool = "AWS::AutoScaling::WarmPool",
        .connect_phone_number = "AWS::Connect::PhoneNumber",
        .app_config_deployment_strategy = "AWS::AppConfig::DeploymentStrategy",
        .app_flow_flow = "AWS::AppFlow::Flow",
        .audit_manager_assessment = "AWS::AuditManager::Assessment",
        .cloud_watch_metric_stream = "AWS::CloudWatch::MetricStream",
        .device_farm_instance_profile = "AWS::DeviceFarm::InstanceProfile",
        .device_farm_project = "AWS::DeviceFarm::Project",
        .ec2_ec2_fleet = "AWS::EC2::EC2Fleet",
        .ec2_subnet_route_table_association = "AWS::EC2::SubnetRouteTableAssociation",
        .ecr_pull_through_cache_rule = "AWS::ECR::PullThroughCacheRule",
        .ground_station_config = "AWS::GroundStation::Config",
        .image_builder_image_pipeline = "AWS::ImageBuilder::ImagePipeline",
        .io_t_fleet_metric = "AWS::IoT::FleetMetric",
        .io_t_wireless_service_profile = "AWS::IoTWireless::ServiceProfile",
        .network_manager_device = "AWS::NetworkManager::Device",
        .network_manager_global_network = "AWS::NetworkManager::GlobalNetwork",
        .network_manager_link = "AWS::NetworkManager::Link",
        .network_manager_site = "AWS::NetworkManager::Site",
        .panorama_package = "AWS::Panorama::Package",
        .pinpoint_app = "AWS::Pinpoint::App",
        .redshift_scheduled_action = "AWS::Redshift::ScheduledAction",
        .route_53_resolver_firewall_rule_group_association = "AWS::Route53Resolver::FirewallRuleGroupAssociation",
        .sage_maker_app_image_config = "AWS::SageMaker::AppImageConfig",
        .sage_maker_image = "AWS::SageMaker::Image",
        .ecs_task_set = "AWS::ECS::TaskSet",
        .cassandra_keyspace = "AWS::Cassandra::Keyspace",
        .signer_signing_profile = "AWS::Signer::SigningProfile",
        .amplify_app = "AWS::Amplify::App",
        .app_mesh_virtual_node = "AWS::AppMesh::VirtualNode",
        .app_mesh_virtual_service = "AWS::AppMesh::VirtualService",
        .app_runner_vpc_connector = "AWS::AppRunner::VpcConnector",
        .app_stream_application = "AWS::AppStream::Application",
        .code_artifact_repository = "AWS::CodeArtifact::Repository",
        .ec2_prefix_list = "AWS::EC2::PrefixList",
        .ec2_spot_fleet = "AWS::EC2::SpotFleet",
        .evidently_project = "AWS::Evidently::Project",
        .forecast_dataset = "AWS::Forecast::Dataset",
        .iamsaml_provider = "AWS::IAM::SAMLProvider",
        .iam_server_certificate = "AWS::IAM::ServerCertificate",
        .pinpoint_campaign = "AWS::Pinpoint::Campaign",
        .pinpoint_in_app_template = "AWS::Pinpoint::InAppTemplate",
        .sage_maker_domain = "AWS::SageMaker::Domain",
        .transfer_agreement = "AWS::Transfer::Agreement",
        .transfer_connector = "AWS::Transfer::Connector",
        .kinesis_firehose_delivery_stream = "AWS::KinesisFirehose::DeliveryStream",
        .amplify_branch = "AWS::Amplify::Branch",
        .app_integrations_event_integration = "AWS::AppIntegrations::EventIntegration",
        .app_mesh_route = "AWS::AppMesh::Route",
        .athena_prepared_statement = "AWS::Athena::PreparedStatement",
        .ec2_ipam_scope = "AWS::EC2::IPAMScope",
        .evidently_launch = "AWS::Evidently::Launch",
        .forecast_dataset_group = "AWS::Forecast::DatasetGroup",
        .greengrass_v2_component_version = "AWS::GreengrassV2::ComponentVersion",
        .ground_station_mission_profile = "AWS::GroundStation::MissionProfile",
        .media_connect_flow_entitlement = "AWS::MediaConnect::FlowEntitlement",
        .media_connect_flow_vpc_interface = "AWS::MediaConnect::FlowVpcInterface",
        .media_tailor_playback_configuration = "AWS::MediaTailor::PlaybackConfiguration",
        .msk_configuration = "AWS::MSK::Configuration",
        .personalize_dataset = "AWS::Personalize::Dataset",
        .personalize_schema = "AWS::Personalize::Schema",
        .personalize_solution = "AWS::Personalize::Solution",
        .pinpoint_email_template = "AWS::Pinpoint::EmailTemplate",
        .pinpoint_event_stream = "AWS::Pinpoint::EventStream",
        .resilience_hub_app = "AWS::ResilienceHub::App",
        .acmpca_certificate_authority = "AWS::ACMPCA::CertificateAuthority",
        .app_config_hosted_configuration_version = "AWS::AppConfig::HostedConfigurationVersion",
        .app_mesh_virtual_gateway = "AWS::AppMesh::VirtualGateway",
        .app_mesh_virtual_router = "AWS::AppMesh::VirtualRouter",
        .app_runner_service = "AWS::AppRunner::Service",
        .customer_profiles_object_type = "AWS::CustomerProfiles::ObjectType",
        .dms_endpoint = "AWS::DMS::Endpoint",
        .ec2_capacity_reservation = "AWS::EC2::CapacityReservation",
        .ec2_client_vpn_endpoint = "AWS::EC2::ClientVpnEndpoint",
        .kendra_index = "AWS::Kendra::Index",
        .kinesis_video_stream = "AWS::KinesisVideo::Stream",
        .logs_destination = "AWS::Logs::Destination",
        .pinpoint_email_channel = "AWS::Pinpoint::EmailChannel",
        .s3_access_point = "AWS::S3::AccessPoint",
        .network_manager_customer_gateway_association = "AWS::NetworkManager::CustomerGatewayAssociation",
        .network_manager_link_association = "AWS::NetworkManager::LinkAssociation",
        .io_t_wireless_multicast_group = "AWS::IoTWireless::MulticastGroup",
        .personalize_dataset_group = "AWS::Personalize::DatasetGroup",
        .io_t_twin_maker_component_type = "AWS::IoTTwinMaker::ComponentType",
        .code_build_report_group = "AWS::CodeBuild::ReportGroup",
        .sage_maker_feature_group = "AWS::SageMaker::FeatureGroup",
        .msk_batch_scram_secret = "AWS::MSK::BatchScramSecret",
        .app_stream_stack = "AWS::AppStream::Stack",
        .io_t_job_template = "AWS::IoT::JobTemplate",
        .io_t_wireless_fuota_task = "AWS::IoTWireless::FuotaTask",
        .io_t_provisioning_template = "AWS::IoT::ProvisioningTemplate",
        .inspector_v2_filter = "AWS::InspectorV2::Filter",
        .route_53_resolver_resolver_query_logging_config_association = "AWS::Route53Resolver::ResolverQueryLoggingConfigAssociation",
        .service_discovery_instance = "AWS::ServiceDiscovery::Instance",
        .transfer_certificate = "AWS::Transfer::Certificate",
        .media_connect_flow_source = "AWS::MediaConnect::FlowSource",
        .aps_rule_groups_namespace = "AWS::APS::RuleGroupsNamespace",
        .code_guru_profiler_profiling_group = "AWS::CodeGuruProfiler::ProfilingGroup",
        .route_53_resolver_resolver_query_logging_config = "AWS::Route53Resolver::ResolverQueryLoggingConfig",
        .batch_scheduling_policy = "AWS::Batch::SchedulingPolicy",
        .acmpca_certificate_authority_activation = "AWS::ACMPCA::CertificateAuthorityActivation",
        .app_mesh_gateway_route = "AWS::AppMesh::GatewayRoute",
        .app_mesh_mesh = "AWS::AppMesh::Mesh",
        .connect_instance = "AWS::Connect::Instance",
        .connect_quick_connect = "AWS::Connect::QuickConnect",
        .ec2_carrier_gateway = "AWS::EC2::CarrierGateway",
        .ec2_ipam_pool = "AWS::EC2::IPAMPool",
        .ec2_transit_gateway_connect = "AWS::EC2::TransitGatewayConnect",
        .ec2_transit_gateway_multicast_domain = "AWS::EC2::TransitGatewayMulticastDomain",
        .ecs_capacity_provider = "AWS::ECS::CapacityProvider",
        .iam_instance_profile = "AWS::IAM::InstanceProfile",
        .io_tca_certificate = "AWS::IoT::CACertificate",
        .io_t_twin_maker_sync_job = "AWS::IoTTwinMaker::SyncJob",
        .kafka_connect_connector = "AWS::KafkaConnect::Connector",
        .lambda_code_signing_config = "AWS::Lambda::CodeSigningConfig",
        .network_manager_connect_peer = "AWS::NetworkManager::ConnectPeer",
        .resource_explorer_2_index = "AWS::ResourceExplorer2::Index",
        .app_stream_fleet = "AWS::AppStream::Fleet",
        .cognito_user_pool = "AWS::Cognito::UserPool",
        .cognito_user_pool_client = "AWS::Cognito::UserPoolClient",
        .cognito_user_pool_group = "AWS::Cognito::UserPoolGroup",
        .ec2_network_insights_access_scope = "AWS::EC2::NetworkInsightsAccessScope",
        .ec2_network_insights_analysis = "AWS::EC2::NetworkInsightsAnalysis",
        .grafana_workspace = "AWS::Grafana::Workspace",
        .ground_station_dataflow_endpoint_group = "AWS::GroundStation::DataflowEndpointGroup",
        .image_builder_image_recipe = "AWS::ImageBuilder::ImageRecipe",
        .kms_alias = "AWS::KMS::Alias",
        .m2_environment = "AWS::M2::Environment",
        .quick_sight_data_source = "AWS::QuickSight::DataSource",
        .quick_sight_template = "AWS::QuickSight::Template",
        .quick_sight_theme = "AWS::QuickSight::Theme",
        .rds_option_group = "AWS::RDS::OptionGroup",
        .redshift_endpoint_access = "AWS::Redshift::EndpointAccess",
        .route_53_resolver_firewall_rule_group = "AWS::Route53Resolver::FirewallRuleGroup",
        .ssm_document = "AWS::SSM::Document",
        .app_config_extension_association = "AWS::AppConfig::ExtensionAssociation",
        .app_integrations_application = "AWS::AppIntegrations::Application",
        .app_sync_api_cache = "AWS::AppSync::ApiCache",
        .bedrock_guardrail = "AWS::Bedrock::Guardrail",
        .bedrock_knowledge_base = "AWS::Bedrock::KnowledgeBase",
        .cognito_identity_pool = "AWS::Cognito::IdentityPool",
        .connect_rule = "AWS::Connect::Rule",
        .connect_user = "AWS::Connect::User",
        .ec2_client_vpn_target_network_association = "AWS::EC2::ClientVpnTargetNetworkAssociation",
        .ec2_eip_association = "AWS::EC2::EIPAssociation",
        .ec2_ipam_resource_discovery = "AWS::EC2::IPAMResourceDiscovery",
        .ec2_ipam_resource_discovery_association = "AWS::EC2::IPAMResourceDiscoveryAssociation",
        .ec2_instance_connect_endpoint = "AWS::EC2::InstanceConnectEndpoint",
        .ec2_snapshot_block_public_access = "AWS::EC2::SnapshotBlockPublicAccess",
        .ec2_vpc_block_public_access_exclusion = "AWS::EC2::VPCBlockPublicAccessExclusion",
        .ec2_vpc_block_public_access_options = "AWS::EC2::VPCBlockPublicAccessOptions",
        .ec2_vpc_endpoint_connection_notification = "AWS::EC2::VPCEndpointConnectionNotification",
        .ec2_vpn_connection_route = "AWS::EC2::VPNConnectionRoute",
        .evidently_segment = "AWS::Evidently::Segment",
        .iamoidc_provider = "AWS::IAM::OIDCProvider",
        .inspector_v2_activation = "AWS::InspectorV2::Activation",
        .msk_cluster_policy = "AWS::MSK::ClusterPolicy",
        .msk_vpc_connection = "AWS::MSK::VpcConnection",
        .media_connect_gateway = "AWS::MediaConnect::Gateway",
        .memory_db_subnet_group = "AWS::MemoryDB::SubnetGroup",
        .open_search_serverless_collection = "AWS::OpenSearchServerless::Collection",
        .open_search_serverless_vpc_endpoint = "AWS::OpenSearchServerless::VpcEndpoint",
        .redshift_endpoint_authorization = "AWS::Redshift::EndpointAuthorization",
        .route_53_profiles_profile = "AWS::Route53Profiles::Profile",
        .s3_storage_lens_group = "AWS::S3::StorageLensGroup",
        .s3_express_bucket_policy = "AWS::S3Express::BucketPolicy",
        .s3_express_directory_bucket = "AWS::S3Express::DirectoryBucket",
        .sage_maker_inference_experiment = "AWS::SageMaker::InferenceExperiment",
        .security_hub_standard = "AWS::SecurityHub::Standard",
        .transfer_profile = "AWS::Transfer::Profile",
        .cloud_formation_stack_set = "AWS::CloudFormation::StackSet",
        .media_package_v2_channel = "AWS::MediaPackageV2::Channel",
        .s3_access_grants_location = "AWS::S3::AccessGrantsLocation",
        .s3_access_grant = "AWS::S3::AccessGrant",
        .s3_access_grants_instance = "AWS::S3::AccessGrantsInstance",
        .emr_serverless_application = "AWS::EMRServerless::Application",
        .config_aggregation_authorization = "AWS::Config::AggregationAuthorization",
        .bedrock_application_inference_profile = "AWS::Bedrock::ApplicationInferenceProfile",
        .api_gateway_v2_integration = "AWS::ApiGatewayV2::Integration",
        .sage_maker_mlflow_tracking_server = "AWS::SageMaker::MlflowTrackingServer",
        .sage_maker_model_bias_job_definition = "AWS::SageMaker::ModelBiasJobDefinition",
        .secrets_manager_rotation_schedule = "AWS::SecretsManager::RotationSchedule",
        .deadline_queue_fleet_association = "AWS::Deadline::QueueFleetAssociation",
        .ecr_repository_creation_template = "AWS::ECR::RepositoryCreationTemplate",
        .cloud_formation_lambda_hook = "AWS::CloudFormation::LambdaHook",
        .ec2_subnet_network_acl_association = "AWS::EC2::SubnetNetworkAclAssociation",
        .api_gateway_usage_plan = "AWS::ApiGateway::UsagePlan",
        .app_config_extension = "AWS::AppConfig::Extension",
        .deadline_fleet = "AWS::Deadline::Fleet",
        .emr_studio = "AWS::EMR::Studio",
        .s3_tables_table_bucket = "AWS::S3Tables::TableBucket",
        .cloud_front_realtime_log_config = "AWS::CloudFront::RealtimeLogConfig",
        .backup_gateway_hypervisor = "AWS::BackupGateway::Hypervisor",
        .bcm_data_exports_export = "AWS::BCMDataExports::Export",
        .cloud_formation_guard_hook = "AWS::CloudFormation::GuardHook",
        .cloud_front_public_key = "AWS::CloudFront::PublicKey",
        .cloud_trail_event_data_store = "AWS::CloudTrail::EventDataStore",
        .entity_resolution_id_mapping_workflow = "AWS::EntityResolution::IdMappingWorkflow",
        .entity_resolution_schema_mapping = "AWS::EntityResolution::SchemaMapping",
        .io_t_domain_configuration = "AWS::IoT::DomainConfiguration",
        .pca_connector_ad_directory_registration = "AWS::PCAConnectorAD::DirectoryRegistration",
        .rds_integration = "AWS::RDS::Integration",
        .config_conformance_pack = "AWS::Config::ConformancePack",
        .roles_anywhere_profile = "AWS::RolesAnywhere::Profile",
        .code_artifact_domain = "AWS::CodeArtifact::Domain",
        .backup_restore_testing_plan = "AWS::Backup::RestoreTestingPlan",
        .config_stored_query = "AWS::Config::StoredQuery",
        .sage_maker_data_quality_job_definition = "AWS::SageMaker::DataQualityJobDefinition",
        .sage_maker_model_explainability_job_definition = "AWS::SageMaker::ModelExplainabilityJobDefinition",
        .sage_maker_model_quality_job_definition = "AWS::SageMaker::ModelQualityJobDefinition",
        .sage_maker_studio_lifecycle_config = "AWS::SageMaker::StudioLifecycleConfig",
        .ses_dedicated_ip_pool = "AWS::SES::DedicatedIpPool",
        .ses_mail_manager_traffic_policy = "AWS::SES::MailManagerTrafficPolicy",
        .ssm_resource_data_sync = "AWS::SSM::ResourceDataSync",
        .bedrock_agent_core_runtime = "AWS::BedrockAgentCore::Runtime",
        .bedrock_agent_core_browser_custom = "AWS::BedrockAgentCore::BrowserCustom",
        .elastic_load_balancing_v2_target_group = "AWS::ElasticLoadBalancingV2::TargetGroup",
        .emr_containers_virtual_cluster = "AWS::EMRContainers::VirtualCluster",
        .entity_resolution_matching_workflow = "AWS::EntityResolution::MatchingWorkflow",
        .io_t_core_device_advisor_suite_definition = "AWS::IoTCoreDeviceAdvisor::SuiteDefinition",
        .ec2_security_group_vpc_association = "AWS::EC2::SecurityGroupVpcAssociation",
        .ec2_verified_access_instance = "AWS::EC2::VerifiedAccessInstance",
        .kafka_connect_custom_plugin = "AWS::KafkaConnect::CustomPlugin",
        .network_manager_transit_gateway_peering = "AWS::NetworkManager::TransitGatewayPeering",
        .open_search_serverless_security_config = "AWS::OpenSearchServerless::SecurityConfig",
        .redshift_integration = "AWS::Redshift::Integration",
        .roles_anywhere_trust_anchor = "AWS::RolesAnywhere::TrustAnchor",
        .route_53_profiles_profile_association = "AWS::Route53Profiles::ProfileAssociation",
        .ssm_incidents_response_plan = "AWS::SSMIncidents::ResponsePlan",
        .transfer_server = "AWS::Transfer::Server",
        .glue_database = "AWS::Glue::Database",
        .organizations_organizational_unit = "AWS::Organizations::OrganizationalUnit",
        .ec2_ipam_pool_cidr = "AWS::EC2::IPAMPoolCidr",
        .ec2_vpc_gateway_attachment = "AWS::EC2::VPCGatewayAttachment",
        .bedrock_prompt = "AWS::Bedrock::Prompt",
        .comprehend_flywheel = "AWS::Comprehend::Flywheel",
        .data_sync_agent = "AWS::DataSync::Agent",
        .media_tailor_live_source = "AWS::MediaTailor::LiveSource",
        .msk_serverless_cluster = "AWS::MSK::ServerlessCluster",
        .io_t_site_wise_asset = "AWS::IoTSiteWise::Asset",
        .b2_bi_capability = "AWS::B2BI::Capability",
        .cloud_front_key_value_store = "AWS::CloudFront::KeyValueStore",
        .deadline_monitor = "AWS::Deadline::Monitor",
        .guard_duty_malware_protection_plan = "AWS::GuardDuty::MalwareProtectionPlan",
        .location_api_key = "AWS::Location::APIKey",
        .media_package_v2_origin_endpoint = "AWS::MediaPackageV2::OriginEndpoint",
        .pca_connector_ad_connector = "AWS::PCAConnectorAD::Connector",
        .s3_tables_table_bucket_policy = "AWS::S3Tables::TableBucketPolicy",
        .secrets_manager_resource_policy = "AWS::SecretsManager::ResourcePolicy",
        .ssm_contacts_contact = "AWS::SSMContacts::Contact",
        .io_t_thing_group = "AWS::IoT::ThingGroup",
        .image_builder_lifecycle_policy = "AWS::ImageBuilder::LifecyclePolicy",
        .game_lift_build = "AWS::GameLift::Build",
        .ecr_replication_configuration = "AWS::ECR::ReplicationConfiguration",
        .ec2_subnet_cidr_block = "AWS::EC2::SubnetCidrBlock",
        .connect_security_profile = "AWS::Connect::SecurityProfile",
        .clean_rooms_ml_training_dataset = "AWS::CleanRoomsML::TrainingDataset",
        .app_stream_app_block_builder = "AWS::AppStream::AppBlockBuilder",
        .route_53_dnssec = "AWS::Route53::DNSSEC",
        .sage_maker_user_profile = "AWS::SageMaker::UserProfile",
        .api_gateway_method = "AWS::ApiGateway::Method",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .customer_gateway => "AWS::EC2::CustomerGateway",
            .eip => "AWS::EC2::EIP",
            .host => "AWS::EC2::Host",
            .instance => "AWS::EC2::Instance",
            .internet_gateway => "AWS::EC2::InternetGateway",
            .network_acl => "AWS::EC2::NetworkAcl",
            .network_interface => "AWS::EC2::NetworkInterface",
            .route_table => "AWS::EC2::RouteTable",
            .security_group => "AWS::EC2::SecurityGroup",
            .subnet => "AWS::EC2::Subnet",
            .trail => "AWS::CloudTrail::Trail",
            .volume => "AWS::EC2::Volume",
            .vpc => "AWS::EC2::VPC",
            .vpn_connection => "AWS::EC2::VPNConnection",
            .vpn_gateway => "AWS::EC2::VPNGateway",
            .registered_ha_instance => "AWS::EC2::RegisteredHAInstance",
            .nat_gateway => "AWS::EC2::NatGateway",
            .egress_only_internet_gateway => "AWS::EC2::EgressOnlyInternetGateway",
            .vpc_endpoint => "AWS::EC2::VPCEndpoint",
            .vpc_endpoint_service => "AWS::EC2::VPCEndpointService",
            .flow_log => "AWS::EC2::FlowLog",
            .vpc_peering_connection => "AWS::EC2::VPCPeeringConnection",
            .domain => "AWS::Elasticsearch::Domain",
            .group => "AWS::IAM::Group",
            .policy => "AWS::IAM::Policy",
            .role => "AWS::IAM::Role",
            .user => "AWS::IAM::User",
            .load_balancer_v2 => "AWS::ElasticLoadBalancingV2::LoadBalancer",
            .certificate => "AWS::ACM::Certificate",
            .db_instance => "AWS::RDS::DBInstance",
            .db_subnet_group => "AWS::RDS::DBSubnetGroup",
            .db_security_group => "AWS::RDS::DBSecurityGroup",
            .db_snapshot => "AWS::RDS::DBSnapshot",
            .db_cluster => "AWS::RDS::DBCluster",
            .db_cluster_snapshot => "AWS::RDS::DBClusterSnapshot",
            .event_subscription => "AWS::RDS::EventSubscription",
            .bucket => "AWS::S3::Bucket",
            .account_public_access_block => "AWS::S3::AccountPublicAccessBlock",
            .cluster => "AWS::Redshift::Cluster",
            .cluster_snapshot => "AWS::Redshift::ClusterSnapshot",
            .cluster_parameter_group => "AWS::Redshift::ClusterParameterGroup",
            .cluster_security_group => "AWS::Redshift::ClusterSecurityGroup",
            .cluster_subnet_group => "AWS::Redshift::ClusterSubnetGroup",
            .redshift_event_subscription => "AWS::Redshift::EventSubscription",
            .managed_instance_inventory => "AWS::SSM::ManagedInstanceInventory",
            .alarm => "AWS::CloudWatch::Alarm",
            .stack => "AWS::CloudFormation::Stack",
            .load_balancer => "AWS::ElasticLoadBalancing::LoadBalancer",
            .auto_scaling_group => "AWS::AutoScaling::AutoScalingGroup",
            .launch_configuration => "AWS::AutoScaling::LaunchConfiguration",
            .scaling_policy => "AWS::AutoScaling::ScalingPolicy",
            .scheduled_action => "AWS::AutoScaling::ScheduledAction",
            .table => "AWS::DynamoDB::Table",
            .project => "AWS::CodeBuild::Project",
            .rate_based_rule => "AWS::WAF::RateBasedRule",
            .rule => "AWS::WAF::Rule",
            .rule_group => "AWS::WAF::RuleGroup",
            .web_acl => "AWS::WAF::WebACL",
            .regional_rate_based_rule => "AWS::WAFRegional::RateBasedRule",
            .regional_rule => "AWS::WAFRegional::Rule",
            .regional_rule_group => "AWS::WAFRegional::RuleGroup",
            .regional_web_acl => "AWS::WAFRegional::WebACL",
            .distribution => "AWS::CloudFront::Distribution",
            .streaming_distribution => "AWS::CloudFront::StreamingDistribution",
            .function => "AWS::Lambda::Function",
            .network_firewall_firewall => "AWS::NetworkFirewall::Firewall",
            .network_firewall_firewall_policy => "AWS::NetworkFirewall::FirewallPolicy",
            .network_firewall_rule_group => "AWS::NetworkFirewall::RuleGroup",
            .application => "AWS::ElasticBeanstalk::Application",
            .application_version => "AWS::ElasticBeanstalk::ApplicationVersion",
            .environment => "AWS::ElasticBeanstalk::Environment",
            .web_aclv2 => "AWS::WAFv2::WebACL",
            .rule_group_v2 => "AWS::WAFv2::RuleGroup",
            .ip_set_v2 => "AWS::WAFv2::IPSet",
            .regex_pattern_set_v2 => "AWS::WAFv2::RegexPatternSet",
            .managed_rule_set_v2 => "AWS::WAFv2::ManagedRuleSet",
            .encryption_config => "AWS::XRay::EncryptionConfig",
            .association_compliance => "AWS::SSM::AssociationCompliance",
            .patch_compliance => "AWS::SSM::PatchCompliance",
            .protection => "AWS::Shield::Protection",
            .regional_protection => "AWS::ShieldRegional::Protection",
            .conformance_pack_compliance => "AWS::Config::ConformancePackCompliance",
            .resource_compliance => "AWS::Config::ResourceCompliance",
            .stage => "AWS::ApiGateway::Stage",
            .rest_api => "AWS::ApiGateway::RestApi",
            .stage_v2 => "AWS::ApiGatewayV2::Stage",
            .api => "AWS::ApiGatewayV2::Api",
            .pipeline => "AWS::CodePipeline::Pipeline",
            .cloud_formation_provisioned_product => "AWS::ServiceCatalog::CloudFormationProvisionedProduct",
            .cloud_formation_product => "AWS::ServiceCatalog::CloudFormationProduct",
            .portfolio => "AWS::ServiceCatalog::Portfolio",
            .queue => "AWS::SQS::Queue",
            .key => "AWS::KMS::Key",
            .qldb_ledger => "AWS::QLDB::Ledger",
            .secret => "AWS::SecretsManager::Secret",
            .topic => "AWS::SNS::Topic",
            .file_data => "AWS::SSM::FileData",
            .backup_plan => "AWS::Backup::BackupPlan",
            .backup_selection => "AWS::Backup::BackupSelection",
            .backup_vault => "AWS::Backup::BackupVault",
            .backup_recovery_point => "AWS::Backup::RecoveryPoint",
            .ecr_repository => "AWS::ECR::Repository",
            .ecs_cluster => "AWS::ECS::Cluster",
            .ecs_service => "AWS::ECS::Service",
            .ecs_task_definition => "AWS::ECS::TaskDefinition",
            .efs_access_point => "AWS::EFS::AccessPoint",
            .efs_file_system => "AWS::EFS::FileSystem",
            .eks_cluster => "AWS::EKS::Cluster",
            .open_search_domain => "AWS::OpenSearch::Domain",
            .transit_gateway => "AWS::EC2::TransitGateway",
            .kinesis_stream => "AWS::Kinesis::Stream",
            .kinesis_stream_consumer => "AWS::Kinesis::StreamConsumer",
            .code_deploy_application => "AWS::CodeDeploy::Application",
            .code_deploy_deployment_config => "AWS::CodeDeploy::DeploymentConfig",
            .code_deploy_deployment_group => "AWS::CodeDeploy::DeploymentGroup",
            .launch_template => "AWS::EC2::LaunchTemplate",
            .ecr_public_repository => "AWS::ECR::PublicRepository",
            .guard_duty_detector => "AWS::GuardDuty::Detector",
            .emr_security_configuration => "AWS::EMR::SecurityConfiguration",
            .sage_maker_code_repository => "AWS::SageMaker::CodeRepository",
            .route_53_resolver_resolver_endpoint => "AWS::Route53Resolver::ResolverEndpoint",
            .route_53_resolver_resolver_rule => "AWS::Route53Resolver::ResolverRule",
            .route_53_resolver_resolver_rule_association => "AWS::Route53Resolver::ResolverRuleAssociation",
            .dms_replication_subnet_group => "AWS::DMS::ReplicationSubnetGroup",
            .dms_event_subscription => "AWS::DMS::EventSubscription",
            .msk_cluster => "AWS::MSK::Cluster",
            .step_functions_activity => "AWS::StepFunctions::Activity",
            .work_spaces_workspace => "AWS::WorkSpaces::Workspace",
            .work_spaces_connection_alias => "AWS::WorkSpaces::ConnectionAlias",
            .sage_maker_model => "AWS::SageMaker::Model",
            .listener_v2 => "AWS::ElasticLoadBalancingV2::Listener",
            .step_functions_state_machine => "AWS::StepFunctions::StateMachine",
            .batch_job_queue => "AWS::Batch::JobQueue",
            .batch_compute_environment => "AWS::Batch::ComputeEnvironment",
            .access_analyzer_analyzer => "AWS::AccessAnalyzer::Analyzer",
            .athena_work_group => "AWS::Athena::WorkGroup",
            .athena_data_catalog => "AWS::Athena::DataCatalog",
            .detective_graph => "AWS::Detective::Graph",
            .global_accelerator_accelerator => "AWS::GlobalAccelerator::Accelerator",
            .global_accelerator_endpoint_group => "AWS::GlobalAccelerator::EndpointGroup",
            .global_accelerator_listener => "AWS::GlobalAccelerator::Listener",
            .transit_gateway_attachment => "AWS::EC2::TransitGatewayAttachment",
            .transit_gateway_route_table => "AWS::EC2::TransitGatewayRouteTable",
            .dms_certificate => "AWS::DMS::Certificate",
            .app_config_application => "AWS::AppConfig::Application",
            .app_sync_graph_ql_api => "AWS::AppSync::GraphQLApi",
            .data_sync_location_smb => "AWS::DataSync::LocationSMB",
            .data_sync_location_f_sx_lustre => "AWS::DataSync::LocationFSxLustre",
            .data_sync_location_s3 => "AWS::DataSync::LocationS3",
            .data_sync_location_efs => "AWS::DataSync::LocationEFS",
            .data_sync_task => "AWS::DataSync::Task",
            .data_sync_location_nfs => "AWS::DataSync::LocationNFS",
            .network_insights_access_scope_analysis => "AWS::EC2::NetworkInsightsAccessScopeAnalysis",
            .eks_fargate_profile => "AWS::EKS::FargateProfile",
            .glue_job => "AWS::Glue::Job",
            .guard_duty_threat_intel_set => "AWS::GuardDuty::ThreatIntelSet",
            .guard_duty_ip_set => "AWS::GuardDuty::IPSet",
            .sage_maker_workteam => "AWS::SageMaker::Workteam",
            .sage_maker_notebook_instance_lifecycle_config => "AWS::SageMaker::NotebookInstanceLifecycleConfig",
            .service_discovery_service => "AWS::ServiceDiscovery::Service",
            .service_discovery_public_dns_namespace => "AWS::ServiceDiscovery::PublicDnsNamespace",
            .ses_contact_list => "AWS::SES::ContactList",
            .ses_configuration_set => "AWS::SES::ConfigurationSet",
            .route_53_hosted_zone => "AWS::Route53::HostedZone",
            .io_t_events_input => "AWS::IoTEvents::Input",
            .io_t_events_detector_model => "AWS::IoTEvents::DetectorModel",
            .io_t_events_alarm_model => "AWS::IoTEvents::AlarmModel",
            .service_discovery_http_namespace => "AWS::ServiceDiscovery::HttpNamespace",
            .events_event_bus => "AWS::Events::EventBus",
            .image_builder_container_recipe => "AWS::ImageBuilder::ContainerRecipe",
            .image_builder_distribution_configuration => "AWS::ImageBuilder::DistributionConfiguration",
            .image_builder_infrastructure_configuration => "AWS::ImageBuilder::InfrastructureConfiguration",
            .data_sync_location_object_storage => "AWS::DataSync::LocationObjectStorage",
            .data_sync_location_hdfs => "AWS::DataSync::LocationHDFS",
            .glue_classifier => "AWS::Glue::Classifier",
            .route_53_recovery_readiness_cell => "AWS::Route53RecoveryReadiness::Cell",
            .route_53_recovery_readiness_readiness_check => "AWS::Route53RecoveryReadiness::ReadinessCheck",
            .ecr_registry_policy => "AWS::ECR::RegistryPolicy",
            .backup_report_plan => "AWS::Backup::ReportPlan",
            .lightsail_certificate => "AWS::Lightsail::Certificate",
            .rum_app_monitor => "AWS::RUM::AppMonitor",
            .events_endpoint => "AWS::Events::Endpoint",
            .ses_receipt_rule_set => "AWS::SES::ReceiptRuleSet",
            .events_archive => "AWS::Events::Archive",
            .events_api_destination => "AWS::Events::ApiDestination",
            .lightsail_disk => "AWS::Lightsail::Disk",
            .fis_experiment_template => "AWS::FIS::ExperimentTemplate",
            .data_sync_location_f_sx_windows => "AWS::DataSync::LocationFSxWindows",
            .ses_receipt_filter => "AWS::SES::ReceiptFilter",
            .guard_duty_filter => "AWS::GuardDuty::Filter",
            .ses_template => "AWS::SES::Template",
            .amazon_mq_broker => "AWS::AmazonMQ::Broker",
            .app_config_environment => "AWS::AppConfig::Environment",
            .app_config_configuration_profile => "AWS::AppConfig::ConfigurationProfile",
            .cloud_9_environment_ec2 => "AWS::Cloud9::EnvironmentEC2",
            .event_schemas_registry => "AWS::EventSchemas::Registry",
            .event_schemas_registry_policy => "AWS::EventSchemas::RegistryPolicy",
            .event_schemas_discoverer => "AWS::EventSchemas::Discoverer",
            .fraud_detector_label => "AWS::FraudDetector::Label",
            .fraud_detector_entity_type => "AWS::FraudDetector::EntityType",
            .fraud_detector_variable => "AWS::FraudDetector::Variable",
            .fraud_detector_outcome => "AWS::FraudDetector::Outcome",
            .io_t_authorizer => "AWS::IoT::Authorizer",
            .io_t_security_profile => "AWS::IoT::SecurityProfile",
            .io_t_role_alias => "AWS::IoT::RoleAlias",
            .io_t_dimension => "AWS::IoT::Dimension",
            .io_t_analytics_datastore => "AWS::IoTAnalytics::Datastore",
            .lightsail_bucket => "AWS::Lightsail::Bucket",
            .lightsail_static_ip => "AWS::Lightsail::StaticIp",
            .media_package_packaging_group => "AWS::MediaPackage::PackagingGroup",
            .route_53_recovery_readiness_recovery_group => "AWS::Route53RecoveryReadiness::RecoveryGroup",
            .resilience_hub_resiliency_policy => "AWS::ResilienceHub::ResiliencyPolicy",
            .transfer_workflow => "AWS::Transfer::Workflow",
            .eks_identity_provider_config => "AWS::EKS::IdentityProviderConfig",
            .eks_addon => "AWS::EKS::Addon",
            .glue_ml_transform => "AWS::Glue::MLTransform",
            .io_t_policy => "AWS::IoT::Policy",
            .io_t_mitigation_action => "AWS::IoT::MitigationAction",
            .io_t_twin_maker_workspace => "AWS::IoTTwinMaker::Workspace",
            .io_t_twin_maker_entity => "AWS::IoTTwinMaker::Entity",
            .io_t_analytics_dataset => "AWS::IoTAnalytics::Dataset",
            .io_t_analytics_pipeline => "AWS::IoTAnalytics::Pipeline",
            .io_t_analytics_channel => "AWS::IoTAnalytics::Channel",
            .io_t_site_wise_dashboard => "AWS::IoTSiteWise::Dashboard",
            .io_t_site_wise_project => "AWS::IoTSiteWise::Project",
            .io_t_site_wise_portal => "AWS::IoTSiteWise::Portal",
            .io_t_site_wise_asset_model => "AWS::IoTSiteWise::AssetModel",
            .ivs_channel => "AWS::IVS::Channel",
            .ivs_recording_configuration => "AWS::IVS::RecordingConfiguration",
            .ivs_playback_key_pair => "AWS::IVS::PlaybackKeyPair",
            .kinesis_analytics_v2_application => "AWS::KinesisAnalyticsV2::Application",
            .rds_global_cluster => "AWS::RDS::GlobalCluster",
            .s3_multi_region_access_point => "AWS::S3::MultiRegionAccessPoint",
            .device_farm_test_grid_project => "AWS::DeviceFarm::TestGridProject",
            .budgets_budgets_action => "AWS::Budgets::BudgetsAction",
            .lex_bot => "AWS::Lex::Bot",
            .code_guru_reviewer_repository_association => "AWS::CodeGuruReviewer::RepositoryAssociation",
            .io_t_custom_metric => "AWS::IoT::CustomMetric",
            .route_53_resolver_firewall_domain_list => "AWS::Route53Resolver::FirewallDomainList",
            .robo_maker_robot_application_version => "AWS::RoboMaker::RobotApplicationVersion",
            .ec2_traffic_mirror_session => "AWS::EC2::TrafficMirrorSession",
            .io_t_site_wise_gateway => "AWS::IoTSiteWise::Gateway",
            .lex_bot_alias => "AWS::Lex::BotAlias",
            .lookout_metrics_alert => "AWS::LookoutMetrics::Alert",
            .io_t_account_audit_configuration => "AWS::IoT::AccountAuditConfiguration",
            .ec2_traffic_mirror_target => "AWS::EC2::TrafficMirrorTarget",
            .s3_storage_lens => "AWS::S3::StorageLens",
            .io_t_scheduled_audit => "AWS::IoT::ScheduledAudit",
            .events_connection => "AWS::Events::Connection",
            .event_schemas_schema => "AWS::EventSchemas::Schema",
            .media_package_packaging_configuration => "AWS::MediaPackage::PackagingConfiguration",
            .kinesis_video_signaling_channel => "AWS::KinesisVideo::SignalingChannel",
            .app_stream_directory_config => "AWS::AppStream::DirectoryConfig",
            .lookout_vision_project => "AWS::LookoutVision::Project",
            .route_53_recovery_control_cluster => "AWS::Route53RecoveryControl::Cluster",
            .route_53_recovery_control_safety_rule => "AWS::Route53RecoveryControl::SafetyRule",
            .route_53_recovery_control_control_panel => "AWS::Route53RecoveryControl::ControlPanel",
            .route_53_recovery_control_routing_control => "AWS::Route53RecoveryControl::RoutingControl",
            .route_53_recovery_readiness_resource_set => "AWS::Route53RecoveryReadiness::ResourceSet",
            .robo_maker_simulation_application => "AWS::RoboMaker::SimulationApplication",
            .robo_maker_robot_application => "AWS::RoboMaker::RobotApplication",
            .health_lake_fhir_datastore => "AWS::HealthLake::FHIRDatastore",
            .pinpoint_segment => "AWS::Pinpoint::Segment",
            .pinpoint_application_settings => "AWS::Pinpoint::ApplicationSettings",
            .events_rule => "AWS::Events::Rule",
            .ec2_dhcp_options => "AWS::EC2::DHCPOptions",
            .ec2_network_insights_path => "AWS::EC2::NetworkInsightsPath",
            .ec2_traffic_mirror_filter => "AWS::EC2::TrafficMirrorFilter",
            .ec2_ipam => "AWS::EC2::IPAM",
            .io_t_twin_maker_scene => "AWS::IoTTwinMaker::Scene",
            .network_manager_transit_gateway_registration => "AWS::NetworkManager::TransitGatewayRegistration",
            .customer_profiles_domain => "AWS::CustomerProfiles::Domain",
            .auto_scaling_warm_pool => "AWS::AutoScaling::WarmPool",
            .connect_phone_number => "AWS::Connect::PhoneNumber",
            .app_config_deployment_strategy => "AWS::AppConfig::DeploymentStrategy",
            .app_flow_flow => "AWS::AppFlow::Flow",
            .audit_manager_assessment => "AWS::AuditManager::Assessment",
            .cloud_watch_metric_stream => "AWS::CloudWatch::MetricStream",
            .device_farm_instance_profile => "AWS::DeviceFarm::InstanceProfile",
            .device_farm_project => "AWS::DeviceFarm::Project",
            .ec2_ec2_fleet => "AWS::EC2::EC2Fleet",
            .ec2_subnet_route_table_association => "AWS::EC2::SubnetRouteTableAssociation",
            .ecr_pull_through_cache_rule => "AWS::ECR::PullThroughCacheRule",
            .ground_station_config => "AWS::GroundStation::Config",
            .image_builder_image_pipeline => "AWS::ImageBuilder::ImagePipeline",
            .io_t_fleet_metric => "AWS::IoT::FleetMetric",
            .io_t_wireless_service_profile => "AWS::IoTWireless::ServiceProfile",
            .network_manager_device => "AWS::NetworkManager::Device",
            .network_manager_global_network => "AWS::NetworkManager::GlobalNetwork",
            .network_manager_link => "AWS::NetworkManager::Link",
            .network_manager_site => "AWS::NetworkManager::Site",
            .panorama_package => "AWS::Panorama::Package",
            .pinpoint_app => "AWS::Pinpoint::App",
            .redshift_scheduled_action => "AWS::Redshift::ScheduledAction",
            .route_53_resolver_firewall_rule_group_association => "AWS::Route53Resolver::FirewallRuleGroupAssociation",
            .sage_maker_app_image_config => "AWS::SageMaker::AppImageConfig",
            .sage_maker_image => "AWS::SageMaker::Image",
            .ecs_task_set => "AWS::ECS::TaskSet",
            .cassandra_keyspace => "AWS::Cassandra::Keyspace",
            .signer_signing_profile => "AWS::Signer::SigningProfile",
            .amplify_app => "AWS::Amplify::App",
            .app_mesh_virtual_node => "AWS::AppMesh::VirtualNode",
            .app_mesh_virtual_service => "AWS::AppMesh::VirtualService",
            .app_runner_vpc_connector => "AWS::AppRunner::VpcConnector",
            .app_stream_application => "AWS::AppStream::Application",
            .code_artifact_repository => "AWS::CodeArtifact::Repository",
            .ec2_prefix_list => "AWS::EC2::PrefixList",
            .ec2_spot_fleet => "AWS::EC2::SpotFleet",
            .evidently_project => "AWS::Evidently::Project",
            .forecast_dataset => "AWS::Forecast::Dataset",
            .iamsaml_provider => "AWS::IAM::SAMLProvider",
            .iam_server_certificate => "AWS::IAM::ServerCertificate",
            .pinpoint_campaign => "AWS::Pinpoint::Campaign",
            .pinpoint_in_app_template => "AWS::Pinpoint::InAppTemplate",
            .sage_maker_domain => "AWS::SageMaker::Domain",
            .transfer_agreement => "AWS::Transfer::Agreement",
            .transfer_connector => "AWS::Transfer::Connector",
            .kinesis_firehose_delivery_stream => "AWS::KinesisFirehose::DeliveryStream",
            .amplify_branch => "AWS::Amplify::Branch",
            .app_integrations_event_integration => "AWS::AppIntegrations::EventIntegration",
            .app_mesh_route => "AWS::AppMesh::Route",
            .athena_prepared_statement => "AWS::Athena::PreparedStatement",
            .ec2_ipam_scope => "AWS::EC2::IPAMScope",
            .evidently_launch => "AWS::Evidently::Launch",
            .forecast_dataset_group => "AWS::Forecast::DatasetGroup",
            .greengrass_v2_component_version => "AWS::GreengrassV2::ComponentVersion",
            .ground_station_mission_profile => "AWS::GroundStation::MissionProfile",
            .media_connect_flow_entitlement => "AWS::MediaConnect::FlowEntitlement",
            .media_connect_flow_vpc_interface => "AWS::MediaConnect::FlowVpcInterface",
            .media_tailor_playback_configuration => "AWS::MediaTailor::PlaybackConfiguration",
            .msk_configuration => "AWS::MSK::Configuration",
            .personalize_dataset => "AWS::Personalize::Dataset",
            .personalize_schema => "AWS::Personalize::Schema",
            .personalize_solution => "AWS::Personalize::Solution",
            .pinpoint_email_template => "AWS::Pinpoint::EmailTemplate",
            .pinpoint_event_stream => "AWS::Pinpoint::EventStream",
            .resilience_hub_app => "AWS::ResilienceHub::App",
            .acmpca_certificate_authority => "AWS::ACMPCA::CertificateAuthority",
            .app_config_hosted_configuration_version => "AWS::AppConfig::HostedConfigurationVersion",
            .app_mesh_virtual_gateway => "AWS::AppMesh::VirtualGateway",
            .app_mesh_virtual_router => "AWS::AppMesh::VirtualRouter",
            .app_runner_service => "AWS::AppRunner::Service",
            .customer_profiles_object_type => "AWS::CustomerProfiles::ObjectType",
            .dms_endpoint => "AWS::DMS::Endpoint",
            .ec2_capacity_reservation => "AWS::EC2::CapacityReservation",
            .ec2_client_vpn_endpoint => "AWS::EC2::ClientVpnEndpoint",
            .kendra_index => "AWS::Kendra::Index",
            .kinesis_video_stream => "AWS::KinesisVideo::Stream",
            .logs_destination => "AWS::Logs::Destination",
            .pinpoint_email_channel => "AWS::Pinpoint::EmailChannel",
            .s3_access_point => "AWS::S3::AccessPoint",
            .network_manager_customer_gateway_association => "AWS::NetworkManager::CustomerGatewayAssociation",
            .network_manager_link_association => "AWS::NetworkManager::LinkAssociation",
            .io_t_wireless_multicast_group => "AWS::IoTWireless::MulticastGroup",
            .personalize_dataset_group => "AWS::Personalize::DatasetGroup",
            .io_t_twin_maker_component_type => "AWS::IoTTwinMaker::ComponentType",
            .code_build_report_group => "AWS::CodeBuild::ReportGroup",
            .sage_maker_feature_group => "AWS::SageMaker::FeatureGroup",
            .msk_batch_scram_secret => "AWS::MSK::BatchScramSecret",
            .app_stream_stack => "AWS::AppStream::Stack",
            .io_t_job_template => "AWS::IoT::JobTemplate",
            .io_t_wireless_fuota_task => "AWS::IoTWireless::FuotaTask",
            .io_t_provisioning_template => "AWS::IoT::ProvisioningTemplate",
            .inspector_v2_filter => "AWS::InspectorV2::Filter",
            .route_53_resolver_resolver_query_logging_config_association => "AWS::Route53Resolver::ResolverQueryLoggingConfigAssociation",
            .service_discovery_instance => "AWS::ServiceDiscovery::Instance",
            .transfer_certificate => "AWS::Transfer::Certificate",
            .media_connect_flow_source => "AWS::MediaConnect::FlowSource",
            .aps_rule_groups_namespace => "AWS::APS::RuleGroupsNamespace",
            .code_guru_profiler_profiling_group => "AWS::CodeGuruProfiler::ProfilingGroup",
            .route_53_resolver_resolver_query_logging_config => "AWS::Route53Resolver::ResolverQueryLoggingConfig",
            .batch_scheduling_policy => "AWS::Batch::SchedulingPolicy",
            .acmpca_certificate_authority_activation => "AWS::ACMPCA::CertificateAuthorityActivation",
            .app_mesh_gateway_route => "AWS::AppMesh::GatewayRoute",
            .app_mesh_mesh => "AWS::AppMesh::Mesh",
            .connect_instance => "AWS::Connect::Instance",
            .connect_quick_connect => "AWS::Connect::QuickConnect",
            .ec2_carrier_gateway => "AWS::EC2::CarrierGateway",
            .ec2_ipam_pool => "AWS::EC2::IPAMPool",
            .ec2_transit_gateway_connect => "AWS::EC2::TransitGatewayConnect",
            .ec2_transit_gateway_multicast_domain => "AWS::EC2::TransitGatewayMulticastDomain",
            .ecs_capacity_provider => "AWS::ECS::CapacityProvider",
            .iam_instance_profile => "AWS::IAM::InstanceProfile",
            .io_tca_certificate => "AWS::IoT::CACertificate",
            .io_t_twin_maker_sync_job => "AWS::IoTTwinMaker::SyncJob",
            .kafka_connect_connector => "AWS::KafkaConnect::Connector",
            .lambda_code_signing_config => "AWS::Lambda::CodeSigningConfig",
            .network_manager_connect_peer => "AWS::NetworkManager::ConnectPeer",
            .resource_explorer_2_index => "AWS::ResourceExplorer2::Index",
            .app_stream_fleet => "AWS::AppStream::Fleet",
            .cognito_user_pool => "AWS::Cognito::UserPool",
            .cognito_user_pool_client => "AWS::Cognito::UserPoolClient",
            .cognito_user_pool_group => "AWS::Cognito::UserPoolGroup",
            .ec2_network_insights_access_scope => "AWS::EC2::NetworkInsightsAccessScope",
            .ec2_network_insights_analysis => "AWS::EC2::NetworkInsightsAnalysis",
            .grafana_workspace => "AWS::Grafana::Workspace",
            .ground_station_dataflow_endpoint_group => "AWS::GroundStation::DataflowEndpointGroup",
            .image_builder_image_recipe => "AWS::ImageBuilder::ImageRecipe",
            .kms_alias => "AWS::KMS::Alias",
            .m2_environment => "AWS::M2::Environment",
            .quick_sight_data_source => "AWS::QuickSight::DataSource",
            .quick_sight_template => "AWS::QuickSight::Template",
            .quick_sight_theme => "AWS::QuickSight::Theme",
            .rds_option_group => "AWS::RDS::OptionGroup",
            .redshift_endpoint_access => "AWS::Redshift::EndpointAccess",
            .route_53_resolver_firewall_rule_group => "AWS::Route53Resolver::FirewallRuleGroup",
            .ssm_document => "AWS::SSM::Document",
            .app_config_extension_association => "AWS::AppConfig::ExtensionAssociation",
            .app_integrations_application => "AWS::AppIntegrations::Application",
            .app_sync_api_cache => "AWS::AppSync::ApiCache",
            .bedrock_guardrail => "AWS::Bedrock::Guardrail",
            .bedrock_knowledge_base => "AWS::Bedrock::KnowledgeBase",
            .cognito_identity_pool => "AWS::Cognito::IdentityPool",
            .connect_rule => "AWS::Connect::Rule",
            .connect_user => "AWS::Connect::User",
            .ec2_client_vpn_target_network_association => "AWS::EC2::ClientVpnTargetNetworkAssociation",
            .ec2_eip_association => "AWS::EC2::EIPAssociation",
            .ec2_ipam_resource_discovery => "AWS::EC2::IPAMResourceDiscovery",
            .ec2_ipam_resource_discovery_association => "AWS::EC2::IPAMResourceDiscoveryAssociation",
            .ec2_instance_connect_endpoint => "AWS::EC2::InstanceConnectEndpoint",
            .ec2_snapshot_block_public_access => "AWS::EC2::SnapshotBlockPublicAccess",
            .ec2_vpc_block_public_access_exclusion => "AWS::EC2::VPCBlockPublicAccessExclusion",
            .ec2_vpc_block_public_access_options => "AWS::EC2::VPCBlockPublicAccessOptions",
            .ec2_vpc_endpoint_connection_notification => "AWS::EC2::VPCEndpointConnectionNotification",
            .ec2_vpn_connection_route => "AWS::EC2::VPNConnectionRoute",
            .evidently_segment => "AWS::Evidently::Segment",
            .iamoidc_provider => "AWS::IAM::OIDCProvider",
            .inspector_v2_activation => "AWS::InspectorV2::Activation",
            .msk_cluster_policy => "AWS::MSK::ClusterPolicy",
            .msk_vpc_connection => "AWS::MSK::VpcConnection",
            .media_connect_gateway => "AWS::MediaConnect::Gateway",
            .memory_db_subnet_group => "AWS::MemoryDB::SubnetGroup",
            .open_search_serverless_collection => "AWS::OpenSearchServerless::Collection",
            .open_search_serverless_vpc_endpoint => "AWS::OpenSearchServerless::VpcEndpoint",
            .redshift_endpoint_authorization => "AWS::Redshift::EndpointAuthorization",
            .route_53_profiles_profile => "AWS::Route53Profiles::Profile",
            .s3_storage_lens_group => "AWS::S3::StorageLensGroup",
            .s3_express_bucket_policy => "AWS::S3Express::BucketPolicy",
            .s3_express_directory_bucket => "AWS::S3Express::DirectoryBucket",
            .sage_maker_inference_experiment => "AWS::SageMaker::InferenceExperiment",
            .security_hub_standard => "AWS::SecurityHub::Standard",
            .transfer_profile => "AWS::Transfer::Profile",
            .cloud_formation_stack_set => "AWS::CloudFormation::StackSet",
            .media_package_v2_channel => "AWS::MediaPackageV2::Channel",
            .s3_access_grants_location => "AWS::S3::AccessGrantsLocation",
            .s3_access_grant => "AWS::S3::AccessGrant",
            .s3_access_grants_instance => "AWS::S3::AccessGrantsInstance",
            .emr_serverless_application => "AWS::EMRServerless::Application",
            .config_aggregation_authorization => "AWS::Config::AggregationAuthorization",
            .bedrock_application_inference_profile => "AWS::Bedrock::ApplicationInferenceProfile",
            .api_gateway_v2_integration => "AWS::ApiGatewayV2::Integration",
            .sage_maker_mlflow_tracking_server => "AWS::SageMaker::MlflowTrackingServer",
            .sage_maker_model_bias_job_definition => "AWS::SageMaker::ModelBiasJobDefinition",
            .secrets_manager_rotation_schedule => "AWS::SecretsManager::RotationSchedule",
            .deadline_queue_fleet_association => "AWS::Deadline::QueueFleetAssociation",
            .ecr_repository_creation_template => "AWS::ECR::RepositoryCreationTemplate",
            .cloud_formation_lambda_hook => "AWS::CloudFormation::LambdaHook",
            .ec2_subnet_network_acl_association => "AWS::EC2::SubnetNetworkAclAssociation",
            .api_gateway_usage_plan => "AWS::ApiGateway::UsagePlan",
            .app_config_extension => "AWS::AppConfig::Extension",
            .deadline_fleet => "AWS::Deadline::Fleet",
            .emr_studio => "AWS::EMR::Studio",
            .s3_tables_table_bucket => "AWS::S3Tables::TableBucket",
            .cloud_front_realtime_log_config => "AWS::CloudFront::RealtimeLogConfig",
            .backup_gateway_hypervisor => "AWS::BackupGateway::Hypervisor",
            .bcm_data_exports_export => "AWS::BCMDataExports::Export",
            .cloud_formation_guard_hook => "AWS::CloudFormation::GuardHook",
            .cloud_front_public_key => "AWS::CloudFront::PublicKey",
            .cloud_trail_event_data_store => "AWS::CloudTrail::EventDataStore",
            .entity_resolution_id_mapping_workflow => "AWS::EntityResolution::IdMappingWorkflow",
            .entity_resolution_schema_mapping => "AWS::EntityResolution::SchemaMapping",
            .io_t_domain_configuration => "AWS::IoT::DomainConfiguration",
            .pca_connector_ad_directory_registration => "AWS::PCAConnectorAD::DirectoryRegistration",
            .rds_integration => "AWS::RDS::Integration",
            .config_conformance_pack => "AWS::Config::ConformancePack",
            .roles_anywhere_profile => "AWS::RolesAnywhere::Profile",
            .code_artifact_domain => "AWS::CodeArtifact::Domain",
            .backup_restore_testing_plan => "AWS::Backup::RestoreTestingPlan",
            .config_stored_query => "AWS::Config::StoredQuery",
            .sage_maker_data_quality_job_definition => "AWS::SageMaker::DataQualityJobDefinition",
            .sage_maker_model_explainability_job_definition => "AWS::SageMaker::ModelExplainabilityJobDefinition",
            .sage_maker_model_quality_job_definition => "AWS::SageMaker::ModelQualityJobDefinition",
            .sage_maker_studio_lifecycle_config => "AWS::SageMaker::StudioLifecycleConfig",
            .ses_dedicated_ip_pool => "AWS::SES::DedicatedIpPool",
            .ses_mail_manager_traffic_policy => "AWS::SES::MailManagerTrafficPolicy",
            .ssm_resource_data_sync => "AWS::SSM::ResourceDataSync",
            .bedrock_agent_core_runtime => "AWS::BedrockAgentCore::Runtime",
            .bedrock_agent_core_browser_custom => "AWS::BedrockAgentCore::BrowserCustom",
            .elastic_load_balancing_v2_target_group => "AWS::ElasticLoadBalancingV2::TargetGroup",
            .emr_containers_virtual_cluster => "AWS::EMRContainers::VirtualCluster",
            .entity_resolution_matching_workflow => "AWS::EntityResolution::MatchingWorkflow",
            .io_t_core_device_advisor_suite_definition => "AWS::IoTCoreDeviceAdvisor::SuiteDefinition",
            .ec2_security_group_vpc_association => "AWS::EC2::SecurityGroupVpcAssociation",
            .ec2_verified_access_instance => "AWS::EC2::VerifiedAccessInstance",
            .kafka_connect_custom_plugin => "AWS::KafkaConnect::CustomPlugin",
            .network_manager_transit_gateway_peering => "AWS::NetworkManager::TransitGatewayPeering",
            .open_search_serverless_security_config => "AWS::OpenSearchServerless::SecurityConfig",
            .redshift_integration => "AWS::Redshift::Integration",
            .roles_anywhere_trust_anchor => "AWS::RolesAnywhere::TrustAnchor",
            .route_53_profiles_profile_association => "AWS::Route53Profiles::ProfileAssociation",
            .ssm_incidents_response_plan => "AWS::SSMIncidents::ResponsePlan",
            .transfer_server => "AWS::Transfer::Server",
            .glue_database => "AWS::Glue::Database",
            .organizations_organizational_unit => "AWS::Organizations::OrganizationalUnit",
            .ec2_ipam_pool_cidr => "AWS::EC2::IPAMPoolCidr",
            .ec2_vpc_gateway_attachment => "AWS::EC2::VPCGatewayAttachment",
            .bedrock_prompt => "AWS::Bedrock::Prompt",
            .comprehend_flywheel => "AWS::Comprehend::Flywheel",
            .data_sync_agent => "AWS::DataSync::Agent",
            .media_tailor_live_source => "AWS::MediaTailor::LiveSource",
            .msk_serverless_cluster => "AWS::MSK::ServerlessCluster",
            .io_t_site_wise_asset => "AWS::IoTSiteWise::Asset",
            .b2_bi_capability => "AWS::B2BI::Capability",
            .cloud_front_key_value_store => "AWS::CloudFront::KeyValueStore",
            .deadline_monitor => "AWS::Deadline::Monitor",
            .guard_duty_malware_protection_plan => "AWS::GuardDuty::MalwareProtectionPlan",
            .location_api_key => "AWS::Location::APIKey",
            .media_package_v2_origin_endpoint => "AWS::MediaPackageV2::OriginEndpoint",
            .pca_connector_ad_connector => "AWS::PCAConnectorAD::Connector",
            .s3_tables_table_bucket_policy => "AWS::S3Tables::TableBucketPolicy",
            .secrets_manager_resource_policy => "AWS::SecretsManager::ResourcePolicy",
            .ssm_contacts_contact => "AWS::SSMContacts::Contact",
            .io_t_thing_group => "AWS::IoT::ThingGroup",
            .image_builder_lifecycle_policy => "AWS::ImageBuilder::LifecyclePolicy",
            .game_lift_build => "AWS::GameLift::Build",
            .ecr_replication_configuration => "AWS::ECR::ReplicationConfiguration",
            .ec2_subnet_cidr_block => "AWS::EC2::SubnetCidrBlock",
            .connect_security_profile => "AWS::Connect::SecurityProfile",
            .clean_rooms_ml_training_dataset => "AWS::CleanRoomsML::TrainingDataset",
            .app_stream_app_block_builder => "AWS::AppStream::AppBlockBuilder",
            .route_53_dnssec => "AWS::Route53::DNSSEC",
            .sage_maker_user_profile => "AWS::SageMaker::UserProfile",
            .api_gateway_method => "AWS::ApiGateway::Method",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        @setEvalBranchQuota(1699);
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
