pub const ResourceType = enum {
    customer_gateway,
    eip,
    host,
    instance,
    internet_gateway,
    network_acl,
    network_interface,
    route_table,
    security_group,
    subnet,
    trail,
    volume,
    vpc,
    vpn_connection,
    vpn_gateway,
    registered_ha_instance,
    nat_gateway,
    egress_only_internet_gateway,
    vpc_endpoint,
    vpc_endpoint_service,
    flow_log,
    vpc_peering_connection,
    domain,
    group,
    policy,
    role,
    user,
    load_balancer_v2,
    certificate,
    db_instance,
    db_subnet_group,
    db_security_group,
    db_snapshot,
    db_cluster,
    db_cluster_snapshot,
    event_subscription,
    bucket,
    account_public_access_block,
    cluster,
    cluster_snapshot,
    cluster_parameter_group,
    cluster_security_group,
    cluster_subnet_group,
    redshift_event_subscription,
    managed_instance_inventory,
    alarm,
    stack,
    load_balancer,
    auto_scaling_group,
    launch_configuration,
    scaling_policy,
    scheduled_action,
    table,
    project,
    rate_based_rule,
    rule,
    rule_group,
    web_acl,
    regional_rate_based_rule,
    regional_rule,
    regional_rule_group,
    regional_web_acl,
    distribution,
    streaming_distribution,
    function,
    network_firewall_firewall,
    network_firewall_firewall_policy,
    network_firewall_rule_group,
    application,
    application_version,
    environment,
    web_aclv2,
    rule_group_v2,
    ip_set_v2,
    regex_pattern_set_v2,
    managed_rule_set_v2,
    encryption_config,
    association_compliance,
    patch_compliance,
    protection,
    regional_protection,
    conformance_pack_compliance,
    resource_compliance,
    stage,
    rest_api,
    stage_v2,
    api,
    pipeline,
    cloud_formation_provisioned_product,
    cloud_formation_product,
    portfolio,
    queue,
    key,
    qldb_ledger,
    secret,
    topic,
    file_data,
    backup_plan,
    backup_selection,
    backup_vault,
    backup_recovery_point,
    ecr_repository,
    ecs_cluster,
    ecs_service,
    ecs_task_definition,
    efs_access_point,
    efs_file_system,
    eks_cluster,
    open_search_domain,
    transit_gateway,
    kinesis_stream,
    kinesis_stream_consumer,
    code_deploy_application,
    code_deploy_deployment_config,
    code_deploy_deployment_group,
    launch_template,
    ecr_public_repository,
    guard_duty_detector,
    emr_security_configuration,
    sage_maker_code_repository,
    route_53_resolver_resolver_endpoint,
    route_53_resolver_resolver_rule,
    route_53_resolver_resolver_rule_association,
    dms_replication_subnet_group,
    dms_event_subscription,
    msk_cluster,
    step_functions_activity,
    work_spaces_workspace,
    work_spaces_connection_alias,
    sage_maker_model,
    listener_v2,
    step_functions_state_machine,
    batch_job_queue,
    batch_compute_environment,
    access_analyzer_analyzer,
    athena_work_group,
    athena_data_catalog,
    detective_graph,
    global_accelerator_accelerator,
    global_accelerator_endpoint_group,
    global_accelerator_listener,
    transit_gateway_attachment,
    transit_gateway_route_table,
    dms_certificate,
    app_config_application,
    app_sync_graph_ql_api,
    data_sync_location_smb,
    data_sync_location_f_sx_lustre,
    data_sync_location_s3,
    data_sync_location_efs,
    data_sync_task,
    data_sync_location_nfs,
    network_insights_access_scope_analysis,
    eks_fargate_profile,
    glue_job,
    guard_duty_threat_intel_set,
    guard_duty_ip_set,
    sage_maker_workteam,
    sage_maker_notebook_instance_lifecycle_config,
    service_discovery_service,
    service_discovery_public_dns_namespace,
    ses_contact_list,
    ses_configuration_set,
    route_53_hosted_zone,
    io_t_events_input,
    io_t_events_detector_model,
    io_t_events_alarm_model,
    service_discovery_http_namespace,
    events_event_bus,
    image_builder_container_recipe,
    image_builder_distribution_configuration,
    image_builder_infrastructure_configuration,
    data_sync_location_object_storage,
    data_sync_location_hdfs,
    glue_classifier,
    route_53_recovery_readiness_cell,
    route_53_recovery_readiness_readiness_check,
    ecr_registry_policy,
    backup_report_plan,
    lightsail_certificate,
    rum_app_monitor,
    events_endpoint,
    ses_receipt_rule_set,
    events_archive,
    events_api_destination,
    lightsail_disk,
    fis_experiment_template,
    data_sync_location_f_sx_windows,
    ses_receipt_filter,
    guard_duty_filter,
    ses_template,
    amazon_mq_broker,
    app_config_environment,
    app_config_configuration_profile,
    cloud_9_environment_ec2,
    event_schemas_registry,
    event_schemas_registry_policy,
    event_schemas_discoverer,
    fraud_detector_label,
    fraud_detector_entity_type,
    fraud_detector_variable,
    fraud_detector_outcome,
    io_t_authorizer,
    io_t_security_profile,
    io_t_role_alias,
    io_t_dimension,
    io_t_analytics_datastore,
    lightsail_bucket,
    lightsail_static_ip,
    media_package_packaging_group,
    route_53_recovery_readiness_recovery_group,
    resilience_hub_resiliency_policy,
    transfer_workflow,
    eks_identity_provider_config,
    eks_addon,
    glue_ml_transform,
    io_t_policy,
    io_t_mitigation_action,
    io_t_twin_maker_workspace,
    io_t_twin_maker_entity,
    io_t_analytics_dataset,
    io_t_analytics_pipeline,
    io_t_analytics_channel,
    io_t_site_wise_dashboard,
    io_t_site_wise_project,
    io_t_site_wise_portal,
    io_t_site_wise_asset_model,
    ivs_channel,
    ivs_recording_configuration,
    ivs_playback_key_pair,
    kinesis_analytics_v2_application,
    rds_global_cluster,
    s3_multi_region_access_point,
    device_farm_test_grid_project,
    budgets_budgets_action,
    lex_bot,
    code_guru_reviewer_repository_association,
    io_t_custom_metric,
    route_53_resolver_firewall_domain_list,
    robo_maker_robot_application_version,
    ec2_traffic_mirror_session,
    io_t_site_wise_gateway,
    lex_bot_alias,
    lookout_metrics_alert,
    io_t_account_audit_configuration,
    ec2_traffic_mirror_target,
    s3_storage_lens,
    io_t_scheduled_audit,
    events_connection,
    event_schemas_schema,
    media_package_packaging_configuration,
    kinesis_video_signaling_channel,
    app_stream_directory_config,
    lookout_vision_project,
    route_53_recovery_control_cluster,
    route_53_recovery_control_safety_rule,
    route_53_recovery_control_control_panel,
    route_53_recovery_control_routing_control,
    route_53_recovery_readiness_resource_set,
    robo_maker_simulation_application,
    robo_maker_robot_application,
    health_lake_fhir_datastore,
    pinpoint_segment,
    pinpoint_application_settings,
    events_rule,
    ec2_dhcp_options,
    ec2_network_insights_path,
    ec2_traffic_mirror_filter,
    ec2_ipam,
    io_t_twin_maker_scene,
    network_manager_transit_gateway_registration,
    customer_profiles_domain,
    auto_scaling_warm_pool,
    connect_phone_number,
    app_config_deployment_strategy,
    app_flow_flow,
    audit_manager_assessment,
    cloud_watch_metric_stream,
    device_farm_instance_profile,
    device_farm_project,
    ec2_ec2_fleet,
    ec2_subnet_route_table_association,
    ecr_pull_through_cache_rule,
    ground_station_config,
    image_builder_image_pipeline,
    io_t_fleet_metric,
    io_t_wireless_service_profile,
    network_manager_device,
    network_manager_global_network,
    network_manager_link,
    network_manager_site,
    panorama_package,
    pinpoint_app,
    redshift_scheduled_action,
    route_53_resolver_firewall_rule_group_association,
    sage_maker_app_image_config,
    sage_maker_image,
    ecs_task_set,
    cassandra_keyspace,
    signer_signing_profile,
    amplify_app,
    app_mesh_virtual_node,
    app_mesh_virtual_service,
    app_runner_vpc_connector,
    app_stream_application,
    code_artifact_repository,
    ec2_prefix_list,
    ec2_spot_fleet,
    evidently_project,
    forecast_dataset,
    iamsaml_provider,
    iam_server_certificate,
    pinpoint_campaign,
    pinpoint_in_app_template,
    sage_maker_domain,
    transfer_agreement,
    transfer_connector,
    kinesis_firehose_delivery_stream,
    amplify_branch,
    app_integrations_event_integration,
    app_mesh_route,
    athena_prepared_statement,
    ec2_ipam_scope,
    evidently_launch,
    forecast_dataset_group,
    greengrass_v2_component_version,
    ground_station_mission_profile,
    media_connect_flow_entitlement,
    media_connect_flow_vpc_interface,
    media_tailor_playback_configuration,
    msk_configuration,
    personalize_dataset,
    personalize_schema,
    personalize_solution,
    pinpoint_email_template,
    pinpoint_event_stream,
    resilience_hub_app,
    acmpca_certificate_authority,
    app_config_hosted_configuration_version,
    app_mesh_virtual_gateway,
    app_mesh_virtual_router,
    app_runner_service,
    customer_profiles_object_type,
    dms_endpoint,
    ec2_capacity_reservation,
    ec2_client_vpn_endpoint,
    kendra_index,
    kinesis_video_stream,
    logs_destination,
    pinpoint_email_channel,
    s3_access_point,
    network_manager_customer_gateway_association,
    network_manager_link_association,
    io_t_wireless_multicast_group,
    personalize_dataset_group,
    io_t_twin_maker_component_type,
    code_build_report_group,
    sage_maker_feature_group,
    msk_batch_scram_secret,
    app_stream_stack,
    io_t_job_template,
    io_t_wireless_fuota_task,
    io_t_provisioning_template,
    inspector_v2_filter,
    route_53_resolver_resolver_query_logging_config_association,
    service_discovery_instance,
    transfer_certificate,
    media_connect_flow_source,
    aps_rule_groups_namespace,
    code_guru_profiler_profiling_group,
    route_53_resolver_resolver_query_logging_config,
    batch_scheduling_policy,
    acmpca_certificate_authority_activation,
    app_mesh_gateway_route,
    app_mesh_mesh,
    connect_instance,
    connect_quick_connect,
    ec2_carrier_gateway,
    ec2_ipam_pool,
    ec2_transit_gateway_connect,
    ec2_transit_gateway_multicast_domain,
    ecs_capacity_provider,
    iam_instance_profile,
    io_tca_certificate,
    io_t_twin_maker_sync_job,
    kafka_connect_connector,
    lambda_code_signing_config,
    network_manager_connect_peer,
    resource_explorer_2_index,
    app_stream_fleet,
    cognito_user_pool,
    cognito_user_pool_client,
    cognito_user_pool_group,
    ec2_network_insights_access_scope,
    ec2_network_insights_analysis,
    grafana_workspace,
    ground_station_dataflow_endpoint_group,
    image_builder_image_recipe,
    kms_alias,
    m2_environment,
    quick_sight_data_source,
    quick_sight_template,
    quick_sight_theme,
    rds_option_group,
    redshift_endpoint_access,
    route_53_resolver_firewall_rule_group,
    ssm_document,
    app_config_extension_association,
    app_integrations_application,
    app_sync_api_cache,
    bedrock_guardrail,
    bedrock_knowledge_base,
    cognito_identity_pool,
    connect_rule,
    connect_user,
    ec2_client_vpn_target_network_association,
    ec2_eip_association,
    ec2_ipam_resource_discovery,
    ec2_ipam_resource_discovery_association,
    ec2_instance_connect_endpoint,
    ec2_snapshot_block_public_access,
    ec2_vpc_block_public_access_exclusion,
    ec2_vpc_block_public_access_options,
    ec2_vpc_endpoint_connection_notification,
    ec2_vpn_connection_route,
    evidently_segment,
    iamoidc_provider,
    inspector_v2_activation,
    msk_cluster_policy,
    msk_vpc_connection,
    media_connect_gateway,
    memory_db_subnet_group,
    open_search_serverless_collection,
    open_search_serverless_vpc_endpoint,
    redshift_endpoint_authorization,
    route_53_profiles_profile,
    s3_storage_lens_group,
    s3_express_bucket_policy,
    s3_express_directory_bucket,
    sage_maker_inference_experiment,
    security_hub_standard,
    transfer_profile,
    cloud_formation_stack_set,
    media_package_v2_channel,
    s3_access_grants_location,
    s3_access_grant,
    s3_access_grants_instance,
    emr_serverless_application,
    config_aggregation_authorization,
    bedrock_application_inference_profile,
    api_gateway_v2_integration,
    sage_maker_mlflow_tracking_server,
    sage_maker_model_bias_job_definition,
    secrets_manager_rotation_schedule,
    deadline_queue_fleet_association,
    ecr_repository_creation_template,
    cloud_formation_lambda_hook,
    ec2_subnet_network_acl_association,
    api_gateway_usage_plan,
    app_config_extension,
    deadline_fleet,
    emr_studio,
    s3_tables_table_bucket,
    cloud_front_realtime_log_config,
    backup_gateway_hypervisor,
    bcm_data_exports_export,
    cloud_formation_guard_hook,
    cloud_front_public_key,
    cloud_trail_event_data_store,
    entity_resolution_id_mapping_workflow,
    entity_resolution_schema_mapping,
    io_t_domain_configuration,
    pca_connector_ad_directory_registration,
    rds_integration,
    config_conformance_pack,
    roles_anywhere_profile,
    code_artifact_domain,
    backup_restore_testing_plan,
    config_stored_query,
    sage_maker_data_quality_job_definition,
    sage_maker_model_explainability_job_definition,
    sage_maker_model_quality_job_definition,
    sage_maker_studio_lifecycle_config,
    ses_dedicated_ip_pool,
    ses_mail_manager_traffic_policy,
    ssm_resource_data_sync,
    bedrock_agent_core_runtime,
    bedrock_agent_core_browser_custom,
    elastic_load_balancing_v2_target_group,
    emr_containers_virtual_cluster,
    entity_resolution_matching_workflow,
    io_t_core_device_advisor_suite_definition,
    ec2_security_group_vpc_association,
    ec2_verified_access_instance,
    kafka_connect_custom_plugin,
    network_manager_transit_gateway_peering,
    open_search_serverless_security_config,
    redshift_integration,
    roles_anywhere_trust_anchor,
    route_53_profiles_profile_association,
    ssm_incidents_response_plan,
    transfer_server,
    glue_database,
    organizations_organizational_unit,
    ec2_ipam_pool_cidr,
    ec2_vpc_gateway_attachment,
    bedrock_prompt,
    comprehend_flywheel,
    data_sync_agent,
    media_tailor_live_source,
    msk_serverless_cluster,
    io_t_site_wise_asset,
    b2_bi_capability,
    cloud_front_key_value_store,
    deadline_monitor,
    guard_duty_malware_protection_plan,
    location_api_key,
    media_package_v2_origin_endpoint,
    pca_connector_ad_connector,
    s3_tables_table_bucket_policy,
    secrets_manager_resource_policy,
    ssm_contacts_contact,
    io_t_thing_group,
    image_builder_lifecycle_policy,
    game_lift_build,
    ecr_replication_configuration,
    ec2_subnet_cidr_block,
    connect_security_profile,
    clean_rooms_ml_training_dataset,
    app_stream_app_block_builder,
    route_53_dnssec,
    sage_maker_user_profile,
    api_gateway_method,

    pub const json_field_names = .{
        .customer_gateway = "CustomerGateway",
        .eip = "EIP",
        .host = "Host",
        .instance = "Instance",
        .internet_gateway = "InternetGateway",
        .network_acl = "NetworkAcl",
        .network_interface = "NetworkInterface",
        .route_table = "RouteTable",
        .security_group = "SecurityGroup",
        .subnet = "Subnet",
        .trail = "Trail",
        .volume = "Volume",
        .vpc = "VPC",
        .vpn_connection = "VPNConnection",
        .vpn_gateway = "VPNGateway",
        .registered_ha_instance = "RegisteredHAInstance",
        .nat_gateway = "NatGateway",
        .egress_only_internet_gateway = "EgressOnlyInternetGateway",
        .vpc_endpoint = "VPCEndpoint",
        .vpc_endpoint_service = "VPCEndpointService",
        .flow_log = "FlowLog",
        .vpc_peering_connection = "VPCPeeringConnection",
        .domain = "Domain",
        .group = "Group",
        .policy = "Policy",
        .role = "Role",
        .user = "User",
        .load_balancer_v2 = "LoadBalancerV2",
        .certificate = "Certificate",
        .db_instance = "DBInstance",
        .db_subnet_group = "DBSubnetGroup",
        .db_security_group = "DBSecurityGroup",
        .db_snapshot = "DBSnapshot",
        .db_cluster = "DBCluster",
        .db_cluster_snapshot = "DBClusterSnapshot",
        .event_subscription = "EventSubscription",
        .bucket = "Bucket",
        .account_public_access_block = "AccountPublicAccessBlock",
        .cluster = "Cluster",
        .cluster_snapshot = "ClusterSnapshot",
        .cluster_parameter_group = "ClusterParameterGroup",
        .cluster_security_group = "ClusterSecurityGroup",
        .cluster_subnet_group = "ClusterSubnetGroup",
        .redshift_event_subscription = "RedshiftEventSubscription",
        .managed_instance_inventory = "ManagedInstanceInventory",
        .alarm = "Alarm",
        .stack = "Stack",
        .load_balancer = "LoadBalancer",
        .auto_scaling_group = "AutoScalingGroup",
        .launch_configuration = "LaunchConfiguration",
        .scaling_policy = "ScalingPolicy",
        .scheduled_action = "ScheduledAction",
        .table = "Table",
        .project = "Project",
        .rate_based_rule = "RateBasedRule",
        .rule = "Rule",
        .rule_group = "RuleGroup",
        .web_acl = "WebACL",
        .regional_rate_based_rule = "RegionalRateBasedRule",
        .regional_rule = "RegionalRule",
        .regional_rule_group = "RegionalRuleGroup",
        .regional_web_acl = "RegionalWebACL",
        .distribution = "Distribution",
        .streaming_distribution = "StreamingDistribution",
        .function = "Function",
        .network_firewall_firewall = "NetworkFirewallFirewall",
        .network_firewall_firewall_policy = "NetworkFirewallFirewallPolicy",
        .network_firewall_rule_group = "NetworkFirewallRuleGroup",
        .application = "Application",
        .application_version = "ApplicationVersion",
        .environment = "Environment",
        .web_aclv2 = "WebACLV2",
        .rule_group_v2 = "RuleGroupV2",
        .ip_set_v2 = "IPSetV2",
        .regex_pattern_set_v2 = "RegexPatternSetV2",
        .managed_rule_set_v2 = "ManagedRuleSetV2",
        .encryption_config = "EncryptionConfig",
        .association_compliance = "AssociationCompliance",
        .patch_compliance = "PatchCompliance",
        .protection = "Protection",
        .regional_protection = "RegionalProtection",
        .conformance_pack_compliance = "ConformancePackCompliance",
        .resource_compliance = "ResourceCompliance",
        .stage = "Stage",
        .rest_api = "RestApi",
        .stage_v2 = "StageV2",
        .api = "Api",
        .pipeline = "Pipeline",
        .cloud_formation_provisioned_product = "CloudFormationProvisionedProduct",
        .cloud_formation_product = "CloudFormationProduct",
        .portfolio = "Portfolio",
        .queue = "Queue",
        .key = "Key",
        .qldb_ledger = "QLDBLedger",
        .secret = "Secret",
        .topic = "Topic",
        .file_data = "FileData",
        .backup_plan = "BackupPlan",
        .backup_selection = "BackupSelection",
        .backup_vault = "BackupVault",
        .backup_recovery_point = "BackupRecoveryPoint",
        .ecr_repository = "ECRRepository",
        .ecs_cluster = "ECSCluster",
        .ecs_service = "ECSService",
        .ecs_task_definition = "ECSTaskDefinition",
        .efs_access_point = "EFSAccessPoint",
        .efs_file_system = "EFSFileSystem",
        .eks_cluster = "EKSCluster",
        .open_search_domain = "OpenSearchDomain",
        .transit_gateway = "TransitGateway",
        .kinesis_stream = "KinesisStream",
        .kinesis_stream_consumer = "KinesisStreamConsumer",
        .code_deploy_application = "CodeDeployApplication",
        .code_deploy_deployment_config = "CodeDeployDeploymentConfig",
        .code_deploy_deployment_group = "CodeDeployDeploymentGroup",
        .launch_template = "LaunchTemplate",
        .ecr_public_repository = "ECRPublicRepository",
        .guard_duty_detector = "GuardDutyDetector",
        .emr_security_configuration = "EMRSecurityConfiguration",
        .sage_maker_code_repository = "SageMakerCodeRepository",
        .route_53_resolver_resolver_endpoint = "Route53ResolverResolverEndpoint",
        .route_53_resolver_resolver_rule = "Route53ResolverResolverRule",
        .route_53_resolver_resolver_rule_association = "Route53ResolverResolverRuleAssociation",
        .dms_replication_subnet_group = "DMSReplicationSubnetGroup",
        .dms_event_subscription = "DMSEventSubscription",
        .msk_cluster = "MSKCluster",
        .step_functions_activity = "StepFunctionsActivity",
        .work_spaces_workspace = "WorkSpacesWorkspace",
        .work_spaces_connection_alias = "WorkSpacesConnectionAlias",
        .sage_maker_model = "SageMakerModel",
        .listener_v2 = "ListenerV2",
        .step_functions_state_machine = "StepFunctionsStateMachine",
        .batch_job_queue = "BatchJobQueue",
        .batch_compute_environment = "BatchComputeEnvironment",
        .access_analyzer_analyzer = "AccessAnalyzerAnalyzer",
        .athena_work_group = "AthenaWorkGroup",
        .athena_data_catalog = "AthenaDataCatalog",
        .detective_graph = "DetectiveGraph",
        .global_accelerator_accelerator = "GlobalAcceleratorAccelerator",
        .global_accelerator_endpoint_group = "GlobalAcceleratorEndpointGroup",
        .global_accelerator_listener = "GlobalAcceleratorListener",
        .transit_gateway_attachment = "TransitGatewayAttachment",
        .transit_gateway_route_table = "TransitGatewayRouteTable",
        .dms_certificate = "DMSCertificate",
        .app_config_application = "AppConfigApplication",
        .app_sync_graph_ql_api = "AppSyncGraphQLApi",
        .data_sync_location_smb = "DataSyncLocationSMB",
        .data_sync_location_f_sx_lustre = "DataSyncLocationFSxLustre",
        .data_sync_location_s3 = "DataSyncLocationS3",
        .data_sync_location_efs = "DataSyncLocationEFS",
        .data_sync_task = "DataSyncTask",
        .data_sync_location_nfs = "DataSyncLocationNFS",
        .network_insights_access_scope_analysis = "NetworkInsightsAccessScopeAnalysis",
        .eks_fargate_profile = "EKSFargateProfile",
        .glue_job = "GlueJob",
        .guard_duty_threat_intel_set = "GuardDutyThreatIntelSet",
        .guard_duty_ip_set = "GuardDutyIPSet",
        .sage_maker_workteam = "SageMakerWorkteam",
        .sage_maker_notebook_instance_lifecycle_config = "SageMakerNotebookInstanceLifecycleConfig",
        .service_discovery_service = "ServiceDiscoveryService",
        .service_discovery_public_dns_namespace = "ServiceDiscoveryPublicDnsNamespace",
        .ses_contact_list = "SESContactList",
        .ses_configuration_set = "SESConfigurationSet",
        .route_53_hosted_zone = "Route53HostedZone",
        .io_t_events_input = "IoTEventsInput",
        .io_t_events_detector_model = "IoTEventsDetectorModel",
        .io_t_events_alarm_model = "IoTEventsAlarmModel",
        .service_discovery_http_namespace = "ServiceDiscoveryHttpNamespace",
        .events_event_bus = "EventsEventBus",
        .image_builder_container_recipe = "ImageBuilderContainerRecipe",
        .image_builder_distribution_configuration = "ImageBuilderDistributionConfiguration",
        .image_builder_infrastructure_configuration = "ImageBuilderInfrastructureConfiguration",
        .data_sync_location_object_storage = "DataSyncLocationObjectStorage",
        .data_sync_location_hdfs = "DataSyncLocationHDFS",
        .glue_classifier = "GlueClassifier",
        .route_53_recovery_readiness_cell = "Route53RecoveryReadinessCell",
        .route_53_recovery_readiness_readiness_check = "Route53RecoveryReadinessReadinessCheck",
        .ecr_registry_policy = "ECRRegistryPolicy",
        .backup_report_plan = "BackupReportPlan",
        .lightsail_certificate = "LightsailCertificate",
        .rum_app_monitor = "RUMAppMonitor",
        .events_endpoint = "EventsEndpoint",
        .ses_receipt_rule_set = "SESReceiptRuleSet",
        .events_archive = "EventsArchive",
        .events_api_destination = "EventsApiDestination",
        .lightsail_disk = "LightsailDisk",
        .fis_experiment_template = "FISExperimentTemplate",
        .data_sync_location_f_sx_windows = "DataSyncLocationFSxWindows",
        .ses_receipt_filter = "SESReceiptFilter",
        .guard_duty_filter = "GuardDutyFilter",
        .ses_template = "SESTemplate",
        .amazon_mq_broker = "AmazonMQBroker",
        .app_config_environment = "AppConfigEnvironment",
        .app_config_configuration_profile = "AppConfigConfigurationProfile",
        .cloud_9_environment_ec2 = "Cloud9EnvironmentEC2",
        .event_schemas_registry = "EventSchemasRegistry",
        .event_schemas_registry_policy = "EventSchemasRegistryPolicy",
        .event_schemas_discoverer = "EventSchemasDiscoverer",
        .fraud_detector_label = "FraudDetectorLabel",
        .fraud_detector_entity_type = "FraudDetectorEntityType",
        .fraud_detector_variable = "FraudDetectorVariable",
        .fraud_detector_outcome = "FraudDetectorOutcome",
        .io_t_authorizer = "IoTAuthorizer",
        .io_t_security_profile = "IoTSecurityProfile",
        .io_t_role_alias = "IoTRoleAlias",
        .io_t_dimension = "IoTDimension",
        .io_t_analytics_datastore = "IoTAnalyticsDatastore",
        .lightsail_bucket = "LightsailBucket",
        .lightsail_static_ip = "LightsailStaticIp",
        .media_package_packaging_group = "MediaPackagePackagingGroup",
        .route_53_recovery_readiness_recovery_group = "Route53RecoveryReadinessRecoveryGroup",
        .resilience_hub_resiliency_policy = "ResilienceHubResiliencyPolicy",
        .transfer_workflow = "TransferWorkflow",
        .eks_identity_provider_config = "EKSIdentityProviderConfig",
        .eks_addon = "EKSAddon",
        .glue_ml_transform = "GlueMLTransform",
        .io_t_policy = "IoTPolicy",
        .io_t_mitigation_action = "IoTMitigationAction",
        .io_t_twin_maker_workspace = "IoTTwinMakerWorkspace",
        .io_t_twin_maker_entity = "IoTTwinMakerEntity",
        .io_t_analytics_dataset = "IoTAnalyticsDataset",
        .io_t_analytics_pipeline = "IoTAnalyticsPipeline",
        .io_t_analytics_channel = "IoTAnalyticsChannel",
        .io_t_site_wise_dashboard = "IoTSiteWiseDashboard",
        .io_t_site_wise_project = "IoTSiteWiseProject",
        .io_t_site_wise_portal = "IoTSiteWisePortal",
        .io_t_site_wise_asset_model = "IoTSiteWiseAssetModel",
        .ivs_channel = "IVSChannel",
        .ivs_recording_configuration = "IVSRecordingConfiguration",
        .ivs_playback_key_pair = "IVSPlaybackKeyPair",
        .kinesis_analytics_v2_application = "KinesisAnalyticsV2Application",
        .rds_global_cluster = "RDSGlobalCluster",
        .s3_multi_region_access_point = "S3MultiRegionAccessPoint",
        .device_farm_test_grid_project = "DeviceFarmTestGridProject",
        .budgets_budgets_action = "BudgetsBudgetsAction",
        .lex_bot = "LexBot",
        .code_guru_reviewer_repository_association = "CodeGuruReviewerRepositoryAssociation",
        .io_t_custom_metric = "IoTCustomMetric",
        .route_53_resolver_firewall_domain_list = "Route53ResolverFirewallDomainList",
        .robo_maker_robot_application_version = "RoboMakerRobotApplicationVersion",
        .ec2_traffic_mirror_session = "EC2TrafficMirrorSession",
        .io_t_site_wise_gateway = "IoTSiteWiseGateway",
        .lex_bot_alias = "LexBotAlias",
        .lookout_metrics_alert = "LookoutMetricsAlert",
        .io_t_account_audit_configuration = "IoTAccountAuditConfiguration",
        .ec2_traffic_mirror_target = "EC2TrafficMirrorTarget",
        .s3_storage_lens = "S3StorageLens",
        .io_t_scheduled_audit = "IoTScheduledAudit",
        .events_connection = "EventsConnection",
        .event_schemas_schema = "EventSchemasSchema",
        .media_package_packaging_configuration = "MediaPackagePackagingConfiguration",
        .kinesis_video_signaling_channel = "KinesisVideoSignalingChannel",
        .app_stream_directory_config = "AppStreamDirectoryConfig",
        .lookout_vision_project = "LookoutVisionProject",
        .route_53_recovery_control_cluster = "Route53RecoveryControlCluster",
        .route_53_recovery_control_safety_rule = "Route53RecoveryControlSafetyRule",
        .route_53_recovery_control_control_panel = "Route53RecoveryControlControlPanel",
        .route_53_recovery_control_routing_control = "Route53RecoveryControlRoutingControl",
        .route_53_recovery_readiness_resource_set = "Route53RecoveryReadinessResourceSet",
        .robo_maker_simulation_application = "RoboMakerSimulationApplication",
        .robo_maker_robot_application = "RoboMakerRobotApplication",
        .health_lake_fhir_datastore = "HealthLakeFHIRDatastore",
        .pinpoint_segment = "PinpointSegment",
        .pinpoint_application_settings = "PinpointApplicationSettings",
        .events_rule = "EventsRule",
        .ec2_dhcp_options = "EC2DHCPOptions",
        .ec2_network_insights_path = "EC2NetworkInsightsPath",
        .ec2_traffic_mirror_filter = "EC2TrafficMirrorFilter",
        .ec2_ipam = "EC2IPAM",
        .io_t_twin_maker_scene = "IoTTwinMakerScene",
        .network_manager_transit_gateway_registration = "NetworkManagerTransitGatewayRegistration",
        .customer_profiles_domain = "CustomerProfilesDomain",
        .auto_scaling_warm_pool = "AutoScalingWarmPool",
        .connect_phone_number = "ConnectPhoneNumber",
        .app_config_deployment_strategy = "AppConfigDeploymentStrategy",
        .app_flow_flow = "AppFlowFlow",
        .audit_manager_assessment = "AuditManagerAssessment",
        .cloud_watch_metric_stream = "CloudWatchMetricStream",
        .device_farm_instance_profile = "DeviceFarmInstanceProfile",
        .device_farm_project = "DeviceFarmProject",
        .ec2_ec2_fleet = "EC2EC2Fleet",
        .ec2_subnet_route_table_association = "EC2SubnetRouteTableAssociation",
        .ecr_pull_through_cache_rule = "ECRPullThroughCacheRule",
        .ground_station_config = "GroundStationConfig",
        .image_builder_image_pipeline = "ImageBuilderImagePipeline",
        .io_t_fleet_metric = "IoTFleetMetric",
        .io_t_wireless_service_profile = "IoTWirelessServiceProfile",
        .network_manager_device = "NetworkManagerDevice",
        .network_manager_global_network = "NetworkManagerGlobalNetwork",
        .network_manager_link = "NetworkManagerLink",
        .network_manager_site = "NetworkManagerSite",
        .panorama_package = "PanoramaPackage",
        .pinpoint_app = "PinpointApp",
        .redshift_scheduled_action = "RedshiftScheduledAction",
        .route_53_resolver_firewall_rule_group_association = "Route53ResolverFirewallRuleGroupAssociation",
        .sage_maker_app_image_config = "SageMakerAppImageConfig",
        .sage_maker_image = "SageMakerImage",
        .ecs_task_set = "ECSTaskSet",
        .cassandra_keyspace = "CassandraKeyspace",
        .signer_signing_profile = "SignerSigningProfile",
        .amplify_app = "AmplifyApp",
        .app_mesh_virtual_node = "AppMeshVirtualNode",
        .app_mesh_virtual_service = "AppMeshVirtualService",
        .app_runner_vpc_connector = "AppRunnerVpcConnector",
        .app_stream_application = "AppStreamApplication",
        .code_artifact_repository = "CodeArtifactRepository",
        .ec2_prefix_list = "EC2PrefixList",
        .ec2_spot_fleet = "EC2SpotFleet",
        .evidently_project = "EvidentlyProject",
        .forecast_dataset = "ForecastDataset",
        .iamsaml_provider = "IAMSAMLProvider",
        .iam_server_certificate = "IAMServerCertificate",
        .pinpoint_campaign = "PinpointCampaign",
        .pinpoint_in_app_template = "PinpointInAppTemplate",
        .sage_maker_domain = "SageMakerDomain",
        .transfer_agreement = "TransferAgreement",
        .transfer_connector = "TransferConnector",
        .kinesis_firehose_delivery_stream = "KinesisFirehoseDeliveryStream",
        .amplify_branch = "AmplifyBranch",
        .app_integrations_event_integration = "AppIntegrationsEventIntegration",
        .app_mesh_route = "AppMeshRoute",
        .athena_prepared_statement = "AthenaPreparedStatement",
        .ec2_ipam_scope = "EC2IPAMScope",
        .evidently_launch = "EvidentlyLaunch",
        .forecast_dataset_group = "ForecastDatasetGroup",
        .greengrass_v2_component_version = "GreengrassV2ComponentVersion",
        .ground_station_mission_profile = "GroundStationMissionProfile",
        .media_connect_flow_entitlement = "MediaConnectFlowEntitlement",
        .media_connect_flow_vpc_interface = "MediaConnectFlowVpcInterface",
        .media_tailor_playback_configuration = "MediaTailorPlaybackConfiguration",
        .msk_configuration = "MSKConfiguration",
        .personalize_dataset = "PersonalizeDataset",
        .personalize_schema = "PersonalizeSchema",
        .personalize_solution = "PersonalizeSolution",
        .pinpoint_email_template = "PinpointEmailTemplate",
        .pinpoint_event_stream = "PinpointEventStream",
        .resilience_hub_app = "ResilienceHubApp",
        .acmpca_certificate_authority = "ACMPCACertificateAuthority",
        .app_config_hosted_configuration_version = "AppConfigHostedConfigurationVersion",
        .app_mesh_virtual_gateway = "AppMeshVirtualGateway",
        .app_mesh_virtual_router = "AppMeshVirtualRouter",
        .app_runner_service = "AppRunnerService",
        .customer_profiles_object_type = "CustomerProfilesObjectType",
        .dms_endpoint = "DMSEndpoint",
        .ec2_capacity_reservation = "EC2CapacityReservation",
        .ec2_client_vpn_endpoint = "EC2ClientVpnEndpoint",
        .kendra_index = "KendraIndex",
        .kinesis_video_stream = "KinesisVideoStream",
        .logs_destination = "LogsDestination",
        .pinpoint_email_channel = "PinpointEmailChannel",
        .s3_access_point = "S3AccessPoint",
        .network_manager_customer_gateway_association = "NetworkManagerCustomerGatewayAssociation",
        .network_manager_link_association = "NetworkManagerLinkAssociation",
        .io_t_wireless_multicast_group = "IoTWirelessMulticastGroup",
        .personalize_dataset_group = "PersonalizeDatasetGroup",
        .io_t_twin_maker_component_type = "IoTTwinMakerComponentType",
        .code_build_report_group = "CodeBuildReportGroup",
        .sage_maker_feature_group = "SageMakerFeatureGroup",
        .msk_batch_scram_secret = "MSKBatchScramSecret",
        .app_stream_stack = "AppStreamStack",
        .io_t_job_template = "IoTJobTemplate",
        .io_t_wireless_fuota_task = "IoTWirelessFuotaTask",
        .io_t_provisioning_template = "IoTProvisioningTemplate",
        .inspector_v2_filter = "InspectorV2Filter",
        .route_53_resolver_resolver_query_logging_config_association = "Route53ResolverResolverQueryLoggingConfigAssociation",
        .service_discovery_instance = "ServiceDiscoveryInstance",
        .transfer_certificate = "TransferCertificate",
        .media_connect_flow_source = "MediaConnectFlowSource",
        .aps_rule_groups_namespace = "APSRuleGroupsNamespace",
        .code_guru_profiler_profiling_group = "CodeGuruProfilerProfilingGroup",
        .route_53_resolver_resolver_query_logging_config = "Route53ResolverResolverQueryLoggingConfig",
        .batch_scheduling_policy = "BatchSchedulingPolicy",
        .acmpca_certificate_authority_activation = "ACMPCACertificateAuthorityActivation",
        .app_mesh_gateway_route = "AppMeshGatewayRoute",
        .app_mesh_mesh = "AppMeshMesh",
        .connect_instance = "ConnectInstance",
        .connect_quick_connect = "ConnectQuickConnect",
        .ec2_carrier_gateway = "EC2CarrierGateway",
        .ec2_ipam_pool = "EC2IPAMPool",
        .ec2_transit_gateway_connect = "EC2TransitGatewayConnect",
        .ec2_transit_gateway_multicast_domain = "EC2TransitGatewayMulticastDomain",
        .ecs_capacity_provider = "ECSCapacityProvider",
        .iam_instance_profile = "IAMInstanceProfile",
        .io_tca_certificate = "IoTCACertificate",
        .io_t_twin_maker_sync_job = "IoTTwinMakerSyncJob",
        .kafka_connect_connector = "KafkaConnectConnector",
        .lambda_code_signing_config = "LambdaCodeSigningConfig",
        .network_manager_connect_peer = "NetworkManagerConnectPeer",
        .resource_explorer_2_index = "ResourceExplorer2Index",
        .app_stream_fleet = "AppStreamFleet",
        .cognito_user_pool = "CognitoUserPool",
        .cognito_user_pool_client = "CognitoUserPoolClient",
        .cognito_user_pool_group = "CognitoUserPoolGroup",
        .ec2_network_insights_access_scope = "EC2NetworkInsightsAccessScope",
        .ec2_network_insights_analysis = "EC2NetworkInsightsAnalysis",
        .grafana_workspace = "GrafanaWorkspace",
        .ground_station_dataflow_endpoint_group = "GroundStationDataflowEndpointGroup",
        .image_builder_image_recipe = "ImageBuilderImageRecipe",
        .kms_alias = "KMSAlias",
        .m2_environment = "M2Environment",
        .quick_sight_data_source = "QuickSightDataSource",
        .quick_sight_template = "QuickSightTemplate",
        .quick_sight_theme = "QuickSightTheme",
        .rds_option_group = "RDSOptionGroup",
        .redshift_endpoint_access = "RedshiftEndpointAccess",
        .route_53_resolver_firewall_rule_group = "Route53ResolverFirewallRuleGroup",
        .ssm_document = "SSMDocument",
        .app_config_extension_association = "AppConfigExtensionAssociation",
        .app_integrations_application = "AppIntegrationsApplication",
        .app_sync_api_cache = "AppSyncApiCache",
        .bedrock_guardrail = "BedrockGuardrail",
        .bedrock_knowledge_base = "BedrockKnowledgeBase",
        .cognito_identity_pool = "CognitoIdentityPool",
        .connect_rule = "ConnectRule",
        .connect_user = "ConnectUser",
        .ec2_client_vpn_target_network_association = "EC2ClientVpnTargetNetworkAssociation",
        .ec2_eip_association = "EC2EIPAssociation",
        .ec2_ipam_resource_discovery = "EC2IPAMResourceDiscovery",
        .ec2_ipam_resource_discovery_association = "EC2IPAMResourceDiscoveryAssociation",
        .ec2_instance_connect_endpoint = "EC2InstanceConnectEndpoint",
        .ec2_snapshot_block_public_access = "EC2SnapshotBlockPublicAccess",
        .ec2_vpc_block_public_access_exclusion = "EC2VPCBlockPublicAccessExclusion",
        .ec2_vpc_block_public_access_options = "EC2VPCBlockPublicAccessOptions",
        .ec2_vpc_endpoint_connection_notification = "EC2VPCEndpointConnectionNotification",
        .ec2_vpn_connection_route = "EC2VPNConnectionRoute",
        .evidently_segment = "EvidentlySegment",
        .iamoidc_provider = "IAMOIDCProvider",
        .inspector_v2_activation = "InspectorV2Activation",
        .msk_cluster_policy = "MSKClusterPolicy",
        .msk_vpc_connection = "MSKVpcConnection",
        .media_connect_gateway = "MediaConnectGateway",
        .memory_db_subnet_group = "MemoryDBSubnetGroup",
        .open_search_serverless_collection = "OpenSearchServerlessCollection",
        .open_search_serverless_vpc_endpoint = "OpenSearchServerlessVpcEndpoint",
        .redshift_endpoint_authorization = "RedshiftEndpointAuthorization",
        .route_53_profiles_profile = "Route53ProfilesProfile",
        .s3_storage_lens_group = "S3StorageLensGroup",
        .s3_express_bucket_policy = "S3ExpressBucketPolicy",
        .s3_express_directory_bucket = "S3ExpressDirectoryBucket",
        .sage_maker_inference_experiment = "SageMakerInferenceExperiment",
        .security_hub_standard = "SecurityHubStandard",
        .transfer_profile = "TransferProfile",
        .cloud_formation_stack_set = "CloudFormationStackSet",
        .media_package_v2_channel = "MediaPackageV2Channel",
        .s3_access_grants_location = "S3AccessGrantsLocation",
        .s3_access_grant = "S3AccessGrant",
        .s3_access_grants_instance = "S3AccessGrantsInstance",
        .emr_serverless_application = "EMRServerlessApplication",
        .config_aggregation_authorization = "ConfigAggregationAuthorization",
        .bedrock_application_inference_profile = "BedrockApplicationInferenceProfile",
        .api_gateway_v2_integration = "ApiGatewayV2Integration",
        .sage_maker_mlflow_tracking_server = "SageMakerMlflowTrackingServer",
        .sage_maker_model_bias_job_definition = "SageMakerModelBiasJobDefinition",
        .secrets_manager_rotation_schedule = "SecretsManagerRotationSchedule",
        .deadline_queue_fleet_association = "DeadlineQueueFleetAssociation",
        .ecr_repository_creation_template = "ECRRepositoryCreationTemplate",
        .cloud_formation_lambda_hook = "CloudFormationLambdaHook",
        .ec2_subnet_network_acl_association = "EC2SubnetNetworkAclAssociation",
        .api_gateway_usage_plan = "ApiGatewayUsagePlan",
        .app_config_extension = "AppConfigExtension",
        .deadline_fleet = "DeadlineFleet",
        .emr_studio = "EMRStudio",
        .s3_tables_table_bucket = "S3TablesTableBucket",
        .cloud_front_realtime_log_config = "CloudFrontRealtimeLogConfig",
        .backup_gateway_hypervisor = "BackupGatewayHypervisor",
        .bcm_data_exports_export = "BCMDataExportsExport",
        .cloud_formation_guard_hook = "CloudFormationGuardHook",
        .cloud_front_public_key = "CloudFrontPublicKey",
        .cloud_trail_event_data_store = "CloudTrailEventDataStore",
        .entity_resolution_id_mapping_workflow = "EntityResolutionIdMappingWorkflow",
        .entity_resolution_schema_mapping = "EntityResolutionSchemaMapping",
        .io_t_domain_configuration = "IoTDomainConfiguration",
        .pca_connector_ad_directory_registration = "PCAConnectorADDirectoryRegistration",
        .rds_integration = "RDSIntegration",
        .config_conformance_pack = "ConfigConformancePack",
        .roles_anywhere_profile = "RolesAnywhereProfile",
        .code_artifact_domain = "CodeArtifactDomain",
        .backup_restore_testing_plan = "BackupRestoreTestingPlan",
        .config_stored_query = "ConfigStoredQuery",
        .sage_maker_data_quality_job_definition = "SageMakerDataQualityJobDefinition",
        .sage_maker_model_explainability_job_definition = "SageMakerModelExplainabilityJobDefinition",
        .sage_maker_model_quality_job_definition = "SageMakerModelQualityJobDefinition",
        .sage_maker_studio_lifecycle_config = "SageMakerStudioLifecycleConfig",
        .ses_dedicated_ip_pool = "SESDedicatedIpPool",
        .ses_mail_manager_traffic_policy = "SESMailManagerTrafficPolicy",
        .ssm_resource_data_sync = "SSMResourceDataSync",
        .bedrock_agent_core_runtime = "BedrockAgentCoreRuntime",
        .bedrock_agent_core_browser_custom = "BedrockAgentCoreBrowserCustom",
        .elastic_load_balancing_v2_target_group = "ElasticLoadBalancingV2TargetGroup",
        .emr_containers_virtual_cluster = "EMRContainersVirtualCluster",
        .entity_resolution_matching_workflow = "EntityResolutionMatchingWorkflow",
        .io_t_core_device_advisor_suite_definition = "IoTCoreDeviceAdvisorSuiteDefinition",
        .ec2_security_group_vpc_association = "EC2SecurityGroupVpcAssociation",
        .ec2_verified_access_instance = "EC2VerifiedAccessInstance",
        .kafka_connect_custom_plugin = "KafkaConnectCustomPlugin",
        .network_manager_transit_gateway_peering = "NetworkManagerTransitGatewayPeering",
        .open_search_serverless_security_config = "OpenSearchServerlessSecurityConfig",
        .redshift_integration = "RedshiftIntegration",
        .roles_anywhere_trust_anchor = "RolesAnywhereTrustAnchor",
        .route_53_profiles_profile_association = "Route53ProfilesProfileAssociation",
        .ssm_incidents_response_plan = "SSMIncidentsResponsePlan",
        .transfer_server = "TransferServer",
        .glue_database = "GlueDatabase",
        .organizations_organizational_unit = "OrganizationsOrganizationalUnit",
        .ec2_ipam_pool_cidr = "EC2IPAMPoolCidr",
        .ec2_vpc_gateway_attachment = "EC2VPCGatewayAttachment",
        .bedrock_prompt = "BedrockPrompt",
        .comprehend_flywheel = "ComprehendFlywheel",
        .data_sync_agent = "DataSyncAgent",
        .media_tailor_live_source = "MediaTailorLiveSource",
        .msk_serverless_cluster = "MSKServerlessCluster",
        .io_t_site_wise_asset = "IoTSiteWiseAsset",
        .b2_bi_capability = "B2BICapability",
        .cloud_front_key_value_store = "CloudFrontKeyValueStore",
        .deadline_monitor = "DeadlineMonitor",
        .guard_duty_malware_protection_plan = "GuardDutyMalwareProtectionPlan",
        .location_api_key = "LocationAPIKey",
        .media_package_v2_origin_endpoint = "MediaPackageV2OriginEndpoint",
        .pca_connector_ad_connector = "PCAConnectorADConnector",
        .s3_tables_table_bucket_policy = "S3TablesTableBucketPolicy",
        .secrets_manager_resource_policy = "SecretsManagerResourcePolicy",
        .ssm_contacts_contact = "SSMContactsContact",
        .io_t_thing_group = "IoTThingGroup",
        .image_builder_lifecycle_policy = "ImageBuilderLifecyclePolicy",
        .game_lift_build = "GameLiftBuild",
        .ecr_replication_configuration = "ECRReplicationConfiguration",
        .ec2_subnet_cidr_block = "EC2SubnetCidrBlock",
        .connect_security_profile = "ConnectSecurityProfile",
        .clean_rooms_ml_training_dataset = "CleanRoomsMLTrainingDataset",
        .app_stream_app_block_builder = "AppStreamAppBlockBuilder",
        .route_53_dnssec = "Route53DNSSEC",
        .sage_maker_user_profile = "SageMakerUserProfile",
        .api_gateway_method = "ApiGatewayMethod",
    };
};
