const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const DestinationConfiguration = @import("destination_configuration.zig").DestinationConfiguration;
const CreateLoggingConfigurationState = @import("create_logging_configuration_state.zig").CreateLoggingConfigurationState;

pub const CreateLoggingConfigurationInput = struct {
    /// A complex type that contains a destination configuration for where chat
    /// content will be
    /// logged. There can be only one type of destination (`cloudWatchLogs`,
    /// `firehose`, or `s3`) in a
    /// `destinationConfiguration`.
    destination_configuration: DestinationConfiguration,

    /// Logging-configuration name. The value does not need to be unique.
    name: ?[]const u8 = null,

    /// Tags to attach to the resource. Array of maps, each of the form
    /// `string:string
    /// (key:value)`. See [Best practices and
    /// strategies](https://docs.aws.amazon.com/tag-editor/latest/userguide/best-practices-and-strats.html) in *Tagging Amazon Web Services Resources and Tag Editor* for details, including restrictions that apply to tags and "Tag naming limits and requirements"; Amazon IVS Chat has no constraints on tags beyond what is
    /// documented there.
    tags: ?[]const aws.map.StringMapEntry = null,

    pub const json_field_names = .{
        .destination_configuration = "destinationConfiguration",
        .name = "name",
        .tags = "tags",
    };
};

pub const CreateLoggingConfigurationOutput = struct {
    /// Logging-configuration ARN, assigned by the system.
    arn: ?[]const u8 = null,

    /// Time when the logging configuration was created. This is an ISO 8601
    /// timestamp;
    /// *note that this is returned as a string*.
    create_time: ?i64 = null,

    /// A complex type that contains a destination configuration for where chat
    /// content will be
    /// logged, from the request. There is only one type of destination
    /// (`cloudWatchLogs`, `firehose`, or `s3`) in a
    /// `destinationConfiguration`.
    destination_configuration: ?DestinationConfiguration = null,

    /// Logging-configuration ID, generated by the system. This is a relative
    /// identifier, the
    /// part of the ARN that uniquely identifies the logging configuration.
    id: ?[]const u8 = null,

    /// Logging-configuration name, from the request (if specified).
    name: ?[]const u8 = null,

    /// The state of the logging configuration. When the state is `ACTIVE`, the
    /// configuration is ready to log chat content.
    state: ?CreateLoggingConfigurationState = null,

    /// Tags attached to the resource, from the request (if specified). Array of
    /// maps, each of
    /// the form `string:string (key:value)`.
    tags: ?[]const aws.map.StringMapEntry = null,

    /// Time of the logging configuration’s last update. This is an ISO 8601
    /// timestamp;
    /// *note that this is returned as a string*.
    update_time: ?i64 = null,

    pub const json_field_names = .{
        .arn = "arn",
        .create_time = "createTime",
        .destination_configuration = "destinationConfiguration",
        .id = "id",
        .name = "name",
        .state = "state",
        .tags = "tags",
        .update_time = "updateTime",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateLoggingConfigurationInput, options: CallOptions) !CreateLoggingConfigurationOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "ivschat", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateLoggingConfigurationInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("ivschat", "ivschat", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/CreateLoggingConfiguration";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"destinationConfiguration\":");
    try aws.json.writeValue(@TypeOf(input.destination_configuration), input.destination_configuration, allocator, &body_buf);
    has_prev = true;
    if (input.name) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"name\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.tags) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"tags\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateLoggingConfigurationOutput {
    const result: CreateLoggingConfigurationOutput = try aws.json.parseJsonObject(
        CreateLoggingConfigurationOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
