const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const DestinationConfiguration = @import("destination_configuration.zig").DestinationConfiguration;
const LoggingConfigurationState = @import("logging_configuration_state.zig").LoggingConfigurationState;

pub const GetLoggingConfigurationInput = struct {
    /// Identifier of the logging configuration to be retrieved.
    identifier: []const u8,

    pub const json_field_names = .{
        .identifier = "identifier",
    };
};

pub const GetLoggingConfigurationOutput = struct {
    /// Logging-configuration ARN, from the request (if `identifier` was an
    /// ARN).
    arn: ?[]const u8 = null,

    /// Time when the logging configuration was created. This is an ISO 8601
    /// timestamp;
    /// *note that this is returned as a string*.
    create_time: ?i64 = null,

    /// A complex type that contains a destination configuration for where chat
    /// content will be
    /// logged. There is only one type of destination (`cloudWatchLogs`,
    /// `firehose`, or `s3`) in a
    /// `destinationConfiguration`.
    destination_configuration: ?DestinationConfiguration = null,

    /// Logging-configuration ID, generated by the system. This is a relative
    /// identifier, the
    /// part of the ARN that uniquely identifies the logging configuration.
    id: ?[]const u8 = null,

    /// Logging-configuration name. This value does not need to be unique.
    name: ?[]const u8 = null,

    /// The state of the logging configuration. When the state is `ACTIVE`, the
    /// configuration is ready to log chat content.
    state: ?LoggingConfigurationState = null,

    /// Tags attached to the resource. Array of maps, each of the form
    /// `string:string
    /// (key:value)`.
    tags: ?[]const aws.map.StringMapEntry = null,

    /// Time of the logging configuration’s last update. This is an ISO 8601
    /// timestamp;
    /// *note that this is returned as a string*.
    update_time: ?i64 = null,

    pub const json_field_names = .{
        .arn = "arn",
        .create_time = "createTime",
        .destination_configuration = "destinationConfiguration",
        .id = "id",
        .name = "name",
        .state = "state",
        .tags = "tags",
        .update_time = "updateTime",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetLoggingConfigurationInput, options: CallOptions) !GetLoggingConfigurationOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "ivschat", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetLoggingConfigurationInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("ivschat", "ivschat", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const path = "/GetLoggingConfiguration";

    var body_buf: std.ArrayList(u8) = .empty;
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"identifier\":");
    try aws.json.writeValue(@TypeOf(input.identifier), input.identifier, allocator, &body_buf);
    has_prev = true;

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetLoggingConfigurationOutput {
    const result: GetLoggingConfigurationOutput = try aws.json.parseJsonObject(
        GetLoggingConfigurationOutput,
        if (body.len > 0) body else "{}",
        allocator,
    );
    _ = status;
    _ = headers;

    return result;
}
