const aws = @import("aws");

const MessageReviewHandler = @import("message_review_handler.zig").MessageReviewHandler;

/// Summary information about a room.
pub const RoomSummary = struct {
    /// Room ARN.
    arn: ?[]const u8 = null,

    /// Time when the room was created. This is an ISO 8601 timestamp; *note that
    /// this is
    /// returned as a string*.
    create_time: ?i64 = null,

    /// Room ID, generated by the system. This is a relative identifier, the part of
    /// the ARN that
    /// uniquely identifies the room.
    id: ?[]const u8 = null,

    /// List of logging-configuration identifiers attached to the room.
    logging_configuration_identifiers: ?[]const []const u8 = null,

    /// Configuration information for optional review of messages.
    message_review_handler: ?MessageReviewHandler = null,

    /// Room name. The value does not need to be unique.
    name: ?[]const u8 = null,

    /// Tags attached to the resource. Array of maps, each of the form
    /// `string:string
    /// (key:value)`. See [Best practices and
    /// strategies](https://docs.aws.amazon.com/tag-editor/latest/userguide/best-practices-and-strats.html) in *Tagging Amazon Web Services Resources and Tag Editor* for details, including restrictions that apply to tags and "Tag naming limits and requirements"; Amazon IVS Chat has no constraints beyond what is documented
    /// there.
    tags: ?[]const aws.map.StringMapEntry = null,

    /// Time of the room’s last update. This is an ISO 8601 timestamp; *note that
    /// this is
    /// returned as a string*.
    update_time: ?i64 = null,

    pub const json_field_names = .{
        .arn = "arn",
        .create_time = "createTime",
        .id = "id",
        .logging_configuration_identifiers = "loggingConfigurationIdentifiers",
        .message_review_handler = "messageReviewHandler",
        .name = "name",
        .tags = "tags",
        .update_time = "updateTime",
    };
};
