const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const ServiceError = @import("errors.zig").ServiceError;
const MessageReviewHandler = @import("message_review_handler.zig").MessageReviewHandler;

pub const UpdateRoomInput = struct {
    /// Identifier of the room to be updated. Currently this must be an ARN.
    identifier: []const u8,

    /// Array of logging-configuration identifiers attached to the room.
    logging_configuration_identifiers: ?[]const []const u8 = null,

    /// The maximum number of characters in a single message. Messages are expected
    /// to be UTF-8
    /// encoded and this limit applies specifically to rune/code-point count, not
    /// number of bytes.
    /// Default: 500.
    maximum_message_length: ?i32 = null,

    /// Maximum number of messages per second that can be sent to the room (by all
    /// clients).
    /// Default: 10.
    maximum_message_rate_per_second: ?i32 = null,

    /// Configuration information for optional review of messages. Specify an empty
    /// `uri` string to disassociate a message review handler from the specified
    /// room.
    message_review_handler: ?MessageReviewHandler = null,

    /// Room name. The value does not need to be unique.
    name: ?[]const u8 = null,

    pub const json_field_names = .{
        .identifier = "identifier",
        .logging_configuration_identifiers = "loggingConfigurationIdentifiers",
        .maximum_message_length = "maximumMessageLength",
        .maximum_message_rate_per_second = "maximumMessageRatePerSecond",
        .message_review_handler = "messageReviewHandler",
        .name = "name",
    };
};

pub const UpdateRoomOutput = struct {
    /// Room ARN, from the request (if `identifier` was an ARN).
    arn: ?[]const u8 = null,

    /// Time when the room was created. This is an ISO 8601 timestamp; *note that
    /// this
    /// is returned as a string*.
    create_time: ?i64 = null,

    /// Room ID, generated by the system. This is a relative identifier, the part of
    /// the ARN
    /// that uniquely identifies the room.
    id: ?[]const u8 = null,

    /// Array of logging configurations attached to the room, from the request (if
    /// specified).
    logging_configuration_identifiers: ?[]const []const u8 = null,

    /// Maximum number of characters in a single message, from the request (if
    /// specified).
    maximum_message_length: ?i32 = null,

    /// Maximum number of messages per second that can be sent to the room (by all
    /// clients),
    /// from the request (if specified).
    maximum_message_rate_per_second: ?i32 = null,

    /// Configuration information for optional review of messages.
    message_review_handler: ?MessageReviewHandler = null,

    /// Room name, from the request (if specified).
    name: ?[]const u8 = null,

    /// Tags attached to the resource. Array of maps, each of the form
    /// `string:string
    /// (key:value)`.
    tags: ?[]const aws.map.StringMapEntry = null,

    /// Time of the room’s last update. This is an ISO 8601 timestamp; *note that
    /// this
    /// is returned as a string*.
    update_time: ?i64 = null,

    pub const json_field_names = .{
        .arn = "arn",
        .create_time = "createTime",
        .id = "id",
        .logging_configuration_identifiers = "loggingConfigurationIdentifiers",
        .maximum_message_length = "maximumMessageLength",
        .maximum_message_rate_per_second = "maximumMessageRatePerSecond",
        .message_review_handler = "messageReviewHandler",
        .name = "name",
        .tags = "tags",
        .update_time = "updateTime",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: UpdateRoomInput, options: CallOptions) !UpdateRoomOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(alloc);
    try aws.signing.signRequest(alloc, &request, creds, client.config.region, "ivschat");

    var response = try client.http_client.sendRequest(&request);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = parseErrorResponse(client.allocator, response.body, response.status) catch .{ .kind = .{ .unknown = .{ .http_status = @intCast(response.status) } } };
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: UpdateRoomInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("ivschat", "ivschat", allocator);

    const host = aws.url.parseHost(endpoint);
    const tls = !std.mem.startsWith(u8, endpoint, "http://");
    const port = aws.url.parsePort(endpoint);

    const path = "/UpdateRoom";

    var body_buf: std.ArrayList(u8) = .{};
    var has_prev = false;
    try body_buf.appendSlice(allocator, "{");

    if (has_prev) try body_buf.appendSlice(allocator, ",");
    try body_buf.appendSlice(allocator, "\"identifier\":");
    try aws.json.writeValue(@TypeOf(input.identifier), input.identifier, allocator, &body_buf);
    has_prev = true;
    if (input.logging_configuration_identifiers) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"loggingConfigurationIdentifiers\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.maximum_message_length) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"maximumMessageLength\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.maximum_message_rate_per_second) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"maximumMessageRatePerSecond\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.message_review_handler) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"messageReviewHandler\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }
    if (input.name) |v| {
        if (has_prev) try body_buf.appendSlice(allocator, ",");
        try body_buf.appendSlice(allocator, "\"name\":");
        try aws.json.writeValue(@TypeOf(v), v, allocator, &body_buf);
        has_prev = true;
    }

    try body_buf.appendSlice(allocator, "}");
    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(host);
    request.method = .POST;
    request.path = path;
    request.tls = tls;
    request.port = port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !UpdateRoomOutput {
    var result: UpdateRoomOutput = .{};
    if (body.len > 0) {
        result = try aws.json.parseJsonObject(UpdateRoomOutput, body, allocator);
    }
    _ = status;
    _ = headers;

    return result;
}

fn parseErrorResponse(allocator: std.mem.Allocator, body: []const u8, status: u16) !ServiceError {
    const error_code = blk: {
        const type_str = aws.json.findJsonValue(body, "__type") orelse break :blk @as([]const u8, "Unknown");
        if (std.mem.lastIndexOfScalar(u8, type_str, '#')) |idx| {
            break :blk type_str[idx + 1 ..];
        }
        break :blk type_str;
    };
    const error_message = aws.json.findJsonValue(body, "message") orelse aws.json.findJsonValue(body, "Message") orelse "";
    var arena = std.heap.ArenaAllocator.init(allocator);
    errdefer arena.deinit();
    const arena_alloc = arena.allocator();
    const owned_message = try arena_alloc.dupe(u8, error_message);
    const owned_request_id = try arena_alloc.dupe(u8, "");

    if (std.mem.eql(u8, error_code, "AccessDeniedException")) {
        return .{ .arena = arena, .kind = .{ .access_denied_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ConflictException")) {
        return .{ .arena = arena, .kind = .{ .conflict_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "InternalServerException")) {
        return .{ .arena = arena, .kind = .{ .internal_server_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "PendingVerification")) {
        return .{ .arena = arena, .kind = .{ .pending_verification = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ResourceNotFoundException")) {
        return .{ .arena = arena, .kind = .{ .resource_not_found_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ServiceQuotaExceededException")) {
        return .{ .arena = arena, .kind = .{ .service_quota_exceeded_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ThrottlingException")) {
        return .{ .arena = arena, .kind = .{ .throttling_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }
    if (std.mem.eql(u8, error_code, "ValidationException")) {
        return .{ .arena = arena, .kind = .{ .validation_exception = .{
            .message = owned_message,
            .request_id = owned_request_id,
        } } };
    }

    const owned_code = try arena_alloc.dupe(u8, error_code);
    return .{ .arena = arena, .kind = .{ .unknown = .{
        .code = owned_code,
        .message = owned_message,
        .request_id = owned_request_id,
        .http_status = status,
    } } };
}
