pub const ExecutionEventType = enum {
    unknown,
    execution_pending,
    execution_started,
    execution_succeeded,
    execution_failed,
    execution_pausing,
    execution_paused,
    execution_canceling,
    execution_canceled,
    execution_pending_approval,
    execution_behavior_changed_to_ungraceful,
    execution_behavior_changed_to_graceful,
    execution_pending_child_plan_manual_approval,
    execution_success_monitoring_application_health,
    step_started,
    step_update,
    step_succeeded,
    step_failed,
    step_skipped,
    step_paused_by_error,
    step_paused_by_operator,
    step_canceled,
    step_pending_approval,
    step_execution_behavior_changed_to_ungraceful,
    step_pending_application_health_monitor,
    plan_evaluation_warning,

    pub const json_field_names = .{
        .unknown = "UNKNOWN",
        .execution_pending = "EXECUTION_PENDING",
        .execution_started = "EXECUTION_STARTED",
        .execution_succeeded = "EXECUTION_SUCCEEDED",
        .execution_failed = "EXECUTION_FAILED",
        .execution_pausing = "EXECUTION_PAUSING",
        .execution_paused = "EXECUTION_PAUSED",
        .execution_canceling = "EXECUTION_CANCELING",
        .execution_canceled = "EXECUTION_CANCELED",
        .execution_pending_approval = "EXECUTION_PENDING_APPROVAL",
        .execution_behavior_changed_to_ungraceful = "EXECUTION_BEHAVIOR_CHANGED_TO_UNGRACEFUL",
        .execution_behavior_changed_to_graceful = "EXECUTION_BEHAVIOR_CHANGED_TO_GRACEFUL",
        .execution_pending_child_plan_manual_approval = "EXECUTION_PENDING_CHILD_PLAN_MANUAL_APPROVAL",
        .execution_success_monitoring_application_health = "EXECUTION_SUCCESS_MONITORING_APPLICATION_HEALTH",
        .step_started = "STEP_STARTED",
        .step_update = "STEP_UPDATE",
        .step_succeeded = "STEP_SUCCEEDED",
        .step_failed = "STEP_FAILED",
        .step_skipped = "STEP_SKIPPED",
        .step_paused_by_error = "STEP_PAUSED_BY_ERROR",
        .step_paused_by_operator = "STEP_PAUSED_BY_OPERATOR",
        .step_canceled = "STEP_CANCELED",
        .step_pending_approval = "STEP_PENDING_APPROVAL",
        .step_execution_behavior_changed_to_ungraceful = "STEP_EXECUTION_BEHAVIOR_CHANGED_TO_UNGRACEFUL",
        .step_pending_application_health_monitor = "STEP_PENDING_APPLICATION_HEALTH_MONITOR",
        .plan_evaluation_warning = "PLAN_EVALUATION_WARNING",
    };
};
