const TranscribeContentIdentificationType = @import("transcribe_content_identification_type.zig").TranscribeContentIdentificationType;
const TranscribeContentRedactionType = @import("transcribe_content_redaction_type.zig").TranscribeContentRedactionType;
const TranscribeLanguageCode = @import("transcribe_language_code.zig").TranscribeLanguageCode;
const TranscribePartialResultsStability = @import("transcribe_partial_results_stability.zig").TranscribePartialResultsStability;
const TranscribeRegion = @import("transcribe_region.zig").TranscribeRegion;
const TranscribeVocabularyFilterMethod = @import("transcribe_vocabulary_filter_method.zig").TranscribeVocabularyFilterMethod;

/// Settings specific for Amazon Transcribe as the live transcription engine.
///
/// If you specify an invalid combination of parameters, a `TranscriptFailed`
/// event will be sent with the contents of the
/// `BadRequestException` generated by Amazon Transcribe. For more information
/// on each parameter and which combinations are valid, refer to the
/// [StartStreamTranscription](https://docs.aws.amazon.com/transcribe/latest/APIReference/API_streaming_StartStreamTranscription.html) API in the
/// *Amazon Transcribe Developer Guide*.
pub const EngineTranscribeSettings = struct {
    /// Labels all personally identifiable information (PII) identified in your
    /// transcript. If you don't include `PiiEntityTypes`, all PII is identified.
    ///
    /// You can’t set `ContentIdentificationType` and `ContentRedactionType`.
    content_identification_type: ?TranscribeContentIdentificationType,

    /// Content redaction is performed at the segment level. If you don't include
    /// `PiiEntityTypes`, all PII is redacted.
    ///
    /// You can’t set `ContentRedactionType` and `ContentIdentificationType`.
    content_redaction_type: ?TranscribeContentRedactionType,

    /// Enables partial result stabilization for your transcription. Partial result
    /// stabilization can reduce latency in your output, but may impact accuracy.
    enable_partial_results_stabilization: bool = false,

    /// Enables automatic language identification for your transcription.
    ///
    /// If you include `IdentifyLanguage`, you can optionally use `LanguageOptions`
    /// to include a list of language codes that you think may be present in your
    /// audio stream.
    /// Including language options can improve transcription accuracy.
    ///
    /// You can also use `PreferredLanguage` to include a preferred language. Doing
    /// so can help Amazon Transcribe identify the language faster.
    ///
    /// You must include either `LanguageCode` or `IdentifyLanguage`.
    ///
    /// Language identification can't be combined with custom language models or
    /// redaction.
    identify_language: bool = false,

    /// Specify the language code that represents the language spoken.
    ///
    /// If you're unsure of the language spoken in your audio, consider using
    /// `IdentifyLanguage` to enable automatic language identification.
    language_code: ?TranscribeLanguageCode,

    /// Specify the name of the custom language model that you want to use when
    /// processing your transcription. Note that language model names are case
    /// sensitive.
    ///
    /// The language of the specified language model must match the language code.
    /// If the languages don't match, the custom language model isn't applied. There
    /// are no errors or warnings associated with
    /// a language mismatch.
    ///
    /// If you use Amazon Transcribe in multiple Regions, the custom language model
    /// must be available in Amazon Transcribe in each Region.
    language_model_name: ?[]const u8,

    /// Specify two or more language codes that represent the languages you think
    /// may be present in your media; including more than five is not recommended.
    /// If you're unsure what languages
    /// are present, do not include this parameter.
    ///
    /// Including language options can improve the accuracy of language
    /// identification.
    ///
    /// If you include `LanguageOptions`, you must also include `IdentifyLanguage`.
    ///
    /// You can only include one language dialect per language. For example, you
    /// cannot include `en-US` and `en-AU`.
    language_options: ?[]const u8,

    /// Specify the level of stability to use when you enable partial results
    /// stabilization (`EnablePartialResultsStabilization`).
    ///
    /// Low stability provides the highest accuracy. High stability transcribes
    /// faster, but with slightly lower accuracy.
    partial_results_stability: ?TranscribePartialResultsStability,

    /// Specify which types of personally identifiable information (PII) you want to
    /// redact in your transcript. You can include as many types as you'd like, or
    /// you can select `ALL`.
    ///
    /// Values must be comma-separated and can include: `ADDRESS`,
    /// `BANK_ACCOUNT_NUMBER`, `BANK_ROUTING`, `CREDIT_DEBIT_CVV`,
    /// `CREDIT_DEBIT_EXPIRY`
    /// `CREDIT_DEBIT_NUMBER`, `EMAIL`,`NAME`, `PHONE`, `PIN`,
    /// `SSN`, or `ALL`.
    ///
    /// Note that if you include `PiiEntityTypes`, you must also include
    /// `ContentIdentificationType` or `ContentRedactionType`.
    ///
    /// If you include `ContentRedactionType` or `ContentIdentificationType`, but do
    /// not include PiiEntityTypes, all PII is redacted or identified.
    pii_entity_types: ?[]const u8,

    /// Specify a preferred language from the subset of languages codes you
    /// specified in `LanguageOptions`.
    ///
    /// You can only use this parameter if you include `IdentifyLanguage` and
    /// `LanguageOptions`.
    preferred_language: ?TranscribeLanguageCode,

    /// The Amazon Web Services Region in which to use Amazon Transcribe.
    ///
    /// If you don't specify a Region, then the
    /// [MediaRegion](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateMeeting.html) of the meeting is used.
    /// However, if Amazon Transcribe is not available in the `MediaRegion`, then a
    /// `TranscriptFailed` event is sent.
    ///
    /// Use `auto` to use Amazon Transcribe in a Region near the meeting’s
    /// `MediaRegion`. For more information, refer to
    /// [Choosing a transcription
    /// Region](https://docs.aws.amazon.com/chime-sdk/latest/dg/transcription-options.html#choose-region) in the
    /// *Amazon Chime SDK Developer Guide*.
    region: ?TranscribeRegion,

    /// Specify how you want your vocabulary filter applied to your transcript.
    ///
    /// To replace words with `***`, choose `mask`.
    ///
    /// To delete words, choose `remove`.
    ///
    /// To flag words without changing them, choose `tag`.
    vocabulary_filter_method: ?TranscribeVocabularyFilterMethod,

    /// Specify the name of the custom vocabulary filter that you want to use when
    /// processing your transcription. Note that vocabulary filter names are case
    /// sensitive.
    ///
    /// If you use Amazon Transcribe in multiple Regions, the vocabulary filter must
    /// be available in Amazon Transcribe in each Region.
    ///
    /// If you include `IdentifyLanguage` and want to use one or more vocabulary
    /// filters with your transcription, use the `VocabularyFilterNames` parameter
    /// instead.
    vocabulary_filter_name: ?[]const u8,

    /// Specify the names of the custom vocabulary filters that you want to use when
    /// processing your transcription. Note that vocabulary filter names are case
    /// sensitive.
    ///
    /// If you use Amazon Transcribe in multiple Regions, the vocabulary filter must
    /// be available in Amazon Transcribe in each Region.
    ///
    /// If you're *not* including `IdentifyLanguage` and want to use a custom
    /// vocabulary filter with your transcription, use the `VocabularyFilterName`
    /// parameter instead.
    vocabulary_filter_names: ?[]const u8,

    /// Specify the name of the custom vocabulary that you want to use when
    /// processing your transcription. Note that vocabulary names are case
    /// sensitive.
    ///
    /// If you use Amazon Transcribe multiple Regions, the vocabulary must be
    /// available in Amazon Transcribe in each Region.
    ///
    /// If you include `IdentifyLanguage` and want to use one or more custom
    /// vocabularies with your transcription, use the `VocabularyNames`
    /// parameter instead.
    vocabulary_name: ?[]const u8,

    /// Specify the names of the custom vocabularies that you want to use when
    /// processing your transcription. Note that vocabulary names are case
    /// sensitive.
    ///
    /// If you use Amazon Transcribe in multiple Regions, the vocabulary must be
    /// available in Amazon Transcribe in each Region.
    ///
    /// If you don't include `IdentifyLanguage` and want to use a custom vocabulary
    /// with your transcription, use the `VocabularyName` parameter instead.
    vocabulary_names: ?[]const u8,

    pub const json_field_names = .{
        .content_identification_type = "ContentIdentificationType",
        .content_redaction_type = "ContentRedactionType",
        .enable_partial_results_stabilization = "EnablePartialResultsStabilization",
        .identify_language = "IdentifyLanguage",
        .language_code = "LanguageCode",
        .language_model_name = "LanguageModelName",
        .language_options = "LanguageOptions",
        .partial_results_stability = "PartialResultsStability",
        .pii_entity_types = "PiiEntityTypes",
        .preferred_language = "PreferredLanguage",
        .region = "Region",
        .vocabulary_filter_method = "VocabularyFilterMethod",
        .vocabulary_filter_name = "VocabularyFilterName",
        .vocabulary_filter_names = "VocabularyFilterNames",
        .vocabulary_name = "VocabularyName",
        .vocabulary_names = "VocabularyNames",
    };
};
