pub const ResourceType = enum {
    account,
    phone_number,
    sender_id,
    pool,
    configuration_set,
    opt_out_list,
    event_destination,
    keyword,
    opted_out_number,
    registration,
    registration_attachment,
    verified_destination_number,
    protect_configuration,
    message_template,
    policy,
    message,

    pub const json_field_names = .{
        .account = "ACCOUNT",
        .phone_number = "PHONE_NUMBER",
        .sender_id = "SENDER_ID",
        .pool = "POOL",
        .configuration_set = "CONFIGURATION_SET",
        .opt_out_list = "OPT_OUT_LIST",
        .event_destination = "EVENT_DESTINATION",
        .keyword = "KEYWORD",
        .opted_out_number = "OPTED_OUT_NUMBER",
        .registration = "REGISTRATION",
        .registration_attachment = "REGISTRATION_ATTACHMENT",
        .verified_destination_number = "VERIFIED_DESTINATION_NUMBER",
        .protect_configuration = "PROTECT_CONFIGURATION",
        .message_template = "MESSAGE_TEMPLATE",
        .policy = "POLICY",
        .message = "MESSAGE",
    };
};
