pub const ServiceQuotaExceededExceptionReason = enum {
    associations_per_registration,
    configuration_sets_per_account,
    daily_destination_call_limit,
    event_destinations_per_configuration_set,
    keywords_per_phone_number,
    keywords_per_pool,
    monthly_spend_limit_reached_for_media,
    monthly_spend_limit_reached_for_text,
    monthly_spend_limit_reached_for_voice,
    opt_out_lists_per_account,
    origination_identities_per_pool,
    phone_numbers_per_account,
    phone_numbers_per_registration,
    pools_per_account,
    registration_attachments_created_per_day,
    registration_attachments_per_account,
    registration_versions_created_per_day,
    registrations_per_account,
    sender_ids_per_account,
    tags_per_resource,
    verified_destination_numbers_per_account,
    verification_attempts_per_day,
    protect_configurations_per_account,

    pub const json_field_names = .{
        .associations_per_registration = "ASSOCIATIONS_PER_REGISTRATION",
        .configuration_sets_per_account = "CONFIGURATION_SETS_PER_ACCOUNT",
        .daily_destination_call_limit = "DAILY_DESTINATION_CALL_LIMIT",
        .event_destinations_per_configuration_set = "EVENT_DESTINATIONS_PER_CONFIGURATION_SET",
        .keywords_per_phone_number = "KEYWORDS_PER_PHONE_NUMBER",
        .keywords_per_pool = "KEYWORDS_PER_POOL",
        .monthly_spend_limit_reached_for_media = "MONTHLY_SPEND_LIMIT_REACHED_FOR_MEDIA",
        .monthly_spend_limit_reached_for_text = "MONTHLY_SPEND_LIMIT_REACHED_FOR_TEXT",
        .monthly_spend_limit_reached_for_voice = "MONTHLY_SPEND_LIMIT_REACHED_FOR_VOICE",
        .opt_out_lists_per_account = "OPT_OUT_LISTS_PER_ACCOUNT",
        .origination_identities_per_pool = "ORIGINATION_IDENTITIES_PER_POOL",
        .phone_numbers_per_account = "PHONE_NUMBERS_PER_ACCOUNT",
        .phone_numbers_per_registration = "PHONE_NUMBERS_PER_REGISTRATION",
        .pools_per_account = "POOLS_PER_ACCOUNT",
        .registration_attachments_created_per_day = "REGISTRATION_ATTACHMENTS_CREATED_PER_DAY",
        .registration_attachments_per_account = "REGISTRATION_ATTACHMENTS_PER_ACCOUNT",
        .registration_versions_created_per_day = "REGISTRATION_VERSIONS_CREATED_PER_DAY",
        .registrations_per_account = "REGISTRATIONS_PER_ACCOUNT",
        .sender_ids_per_account = "SENDER_IDS_PER_ACCOUNT",
        .tags_per_resource = "TAGS_PER_RESOURCE",
        .verified_destination_numbers_per_account = "VERIFIED_DESTINATION_NUMBERS_PER_ACCOUNT",
        .verification_attempts_per_day = "VERIFICATION_ATTEMPTS_PER_DAY",
        .protect_configurations_per_account = "PROTECT_CONFIGURATIONS_PER_ACCOUNT",
    };
};
