pub const VoiceId = enum {
    amy,
    astrid,
    bianca,
    brian,
    camila,
    carla,
    carmen,
    celine,
    chantal,
    conchita,
    cristiano,
    dora,
    emma,
    enrique,
    ewa,
    filiz,
    geraint,
    giorgio,
    gwyneth,
    hans,
    ines,
    ivy,
    jacek,
    jan,
    joanna,
    joey,
    justin,
    karl,
    kendra,
    kimberly,
    lea,
    liv,
    lotte,
    lucia,
    lupe,
    mads,
    maja,
    marlene,
    mathieu,
    matthew,
    maxim,
    mia,
    miguel,
    mizuki,
    naja,
    nicole,
    penelope,
    raveena,
    ricardo,
    ruben,
    russell,
    salli,
    seoyeon,
    takumi,
    tatyana,
    vicki,
    vitoria,
    zeina,
    zhiyu,

    pub const json_field_names = .{
        .amy = "AMY",
        .astrid = "ASTRID",
        .bianca = "BIANCA",
        .brian = "BRIAN",
        .camila = "CAMILA",
        .carla = "CARLA",
        .carmen = "CARMEN",
        .celine = "CELINE",
        .chantal = "CHANTAL",
        .conchita = "CONCHITA",
        .cristiano = "CRISTIANO",
        .dora = "DORA",
        .emma = "EMMA",
        .enrique = "ENRIQUE",
        .ewa = "EWA",
        .filiz = "FILIZ",
        .geraint = "GERAINT",
        .giorgio = "GIORGIO",
        .gwyneth = "GWYNETH",
        .hans = "HANS",
        .ines = "INES",
        .ivy = "IVY",
        .jacek = "JACEK",
        .jan = "JAN",
        .joanna = "JOANNA",
        .joey = "JOEY",
        .justin = "JUSTIN",
        .karl = "KARL",
        .kendra = "KENDRA",
        .kimberly = "KIMBERLY",
        .lea = "LEA",
        .liv = "LIV",
        .lotte = "LOTTE",
        .lucia = "LUCIA",
        .lupe = "LUPE",
        .mads = "MADS",
        .maja = "MAJA",
        .marlene = "MARLENE",
        .mathieu = "MATHIEU",
        .matthew = "MATTHEW",
        .maxim = "MAXIM",
        .mia = "MIA",
        .miguel = "MIGUEL",
        .mizuki = "MIZUKI",
        .naja = "NAJA",
        .nicole = "NICOLE",
        .penelope = "PENELOPE",
        .raveena = "RAVEENA",
        .ricardo = "RICARDO",
        .ruben = "RUBEN",
        .russell = "RUSSELL",
        .salli = "SALLI",
        .seoyeon = "SEOYEON",
        .takumi = "TAKUMI",
        .tatyana = "TATYANA",
        .vicki = "VICKI",
        .vitoria = "VITORIA",
        .zeina = "ZEINA",
        .zhiyu = "ZHIYU",
    };
};
