const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Destination = @import("destination.zig").Destination;
const IngestionStatus = @import("ingestion_status.zig").IngestionStatus;
const SourceConfig = @import("source_config.zig").SourceConfig;

pub const GetChannelInput = struct {
    /// The ARN or `UUID` of a channel.
    channel: []const u8,

    pub const json_field_names = .{
        .channel = "Channel",
    };
};

pub const GetChannelOutput = struct {
    /// The ARN of an channel returned by a `GetChannel` request.
    channel_arn: ?[]const u8 = null,

    /// The destinations for the channel. For channels created for integrations,
    /// the destinations are the event data stores that log events arriving through
    /// the channel.
    /// For service-linked channels, the destination is the Amazon Web Services
    /// service that created the service-linked channel to receive events.
    destinations: ?[]const Destination = null,

    /// A table showing information about the most recent successful and failed
    /// attempts
    /// to ingest events.
    ingestion_status: ?IngestionStatus = null,

    /// The name of the CloudTrail channel. For service-linked channels, the name is
    /// `aws-service-channel/service-name/custom-suffix` where
    /// `service-name` represents the name of the Amazon Web Services service that
    /// created the channel and `custom-suffix` represents the suffix generated by
    /// the
    /// Amazon Web Services service.
    name: ?[]const u8 = null,

    /// The source for the CloudTrail channel.
    source: ?[]const u8 = null,

    /// Provides information about the advanced event selectors configured for the
    /// channel, and
    /// whether the channel applies to all Regions or a single Region.
    source_config: ?SourceConfig = null,

    pub const json_field_names = .{
        .channel_arn = "ChannelArn",
        .destinations = "Destinations",
        .ingestion_status = "IngestionStatus",
        .name = "Name",
        .source = "Source",
        .source_config = "SourceConfig",
    };
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: GetChannelInput, options: CallOptions) !GetChannelOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "cloudtrail", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: GetChannelInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("cloudtrail", "CloudTrail", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    const body = try aws.json.jsonStringify(input, allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-amz-json-1.1");
    try request.headers.put(allocator, "X-Amz-Target", "CloudTrail_20131101.GetChannel");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !GetChannelOutput {
    _ = status;
    _ = headers;
    if (body.len == 0) return .{};
    return aws.json.parseJsonObject(GetChannelOutput, body, allocator);
}
