pub const FleetErrorCode = enum {
    iam_service_role_missing_eni_describe_action,
    iam_service_role_missing_eni_create_action,
    iam_service_role_missing_eni_delete_action,
    network_interface_limit_exceeded,
    internal_service_error,
    iam_service_role_is_missing,
    machine_role_is_missing,
    sts_disabled_in_region,
    subnet_has_insufficient_ip_addresses,
    iam_service_role_missing_describe_subnet_action,
    subnet_not_found,
    image_not_found,
    invalid_subnet_configuration,
    security_groups_not_found,
    igw_not_attached,
    iam_service_role_missing_describe_security_groups_action,
    fleet_stopped,
    fleet_instance_provisioning_failure,
    domain_join_error_file_not_found,
    domain_join_error_access_denied,
    domain_join_error_logon_failure,
    domain_join_error_invalid_parameter,
    domain_join_error_more_data,
    domain_join_error_no_such_domain,
    domain_join_error_not_supported,
    domain_join_nerr_invalid_workgroup_name,
    domain_join_nerr_workstation_not_started,
    domain_join_error_ds_machine_account_quota_exceeded,
    domain_join_nerr_password_expired,
    domain_join_internal_service_error,
    validation_error,

    pub const json_field_names = .{
        .iam_service_role_missing_eni_describe_action = "IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION",
        .iam_service_role_missing_eni_create_action = "IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION",
        .iam_service_role_missing_eni_delete_action = "IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION",
        .network_interface_limit_exceeded = "NETWORK_INTERFACE_LIMIT_EXCEEDED",
        .internal_service_error = "INTERNAL_SERVICE_ERROR",
        .iam_service_role_is_missing = "IAM_SERVICE_ROLE_IS_MISSING",
        .machine_role_is_missing = "MACHINE_ROLE_IS_MISSING",
        .sts_disabled_in_region = "STS_DISABLED_IN_REGION",
        .subnet_has_insufficient_ip_addresses = "SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES",
        .iam_service_role_missing_describe_subnet_action = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION",
        .subnet_not_found = "SUBNET_NOT_FOUND",
        .image_not_found = "IMAGE_NOT_FOUND",
        .invalid_subnet_configuration = "INVALID_SUBNET_CONFIGURATION",
        .security_groups_not_found = "SECURITY_GROUPS_NOT_FOUND",
        .igw_not_attached = "IGW_NOT_ATTACHED",
        .iam_service_role_missing_describe_security_groups_action = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION",
        .fleet_stopped = "FLEET_STOPPED",
        .fleet_instance_provisioning_failure = "FLEET_INSTANCE_PROVISIONING_FAILURE",
        .domain_join_error_file_not_found = "DOMAIN_JOIN_ERROR_FILE_NOT_FOUND",
        .domain_join_error_access_denied = "DOMAIN_JOIN_ERROR_ACCESS_DENIED",
        .domain_join_error_logon_failure = "DOMAIN_JOIN_ERROR_LOGON_FAILURE",
        .domain_join_error_invalid_parameter = "DOMAIN_JOIN_ERROR_INVALID_PARAMETER",
        .domain_join_error_more_data = "DOMAIN_JOIN_ERROR_MORE_DATA",
        .domain_join_error_no_such_domain = "DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN",
        .domain_join_error_not_supported = "DOMAIN_JOIN_ERROR_NOT_SUPPORTED",
        .domain_join_nerr_invalid_workgroup_name = "DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME",
        .domain_join_nerr_workstation_not_started = "DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED",
        .domain_join_error_ds_machine_account_quota_exceeded = "DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED",
        .domain_join_nerr_password_expired = "DOMAIN_JOIN_NERR_PASSWORD_EXPIRED",
        .domain_join_internal_service_error = "DOMAIN_JOIN_INTERNAL_SERVICE_ERROR",
        .validation_error = "VALIDATION_ERROR",
    };
};
