const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;

pub const ActivateEmailContactInput = struct {
    /// The Amazon Resource Name (ARN) of the resource.
    arn: []const u8,

    /// The activation code for this email contact.
    ///
    /// An email contact has a maximum of five activation attempts. Activation codes
    /// expire after 12 hours and are generated by the
    /// [SendActivationCode](https://docs.aws.amazon.com/notificationscontacts/latest/APIReference/API_SendActivationCode.html) API action.
    code: []const u8,

    pub const json_field_names = .{
        .arn = "arn",
        .code = "code",
    };
};

pub const ActivateEmailContactOutput = struct {};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: ActivateEmailContactInput, options: CallOptions) !ActivateEmailContactOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "notifications-contacts", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: ActivateEmailContactInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("notifications-contacts", "NotificationsContacts", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var path_buf: std.ArrayList(u8) = .empty;
    try path_buf.appendSlice(allocator, "/emailcontacts/");
    try path_buf.appendSlice(allocator, input.arn);
    try path_buf.appendSlice(allocator, "/activate/");
    try path_buf.appendSlice(allocator, input.code);
    const path = try path_buf.toOwnedSlice(allocator);

    const body: ?[]const u8 = null;

    var request = aws.http.Request.init(ep.host);
    request.method = .PUT;
    request.path = path;
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/json");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !ActivateEmailContactOutput {
    _ = allocator;
    _ = body;
    _ = status;
    _ = headers;
    const result: ActivateEmailContactOutput = .{};

    return result;
}
