const aws = @import("aws");
const std = @import("std");

const Client = @import("client.zig").Client;
const CallOptions = @import("call_options.zig").CallOptions;
const parseErrorResponse = @import("errors.zig").parseErrorResponse;
const Tag = @import("tag.zig").Tag;
const EventSubscription = @import("event_subscription.zig").EventSubscription;
const serde = @import("serde.zig");

pub const CreateEventSubscriptionInput = struct {
    /// Specifies whether to activate the subscription. If the event notification
    /// subscription isn't activated, the subscription is created but not active.
    enabled: ?bool = null,

    /// A list of event categories for a particular source type (`SourceType`) that
    /// you want to subscribe to. You can see a list of the categories for a given
    /// source type in the "Amazon RDS event categories and event messages" section
    /// of the [ *Amazon RDS User Guide*
    /// ](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.Messages.html) or the [ *Amazon Aurora User Guide* ](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_Events.Messages.html). You can also see this list by using the `DescribeEventCategories` operation.
    event_categories: ?[]const []const u8 = null,

    /// The Amazon Resource Name (ARN) of the SNS topic created for event
    /// notification. SNS automatically creates the ARN when you create a topic and
    /// subscribe to it.
    ///
    /// RDS doesn't support FIFO (first in, first out) topics. For more information,
    /// see [Message ordering and deduplication (FIFO
    /// topics)](https://docs.aws.amazon.com/sns/latest/dg/sns-fifo-topics.html) in
    /// the *Amazon Simple Notification Service Developer Guide*.
    sns_topic_arn: []const u8,

    /// The list of identifiers of the event sources for which events are returned.
    /// If not specified, then all sources are included in the response. An
    /// identifier must begin with a letter and must contain only ASCII letters,
    /// digits, and hyphens. It can't end with a hyphen or contain two consecutive
    /// hyphens.
    ///
    /// Constraints:
    ///
    /// * If `SourceIds` are supplied, `SourceType` must also be provided.
    /// * If the source type is a DB instance, a `DBInstanceIdentifier` value must
    ///   be supplied.
    /// * If the source type is a DB cluster, a `DBClusterIdentifier` value must be
    ///   supplied.
    /// * If the source type is a DB parameter group, a `DBParameterGroupName` value
    ///   must be supplied.
    /// * If the source type is a DB security group, a `DBSecurityGroupName` value
    ///   must be supplied.
    /// * If the source type is a DB snapshot, a `DBSnapshotIdentifier` value must
    ///   be supplied.
    /// * If the source type is a DB cluster snapshot, a
    ///   `DBClusterSnapshotIdentifier` value must be supplied.
    /// * If the source type is an RDS Proxy, a `DBProxyName` value must be
    ///   supplied.
    source_ids: ?[]const []const u8 = null,

    /// The type of source that is generating the events. For example, if you want
    /// to be notified of events generated by a DB instance, you set this parameter
    /// to `db-instance`. For RDS Proxy events, specify `db-proxy`. If this value
    /// isn't specified, all events are returned.
    ///
    /// Valid Values:` db-instance | db-cluster | db-parameter-group |
    /// db-security-group | db-snapshot | db-cluster-snapshot | db-proxy | zero-etl
    /// | custom-engine-version | blue-green-deployment `
    source_type: ?[]const u8 = null,

    /// The name of the subscription.
    ///
    /// Constraints: The name must be less than 255 characters.
    subscription_name: []const u8,

    tags: ?[]const Tag = null,
};

pub const CreateEventSubscriptionOutput = struct {
    event_subscription: ?EventSubscription = null,
};

pub fn execute(client: *Client, allocator: std.mem.Allocator, input: CreateEventSubscriptionInput, options: CallOptions) !CreateEventSubscriptionOutput {
    var arena = std.heap.ArenaAllocator.init(client.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var request = try serializeRequest(alloc, input, client.config);
    defer request.deinit(alloc);

    const creds = try client.config.credentials.getCredentials(client.allocator);
    try aws.signing.signRequest(alloc, client.config.io, &request, creds, client.config.region, "rds", client.config.http_client.clock_skew_offset);

    var response = try client.config.http_client.sendRequestWithOptions(&request, client.options);
    defer response.deinit();

    if (!response.isSuccess()) {
        if (options.diagnostic) |d| {
            d.* = try parseErrorResponse(client.allocator, response.body, response.status);
        }
        return error.ServiceError;
    }

    const result = try deserializeResponse(allocator, response.body, response.status, response.headers);
    return result;
}

fn serializeRequest(allocator: std.mem.Allocator, input: CreateEventSubscriptionInput, config: *aws.Config) !aws.http.Request {
    const endpoint = try config.getEndpointForService("rds", "RDS", allocator);

    const ep = try aws.url.parseEndpoint(endpoint);

    var body_buf: std.ArrayList(u8) = .empty;

    try body_buf.appendSlice(allocator, "Action=CreateEventSubscription&Version=2014-10-31");
    if (input.enabled) |v| {
        try body_buf.appendSlice(allocator, "&Enabled=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, if (v) "true" else "false");
    }
    if (input.event_categories) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            var prefix_buf: [256]u8 = undefined;
            const field_prefix = std.fmt.bufPrint(&prefix_buf, "&EventCategories.EventCategory.{d}=", .{n}) catch continue;
            try body_buf.appendSlice(allocator, field_prefix);
            try aws.url.appendUrlEncoded(allocator, &body_buf, item);
        }
    }
    try body_buf.appendSlice(allocator, "&SnsTopicArn=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.sns_topic_arn);
    if (input.source_ids) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            var prefix_buf: [256]u8 = undefined;
            const field_prefix = std.fmt.bufPrint(&prefix_buf, "&SourceIds.SourceId.{d}=", .{n}) catch continue;
            try body_buf.appendSlice(allocator, field_prefix);
            try aws.url.appendUrlEncoded(allocator, &body_buf, item);
        }
    }
    if (input.source_type) |v| {
        try body_buf.appendSlice(allocator, "&SourceType=");
        try aws.url.appendUrlEncoded(allocator, &body_buf, v);
    }
    try body_buf.appendSlice(allocator, "&SubscriptionName=");
    try aws.url.appendUrlEncoded(allocator, &body_buf, input.subscription_name);
    if (input.tags) |list| {
        for (list, 0..) |item, idx| {
            const n = idx + 1;
            {
                var prefix_buf: [256]u8 = undefined;
                if (item.key) |fv_1| {
                    const field_prefix = std.fmt.bufPrint(&prefix_buf, "&Tags.Tag.{d}.Key=", .{n}) catch continue;
                    try body_buf.appendSlice(allocator, field_prefix);
                    try aws.url.appendUrlEncoded(allocator, &body_buf, fv_1);
                }
            }
            {
                var prefix_buf: [256]u8 = undefined;
                if (item.value) |fv_1| {
                    const field_prefix = std.fmt.bufPrint(&prefix_buf, "&Tags.Tag.{d}.Value=", .{n}) catch continue;
                    try body_buf.appendSlice(allocator, field_prefix);
                    try aws.url.appendUrlEncoded(allocator, &body_buf, fv_1);
                }
            }
        }
    }

    const body = try body_buf.toOwnedSlice(allocator);

    var request = aws.http.Request.init(ep.host);
    request.method = .POST;
    request.path = "/";
    request.tls = ep.tls;
    request.port = ep.port;
    request.body = body;
    try request.headers.put(allocator, "Content-Type", "application/x-www-form-urlencoded");

    return request;
}

fn deserializeResponse(allocator: std.mem.Allocator, body: []const u8, status: u16, headers: anytype) !CreateEventSubscriptionOutput {
    _ = status;
    _ = headers;
    var reader = aws.xml.Reader.init(body);

    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "CreateEventSubscriptionResult")) break;
            },
            else => {},
        }
    }

    var result: CreateEventSubscriptionOutput = .{};
    while (try reader.next()) |event| {
        switch (event) {
            .element_start => |e| {
                if (std.mem.eql(u8, e.local, "EventSubscription")) {
                    result.event_subscription = try serde.deserializeEventSubscription(allocator, &reader);
                } else {
                    try reader.skipElement();
                }
            },
            .element_end => break,
            else => {},
        }
    }

    return result;
}
