/// A logical grouping of Performance Insights metrics for a related subject
/// area. For example, the `db.sql` dimension group consists of the following
/// dimensions:
///
/// * `db.sql.id` - The hash of a running SQL statement, generated by
///   Performance Insights.
/// * `db.sql.db_id` - Either the SQL ID generated by the database engine, or a
///   value generated by Performance Insights that begins with `pi-`.
/// * `db.sql.statement` - The full text of the SQL statement that is running,
///   for example, `SELECT * FROM employees`.
/// * `db.sql_tokenized.id` - The hash of the SQL digest generated by
///   Performance Insights.
///
/// Each response element returns a maximum of 500 bytes. For larger elements,
/// such as SQL statements, only the first 500 bytes are returned.
pub const PerformanceInsightsMetricDimensionGroup = struct {
    /// A list of specific dimensions from a dimension group. If this list isn't
    /// included, then all of the dimensions in the group were requested, or are
    /// present in the response.
    dimensions: ?[]const []const u8,

    /// The available dimension groups for Performance Insights metric type.
    group: ?[]const u8,

    /// The maximum number of items to fetch for this dimension group.
    limit: ?i32,
};
