pub const ValidationExceptionReason = enum {
    invalid_realm,
    invalid_directory_type,
    invalid_secondary_region,
    invalid_next_token,
    invalid_attribute_value,
    invalid_attribute_name,
    invalid_attribute_for_user,
    invalid_attribute_for_group,
    invalid_attribute_for_search,
    invalid_attribute_for_modify,
    duplicate_attribute,
    missing_attribute,
    attribute_exists,
    ldap_size_limit_exceeded,
    ldap_unsupported_operation,

    pub const json_field_names = .{
        .invalid_realm = "INVALID_REALM",
        .invalid_directory_type = "INVALID_DIRECTORY_TYPE",
        .invalid_secondary_region = "INVALID_SECONDARY_REGION",
        .invalid_next_token = "INVALID_NEXT_TOKEN",
        .invalid_attribute_value = "INVALID_ATTRIBUTE_VALUE",
        .invalid_attribute_name = "INVALID_ATTRIBUTE_NAME",
        .invalid_attribute_for_user = "INVALID_ATTRIBUTE_FOR_USER",
        .invalid_attribute_for_group = "INVALID_ATTRIBUTE_FOR_GROUP",
        .invalid_attribute_for_search = "INVALID_ATTRIBUTE_FOR_SEARCH",
        .invalid_attribute_for_modify = "INVALID_ATTRIBUTE_FOR_MODIFY",
        .duplicate_attribute = "DUPLICATE_ATTRIBUTE",
        .missing_attribute = "MISSING_ATTRIBUTE",
        .attribute_exists = "ATTRIBUTE_EXISTS",
        .ldap_size_limit_exceeded = "LDAP_SIZE_LIMIT_EXCEEDED",
        .ldap_unsupported_operation = "LDAP_UNSUPPORTED_OPERATION",
    };
};
