pub const ArtifactType = enum {
    unknown,
    screenshot,
    device_log,
    message_log,
    video_log,
    result_log,
    service_log,
    webkit_log,
    instrumentation_output,
    exerciser_monkey_output,
    calabash_json_output,
    calabash_pretty_output,
    calabash_standard_output,
    calabash_java_xml_output,
    automation_output,
    appium_server_output,
    appium_java_output,
    appium_java_xml_output,
    appium_python_output,
    appium_python_xml_output,
    explorer_event_log,
    explorer_summary_log,
    application_crash_report,
    xctest_log,
    video,
    customer_artifact,
    customer_artifact_log,
    testspec_output,

    pub const json_field_names = .{
        .unknown = "UNKNOWN",
        .screenshot = "SCREENSHOT",
        .device_log = "DEVICE_LOG",
        .message_log = "MESSAGE_LOG",
        .video_log = "VIDEO_LOG",
        .result_log = "RESULT_LOG",
        .service_log = "SERVICE_LOG",
        .webkit_log = "WEBKIT_LOG",
        .instrumentation_output = "INSTRUMENTATION_OUTPUT",
        .exerciser_monkey_output = "EXERCISER_MONKEY_OUTPUT",
        .calabash_json_output = "CALABASH_JSON_OUTPUT",
        .calabash_pretty_output = "CALABASH_PRETTY_OUTPUT",
        .calabash_standard_output = "CALABASH_STANDARD_OUTPUT",
        .calabash_java_xml_output = "CALABASH_JAVA_XML_OUTPUT",
        .automation_output = "AUTOMATION_OUTPUT",
        .appium_server_output = "APPIUM_SERVER_OUTPUT",
        .appium_java_output = "APPIUM_JAVA_OUTPUT",
        .appium_java_xml_output = "APPIUM_JAVA_XML_OUTPUT",
        .appium_python_output = "APPIUM_PYTHON_OUTPUT",
        .appium_python_xml_output = "APPIUM_PYTHON_XML_OUTPUT",
        .explorer_event_log = "EXPLORER_EVENT_LOG",
        .explorer_summary_log = "EXPLORER_SUMMARY_LOG",
        .application_crash_report = "APPLICATION_CRASH_REPORT",
        .xctest_log = "XCTEST_LOG",
        .video = "VIDEO",
        .customer_artifact = "CUSTOMER_ARTIFACT",
        .customer_artifact_log = "CUSTOMER_ARTIFACT_LOG",
        .testspec_output = "TESTSPEC_OUTPUT",
    };
};
