/// A JSON object that specifies the paths where the artifacts generated by the
/// customer's tests, on the
/// device or in the test environment, are pulled from.
///
/// Specify `deviceHostPaths` and optionally specify either
/// `iosPaths` or `androidPaths`.
///
/// For web app tests, you can specify both `iosPaths` and
/// `androidPaths`.
pub const CustomerArtifactPaths = struct {
    /// Comma-separated list of paths on the Android device where the artifacts
    /// generated by the customer's
    /// tests are pulled from.
    android_paths: ?[]const []const u8 = null,

    /// Comma-separated list of paths in the test execution environment where the
    /// artifacts generated by the
    /// customer's tests are pulled from.
    device_host_paths: ?[]const []const u8 = null,

    /// Comma-separated list of paths on the iOS device where the artifacts
    /// generated by the customer's tests
    /// are pulled from.
    ios_paths: ?[]const []const u8 = null,

    pub const json_field_names = .{
        .android_paths = "androidPaths",
        .device_host_paths = "deviceHostPaths",
        .ios_paths = "iosPaths",
    };
};
