const std = @import("std");

pub const AppInstanceType = enum {
    system,
    ml_t3_micro,
    ml_t3_small,
    ml_t3_medium,
    ml_t3_large,
    ml_t3_xlarge,
    ml_t3_2_xlarge,
    ml_m5_large,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_8_xlarge,
    ml_m5_12_xlarge,
    ml_m5_16_xlarge,
    ml_m5_24_xlarge,
    ml_m5_d_large,
    ml_m5_d_xlarge,
    ml_m5_d_2_xlarge,
    ml_m5_d_4_xlarge,
    ml_m5_d_8_xlarge,
    ml_m5_d_12_xlarge,
    ml_m5_d_16_xlarge,
    ml_m5_d_24_xlarge,
    ml_c5_large,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_12_xlarge,
    ml_c5_18_xlarge,
    ml_c5_24_xlarge,
    ml_p3_2_xlarge,
    ml_p3_8_xlarge,
    ml_p3_16_xlarge,
    ml_p3_dn_24_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_r5_large,
    ml_r5_xlarge,
    ml_r5_2_xlarge,
    ml_r5_4_xlarge,
    ml_r5_8_xlarge,
    ml_r5_12_xlarge,
    ml_r5_16_xlarge,
    ml_r5_24_xlarge,
    ml_g5_xlarge,
    ml_g5_2_xlarge,
    ml_g5_4_xlarge,
    ml_g5_8_xlarge,
    ml_g5_16_xlarge,
    ml_g5_12_xlarge,
    ml_g5_24_xlarge,
    ml_g5_48_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_12_xlarge,
    ml_g6_16_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,
    ml_g6_e_xlarge,
    ml_g6_e_2_xlarge,
    ml_g6_e_4_xlarge,
    ml_g6_e_8_xlarge,
    ml_g6_e_12_xlarge,
    ml_g6_e_16_xlarge,
    ml_g6_e_24_xlarge,
    ml_g6_e_48_xlarge,
    ml_geospatial_interactive,
    ml_p4_d_24_xlarge,
    ml_p4_de_24_xlarge,
    ml_trn1_2_xlarge,
    ml_trn1_32_xlarge,
    ml_trn1_n_32_xlarge,
    ml_p5_48_xlarge,
    ml_p5_en_48_xlarge,
    ml_p6_b200_48_xlarge,
    ml_m6_i_large,
    ml_m6_i_xlarge,
    ml_m6_i_2_xlarge,
    ml_m6_i_4_xlarge,
    ml_m6_i_8_xlarge,
    ml_m6_i_12_xlarge,
    ml_m6_i_16_xlarge,
    ml_m6_i_24_xlarge,
    ml_m6_i_32_xlarge,
    ml_m7_i_large,
    ml_m7_i_xlarge,
    ml_m7_i_2_xlarge,
    ml_m7_i_4_xlarge,
    ml_m7_i_8_xlarge,
    ml_m7_i_12_xlarge,
    ml_m7_i_16_xlarge,
    ml_m7_i_24_xlarge,
    ml_m7_i_48_xlarge,
    ml_c6_i_large,
    ml_c6_i_xlarge,
    ml_c6_i_2_xlarge,
    ml_c6_i_4_xlarge,
    ml_c6_i_8_xlarge,
    ml_c6_i_12_xlarge,
    ml_c6_i_16_xlarge,
    ml_c6_i_24_xlarge,
    ml_c6_i_32_xlarge,
    ml_c7_i_large,
    ml_c7_i_xlarge,
    ml_c7_i_2_xlarge,
    ml_c7_i_4_xlarge,
    ml_c7_i_8_xlarge,
    ml_c7_i_12_xlarge,
    ml_c7_i_16_xlarge,
    ml_c7_i_24_xlarge,
    ml_c7_i_48_xlarge,
    ml_r6_i_large,
    ml_r6_i_xlarge,
    ml_r6_i_2_xlarge,
    ml_r6_i_4_xlarge,
    ml_r6_i_8_xlarge,
    ml_r6_i_12_xlarge,
    ml_r6_i_16_xlarge,
    ml_r6_i_24_xlarge,
    ml_r6_i_32_xlarge,
    ml_r7_i_large,
    ml_r7_i_xlarge,
    ml_r7_i_2_xlarge,
    ml_r7_i_4_xlarge,
    ml_r7_i_8_xlarge,
    ml_r7_i_12_xlarge,
    ml_r7_i_16_xlarge,
    ml_r7_i_24_xlarge,
    ml_r7_i_48_xlarge,
    ml_m6_id_large,
    ml_m6_id_xlarge,
    ml_m6_id_2_xlarge,
    ml_m6_id_4_xlarge,
    ml_m6_id_8_xlarge,
    ml_m6_id_12_xlarge,
    ml_m6_id_16_xlarge,
    ml_m6_id_24_xlarge,
    ml_m6_id_32_xlarge,
    ml_c6_id_large,
    ml_c6_id_xlarge,
    ml_c6_id_2_xlarge,
    ml_c6_id_4_xlarge,
    ml_c6_id_8_xlarge,
    ml_c6_id_12_xlarge,
    ml_c6_id_16_xlarge,
    ml_c6_id_24_xlarge,
    ml_c6_id_32_xlarge,
    ml_r6_id_large,
    ml_r6_id_xlarge,
    ml_r6_id_2_xlarge,
    ml_r6_id_4_xlarge,
    ml_r6_id_8_xlarge,
    ml_r6_id_12_xlarge,
    ml_r6_id_16_xlarge,
    ml_r6_id_24_xlarge,
    ml_r6_id_32_xlarge,

    pub const json_field_names = .{
        .system = "system",
        .ml_t3_micro = "ml.t3.micro",
        .ml_t3_small = "ml.t3.small",
        .ml_t3_medium = "ml.t3.medium",
        .ml_t3_large = "ml.t3.large",
        .ml_t3_xlarge = "ml.t3.xlarge",
        .ml_t3_2_xlarge = "ml.t3.2xlarge",
        .ml_m5_large = "ml.m5.large",
        .ml_m5_xlarge = "ml.m5.xlarge",
        .ml_m5_2_xlarge = "ml.m5.2xlarge",
        .ml_m5_4_xlarge = "ml.m5.4xlarge",
        .ml_m5_8_xlarge = "ml.m5.8xlarge",
        .ml_m5_12_xlarge = "ml.m5.12xlarge",
        .ml_m5_16_xlarge = "ml.m5.16xlarge",
        .ml_m5_24_xlarge = "ml.m5.24xlarge",
        .ml_m5_d_large = "ml.m5d.large",
        .ml_m5_d_xlarge = "ml.m5d.xlarge",
        .ml_m5_d_2_xlarge = "ml.m5d.2xlarge",
        .ml_m5_d_4_xlarge = "ml.m5d.4xlarge",
        .ml_m5_d_8_xlarge = "ml.m5d.8xlarge",
        .ml_m5_d_12_xlarge = "ml.m5d.12xlarge",
        .ml_m5_d_16_xlarge = "ml.m5d.16xlarge",
        .ml_m5_d_24_xlarge = "ml.m5d.24xlarge",
        .ml_c5_large = "ml.c5.large",
        .ml_c5_xlarge = "ml.c5.xlarge",
        .ml_c5_2_xlarge = "ml.c5.2xlarge",
        .ml_c5_4_xlarge = "ml.c5.4xlarge",
        .ml_c5_9_xlarge = "ml.c5.9xlarge",
        .ml_c5_12_xlarge = "ml.c5.12xlarge",
        .ml_c5_18_xlarge = "ml.c5.18xlarge",
        .ml_c5_24_xlarge = "ml.c5.24xlarge",
        .ml_p3_2_xlarge = "ml.p3.2xlarge",
        .ml_p3_8_xlarge = "ml.p3.8xlarge",
        .ml_p3_16_xlarge = "ml.p3.16xlarge",
        .ml_p3_dn_24_xlarge = "ml.p3dn.24xlarge",
        .ml_g4_dn_xlarge = "ml.g4dn.xlarge",
        .ml_g4_dn_2_xlarge = "ml.g4dn.2xlarge",
        .ml_g4_dn_4_xlarge = "ml.g4dn.4xlarge",
        .ml_g4_dn_8_xlarge = "ml.g4dn.8xlarge",
        .ml_g4_dn_12_xlarge = "ml.g4dn.12xlarge",
        .ml_g4_dn_16_xlarge = "ml.g4dn.16xlarge",
        .ml_r5_large = "ml.r5.large",
        .ml_r5_xlarge = "ml.r5.xlarge",
        .ml_r5_2_xlarge = "ml.r5.2xlarge",
        .ml_r5_4_xlarge = "ml.r5.4xlarge",
        .ml_r5_8_xlarge = "ml.r5.8xlarge",
        .ml_r5_12_xlarge = "ml.r5.12xlarge",
        .ml_r5_16_xlarge = "ml.r5.16xlarge",
        .ml_r5_24_xlarge = "ml.r5.24xlarge",
        .ml_g5_xlarge = "ml.g5.xlarge",
        .ml_g5_2_xlarge = "ml.g5.2xlarge",
        .ml_g5_4_xlarge = "ml.g5.4xlarge",
        .ml_g5_8_xlarge = "ml.g5.8xlarge",
        .ml_g5_16_xlarge = "ml.g5.16xlarge",
        .ml_g5_12_xlarge = "ml.g5.12xlarge",
        .ml_g5_24_xlarge = "ml.g5.24xlarge",
        .ml_g5_48_xlarge = "ml.g5.48xlarge",
        .ml_g6_xlarge = "ml.g6.xlarge",
        .ml_g6_2_xlarge = "ml.g6.2xlarge",
        .ml_g6_4_xlarge = "ml.g6.4xlarge",
        .ml_g6_8_xlarge = "ml.g6.8xlarge",
        .ml_g6_12_xlarge = "ml.g6.12xlarge",
        .ml_g6_16_xlarge = "ml.g6.16xlarge",
        .ml_g6_24_xlarge = "ml.g6.24xlarge",
        .ml_g6_48_xlarge = "ml.g6.48xlarge",
        .ml_g6_e_xlarge = "ml.g6e.xlarge",
        .ml_g6_e_2_xlarge = "ml.g6e.2xlarge",
        .ml_g6_e_4_xlarge = "ml.g6e.4xlarge",
        .ml_g6_e_8_xlarge = "ml.g6e.8xlarge",
        .ml_g6_e_12_xlarge = "ml.g6e.12xlarge",
        .ml_g6_e_16_xlarge = "ml.g6e.16xlarge",
        .ml_g6_e_24_xlarge = "ml.g6e.24xlarge",
        .ml_g6_e_48_xlarge = "ml.g6e.48xlarge",
        .ml_geospatial_interactive = "ml.geospatial.interactive",
        .ml_p4_d_24_xlarge = "ml.p4d.24xlarge",
        .ml_p4_de_24_xlarge = "ml.p4de.24xlarge",
        .ml_trn1_2_xlarge = "ml.trn1.2xlarge",
        .ml_trn1_32_xlarge = "ml.trn1.32xlarge",
        .ml_trn1_n_32_xlarge = "ml.trn1n.32xlarge",
        .ml_p5_48_xlarge = "ml.p5.48xlarge",
        .ml_p5_en_48_xlarge = "ml.p5en.48xlarge",
        .ml_p6_b200_48_xlarge = "ml.p6-b200.48xlarge",
        .ml_m6_i_large = "ml.m6i.large",
        .ml_m6_i_xlarge = "ml.m6i.xlarge",
        .ml_m6_i_2_xlarge = "ml.m6i.2xlarge",
        .ml_m6_i_4_xlarge = "ml.m6i.4xlarge",
        .ml_m6_i_8_xlarge = "ml.m6i.8xlarge",
        .ml_m6_i_12_xlarge = "ml.m6i.12xlarge",
        .ml_m6_i_16_xlarge = "ml.m6i.16xlarge",
        .ml_m6_i_24_xlarge = "ml.m6i.24xlarge",
        .ml_m6_i_32_xlarge = "ml.m6i.32xlarge",
        .ml_m7_i_large = "ml.m7i.large",
        .ml_m7_i_xlarge = "ml.m7i.xlarge",
        .ml_m7_i_2_xlarge = "ml.m7i.2xlarge",
        .ml_m7_i_4_xlarge = "ml.m7i.4xlarge",
        .ml_m7_i_8_xlarge = "ml.m7i.8xlarge",
        .ml_m7_i_12_xlarge = "ml.m7i.12xlarge",
        .ml_m7_i_16_xlarge = "ml.m7i.16xlarge",
        .ml_m7_i_24_xlarge = "ml.m7i.24xlarge",
        .ml_m7_i_48_xlarge = "ml.m7i.48xlarge",
        .ml_c6_i_large = "ml.c6i.large",
        .ml_c6_i_xlarge = "ml.c6i.xlarge",
        .ml_c6_i_2_xlarge = "ml.c6i.2xlarge",
        .ml_c6_i_4_xlarge = "ml.c6i.4xlarge",
        .ml_c6_i_8_xlarge = "ml.c6i.8xlarge",
        .ml_c6_i_12_xlarge = "ml.c6i.12xlarge",
        .ml_c6_i_16_xlarge = "ml.c6i.16xlarge",
        .ml_c6_i_24_xlarge = "ml.c6i.24xlarge",
        .ml_c6_i_32_xlarge = "ml.c6i.32xlarge",
        .ml_c7_i_large = "ml.c7i.large",
        .ml_c7_i_xlarge = "ml.c7i.xlarge",
        .ml_c7_i_2_xlarge = "ml.c7i.2xlarge",
        .ml_c7_i_4_xlarge = "ml.c7i.4xlarge",
        .ml_c7_i_8_xlarge = "ml.c7i.8xlarge",
        .ml_c7_i_12_xlarge = "ml.c7i.12xlarge",
        .ml_c7_i_16_xlarge = "ml.c7i.16xlarge",
        .ml_c7_i_24_xlarge = "ml.c7i.24xlarge",
        .ml_c7_i_48_xlarge = "ml.c7i.48xlarge",
        .ml_r6_i_large = "ml.r6i.large",
        .ml_r6_i_xlarge = "ml.r6i.xlarge",
        .ml_r6_i_2_xlarge = "ml.r6i.2xlarge",
        .ml_r6_i_4_xlarge = "ml.r6i.4xlarge",
        .ml_r6_i_8_xlarge = "ml.r6i.8xlarge",
        .ml_r6_i_12_xlarge = "ml.r6i.12xlarge",
        .ml_r6_i_16_xlarge = "ml.r6i.16xlarge",
        .ml_r6_i_24_xlarge = "ml.r6i.24xlarge",
        .ml_r6_i_32_xlarge = "ml.r6i.32xlarge",
        .ml_r7_i_large = "ml.r7i.large",
        .ml_r7_i_xlarge = "ml.r7i.xlarge",
        .ml_r7_i_2_xlarge = "ml.r7i.2xlarge",
        .ml_r7_i_4_xlarge = "ml.r7i.4xlarge",
        .ml_r7_i_8_xlarge = "ml.r7i.8xlarge",
        .ml_r7_i_12_xlarge = "ml.r7i.12xlarge",
        .ml_r7_i_16_xlarge = "ml.r7i.16xlarge",
        .ml_r7_i_24_xlarge = "ml.r7i.24xlarge",
        .ml_r7_i_48_xlarge = "ml.r7i.48xlarge",
        .ml_m6_id_large = "ml.m6id.large",
        .ml_m6_id_xlarge = "ml.m6id.xlarge",
        .ml_m6_id_2_xlarge = "ml.m6id.2xlarge",
        .ml_m6_id_4_xlarge = "ml.m6id.4xlarge",
        .ml_m6_id_8_xlarge = "ml.m6id.8xlarge",
        .ml_m6_id_12_xlarge = "ml.m6id.12xlarge",
        .ml_m6_id_16_xlarge = "ml.m6id.16xlarge",
        .ml_m6_id_24_xlarge = "ml.m6id.24xlarge",
        .ml_m6_id_32_xlarge = "ml.m6id.32xlarge",
        .ml_c6_id_large = "ml.c6id.large",
        .ml_c6_id_xlarge = "ml.c6id.xlarge",
        .ml_c6_id_2_xlarge = "ml.c6id.2xlarge",
        .ml_c6_id_4_xlarge = "ml.c6id.4xlarge",
        .ml_c6_id_8_xlarge = "ml.c6id.8xlarge",
        .ml_c6_id_12_xlarge = "ml.c6id.12xlarge",
        .ml_c6_id_16_xlarge = "ml.c6id.16xlarge",
        .ml_c6_id_24_xlarge = "ml.c6id.24xlarge",
        .ml_c6_id_32_xlarge = "ml.c6id.32xlarge",
        .ml_r6_id_large = "ml.r6id.large",
        .ml_r6_id_xlarge = "ml.r6id.xlarge",
        .ml_r6_id_2_xlarge = "ml.r6id.2xlarge",
        .ml_r6_id_4_xlarge = "ml.r6id.4xlarge",
        .ml_r6_id_8_xlarge = "ml.r6id.8xlarge",
        .ml_r6_id_12_xlarge = "ml.r6id.12xlarge",
        .ml_r6_id_16_xlarge = "ml.r6id.16xlarge",
        .ml_r6_id_24_xlarge = "ml.r6id.24xlarge",
        .ml_r6_id_32_xlarge = "ml.r6id.32xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .system => "system",
            .ml_t3_micro => "ml.t3.micro",
            .ml_t3_small => "ml.t3.small",
            .ml_t3_medium => "ml.t3.medium",
            .ml_t3_large => "ml.t3.large",
            .ml_t3_xlarge => "ml.t3.xlarge",
            .ml_t3_2_xlarge => "ml.t3.2xlarge",
            .ml_m5_large => "ml.m5.large",
            .ml_m5_xlarge => "ml.m5.xlarge",
            .ml_m5_2_xlarge => "ml.m5.2xlarge",
            .ml_m5_4_xlarge => "ml.m5.4xlarge",
            .ml_m5_8_xlarge => "ml.m5.8xlarge",
            .ml_m5_12_xlarge => "ml.m5.12xlarge",
            .ml_m5_16_xlarge => "ml.m5.16xlarge",
            .ml_m5_24_xlarge => "ml.m5.24xlarge",
            .ml_m5_d_large => "ml.m5d.large",
            .ml_m5_d_xlarge => "ml.m5d.xlarge",
            .ml_m5_d_2_xlarge => "ml.m5d.2xlarge",
            .ml_m5_d_4_xlarge => "ml.m5d.4xlarge",
            .ml_m5_d_8_xlarge => "ml.m5d.8xlarge",
            .ml_m5_d_12_xlarge => "ml.m5d.12xlarge",
            .ml_m5_d_16_xlarge => "ml.m5d.16xlarge",
            .ml_m5_d_24_xlarge => "ml.m5d.24xlarge",
            .ml_c5_large => "ml.c5.large",
            .ml_c5_xlarge => "ml.c5.xlarge",
            .ml_c5_2_xlarge => "ml.c5.2xlarge",
            .ml_c5_4_xlarge => "ml.c5.4xlarge",
            .ml_c5_9_xlarge => "ml.c5.9xlarge",
            .ml_c5_12_xlarge => "ml.c5.12xlarge",
            .ml_c5_18_xlarge => "ml.c5.18xlarge",
            .ml_c5_24_xlarge => "ml.c5.24xlarge",
            .ml_p3_2_xlarge => "ml.p3.2xlarge",
            .ml_p3_8_xlarge => "ml.p3.8xlarge",
            .ml_p3_16_xlarge => "ml.p3.16xlarge",
            .ml_p3_dn_24_xlarge => "ml.p3dn.24xlarge",
            .ml_g4_dn_xlarge => "ml.g4dn.xlarge",
            .ml_g4_dn_2_xlarge => "ml.g4dn.2xlarge",
            .ml_g4_dn_4_xlarge => "ml.g4dn.4xlarge",
            .ml_g4_dn_8_xlarge => "ml.g4dn.8xlarge",
            .ml_g4_dn_12_xlarge => "ml.g4dn.12xlarge",
            .ml_g4_dn_16_xlarge => "ml.g4dn.16xlarge",
            .ml_r5_large => "ml.r5.large",
            .ml_r5_xlarge => "ml.r5.xlarge",
            .ml_r5_2_xlarge => "ml.r5.2xlarge",
            .ml_r5_4_xlarge => "ml.r5.4xlarge",
            .ml_r5_8_xlarge => "ml.r5.8xlarge",
            .ml_r5_12_xlarge => "ml.r5.12xlarge",
            .ml_r5_16_xlarge => "ml.r5.16xlarge",
            .ml_r5_24_xlarge => "ml.r5.24xlarge",
            .ml_g5_xlarge => "ml.g5.xlarge",
            .ml_g5_2_xlarge => "ml.g5.2xlarge",
            .ml_g5_4_xlarge => "ml.g5.4xlarge",
            .ml_g5_8_xlarge => "ml.g5.8xlarge",
            .ml_g5_16_xlarge => "ml.g5.16xlarge",
            .ml_g5_12_xlarge => "ml.g5.12xlarge",
            .ml_g5_24_xlarge => "ml.g5.24xlarge",
            .ml_g5_48_xlarge => "ml.g5.48xlarge",
            .ml_g6_xlarge => "ml.g6.xlarge",
            .ml_g6_2_xlarge => "ml.g6.2xlarge",
            .ml_g6_4_xlarge => "ml.g6.4xlarge",
            .ml_g6_8_xlarge => "ml.g6.8xlarge",
            .ml_g6_12_xlarge => "ml.g6.12xlarge",
            .ml_g6_16_xlarge => "ml.g6.16xlarge",
            .ml_g6_24_xlarge => "ml.g6.24xlarge",
            .ml_g6_48_xlarge => "ml.g6.48xlarge",
            .ml_g6_e_xlarge => "ml.g6e.xlarge",
            .ml_g6_e_2_xlarge => "ml.g6e.2xlarge",
            .ml_g6_e_4_xlarge => "ml.g6e.4xlarge",
            .ml_g6_e_8_xlarge => "ml.g6e.8xlarge",
            .ml_g6_e_12_xlarge => "ml.g6e.12xlarge",
            .ml_g6_e_16_xlarge => "ml.g6e.16xlarge",
            .ml_g6_e_24_xlarge => "ml.g6e.24xlarge",
            .ml_g6_e_48_xlarge => "ml.g6e.48xlarge",
            .ml_geospatial_interactive => "ml.geospatial.interactive",
            .ml_p4_d_24_xlarge => "ml.p4d.24xlarge",
            .ml_p4_de_24_xlarge => "ml.p4de.24xlarge",
            .ml_trn1_2_xlarge => "ml.trn1.2xlarge",
            .ml_trn1_32_xlarge => "ml.trn1.32xlarge",
            .ml_trn1_n_32_xlarge => "ml.trn1n.32xlarge",
            .ml_p5_48_xlarge => "ml.p5.48xlarge",
            .ml_p5_en_48_xlarge => "ml.p5en.48xlarge",
            .ml_p6_b200_48_xlarge => "ml.p6-b200.48xlarge",
            .ml_m6_i_large => "ml.m6i.large",
            .ml_m6_i_xlarge => "ml.m6i.xlarge",
            .ml_m6_i_2_xlarge => "ml.m6i.2xlarge",
            .ml_m6_i_4_xlarge => "ml.m6i.4xlarge",
            .ml_m6_i_8_xlarge => "ml.m6i.8xlarge",
            .ml_m6_i_12_xlarge => "ml.m6i.12xlarge",
            .ml_m6_i_16_xlarge => "ml.m6i.16xlarge",
            .ml_m6_i_24_xlarge => "ml.m6i.24xlarge",
            .ml_m6_i_32_xlarge => "ml.m6i.32xlarge",
            .ml_m7_i_large => "ml.m7i.large",
            .ml_m7_i_xlarge => "ml.m7i.xlarge",
            .ml_m7_i_2_xlarge => "ml.m7i.2xlarge",
            .ml_m7_i_4_xlarge => "ml.m7i.4xlarge",
            .ml_m7_i_8_xlarge => "ml.m7i.8xlarge",
            .ml_m7_i_12_xlarge => "ml.m7i.12xlarge",
            .ml_m7_i_16_xlarge => "ml.m7i.16xlarge",
            .ml_m7_i_24_xlarge => "ml.m7i.24xlarge",
            .ml_m7_i_48_xlarge => "ml.m7i.48xlarge",
            .ml_c6_i_large => "ml.c6i.large",
            .ml_c6_i_xlarge => "ml.c6i.xlarge",
            .ml_c6_i_2_xlarge => "ml.c6i.2xlarge",
            .ml_c6_i_4_xlarge => "ml.c6i.4xlarge",
            .ml_c6_i_8_xlarge => "ml.c6i.8xlarge",
            .ml_c6_i_12_xlarge => "ml.c6i.12xlarge",
            .ml_c6_i_16_xlarge => "ml.c6i.16xlarge",
            .ml_c6_i_24_xlarge => "ml.c6i.24xlarge",
            .ml_c6_i_32_xlarge => "ml.c6i.32xlarge",
            .ml_c7_i_large => "ml.c7i.large",
            .ml_c7_i_xlarge => "ml.c7i.xlarge",
            .ml_c7_i_2_xlarge => "ml.c7i.2xlarge",
            .ml_c7_i_4_xlarge => "ml.c7i.4xlarge",
            .ml_c7_i_8_xlarge => "ml.c7i.8xlarge",
            .ml_c7_i_12_xlarge => "ml.c7i.12xlarge",
            .ml_c7_i_16_xlarge => "ml.c7i.16xlarge",
            .ml_c7_i_24_xlarge => "ml.c7i.24xlarge",
            .ml_c7_i_48_xlarge => "ml.c7i.48xlarge",
            .ml_r6_i_large => "ml.r6i.large",
            .ml_r6_i_xlarge => "ml.r6i.xlarge",
            .ml_r6_i_2_xlarge => "ml.r6i.2xlarge",
            .ml_r6_i_4_xlarge => "ml.r6i.4xlarge",
            .ml_r6_i_8_xlarge => "ml.r6i.8xlarge",
            .ml_r6_i_12_xlarge => "ml.r6i.12xlarge",
            .ml_r6_i_16_xlarge => "ml.r6i.16xlarge",
            .ml_r6_i_24_xlarge => "ml.r6i.24xlarge",
            .ml_r6_i_32_xlarge => "ml.r6i.32xlarge",
            .ml_r7_i_large => "ml.r7i.large",
            .ml_r7_i_xlarge => "ml.r7i.xlarge",
            .ml_r7_i_2_xlarge => "ml.r7i.2xlarge",
            .ml_r7_i_4_xlarge => "ml.r7i.4xlarge",
            .ml_r7_i_8_xlarge => "ml.r7i.8xlarge",
            .ml_r7_i_12_xlarge => "ml.r7i.12xlarge",
            .ml_r7_i_16_xlarge => "ml.r7i.16xlarge",
            .ml_r7_i_24_xlarge => "ml.r7i.24xlarge",
            .ml_r7_i_48_xlarge => "ml.r7i.48xlarge",
            .ml_m6_id_large => "ml.m6id.large",
            .ml_m6_id_xlarge => "ml.m6id.xlarge",
            .ml_m6_id_2_xlarge => "ml.m6id.2xlarge",
            .ml_m6_id_4_xlarge => "ml.m6id.4xlarge",
            .ml_m6_id_8_xlarge => "ml.m6id.8xlarge",
            .ml_m6_id_12_xlarge => "ml.m6id.12xlarge",
            .ml_m6_id_16_xlarge => "ml.m6id.16xlarge",
            .ml_m6_id_24_xlarge => "ml.m6id.24xlarge",
            .ml_m6_id_32_xlarge => "ml.m6id.32xlarge",
            .ml_c6_id_large => "ml.c6id.large",
            .ml_c6_id_xlarge => "ml.c6id.xlarge",
            .ml_c6_id_2_xlarge => "ml.c6id.2xlarge",
            .ml_c6_id_4_xlarge => "ml.c6id.4xlarge",
            .ml_c6_id_8_xlarge => "ml.c6id.8xlarge",
            .ml_c6_id_12_xlarge => "ml.c6id.12xlarge",
            .ml_c6_id_16_xlarge => "ml.c6id.16xlarge",
            .ml_c6_id_24_xlarge => "ml.c6id.24xlarge",
            .ml_c6_id_32_xlarge => "ml.c6id.32xlarge",
            .ml_r6_id_large => "ml.r6id.large",
            .ml_r6_id_xlarge => "ml.r6id.xlarge",
            .ml_r6_id_2_xlarge => "ml.r6id.2xlarge",
            .ml_r6_id_4_xlarge => "ml.r6id.4xlarge",
            .ml_r6_id_8_xlarge => "ml.r6id.8xlarge",
            .ml_r6_id_12_xlarge => "ml.r6id.12xlarge",
            .ml_r6_id_16_xlarge => "ml.r6id.16xlarge",
            .ml_r6_id_24_xlarge => "ml.r6id.24xlarge",
            .ml_r6_id_32_xlarge => "ml.r6id.32xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
