pub const AutoMLMetricEnum = enum {
    accuracy,
    mse,
    f1,
    f1_macro,
    auc,
    rmse,
    balanced_accuracy,
    r2,
    recall,
    recall_macro,
    precision,
    precision_macro,
    mae,
    mape,
    mase,
    wape,
    average_weighted_quantile_loss,

    pub const json_field_names = .{
        .accuracy = "ACCURACY",
        .mse = "MSE",
        .f1 = "F1",
        .f1_macro = "F1_MACRO",
        .auc = "AUC",
        .rmse = "RMSE",
        .balanced_accuracy = "BALANCED_ACCURACY",
        .r2 = "R2",
        .recall = "RECALL",
        .recall_macro = "RECALL_MACRO",
        .precision = "PRECISION",
        .precision_macro = "PRECISION_MACRO",
        .mae = "MAE",
        .mape = "MAPE",
        .mase = "MASE",
        .wape = "WAPE",
        .average_weighted_quantile_loss = "AVERAGE_WEIGHTED_QUANTILE_LOSS",
    };
};
