pub const AutoMLJobSecondaryStatus = enum {
    starting,
    max_candidates_reached,
    failed,
    stopped,
    max_auto_ml_job_runtime_reached,
    stopping,
    candidate_definitions_generated,
    completed,
    explainability_error,
    deploying_model,
    model_deployment_error,
    generating_model_insights_report,
    model_insights_error,
    analyzing_data,
    feature_engineering,
    model_tuning,
    generating_explainability_report,
    training_models,
    pre_training,

    pub const json_field_names = .{
        .starting = "STARTING",
        .max_candidates_reached = "MAX_CANDIDATES_REACHED",
        .failed = "FAILED",
        .stopped = "STOPPED",
        .max_auto_ml_job_runtime_reached = "MAX_AUTO_ML_JOB_RUNTIME_REACHED",
        .stopping = "STOPPING",
        .candidate_definitions_generated = "CANDIDATE_DEFINITIONS_GENERATED",
        .completed = "COMPLETED",
        .explainability_error = "EXPLAINABILITY_ERROR",
        .deploying_model = "DEPLOYING_MODEL",
        .model_deployment_error = "MODEL_DEPLOYMENT_ERROR",
        .generating_model_insights_report = "GENERATING_MODEL_INSIGHTS_REPORT",
        .model_insights_error = "MODEL_INSIGHTS_ERROR",
        .analyzing_data = "ANALYZING_DATA",
        .feature_engineering = "FEATURE_ENGINEERING",
        .model_tuning = "MODEL_TUNING",
        .generating_explainability_report = "GENERATING_EXPLAINABILITY_REPORT",
        .training_models = "TRAINING_MODELS",
        .pre_training = "PRE_TRAINING",
    };
};
