pub const AutoMLAlgorithm = enum {
    xgboost,
    linear_learner,
    mlp,
    lightgbm,
    catboost,
    randomforest,
    extra_trees,
    nn_torch,
    fastai,
    cnn_qr,
    deepar,
    prophet,
    npts,
    arima,
    ets,

    pub const json_field_names = .{
        .xgboost = "XGBOOST",
        .linear_learner = "LINEAR_LEARNER",
        .mlp = "MLP",
        .lightgbm = "LIGHTGBM",
        .catboost = "CATBOOST",
        .randomforest = "RANDOMFOREST",
        .extra_trees = "EXTRA_TREES",
        .nn_torch = "NN_TORCH",
        .fastai = "FASTAI",
        .cnn_qr = "CNN_QR",
        .deepar = "DEEPAR",
        .prophet = "PROPHET",
        .npts = "NPTS",
        .arima = "ARIMA",
        .ets = "ETS",
    };
};
