pub const AutoMLMetricExtendedEnum = enum {
    accuracy,
    mse,
    f1,
    f1_macro,
    auc,
    rmse,
    mae,
    r2,
    balanced_accuracy,
    precision,
    precision_macro,
    recall,
    recall_macro,
    log_loss,
    inference_latency,
    mape,
    mase,
    wape,
    average_weighted_quantile_loss,
    rouge1,
    rouge2,
    rougel,
    rougel_sum,
    perplexity,
    validation_loss,
    training_loss,

    pub const json_field_names = .{
        .accuracy = "ACCURACY",
        .mse = "MSE",
        .f1 = "F1",
        .f1_macro = "F1_MACRO",
        .auc = "AUC",
        .rmse = "RMSE",
        .mae = "MAE",
        .r2 = "R2",
        .balanced_accuracy = "BALANCED_ACCURACY",
        .precision = "PRECISION",
        .precision_macro = "PRECISION_MACRO",
        .recall = "RECALL",
        .recall_macro = "RECALL_MACRO",
        .log_loss = "LogLoss",
        .inference_latency = "INFERENCE_LATENCY",
        .mape = "MAPE",
        .mase = "MASE",
        .wape = "WAPE",
        .average_weighted_quantile_loss = "AVERAGE_WEIGHTED_QUANTILE_LOSS",
        .rouge1 = "ROUGE1",
        .rouge2 = "ROUGE2",
        .rougel = "ROUGEL",
        .rougel_sum = "ROUGEL_SUM",
        .perplexity = "PERPLEXITY",
        .validation_loss = "VALIDATION_LOSS",
        .training_loss = "TRAINING_LOSS",
    };
};
