pub const ClarifyTextLanguage = enum {
    afrikaans,
    albanian,
    arabic,
    armenian,
    basque,
    bengali,
    bulgarian,
    catalan,
    chinese,
    croatian,
    czech,
    danish,
    dutch,
    english,
    estonian,
    finnish,
    french,
    german,
    greek,
    gujarati,
    hebrew,
    hindi,
    hungarian,
    icelandic,
    indonesian,
    irish,
    italian,
    kannada,
    kyrgyz,
    latvian,
    lithuanian,
    luxembourgish,
    macedonian,
    malayalam,
    marathi,
    nepali,
    norwegian_bokmal,
    persian,
    polish,
    portuguese,
    romanian,
    russian,
    sanskrit,
    serbian,
    setswana,
    sinhala,
    slovak,
    slovenian,
    spanish,
    swedish,
    tagalog,
    tamil,
    tatar,
    telugu,
    turkish,
    ukrainian,
    urdu,
    yoruba,
    ligurian,
    multi_language,

    pub const json_field_names = .{
        .afrikaans = "AFRIKAANS",
        .albanian = "ALBANIAN",
        .arabic = "ARABIC",
        .armenian = "ARMENIAN",
        .basque = "BASQUE",
        .bengali = "BENGALI",
        .bulgarian = "BULGARIAN",
        .catalan = "CATALAN",
        .chinese = "CHINESE",
        .croatian = "CROATIAN",
        .czech = "CZECH",
        .danish = "DANISH",
        .dutch = "DUTCH",
        .english = "ENGLISH",
        .estonian = "ESTONIAN",
        .finnish = "FINNISH",
        .french = "FRENCH",
        .german = "GERMAN",
        .greek = "GREEK",
        .gujarati = "GUJARATI",
        .hebrew = "HEBREW",
        .hindi = "HINDI",
        .hungarian = "HUNGARIAN",
        .icelandic = "ICELANDIC",
        .indonesian = "INDONESIAN",
        .irish = "IRISH",
        .italian = "ITALIAN",
        .kannada = "KANNADA",
        .kyrgyz = "KYRGYZ",
        .latvian = "LATVIAN",
        .lithuanian = "LITHUANIAN",
        .luxembourgish = "LUXEMBOURGISH",
        .macedonian = "MACEDONIAN",
        .malayalam = "MALAYALAM",
        .marathi = "MARATHI",
        .nepali = "NEPALI",
        .norwegian_bokmal = "NORWEGIAN_BOKMAL",
        .persian = "PERSIAN",
        .polish = "POLISH",
        .portuguese = "PORTUGUESE",
        .romanian = "ROMANIAN",
        .russian = "RUSSIAN",
        .sanskrit = "SANSKRIT",
        .serbian = "SERBIAN",
        .setswana = "SETSWANA",
        .sinhala = "SINHALA",
        .slovak = "SLOVAK",
        .slovenian = "SLOVENIAN",
        .spanish = "SPANISH",
        .swedish = "SWEDISH",
        .tagalog = "TAGALOG",
        .tamil = "TAMIL",
        .tatar = "TATAR",
        .telugu = "TELUGU",
        .turkish = "TURKISH",
        .ukrainian = "UKRAINIAN",
        .urdu = "URDU",
        .yoruba = "YORUBA",
        .ligurian = "LIGURIAN",
        .multi_language = "MULTI_LANGUAGE",
    };
};
