const std = @import("std");

pub const ClarifyTextLanguage = enum {
    afrikaans,
    albanian,
    arabic,
    armenian,
    basque,
    bengali,
    bulgarian,
    catalan,
    chinese,
    croatian,
    czech,
    danish,
    dutch,
    english,
    estonian,
    finnish,
    french,
    german,
    greek,
    gujarati,
    hebrew,
    hindi,
    hungarian,
    icelandic,
    indonesian,
    irish,
    italian,
    kannada,
    kyrgyz,
    latvian,
    lithuanian,
    luxembourgish,
    macedonian,
    malayalam,
    marathi,
    nepali,
    norwegian_bokmal,
    persian,
    polish,
    portuguese,
    romanian,
    russian,
    sanskrit,
    serbian,
    setswana,
    sinhala,
    slovak,
    slovenian,
    spanish,
    swedish,
    tagalog,
    tamil,
    tatar,
    telugu,
    turkish,
    ukrainian,
    urdu,
    yoruba,
    ligurian,
    multi_language,

    pub const json_field_names = .{
        .afrikaans = "af",
        .albanian = "sq",
        .arabic = "ar",
        .armenian = "hy",
        .basque = "eu",
        .bengali = "bn",
        .bulgarian = "bg",
        .catalan = "ca",
        .chinese = "zh",
        .croatian = "hr",
        .czech = "cs",
        .danish = "da",
        .dutch = "nl",
        .english = "en",
        .estonian = "et",
        .finnish = "fi",
        .french = "fr",
        .german = "de",
        .greek = "el",
        .gujarati = "gu",
        .hebrew = "he",
        .hindi = "hi",
        .hungarian = "hu",
        .icelandic = "is",
        .indonesian = "id",
        .irish = "ga",
        .italian = "it",
        .kannada = "kn",
        .kyrgyz = "ky",
        .latvian = "lv",
        .lithuanian = "lt",
        .luxembourgish = "lb",
        .macedonian = "mk",
        .malayalam = "ml",
        .marathi = "mr",
        .nepali = "ne",
        .norwegian_bokmal = "nb",
        .persian = "fa",
        .polish = "pl",
        .portuguese = "pt",
        .romanian = "ro",
        .russian = "ru",
        .sanskrit = "sa",
        .serbian = "sr",
        .setswana = "tn",
        .sinhala = "si",
        .slovak = "sk",
        .slovenian = "sl",
        .spanish = "es",
        .swedish = "sv",
        .tagalog = "tl",
        .tamil = "ta",
        .tatar = "tt",
        .telugu = "te",
        .turkish = "tr",
        .ukrainian = "uk",
        .urdu = "ur",
        .yoruba = "yo",
        .ligurian = "lij",
        .multi_language = "xx",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .afrikaans => "af",
            .albanian => "sq",
            .arabic => "ar",
            .armenian => "hy",
            .basque => "eu",
            .bengali => "bn",
            .bulgarian => "bg",
            .catalan => "ca",
            .chinese => "zh",
            .croatian => "hr",
            .czech => "cs",
            .danish => "da",
            .dutch => "nl",
            .english => "en",
            .estonian => "et",
            .finnish => "fi",
            .french => "fr",
            .german => "de",
            .greek => "el",
            .gujarati => "gu",
            .hebrew => "he",
            .hindi => "hi",
            .hungarian => "hu",
            .icelandic => "is",
            .indonesian => "id",
            .irish => "ga",
            .italian => "it",
            .kannada => "kn",
            .kyrgyz => "ky",
            .latvian => "lv",
            .lithuanian => "lt",
            .luxembourgish => "lb",
            .macedonian => "mk",
            .malayalam => "ml",
            .marathi => "mr",
            .nepali => "ne",
            .norwegian_bokmal => "nb",
            .persian => "fa",
            .polish => "pl",
            .portuguese => "pt",
            .romanian => "ro",
            .russian => "ru",
            .sanskrit => "sa",
            .serbian => "sr",
            .setswana => "tn",
            .sinhala => "si",
            .slovak => "sk",
            .slovenian => "sl",
            .spanish => "es",
            .swedish => "sv",
            .tagalog => "tl",
            .tamil => "ta",
            .tatar => "tt",
            .telugu => "te",
            .turkish => "tr",
            .ukrainian => "uk",
            .urdu => "ur",
            .yoruba => "yo",
            .ligurian => "lij",
            .multi_language => "xx",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
