const std = @import("std");

pub const ClusterInstanceType = enum {
    ml_p4_d_24_xlarge,
    ml_p4_de_24_xlarge,
    ml_p5_48_xlarge,
    ml_p5_4_xlarge,
    ml_p6_e_gb200_36_xlarge,
    ml_trn1_32_xlarge,
    ml_trn1_n_32_xlarge,
    ml_g5_xlarge,
    ml_g5_2_xlarge,
    ml_g5_4_xlarge,
    ml_g5_8_xlarge,
    ml_g5_12_xlarge,
    ml_g5_16_xlarge,
    ml_g5_24_xlarge,
    ml_g5_48_xlarge,
    ml_c5_large,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_12_xlarge,
    ml_c5_18_xlarge,
    ml_c5_24_xlarge,
    ml_c5_n_large,
    ml_c5_n_2_xlarge,
    ml_c5_n_4_xlarge,
    ml_c5_n_9_xlarge,
    ml_c5_n_18_xlarge,
    ml_m5_large,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_8_xlarge,
    ml_m5_12_xlarge,
    ml_m5_16_xlarge,
    ml_m5_24_xlarge,
    ml_t3_medium,
    ml_t3_large,
    ml_t3_xlarge,
    ml_t3_2_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_16_xlarge,
    ml_g6_12_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,
    ml_gr6_4_xlarge,
    ml_gr6_8_xlarge,
    ml_g6_e_xlarge,
    ml_g6_e_2_xlarge,
    ml_g6_e_4_xlarge,
    ml_g6_e_8_xlarge,
    ml_g6_e_16_xlarge,
    ml_g6_e_12_xlarge,
    ml_g6_e_24_xlarge,
    ml_g6_e_48_xlarge,
    ml_p5_e_48_xlarge,
    ml_p5_en_48_xlarge,
    ml_p6_b200_48_xlarge,
    ml_trn2_3_xlarge,
    ml_trn2_48_xlarge,
    ml_c6_i_large,
    ml_c6_i_xlarge,
    ml_c6_i_2_xlarge,
    ml_c6_i_4_xlarge,
    ml_c6_i_8_xlarge,
    ml_c6_i_12_xlarge,
    ml_c6_i_16_xlarge,
    ml_c6_i_24_xlarge,
    ml_c6_i_32_xlarge,
    ml_m6_i_large,
    ml_m6_i_xlarge,
    ml_m6_i_2_xlarge,
    ml_m6_i_4_xlarge,
    ml_m6_i_8_xlarge,
    ml_m6_i_12_xlarge,
    ml_m6_i_16_xlarge,
    ml_m6_i_24_xlarge,
    ml_m6_i_32_xlarge,
    ml_r6_i_large,
    ml_r6_i_xlarge,
    ml_r6_i_2_xlarge,
    ml_r6_i_4_xlarge,
    ml_r6_i_8_xlarge,
    ml_r6_i_12_xlarge,
    ml_r6_i_16_xlarge,
    ml_r6_i_24_xlarge,
    ml_r6_i_32_xlarge,
    ml_i3_en_large,
    ml_i3_en_xlarge,
    ml_i3_en_2_xlarge,
    ml_i3_en_3_xlarge,
    ml_i3_en_6_xlarge,
    ml_i3_en_12_xlarge,
    ml_i3_en_24_xlarge,
    ml_m7_i_large,
    ml_m7_i_xlarge,
    ml_m7_i_2_xlarge,
    ml_m7_i_4_xlarge,
    ml_m7_i_8_xlarge,
    ml_m7_i_12_xlarge,
    ml_m7_i_16_xlarge,
    ml_m7_i_24_xlarge,
    ml_m7_i_48_xlarge,
    ml_r7_i_large,
    ml_r7_i_xlarge,
    ml_r7_i_2_xlarge,
    ml_r7_i_4_xlarge,
    ml_r7_i_8_xlarge,
    ml_r7_i_12_xlarge,
    ml_r7_i_16_xlarge,
    ml_r7_i_24_xlarge,
    ml_r7_i_48_xlarge,
    ml_r5_d_16_xlarge,
    ml_g7_e_2_xlarge,
    ml_g7_e_4_xlarge,
    ml_g7_e_8_xlarge,
    ml_g7_e_12_xlarge,
    ml_g7_e_24_xlarge,
    ml_g7_e_48_xlarge,
    ml_p6_b300_48_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_c6_g_medium,
    ml_c6_g_large,
    ml_c6_g_xlarge,
    ml_c6_g_2_xlarge,
    ml_c6_g_4_xlarge,
    ml_c6_g_8_xlarge,
    ml_c6_g_12_xlarge,
    ml_c6_g_16_xlarge,
    ml_c7_g_medium,
    ml_c7_g_large,
    ml_c7_g_xlarge,
    ml_c7_g_2_xlarge,
    ml_c7_g_4_xlarge,
    ml_c7_g_8_xlarge,
    ml_c7_g_12_xlarge,
    ml_c7_g_16_xlarge,
    ml_c8_g_medium,
    ml_c8_g_large,
    ml_c8_g_xlarge,
    ml_c8_g_2_xlarge,
    ml_c8_g_4_xlarge,
    ml_c8_g_8_xlarge,
    ml_c8_g_12_xlarge,
    ml_c8_g_16_xlarge,
    ml_c8_g_24_xlarge,
    ml_c8_g_48_xlarge,
    ml_c6_a_large,
    ml_c6_a_xlarge,
    ml_c6_a_2_xlarge,
    ml_c6_a_4_xlarge,
    ml_c6_a_8_xlarge,
    ml_c6_a_12_xlarge,
    ml_c6_a_16_xlarge,
    ml_c6_a_24_xlarge,
    ml_c6_a_32_xlarge,
    ml_c6_a_48_xlarge,
    ml_m6_a_large,
    ml_m6_a_xlarge,
    ml_m6_a_2_xlarge,
    ml_m6_a_4_xlarge,
    ml_m6_a_8_xlarge,
    ml_m6_a_12_xlarge,
    ml_m6_a_16_xlarge,
    ml_m6_a_24_xlarge,
    ml_m6_a_32_xlarge,
    ml_m6_a_48_xlarge,
    ml_m6_g_medium,
    ml_m6_g_large,
    ml_m6_g_xlarge,
    ml_m6_g_2_xlarge,
    ml_m6_g_4_xlarge,
    ml_m6_g_8_xlarge,
    ml_m6_g_12_xlarge,
    ml_m6_g_16_xlarge,
    ml_m7_g_medium,
    ml_m7_g_large,
    ml_m7_g_xlarge,
    ml_m7_g_2_xlarge,
    ml_m7_g_4_xlarge,
    ml_m7_g_8_xlarge,
    ml_m7_g_12_xlarge,
    ml_m7_g_16_xlarge,
    ml_m8_g_medium,
    ml_m8_g_large,
    ml_m8_g_xlarge,
    ml_m8_g_2_xlarge,
    ml_m8_g_4_xlarge,
    ml_m8_g_8_xlarge,
    ml_m8_g_12_xlarge,
    ml_m8_g_16_xlarge,
    ml_m8_g_24_xlarge,
    ml_m8_g_48_xlarge,
    ml_g7_2_xlarge,
    ml_g7_4_xlarge,
    ml_g7_8_xlarge,
    ml_g7_12_xlarge,
    ml_g7_24_xlarge,
    ml_g7_48_xlarge,
    ml_c8_a_16_xlarge,
    ml_m8_a_16_xlarge,

    pub const json_field_names = .{
        .ml_p4_d_24_xlarge = "ml.p4d.24xlarge",
        .ml_p4_de_24_xlarge = "ml.p4de.24xlarge",
        .ml_p5_48_xlarge = "ml.p5.48xlarge",
        .ml_p5_4_xlarge = "ml.p5.4xlarge",
        .ml_p6_e_gb200_36_xlarge = "ml.p6e-gb200.36xlarge",
        .ml_trn1_32_xlarge = "ml.trn1.32xlarge",
        .ml_trn1_n_32_xlarge = "ml.trn1n.32xlarge",
        .ml_g5_xlarge = "ml.g5.xlarge",
        .ml_g5_2_xlarge = "ml.g5.2xlarge",
        .ml_g5_4_xlarge = "ml.g5.4xlarge",
        .ml_g5_8_xlarge = "ml.g5.8xlarge",
        .ml_g5_12_xlarge = "ml.g5.12xlarge",
        .ml_g5_16_xlarge = "ml.g5.16xlarge",
        .ml_g5_24_xlarge = "ml.g5.24xlarge",
        .ml_g5_48_xlarge = "ml.g5.48xlarge",
        .ml_c5_large = "ml.c5.large",
        .ml_c5_xlarge = "ml.c5.xlarge",
        .ml_c5_2_xlarge = "ml.c5.2xlarge",
        .ml_c5_4_xlarge = "ml.c5.4xlarge",
        .ml_c5_9_xlarge = "ml.c5.9xlarge",
        .ml_c5_12_xlarge = "ml.c5.12xlarge",
        .ml_c5_18_xlarge = "ml.c5.18xlarge",
        .ml_c5_24_xlarge = "ml.c5.24xlarge",
        .ml_c5_n_large = "ml.c5n.large",
        .ml_c5_n_2_xlarge = "ml.c5n.2xlarge",
        .ml_c5_n_4_xlarge = "ml.c5n.4xlarge",
        .ml_c5_n_9_xlarge = "ml.c5n.9xlarge",
        .ml_c5_n_18_xlarge = "ml.c5n.18xlarge",
        .ml_m5_large = "ml.m5.large",
        .ml_m5_xlarge = "ml.m5.xlarge",
        .ml_m5_2_xlarge = "ml.m5.2xlarge",
        .ml_m5_4_xlarge = "ml.m5.4xlarge",
        .ml_m5_8_xlarge = "ml.m5.8xlarge",
        .ml_m5_12_xlarge = "ml.m5.12xlarge",
        .ml_m5_16_xlarge = "ml.m5.16xlarge",
        .ml_m5_24_xlarge = "ml.m5.24xlarge",
        .ml_t3_medium = "ml.t3.medium",
        .ml_t3_large = "ml.t3.large",
        .ml_t3_xlarge = "ml.t3.xlarge",
        .ml_t3_2_xlarge = "ml.t3.2xlarge",
        .ml_g6_xlarge = "ml.g6.xlarge",
        .ml_g6_2_xlarge = "ml.g6.2xlarge",
        .ml_g6_4_xlarge = "ml.g6.4xlarge",
        .ml_g6_8_xlarge = "ml.g6.8xlarge",
        .ml_g6_16_xlarge = "ml.g6.16xlarge",
        .ml_g6_12_xlarge = "ml.g6.12xlarge",
        .ml_g6_24_xlarge = "ml.g6.24xlarge",
        .ml_g6_48_xlarge = "ml.g6.48xlarge",
        .ml_gr6_4_xlarge = "ml.gr6.4xlarge",
        .ml_gr6_8_xlarge = "ml.gr6.8xlarge",
        .ml_g6_e_xlarge = "ml.g6e.xlarge",
        .ml_g6_e_2_xlarge = "ml.g6e.2xlarge",
        .ml_g6_e_4_xlarge = "ml.g6e.4xlarge",
        .ml_g6_e_8_xlarge = "ml.g6e.8xlarge",
        .ml_g6_e_16_xlarge = "ml.g6e.16xlarge",
        .ml_g6_e_12_xlarge = "ml.g6e.12xlarge",
        .ml_g6_e_24_xlarge = "ml.g6e.24xlarge",
        .ml_g6_e_48_xlarge = "ml.g6e.48xlarge",
        .ml_p5_e_48_xlarge = "ml.p5e.48xlarge",
        .ml_p5_en_48_xlarge = "ml.p5en.48xlarge",
        .ml_p6_b200_48_xlarge = "ml.p6-b200.48xlarge",
        .ml_trn2_3_xlarge = "ml.trn2.3xlarge",
        .ml_trn2_48_xlarge = "ml.trn2.48xlarge",
        .ml_c6_i_large = "ml.c6i.large",
        .ml_c6_i_xlarge = "ml.c6i.xlarge",
        .ml_c6_i_2_xlarge = "ml.c6i.2xlarge",
        .ml_c6_i_4_xlarge = "ml.c6i.4xlarge",
        .ml_c6_i_8_xlarge = "ml.c6i.8xlarge",
        .ml_c6_i_12_xlarge = "ml.c6i.12xlarge",
        .ml_c6_i_16_xlarge = "ml.c6i.16xlarge",
        .ml_c6_i_24_xlarge = "ml.c6i.24xlarge",
        .ml_c6_i_32_xlarge = "ml.c6i.32xlarge",
        .ml_m6_i_large = "ml.m6i.large",
        .ml_m6_i_xlarge = "ml.m6i.xlarge",
        .ml_m6_i_2_xlarge = "ml.m6i.2xlarge",
        .ml_m6_i_4_xlarge = "ml.m6i.4xlarge",
        .ml_m6_i_8_xlarge = "ml.m6i.8xlarge",
        .ml_m6_i_12_xlarge = "ml.m6i.12xlarge",
        .ml_m6_i_16_xlarge = "ml.m6i.16xlarge",
        .ml_m6_i_24_xlarge = "ml.m6i.24xlarge",
        .ml_m6_i_32_xlarge = "ml.m6i.32xlarge",
        .ml_r6_i_large = "ml.r6i.large",
        .ml_r6_i_xlarge = "ml.r6i.xlarge",
        .ml_r6_i_2_xlarge = "ml.r6i.2xlarge",
        .ml_r6_i_4_xlarge = "ml.r6i.4xlarge",
        .ml_r6_i_8_xlarge = "ml.r6i.8xlarge",
        .ml_r6_i_12_xlarge = "ml.r6i.12xlarge",
        .ml_r6_i_16_xlarge = "ml.r6i.16xlarge",
        .ml_r6_i_24_xlarge = "ml.r6i.24xlarge",
        .ml_r6_i_32_xlarge = "ml.r6i.32xlarge",
        .ml_i3_en_large = "ml.i3en.large",
        .ml_i3_en_xlarge = "ml.i3en.xlarge",
        .ml_i3_en_2_xlarge = "ml.i3en.2xlarge",
        .ml_i3_en_3_xlarge = "ml.i3en.3xlarge",
        .ml_i3_en_6_xlarge = "ml.i3en.6xlarge",
        .ml_i3_en_12_xlarge = "ml.i3en.12xlarge",
        .ml_i3_en_24_xlarge = "ml.i3en.24xlarge",
        .ml_m7_i_large = "ml.m7i.large",
        .ml_m7_i_xlarge = "ml.m7i.xlarge",
        .ml_m7_i_2_xlarge = "ml.m7i.2xlarge",
        .ml_m7_i_4_xlarge = "ml.m7i.4xlarge",
        .ml_m7_i_8_xlarge = "ml.m7i.8xlarge",
        .ml_m7_i_12_xlarge = "ml.m7i.12xlarge",
        .ml_m7_i_16_xlarge = "ml.m7i.16xlarge",
        .ml_m7_i_24_xlarge = "ml.m7i.24xlarge",
        .ml_m7_i_48_xlarge = "ml.m7i.48xlarge",
        .ml_r7_i_large = "ml.r7i.large",
        .ml_r7_i_xlarge = "ml.r7i.xlarge",
        .ml_r7_i_2_xlarge = "ml.r7i.2xlarge",
        .ml_r7_i_4_xlarge = "ml.r7i.4xlarge",
        .ml_r7_i_8_xlarge = "ml.r7i.8xlarge",
        .ml_r7_i_12_xlarge = "ml.r7i.12xlarge",
        .ml_r7_i_16_xlarge = "ml.r7i.16xlarge",
        .ml_r7_i_24_xlarge = "ml.r7i.24xlarge",
        .ml_r7_i_48_xlarge = "ml.r7i.48xlarge",
        .ml_r5_d_16_xlarge = "ml.r5d.16xlarge",
        .ml_g7_e_2_xlarge = "ml.g7e.2xlarge",
        .ml_g7_e_4_xlarge = "ml.g7e.4xlarge",
        .ml_g7_e_8_xlarge = "ml.g7e.8xlarge",
        .ml_g7_e_12_xlarge = "ml.g7e.12xlarge",
        .ml_g7_e_24_xlarge = "ml.g7e.24xlarge",
        .ml_g7_e_48_xlarge = "ml.g7e.48xlarge",
        .ml_p6_b300_48_xlarge = "ml.p6-b300.48xlarge",
        .ml_g4_dn_xlarge = "ml.g4dn.xlarge",
        .ml_g4_dn_2_xlarge = "ml.g4dn.2xlarge",
        .ml_g4_dn_4_xlarge = "ml.g4dn.4xlarge",
        .ml_g4_dn_8_xlarge = "ml.g4dn.8xlarge",
        .ml_g4_dn_12_xlarge = "ml.g4dn.12xlarge",
        .ml_g4_dn_16_xlarge = "ml.g4dn.16xlarge",
        .ml_c6_g_medium = "ml.c6g.medium",
        .ml_c6_g_large = "ml.c6g.large",
        .ml_c6_g_xlarge = "ml.c6g.xlarge",
        .ml_c6_g_2_xlarge = "ml.c6g.2xlarge",
        .ml_c6_g_4_xlarge = "ml.c6g.4xlarge",
        .ml_c6_g_8_xlarge = "ml.c6g.8xlarge",
        .ml_c6_g_12_xlarge = "ml.c6g.12xlarge",
        .ml_c6_g_16_xlarge = "ml.c6g.16xlarge",
        .ml_c7_g_medium = "ml.c7g.medium",
        .ml_c7_g_large = "ml.c7g.large",
        .ml_c7_g_xlarge = "ml.c7g.xlarge",
        .ml_c7_g_2_xlarge = "ml.c7g.2xlarge",
        .ml_c7_g_4_xlarge = "ml.c7g.4xlarge",
        .ml_c7_g_8_xlarge = "ml.c7g.8xlarge",
        .ml_c7_g_12_xlarge = "ml.c7g.12xlarge",
        .ml_c7_g_16_xlarge = "ml.c7g.16xlarge",
        .ml_c8_g_medium = "ml.c8g.medium",
        .ml_c8_g_large = "ml.c8g.large",
        .ml_c8_g_xlarge = "ml.c8g.xlarge",
        .ml_c8_g_2_xlarge = "ml.c8g.2xlarge",
        .ml_c8_g_4_xlarge = "ml.c8g.4xlarge",
        .ml_c8_g_8_xlarge = "ml.c8g.8xlarge",
        .ml_c8_g_12_xlarge = "ml.c8g.12xlarge",
        .ml_c8_g_16_xlarge = "ml.c8g.16xlarge",
        .ml_c8_g_24_xlarge = "ml.c8g.24xlarge",
        .ml_c8_g_48_xlarge = "ml.c8g.48xlarge",
        .ml_c6_a_large = "ml.c6a.large",
        .ml_c6_a_xlarge = "ml.c6a.xlarge",
        .ml_c6_a_2_xlarge = "ml.c6a.2xlarge",
        .ml_c6_a_4_xlarge = "ml.c6a.4xlarge",
        .ml_c6_a_8_xlarge = "ml.c6a.8xlarge",
        .ml_c6_a_12_xlarge = "ml.c6a.12xlarge",
        .ml_c6_a_16_xlarge = "ml.c6a.16xlarge",
        .ml_c6_a_24_xlarge = "ml.c6a.24xlarge",
        .ml_c6_a_32_xlarge = "ml.c6a.32xlarge",
        .ml_c6_a_48_xlarge = "ml.c6a.48xlarge",
        .ml_m6_a_large = "ml.m6a.large",
        .ml_m6_a_xlarge = "ml.m6a.xlarge",
        .ml_m6_a_2_xlarge = "ml.m6a.2xlarge",
        .ml_m6_a_4_xlarge = "ml.m6a.4xlarge",
        .ml_m6_a_8_xlarge = "ml.m6a.8xlarge",
        .ml_m6_a_12_xlarge = "ml.m6a.12xlarge",
        .ml_m6_a_16_xlarge = "ml.m6a.16xlarge",
        .ml_m6_a_24_xlarge = "ml.m6a.24xlarge",
        .ml_m6_a_32_xlarge = "ml.m6a.32xlarge",
        .ml_m6_a_48_xlarge = "ml.m6a.48xlarge",
        .ml_m6_g_medium = "ml.m6g.medium",
        .ml_m6_g_large = "ml.m6g.large",
        .ml_m6_g_xlarge = "ml.m6g.xlarge",
        .ml_m6_g_2_xlarge = "ml.m6g.2xlarge",
        .ml_m6_g_4_xlarge = "ml.m6g.4xlarge",
        .ml_m6_g_8_xlarge = "ml.m6g.8xlarge",
        .ml_m6_g_12_xlarge = "ml.m6g.12xlarge",
        .ml_m6_g_16_xlarge = "ml.m6g.16xlarge",
        .ml_m7_g_medium = "ml.m7g.medium",
        .ml_m7_g_large = "ml.m7g.large",
        .ml_m7_g_xlarge = "ml.m7g.xlarge",
        .ml_m7_g_2_xlarge = "ml.m7g.2xlarge",
        .ml_m7_g_4_xlarge = "ml.m7g.4xlarge",
        .ml_m7_g_8_xlarge = "ml.m7g.8xlarge",
        .ml_m7_g_12_xlarge = "ml.m7g.12xlarge",
        .ml_m7_g_16_xlarge = "ml.m7g.16xlarge",
        .ml_m8_g_medium = "ml.m8g.medium",
        .ml_m8_g_large = "ml.m8g.large",
        .ml_m8_g_xlarge = "ml.m8g.xlarge",
        .ml_m8_g_2_xlarge = "ml.m8g.2xlarge",
        .ml_m8_g_4_xlarge = "ml.m8g.4xlarge",
        .ml_m8_g_8_xlarge = "ml.m8g.8xlarge",
        .ml_m8_g_12_xlarge = "ml.m8g.12xlarge",
        .ml_m8_g_16_xlarge = "ml.m8g.16xlarge",
        .ml_m8_g_24_xlarge = "ml.m8g.24xlarge",
        .ml_m8_g_48_xlarge = "ml.m8g.48xlarge",
        .ml_g7_2_xlarge = "ml.g7.2xlarge",
        .ml_g7_4_xlarge = "ml.g7.4xlarge",
        .ml_g7_8_xlarge = "ml.g7.8xlarge",
        .ml_g7_12_xlarge = "ml.g7.12xlarge",
        .ml_g7_24_xlarge = "ml.g7.24xlarge",
        .ml_g7_48_xlarge = "ml.g7.48xlarge",
        .ml_c8_a_16_xlarge = "ml.c8a.16xlarge",
        .ml_m8_a_16_xlarge = "ml.m8a.16xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .ml_p4_d_24_xlarge => "ml.p4d.24xlarge",
            .ml_p4_de_24_xlarge => "ml.p4de.24xlarge",
            .ml_p5_48_xlarge => "ml.p5.48xlarge",
            .ml_p5_4_xlarge => "ml.p5.4xlarge",
            .ml_p6_e_gb200_36_xlarge => "ml.p6e-gb200.36xlarge",
            .ml_trn1_32_xlarge => "ml.trn1.32xlarge",
            .ml_trn1_n_32_xlarge => "ml.trn1n.32xlarge",
            .ml_g5_xlarge => "ml.g5.xlarge",
            .ml_g5_2_xlarge => "ml.g5.2xlarge",
            .ml_g5_4_xlarge => "ml.g5.4xlarge",
            .ml_g5_8_xlarge => "ml.g5.8xlarge",
            .ml_g5_12_xlarge => "ml.g5.12xlarge",
            .ml_g5_16_xlarge => "ml.g5.16xlarge",
            .ml_g5_24_xlarge => "ml.g5.24xlarge",
            .ml_g5_48_xlarge => "ml.g5.48xlarge",
            .ml_c5_large => "ml.c5.large",
            .ml_c5_xlarge => "ml.c5.xlarge",
            .ml_c5_2_xlarge => "ml.c5.2xlarge",
            .ml_c5_4_xlarge => "ml.c5.4xlarge",
            .ml_c5_9_xlarge => "ml.c5.9xlarge",
            .ml_c5_12_xlarge => "ml.c5.12xlarge",
            .ml_c5_18_xlarge => "ml.c5.18xlarge",
            .ml_c5_24_xlarge => "ml.c5.24xlarge",
            .ml_c5_n_large => "ml.c5n.large",
            .ml_c5_n_2_xlarge => "ml.c5n.2xlarge",
            .ml_c5_n_4_xlarge => "ml.c5n.4xlarge",
            .ml_c5_n_9_xlarge => "ml.c5n.9xlarge",
            .ml_c5_n_18_xlarge => "ml.c5n.18xlarge",
            .ml_m5_large => "ml.m5.large",
            .ml_m5_xlarge => "ml.m5.xlarge",
            .ml_m5_2_xlarge => "ml.m5.2xlarge",
            .ml_m5_4_xlarge => "ml.m5.4xlarge",
            .ml_m5_8_xlarge => "ml.m5.8xlarge",
            .ml_m5_12_xlarge => "ml.m5.12xlarge",
            .ml_m5_16_xlarge => "ml.m5.16xlarge",
            .ml_m5_24_xlarge => "ml.m5.24xlarge",
            .ml_t3_medium => "ml.t3.medium",
            .ml_t3_large => "ml.t3.large",
            .ml_t3_xlarge => "ml.t3.xlarge",
            .ml_t3_2_xlarge => "ml.t3.2xlarge",
            .ml_g6_xlarge => "ml.g6.xlarge",
            .ml_g6_2_xlarge => "ml.g6.2xlarge",
            .ml_g6_4_xlarge => "ml.g6.4xlarge",
            .ml_g6_8_xlarge => "ml.g6.8xlarge",
            .ml_g6_16_xlarge => "ml.g6.16xlarge",
            .ml_g6_12_xlarge => "ml.g6.12xlarge",
            .ml_g6_24_xlarge => "ml.g6.24xlarge",
            .ml_g6_48_xlarge => "ml.g6.48xlarge",
            .ml_gr6_4_xlarge => "ml.gr6.4xlarge",
            .ml_gr6_8_xlarge => "ml.gr6.8xlarge",
            .ml_g6_e_xlarge => "ml.g6e.xlarge",
            .ml_g6_e_2_xlarge => "ml.g6e.2xlarge",
            .ml_g6_e_4_xlarge => "ml.g6e.4xlarge",
            .ml_g6_e_8_xlarge => "ml.g6e.8xlarge",
            .ml_g6_e_16_xlarge => "ml.g6e.16xlarge",
            .ml_g6_e_12_xlarge => "ml.g6e.12xlarge",
            .ml_g6_e_24_xlarge => "ml.g6e.24xlarge",
            .ml_g6_e_48_xlarge => "ml.g6e.48xlarge",
            .ml_p5_e_48_xlarge => "ml.p5e.48xlarge",
            .ml_p5_en_48_xlarge => "ml.p5en.48xlarge",
            .ml_p6_b200_48_xlarge => "ml.p6-b200.48xlarge",
            .ml_trn2_3_xlarge => "ml.trn2.3xlarge",
            .ml_trn2_48_xlarge => "ml.trn2.48xlarge",
            .ml_c6_i_large => "ml.c6i.large",
            .ml_c6_i_xlarge => "ml.c6i.xlarge",
            .ml_c6_i_2_xlarge => "ml.c6i.2xlarge",
            .ml_c6_i_4_xlarge => "ml.c6i.4xlarge",
            .ml_c6_i_8_xlarge => "ml.c6i.8xlarge",
            .ml_c6_i_12_xlarge => "ml.c6i.12xlarge",
            .ml_c6_i_16_xlarge => "ml.c6i.16xlarge",
            .ml_c6_i_24_xlarge => "ml.c6i.24xlarge",
            .ml_c6_i_32_xlarge => "ml.c6i.32xlarge",
            .ml_m6_i_large => "ml.m6i.large",
            .ml_m6_i_xlarge => "ml.m6i.xlarge",
            .ml_m6_i_2_xlarge => "ml.m6i.2xlarge",
            .ml_m6_i_4_xlarge => "ml.m6i.4xlarge",
            .ml_m6_i_8_xlarge => "ml.m6i.8xlarge",
            .ml_m6_i_12_xlarge => "ml.m6i.12xlarge",
            .ml_m6_i_16_xlarge => "ml.m6i.16xlarge",
            .ml_m6_i_24_xlarge => "ml.m6i.24xlarge",
            .ml_m6_i_32_xlarge => "ml.m6i.32xlarge",
            .ml_r6_i_large => "ml.r6i.large",
            .ml_r6_i_xlarge => "ml.r6i.xlarge",
            .ml_r6_i_2_xlarge => "ml.r6i.2xlarge",
            .ml_r6_i_4_xlarge => "ml.r6i.4xlarge",
            .ml_r6_i_8_xlarge => "ml.r6i.8xlarge",
            .ml_r6_i_12_xlarge => "ml.r6i.12xlarge",
            .ml_r6_i_16_xlarge => "ml.r6i.16xlarge",
            .ml_r6_i_24_xlarge => "ml.r6i.24xlarge",
            .ml_r6_i_32_xlarge => "ml.r6i.32xlarge",
            .ml_i3_en_large => "ml.i3en.large",
            .ml_i3_en_xlarge => "ml.i3en.xlarge",
            .ml_i3_en_2_xlarge => "ml.i3en.2xlarge",
            .ml_i3_en_3_xlarge => "ml.i3en.3xlarge",
            .ml_i3_en_6_xlarge => "ml.i3en.6xlarge",
            .ml_i3_en_12_xlarge => "ml.i3en.12xlarge",
            .ml_i3_en_24_xlarge => "ml.i3en.24xlarge",
            .ml_m7_i_large => "ml.m7i.large",
            .ml_m7_i_xlarge => "ml.m7i.xlarge",
            .ml_m7_i_2_xlarge => "ml.m7i.2xlarge",
            .ml_m7_i_4_xlarge => "ml.m7i.4xlarge",
            .ml_m7_i_8_xlarge => "ml.m7i.8xlarge",
            .ml_m7_i_12_xlarge => "ml.m7i.12xlarge",
            .ml_m7_i_16_xlarge => "ml.m7i.16xlarge",
            .ml_m7_i_24_xlarge => "ml.m7i.24xlarge",
            .ml_m7_i_48_xlarge => "ml.m7i.48xlarge",
            .ml_r7_i_large => "ml.r7i.large",
            .ml_r7_i_xlarge => "ml.r7i.xlarge",
            .ml_r7_i_2_xlarge => "ml.r7i.2xlarge",
            .ml_r7_i_4_xlarge => "ml.r7i.4xlarge",
            .ml_r7_i_8_xlarge => "ml.r7i.8xlarge",
            .ml_r7_i_12_xlarge => "ml.r7i.12xlarge",
            .ml_r7_i_16_xlarge => "ml.r7i.16xlarge",
            .ml_r7_i_24_xlarge => "ml.r7i.24xlarge",
            .ml_r7_i_48_xlarge => "ml.r7i.48xlarge",
            .ml_r5_d_16_xlarge => "ml.r5d.16xlarge",
            .ml_g7_e_2_xlarge => "ml.g7e.2xlarge",
            .ml_g7_e_4_xlarge => "ml.g7e.4xlarge",
            .ml_g7_e_8_xlarge => "ml.g7e.8xlarge",
            .ml_g7_e_12_xlarge => "ml.g7e.12xlarge",
            .ml_g7_e_24_xlarge => "ml.g7e.24xlarge",
            .ml_g7_e_48_xlarge => "ml.g7e.48xlarge",
            .ml_p6_b300_48_xlarge => "ml.p6-b300.48xlarge",
            .ml_g4_dn_xlarge => "ml.g4dn.xlarge",
            .ml_g4_dn_2_xlarge => "ml.g4dn.2xlarge",
            .ml_g4_dn_4_xlarge => "ml.g4dn.4xlarge",
            .ml_g4_dn_8_xlarge => "ml.g4dn.8xlarge",
            .ml_g4_dn_12_xlarge => "ml.g4dn.12xlarge",
            .ml_g4_dn_16_xlarge => "ml.g4dn.16xlarge",
            .ml_c6_g_medium => "ml.c6g.medium",
            .ml_c6_g_large => "ml.c6g.large",
            .ml_c6_g_xlarge => "ml.c6g.xlarge",
            .ml_c6_g_2_xlarge => "ml.c6g.2xlarge",
            .ml_c6_g_4_xlarge => "ml.c6g.4xlarge",
            .ml_c6_g_8_xlarge => "ml.c6g.8xlarge",
            .ml_c6_g_12_xlarge => "ml.c6g.12xlarge",
            .ml_c6_g_16_xlarge => "ml.c6g.16xlarge",
            .ml_c7_g_medium => "ml.c7g.medium",
            .ml_c7_g_large => "ml.c7g.large",
            .ml_c7_g_xlarge => "ml.c7g.xlarge",
            .ml_c7_g_2_xlarge => "ml.c7g.2xlarge",
            .ml_c7_g_4_xlarge => "ml.c7g.4xlarge",
            .ml_c7_g_8_xlarge => "ml.c7g.8xlarge",
            .ml_c7_g_12_xlarge => "ml.c7g.12xlarge",
            .ml_c7_g_16_xlarge => "ml.c7g.16xlarge",
            .ml_c8_g_medium => "ml.c8g.medium",
            .ml_c8_g_large => "ml.c8g.large",
            .ml_c8_g_xlarge => "ml.c8g.xlarge",
            .ml_c8_g_2_xlarge => "ml.c8g.2xlarge",
            .ml_c8_g_4_xlarge => "ml.c8g.4xlarge",
            .ml_c8_g_8_xlarge => "ml.c8g.8xlarge",
            .ml_c8_g_12_xlarge => "ml.c8g.12xlarge",
            .ml_c8_g_16_xlarge => "ml.c8g.16xlarge",
            .ml_c8_g_24_xlarge => "ml.c8g.24xlarge",
            .ml_c8_g_48_xlarge => "ml.c8g.48xlarge",
            .ml_c6_a_large => "ml.c6a.large",
            .ml_c6_a_xlarge => "ml.c6a.xlarge",
            .ml_c6_a_2_xlarge => "ml.c6a.2xlarge",
            .ml_c6_a_4_xlarge => "ml.c6a.4xlarge",
            .ml_c6_a_8_xlarge => "ml.c6a.8xlarge",
            .ml_c6_a_12_xlarge => "ml.c6a.12xlarge",
            .ml_c6_a_16_xlarge => "ml.c6a.16xlarge",
            .ml_c6_a_24_xlarge => "ml.c6a.24xlarge",
            .ml_c6_a_32_xlarge => "ml.c6a.32xlarge",
            .ml_c6_a_48_xlarge => "ml.c6a.48xlarge",
            .ml_m6_a_large => "ml.m6a.large",
            .ml_m6_a_xlarge => "ml.m6a.xlarge",
            .ml_m6_a_2_xlarge => "ml.m6a.2xlarge",
            .ml_m6_a_4_xlarge => "ml.m6a.4xlarge",
            .ml_m6_a_8_xlarge => "ml.m6a.8xlarge",
            .ml_m6_a_12_xlarge => "ml.m6a.12xlarge",
            .ml_m6_a_16_xlarge => "ml.m6a.16xlarge",
            .ml_m6_a_24_xlarge => "ml.m6a.24xlarge",
            .ml_m6_a_32_xlarge => "ml.m6a.32xlarge",
            .ml_m6_a_48_xlarge => "ml.m6a.48xlarge",
            .ml_m6_g_medium => "ml.m6g.medium",
            .ml_m6_g_large => "ml.m6g.large",
            .ml_m6_g_xlarge => "ml.m6g.xlarge",
            .ml_m6_g_2_xlarge => "ml.m6g.2xlarge",
            .ml_m6_g_4_xlarge => "ml.m6g.4xlarge",
            .ml_m6_g_8_xlarge => "ml.m6g.8xlarge",
            .ml_m6_g_12_xlarge => "ml.m6g.12xlarge",
            .ml_m6_g_16_xlarge => "ml.m6g.16xlarge",
            .ml_m7_g_medium => "ml.m7g.medium",
            .ml_m7_g_large => "ml.m7g.large",
            .ml_m7_g_xlarge => "ml.m7g.xlarge",
            .ml_m7_g_2_xlarge => "ml.m7g.2xlarge",
            .ml_m7_g_4_xlarge => "ml.m7g.4xlarge",
            .ml_m7_g_8_xlarge => "ml.m7g.8xlarge",
            .ml_m7_g_12_xlarge => "ml.m7g.12xlarge",
            .ml_m7_g_16_xlarge => "ml.m7g.16xlarge",
            .ml_m8_g_medium => "ml.m8g.medium",
            .ml_m8_g_large => "ml.m8g.large",
            .ml_m8_g_xlarge => "ml.m8g.xlarge",
            .ml_m8_g_2_xlarge => "ml.m8g.2xlarge",
            .ml_m8_g_4_xlarge => "ml.m8g.4xlarge",
            .ml_m8_g_8_xlarge => "ml.m8g.8xlarge",
            .ml_m8_g_12_xlarge => "ml.m8g.12xlarge",
            .ml_m8_g_16_xlarge => "ml.m8g.16xlarge",
            .ml_m8_g_24_xlarge => "ml.m8g.24xlarge",
            .ml_m8_g_48_xlarge => "ml.m8g.48xlarge",
            .ml_g7_2_xlarge => "ml.g7.2xlarge",
            .ml_g7_4_xlarge => "ml.g7.4xlarge",
            .ml_g7_8_xlarge => "ml.g7.8xlarge",
            .ml_g7_12_xlarge => "ml.g7.12xlarge",
            .ml_g7_24_xlarge => "ml.g7.24xlarge",
            .ml_g7_48_xlarge => "ml.g7.48xlarge",
            .ml_c8_a_16_xlarge => "ml.c8a.16xlarge",
            .ml_m8_a_16_xlarge => "ml.m8a.16xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
