pub const InstanceType = enum {
    ml_t2_medium,
    ml_t2_large,
    ml_t2_xlarge,
    ml_t2_2_xlarge,
    ml_t3_medium,
    ml_t3_large,
    ml_t3_xlarge,
    ml_t3_2_xlarge,
    ml_m4_xlarge,
    ml_m4_2_xlarge,
    ml_m4_4_xlarge,
    ml_m4_10_xlarge,
    ml_m4_16_xlarge,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_12_xlarge,
    ml_m5_24_xlarge,
    ml_m5_d_large,
    ml_m5_d_xlarge,
    ml_m5_d_2_xlarge,
    ml_m5_d_4_xlarge,
    ml_m5_d_8_xlarge,
    ml_m5_d_12_xlarge,
    ml_m5_d_16_xlarge,
    ml_m5_d_24_xlarge,
    ml_c4_xlarge,
    ml_c4_2_xlarge,
    ml_c4_4_xlarge,
    ml_c4_8_xlarge,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_18_xlarge,
    ml_c5_d_xlarge,
    ml_c5_d_2_xlarge,
    ml_c5_d_4_xlarge,
    ml_c5_d_9_xlarge,
    ml_c5_d_18_xlarge,
    ml_p2_xlarge,
    ml_p2_8_xlarge,
    ml_p2_16_xlarge,
    ml_p3_2_xlarge,
    ml_p3_8_xlarge,
    ml_p3_16_xlarge,
    ml_p3_dn_24_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_r5_large,
    ml_r5_xlarge,
    ml_r5_2_xlarge,
    ml_r5_4_xlarge,
    ml_r5_8_xlarge,
    ml_r5_12_xlarge,
    ml_r5_16_xlarge,
    ml_r5_24_xlarge,
    ml_g5_xlarge,
    ml_g5_2_xlarge,
    ml_g5_4_xlarge,
    ml_g5_8_xlarge,
    ml_g5_16_xlarge,
    ml_g5_12_xlarge,
    ml_g5_24_xlarge,
    ml_g5_48_xlarge,
    ml_inf1_xlarge,
    ml_inf1_2_xlarge,
    ml_inf1_6_xlarge,
    ml_inf1_24_xlarge,
    ml_trn1_2_xlarge,
    ml_trn1_32_xlarge,
    ml_trn1_n_32_xlarge,
    ml_inf2_xlarge,
    ml_inf2_8_xlarge,
    ml_inf2_24_xlarge,
    ml_inf2_48_xlarge,
    ml_p4_d_24_xlarge,
    ml_p4_de_24_xlarge,
    ml_p5_48_xlarge,
    ml_p6_b200_48_xlarge,
    ml_m6_i_large,
    ml_m6_i_xlarge,
    ml_m6_i_2_xlarge,
    ml_m6_i_4_xlarge,
    ml_m6_i_8_xlarge,
    ml_m6_i_12_xlarge,
    ml_m6_i_16_xlarge,
    ml_m6_i_24_xlarge,
    ml_m6_i_32_xlarge,
    ml_m7_i_large,
    ml_m7_i_xlarge,
    ml_m7_i_2_xlarge,
    ml_m7_i_4_xlarge,
    ml_m7_i_8_xlarge,
    ml_m7_i_12_xlarge,
    ml_m7_i_16_xlarge,
    ml_m7_i_24_xlarge,
    ml_m7_i_48_xlarge,
    ml_c6_i_large,
    ml_c6_i_xlarge,
    ml_c6_i_2_xlarge,
    ml_c6_i_4_xlarge,
    ml_c6_i_8_xlarge,
    ml_c6_i_12_xlarge,
    ml_c6_i_16_xlarge,
    ml_c6_i_24_xlarge,
    ml_c6_i_32_xlarge,
    ml_c7_i_large,
    ml_c7_i_xlarge,
    ml_c7_i_2_xlarge,
    ml_c7_i_4_xlarge,
    ml_c7_i_8_xlarge,
    ml_c7_i_12_xlarge,
    ml_c7_i_16_xlarge,
    ml_c7_i_24_xlarge,
    ml_c7_i_48_xlarge,
    ml_r6_i_large,
    ml_r6_i_xlarge,
    ml_r6_i_2_xlarge,
    ml_r6_i_4_xlarge,
    ml_r6_i_8_xlarge,
    ml_r6_i_12_xlarge,
    ml_r6_i_16_xlarge,
    ml_r6_i_24_xlarge,
    ml_r6_i_32_xlarge,
    ml_r7_i_large,
    ml_r7_i_xlarge,
    ml_r7_i_2_xlarge,
    ml_r7_i_4_xlarge,
    ml_r7_i_8_xlarge,
    ml_r7_i_12_xlarge,
    ml_r7_i_16_xlarge,
    ml_r7_i_24_xlarge,
    ml_r7_i_48_xlarge,
    ml_m6_id_large,
    ml_m6_id_xlarge,
    ml_m6_id_2_xlarge,
    ml_m6_id_4_xlarge,
    ml_m6_id_8_xlarge,
    ml_m6_id_12_xlarge,
    ml_m6_id_16_xlarge,
    ml_m6_id_24_xlarge,
    ml_m6_id_32_xlarge,
    ml_c6_id_large,
    ml_c6_id_xlarge,
    ml_c6_id_2_xlarge,
    ml_c6_id_4_xlarge,
    ml_c6_id_8_xlarge,
    ml_c6_id_12_xlarge,
    ml_c6_id_16_xlarge,
    ml_c6_id_24_xlarge,
    ml_c6_id_32_xlarge,
    ml_r6_id_large,
    ml_r6_id_xlarge,
    ml_r6_id_2_xlarge,
    ml_r6_id_4_xlarge,
    ml_r6_id_8_xlarge,
    ml_r6_id_12_xlarge,
    ml_r6_id_16_xlarge,
    ml_r6_id_24_xlarge,
    ml_r6_id_32_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_12_xlarge,
    ml_g6_16_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,

    pub const json_field_names = .{
        .ml_t2_medium = "ML_T2_MEDIUM",
        .ml_t2_large = "ML_T2_LARGE",
        .ml_t2_xlarge = "ML_T2_XLARGE",
        .ml_t2_2_xlarge = "ML_T2_2XLARGE",
        .ml_t3_medium = "ML_T3_MEDIUM",
        .ml_t3_large = "ML_T3_LARGE",
        .ml_t3_xlarge = "ML_T3_XLARGE",
        .ml_t3_2_xlarge = "ML_T3_2XLARGE",
        .ml_m4_xlarge = "ML_M4_XLARGE",
        .ml_m4_2_xlarge = "ML_M4_2XLARGE",
        .ml_m4_4_xlarge = "ML_M4_4XLARGE",
        .ml_m4_10_xlarge = "ML_M4_10XLARGE",
        .ml_m4_16_xlarge = "ML_M4_16XLARGE",
        .ml_m5_xlarge = "ML_M5_XLARGE",
        .ml_m5_2_xlarge = "ML_M5_2XLARGE",
        .ml_m5_4_xlarge = "ML_M5_4XLARGE",
        .ml_m5_12_xlarge = "ML_M5_12XLARGE",
        .ml_m5_24_xlarge = "ML_M5_24XLARGE",
        .ml_m5_d_large = "ML_M5D_LARGE",
        .ml_m5_d_xlarge = "ML_M5D_XLARGE",
        .ml_m5_d_2_xlarge = "ML_M5D_2XLARGE",
        .ml_m5_d_4_xlarge = "ML_M5D_4XLARGE",
        .ml_m5_d_8_xlarge = "ML_M5D_8XLARGE",
        .ml_m5_d_12_xlarge = "ML_M5D_12XLARGE",
        .ml_m5_d_16_xlarge = "ML_M5D_16XLARGE",
        .ml_m5_d_24_xlarge = "ML_M5D_24XLARGE",
        .ml_c4_xlarge = "ML_C4_XLARGE",
        .ml_c4_2_xlarge = "ML_C4_2XLARGE",
        .ml_c4_4_xlarge = "ML_C4_4XLARGE",
        .ml_c4_8_xlarge = "ML_C4_8XLARGE",
        .ml_c5_xlarge = "ML_C5_XLARGE",
        .ml_c5_2_xlarge = "ML_C5_2XLARGE",
        .ml_c5_4_xlarge = "ML_C5_4XLARGE",
        .ml_c5_9_xlarge = "ML_C5_9XLARGE",
        .ml_c5_18_xlarge = "ML_C5_18XLARGE",
        .ml_c5_d_xlarge = "ML_C5D_XLARGE",
        .ml_c5_d_2_xlarge = "ML_C5D_2XLARGE",
        .ml_c5_d_4_xlarge = "ML_C5D_4XLARGE",
        .ml_c5_d_9_xlarge = "ML_C5D_9XLARGE",
        .ml_c5_d_18_xlarge = "ML_C5D_18XLARGE",
        .ml_p2_xlarge = "ML_P2_XLARGE",
        .ml_p2_8_xlarge = "ML_P2_8XLARGE",
        .ml_p2_16_xlarge = "ML_P2_16XLARGE",
        .ml_p3_2_xlarge = "ML_P3_2XLARGE",
        .ml_p3_8_xlarge = "ML_P3_8XLARGE",
        .ml_p3_16_xlarge = "ML_P3_16XLARGE",
        .ml_p3_dn_24_xlarge = "ML_P3DN_24XLARGE",
        .ml_g4_dn_xlarge = "ML_G4DN_XLARGE",
        .ml_g4_dn_2_xlarge = "ML_G4DN_2XLARGE",
        .ml_g4_dn_4_xlarge = "ML_G4DN_4XLARGE",
        .ml_g4_dn_8_xlarge = "ML_G4DN_8XLARGE",
        .ml_g4_dn_12_xlarge = "ML_G4DN_12XLARGE",
        .ml_g4_dn_16_xlarge = "ML_G4DN_16XLARGE",
        .ml_r5_large = "ML_R5_LARGE",
        .ml_r5_xlarge = "ML_R5_XLARGE",
        .ml_r5_2_xlarge = "ML_R5_2XLARGE",
        .ml_r5_4_xlarge = "ML_R5_4XLARGE",
        .ml_r5_8_xlarge = "ML_R5_8XLARGE",
        .ml_r5_12_xlarge = "ML_R5_12XLARGE",
        .ml_r5_16_xlarge = "ML_R5_16XLARGE",
        .ml_r5_24_xlarge = "ML_R5_24XLARGE",
        .ml_g5_xlarge = "ML_G5_XLARGE",
        .ml_g5_2_xlarge = "ML_G5_2XLARGE",
        .ml_g5_4_xlarge = "ML_G5_4XLARGE",
        .ml_g5_8_xlarge = "ML_G5_8XLARGE",
        .ml_g5_16_xlarge = "ML_G5_16XLARGE",
        .ml_g5_12_xlarge = "ML_G5_12XLARGE",
        .ml_g5_24_xlarge = "ML_G5_24XLARGE",
        .ml_g5_48_xlarge = "ML_G5_48XLARGE",
        .ml_inf1_xlarge = "ML_INF1_XLARGE",
        .ml_inf1_2_xlarge = "ML_INF1_2XLARGE",
        .ml_inf1_6_xlarge = "ML_INF1_6XLARGE",
        .ml_inf1_24_xlarge = "ML_INF1_24XLARGE",
        .ml_trn1_2_xlarge = "ML_TRN1_2XLARGE",
        .ml_trn1_32_xlarge = "ML_TRN1_32XLARGE",
        .ml_trn1_n_32_xlarge = "ML_TRN1N_32XLARGE",
        .ml_inf2_xlarge = "ML_INF2_XLARGE",
        .ml_inf2_8_xlarge = "ML_INF2_8XLARGE",
        .ml_inf2_24_xlarge = "ML_INF2_24XLARGE",
        .ml_inf2_48_xlarge = "ML_INF2_48XLARGE",
        .ml_p4_d_24_xlarge = "ML_P4D_24XLARGE",
        .ml_p4_de_24_xlarge = "ML_P4DE_24XLARGE",
        .ml_p5_48_xlarge = "ML_P5_48XLARGE",
        .ml_p6_b200_48_xlarge = "ML_P6_B200_48XLARGE",
        .ml_m6_i_large = "ML_M6I_LARGE",
        .ml_m6_i_xlarge = "ML_M6I_XLARGE",
        .ml_m6_i_2_xlarge = "ML_M6I_2XLARGE",
        .ml_m6_i_4_xlarge = "ML_M6I_4XLARGE",
        .ml_m6_i_8_xlarge = "ML_M6I_8XLARGE",
        .ml_m6_i_12_xlarge = "ML_M6I_12XLARGE",
        .ml_m6_i_16_xlarge = "ML_M6I_16XLARGE",
        .ml_m6_i_24_xlarge = "ML_M6I_24XLARGE",
        .ml_m6_i_32_xlarge = "ML_M6I_32XLARGE",
        .ml_m7_i_large = "ML_M7I_LARGE",
        .ml_m7_i_xlarge = "ML_M7I_XLARGE",
        .ml_m7_i_2_xlarge = "ML_M7I_2XLARGE",
        .ml_m7_i_4_xlarge = "ML_M7I_4XLARGE",
        .ml_m7_i_8_xlarge = "ML_M7I_8XLARGE",
        .ml_m7_i_12_xlarge = "ML_M7I_12XLARGE",
        .ml_m7_i_16_xlarge = "ML_M7I_16XLARGE",
        .ml_m7_i_24_xlarge = "ML_M7I_24XLARGE",
        .ml_m7_i_48_xlarge = "ML_M7I_48XLARGE",
        .ml_c6_i_large = "ML_C6I_LARGE",
        .ml_c6_i_xlarge = "ML_C6I_XLARGE",
        .ml_c6_i_2_xlarge = "ML_C6I_2XLARGE",
        .ml_c6_i_4_xlarge = "ML_C6I_4XLARGE",
        .ml_c6_i_8_xlarge = "ML_C6I_8XLARGE",
        .ml_c6_i_12_xlarge = "ML_C6I_12XLARGE",
        .ml_c6_i_16_xlarge = "ML_C6I_16XLARGE",
        .ml_c6_i_24_xlarge = "ML_C6I_24XLARGE",
        .ml_c6_i_32_xlarge = "ML_C6I_32XLARGE",
        .ml_c7_i_large = "ML_C7I_LARGE",
        .ml_c7_i_xlarge = "ML_C7I_XLARGE",
        .ml_c7_i_2_xlarge = "ML_C7I_2XLARGE",
        .ml_c7_i_4_xlarge = "ML_C7I_4XLARGE",
        .ml_c7_i_8_xlarge = "ML_C7I_8XLARGE",
        .ml_c7_i_12_xlarge = "ML_C7I_12XLARGE",
        .ml_c7_i_16_xlarge = "ML_C7I_16XLARGE",
        .ml_c7_i_24_xlarge = "ML_C7I_24XLARGE",
        .ml_c7_i_48_xlarge = "ML_C7I_48XLARGE",
        .ml_r6_i_large = "ML_R6I_LARGE",
        .ml_r6_i_xlarge = "ML_R6I_XLARGE",
        .ml_r6_i_2_xlarge = "ML_R6I_2XLARGE",
        .ml_r6_i_4_xlarge = "ML_R6I_4XLARGE",
        .ml_r6_i_8_xlarge = "ML_R6I_8XLARGE",
        .ml_r6_i_12_xlarge = "ML_R6I_12XLARGE",
        .ml_r6_i_16_xlarge = "ML_R6I_16XLARGE",
        .ml_r6_i_24_xlarge = "ML_R6I_24XLARGE",
        .ml_r6_i_32_xlarge = "ML_R6I_32XLARGE",
        .ml_r7_i_large = "ML_R7I_LARGE",
        .ml_r7_i_xlarge = "ML_R7I_XLARGE",
        .ml_r7_i_2_xlarge = "ML_R7I_2XLARGE",
        .ml_r7_i_4_xlarge = "ML_R7I_4XLARGE",
        .ml_r7_i_8_xlarge = "ML_R7I_8XLARGE",
        .ml_r7_i_12_xlarge = "ML_R7I_12XLARGE",
        .ml_r7_i_16_xlarge = "ML_R7I_16XLARGE",
        .ml_r7_i_24_xlarge = "ML_R7I_24XLARGE",
        .ml_r7_i_48_xlarge = "ML_R7I_48XLARGE",
        .ml_m6_id_large = "ML_M6ID_LARGE",
        .ml_m6_id_xlarge = "ML_M6ID_XLARGE",
        .ml_m6_id_2_xlarge = "ML_M6ID_2XLARGE",
        .ml_m6_id_4_xlarge = "ML_M6ID_4XLARGE",
        .ml_m6_id_8_xlarge = "ML_M6ID_8XLARGE",
        .ml_m6_id_12_xlarge = "ML_M6ID_12XLARGE",
        .ml_m6_id_16_xlarge = "ML_M6ID_16XLARGE",
        .ml_m6_id_24_xlarge = "ML_M6ID_24XLARGE",
        .ml_m6_id_32_xlarge = "ML_M6ID_32XLARGE",
        .ml_c6_id_large = "ML_C6ID_LARGE",
        .ml_c6_id_xlarge = "ML_C6ID_XLARGE",
        .ml_c6_id_2_xlarge = "ML_C6ID_2XLARGE",
        .ml_c6_id_4_xlarge = "ML_C6ID_4XLARGE",
        .ml_c6_id_8_xlarge = "ML_C6ID_8XLARGE",
        .ml_c6_id_12_xlarge = "ML_C6ID_12XLARGE",
        .ml_c6_id_16_xlarge = "ML_C6ID_16XLARGE",
        .ml_c6_id_24_xlarge = "ML_C6ID_24XLARGE",
        .ml_c6_id_32_xlarge = "ML_C6ID_32XLARGE",
        .ml_r6_id_large = "ML_R6ID_LARGE",
        .ml_r6_id_xlarge = "ML_R6ID_XLARGE",
        .ml_r6_id_2_xlarge = "ML_R6ID_2XLARGE",
        .ml_r6_id_4_xlarge = "ML_R6ID_4XLARGE",
        .ml_r6_id_8_xlarge = "ML_R6ID_8XLARGE",
        .ml_r6_id_12_xlarge = "ML_R6ID_12XLARGE",
        .ml_r6_id_16_xlarge = "ML_R6ID_16XLARGE",
        .ml_r6_id_24_xlarge = "ML_R6ID_24XLARGE",
        .ml_r6_id_32_xlarge = "ML_R6ID_32XLARGE",
        .ml_g6_xlarge = "ML_G6_XLARGE",
        .ml_g6_2_xlarge = "ML_G6_2XLARGE",
        .ml_g6_4_xlarge = "ML_G6_4XLARGE",
        .ml_g6_8_xlarge = "ML_G6_8XLARGE",
        .ml_g6_12_xlarge = "ML_G6_12XLARGE",
        .ml_g6_16_xlarge = "ML_G6_16XLARGE",
        .ml_g6_24_xlarge = "ML_G6_24XLARGE",
        .ml_g6_48_xlarge = "ML_G6_48XLARGE",
    };
};
