pub const MlTools = enum {
    data_wrangler,
    feature_store,
    emr_clusters,
    auto_ml,
    experiments,
    training,
    model_evaluation,
    pipelines,
    models,
    jump_start,
    inference_recommender,
    endpoints,
    projects,
    inference_optimization,
    performance_evaluation,
    lakera_guard,
    comet,
    deepchecks_llm_evaluation,
    fiddler,
    hyper_pod_clusters,
    running_instances,
    datasets,
    evaluators,

    pub const json_field_names = .{
        .data_wrangler = "DATA_WRANGLER",
        .feature_store = "FEATURE_STORE",
        .emr_clusters = "EMR_CLUSTERS",
        .auto_ml = "AUTO_ML",
        .experiments = "EXPERIMENTS",
        .training = "TRAINING",
        .model_evaluation = "MODEL_EVALUATION",
        .pipelines = "PIPELINES",
        .models = "MODELS",
        .jump_start = "JUMP_START",
        .inference_recommender = "INFERENCE_RECOMMENDER",
        .endpoints = "ENDPOINTS",
        .projects = "PROJECTS",
        .inference_optimization = "INFERENCE_OPTIMIZATION",
        .performance_evaluation = "PERFORMANCE_EVALUATION",
        .lakera_guard = "LAKERA_GUARD",
        .comet = "COMET",
        .deepchecks_llm_evaluation = "DEEPCHECKS_LLM_EVALUATION",
        .fiddler = "FIDDLER",
        .hyper_pod_clusters = "HYPER_POD_CLUSTERS",
        .running_instances = "RUNNING_INSTANCES",
        .datasets = "DATASETS",
        .evaluators = "EVALUATORS",
    };
};
