const std = @import("std");

pub const OptimizationJobDeploymentInstanceType = enum {
    ml_p4_d_24_xlarge,
    ml_p4_de_24_xlarge,
    ml_p5_48_xlarge,
    ml_p5_e_48_xlarge,
    ml_p5_en_48_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_g5_xlarge,
    ml_g5_2_xlarge,
    ml_g5_4_xlarge,
    ml_g5_8_xlarge,
    ml_g5_12_xlarge,
    ml_g5_16_xlarge,
    ml_g5_24_xlarge,
    ml_g5_48_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_12_xlarge,
    ml_g6_16_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,
    ml_g6_e_xlarge,
    ml_g6_e_2_xlarge,
    ml_g6_e_4_xlarge,
    ml_g6_e_8_xlarge,
    ml_g6_e_12_xlarge,
    ml_g6_e_16_xlarge,
    ml_g6_e_24_xlarge,
    ml_g6_e_48_xlarge,
    ml_inf2_xlarge,
    ml_inf2_8_xlarge,
    ml_inf2_24_xlarge,
    ml_inf2_48_xlarge,
    ml_trn1_2_xlarge,
    ml_trn1_32_xlarge,
    ml_trn1_n_32_xlarge,

    pub const json_field_names = .{
        .ml_p4_d_24_xlarge = "ml.p4d.24xlarge",
        .ml_p4_de_24_xlarge = "ml.p4de.24xlarge",
        .ml_p5_48_xlarge = "ml.p5.48xlarge",
        .ml_p5_e_48_xlarge = "ml.p5e.48xlarge",
        .ml_p5_en_48_xlarge = "ml.p5en.48xlarge",
        .ml_g4_dn_xlarge = "ml.g4dn.xlarge",
        .ml_g4_dn_2_xlarge = "ml.g4dn.2xlarge",
        .ml_g4_dn_4_xlarge = "ml.g4dn.4xlarge",
        .ml_g4_dn_8_xlarge = "ml.g4dn.8xlarge",
        .ml_g4_dn_12_xlarge = "ml.g4dn.12xlarge",
        .ml_g4_dn_16_xlarge = "ml.g4dn.16xlarge",
        .ml_g5_xlarge = "ml.g5.xlarge",
        .ml_g5_2_xlarge = "ml.g5.2xlarge",
        .ml_g5_4_xlarge = "ml.g5.4xlarge",
        .ml_g5_8_xlarge = "ml.g5.8xlarge",
        .ml_g5_12_xlarge = "ml.g5.12xlarge",
        .ml_g5_16_xlarge = "ml.g5.16xlarge",
        .ml_g5_24_xlarge = "ml.g5.24xlarge",
        .ml_g5_48_xlarge = "ml.g5.48xlarge",
        .ml_g6_xlarge = "ml.g6.xlarge",
        .ml_g6_2_xlarge = "ml.g6.2xlarge",
        .ml_g6_4_xlarge = "ml.g6.4xlarge",
        .ml_g6_8_xlarge = "ml.g6.8xlarge",
        .ml_g6_12_xlarge = "ml.g6.12xlarge",
        .ml_g6_16_xlarge = "ml.g6.16xlarge",
        .ml_g6_24_xlarge = "ml.g6.24xlarge",
        .ml_g6_48_xlarge = "ml.g6.48xlarge",
        .ml_g6_e_xlarge = "ml.g6e.xlarge",
        .ml_g6_e_2_xlarge = "ml.g6e.2xlarge",
        .ml_g6_e_4_xlarge = "ml.g6e.4xlarge",
        .ml_g6_e_8_xlarge = "ml.g6e.8xlarge",
        .ml_g6_e_12_xlarge = "ml.g6e.12xlarge",
        .ml_g6_e_16_xlarge = "ml.g6e.16xlarge",
        .ml_g6_e_24_xlarge = "ml.g6e.24xlarge",
        .ml_g6_e_48_xlarge = "ml.g6e.48xlarge",
        .ml_inf2_xlarge = "ml.inf2.xlarge",
        .ml_inf2_8_xlarge = "ml.inf2.8xlarge",
        .ml_inf2_24_xlarge = "ml.inf2.24xlarge",
        .ml_inf2_48_xlarge = "ml.inf2.48xlarge",
        .ml_trn1_2_xlarge = "ml.trn1.2xlarge",
        .ml_trn1_32_xlarge = "ml.trn1.32xlarge",
        .ml_trn1_n_32_xlarge = "ml.trn1n.32xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .ml_p4_d_24_xlarge => "ml.p4d.24xlarge",
            .ml_p4_de_24_xlarge => "ml.p4de.24xlarge",
            .ml_p5_48_xlarge => "ml.p5.48xlarge",
            .ml_p5_e_48_xlarge => "ml.p5e.48xlarge",
            .ml_p5_en_48_xlarge => "ml.p5en.48xlarge",
            .ml_g4_dn_xlarge => "ml.g4dn.xlarge",
            .ml_g4_dn_2_xlarge => "ml.g4dn.2xlarge",
            .ml_g4_dn_4_xlarge => "ml.g4dn.4xlarge",
            .ml_g4_dn_8_xlarge => "ml.g4dn.8xlarge",
            .ml_g4_dn_12_xlarge => "ml.g4dn.12xlarge",
            .ml_g4_dn_16_xlarge => "ml.g4dn.16xlarge",
            .ml_g5_xlarge => "ml.g5.xlarge",
            .ml_g5_2_xlarge => "ml.g5.2xlarge",
            .ml_g5_4_xlarge => "ml.g5.4xlarge",
            .ml_g5_8_xlarge => "ml.g5.8xlarge",
            .ml_g5_12_xlarge => "ml.g5.12xlarge",
            .ml_g5_16_xlarge => "ml.g5.16xlarge",
            .ml_g5_24_xlarge => "ml.g5.24xlarge",
            .ml_g5_48_xlarge => "ml.g5.48xlarge",
            .ml_g6_xlarge => "ml.g6.xlarge",
            .ml_g6_2_xlarge => "ml.g6.2xlarge",
            .ml_g6_4_xlarge => "ml.g6.4xlarge",
            .ml_g6_8_xlarge => "ml.g6.8xlarge",
            .ml_g6_12_xlarge => "ml.g6.12xlarge",
            .ml_g6_16_xlarge => "ml.g6.16xlarge",
            .ml_g6_24_xlarge => "ml.g6.24xlarge",
            .ml_g6_48_xlarge => "ml.g6.48xlarge",
            .ml_g6_e_xlarge => "ml.g6e.xlarge",
            .ml_g6_e_2_xlarge => "ml.g6e.2xlarge",
            .ml_g6_e_4_xlarge => "ml.g6e.4xlarge",
            .ml_g6_e_8_xlarge => "ml.g6e.8xlarge",
            .ml_g6_e_12_xlarge => "ml.g6e.12xlarge",
            .ml_g6_e_16_xlarge => "ml.g6e.16xlarge",
            .ml_g6_e_24_xlarge => "ml.g6e.24xlarge",
            .ml_g6_e_48_xlarge => "ml.g6e.48xlarge",
            .ml_inf2_xlarge => "ml.inf2.xlarge",
            .ml_inf2_8_xlarge => "ml.inf2.8xlarge",
            .ml_inf2_24_xlarge => "ml.inf2.24xlarge",
            .ml_inf2_48_xlarge => "ml.inf2.48xlarge",
            .ml_trn1_2_xlarge => "ml.trn1.2xlarge",
            .ml_trn1_32_xlarge => "ml.trn1.32xlarge",
            .ml_trn1_n_32_xlarge => "ml.trn1n.32xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
