const PipelineExecutionStatus = @import("pipeline_execution_status.zig").PipelineExecutionStatus;

/// A pipeline execution summary.
pub const PipelineExecutionSummary = struct {
    /// The Amazon Resource Name (ARN) of the pipeline execution.
    pipeline_execution_arn: ?[]const u8,

    /// The description of the pipeline execution.
    pipeline_execution_description: ?[]const u8,

    /// The display name of the pipeline execution.
    pipeline_execution_display_name: ?[]const u8,

    /// A message generated by SageMaker Pipelines describing why the pipeline
    /// execution failed.
    pipeline_execution_failure_reason: ?[]const u8,

    /// The status of the pipeline execution.
    pipeline_execution_status: ?PipelineExecutionStatus,

    /// The start time of the pipeline execution.
    start_time: ?i64,

    pub const json_field_names = .{
        .pipeline_execution_arn = "PipelineExecutionArn",
        .pipeline_execution_description = "PipelineExecutionDescription",
        .pipeline_execution_display_name = "PipelineExecutionDisplayName",
        .pipeline_execution_failure_reason = "PipelineExecutionFailureReason",
        .pipeline_execution_status = "PipelineExecutionStatus",
        .start_time = "StartTime",
    };
};
