const std = @import("std");

pub const ProcessingInstanceType = enum {
    ml_t3_medium,
    ml_t3_large,
    ml_t3_xlarge,
    ml_t3_2_xlarge,
    ml_m4_xlarge,
    ml_m4_2_xlarge,
    ml_m4_4_xlarge,
    ml_m4_10_xlarge,
    ml_m4_16_xlarge,
    ml_c4_xlarge,
    ml_c4_2_xlarge,
    ml_c4_4_xlarge,
    ml_c4_8_xlarge,
    ml_p2_xlarge,
    ml_p2_8_xlarge,
    ml_p2_16_xlarge,
    ml_p3_2_xlarge,
    ml_p3_8_xlarge,
    ml_p3_16_xlarge,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_18_xlarge,
    ml_m5_large,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_12_xlarge,
    ml_m5_24_xlarge,
    ml_r5_large,
    ml_r5_xlarge,
    ml_r5_2_xlarge,
    ml_r5_4_xlarge,
    ml_r5_8_xlarge,
    ml_r5_12_xlarge,
    ml_r5_16_xlarge,
    ml_r5_24_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_g5_xlarge,
    ml_g5_2_xlarge,
    ml_g5_4_xlarge,
    ml_g5_8_xlarge,
    ml_g5_16_xlarge,
    ml_g5_12_xlarge,
    ml_g5_24_xlarge,
    ml_g5_48_xlarge,
    ml_r5_d_large,
    ml_r5_d_xlarge,
    ml_r5_d_2_xlarge,
    ml_r5_d_4_xlarge,
    ml_r5_d_8_xlarge,
    ml_r5_d_12_xlarge,
    ml_r5_d_16_xlarge,
    ml_r5_d_24_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_12_xlarge,
    ml_g6_16_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,
    ml_g6_e_xlarge,
    ml_g6_e_2_xlarge,
    ml_g6_e_4_xlarge,
    ml_g6_e_8_xlarge,
    ml_g6_e_12_xlarge,
    ml_g6_e_16_xlarge,
    ml_g6_e_24_xlarge,
    ml_g6_e_48_xlarge,
    ml_m6_i_large,
    ml_m6_i_xlarge,
    ml_m6_i_2_xlarge,
    ml_m6_i_4_xlarge,
    ml_m6_i_8_xlarge,
    ml_m6_i_12_xlarge,
    ml_m6_i_16_xlarge,
    ml_m6_i_24_xlarge,
    ml_m6_i_32_xlarge,
    ml_c6_i_xlarge,
    ml_c6_i_2_xlarge,
    ml_c6_i_4_xlarge,
    ml_c6_i_8_xlarge,
    ml_c6_i_12_xlarge,
    ml_c6_i_16_xlarge,
    ml_c6_i_24_xlarge,
    ml_c6_i_32_xlarge,
    ml_m7_i_large,
    ml_m7_i_xlarge,
    ml_m7_i_2_xlarge,
    ml_m7_i_4_xlarge,
    ml_m7_i_8_xlarge,
    ml_m7_i_12_xlarge,
    ml_m7_i_16_xlarge,
    ml_m7_i_24_xlarge,
    ml_m7_i_48_xlarge,
    ml_c7_i_large,
    ml_c7_i_xlarge,
    ml_c7_i_2_xlarge,
    ml_c7_i_4_xlarge,
    ml_c7_i_8_xlarge,
    ml_c7_i_12_xlarge,
    ml_c7_i_16_xlarge,
    ml_c7_i_24_xlarge,
    ml_c7_i_48_xlarge,
    ml_r7_i_large,
    ml_r7_i_xlarge,
    ml_r7_i_2_xlarge,
    ml_r7_i_4_xlarge,
    ml_r7_i_8_xlarge,
    ml_r7_i_12_xlarge,
    ml_r7_i_16_xlarge,
    ml_r7_i_24_xlarge,
    ml_r7_i_48_xlarge,
    ml_p5_4_xlarge,
    ml_g7_e_2_xlarge,
    ml_g7_e_4_xlarge,
    ml_g7_e_8_xlarge,
    ml_g7_e_12_xlarge,
    ml_g7_e_24_xlarge,
    ml_g7_e_48_xlarge,
    ml_g7_2_xlarge,
    ml_g7_4_xlarge,
    ml_g7_8_xlarge,
    ml_g7_12_xlarge,
    ml_g7_24_xlarge,
    ml_g7_48_xlarge,
    ml_r6_i_large,
    ml_r6_i_xlarge,
    ml_r6_i_2_xlarge,
    ml_r6_i_4_xlarge,
    ml_r6_i_8_xlarge,
    ml_r6_i_12_xlarge,
    ml_r6_i_16_xlarge,
    ml_r6_i_24_xlarge,
    ml_r6_i_32_xlarge,
    ml_m8_i_large,
    ml_m8_i_xlarge,
    ml_m8_i_2_xlarge,
    ml_m8_i_4_xlarge,
    ml_m8_i_8_xlarge,
    ml_m8_i_12_xlarge,
    ml_m8_i_16_xlarge,
    ml_m8_i_24_xlarge,
    ml_m8_i_32_xlarge,
    ml_m8_i_48_xlarge,
    ml_m8_i_96_xlarge,
    ml_c8_i_xlarge,
    ml_c8_i_2_xlarge,
    ml_c8_i_4_xlarge,
    ml_c8_i_8_xlarge,
    ml_c8_i_12_xlarge,
    ml_c8_i_16_xlarge,
    ml_c8_i_24_xlarge,
    ml_c8_i_32_xlarge,
    ml_c8_i_48_xlarge,
    ml_c8_i_96_xlarge,
    ml_r8_i_large,
    ml_r8_i_xlarge,
    ml_r8_i_2_xlarge,
    ml_r8_i_4_xlarge,
    ml_r8_i_8_xlarge,
    ml_r8_i_12_xlarge,
    ml_r8_i_16_xlarge,
    ml_r8_i_24_xlarge,
    ml_r8_i_32_xlarge,
    ml_r8_i_48_xlarge,
    ml_r8_i_96_xlarge,
    ml_m7_i_flex_large,
    ml_m7_i_flex_xlarge,
    ml_m7_i_flex_2_xlarge,
    ml_m7_i_flex_4_xlarge,
    ml_m7_i_flex_8_xlarge,
    ml_m7_i_flex_12_xlarge,
    ml_m7_i_flex_16_xlarge,
    ml_c7_i_flex_xlarge,
    ml_c7_i_flex_2_xlarge,
    ml_c7_i_flex_4_xlarge,
    ml_c7_i_flex_8_xlarge,
    ml_c7_i_flex_12_xlarge,
    ml_c7_i_flex_16_xlarge,
    ml_m8_i_flex_large,
    ml_m8_i_flex_xlarge,
    ml_m8_i_flex_2_xlarge,
    ml_m8_i_flex_4_xlarge,
    ml_m8_i_flex_8_xlarge,
    ml_m8_i_flex_12_xlarge,
    ml_m8_i_flex_16_xlarge,
    ml_c8_i_flex_xlarge,
    ml_c8_i_flex_2_xlarge,
    ml_c8_i_flex_4_xlarge,
    ml_c8_i_flex_8_xlarge,
    ml_c8_i_flex_12_xlarge,
    ml_c8_i_flex_16_xlarge,
    ml_r8_i_flex_large,
    ml_r8_i_flex_xlarge,
    ml_r8_i_flex_2_xlarge,
    ml_r8_i_flex_4_xlarge,
    ml_r8_i_flex_8_xlarge,
    ml_r8_i_flex_12_xlarge,
    ml_r8_i_flex_16_xlarge,

    pub const json_field_names = .{
        .ml_t3_medium = "ml.t3.medium",
        .ml_t3_large = "ml.t3.large",
        .ml_t3_xlarge = "ml.t3.xlarge",
        .ml_t3_2_xlarge = "ml.t3.2xlarge",
        .ml_m4_xlarge = "ml.m4.xlarge",
        .ml_m4_2_xlarge = "ml.m4.2xlarge",
        .ml_m4_4_xlarge = "ml.m4.4xlarge",
        .ml_m4_10_xlarge = "ml.m4.10xlarge",
        .ml_m4_16_xlarge = "ml.m4.16xlarge",
        .ml_c4_xlarge = "ml.c4.xlarge",
        .ml_c4_2_xlarge = "ml.c4.2xlarge",
        .ml_c4_4_xlarge = "ml.c4.4xlarge",
        .ml_c4_8_xlarge = "ml.c4.8xlarge",
        .ml_p2_xlarge = "ml.p2.xlarge",
        .ml_p2_8_xlarge = "ml.p2.8xlarge",
        .ml_p2_16_xlarge = "ml.p2.16xlarge",
        .ml_p3_2_xlarge = "ml.p3.2xlarge",
        .ml_p3_8_xlarge = "ml.p3.8xlarge",
        .ml_p3_16_xlarge = "ml.p3.16xlarge",
        .ml_c5_xlarge = "ml.c5.xlarge",
        .ml_c5_2_xlarge = "ml.c5.2xlarge",
        .ml_c5_4_xlarge = "ml.c5.4xlarge",
        .ml_c5_9_xlarge = "ml.c5.9xlarge",
        .ml_c5_18_xlarge = "ml.c5.18xlarge",
        .ml_m5_large = "ml.m5.large",
        .ml_m5_xlarge = "ml.m5.xlarge",
        .ml_m5_2_xlarge = "ml.m5.2xlarge",
        .ml_m5_4_xlarge = "ml.m5.4xlarge",
        .ml_m5_12_xlarge = "ml.m5.12xlarge",
        .ml_m5_24_xlarge = "ml.m5.24xlarge",
        .ml_r5_large = "ml.r5.large",
        .ml_r5_xlarge = "ml.r5.xlarge",
        .ml_r5_2_xlarge = "ml.r5.2xlarge",
        .ml_r5_4_xlarge = "ml.r5.4xlarge",
        .ml_r5_8_xlarge = "ml.r5.8xlarge",
        .ml_r5_12_xlarge = "ml.r5.12xlarge",
        .ml_r5_16_xlarge = "ml.r5.16xlarge",
        .ml_r5_24_xlarge = "ml.r5.24xlarge",
        .ml_g4_dn_xlarge = "ml.g4dn.xlarge",
        .ml_g4_dn_2_xlarge = "ml.g4dn.2xlarge",
        .ml_g4_dn_4_xlarge = "ml.g4dn.4xlarge",
        .ml_g4_dn_8_xlarge = "ml.g4dn.8xlarge",
        .ml_g4_dn_12_xlarge = "ml.g4dn.12xlarge",
        .ml_g4_dn_16_xlarge = "ml.g4dn.16xlarge",
        .ml_g5_xlarge = "ml.g5.xlarge",
        .ml_g5_2_xlarge = "ml.g5.2xlarge",
        .ml_g5_4_xlarge = "ml.g5.4xlarge",
        .ml_g5_8_xlarge = "ml.g5.8xlarge",
        .ml_g5_16_xlarge = "ml.g5.16xlarge",
        .ml_g5_12_xlarge = "ml.g5.12xlarge",
        .ml_g5_24_xlarge = "ml.g5.24xlarge",
        .ml_g5_48_xlarge = "ml.g5.48xlarge",
        .ml_r5_d_large = "ml.r5d.large",
        .ml_r5_d_xlarge = "ml.r5d.xlarge",
        .ml_r5_d_2_xlarge = "ml.r5d.2xlarge",
        .ml_r5_d_4_xlarge = "ml.r5d.4xlarge",
        .ml_r5_d_8_xlarge = "ml.r5d.8xlarge",
        .ml_r5_d_12_xlarge = "ml.r5d.12xlarge",
        .ml_r5_d_16_xlarge = "ml.r5d.16xlarge",
        .ml_r5_d_24_xlarge = "ml.r5d.24xlarge",
        .ml_g6_xlarge = "ml.g6.xlarge",
        .ml_g6_2_xlarge = "ml.g6.2xlarge",
        .ml_g6_4_xlarge = "ml.g6.4xlarge",
        .ml_g6_8_xlarge = "ml.g6.8xlarge",
        .ml_g6_12_xlarge = "ml.g6.12xlarge",
        .ml_g6_16_xlarge = "ml.g6.16xlarge",
        .ml_g6_24_xlarge = "ml.g6.24xlarge",
        .ml_g6_48_xlarge = "ml.g6.48xlarge",
        .ml_g6_e_xlarge = "ml.g6e.xlarge",
        .ml_g6_e_2_xlarge = "ml.g6e.2xlarge",
        .ml_g6_e_4_xlarge = "ml.g6e.4xlarge",
        .ml_g6_e_8_xlarge = "ml.g6e.8xlarge",
        .ml_g6_e_12_xlarge = "ml.g6e.12xlarge",
        .ml_g6_e_16_xlarge = "ml.g6e.16xlarge",
        .ml_g6_e_24_xlarge = "ml.g6e.24xlarge",
        .ml_g6_e_48_xlarge = "ml.g6e.48xlarge",
        .ml_m6_i_large = "ml.m6i.large",
        .ml_m6_i_xlarge = "ml.m6i.xlarge",
        .ml_m6_i_2_xlarge = "ml.m6i.2xlarge",
        .ml_m6_i_4_xlarge = "ml.m6i.4xlarge",
        .ml_m6_i_8_xlarge = "ml.m6i.8xlarge",
        .ml_m6_i_12_xlarge = "ml.m6i.12xlarge",
        .ml_m6_i_16_xlarge = "ml.m6i.16xlarge",
        .ml_m6_i_24_xlarge = "ml.m6i.24xlarge",
        .ml_m6_i_32_xlarge = "ml.m6i.32xlarge",
        .ml_c6_i_xlarge = "ml.c6i.xlarge",
        .ml_c6_i_2_xlarge = "ml.c6i.2xlarge",
        .ml_c6_i_4_xlarge = "ml.c6i.4xlarge",
        .ml_c6_i_8_xlarge = "ml.c6i.8xlarge",
        .ml_c6_i_12_xlarge = "ml.c6i.12xlarge",
        .ml_c6_i_16_xlarge = "ml.c6i.16xlarge",
        .ml_c6_i_24_xlarge = "ml.c6i.24xlarge",
        .ml_c6_i_32_xlarge = "ml.c6i.32xlarge",
        .ml_m7_i_large = "ml.m7i.large",
        .ml_m7_i_xlarge = "ml.m7i.xlarge",
        .ml_m7_i_2_xlarge = "ml.m7i.2xlarge",
        .ml_m7_i_4_xlarge = "ml.m7i.4xlarge",
        .ml_m7_i_8_xlarge = "ml.m7i.8xlarge",
        .ml_m7_i_12_xlarge = "ml.m7i.12xlarge",
        .ml_m7_i_16_xlarge = "ml.m7i.16xlarge",
        .ml_m7_i_24_xlarge = "ml.m7i.24xlarge",
        .ml_m7_i_48_xlarge = "ml.m7i.48xlarge",
        .ml_c7_i_large = "ml.c7i.large",
        .ml_c7_i_xlarge = "ml.c7i.xlarge",
        .ml_c7_i_2_xlarge = "ml.c7i.2xlarge",
        .ml_c7_i_4_xlarge = "ml.c7i.4xlarge",
        .ml_c7_i_8_xlarge = "ml.c7i.8xlarge",
        .ml_c7_i_12_xlarge = "ml.c7i.12xlarge",
        .ml_c7_i_16_xlarge = "ml.c7i.16xlarge",
        .ml_c7_i_24_xlarge = "ml.c7i.24xlarge",
        .ml_c7_i_48_xlarge = "ml.c7i.48xlarge",
        .ml_r7_i_large = "ml.r7i.large",
        .ml_r7_i_xlarge = "ml.r7i.xlarge",
        .ml_r7_i_2_xlarge = "ml.r7i.2xlarge",
        .ml_r7_i_4_xlarge = "ml.r7i.4xlarge",
        .ml_r7_i_8_xlarge = "ml.r7i.8xlarge",
        .ml_r7_i_12_xlarge = "ml.r7i.12xlarge",
        .ml_r7_i_16_xlarge = "ml.r7i.16xlarge",
        .ml_r7_i_24_xlarge = "ml.r7i.24xlarge",
        .ml_r7_i_48_xlarge = "ml.r7i.48xlarge",
        .ml_p5_4_xlarge = "ml.p5.4xlarge",
        .ml_g7_e_2_xlarge = "ml.g7e.2xlarge",
        .ml_g7_e_4_xlarge = "ml.g7e.4xlarge",
        .ml_g7_e_8_xlarge = "ml.g7e.8xlarge",
        .ml_g7_e_12_xlarge = "ml.g7e.12xlarge",
        .ml_g7_e_24_xlarge = "ml.g7e.24xlarge",
        .ml_g7_e_48_xlarge = "ml.g7e.48xlarge",
        .ml_g7_2_xlarge = "ml.g7.2xlarge",
        .ml_g7_4_xlarge = "ml.g7.4xlarge",
        .ml_g7_8_xlarge = "ml.g7.8xlarge",
        .ml_g7_12_xlarge = "ml.g7.12xlarge",
        .ml_g7_24_xlarge = "ml.g7.24xlarge",
        .ml_g7_48_xlarge = "ml.g7.48xlarge",
        .ml_r6_i_large = "ml.r6i.large",
        .ml_r6_i_xlarge = "ml.r6i.xlarge",
        .ml_r6_i_2_xlarge = "ml.r6i.2xlarge",
        .ml_r6_i_4_xlarge = "ml.r6i.4xlarge",
        .ml_r6_i_8_xlarge = "ml.r6i.8xlarge",
        .ml_r6_i_12_xlarge = "ml.r6i.12xlarge",
        .ml_r6_i_16_xlarge = "ml.r6i.16xlarge",
        .ml_r6_i_24_xlarge = "ml.r6i.24xlarge",
        .ml_r6_i_32_xlarge = "ml.r6i.32xlarge",
        .ml_m8_i_large = "ml.m8i.large",
        .ml_m8_i_xlarge = "ml.m8i.xlarge",
        .ml_m8_i_2_xlarge = "ml.m8i.2xlarge",
        .ml_m8_i_4_xlarge = "ml.m8i.4xlarge",
        .ml_m8_i_8_xlarge = "ml.m8i.8xlarge",
        .ml_m8_i_12_xlarge = "ml.m8i.12xlarge",
        .ml_m8_i_16_xlarge = "ml.m8i.16xlarge",
        .ml_m8_i_24_xlarge = "ml.m8i.24xlarge",
        .ml_m8_i_32_xlarge = "ml.m8i.32xlarge",
        .ml_m8_i_48_xlarge = "ml.m8i.48xlarge",
        .ml_m8_i_96_xlarge = "ml.m8i.96xlarge",
        .ml_c8_i_xlarge = "ml.c8i.xlarge",
        .ml_c8_i_2_xlarge = "ml.c8i.2xlarge",
        .ml_c8_i_4_xlarge = "ml.c8i.4xlarge",
        .ml_c8_i_8_xlarge = "ml.c8i.8xlarge",
        .ml_c8_i_12_xlarge = "ml.c8i.12xlarge",
        .ml_c8_i_16_xlarge = "ml.c8i.16xlarge",
        .ml_c8_i_24_xlarge = "ml.c8i.24xlarge",
        .ml_c8_i_32_xlarge = "ml.c8i.32xlarge",
        .ml_c8_i_48_xlarge = "ml.c8i.48xlarge",
        .ml_c8_i_96_xlarge = "ml.c8i.96xlarge",
        .ml_r8_i_large = "ml.r8i.large",
        .ml_r8_i_xlarge = "ml.r8i.xlarge",
        .ml_r8_i_2_xlarge = "ml.r8i.2xlarge",
        .ml_r8_i_4_xlarge = "ml.r8i.4xlarge",
        .ml_r8_i_8_xlarge = "ml.r8i.8xlarge",
        .ml_r8_i_12_xlarge = "ml.r8i.12xlarge",
        .ml_r8_i_16_xlarge = "ml.r8i.16xlarge",
        .ml_r8_i_24_xlarge = "ml.r8i.24xlarge",
        .ml_r8_i_32_xlarge = "ml.r8i.32xlarge",
        .ml_r8_i_48_xlarge = "ml.r8i.48xlarge",
        .ml_r8_i_96_xlarge = "ml.r8i.96xlarge",
        .ml_m7_i_flex_large = "ml.m7i-flex.large",
        .ml_m7_i_flex_xlarge = "ml.m7i-flex.xlarge",
        .ml_m7_i_flex_2_xlarge = "ml.m7i-flex.2xlarge",
        .ml_m7_i_flex_4_xlarge = "ml.m7i-flex.4xlarge",
        .ml_m7_i_flex_8_xlarge = "ml.m7i-flex.8xlarge",
        .ml_m7_i_flex_12_xlarge = "ml.m7i-flex.12xlarge",
        .ml_m7_i_flex_16_xlarge = "ml.m7i-flex.16xlarge",
        .ml_c7_i_flex_xlarge = "ml.c7i-flex.xlarge",
        .ml_c7_i_flex_2_xlarge = "ml.c7i-flex.2xlarge",
        .ml_c7_i_flex_4_xlarge = "ml.c7i-flex.4xlarge",
        .ml_c7_i_flex_8_xlarge = "ml.c7i-flex.8xlarge",
        .ml_c7_i_flex_12_xlarge = "ml.c7i-flex.12xlarge",
        .ml_c7_i_flex_16_xlarge = "ml.c7i-flex.16xlarge",
        .ml_m8_i_flex_large = "ml.m8i-flex.large",
        .ml_m8_i_flex_xlarge = "ml.m8i-flex.xlarge",
        .ml_m8_i_flex_2_xlarge = "ml.m8i-flex.2xlarge",
        .ml_m8_i_flex_4_xlarge = "ml.m8i-flex.4xlarge",
        .ml_m8_i_flex_8_xlarge = "ml.m8i-flex.8xlarge",
        .ml_m8_i_flex_12_xlarge = "ml.m8i-flex.12xlarge",
        .ml_m8_i_flex_16_xlarge = "ml.m8i-flex.16xlarge",
        .ml_c8_i_flex_xlarge = "ml.c8i-flex.xlarge",
        .ml_c8_i_flex_2_xlarge = "ml.c8i-flex.2xlarge",
        .ml_c8_i_flex_4_xlarge = "ml.c8i-flex.4xlarge",
        .ml_c8_i_flex_8_xlarge = "ml.c8i-flex.8xlarge",
        .ml_c8_i_flex_12_xlarge = "ml.c8i-flex.12xlarge",
        .ml_c8_i_flex_16_xlarge = "ml.c8i-flex.16xlarge",
        .ml_r8_i_flex_large = "ml.r8i-flex.large",
        .ml_r8_i_flex_xlarge = "ml.r8i-flex.xlarge",
        .ml_r8_i_flex_2_xlarge = "ml.r8i-flex.2xlarge",
        .ml_r8_i_flex_4_xlarge = "ml.r8i-flex.4xlarge",
        .ml_r8_i_flex_8_xlarge = "ml.r8i-flex.8xlarge",
        .ml_r8_i_flex_12_xlarge = "ml.r8i-flex.12xlarge",
        .ml_r8_i_flex_16_xlarge = "ml.r8i-flex.16xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .ml_t3_medium => "ml.t3.medium",
            .ml_t3_large => "ml.t3.large",
            .ml_t3_xlarge => "ml.t3.xlarge",
            .ml_t3_2_xlarge => "ml.t3.2xlarge",
            .ml_m4_xlarge => "ml.m4.xlarge",
            .ml_m4_2_xlarge => "ml.m4.2xlarge",
            .ml_m4_4_xlarge => "ml.m4.4xlarge",
            .ml_m4_10_xlarge => "ml.m4.10xlarge",
            .ml_m4_16_xlarge => "ml.m4.16xlarge",
            .ml_c4_xlarge => "ml.c4.xlarge",
            .ml_c4_2_xlarge => "ml.c4.2xlarge",
            .ml_c4_4_xlarge => "ml.c4.4xlarge",
            .ml_c4_8_xlarge => "ml.c4.8xlarge",
            .ml_p2_xlarge => "ml.p2.xlarge",
            .ml_p2_8_xlarge => "ml.p2.8xlarge",
            .ml_p2_16_xlarge => "ml.p2.16xlarge",
            .ml_p3_2_xlarge => "ml.p3.2xlarge",
            .ml_p3_8_xlarge => "ml.p3.8xlarge",
            .ml_p3_16_xlarge => "ml.p3.16xlarge",
            .ml_c5_xlarge => "ml.c5.xlarge",
            .ml_c5_2_xlarge => "ml.c5.2xlarge",
            .ml_c5_4_xlarge => "ml.c5.4xlarge",
            .ml_c5_9_xlarge => "ml.c5.9xlarge",
            .ml_c5_18_xlarge => "ml.c5.18xlarge",
            .ml_m5_large => "ml.m5.large",
            .ml_m5_xlarge => "ml.m5.xlarge",
            .ml_m5_2_xlarge => "ml.m5.2xlarge",
            .ml_m5_4_xlarge => "ml.m5.4xlarge",
            .ml_m5_12_xlarge => "ml.m5.12xlarge",
            .ml_m5_24_xlarge => "ml.m5.24xlarge",
            .ml_r5_large => "ml.r5.large",
            .ml_r5_xlarge => "ml.r5.xlarge",
            .ml_r5_2_xlarge => "ml.r5.2xlarge",
            .ml_r5_4_xlarge => "ml.r5.4xlarge",
            .ml_r5_8_xlarge => "ml.r5.8xlarge",
            .ml_r5_12_xlarge => "ml.r5.12xlarge",
            .ml_r5_16_xlarge => "ml.r5.16xlarge",
            .ml_r5_24_xlarge => "ml.r5.24xlarge",
            .ml_g4_dn_xlarge => "ml.g4dn.xlarge",
            .ml_g4_dn_2_xlarge => "ml.g4dn.2xlarge",
            .ml_g4_dn_4_xlarge => "ml.g4dn.4xlarge",
            .ml_g4_dn_8_xlarge => "ml.g4dn.8xlarge",
            .ml_g4_dn_12_xlarge => "ml.g4dn.12xlarge",
            .ml_g4_dn_16_xlarge => "ml.g4dn.16xlarge",
            .ml_g5_xlarge => "ml.g5.xlarge",
            .ml_g5_2_xlarge => "ml.g5.2xlarge",
            .ml_g5_4_xlarge => "ml.g5.4xlarge",
            .ml_g5_8_xlarge => "ml.g5.8xlarge",
            .ml_g5_16_xlarge => "ml.g5.16xlarge",
            .ml_g5_12_xlarge => "ml.g5.12xlarge",
            .ml_g5_24_xlarge => "ml.g5.24xlarge",
            .ml_g5_48_xlarge => "ml.g5.48xlarge",
            .ml_r5_d_large => "ml.r5d.large",
            .ml_r5_d_xlarge => "ml.r5d.xlarge",
            .ml_r5_d_2_xlarge => "ml.r5d.2xlarge",
            .ml_r5_d_4_xlarge => "ml.r5d.4xlarge",
            .ml_r5_d_8_xlarge => "ml.r5d.8xlarge",
            .ml_r5_d_12_xlarge => "ml.r5d.12xlarge",
            .ml_r5_d_16_xlarge => "ml.r5d.16xlarge",
            .ml_r5_d_24_xlarge => "ml.r5d.24xlarge",
            .ml_g6_xlarge => "ml.g6.xlarge",
            .ml_g6_2_xlarge => "ml.g6.2xlarge",
            .ml_g6_4_xlarge => "ml.g6.4xlarge",
            .ml_g6_8_xlarge => "ml.g6.8xlarge",
            .ml_g6_12_xlarge => "ml.g6.12xlarge",
            .ml_g6_16_xlarge => "ml.g6.16xlarge",
            .ml_g6_24_xlarge => "ml.g6.24xlarge",
            .ml_g6_48_xlarge => "ml.g6.48xlarge",
            .ml_g6_e_xlarge => "ml.g6e.xlarge",
            .ml_g6_e_2_xlarge => "ml.g6e.2xlarge",
            .ml_g6_e_4_xlarge => "ml.g6e.4xlarge",
            .ml_g6_e_8_xlarge => "ml.g6e.8xlarge",
            .ml_g6_e_12_xlarge => "ml.g6e.12xlarge",
            .ml_g6_e_16_xlarge => "ml.g6e.16xlarge",
            .ml_g6_e_24_xlarge => "ml.g6e.24xlarge",
            .ml_g6_e_48_xlarge => "ml.g6e.48xlarge",
            .ml_m6_i_large => "ml.m6i.large",
            .ml_m6_i_xlarge => "ml.m6i.xlarge",
            .ml_m6_i_2_xlarge => "ml.m6i.2xlarge",
            .ml_m6_i_4_xlarge => "ml.m6i.4xlarge",
            .ml_m6_i_8_xlarge => "ml.m6i.8xlarge",
            .ml_m6_i_12_xlarge => "ml.m6i.12xlarge",
            .ml_m6_i_16_xlarge => "ml.m6i.16xlarge",
            .ml_m6_i_24_xlarge => "ml.m6i.24xlarge",
            .ml_m6_i_32_xlarge => "ml.m6i.32xlarge",
            .ml_c6_i_xlarge => "ml.c6i.xlarge",
            .ml_c6_i_2_xlarge => "ml.c6i.2xlarge",
            .ml_c6_i_4_xlarge => "ml.c6i.4xlarge",
            .ml_c6_i_8_xlarge => "ml.c6i.8xlarge",
            .ml_c6_i_12_xlarge => "ml.c6i.12xlarge",
            .ml_c6_i_16_xlarge => "ml.c6i.16xlarge",
            .ml_c6_i_24_xlarge => "ml.c6i.24xlarge",
            .ml_c6_i_32_xlarge => "ml.c6i.32xlarge",
            .ml_m7_i_large => "ml.m7i.large",
            .ml_m7_i_xlarge => "ml.m7i.xlarge",
            .ml_m7_i_2_xlarge => "ml.m7i.2xlarge",
            .ml_m7_i_4_xlarge => "ml.m7i.4xlarge",
            .ml_m7_i_8_xlarge => "ml.m7i.8xlarge",
            .ml_m7_i_12_xlarge => "ml.m7i.12xlarge",
            .ml_m7_i_16_xlarge => "ml.m7i.16xlarge",
            .ml_m7_i_24_xlarge => "ml.m7i.24xlarge",
            .ml_m7_i_48_xlarge => "ml.m7i.48xlarge",
            .ml_c7_i_large => "ml.c7i.large",
            .ml_c7_i_xlarge => "ml.c7i.xlarge",
            .ml_c7_i_2_xlarge => "ml.c7i.2xlarge",
            .ml_c7_i_4_xlarge => "ml.c7i.4xlarge",
            .ml_c7_i_8_xlarge => "ml.c7i.8xlarge",
            .ml_c7_i_12_xlarge => "ml.c7i.12xlarge",
            .ml_c7_i_16_xlarge => "ml.c7i.16xlarge",
            .ml_c7_i_24_xlarge => "ml.c7i.24xlarge",
            .ml_c7_i_48_xlarge => "ml.c7i.48xlarge",
            .ml_r7_i_large => "ml.r7i.large",
            .ml_r7_i_xlarge => "ml.r7i.xlarge",
            .ml_r7_i_2_xlarge => "ml.r7i.2xlarge",
            .ml_r7_i_4_xlarge => "ml.r7i.4xlarge",
            .ml_r7_i_8_xlarge => "ml.r7i.8xlarge",
            .ml_r7_i_12_xlarge => "ml.r7i.12xlarge",
            .ml_r7_i_16_xlarge => "ml.r7i.16xlarge",
            .ml_r7_i_24_xlarge => "ml.r7i.24xlarge",
            .ml_r7_i_48_xlarge => "ml.r7i.48xlarge",
            .ml_p5_4_xlarge => "ml.p5.4xlarge",
            .ml_g7_e_2_xlarge => "ml.g7e.2xlarge",
            .ml_g7_e_4_xlarge => "ml.g7e.4xlarge",
            .ml_g7_e_8_xlarge => "ml.g7e.8xlarge",
            .ml_g7_e_12_xlarge => "ml.g7e.12xlarge",
            .ml_g7_e_24_xlarge => "ml.g7e.24xlarge",
            .ml_g7_e_48_xlarge => "ml.g7e.48xlarge",
            .ml_g7_2_xlarge => "ml.g7.2xlarge",
            .ml_g7_4_xlarge => "ml.g7.4xlarge",
            .ml_g7_8_xlarge => "ml.g7.8xlarge",
            .ml_g7_12_xlarge => "ml.g7.12xlarge",
            .ml_g7_24_xlarge => "ml.g7.24xlarge",
            .ml_g7_48_xlarge => "ml.g7.48xlarge",
            .ml_r6_i_large => "ml.r6i.large",
            .ml_r6_i_xlarge => "ml.r6i.xlarge",
            .ml_r6_i_2_xlarge => "ml.r6i.2xlarge",
            .ml_r6_i_4_xlarge => "ml.r6i.4xlarge",
            .ml_r6_i_8_xlarge => "ml.r6i.8xlarge",
            .ml_r6_i_12_xlarge => "ml.r6i.12xlarge",
            .ml_r6_i_16_xlarge => "ml.r6i.16xlarge",
            .ml_r6_i_24_xlarge => "ml.r6i.24xlarge",
            .ml_r6_i_32_xlarge => "ml.r6i.32xlarge",
            .ml_m8_i_large => "ml.m8i.large",
            .ml_m8_i_xlarge => "ml.m8i.xlarge",
            .ml_m8_i_2_xlarge => "ml.m8i.2xlarge",
            .ml_m8_i_4_xlarge => "ml.m8i.4xlarge",
            .ml_m8_i_8_xlarge => "ml.m8i.8xlarge",
            .ml_m8_i_12_xlarge => "ml.m8i.12xlarge",
            .ml_m8_i_16_xlarge => "ml.m8i.16xlarge",
            .ml_m8_i_24_xlarge => "ml.m8i.24xlarge",
            .ml_m8_i_32_xlarge => "ml.m8i.32xlarge",
            .ml_m8_i_48_xlarge => "ml.m8i.48xlarge",
            .ml_m8_i_96_xlarge => "ml.m8i.96xlarge",
            .ml_c8_i_xlarge => "ml.c8i.xlarge",
            .ml_c8_i_2_xlarge => "ml.c8i.2xlarge",
            .ml_c8_i_4_xlarge => "ml.c8i.4xlarge",
            .ml_c8_i_8_xlarge => "ml.c8i.8xlarge",
            .ml_c8_i_12_xlarge => "ml.c8i.12xlarge",
            .ml_c8_i_16_xlarge => "ml.c8i.16xlarge",
            .ml_c8_i_24_xlarge => "ml.c8i.24xlarge",
            .ml_c8_i_32_xlarge => "ml.c8i.32xlarge",
            .ml_c8_i_48_xlarge => "ml.c8i.48xlarge",
            .ml_c8_i_96_xlarge => "ml.c8i.96xlarge",
            .ml_r8_i_large => "ml.r8i.large",
            .ml_r8_i_xlarge => "ml.r8i.xlarge",
            .ml_r8_i_2_xlarge => "ml.r8i.2xlarge",
            .ml_r8_i_4_xlarge => "ml.r8i.4xlarge",
            .ml_r8_i_8_xlarge => "ml.r8i.8xlarge",
            .ml_r8_i_12_xlarge => "ml.r8i.12xlarge",
            .ml_r8_i_16_xlarge => "ml.r8i.16xlarge",
            .ml_r8_i_24_xlarge => "ml.r8i.24xlarge",
            .ml_r8_i_32_xlarge => "ml.r8i.32xlarge",
            .ml_r8_i_48_xlarge => "ml.r8i.48xlarge",
            .ml_r8_i_96_xlarge => "ml.r8i.96xlarge",
            .ml_m7_i_flex_large => "ml.m7i-flex.large",
            .ml_m7_i_flex_xlarge => "ml.m7i-flex.xlarge",
            .ml_m7_i_flex_2_xlarge => "ml.m7i-flex.2xlarge",
            .ml_m7_i_flex_4_xlarge => "ml.m7i-flex.4xlarge",
            .ml_m7_i_flex_8_xlarge => "ml.m7i-flex.8xlarge",
            .ml_m7_i_flex_12_xlarge => "ml.m7i-flex.12xlarge",
            .ml_m7_i_flex_16_xlarge => "ml.m7i-flex.16xlarge",
            .ml_c7_i_flex_xlarge => "ml.c7i-flex.xlarge",
            .ml_c7_i_flex_2_xlarge => "ml.c7i-flex.2xlarge",
            .ml_c7_i_flex_4_xlarge => "ml.c7i-flex.4xlarge",
            .ml_c7_i_flex_8_xlarge => "ml.c7i-flex.8xlarge",
            .ml_c7_i_flex_12_xlarge => "ml.c7i-flex.12xlarge",
            .ml_c7_i_flex_16_xlarge => "ml.c7i-flex.16xlarge",
            .ml_m8_i_flex_large => "ml.m8i-flex.large",
            .ml_m8_i_flex_xlarge => "ml.m8i-flex.xlarge",
            .ml_m8_i_flex_2_xlarge => "ml.m8i-flex.2xlarge",
            .ml_m8_i_flex_4_xlarge => "ml.m8i-flex.4xlarge",
            .ml_m8_i_flex_8_xlarge => "ml.m8i-flex.8xlarge",
            .ml_m8_i_flex_12_xlarge => "ml.m8i-flex.12xlarge",
            .ml_m8_i_flex_16_xlarge => "ml.m8i-flex.16xlarge",
            .ml_c8_i_flex_xlarge => "ml.c8i-flex.xlarge",
            .ml_c8_i_flex_2_xlarge => "ml.c8i-flex.2xlarge",
            .ml_c8_i_flex_4_xlarge => "ml.c8i-flex.4xlarge",
            .ml_c8_i_flex_8_xlarge => "ml.c8i-flex.8xlarge",
            .ml_c8_i_flex_12_xlarge => "ml.c8i-flex.12xlarge",
            .ml_c8_i_flex_16_xlarge => "ml.c8i-flex.16xlarge",
            .ml_r8_i_flex_large => "ml.r8i-flex.large",
            .ml_r8_i_flex_xlarge => "ml.r8i-flex.xlarge",
            .ml_r8_i_flex_2_xlarge => "ml.r8i-flex.2xlarge",
            .ml_r8_i_flex_4_xlarge => "ml.r8i-flex.4xlarge",
            .ml_r8_i_flex_8_xlarge => "ml.r8i-flex.8xlarge",
            .ml_r8_i_flex_12_xlarge => "ml.r8i-flex.12xlarge",
            .ml_r8_i_flex_16_xlarge => "ml.r8i-flex.16xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        const fields = @typeInfo(@TypeOf(json_field_names)).@"struct".field_names;
        inline for (fields) |field_name| {
            if (std.mem.eql(u8, str, @field(json_field_names, field_name))) {
                return @field(@This(), field_name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
