pub const ProductionVariantInstanceType = enum {
    ml_t2_medium,
    ml_t2_large,
    ml_t2_xlarge,
    ml_t2_2_xlarge,
    ml_m4_xlarge,
    ml_m4_2_xlarge,
    ml_m4_4_xlarge,
    ml_m4_10_xlarge,
    ml_m4_16_xlarge,
    ml_m5_large,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_12_xlarge,
    ml_m5_24_xlarge,
    ml_m5_d_large,
    ml_m5_d_xlarge,
    ml_m5_d_2_xlarge,
    ml_m5_d_4_xlarge,
    ml_m5_d_12_xlarge,
    ml_m5_d_24_xlarge,
    ml_c4_large,
    ml_c4_xlarge,
    ml_c4_2_xlarge,
    ml_c4_4_xlarge,
    ml_c4_8_xlarge,
    ml_p2_xlarge,
    ml_p2_8_xlarge,
    ml_p2_16_xlarge,
    ml_p3_2_xlarge,
    ml_p3_8_xlarge,
    ml_p3_16_xlarge,
    ml_c5_large,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_18_xlarge,
    ml_c5_d_large,
    ml_c5_d_xlarge,
    ml_c5_d_2_xlarge,
    ml_c5_d_4_xlarge,
    ml_c5_d_9_xlarge,
    ml_c5_d_18_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_r5_large,
    ml_r5_xlarge,
    ml_r5_2_xlarge,
    ml_r5_4_xlarge,
    ml_r5_12_xlarge,
    ml_r5_24_xlarge,
    ml_r5_d_large,
    ml_r5_d_xlarge,
    ml_r5_d_2_xlarge,
    ml_r5_d_4_xlarge,
    ml_r5_d_12_xlarge,
    ml_r5_d_24_xlarge,
    ml_inf1_xlarge,
    ml_inf1_2_xlarge,
    ml_inf1_6_xlarge,
    ml_inf1_24_xlarge,
    ml_dl1_24_xlarge,
    ml_c6_i_large,
    ml_c6_i_xlarge,
    ml_c6_i_2_xlarge,
    ml_c6_i_4_xlarge,
    ml_c6_i_8_xlarge,
    ml_c6_i_12_xlarge,
    ml_c6_i_16_xlarge,
    ml_c6_i_24_xlarge,
    ml_c6_i_32_xlarge,
    ml_m6_i_large,
    ml_m6_i_xlarge,
    ml_m6_i_2_xlarge,
    ml_m6_i_4_xlarge,
    ml_m6_i_8_xlarge,
    ml_m6_i_12_xlarge,
    ml_m6_i_16_xlarge,
    ml_m6_i_24_xlarge,
    ml_m6_i_32_xlarge,
    ml_r6_i_large,
    ml_r6_i_xlarge,
    ml_r6_i_2_xlarge,
    ml_r6_i_4_xlarge,
    ml_r6_i_8_xlarge,
    ml_r6_i_12_xlarge,
    ml_r6_i_16_xlarge,
    ml_r6_i_24_xlarge,
    ml_r6_i_32_xlarge,
    ml_g5_xlarge,
    ml_g5_2_xlarge,
    ml_g5_4_xlarge,
    ml_g5_8_xlarge,
    ml_g5_12_xlarge,
    ml_g5_16_xlarge,
    ml_g5_24_xlarge,
    ml_g5_48_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_12_xlarge,
    ml_g6_16_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,
    ml_r8_g_medium,
    ml_r8_g_large,
    ml_r8_g_xlarge,
    ml_r8_g_2_xlarge,
    ml_r8_g_4_xlarge,
    ml_r8_g_8_xlarge,
    ml_r8_g_12_xlarge,
    ml_r8_g_16_xlarge,
    ml_r8_g_24_xlarge,
    ml_r8_g_48_xlarge,
    ml_g6_e_xlarge,
    ml_g6_e_2_xlarge,
    ml_g6_e_4_xlarge,
    ml_g6_e_8_xlarge,
    ml_g6_e_12_xlarge,
    ml_g6_e_16_xlarge,
    ml_g6_e_24_xlarge,
    ml_g6_e_48_xlarge,
    ml_p4_d_24_xlarge,
    ml_c7_g_large,
    ml_c7_g_xlarge,
    ml_c7_g_2_xlarge,
    ml_c7_g_4_xlarge,
    ml_c7_g_8_xlarge,
    ml_c7_g_12_xlarge,
    ml_c7_g_16_xlarge,
    ml_m6_g_large,
    ml_m6_g_xlarge,
    ml_m6_g_2_xlarge,
    ml_m6_g_4_xlarge,
    ml_m6_g_8_xlarge,
    ml_m6_g_12_xlarge,
    ml_m6_g_16_xlarge,
    ml_m6_gd_large,
    ml_m6_gd_xlarge,
    ml_m6_gd_2_xlarge,
    ml_m6_gd_4_xlarge,
    ml_m6_gd_8_xlarge,
    ml_m6_gd_12_xlarge,
    ml_m6_gd_16_xlarge,
    ml_c6_g_large,
    ml_c6_g_xlarge,
    ml_c6_g_2_xlarge,
    ml_c6_g_4_xlarge,
    ml_c6_g_8_xlarge,
    ml_c6_g_12_xlarge,
    ml_c6_g_16_xlarge,
    ml_c6_gd_large,
    ml_c6_gd_xlarge,
    ml_c6_gd_2_xlarge,
    ml_c6_gd_4_xlarge,
    ml_c6_gd_8_xlarge,
    ml_c6_gd_12_xlarge,
    ml_c6_gd_16_xlarge,
    ml_c6_gn_large,
    ml_c6_gn_xlarge,
    ml_c6_gn_2_xlarge,
    ml_c6_gn_4_xlarge,
    ml_c6_gn_8_xlarge,
    ml_c6_gn_12_xlarge,
    ml_c6_gn_16_xlarge,
    ml_r6_g_large,
    ml_r6_g_xlarge,
    ml_r6_g_2_xlarge,
    ml_r6_g_4_xlarge,
    ml_r6_g_8_xlarge,
    ml_r6_g_12_xlarge,
    ml_r6_g_16_xlarge,
    ml_r6_gd_large,
    ml_r6_gd_xlarge,
    ml_r6_gd_2_xlarge,
    ml_r6_gd_4_xlarge,
    ml_r6_gd_8_xlarge,
    ml_r6_gd_12_xlarge,
    ml_r6_gd_16_xlarge,
    ml_p4_de_24_xlarge,
    ml_trn1_2_xlarge,
    ml_trn1_32_xlarge,
    ml_trn1_n_32_xlarge,
    ml_trn2_48_xlarge,
    ml_inf2_xlarge,
    ml_inf2_8_xlarge,
    ml_inf2_24_xlarge,
    ml_inf2_48_xlarge,
    ml_p5_48_xlarge,
    ml_p5_e_48_xlarge,
    ml_p5_en_48_xlarge,
    ml_m7_i_large,
    ml_m7_i_xlarge,
    ml_m7_i_2_xlarge,
    ml_m7_i_4_xlarge,
    ml_m7_i_8_xlarge,
    ml_m7_i_12_xlarge,
    ml_m7_i_16_xlarge,
    ml_m7_i_24_xlarge,
    ml_m7_i_48_xlarge,
    ml_c7_i_large,
    ml_c7_i_xlarge,
    ml_c7_i_2_xlarge,
    ml_c7_i_4_xlarge,
    ml_c7_i_8_xlarge,
    ml_c7_i_12_xlarge,
    ml_c7_i_16_xlarge,
    ml_c7_i_24_xlarge,
    ml_c7_i_48_xlarge,
    ml_r7_i_large,
    ml_r7_i_xlarge,
    ml_r7_i_2_xlarge,
    ml_r7_i_4_xlarge,
    ml_r7_i_8_xlarge,
    ml_r7_i_12_xlarge,
    ml_r7_i_16_xlarge,
    ml_r7_i_24_xlarge,
    ml_r7_i_48_xlarge,
    ml_c8_g_medium,
    ml_c8_g_large,
    ml_c8_g_xlarge,
    ml_c8_g_2_xlarge,
    ml_c8_g_4_xlarge,
    ml_c8_g_8_xlarge,
    ml_c8_g_12_xlarge,
    ml_c8_g_16_xlarge,
    ml_c8_g_24_xlarge,
    ml_c8_g_48_xlarge,
    ml_r7_gd_medium,
    ml_r7_gd_large,
    ml_r7_gd_xlarge,
    ml_r7_gd_2_xlarge,
    ml_r7_gd_4_xlarge,
    ml_r7_gd_8_xlarge,
    ml_r7_gd_12_xlarge,
    ml_r7_gd_16_xlarge,
    ml_m8_g_medium,
    ml_m8_g_large,
    ml_m8_g_xlarge,
    ml_m8_g_2_xlarge,
    ml_m8_g_4_xlarge,
    ml_m8_g_8_xlarge,
    ml_m8_g_12_xlarge,
    ml_m8_g_16_xlarge,
    ml_m8_g_24_xlarge,
    ml_m8_g_48_xlarge,
    ml_c6_in_large,
    ml_c6_in_xlarge,
    ml_c6_in_2_xlarge,
    ml_c6_in_4_xlarge,
    ml_c6_in_8_xlarge,
    ml_c6_in_12_xlarge,
    ml_c6_in_16_xlarge,
    ml_c6_in_24_xlarge,
    ml_c6_in_32_xlarge,
    ml_p6_b200_48_xlarge,
    ml_p6_e_gb200_36_xlarge,
    ml_p5_4_xlarge,

    pub const json_field_names = .{
        .ml_t2_medium = "ML_T2_MEDIUM",
        .ml_t2_large = "ML_T2_LARGE",
        .ml_t2_xlarge = "ML_T2_XLARGE",
        .ml_t2_2_xlarge = "ML_T2_2XLARGE",
        .ml_m4_xlarge = "ML_M4_XLARGE",
        .ml_m4_2_xlarge = "ML_M4_2XLARGE",
        .ml_m4_4_xlarge = "ML_M4_4XLARGE",
        .ml_m4_10_xlarge = "ML_M4_10XLARGE",
        .ml_m4_16_xlarge = "ML_M4_16XLARGE",
        .ml_m5_large = "ML_M5_LARGE",
        .ml_m5_xlarge = "ML_M5_XLARGE",
        .ml_m5_2_xlarge = "ML_M5_2XLARGE",
        .ml_m5_4_xlarge = "ML_M5_4XLARGE",
        .ml_m5_12_xlarge = "ML_M5_12XLARGE",
        .ml_m5_24_xlarge = "ML_M5_24XLARGE",
        .ml_m5_d_large = "ML_M5D_LARGE",
        .ml_m5_d_xlarge = "ML_M5D_XLARGE",
        .ml_m5_d_2_xlarge = "ML_M5D_2XLARGE",
        .ml_m5_d_4_xlarge = "ML_M5D_4XLARGE",
        .ml_m5_d_12_xlarge = "ML_M5D_12XLARGE",
        .ml_m5_d_24_xlarge = "ML_M5D_24XLARGE",
        .ml_c4_large = "ML_C4_LARGE",
        .ml_c4_xlarge = "ML_C4_XLARGE",
        .ml_c4_2_xlarge = "ML_C4_2XLARGE",
        .ml_c4_4_xlarge = "ML_C4_4XLARGE",
        .ml_c4_8_xlarge = "ML_C4_8XLARGE",
        .ml_p2_xlarge = "ML_P2_XLARGE",
        .ml_p2_8_xlarge = "ML_P2_8XLARGE",
        .ml_p2_16_xlarge = "ML_P2_16XLARGE",
        .ml_p3_2_xlarge = "ML_P3_2XLARGE",
        .ml_p3_8_xlarge = "ML_P3_8XLARGE",
        .ml_p3_16_xlarge = "ML_P3_16XLARGE",
        .ml_c5_large = "ML_C5_LARGE",
        .ml_c5_xlarge = "ML_C5_XLARGE",
        .ml_c5_2_xlarge = "ML_C5_2XLARGE",
        .ml_c5_4_xlarge = "ML_C5_4XLARGE",
        .ml_c5_9_xlarge = "ML_C5_9XLARGE",
        .ml_c5_18_xlarge = "ML_C5_18XLARGE",
        .ml_c5_d_large = "ML_C5D_LARGE",
        .ml_c5_d_xlarge = "ML_C5D_XLARGE",
        .ml_c5_d_2_xlarge = "ML_C5D_2XLARGE",
        .ml_c5_d_4_xlarge = "ML_C5D_4XLARGE",
        .ml_c5_d_9_xlarge = "ML_C5D_9XLARGE",
        .ml_c5_d_18_xlarge = "ML_C5D_18XLARGE",
        .ml_g4_dn_xlarge = "ML_G4DN_XLARGE",
        .ml_g4_dn_2_xlarge = "ML_G4DN_2XLARGE",
        .ml_g4_dn_4_xlarge = "ML_G4DN_4XLARGE",
        .ml_g4_dn_8_xlarge = "ML_G4DN_8XLARGE",
        .ml_g4_dn_12_xlarge = "ML_G4DN_12XLARGE",
        .ml_g4_dn_16_xlarge = "ML_G4DN_16XLARGE",
        .ml_r5_large = "ML_R5_LARGE",
        .ml_r5_xlarge = "ML_R5_XLARGE",
        .ml_r5_2_xlarge = "ML_R5_2XLARGE",
        .ml_r5_4_xlarge = "ML_R5_4XLARGE",
        .ml_r5_12_xlarge = "ML_R5_12XLARGE",
        .ml_r5_24_xlarge = "ML_R5_24XLARGE",
        .ml_r5_d_large = "ML_R5D_LARGE",
        .ml_r5_d_xlarge = "ML_R5D_XLARGE",
        .ml_r5_d_2_xlarge = "ML_R5D_2XLARGE",
        .ml_r5_d_4_xlarge = "ML_R5D_4XLARGE",
        .ml_r5_d_12_xlarge = "ML_R5D_12XLARGE",
        .ml_r5_d_24_xlarge = "ML_R5D_24XLARGE",
        .ml_inf1_xlarge = "ML_INF1_XLARGE",
        .ml_inf1_2_xlarge = "ML_INF1_2XLARGE",
        .ml_inf1_6_xlarge = "ML_INF1_6XLARGE",
        .ml_inf1_24_xlarge = "ML_INF1_24XLARGE",
        .ml_dl1_24_xlarge = "ML_DL1_24XLARGE",
        .ml_c6_i_large = "ML_C6I_LARGE",
        .ml_c6_i_xlarge = "ML_C6I_XLARGE",
        .ml_c6_i_2_xlarge = "ML_C6I_2XLARGE",
        .ml_c6_i_4_xlarge = "ML_C6I_4XLARGE",
        .ml_c6_i_8_xlarge = "ML_C6I_8XLARGE",
        .ml_c6_i_12_xlarge = "ML_C6I_12XLARGE",
        .ml_c6_i_16_xlarge = "ML_C6I_16XLARGE",
        .ml_c6_i_24_xlarge = "ML_C6I_24XLARGE",
        .ml_c6_i_32_xlarge = "ML_C6I_32XLARGE",
        .ml_m6_i_large = "ML_M6I_LARGE",
        .ml_m6_i_xlarge = "ML_M6I_XLARGE",
        .ml_m6_i_2_xlarge = "ML_M6I_2XLARGE",
        .ml_m6_i_4_xlarge = "ML_M6I_4XLARGE",
        .ml_m6_i_8_xlarge = "ML_M6I_8XLARGE",
        .ml_m6_i_12_xlarge = "ML_M6I_12XLARGE",
        .ml_m6_i_16_xlarge = "ML_M6I_16XLARGE",
        .ml_m6_i_24_xlarge = "ML_M6I_24XLARGE",
        .ml_m6_i_32_xlarge = "ML_M6I_32XLARGE",
        .ml_r6_i_large = "ML_R6I_LARGE",
        .ml_r6_i_xlarge = "ML_R6I_XLARGE",
        .ml_r6_i_2_xlarge = "ML_R6I_2XLARGE",
        .ml_r6_i_4_xlarge = "ML_R6I_4XLARGE",
        .ml_r6_i_8_xlarge = "ML_R6I_8XLARGE",
        .ml_r6_i_12_xlarge = "ML_R6I_12XLARGE",
        .ml_r6_i_16_xlarge = "ML_R6I_16XLARGE",
        .ml_r6_i_24_xlarge = "ML_R6I_24XLARGE",
        .ml_r6_i_32_xlarge = "ML_R6I_32XLARGE",
        .ml_g5_xlarge = "ML_G5_XLARGE",
        .ml_g5_2_xlarge = "ML_G5_2XLARGE",
        .ml_g5_4_xlarge = "ML_G5_4XLARGE",
        .ml_g5_8_xlarge = "ML_G5_8XLARGE",
        .ml_g5_12_xlarge = "ML_G5_12XLARGE",
        .ml_g5_16_xlarge = "ML_G5_16XLARGE",
        .ml_g5_24_xlarge = "ML_G5_24XLARGE",
        .ml_g5_48_xlarge = "ML_G5_48XLARGE",
        .ml_g6_xlarge = "ML_G6_XLARGE",
        .ml_g6_2_xlarge = "ML_G6_2XLARGE",
        .ml_g6_4_xlarge = "ML_G6_4XLARGE",
        .ml_g6_8_xlarge = "ML_G6_8XLARGE",
        .ml_g6_12_xlarge = "ML_G6_12XLARGE",
        .ml_g6_16_xlarge = "ML_G6_16XLARGE",
        .ml_g6_24_xlarge = "ML_G6_24XLARGE",
        .ml_g6_48_xlarge = "ML_G6_48XLARGE",
        .ml_r8_g_medium = "ML_R8G_MEDIUM",
        .ml_r8_g_large = "ML_R8G_LARGE",
        .ml_r8_g_xlarge = "ML_R8G_XLARGE",
        .ml_r8_g_2_xlarge = "ML_R8G_2XLARGE",
        .ml_r8_g_4_xlarge = "ML_R8G_4XLARGE",
        .ml_r8_g_8_xlarge = "ML_R8G_8XLARGE",
        .ml_r8_g_12_xlarge = "ML_R8G_12XLARGE",
        .ml_r8_g_16_xlarge = "ML_R8G_16XLARGE",
        .ml_r8_g_24_xlarge = "ML_R8G_24XLARGE",
        .ml_r8_g_48_xlarge = "ML_R8G_48XLARGE",
        .ml_g6_e_xlarge = "ML_G6E_XLARGE",
        .ml_g6_e_2_xlarge = "ML_G6E_2XLARGE",
        .ml_g6_e_4_xlarge = "ML_G6E_4XLARGE",
        .ml_g6_e_8_xlarge = "ML_G6E_8XLARGE",
        .ml_g6_e_12_xlarge = "ML_G6E_12XLARGE",
        .ml_g6_e_16_xlarge = "ML_G6E_16XLARGE",
        .ml_g6_e_24_xlarge = "ML_G6E_24XLARGE",
        .ml_g6_e_48_xlarge = "ML_G6E_48XLARGE",
        .ml_p4_d_24_xlarge = "ML_P4D_24XLARGE",
        .ml_c7_g_large = "ML_C7G_LARGE",
        .ml_c7_g_xlarge = "ML_C7G_XLARGE",
        .ml_c7_g_2_xlarge = "ML_C7G_2XLARGE",
        .ml_c7_g_4_xlarge = "ML_C7G_4XLARGE",
        .ml_c7_g_8_xlarge = "ML_C7G_8XLARGE",
        .ml_c7_g_12_xlarge = "ML_C7G_12XLARGE",
        .ml_c7_g_16_xlarge = "ML_C7G_16XLARGE",
        .ml_m6_g_large = "ML_M6G_LARGE",
        .ml_m6_g_xlarge = "ML_M6G_XLARGE",
        .ml_m6_g_2_xlarge = "ML_M6G_2XLARGE",
        .ml_m6_g_4_xlarge = "ML_M6G_4XLARGE",
        .ml_m6_g_8_xlarge = "ML_M6G_8XLARGE",
        .ml_m6_g_12_xlarge = "ML_M6G_12XLARGE",
        .ml_m6_g_16_xlarge = "ML_M6G_16XLARGE",
        .ml_m6_gd_large = "ML_M6GD_LARGE",
        .ml_m6_gd_xlarge = "ML_M6GD_XLARGE",
        .ml_m6_gd_2_xlarge = "ML_M6GD_2XLARGE",
        .ml_m6_gd_4_xlarge = "ML_M6GD_4XLARGE",
        .ml_m6_gd_8_xlarge = "ML_M6GD_8XLARGE",
        .ml_m6_gd_12_xlarge = "ML_M6GD_12XLARGE",
        .ml_m6_gd_16_xlarge = "ML_M6GD_16XLARGE",
        .ml_c6_g_large = "ML_C6G_LARGE",
        .ml_c6_g_xlarge = "ML_C6G_XLARGE",
        .ml_c6_g_2_xlarge = "ML_C6G_2XLARGE",
        .ml_c6_g_4_xlarge = "ML_C6G_4XLARGE",
        .ml_c6_g_8_xlarge = "ML_C6G_8XLARGE",
        .ml_c6_g_12_xlarge = "ML_C6G_12XLARGE",
        .ml_c6_g_16_xlarge = "ML_C6G_16XLARGE",
        .ml_c6_gd_large = "ML_C6GD_LARGE",
        .ml_c6_gd_xlarge = "ML_C6GD_XLARGE",
        .ml_c6_gd_2_xlarge = "ML_C6GD_2XLARGE",
        .ml_c6_gd_4_xlarge = "ML_C6GD_4XLARGE",
        .ml_c6_gd_8_xlarge = "ML_C6GD_8XLARGE",
        .ml_c6_gd_12_xlarge = "ML_C6GD_12XLARGE",
        .ml_c6_gd_16_xlarge = "ML_C6GD_16XLARGE",
        .ml_c6_gn_large = "ML_C6GN_LARGE",
        .ml_c6_gn_xlarge = "ML_C6GN_XLARGE",
        .ml_c6_gn_2_xlarge = "ML_C6GN_2XLARGE",
        .ml_c6_gn_4_xlarge = "ML_C6GN_4XLARGE",
        .ml_c6_gn_8_xlarge = "ML_C6GN_8XLARGE",
        .ml_c6_gn_12_xlarge = "ML_C6GN_12XLARGE",
        .ml_c6_gn_16_xlarge = "ML_C6GN_16XLARGE",
        .ml_r6_g_large = "ML_R6G_LARGE",
        .ml_r6_g_xlarge = "ML_R6G_XLARGE",
        .ml_r6_g_2_xlarge = "ML_R6G_2XLARGE",
        .ml_r6_g_4_xlarge = "ML_R6G_4XLARGE",
        .ml_r6_g_8_xlarge = "ML_R6G_8XLARGE",
        .ml_r6_g_12_xlarge = "ML_R6G_12XLARGE",
        .ml_r6_g_16_xlarge = "ML_R6G_16XLARGE",
        .ml_r6_gd_large = "ML_R6GD_LARGE",
        .ml_r6_gd_xlarge = "ML_R6GD_XLARGE",
        .ml_r6_gd_2_xlarge = "ML_R6GD_2XLARGE",
        .ml_r6_gd_4_xlarge = "ML_R6GD_4XLARGE",
        .ml_r6_gd_8_xlarge = "ML_R6GD_8XLARGE",
        .ml_r6_gd_12_xlarge = "ML_R6GD_12XLARGE",
        .ml_r6_gd_16_xlarge = "ML_R6GD_16XLARGE",
        .ml_p4_de_24_xlarge = "ML_P4DE_24XLARGE",
        .ml_trn1_2_xlarge = "ML_TRN1_2XLARGE",
        .ml_trn1_32_xlarge = "ML_TRN1_32XLARGE",
        .ml_trn1_n_32_xlarge = "ML_TRN1N_32XLARGE",
        .ml_trn2_48_xlarge = "ML_TRN2_48XLARGE",
        .ml_inf2_xlarge = "ML_INF2_XLARGE",
        .ml_inf2_8_xlarge = "ML_INF2_8XLARGE",
        .ml_inf2_24_xlarge = "ML_INF2_24XLARGE",
        .ml_inf2_48_xlarge = "ML_INF2_48XLARGE",
        .ml_p5_48_xlarge = "ML_P5_48XLARGE",
        .ml_p5_e_48_xlarge = "ML_P5E_48XLARGE",
        .ml_p5_en_48_xlarge = "ML_P5EN_48XLARGE",
        .ml_m7_i_large = "ML_M7I_LARGE",
        .ml_m7_i_xlarge = "ML_M7I_XLARGE",
        .ml_m7_i_2_xlarge = "ML_M7I_2XLARGE",
        .ml_m7_i_4_xlarge = "ML_M7I_4XLARGE",
        .ml_m7_i_8_xlarge = "ML_M7I_8XLARGE",
        .ml_m7_i_12_xlarge = "ML_M7I_12XLARGE",
        .ml_m7_i_16_xlarge = "ML_M7I_16XLARGE",
        .ml_m7_i_24_xlarge = "ML_M7I_24XLARGE",
        .ml_m7_i_48_xlarge = "ML_M7I_48XLARGE",
        .ml_c7_i_large = "ML_C7I_LARGE",
        .ml_c7_i_xlarge = "ML_C7I_XLARGE",
        .ml_c7_i_2_xlarge = "ML_C7I_2XLARGE",
        .ml_c7_i_4_xlarge = "ML_C7I_4XLARGE",
        .ml_c7_i_8_xlarge = "ML_C7I_8XLARGE",
        .ml_c7_i_12_xlarge = "ML_C7I_12XLARGE",
        .ml_c7_i_16_xlarge = "ML_C7I_16XLARGE",
        .ml_c7_i_24_xlarge = "ML_C7I_24XLARGE",
        .ml_c7_i_48_xlarge = "ML_C7I_48XLARGE",
        .ml_r7_i_large = "ML_R7I_LARGE",
        .ml_r7_i_xlarge = "ML_R7I_XLARGE",
        .ml_r7_i_2_xlarge = "ML_R7I_2XLARGE",
        .ml_r7_i_4_xlarge = "ML_R7I_4XLARGE",
        .ml_r7_i_8_xlarge = "ML_R7I_8XLARGE",
        .ml_r7_i_12_xlarge = "ML_R7I_12XLARGE",
        .ml_r7_i_16_xlarge = "ML_R7I_16XLARGE",
        .ml_r7_i_24_xlarge = "ML_R7I_24XLARGE",
        .ml_r7_i_48_xlarge = "ML_R7I_48XLARGE",
        .ml_c8_g_medium = "ML_C8G_MEDIUM",
        .ml_c8_g_large = "ML_C8G_LARGE",
        .ml_c8_g_xlarge = "ML_C8G_XLARGE",
        .ml_c8_g_2_xlarge = "ML_C8G_2XLARGE",
        .ml_c8_g_4_xlarge = "ML_C8G_4XLARGE",
        .ml_c8_g_8_xlarge = "ML_C8G_8XLARGE",
        .ml_c8_g_12_xlarge = "ML_C8G_12XLARGE",
        .ml_c8_g_16_xlarge = "ML_C8G_16XLARGE",
        .ml_c8_g_24_xlarge = "ML_C8G_24XLARGE",
        .ml_c8_g_48_xlarge = "ML_C8G_48XLARGE",
        .ml_r7_gd_medium = "ML_R7GD_MEDIUM",
        .ml_r7_gd_large = "ML_R7GD_LARGE",
        .ml_r7_gd_xlarge = "ML_R7GD_XLARGE",
        .ml_r7_gd_2_xlarge = "ML_R7GD_2XLARGE",
        .ml_r7_gd_4_xlarge = "ML_R7GD_4XLARGE",
        .ml_r7_gd_8_xlarge = "ML_R7GD_8XLARGE",
        .ml_r7_gd_12_xlarge = "ML_R7GD_12XLARGE",
        .ml_r7_gd_16_xlarge = "ML_R7GD_16XLARGE",
        .ml_m8_g_medium = "ML_M8G_MEDIUM",
        .ml_m8_g_large = "ML_M8G_LARGE",
        .ml_m8_g_xlarge = "ML_M8G_XLARGE",
        .ml_m8_g_2_xlarge = "ML_M8G_2XLARGE",
        .ml_m8_g_4_xlarge = "ML_M8G_4XLARGE",
        .ml_m8_g_8_xlarge = "ML_M8G_8XLARGE",
        .ml_m8_g_12_xlarge = "ML_M8G_12XLARGE",
        .ml_m8_g_16_xlarge = "ML_M8G_16XLARGE",
        .ml_m8_g_24_xlarge = "ML_M8G_24XLARGE",
        .ml_m8_g_48_xlarge = "ML_M8G_48XLARGE",
        .ml_c6_in_large = "ML_C6IN_LARGE",
        .ml_c6_in_xlarge = "ML_C6IN_XLARGE",
        .ml_c6_in_2_xlarge = "ML_C6IN_2XLARGE",
        .ml_c6_in_4_xlarge = "ML_C6IN_4XLARGE",
        .ml_c6_in_8_xlarge = "ML_C6IN_8XLARGE",
        .ml_c6_in_12_xlarge = "ML_C6IN_12XLARGE",
        .ml_c6_in_16_xlarge = "ML_C6IN_16XLARGE",
        .ml_c6_in_24_xlarge = "ML_C6IN_24XLARGE",
        .ml_c6_in_32_xlarge = "ML_C6IN_32XLARGE",
        .ml_p6_b200_48_xlarge = "ML_P6_B200_48XLARGE",
        .ml_p6_e_gb200_36_xlarge = "ML_P6E_GB200_36XLARGE",
        .ml_p5_4_xlarge = "ML_P5_4XLARGE",
    };
};
