const std = @import("std");

pub const ProductionVariantInstanceType = enum {
    ml_t2_medium,
    ml_t2_large,
    ml_t2_xlarge,
    ml_t2_2_xlarge,
    ml_m4_xlarge,
    ml_m4_2_xlarge,
    ml_m4_4_xlarge,
    ml_m4_10_xlarge,
    ml_m4_16_xlarge,
    ml_m5_large,
    ml_m5_xlarge,
    ml_m5_2_xlarge,
    ml_m5_4_xlarge,
    ml_m5_12_xlarge,
    ml_m5_24_xlarge,
    ml_m5_d_large,
    ml_m5_d_xlarge,
    ml_m5_d_2_xlarge,
    ml_m5_d_4_xlarge,
    ml_m5_d_12_xlarge,
    ml_m5_d_24_xlarge,
    ml_c4_large,
    ml_c4_xlarge,
    ml_c4_2_xlarge,
    ml_c4_4_xlarge,
    ml_c4_8_xlarge,
    ml_p2_xlarge,
    ml_p2_8_xlarge,
    ml_p2_16_xlarge,
    ml_p3_2_xlarge,
    ml_p3_8_xlarge,
    ml_p3_16_xlarge,
    ml_c5_large,
    ml_c5_xlarge,
    ml_c5_2_xlarge,
    ml_c5_4_xlarge,
    ml_c5_9_xlarge,
    ml_c5_18_xlarge,
    ml_c5_d_large,
    ml_c5_d_xlarge,
    ml_c5_d_2_xlarge,
    ml_c5_d_4_xlarge,
    ml_c5_d_9_xlarge,
    ml_c5_d_18_xlarge,
    ml_g4_dn_xlarge,
    ml_g4_dn_2_xlarge,
    ml_g4_dn_4_xlarge,
    ml_g4_dn_8_xlarge,
    ml_g4_dn_12_xlarge,
    ml_g4_dn_16_xlarge,
    ml_r5_large,
    ml_r5_xlarge,
    ml_r5_2_xlarge,
    ml_r5_4_xlarge,
    ml_r5_12_xlarge,
    ml_r5_24_xlarge,
    ml_r5_d_large,
    ml_r5_d_xlarge,
    ml_r5_d_2_xlarge,
    ml_r5_d_4_xlarge,
    ml_r5_d_12_xlarge,
    ml_r5_d_24_xlarge,
    ml_inf1_xlarge,
    ml_inf1_2_xlarge,
    ml_inf1_6_xlarge,
    ml_inf1_24_xlarge,
    ml_dl1_24_xlarge,
    ml_c6_i_large,
    ml_c6_i_xlarge,
    ml_c6_i_2_xlarge,
    ml_c6_i_4_xlarge,
    ml_c6_i_8_xlarge,
    ml_c6_i_12_xlarge,
    ml_c6_i_16_xlarge,
    ml_c6_i_24_xlarge,
    ml_c6_i_32_xlarge,
    ml_m6_i_large,
    ml_m6_i_xlarge,
    ml_m6_i_2_xlarge,
    ml_m6_i_4_xlarge,
    ml_m6_i_8_xlarge,
    ml_m6_i_12_xlarge,
    ml_m6_i_16_xlarge,
    ml_m6_i_24_xlarge,
    ml_m6_i_32_xlarge,
    ml_r6_i_large,
    ml_r6_i_xlarge,
    ml_r6_i_2_xlarge,
    ml_r6_i_4_xlarge,
    ml_r6_i_8_xlarge,
    ml_r6_i_12_xlarge,
    ml_r6_i_16_xlarge,
    ml_r6_i_24_xlarge,
    ml_r6_i_32_xlarge,
    ml_g5_xlarge,
    ml_g5_2_xlarge,
    ml_g5_4_xlarge,
    ml_g5_8_xlarge,
    ml_g5_12_xlarge,
    ml_g5_16_xlarge,
    ml_g5_24_xlarge,
    ml_g5_48_xlarge,
    ml_g6_xlarge,
    ml_g6_2_xlarge,
    ml_g6_4_xlarge,
    ml_g6_8_xlarge,
    ml_g6_12_xlarge,
    ml_g6_16_xlarge,
    ml_g6_24_xlarge,
    ml_g6_48_xlarge,
    ml_r8_g_medium,
    ml_r8_g_large,
    ml_r8_g_xlarge,
    ml_r8_g_2_xlarge,
    ml_r8_g_4_xlarge,
    ml_r8_g_8_xlarge,
    ml_r8_g_12_xlarge,
    ml_r8_g_16_xlarge,
    ml_r8_g_24_xlarge,
    ml_r8_g_48_xlarge,
    ml_g6_e_xlarge,
    ml_g6_e_2_xlarge,
    ml_g6_e_4_xlarge,
    ml_g6_e_8_xlarge,
    ml_g6_e_12_xlarge,
    ml_g6_e_16_xlarge,
    ml_g6_e_24_xlarge,
    ml_g6_e_48_xlarge,
    ml_p4_d_24_xlarge,
    ml_c7_g_large,
    ml_c7_g_xlarge,
    ml_c7_g_2_xlarge,
    ml_c7_g_4_xlarge,
    ml_c7_g_8_xlarge,
    ml_c7_g_12_xlarge,
    ml_c7_g_16_xlarge,
    ml_m6_g_large,
    ml_m6_g_xlarge,
    ml_m6_g_2_xlarge,
    ml_m6_g_4_xlarge,
    ml_m6_g_8_xlarge,
    ml_m6_g_12_xlarge,
    ml_m6_g_16_xlarge,
    ml_m6_gd_large,
    ml_m6_gd_xlarge,
    ml_m6_gd_2_xlarge,
    ml_m6_gd_4_xlarge,
    ml_m6_gd_8_xlarge,
    ml_m6_gd_12_xlarge,
    ml_m6_gd_16_xlarge,
    ml_c6_g_large,
    ml_c6_g_xlarge,
    ml_c6_g_2_xlarge,
    ml_c6_g_4_xlarge,
    ml_c6_g_8_xlarge,
    ml_c6_g_12_xlarge,
    ml_c6_g_16_xlarge,
    ml_c6_gd_large,
    ml_c6_gd_xlarge,
    ml_c6_gd_2_xlarge,
    ml_c6_gd_4_xlarge,
    ml_c6_gd_8_xlarge,
    ml_c6_gd_12_xlarge,
    ml_c6_gd_16_xlarge,
    ml_c6_gn_large,
    ml_c6_gn_xlarge,
    ml_c6_gn_2_xlarge,
    ml_c6_gn_4_xlarge,
    ml_c6_gn_8_xlarge,
    ml_c6_gn_12_xlarge,
    ml_c6_gn_16_xlarge,
    ml_r6_g_large,
    ml_r6_g_xlarge,
    ml_r6_g_2_xlarge,
    ml_r6_g_4_xlarge,
    ml_r6_g_8_xlarge,
    ml_r6_g_12_xlarge,
    ml_r6_g_16_xlarge,
    ml_r6_gd_large,
    ml_r6_gd_xlarge,
    ml_r6_gd_2_xlarge,
    ml_r6_gd_4_xlarge,
    ml_r6_gd_8_xlarge,
    ml_r6_gd_12_xlarge,
    ml_r6_gd_16_xlarge,
    ml_p4_de_24_xlarge,
    ml_trn1_2_xlarge,
    ml_trn1_32_xlarge,
    ml_trn1_n_32_xlarge,
    ml_trn2_48_xlarge,
    ml_inf2_xlarge,
    ml_inf2_8_xlarge,
    ml_inf2_24_xlarge,
    ml_inf2_48_xlarge,
    ml_p5_48_xlarge,
    ml_p5_e_48_xlarge,
    ml_p5_en_48_xlarge,
    ml_m7_i_large,
    ml_m7_i_xlarge,
    ml_m7_i_2_xlarge,
    ml_m7_i_4_xlarge,
    ml_m7_i_8_xlarge,
    ml_m7_i_12_xlarge,
    ml_m7_i_16_xlarge,
    ml_m7_i_24_xlarge,
    ml_m7_i_48_xlarge,
    ml_c7_i_large,
    ml_c7_i_xlarge,
    ml_c7_i_2_xlarge,
    ml_c7_i_4_xlarge,
    ml_c7_i_8_xlarge,
    ml_c7_i_12_xlarge,
    ml_c7_i_16_xlarge,
    ml_c7_i_24_xlarge,
    ml_c7_i_48_xlarge,
    ml_r7_i_large,
    ml_r7_i_xlarge,
    ml_r7_i_2_xlarge,
    ml_r7_i_4_xlarge,
    ml_r7_i_8_xlarge,
    ml_r7_i_12_xlarge,
    ml_r7_i_16_xlarge,
    ml_r7_i_24_xlarge,
    ml_r7_i_48_xlarge,
    ml_c8_g_medium,
    ml_c8_g_large,
    ml_c8_g_xlarge,
    ml_c8_g_2_xlarge,
    ml_c8_g_4_xlarge,
    ml_c8_g_8_xlarge,
    ml_c8_g_12_xlarge,
    ml_c8_g_16_xlarge,
    ml_c8_g_24_xlarge,
    ml_c8_g_48_xlarge,
    ml_r7_gd_medium,
    ml_r7_gd_large,
    ml_r7_gd_xlarge,
    ml_r7_gd_2_xlarge,
    ml_r7_gd_4_xlarge,
    ml_r7_gd_8_xlarge,
    ml_r7_gd_12_xlarge,
    ml_r7_gd_16_xlarge,
    ml_m8_g_medium,
    ml_m8_g_large,
    ml_m8_g_xlarge,
    ml_m8_g_2_xlarge,
    ml_m8_g_4_xlarge,
    ml_m8_g_8_xlarge,
    ml_m8_g_12_xlarge,
    ml_m8_g_16_xlarge,
    ml_m8_g_24_xlarge,
    ml_m8_g_48_xlarge,
    ml_c6_in_large,
    ml_c6_in_xlarge,
    ml_c6_in_2_xlarge,
    ml_c6_in_4_xlarge,
    ml_c6_in_8_xlarge,
    ml_c6_in_12_xlarge,
    ml_c6_in_16_xlarge,
    ml_c6_in_24_xlarge,
    ml_c6_in_32_xlarge,
    ml_p6_b200_48_xlarge,
    ml_p6_e_gb200_36_xlarge,
    ml_p5_4_xlarge,

    pub const json_field_names = .{
        .ml_t2_medium = "ml.t2.medium",
        .ml_t2_large = "ml.t2.large",
        .ml_t2_xlarge = "ml.t2.xlarge",
        .ml_t2_2_xlarge = "ml.t2.2xlarge",
        .ml_m4_xlarge = "ml.m4.xlarge",
        .ml_m4_2_xlarge = "ml.m4.2xlarge",
        .ml_m4_4_xlarge = "ml.m4.4xlarge",
        .ml_m4_10_xlarge = "ml.m4.10xlarge",
        .ml_m4_16_xlarge = "ml.m4.16xlarge",
        .ml_m5_large = "ml.m5.large",
        .ml_m5_xlarge = "ml.m5.xlarge",
        .ml_m5_2_xlarge = "ml.m5.2xlarge",
        .ml_m5_4_xlarge = "ml.m5.4xlarge",
        .ml_m5_12_xlarge = "ml.m5.12xlarge",
        .ml_m5_24_xlarge = "ml.m5.24xlarge",
        .ml_m5_d_large = "ml.m5d.large",
        .ml_m5_d_xlarge = "ml.m5d.xlarge",
        .ml_m5_d_2_xlarge = "ml.m5d.2xlarge",
        .ml_m5_d_4_xlarge = "ml.m5d.4xlarge",
        .ml_m5_d_12_xlarge = "ml.m5d.12xlarge",
        .ml_m5_d_24_xlarge = "ml.m5d.24xlarge",
        .ml_c4_large = "ml.c4.large",
        .ml_c4_xlarge = "ml.c4.xlarge",
        .ml_c4_2_xlarge = "ml.c4.2xlarge",
        .ml_c4_4_xlarge = "ml.c4.4xlarge",
        .ml_c4_8_xlarge = "ml.c4.8xlarge",
        .ml_p2_xlarge = "ml.p2.xlarge",
        .ml_p2_8_xlarge = "ml.p2.8xlarge",
        .ml_p2_16_xlarge = "ml.p2.16xlarge",
        .ml_p3_2_xlarge = "ml.p3.2xlarge",
        .ml_p3_8_xlarge = "ml.p3.8xlarge",
        .ml_p3_16_xlarge = "ml.p3.16xlarge",
        .ml_c5_large = "ml.c5.large",
        .ml_c5_xlarge = "ml.c5.xlarge",
        .ml_c5_2_xlarge = "ml.c5.2xlarge",
        .ml_c5_4_xlarge = "ml.c5.4xlarge",
        .ml_c5_9_xlarge = "ml.c5.9xlarge",
        .ml_c5_18_xlarge = "ml.c5.18xlarge",
        .ml_c5_d_large = "ml.c5d.large",
        .ml_c5_d_xlarge = "ml.c5d.xlarge",
        .ml_c5_d_2_xlarge = "ml.c5d.2xlarge",
        .ml_c5_d_4_xlarge = "ml.c5d.4xlarge",
        .ml_c5_d_9_xlarge = "ml.c5d.9xlarge",
        .ml_c5_d_18_xlarge = "ml.c5d.18xlarge",
        .ml_g4_dn_xlarge = "ml.g4dn.xlarge",
        .ml_g4_dn_2_xlarge = "ml.g4dn.2xlarge",
        .ml_g4_dn_4_xlarge = "ml.g4dn.4xlarge",
        .ml_g4_dn_8_xlarge = "ml.g4dn.8xlarge",
        .ml_g4_dn_12_xlarge = "ml.g4dn.12xlarge",
        .ml_g4_dn_16_xlarge = "ml.g4dn.16xlarge",
        .ml_r5_large = "ml.r5.large",
        .ml_r5_xlarge = "ml.r5.xlarge",
        .ml_r5_2_xlarge = "ml.r5.2xlarge",
        .ml_r5_4_xlarge = "ml.r5.4xlarge",
        .ml_r5_12_xlarge = "ml.r5.12xlarge",
        .ml_r5_24_xlarge = "ml.r5.24xlarge",
        .ml_r5_d_large = "ml.r5d.large",
        .ml_r5_d_xlarge = "ml.r5d.xlarge",
        .ml_r5_d_2_xlarge = "ml.r5d.2xlarge",
        .ml_r5_d_4_xlarge = "ml.r5d.4xlarge",
        .ml_r5_d_12_xlarge = "ml.r5d.12xlarge",
        .ml_r5_d_24_xlarge = "ml.r5d.24xlarge",
        .ml_inf1_xlarge = "ml.inf1.xlarge",
        .ml_inf1_2_xlarge = "ml.inf1.2xlarge",
        .ml_inf1_6_xlarge = "ml.inf1.6xlarge",
        .ml_inf1_24_xlarge = "ml.inf1.24xlarge",
        .ml_dl1_24_xlarge = "ml.dl1.24xlarge",
        .ml_c6_i_large = "ml.c6i.large",
        .ml_c6_i_xlarge = "ml.c6i.xlarge",
        .ml_c6_i_2_xlarge = "ml.c6i.2xlarge",
        .ml_c6_i_4_xlarge = "ml.c6i.4xlarge",
        .ml_c6_i_8_xlarge = "ml.c6i.8xlarge",
        .ml_c6_i_12_xlarge = "ml.c6i.12xlarge",
        .ml_c6_i_16_xlarge = "ml.c6i.16xlarge",
        .ml_c6_i_24_xlarge = "ml.c6i.24xlarge",
        .ml_c6_i_32_xlarge = "ml.c6i.32xlarge",
        .ml_m6_i_large = "ml.m6i.large",
        .ml_m6_i_xlarge = "ml.m6i.xlarge",
        .ml_m6_i_2_xlarge = "ml.m6i.2xlarge",
        .ml_m6_i_4_xlarge = "ml.m6i.4xlarge",
        .ml_m6_i_8_xlarge = "ml.m6i.8xlarge",
        .ml_m6_i_12_xlarge = "ml.m6i.12xlarge",
        .ml_m6_i_16_xlarge = "ml.m6i.16xlarge",
        .ml_m6_i_24_xlarge = "ml.m6i.24xlarge",
        .ml_m6_i_32_xlarge = "ml.m6i.32xlarge",
        .ml_r6_i_large = "ml.r6i.large",
        .ml_r6_i_xlarge = "ml.r6i.xlarge",
        .ml_r6_i_2_xlarge = "ml.r6i.2xlarge",
        .ml_r6_i_4_xlarge = "ml.r6i.4xlarge",
        .ml_r6_i_8_xlarge = "ml.r6i.8xlarge",
        .ml_r6_i_12_xlarge = "ml.r6i.12xlarge",
        .ml_r6_i_16_xlarge = "ml.r6i.16xlarge",
        .ml_r6_i_24_xlarge = "ml.r6i.24xlarge",
        .ml_r6_i_32_xlarge = "ml.r6i.32xlarge",
        .ml_g5_xlarge = "ml.g5.xlarge",
        .ml_g5_2_xlarge = "ml.g5.2xlarge",
        .ml_g5_4_xlarge = "ml.g5.4xlarge",
        .ml_g5_8_xlarge = "ml.g5.8xlarge",
        .ml_g5_12_xlarge = "ml.g5.12xlarge",
        .ml_g5_16_xlarge = "ml.g5.16xlarge",
        .ml_g5_24_xlarge = "ml.g5.24xlarge",
        .ml_g5_48_xlarge = "ml.g5.48xlarge",
        .ml_g6_xlarge = "ml.g6.xlarge",
        .ml_g6_2_xlarge = "ml.g6.2xlarge",
        .ml_g6_4_xlarge = "ml.g6.4xlarge",
        .ml_g6_8_xlarge = "ml.g6.8xlarge",
        .ml_g6_12_xlarge = "ml.g6.12xlarge",
        .ml_g6_16_xlarge = "ml.g6.16xlarge",
        .ml_g6_24_xlarge = "ml.g6.24xlarge",
        .ml_g6_48_xlarge = "ml.g6.48xlarge",
        .ml_r8_g_medium = "ml.r8g.medium",
        .ml_r8_g_large = "ml.r8g.large",
        .ml_r8_g_xlarge = "ml.r8g.xlarge",
        .ml_r8_g_2_xlarge = "ml.r8g.2xlarge",
        .ml_r8_g_4_xlarge = "ml.r8g.4xlarge",
        .ml_r8_g_8_xlarge = "ml.r8g.8xlarge",
        .ml_r8_g_12_xlarge = "ml.r8g.12xlarge",
        .ml_r8_g_16_xlarge = "ml.r8g.16xlarge",
        .ml_r8_g_24_xlarge = "ml.r8g.24xlarge",
        .ml_r8_g_48_xlarge = "ml.r8g.48xlarge",
        .ml_g6_e_xlarge = "ml.g6e.xlarge",
        .ml_g6_e_2_xlarge = "ml.g6e.2xlarge",
        .ml_g6_e_4_xlarge = "ml.g6e.4xlarge",
        .ml_g6_e_8_xlarge = "ml.g6e.8xlarge",
        .ml_g6_e_12_xlarge = "ml.g6e.12xlarge",
        .ml_g6_e_16_xlarge = "ml.g6e.16xlarge",
        .ml_g6_e_24_xlarge = "ml.g6e.24xlarge",
        .ml_g6_e_48_xlarge = "ml.g6e.48xlarge",
        .ml_p4_d_24_xlarge = "ml.p4d.24xlarge",
        .ml_c7_g_large = "ml.c7g.large",
        .ml_c7_g_xlarge = "ml.c7g.xlarge",
        .ml_c7_g_2_xlarge = "ml.c7g.2xlarge",
        .ml_c7_g_4_xlarge = "ml.c7g.4xlarge",
        .ml_c7_g_8_xlarge = "ml.c7g.8xlarge",
        .ml_c7_g_12_xlarge = "ml.c7g.12xlarge",
        .ml_c7_g_16_xlarge = "ml.c7g.16xlarge",
        .ml_m6_g_large = "ml.m6g.large",
        .ml_m6_g_xlarge = "ml.m6g.xlarge",
        .ml_m6_g_2_xlarge = "ml.m6g.2xlarge",
        .ml_m6_g_4_xlarge = "ml.m6g.4xlarge",
        .ml_m6_g_8_xlarge = "ml.m6g.8xlarge",
        .ml_m6_g_12_xlarge = "ml.m6g.12xlarge",
        .ml_m6_g_16_xlarge = "ml.m6g.16xlarge",
        .ml_m6_gd_large = "ml.m6gd.large",
        .ml_m6_gd_xlarge = "ml.m6gd.xlarge",
        .ml_m6_gd_2_xlarge = "ml.m6gd.2xlarge",
        .ml_m6_gd_4_xlarge = "ml.m6gd.4xlarge",
        .ml_m6_gd_8_xlarge = "ml.m6gd.8xlarge",
        .ml_m6_gd_12_xlarge = "ml.m6gd.12xlarge",
        .ml_m6_gd_16_xlarge = "ml.m6gd.16xlarge",
        .ml_c6_g_large = "ml.c6g.large",
        .ml_c6_g_xlarge = "ml.c6g.xlarge",
        .ml_c6_g_2_xlarge = "ml.c6g.2xlarge",
        .ml_c6_g_4_xlarge = "ml.c6g.4xlarge",
        .ml_c6_g_8_xlarge = "ml.c6g.8xlarge",
        .ml_c6_g_12_xlarge = "ml.c6g.12xlarge",
        .ml_c6_g_16_xlarge = "ml.c6g.16xlarge",
        .ml_c6_gd_large = "ml.c6gd.large",
        .ml_c6_gd_xlarge = "ml.c6gd.xlarge",
        .ml_c6_gd_2_xlarge = "ml.c6gd.2xlarge",
        .ml_c6_gd_4_xlarge = "ml.c6gd.4xlarge",
        .ml_c6_gd_8_xlarge = "ml.c6gd.8xlarge",
        .ml_c6_gd_12_xlarge = "ml.c6gd.12xlarge",
        .ml_c6_gd_16_xlarge = "ml.c6gd.16xlarge",
        .ml_c6_gn_large = "ml.c6gn.large",
        .ml_c6_gn_xlarge = "ml.c6gn.xlarge",
        .ml_c6_gn_2_xlarge = "ml.c6gn.2xlarge",
        .ml_c6_gn_4_xlarge = "ml.c6gn.4xlarge",
        .ml_c6_gn_8_xlarge = "ml.c6gn.8xlarge",
        .ml_c6_gn_12_xlarge = "ml.c6gn.12xlarge",
        .ml_c6_gn_16_xlarge = "ml.c6gn.16xlarge",
        .ml_r6_g_large = "ml.r6g.large",
        .ml_r6_g_xlarge = "ml.r6g.xlarge",
        .ml_r6_g_2_xlarge = "ml.r6g.2xlarge",
        .ml_r6_g_4_xlarge = "ml.r6g.4xlarge",
        .ml_r6_g_8_xlarge = "ml.r6g.8xlarge",
        .ml_r6_g_12_xlarge = "ml.r6g.12xlarge",
        .ml_r6_g_16_xlarge = "ml.r6g.16xlarge",
        .ml_r6_gd_large = "ml.r6gd.large",
        .ml_r6_gd_xlarge = "ml.r6gd.xlarge",
        .ml_r6_gd_2_xlarge = "ml.r6gd.2xlarge",
        .ml_r6_gd_4_xlarge = "ml.r6gd.4xlarge",
        .ml_r6_gd_8_xlarge = "ml.r6gd.8xlarge",
        .ml_r6_gd_12_xlarge = "ml.r6gd.12xlarge",
        .ml_r6_gd_16_xlarge = "ml.r6gd.16xlarge",
        .ml_p4_de_24_xlarge = "ml.p4de.24xlarge",
        .ml_trn1_2_xlarge = "ml.trn1.2xlarge",
        .ml_trn1_32_xlarge = "ml.trn1.32xlarge",
        .ml_trn1_n_32_xlarge = "ml.trn1n.32xlarge",
        .ml_trn2_48_xlarge = "ml.trn2.48xlarge",
        .ml_inf2_xlarge = "ml.inf2.xlarge",
        .ml_inf2_8_xlarge = "ml.inf2.8xlarge",
        .ml_inf2_24_xlarge = "ml.inf2.24xlarge",
        .ml_inf2_48_xlarge = "ml.inf2.48xlarge",
        .ml_p5_48_xlarge = "ml.p5.48xlarge",
        .ml_p5_e_48_xlarge = "ml.p5e.48xlarge",
        .ml_p5_en_48_xlarge = "ml.p5en.48xlarge",
        .ml_m7_i_large = "ml.m7i.large",
        .ml_m7_i_xlarge = "ml.m7i.xlarge",
        .ml_m7_i_2_xlarge = "ml.m7i.2xlarge",
        .ml_m7_i_4_xlarge = "ml.m7i.4xlarge",
        .ml_m7_i_8_xlarge = "ml.m7i.8xlarge",
        .ml_m7_i_12_xlarge = "ml.m7i.12xlarge",
        .ml_m7_i_16_xlarge = "ml.m7i.16xlarge",
        .ml_m7_i_24_xlarge = "ml.m7i.24xlarge",
        .ml_m7_i_48_xlarge = "ml.m7i.48xlarge",
        .ml_c7_i_large = "ml.c7i.large",
        .ml_c7_i_xlarge = "ml.c7i.xlarge",
        .ml_c7_i_2_xlarge = "ml.c7i.2xlarge",
        .ml_c7_i_4_xlarge = "ml.c7i.4xlarge",
        .ml_c7_i_8_xlarge = "ml.c7i.8xlarge",
        .ml_c7_i_12_xlarge = "ml.c7i.12xlarge",
        .ml_c7_i_16_xlarge = "ml.c7i.16xlarge",
        .ml_c7_i_24_xlarge = "ml.c7i.24xlarge",
        .ml_c7_i_48_xlarge = "ml.c7i.48xlarge",
        .ml_r7_i_large = "ml.r7i.large",
        .ml_r7_i_xlarge = "ml.r7i.xlarge",
        .ml_r7_i_2_xlarge = "ml.r7i.2xlarge",
        .ml_r7_i_4_xlarge = "ml.r7i.4xlarge",
        .ml_r7_i_8_xlarge = "ml.r7i.8xlarge",
        .ml_r7_i_12_xlarge = "ml.r7i.12xlarge",
        .ml_r7_i_16_xlarge = "ml.r7i.16xlarge",
        .ml_r7_i_24_xlarge = "ml.r7i.24xlarge",
        .ml_r7_i_48_xlarge = "ml.r7i.48xlarge",
        .ml_c8_g_medium = "ml.c8g.medium",
        .ml_c8_g_large = "ml.c8g.large",
        .ml_c8_g_xlarge = "ml.c8g.xlarge",
        .ml_c8_g_2_xlarge = "ml.c8g.2xlarge",
        .ml_c8_g_4_xlarge = "ml.c8g.4xlarge",
        .ml_c8_g_8_xlarge = "ml.c8g.8xlarge",
        .ml_c8_g_12_xlarge = "ml.c8g.12xlarge",
        .ml_c8_g_16_xlarge = "ml.c8g.16xlarge",
        .ml_c8_g_24_xlarge = "ml.c8g.24xlarge",
        .ml_c8_g_48_xlarge = "ml.c8g.48xlarge",
        .ml_r7_gd_medium = "ml.r7gd.medium",
        .ml_r7_gd_large = "ml.r7gd.large",
        .ml_r7_gd_xlarge = "ml.r7gd.xlarge",
        .ml_r7_gd_2_xlarge = "ml.r7gd.2xlarge",
        .ml_r7_gd_4_xlarge = "ml.r7gd.4xlarge",
        .ml_r7_gd_8_xlarge = "ml.r7gd.8xlarge",
        .ml_r7_gd_12_xlarge = "ml.r7gd.12xlarge",
        .ml_r7_gd_16_xlarge = "ml.r7gd.16xlarge",
        .ml_m8_g_medium = "ml.m8g.medium",
        .ml_m8_g_large = "ml.m8g.large",
        .ml_m8_g_xlarge = "ml.m8g.xlarge",
        .ml_m8_g_2_xlarge = "ml.m8g.2xlarge",
        .ml_m8_g_4_xlarge = "ml.m8g.4xlarge",
        .ml_m8_g_8_xlarge = "ml.m8g.8xlarge",
        .ml_m8_g_12_xlarge = "ml.m8g.12xlarge",
        .ml_m8_g_16_xlarge = "ml.m8g.16xlarge",
        .ml_m8_g_24_xlarge = "ml.m8g.24xlarge",
        .ml_m8_g_48_xlarge = "ml.m8g.48xlarge",
        .ml_c6_in_large = "ml.c6in.large",
        .ml_c6_in_xlarge = "ml.c6in.xlarge",
        .ml_c6_in_2_xlarge = "ml.c6in.2xlarge",
        .ml_c6_in_4_xlarge = "ml.c6in.4xlarge",
        .ml_c6_in_8_xlarge = "ml.c6in.8xlarge",
        .ml_c6_in_12_xlarge = "ml.c6in.12xlarge",
        .ml_c6_in_16_xlarge = "ml.c6in.16xlarge",
        .ml_c6_in_24_xlarge = "ml.c6in.24xlarge",
        .ml_c6_in_32_xlarge = "ml.c6in.32xlarge",
        .ml_p6_b200_48_xlarge = "ml.p6-b200.48xlarge",
        .ml_p6_e_gb200_36_xlarge = "ml.p6e-gb200.36xlarge",
        .ml_p5_4_xlarge = "ml.p5.4xlarge",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .ml_t2_medium => "ml.t2.medium",
            .ml_t2_large => "ml.t2.large",
            .ml_t2_xlarge => "ml.t2.xlarge",
            .ml_t2_2_xlarge => "ml.t2.2xlarge",
            .ml_m4_xlarge => "ml.m4.xlarge",
            .ml_m4_2_xlarge => "ml.m4.2xlarge",
            .ml_m4_4_xlarge => "ml.m4.4xlarge",
            .ml_m4_10_xlarge => "ml.m4.10xlarge",
            .ml_m4_16_xlarge => "ml.m4.16xlarge",
            .ml_m5_large => "ml.m5.large",
            .ml_m5_xlarge => "ml.m5.xlarge",
            .ml_m5_2_xlarge => "ml.m5.2xlarge",
            .ml_m5_4_xlarge => "ml.m5.4xlarge",
            .ml_m5_12_xlarge => "ml.m5.12xlarge",
            .ml_m5_24_xlarge => "ml.m5.24xlarge",
            .ml_m5_d_large => "ml.m5d.large",
            .ml_m5_d_xlarge => "ml.m5d.xlarge",
            .ml_m5_d_2_xlarge => "ml.m5d.2xlarge",
            .ml_m5_d_4_xlarge => "ml.m5d.4xlarge",
            .ml_m5_d_12_xlarge => "ml.m5d.12xlarge",
            .ml_m5_d_24_xlarge => "ml.m5d.24xlarge",
            .ml_c4_large => "ml.c4.large",
            .ml_c4_xlarge => "ml.c4.xlarge",
            .ml_c4_2_xlarge => "ml.c4.2xlarge",
            .ml_c4_4_xlarge => "ml.c4.4xlarge",
            .ml_c4_8_xlarge => "ml.c4.8xlarge",
            .ml_p2_xlarge => "ml.p2.xlarge",
            .ml_p2_8_xlarge => "ml.p2.8xlarge",
            .ml_p2_16_xlarge => "ml.p2.16xlarge",
            .ml_p3_2_xlarge => "ml.p3.2xlarge",
            .ml_p3_8_xlarge => "ml.p3.8xlarge",
            .ml_p3_16_xlarge => "ml.p3.16xlarge",
            .ml_c5_large => "ml.c5.large",
            .ml_c5_xlarge => "ml.c5.xlarge",
            .ml_c5_2_xlarge => "ml.c5.2xlarge",
            .ml_c5_4_xlarge => "ml.c5.4xlarge",
            .ml_c5_9_xlarge => "ml.c5.9xlarge",
            .ml_c5_18_xlarge => "ml.c5.18xlarge",
            .ml_c5_d_large => "ml.c5d.large",
            .ml_c5_d_xlarge => "ml.c5d.xlarge",
            .ml_c5_d_2_xlarge => "ml.c5d.2xlarge",
            .ml_c5_d_4_xlarge => "ml.c5d.4xlarge",
            .ml_c5_d_9_xlarge => "ml.c5d.9xlarge",
            .ml_c5_d_18_xlarge => "ml.c5d.18xlarge",
            .ml_g4_dn_xlarge => "ml.g4dn.xlarge",
            .ml_g4_dn_2_xlarge => "ml.g4dn.2xlarge",
            .ml_g4_dn_4_xlarge => "ml.g4dn.4xlarge",
            .ml_g4_dn_8_xlarge => "ml.g4dn.8xlarge",
            .ml_g4_dn_12_xlarge => "ml.g4dn.12xlarge",
            .ml_g4_dn_16_xlarge => "ml.g4dn.16xlarge",
            .ml_r5_large => "ml.r5.large",
            .ml_r5_xlarge => "ml.r5.xlarge",
            .ml_r5_2_xlarge => "ml.r5.2xlarge",
            .ml_r5_4_xlarge => "ml.r5.4xlarge",
            .ml_r5_12_xlarge => "ml.r5.12xlarge",
            .ml_r5_24_xlarge => "ml.r5.24xlarge",
            .ml_r5_d_large => "ml.r5d.large",
            .ml_r5_d_xlarge => "ml.r5d.xlarge",
            .ml_r5_d_2_xlarge => "ml.r5d.2xlarge",
            .ml_r5_d_4_xlarge => "ml.r5d.4xlarge",
            .ml_r5_d_12_xlarge => "ml.r5d.12xlarge",
            .ml_r5_d_24_xlarge => "ml.r5d.24xlarge",
            .ml_inf1_xlarge => "ml.inf1.xlarge",
            .ml_inf1_2_xlarge => "ml.inf1.2xlarge",
            .ml_inf1_6_xlarge => "ml.inf1.6xlarge",
            .ml_inf1_24_xlarge => "ml.inf1.24xlarge",
            .ml_dl1_24_xlarge => "ml.dl1.24xlarge",
            .ml_c6_i_large => "ml.c6i.large",
            .ml_c6_i_xlarge => "ml.c6i.xlarge",
            .ml_c6_i_2_xlarge => "ml.c6i.2xlarge",
            .ml_c6_i_4_xlarge => "ml.c6i.4xlarge",
            .ml_c6_i_8_xlarge => "ml.c6i.8xlarge",
            .ml_c6_i_12_xlarge => "ml.c6i.12xlarge",
            .ml_c6_i_16_xlarge => "ml.c6i.16xlarge",
            .ml_c6_i_24_xlarge => "ml.c6i.24xlarge",
            .ml_c6_i_32_xlarge => "ml.c6i.32xlarge",
            .ml_m6_i_large => "ml.m6i.large",
            .ml_m6_i_xlarge => "ml.m6i.xlarge",
            .ml_m6_i_2_xlarge => "ml.m6i.2xlarge",
            .ml_m6_i_4_xlarge => "ml.m6i.4xlarge",
            .ml_m6_i_8_xlarge => "ml.m6i.8xlarge",
            .ml_m6_i_12_xlarge => "ml.m6i.12xlarge",
            .ml_m6_i_16_xlarge => "ml.m6i.16xlarge",
            .ml_m6_i_24_xlarge => "ml.m6i.24xlarge",
            .ml_m6_i_32_xlarge => "ml.m6i.32xlarge",
            .ml_r6_i_large => "ml.r6i.large",
            .ml_r6_i_xlarge => "ml.r6i.xlarge",
            .ml_r6_i_2_xlarge => "ml.r6i.2xlarge",
            .ml_r6_i_4_xlarge => "ml.r6i.4xlarge",
            .ml_r6_i_8_xlarge => "ml.r6i.8xlarge",
            .ml_r6_i_12_xlarge => "ml.r6i.12xlarge",
            .ml_r6_i_16_xlarge => "ml.r6i.16xlarge",
            .ml_r6_i_24_xlarge => "ml.r6i.24xlarge",
            .ml_r6_i_32_xlarge => "ml.r6i.32xlarge",
            .ml_g5_xlarge => "ml.g5.xlarge",
            .ml_g5_2_xlarge => "ml.g5.2xlarge",
            .ml_g5_4_xlarge => "ml.g5.4xlarge",
            .ml_g5_8_xlarge => "ml.g5.8xlarge",
            .ml_g5_12_xlarge => "ml.g5.12xlarge",
            .ml_g5_16_xlarge => "ml.g5.16xlarge",
            .ml_g5_24_xlarge => "ml.g5.24xlarge",
            .ml_g5_48_xlarge => "ml.g5.48xlarge",
            .ml_g6_xlarge => "ml.g6.xlarge",
            .ml_g6_2_xlarge => "ml.g6.2xlarge",
            .ml_g6_4_xlarge => "ml.g6.4xlarge",
            .ml_g6_8_xlarge => "ml.g6.8xlarge",
            .ml_g6_12_xlarge => "ml.g6.12xlarge",
            .ml_g6_16_xlarge => "ml.g6.16xlarge",
            .ml_g6_24_xlarge => "ml.g6.24xlarge",
            .ml_g6_48_xlarge => "ml.g6.48xlarge",
            .ml_r8_g_medium => "ml.r8g.medium",
            .ml_r8_g_large => "ml.r8g.large",
            .ml_r8_g_xlarge => "ml.r8g.xlarge",
            .ml_r8_g_2_xlarge => "ml.r8g.2xlarge",
            .ml_r8_g_4_xlarge => "ml.r8g.4xlarge",
            .ml_r8_g_8_xlarge => "ml.r8g.8xlarge",
            .ml_r8_g_12_xlarge => "ml.r8g.12xlarge",
            .ml_r8_g_16_xlarge => "ml.r8g.16xlarge",
            .ml_r8_g_24_xlarge => "ml.r8g.24xlarge",
            .ml_r8_g_48_xlarge => "ml.r8g.48xlarge",
            .ml_g6_e_xlarge => "ml.g6e.xlarge",
            .ml_g6_e_2_xlarge => "ml.g6e.2xlarge",
            .ml_g6_e_4_xlarge => "ml.g6e.4xlarge",
            .ml_g6_e_8_xlarge => "ml.g6e.8xlarge",
            .ml_g6_e_12_xlarge => "ml.g6e.12xlarge",
            .ml_g6_e_16_xlarge => "ml.g6e.16xlarge",
            .ml_g6_e_24_xlarge => "ml.g6e.24xlarge",
            .ml_g6_e_48_xlarge => "ml.g6e.48xlarge",
            .ml_p4_d_24_xlarge => "ml.p4d.24xlarge",
            .ml_c7_g_large => "ml.c7g.large",
            .ml_c7_g_xlarge => "ml.c7g.xlarge",
            .ml_c7_g_2_xlarge => "ml.c7g.2xlarge",
            .ml_c7_g_4_xlarge => "ml.c7g.4xlarge",
            .ml_c7_g_8_xlarge => "ml.c7g.8xlarge",
            .ml_c7_g_12_xlarge => "ml.c7g.12xlarge",
            .ml_c7_g_16_xlarge => "ml.c7g.16xlarge",
            .ml_m6_g_large => "ml.m6g.large",
            .ml_m6_g_xlarge => "ml.m6g.xlarge",
            .ml_m6_g_2_xlarge => "ml.m6g.2xlarge",
            .ml_m6_g_4_xlarge => "ml.m6g.4xlarge",
            .ml_m6_g_8_xlarge => "ml.m6g.8xlarge",
            .ml_m6_g_12_xlarge => "ml.m6g.12xlarge",
            .ml_m6_g_16_xlarge => "ml.m6g.16xlarge",
            .ml_m6_gd_large => "ml.m6gd.large",
            .ml_m6_gd_xlarge => "ml.m6gd.xlarge",
            .ml_m6_gd_2_xlarge => "ml.m6gd.2xlarge",
            .ml_m6_gd_4_xlarge => "ml.m6gd.4xlarge",
            .ml_m6_gd_8_xlarge => "ml.m6gd.8xlarge",
            .ml_m6_gd_12_xlarge => "ml.m6gd.12xlarge",
            .ml_m6_gd_16_xlarge => "ml.m6gd.16xlarge",
            .ml_c6_g_large => "ml.c6g.large",
            .ml_c6_g_xlarge => "ml.c6g.xlarge",
            .ml_c6_g_2_xlarge => "ml.c6g.2xlarge",
            .ml_c6_g_4_xlarge => "ml.c6g.4xlarge",
            .ml_c6_g_8_xlarge => "ml.c6g.8xlarge",
            .ml_c6_g_12_xlarge => "ml.c6g.12xlarge",
            .ml_c6_g_16_xlarge => "ml.c6g.16xlarge",
            .ml_c6_gd_large => "ml.c6gd.large",
            .ml_c6_gd_xlarge => "ml.c6gd.xlarge",
            .ml_c6_gd_2_xlarge => "ml.c6gd.2xlarge",
            .ml_c6_gd_4_xlarge => "ml.c6gd.4xlarge",
            .ml_c6_gd_8_xlarge => "ml.c6gd.8xlarge",
            .ml_c6_gd_12_xlarge => "ml.c6gd.12xlarge",
            .ml_c6_gd_16_xlarge => "ml.c6gd.16xlarge",
            .ml_c6_gn_large => "ml.c6gn.large",
            .ml_c6_gn_xlarge => "ml.c6gn.xlarge",
            .ml_c6_gn_2_xlarge => "ml.c6gn.2xlarge",
            .ml_c6_gn_4_xlarge => "ml.c6gn.4xlarge",
            .ml_c6_gn_8_xlarge => "ml.c6gn.8xlarge",
            .ml_c6_gn_12_xlarge => "ml.c6gn.12xlarge",
            .ml_c6_gn_16_xlarge => "ml.c6gn.16xlarge",
            .ml_r6_g_large => "ml.r6g.large",
            .ml_r6_g_xlarge => "ml.r6g.xlarge",
            .ml_r6_g_2_xlarge => "ml.r6g.2xlarge",
            .ml_r6_g_4_xlarge => "ml.r6g.4xlarge",
            .ml_r6_g_8_xlarge => "ml.r6g.8xlarge",
            .ml_r6_g_12_xlarge => "ml.r6g.12xlarge",
            .ml_r6_g_16_xlarge => "ml.r6g.16xlarge",
            .ml_r6_gd_large => "ml.r6gd.large",
            .ml_r6_gd_xlarge => "ml.r6gd.xlarge",
            .ml_r6_gd_2_xlarge => "ml.r6gd.2xlarge",
            .ml_r6_gd_4_xlarge => "ml.r6gd.4xlarge",
            .ml_r6_gd_8_xlarge => "ml.r6gd.8xlarge",
            .ml_r6_gd_12_xlarge => "ml.r6gd.12xlarge",
            .ml_r6_gd_16_xlarge => "ml.r6gd.16xlarge",
            .ml_p4_de_24_xlarge => "ml.p4de.24xlarge",
            .ml_trn1_2_xlarge => "ml.trn1.2xlarge",
            .ml_trn1_32_xlarge => "ml.trn1.32xlarge",
            .ml_trn1_n_32_xlarge => "ml.trn1n.32xlarge",
            .ml_trn2_48_xlarge => "ml.trn2.48xlarge",
            .ml_inf2_xlarge => "ml.inf2.xlarge",
            .ml_inf2_8_xlarge => "ml.inf2.8xlarge",
            .ml_inf2_24_xlarge => "ml.inf2.24xlarge",
            .ml_inf2_48_xlarge => "ml.inf2.48xlarge",
            .ml_p5_48_xlarge => "ml.p5.48xlarge",
            .ml_p5_e_48_xlarge => "ml.p5e.48xlarge",
            .ml_p5_en_48_xlarge => "ml.p5en.48xlarge",
            .ml_m7_i_large => "ml.m7i.large",
            .ml_m7_i_xlarge => "ml.m7i.xlarge",
            .ml_m7_i_2_xlarge => "ml.m7i.2xlarge",
            .ml_m7_i_4_xlarge => "ml.m7i.4xlarge",
            .ml_m7_i_8_xlarge => "ml.m7i.8xlarge",
            .ml_m7_i_12_xlarge => "ml.m7i.12xlarge",
            .ml_m7_i_16_xlarge => "ml.m7i.16xlarge",
            .ml_m7_i_24_xlarge => "ml.m7i.24xlarge",
            .ml_m7_i_48_xlarge => "ml.m7i.48xlarge",
            .ml_c7_i_large => "ml.c7i.large",
            .ml_c7_i_xlarge => "ml.c7i.xlarge",
            .ml_c7_i_2_xlarge => "ml.c7i.2xlarge",
            .ml_c7_i_4_xlarge => "ml.c7i.4xlarge",
            .ml_c7_i_8_xlarge => "ml.c7i.8xlarge",
            .ml_c7_i_12_xlarge => "ml.c7i.12xlarge",
            .ml_c7_i_16_xlarge => "ml.c7i.16xlarge",
            .ml_c7_i_24_xlarge => "ml.c7i.24xlarge",
            .ml_c7_i_48_xlarge => "ml.c7i.48xlarge",
            .ml_r7_i_large => "ml.r7i.large",
            .ml_r7_i_xlarge => "ml.r7i.xlarge",
            .ml_r7_i_2_xlarge => "ml.r7i.2xlarge",
            .ml_r7_i_4_xlarge => "ml.r7i.4xlarge",
            .ml_r7_i_8_xlarge => "ml.r7i.8xlarge",
            .ml_r7_i_12_xlarge => "ml.r7i.12xlarge",
            .ml_r7_i_16_xlarge => "ml.r7i.16xlarge",
            .ml_r7_i_24_xlarge => "ml.r7i.24xlarge",
            .ml_r7_i_48_xlarge => "ml.r7i.48xlarge",
            .ml_c8_g_medium => "ml.c8g.medium",
            .ml_c8_g_large => "ml.c8g.large",
            .ml_c8_g_xlarge => "ml.c8g.xlarge",
            .ml_c8_g_2_xlarge => "ml.c8g.2xlarge",
            .ml_c8_g_4_xlarge => "ml.c8g.4xlarge",
            .ml_c8_g_8_xlarge => "ml.c8g.8xlarge",
            .ml_c8_g_12_xlarge => "ml.c8g.12xlarge",
            .ml_c8_g_16_xlarge => "ml.c8g.16xlarge",
            .ml_c8_g_24_xlarge => "ml.c8g.24xlarge",
            .ml_c8_g_48_xlarge => "ml.c8g.48xlarge",
            .ml_r7_gd_medium => "ml.r7gd.medium",
            .ml_r7_gd_large => "ml.r7gd.large",
            .ml_r7_gd_xlarge => "ml.r7gd.xlarge",
            .ml_r7_gd_2_xlarge => "ml.r7gd.2xlarge",
            .ml_r7_gd_4_xlarge => "ml.r7gd.4xlarge",
            .ml_r7_gd_8_xlarge => "ml.r7gd.8xlarge",
            .ml_r7_gd_12_xlarge => "ml.r7gd.12xlarge",
            .ml_r7_gd_16_xlarge => "ml.r7gd.16xlarge",
            .ml_m8_g_medium => "ml.m8g.medium",
            .ml_m8_g_large => "ml.m8g.large",
            .ml_m8_g_xlarge => "ml.m8g.xlarge",
            .ml_m8_g_2_xlarge => "ml.m8g.2xlarge",
            .ml_m8_g_4_xlarge => "ml.m8g.4xlarge",
            .ml_m8_g_8_xlarge => "ml.m8g.8xlarge",
            .ml_m8_g_12_xlarge => "ml.m8g.12xlarge",
            .ml_m8_g_16_xlarge => "ml.m8g.16xlarge",
            .ml_m8_g_24_xlarge => "ml.m8g.24xlarge",
            .ml_m8_g_48_xlarge => "ml.m8g.48xlarge",
            .ml_c6_in_large => "ml.c6in.large",
            .ml_c6_in_xlarge => "ml.c6in.xlarge",
            .ml_c6_in_2_xlarge => "ml.c6in.2xlarge",
            .ml_c6_in_4_xlarge => "ml.c6in.4xlarge",
            .ml_c6_in_8_xlarge => "ml.c6in.8xlarge",
            .ml_c6_in_12_xlarge => "ml.c6in.12xlarge",
            .ml_c6_in_16_xlarge => "ml.c6in.16xlarge",
            .ml_c6_in_24_xlarge => "ml.c6in.24xlarge",
            .ml_c6_in_32_xlarge => "ml.c6in.32xlarge",
            .ml_p6_b200_48_xlarge => "ml.p6-b200.48xlarge",
            .ml_p6_e_gb200_36_xlarge => "ml.p6e-gb200.36xlarge",
            .ml_p5_4_xlarge => "ml.p5.4xlarge",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
