pub const ResourceType = enum {
    training_job,
    experiment,
    experiment_trial,
    experiment_trial_component,
    endpoint,
    model,
    model_package,
    model_package_group,
    pipeline,
    pipeline_execution,
    feature_group,
    feature_metadata,
    image,
    image_version,
    project,
    hyper_parameter_tuning_job,
    model_card,
    pipeline_version,

    pub const json_field_names = .{
        .training_job = "TRAINING_JOB",
        .experiment = "EXPERIMENT",
        .experiment_trial = "EXPERIMENT_TRIAL",
        .experiment_trial_component = "EXPERIMENT_TRIAL_COMPONENT",
        .endpoint = "ENDPOINT",
        .model = "MODEL",
        .model_package = "MODEL_PACKAGE",
        .model_package_group = "MODEL_PACKAGE_GROUP",
        .pipeline = "PIPELINE",
        .pipeline_execution = "PIPELINE_EXECUTION",
        .feature_group = "FEATURE_GROUP",
        .feature_metadata = "FEATURE_METADATA",
        .image = "IMAGE",
        .image_version = "IMAGE_VERSION",
        .project = "PROJECT",
        .hyper_parameter_tuning_job = "HYPER_PARAMETER_TUNING_JOB",
        .model_card = "MODEL_CARD",
        .pipeline_version = "PIPELINE_VERSION",
    };
};
