pub const SecondaryStatus = enum {
    starting,
    launching_ml_instances,
    preparing_training_stack,
    downloading,
    downloading_training_image,
    training,
    uploading,
    stopping,
    stopped,
    max_runtime_exceeded,
    completed,
    failed,
    interrupted,
    max_wait_time_exceeded,
    updating,
    restarting,
    pending,

    pub const json_field_names = .{
        .starting = "STARTING",
        .launching_ml_instances = "LAUNCHING_ML_INSTANCES",
        .preparing_training_stack = "PREPARING_TRAINING_STACK",
        .downloading = "DOWNLOADING",
        .downloading_training_image = "DOWNLOADING_TRAINING_IMAGE",
        .training = "TRAINING",
        .uploading = "UPLOADING",
        .stopping = "STOPPING",
        .stopped = "STOPPED",
        .max_runtime_exceeded = "MAX_RUNTIME_EXCEEDED",
        .completed = "COMPLETED",
        .failed = "FAILED",
        .interrupted = "INTERRUPTED",
        .max_wait_time_exceeded = "MAX_WAIT_TIME_EXCEEDED",
        .updating = "UPDATING",
        .restarting = "RESTARTING",
        .pending = "PENDING",
    };
};
