const std = @import("std");

pub const TargetDevice = enum {
    lambda,
    ml_m4,
    ml_m5,
    ml_m6_g,
    ml_c4,
    ml_c5,
    ml_c6_g,
    ml_p2,
    ml_p3,
    ml_g4_dn,
    ml_inf1,
    ml_inf2,
    ml_trn1,
    ml_eia2,
    jetson_tx1,
    jetson_tx2,
    jetson_nano,
    jetson_xavier,
    rasp3_b,
    rasp4_b,
    imx8_qm,
    deeplens,
    rk3399,
    rk3288,
    aisage,
    sbe_c,
    qcs605,
    qcs603,
    sitara_am57_x,
    amba_cv2,
    amba_cv22,
    amba_cv25,
    x86_win32,
    x86_win64,
    coreml,
    jacinto_tda4_vm,
    imx8_mplus,

    pub const json_field_names = .{
        .lambda = "lambda",
        .ml_m4 = "ml_m4",
        .ml_m5 = "ml_m5",
        .ml_m6_g = "ml_m6g",
        .ml_c4 = "ml_c4",
        .ml_c5 = "ml_c5",
        .ml_c6_g = "ml_c6g",
        .ml_p2 = "ml_p2",
        .ml_p3 = "ml_p3",
        .ml_g4_dn = "ml_g4dn",
        .ml_inf1 = "ml_inf1",
        .ml_inf2 = "ml_inf2",
        .ml_trn1 = "ml_trn1",
        .ml_eia2 = "ml_eia2",
        .jetson_tx1 = "jetson_tx1",
        .jetson_tx2 = "jetson_tx2",
        .jetson_nano = "jetson_nano",
        .jetson_xavier = "jetson_xavier",
        .rasp3_b = "rasp3b",
        .rasp4_b = "rasp4b",
        .imx8_qm = "imx8qm",
        .deeplens = "deeplens",
        .rk3399 = "rk3399",
        .rk3288 = "rk3288",
        .aisage = "aisage",
        .sbe_c = "sbe_c",
        .qcs605 = "qcs605",
        .qcs603 = "qcs603",
        .sitara_am57_x = "sitara_am57x",
        .amba_cv2 = "amba_cv2",
        .amba_cv22 = "amba_cv22",
        .amba_cv25 = "amba_cv25",
        .x86_win32 = "x86_win32",
        .x86_win64 = "x86_win64",
        .coreml = "coreml",
        .jacinto_tda4_vm = "jacinto_tda4vm",
        .imx8_mplus = "imx8mplus",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .lambda => "lambda",
            .ml_m4 => "ml_m4",
            .ml_m5 => "ml_m5",
            .ml_m6_g => "ml_m6g",
            .ml_c4 => "ml_c4",
            .ml_c5 => "ml_c5",
            .ml_c6_g => "ml_c6g",
            .ml_p2 => "ml_p2",
            .ml_p3 => "ml_p3",
            .ml_g4_dn => "ml_g4dn",
            .ml_inf1 => "ml_inf1",
            .ml_inf2 => "ml_inf2",
            .ml_trn1 => "ml_trn1",
            .ml_eia2 => "ml_eia2",
            .jetson_tx1 => "jetson_tx1",
            .jetson_tx2 => "jetson_tx2",
            .jetson_nano => "jetson_nano",
            .jetson_xavier => "jetson_xavier",
            .rasp3_b => "rasp3b",
            .rasp4_b => "rasp4b",
            .imx8_qm => "imx8qm",
            .deeplens => "deeplens",
            .rk3399 => "rk3399",
            .rk3288 => "rk3288",
            .aisage => "aisage",
            .sbe_c => "sbe_c",
            .qcs605 => "qcs605",
            .qcs603 => "qcs603",
            .sitara_am57_x => "sitara_am57x",
            .amba_cv2 => "amba_cv2",
            .amba_cv22 => "amba_cv22",
            .amba_cv25 => "amba_cv25",
            .x86_win32 => "x86_win32",
            .x86_win64 => "x86_win64",
            .coreml => "coreml",
            .jacinto_tda4_vm => "jacinto_tda4vm",
            .imx8_mplus => "imx8mplus",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
