pub const TargetDevice = enum {
    lambda,
    ml_m4,
    ml_m5,
    ml_m6_g,
    ml_c4,
    ml_c5,
    ml_c6_g,
    ml_p2,
    ml_p3,
    ml_g4_dn,
    ml_inf1,
    ml_inf2,
    ml_trn1,
    ml_eia2,
    jetson_tx1,
    jetson_tx2,
    jetson_nano,
    jetson_xavier,
    rasp3_b,
    rasp4_b,
    imx8_qm,
    deeplens,
    rk3399,
    rk3288,
    aisage,
    sbe_c,
    qcs605,
    qcs603,
    sitara_am57_x,
    amba_cv2,
    amba_cv22,
    amba_cv25,
    x86_win32,
    x86_win64,
    coreml,
    jacinto_tda4_vm,
    imx8_mplus,

    pub const json_field_names = .{
        .lambda = "LAMBDA",
        .ml_m4 = "ML_M4",
        .ml_m5 = "ML_M5",
        .ml_m6_g = "ML_M6G",
        .ml_c4 = "ML_C4",
        .ml_c5 = "ML_C5",
        .ml_c6_g = "ML_C6G",
        .ml_p2 = "ML_P2",
        .ml_p3 = "ML_P3",
        .ml_g4_dn = "ML_G4DN",
        .ml_inf1 = "ML_INF1",
        .ml_inf2 = "ML_INF2",
        .ml_trn1 = "ML_TRN1",
        .ml_eia2 = "ML_EIA2",
        .jetson_tx1 = "JETSON_TX1",
        .jetson_tx2 = "JETSON_TX2",
        .jetson_nano = "JETSON_NANO",
        .jetson_xavier = "JETSON_XAVIER",
        .rasp3_b = "RASP3B",
        .rasp4_b = "RASP4B",
        .imx8_qm = "IMX8QM",
        .deeplens = "DEEPLENS",
        .rk3399 = "RK3399",
        .rk3288 = "RK3288",
        .aisage = "AISAGE",
        .sbe_c = "SBE_C",
        .qcs605 = "QCS605",
        .qcs603 = "QCS603",
        .sitara_am57_x = "SITARA_AM57X",
        .amba_cv2 = "AMBA_CV2",
        .amba_cv22 = "AMBA_CV22",
        .amba_cv25 = "AMBA_CV25",
        .x86_win32 = "X86_WIN32",
        .x86_win64 = "X86_WIN64",
        .coreml = "COREML",
        .jacinto_tda4_vm = "JACINTO_TDA4VM",
        .imx8_mplus = "IMX8MPLUS",
    };
};
