pub const TrackingServerStatus = enum {
    creating,
    created,
    create_failed,
    updating,
    updated,
    update_failed,
    deleting,
    delete_failed,
    stopping,
    stopped,
    stop_failed,
    starting,
    started,
    start_failed,
    maintenance_in_progress,
    maintenance_complete,
    maintenance_failed,

    pub const json_field_names = .{
        .creating = "CREATING",
        .created = "CREATED",
        .create_failed = "CREATE_FAILED",
        .updating = "UPDATING",
        .updated = "UPDATED",
        .update_failed = "UPDATE_FAILED",
        .deleting = "DELETING",
        .delete_failed = "DELETE_FAILED",
        .stopping = "STOPPING",
        .stopped = "STOPPED",
        .stop_failed = "STOP_FAILED",
        .starting = "STARTING",
        .started = "STARTED",
        .start_failed = "START_FAILED",
        .maintenance_in_progress = "MAINTENANCE_IN_PROGRESS",
        .maintenance_complete = "MAINTENANCE_COMPLETE",
        .maintenance_failed = "MAINTENANCE_FAILED",
    };
};
