/// The workspace settings for the SageMaker Canvas application.
pub const WorkspaceSettings = struct {
    /// The Amazon S3 bucket used to store artifacts generated by Canvas. Updating
    /// the Amazon S3 location impacts existing configuration settings, and Canvas
    /// users no longer have access to their artifacts. Canvas users must log out
    /// and log back in to apply the new location.
    s3_artifact_path: ?[]const u8,

    /// The Amazon Web Services Key Management Service (KMS) encryption key ID that
    /// is used to encrypt artifacts generated by Canvas in the Amazon S3 bucket.
    s3_kms_key_id: ?[]const u8,

    pub const json_field_names = .{
        .s3_artifact_path = "S3ArtifactPath",
        .s3_kms_key_id = "S3KmsKeyId",
    };
};
