const std = @import("std");

pub const CountryCode = enum {
    ac,
    ad,
    ae,
    af,
    ag,
    ai,
    al,
    am,
    an,
    ao,
    aq,
    ar,
    as,
    at,
    au,
    aw,
    ax,
    az,
    ba,
    bb,
    bd,
    be,
    bf,
    bg,
    bh,
    bi,
    bj,
    bl,
    bm,
    bn,
    bo,
    bq,
    br,
    bs,
    bt,
    bv,
    bw,
    by,
    bz,
    ca,
    cc,
    cd,
    cf,
    cg,
    ch,
    ci,
    ck,
    cl,
    cm,
    cn,
    co,
    cr,
    cu,
    cv,
    cw,
    cx,
    cy,
    cz,
    de,
    dj,
    dk,
    dm,
    do,
    dz,
    ec,
    ee,
    eg,
    eh,
    er,
    es,
    et,
    fi,
    fj,
    fk,
    fm,
    fo,
    fr,
    ga,
    gb,
    gd,
    ge,
    gf,
    gg,
    gh,
    gi,
    gl,
    gm,
    gn,
    gp,
    gq,
    gr,
    gs,
    gt,
    gu,
    gw,
    gy,
    hk,
    hm,
    hn,
    hr,
    ht,
    hu,
    id,
    ie,
    il,
    im,
    in,
    io,
    iq,
    ir,
    is,
    it,
    je,
    jm,
    jo,
    jp,
    ke,
    kg,
    kh,
    ki,
    km,
    kn,
    kp,
    kr,
    kw,
    ky,
    kz,
    la,
    lb,
    lc,
    li,
    lk,
    lr,
    ls,
    lt,
    lu,
    lv,
    ly,
    ma,
    mc,
    md,
    me,
    mf,
    mg,
    mh,
    mk,
    ml,
    mm,
    mn,
    mo,
    mp,
    mq,
    mr,
    ms,
    mt,
    mu,
    mv,
    mw,
    mx,
    my,
    mz,
    na,
    nc,
    ne,
    nf,
    ng,
    ni,
    nl,
    no,
    np,
    nr,
    nu,
    nz,
    om,
    pa,
    pe,
    pf,
    pg,
    ph,
    pk,
    pl,
    pm,
    pn,
    pr,
    ps,
    pt,
    pw,
    py,
    qa,
    re,
    ro,
    rs,
    ru,
    rw,
    sa,
    sb,
    sc,
    sd,
    se,
    sg,
    sh,
    si,
    sj,
    sk,
    sl,
    sm,
    sn,
    so,
    sr,
    ss,
    st,
    sv,
    sx,
    sy,
    sz,
    tc,
    td,
    tf,
    tg,
    th,
    tj,
    tk,
    tl,
    tm,
    tn,
    to,
    tp,
    tr,
    tt,
    tv,
    tw,
    tz,
    ua,
    ug,
    us,
    uy,
    uz,
    va,
    vc,
    ve,
    vg,
    vi,
    vn,
    vu,
    wf,
    ws,
    ye,
    yt,
    za,
    zm,
    zw,

    pub const json_field_names = .{
        .ac = "AC",
        .ad = "AD",
        .ae = "AE",
        .af = "AF",
        .ag = "AG",
        .ai = "AI",
        .al = "AL",
        .am = "AM",
        .an = "AN",
        .ao = "AO",
        .aq = "AQ",
        .ar = "AR",
        .as = "AS",
        .at = "AT",
        .au = "AU",
        .aw = "AW",
        .ax = "AX",
        .az = "AZ",
        .ba = "BA",
        .bb = "BB",
        .bd = "BD",
        .be = "BE",
        .bf = "BF",
        .bg = "BG",
        .bh = "BH",
        .bi = "BI",
        .bj = "BJ",
        .bl = "BL",
        .bm = "BM",
        .bn = "BN",
        .bo = "BO",
        .bq = "BQ",
        .br = "BR",
        .bs = "BS",
        .bt = "BT",
        .bv = "BV",
        .bw = "BW",
        .by = "BY",
        .bz = "BZ",
        .ca = "CA",
        .cc = "CC",
        .cd = "CD",
        .cf = "CF",
        .cg = "CG",
        .ch = "CH",
        .ci = "CI",
        .ck = "CK",
        .cl = "CL",
        .cm = "CM",
        .cn = "CN",
        .co = "CO",
        .cr = "CR",
        .cu = "CU",
        .cv = "CV",
        .cw = "CW",
        .cx = "CX",
        .cy = "CY",
        .cz = "CZ",
        .de = "DE",
        .dj = "DJ",
        .dk = "DK",
        .dm = "DM",
        .do = "DO",
        .dz = "DZ",
        .ec = "EC",
        .ee = "EE",
        .eg = "EG",
        .eh = "EH",
        .er = "ER",
        .es = "ES",
        .et = "ET",
        .fi = "FI",
        .fj = "FJ",
        .fk = "FK",
        .fm = "FM",
        .fo = "FO",
        .fr = "FR",
        .ga = "GA",
        .gb = "GB",
        .gd = "GD",
        .ge = "GE",
        .gf = "GF",
        .gg = "GG",
        .gh = "GH",
        .gi = "GI",
        .gl = "GL",
        .gm = "GM",
        .gn = "GN",
        .gp = "GP",
        .gq = "GQ",
        .gr = "GR",
        .gs = "GS",
        .gt = "GT",
        .gu = "GU",
        .gw = "GW",
        .gy = "GY",
        .hk = "HK",
        .hm = "HM",
        .hn = "HN",
        .hr = "HR",
        .ht = "HT",
        .hu = "HU",
        .id = "ID",
        .ie = "IE",
        .il = "IL",
        .im = "IM",
        .in = "IN",
        .io = "IO",
        .iq = "IQ",
        .ir = "IR",
        .is = "IS",
        .it = "IT",
        .je = "JE",
        .jm = "JM",
        .jo = "JO",
        .jp = "JP",
        .ke = "KE",
        .kg = "KG",
        .kh = "KH",
        .ki = "KI",
        .km = "KM",
        .kn = "KN",
        .kp = "KP",
        .kr = "KR",
        .kw = "KW",
        .ky = "KY",
        .kz = "KZ",
        .la = "LA",
        .lb = "LB",
        .lc = "LC",
        .li = "LI",
        .lk = "LK",
        .lr = "LR",
        .ls = "LS",
        .lt = "LT",
        .lu = "LU",
        .lv = "LV",
        .ly = "LY",
        .ma = "MA",
        .mc = "MC",
        .md = "MD",
        .me = "ME",
        .mf = "MF",
        .mg = "MG",
        .mh = "MH",
        .mk = "MK",
        .ml = "ML",
        .mm = "MM",
        .mn = "MN",
        .mo = "MO",
        .mp = "MP",
        .mq = "MQ",
        .mr = "MR",
        .ms = "MS",
        .mt = "MT",
        .mu = "MU",
        .mv = "MV",
        .mw = "MW",
        .mx = "MX",
        .my = "MY",
        .mz = "MZ",
        .na = "NA",
        .nc = "NC",
        .ne = "NE",
        .nf = "NF",
        .ng = "NG",
        .ni = "NI",
        .nl = "NL",
        .no = "NO",
        .np = "NP",
        .nr = "NR",
        .nu = "NU",
        .nz = "NZ",
        .om = "OM",
        .pa = "PA",
        .pe = "PE",
        .pf = "PF",
        .pg = "PG",
        .ph = "PH",
        .pk = "PK",
        .pl = "PL",
        .pm = "PM",
        .pn = "PN",
        .pr = "PR",
        .ps = "PS",
        .pt = "PT",
        .pw = "PW",
        .py = "PY",
        .qa = "QA",
        .re = "RE",
        .ro = "RO",
        .rs = "RS",
        .ru = "RU",
        .rw = "RW",
        .sa = "SA",
        .sb = "SB",
        .sc = "SC",
        .sd = "SD",
        .se = "SE",
        .sg = "SG",
        .sh = "SH",
        .si = "SI",
        .sj = "SJ",
        .sk = "SK",
        .sl = "SL",
        .sm = "SM",
        .sn = "SN",
        .so = "SO",
        .sr = "SR",
        .ss = "SS",
        .st = "ST",
        .sv = "SV",
        .sx = "SX",
        .sy = "SY",
        .sz = "SZ",
        .tc = "TC",
        .td = "TD",
        .tf = "TF",
        .tg = "TG",
        .th = "TH",
        .tj = "TJ",
        .tk = "TK",
        .tl = "TL",
        .tm = "TM",
        .tn = "TN",
        .to = "TO",
        .tp = "TP",
        .tr = "TR",
        .tt = "TT",
        .tv = "TV",
        .tw = "TW",
        .tz = "TZ",
        .ua = "UA",
        .ug = "UG",
        .us = "US",
        .uy = "UY",
        .uz = "UZ",
        .va = "VA",
        .vc = "VC",
        .ve = "VE",
        .vg = "VG",
        .vi = "VI",
        .vn = "VN",
        .vu = "VU",
        .wf = "WF",
        .ws = "WS",
        .ye = "YE",
        .yt = "YT",
        .za = "ZA",
        .zm = "ZM",
        .zw = "ZW",
    };

    pub fn wireName(self: @This()) []const u8 {
        return switch (self) {
            .ac => "AC",
            .ad => "AD",
            .ae => "AE",
            .af => "AF",
            .ag => "AG",
            .ai => "AI",
            .al => "AL",
            .am => "AM",
            .an => "AN",
            .ao => "AO",
            .aq => "AQ",
            .ar => "AR",
            .as => "AS",
            .at => "AT",
            .au => "AU",
            .aw => "AW",
            .ax => "AX",
            .az => "AZ",
            .ba => "BA",
            .bb => "BB",
            .bd => "BD",
            .be => "BE",
            .bf => "BF",
            .bg => "BG",
            .bh => "BH",
            .bi => "BI",
            .bj => "BJ",
            .bl => "BL",
            .bm => "BM",
            .bn => "BN",
            .bo => "BO",
            .bq => "BQ",
            .br => "BR",
            .bs => "BS",
            .bt => "BT",
            .bv => "BV",
            .bw => "BW",
            .by => "BY",
            .bz => "BZ",
            .ca => "CA",
            .cc => "CC",
            .cd => "CD",
            .cf => "CF",
            .cg => "CG",
            .ch => "CH",
            .ci => "CI",
            .ck => "CK",
            .cl => "CL",
            .cm => "CM",
            .cn => "CN",
            .co => "CO",
            .cr => "CR",
            .cu => "CU",
            .cv => "CV",
            .cw => "CW",
            .cx => "CX",
            .cy => "CY",
            .cz => "CZ",
            .de => "DE",
            .dj => "DJ",
            .dk => "DK",
            .dm => "DM",
            .do => "DO",
            .dz => "DZ",
            .ec => "EC",
            .ee => "EE",
            .eg => "EG",
            .eh => "EH",
            .er => "ER",
            .es => "ES",
            .et => "ET",
            .fi => "FI",
            .fj => "FJ",
            .fk => "FK",
            .fm => "FM",
            .fo => "FO",
            .fr => "FR",
            .ga => "GA",
            .gb => "GB",
            .gd => "GD",
            .ge => "GE",
            .gf => "GF",
            .gg => "GG",
            .gh => "GH",
            .gi => "GI",
            .gl => "GL",
            .gm => "GM",
            .gn => "GN",
            .gp => "GP",
            .gq => "GQ",
            .gr => "GR",
            .gs => "GS",
            .gt => "GT",
            .gu => "GU",
            .gw => "GW",
            .gy => "GY",
            .hk => "HK",
            .hm => "HM",
            .hn => "HN",
            .hr => "HR",
            .ht => "HT",
            .hu => "HU",
            .id => "ID",
            .ie => "IE",
            .il => "IL",
            .im => "IM",
            .in => "IN",
            .io => "IO",
            .iq => "IQ",
            .ir => "IR",
            .is => "IS",
            .it => "IT",
            .je => "JE",
            .jm => "JM",
            .jo => "JO",
            .jp => "JP",
            .ke => "KE",
            .kg => "KG",
            .kh => "KH",
            .ki => "KI",
            .km => "KM",
            .kn => "KN",
            .kp => "KP",
            .kr => "KR",
            .kw => "KW",
            .ky => "KY",
            .kz => "KZ",
            .la => "LA",
            .lb => "LB",
            .lc => "LC",
            .li => "LI",
            .lk => "LK",
            .lr => "LR",
            .ls => "LS",
            .lt => "LT",
            .lu => "LU",
            .lv => "LV",
            .ly => "LY",
            .ma => "MA",
            .mc => "MC",
            .md => "MD",
            .me => "ME",
            .mf => "MF",
            .mg => "MG",
            .mh => "MH",
            .mk => "MK",
            .ml => "ML",
            .mm => "MM",
            .mn => "MN",
            .mo => "MO",
            .mp => "MP",
            .mq => "MQ",
            .mr => "MR",
            .ms => "MS",
            .mt => "MT",
            .mu => "MU",
            .mv => "MV",
            .mw => "MW",
            .mx => "MX",
            .my => "MY",
            .mz => "MZ",
            .na => "NA",
            .nc => "NC",
            .ne => "NE",
            .nf => "NF",
            .ng => "NG",
            .ni => "NI",
            .nl => "NL",
            .no => "NO",
            .np => "NP",
            .nr => "NR",
            .nu => "NU",
            .nz => "NZ",
            .om => "OM",
            .pa => "PA",
            .pe => "PE",
            .pf => "PF",
            .pg => "PG",
            .ph => "PH",
            .pk => "PK",
            .pl => "PL",
            .pm => "PM",
            .pn => "PN",
            .pr => "PR",
            .ps => "PS",
            .pt => "PT",
            .pw => "PW",
            .py => "PY",
            .qa => "QA",
            .re => "RE",
            .ro => "RO",
            .rs => "RS",
            .ru => "RU",
            .rw => "RW",
            .sa => "SA",
            .sb => "SB",
            .sc => "SC",
            .sd => "SD",
            .se => "SE",
            .sg => "SG",
            .sh => "SH",
            .si => "SI",
            .sj => "SJ",
            .sk => "SK",
            .sl => "SL",
            .sm => "SM",
            .sn => "SN",
            .so => "SO",
            .sr => "SR",
            .ss => "SS",
            .st => "ST",
            .sv => "SV",
            .sx => "SX",
            .sy => "SY",
            .sz => "SZ",
            .tc => "TC",
            .td => "TD",
            .tf => "TF",
            .tg => "TG",
            .th => "TH",
            .tj => "TJ",
            .tk => "TK",
            .tl => "TL",
            .tm => "TM",
            .tn => "TN",
            .to => "TO",
            .tp => "TP",
            .tr => "TR",
            .tt => "TT",
            .tv => "TV",
            .tw => "TW",
            .tz => "TZ",
            .ua => "UA",
            .ug => "UG",
            .us => "US",
            .uy => "UY",
            .uz => "UZ",
            .va => "VA",
            .vc => "VC",
            .ve => "VE",
            .vg => "VG",
            .vi => "VI",
            .vn => "VN",
            .vu => "VU",
            .wf => "WF",
            .ws => "WS",
            .ye => "YE",
            .yt => "YT",
            .za => "ZA",
            .zm => "ZM",
            .zw => "ZW",
        };
    }

    pub fn fromWireName(str: []const u8) ?@This() {
        inline for (std.meta.fields(@TypeOf(json_field_names))) |field| {
            if (std.mem.eql(u8, str, @field(json_field_names, field.name))) {
                return @field(@This(), field.name);
            }
        }
        return std.meta.stringToEnum(@This(), str);
    }
};
